### ISSUE TITLE
".friends remove all" command

### ISSUE THREAD

**Issue by MrAljabal** [Wurst-Imperium/Wurst-Client#1]
I suggest for you to add new Friends list GUI, so i could easily add and remove my friends.
Also, I suggest to add a new command to remove all my friends: ```.friends remove *```.

**Comment by Alexander01998** [comment]
> I suggest for you to add new Friends list GUI.
> So i could easily remove my friends and add.

There already is an easy way to manage friends by middle-clicking players. And it's propably easier than typing their names into a GUI.

> Also, I suggest to add a new command to remove all my friends: ```.friends remove *```.

This one sounds like a good idea though.

**Comment by MrAljabal** [comment]
I know that way of managing friends.
But i need the GUI for games like Annihilation in Shotbow Network so we could add all of our teammates without following them, Like if you pressed Add, You'd see all players in the server, With an add button infront of their names.

**Comment by Alexander01998** [comment]
> Like if you pressed Add, you'd see all players in the server with an add button in front of their names.

This can just as well be done by typing ```.friends add ```, adding the first few letters of the name and auto-completing it by pressing tab.

**Comment by OMGchangeMYusername** [comment]
we'd love to change the ( . ) coz i play with my account <i don't use alts
but sometimes you need to type . at the beginning of the msg
for example i once played vampirez game and all of them are saying: everyone type .legit or .nohack
and when not in big servers like hypixel you'll find people saying you have to type anything with ( . ) at first..

**Comment by OMGchangeMYusername** [comment]
btw can you develop a hack for cops N crims :3
coz i feel that a good coder can, you know you might identify what is the recoil for the guns and maybe disable it :)
also if you add an auto armor and chest stealer that would be the greatest client!

**Comment by GeorgeP05** [comment]
if you can forceop with out huthme

**Comment by Alexander01998** [comment]
I changed my mind on this one. If you really use the friends system for your friends, you will never need to remove all of them at once.

**Comment by MorganPlaysMC** [comment]
**Test**

**Comment by MorganPlaysMC** [comment]
*t*

**Comment by MorganPlaysMC** [comment]
***h***

**Comment by MorganPlaysMC** [comment]
****h**
