### ISSUE TITLE
OPTIFINE!

### ISSUE THREAD

**Issue by NinjaYouBro** [Wurst-Imperium/Wurst-Client#10]
This is a must have adding Optifine will allow users with low end computers you this client with ease. 
I have Optifine on my other clients and I get around 50-60 FPS but on this one I only get around 14-16.  Pleas add this.

**Comment by Alexander01998** [comment]
Duplicate: #2

**Comment by rasmusolle** [comment]
Idea: making a verson with optifine, and one without
