### ISSUE TITLE
NearChestChecker

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1000]
If you are nearby a chest max. 5 blocks. It opens the chest (but the player doesnt see chest gui). if the chest is empty wurst higlights the chest red. Else higlights the chest blue. If auto steal enabled steals everything. And the most comfortable thing: you can chat, move and jump when wst looks chest.

**Comment by OMGchangeMYusername** [comment]
same logic as InventoryWalk?

**Comment by OMGchangeMYusername** [comment]
That would look so obvious,i'm not completely against this,but isn't this the same as #216 in logic?


dam this number tho,i once thought i'd think of something to nail this..

**Comment by 1337HaxorKiddie** [comment]
I don´t think that´s possible, thinks like moving, ok.. some other Client have it(InventoryMove). But Hide GUI, Move with Mouse and Chatting while Chest Stealing is very difficult to code i think.

**Comment by Meylama** [comment]
@1337HaxorKiddie it is possible... there are already 2 clients with this feature... (the feature is called "ChestAura" in this clients.)

**Comment by 1337HaxorKiddie** [comment]
I know this too Clients but in the Clients the GUI is visible and you can't chat. Chest Aura means only, that the chests will be oppened without looking at it.

**Comment by Meylama** [comment]
Yes, but it should be possible.
