### ISSUE TITLE
Inventory Clearer

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#1008]
So yeah. I accidently used the crash chest on myself so can you make a thing that clears ur inv when u join the server or tips to get rid of it

**Comment by scriptinator** [comment]
If you can stay in the server for about a minute use .drop if not ask the server admin to delete your inventory files or use another account.

**Comment by Alexander01998** [comment]
It's impossible. The only way to "unban" someone from CrashChest is to delete their player data from the server.
So unless the server owner is willing to do that, you have to use a different account from now on.
