### ISSUE TITLE
Pass Word Cracker Help

### ISSUE THREAD

**Issue by jacobwatts9** [Wurst-Imperium/Wurst-Client#1009]
So I love using Wurst it is the best, anyways on this server I have been trying to cheat I used the password cracker for every admin on the server and owner. It Has not been finding the passwords for me. So are the password preset or random or same every time. Is there anyway I can get a better chance

**Comment by Orcunegeacar** [comment]
You can search best passwords in the Internet. Copy them and select the text file When you are in Force OP (Password Cracker)

**Comment by GummiBoat** [comment]
There are enough password lists out there. Use one instead of the Default-Wurst one. And you should use a list, that's in your language.

**Comment by jacobwatts9** [comment]
Does anyone know of a good txt file because I found one and I still have no luck :{

**Comment by UnidentifiedProfile** [comment]
@jacobwatts9 
http://www.mediafire.com/view/avk7f1w822l6n56/10k_most_common.txt
