### ISSUE TITLE
Op-Sign Crashes in SinglePlayer

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#1010]
Op-Sign crashes my minecraft in single-player. I created a NEW world in Wurst and tried to use op sign. It crashes. And It freeze. The client's name is turning to Minecraft 1.8 from Wurst.
![image](https://cloud.githubusercontent.com/assets/11218527/8269244/d6429936-17aa-11e5-8130-037bc0fa4a82.png)

**Comment by scriptinator** [comment]
Crash log/output?

**Comment by GummiBoat** [comment]
OP-Sign is not supposed to work in Single-Player. Probably it's crashing because of that.

**Comment by Huanjohn** [comment]
@GummiBoat Still, it shouldn't cause a crash in single-player mode.

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.

**Comment by Orcunegeacar** [comment]
It's freezing. There is no crash log. It's not openning launcher

**Comment by Alexander01998** [comment]
> It's not openning launcher

See: #984

**Comment by Orcunegeacar** [comment]
I don't know how the client fix the problem itself. I created a sign. Code was /say hello. It worked! I guess I was runnig a lot of program. RAM wasn't have any space so it crashed. I needed a free space. There is no crash log actually because it  didn't crash :smile:  Thanks for your time guys. I created virtual memory to my harddisk. All freezing was for no space. I have no problem now.

**Comment by OMGchangeMYusername** [comment]
Glad for you :D
