### ISSUE TITLE
Flight + Jetpack = :(

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1011]
So with flight + Jetpack enable acsending is very slow. My flight speed is set to 5, I activate jetpack, = :(

**Comment by GummiBoat** [comment]
Well, what do you expect? You activate two different versions of "Flying" at once. I don't even know why you should use Flight together with Jetpack..

**Comment by WurstContributer** [comment]
k

**Comment by Alexander01998** [comment]
Then it might be a good idea to make Flight & Jetpack disable each other automatically, just like the different Nukers and Killauras do.

**Comment by WurstContributor** [comment]
Yay!
