### ISSUE TITLE
Book Op Help

### ISSUE THREAD

**Issue by jacobwatts9** [Wurst-Imperium/Wurst-Client#1012]
So you know how you can use that book hack to get op. When I put in the link and give it to people they say it does not work what is the problem, am I doing the whole thing wrong?

**Comment by WurstContributer** [comment]
Duplicate:#763 
https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67
