### ISSUE TITLE
Altmanger Issue

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#1013]
With a newly added alt (Premium) It does not allow you to log into it. Flashes red as if alt is not working

**Comment by Nitrogen-Dioxide** [comment]
The login server banned you, because you tried too many alts. It will take ~4 hours to it unban you.

To bypass that, use a proxy or vpn.

**Comment by WurstContributer** [comment]
I only put in cracked ones and added 1 new premium alt -_-

**Comment by WurstContributer** [comment]
I can click on my main account and it works

**Comment by Alexander01998** [comment]
> I can click on my main account and it works

Some Minecraft accounts are broken and just wont let you log in, even if you have the correct password.

**Comment by WurstContributer** [comment]
Well it can find the skin/username
