### ISSUE TITLE
Op Signs doesn't work

### ISSUE THREAD

**Issue by superleo1** [Wurst-Imperium/Wurst-Client#1014]
I wanted to try the Op Signs on a server, but they didn't worked. So I joined an other server but it didn't work too! Can u fix it please? Maybe it doesn't work on Spigot?

**Comment by superleo1** [comment]
Are u from Germany?

**Comment by OMGchangeMYusername** [comment]
> OP-Sign: You need creative Mode. Give yourself the Sign. Take it from the shoes-slot. Place it. Rightclick it. Done. (Only works on Vanilla 1.8.5 and versions before that.)
-GummiBoat

In addition,i think Spigot and Bukkit have fixed it,you can use the Server Finder to find Vanilla servers

**Comment by superleo1** [comment]
Okay thanks u

**Comment by OMGchangeMYusername** [comment]
No problem :)
and please search the issues whenever you want to report or suggest something,a lot of duplicate issues are happening..
