### ISSUE TITLE
Minecraft crashing on Start

### ISSUE THREAD

**Issue by Dracer0185** [Wurst-Imperium/Wurst-Client#1016]
My Minecraft crashes 90% of the times and when it doesnt crash instantly it freezes in the Main Menu and crashes aswell. No crashlog created
Any Help?

Wurst Version : 1.15

**Comment by Alexander01998** [comment]
See #984 for how to get the crash log.

**Comment by Dracer0185** [comment]
It crashes aswell.
![21-06-2015-20-25-30](https://cloud.githubusercontent.com/assets/11979205/8272838/c67163a8-1853-11e5-958b-63812f1747db.PNG)

**Comment by GummiBoat** [comment]
No, the Keyboard layout doesn't matter. What are you system details? (Java Version, OS (Windows Version) etc.)

**Comment by Dracer0185** [comment]
@GummiBoat  I am on Java Version : 8 Update 25 (Build 1.8.0_25-b18) on a Windows 7 Ultimate PC.
My Minecraft is running fine aswell just not the Wurst Client.

**Comment by Alexander01998** [comment]
Do you have a weird / old / broken graphics card or processor?

**Comment by Dracer0185** [comment]
@Alexander01998  I've got an i7 Processor and a NVIDIA GeForce GTX 780.

**Comment by Dracer0185** [comment]
Is there maybe any JVM Arguments i need to have for it to work?

**Comment by GummiBoat** [comment]
What are your Profile Settings? (Just take a screenshot from your profiles window)

**Comment by Dracer0185** [comment]
![minecraftprofilesettings](https://cloud.githubusercontent.com/assets/11979205/8272913/ecf54870-1856-11e5-90cf-e9ad0bd55489.PNG)

**Comment by Dracer0185** [comment]
Everytime i start my game with the Wurst release it creates another Wurst-natives folder in \versions\Wurst\

**Comment by Dracer0185** [comment]
I fixed it by settings automaximize to false in \.minecraft\wurst\automaximize.txt

**Comment by Alexander01998** [comment]
Wurst no longer uses TXT files for its settings. Changing the old TXT files has no effect.

**Comment by Dracer0185** [comment]
Well it worked after for me so im happy :3
