### ISSUE TITLE
Why can I not use FastEat & Regen on some servers?

### ISSUE THREAD

**Issue by BUZZERD85** [Wurst-Imperium/Wurst-Client#1018]
fast eat and regen used to help me fight but they don't work anymore when I eat it dosnt fill my health fully up plz fix I relie mostly on this hack

**Comment by GummiBoat** [comment]
There are a few requirements for Regen to work.Your health needs to be able to regenerate. If that's not the case, even Regen can't heal you. That counts for your food status aswell. (You'll only regenerate Health until you have lost 1 complete food symbol.) And if your Server has installed NoCheat+, Regen won't work (unless the NoCheat+ version is too old.)
