### ISSUE TITLE
Crash after hitting a mob

### ISSUE THREAD

**Issue by MrCraftLt** [Wurst-Imperium/Wurst-Client#1019]
when i connect then i join server next my minecraft crashes

**Comment by MrCraftLt** [comment]
when i connect then i join server next my minecraft crashes

**Comment by GummiBoat** [comment]
>When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:
```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```
-Alexander01998

Could you also please add the **complete** part above "A detailed walkthrough of the error, its code path and all known details is as follows:"?

And change the title. There is always a reason, WHY Minecraft crashes. Thanks :smiley:

**Comment by mcccs** [comment]
Please review the [contributing guidelines](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for this issue and fix the title

**Comment by Alexander01998** [comment]
This crash log is incomplete and cannot be used to find the source of your problem.

Please include the complete crash log and a more detailed description of what you did before the crash occurred.

**Comment by WurstContributer** [comment]
I discomfirm. I have never experienced this.
