### ISSUE TITLE
item mod

### ISSUE THREAD

**Issue by weshuiz13** [Wurst-Imperium/Wurst-Client#1023]
just like how the chest exploid works it gives you a achest but now a new button on the click gui
when you press ikt it opens a axe file that asks for a item/block id whn i enter the id and press on the button it will give me the block/item id i enterd to force give it use the same way as the chest

**Comment by GummiBoat** [comment]
# *Duplicate: #342*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
