### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#1024]
So I want to hit players + Passive mobs but i cant. So can you turn it into a checkbox thingy?

**Comment by OMGchangeMYusername** [comment]
#23.

**Comment by OMGchangeMYusername** [comment]
oh it was moved into #112 
but yeah you should put a little effort on searching..
i mostly remember,because i'm one of the first followers to this repo xD
i think i'm the first ? @Alexander01998

**Comment by WurstContributer** [comment]
k
