### ISSUE TITLE
Damage Support for any ID selections

### ISSUE THREAD

**Issue by GummiBoat** [Wurst-Imperium/Wurst-Client#1025]
### What does this mean?

There are a few mods, which support ID selection, like `Search`, `Nuker`, `X-Ray`, etc. I would like, that these selections support damage values as well. (Different Stone, Wood, Wool, Slabs, Glass, Quarz, Crops etc.) 

### Why?

This could be useful for extra-specific nuking, advanced searching, or even if you want that your X-Ray shows specific blocks.

Thanks for reading.

**Comment by OMGchangeMYusername** [comment]
Yet another Nuker thing..
I didn't completely get what you meant,but i think he should work on #112 and #748 #596  #784 etc..
i mean,this might be so goood for nuker and such,but there are tons of other mods that need to be implemented as fast as possible.

**Comment by GummiBoat** [comment]
It's not only for Nuker ^^ But I clearly understand your opinion, I didn't said that he had to implement it "RIGHT NOW ON THE POINT WURST 1.16 #YOLO!".

ERMAHGERD (╯°□°）╯︵ ┻━┻
