### ISSUE TITLE
Sessionstealer (Accountstealer)

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1029]
Garploit 1.3 has a Sessionstealer :/ can this be added to wurst too?
https://www.youtube.com/watch?v=NsOGHuPn7Mg
30:12

**Comment by OMGchangeMYusername** [comment]
Didn't watch the vid,and not willing to,but this is illegal.
why would you steal other people's accounts? they paid for it,seriously it's ok to use alts since a lot of them stopped playing minecraft and stuff,but Wurst stealing other accounts is so ugly.

**Comment by Alexander01998** [comment]
> 30:12

That's the end of the video.

**Comment by OMGchangeMYusername** [comment]
lol,you sure have time to watch the whole vid tho..

**Comment by ravenje** [comment]
Fail. 3:12

**Comment by OMGchangeMYusername** [comment]
@ravenje a little tip while we're at it,you can give us the link and it'll start from 3:12 automatically by using the share button and :white_check_mark: the "start at" button :+1: http://puu.sh/iAg5K/b11f907e56.png
[Here's the link] (https://youtu.be/NsOGHuPn7Mg?t=3m12s) that starts at 3:12

**Comment by GlitchHead** [comment]
well time to change my password to change my session id.
also this is not stealing it its just logging into the player with there session id.

**Comment by GlitchHead** [comment]
Also it seems you can still get the session id login part from the code because it has a "premium login" button at start so that means the premium features are in the client still.

**Comment by GlitchHead** [comment]
[3:30](https://www.youtube.com/watch?v=NsOGHuPn7Mg&feature=youtu.be&t=3m30s) at that time he says its only valid until the player logs in again. Making this useless unless you need a alt for like 3 seconds or you somehow get a servers owner session ID.

**Comment by mcccs** [comment]
NO I don't want this. Im very Bighearted! Please disconfirm :-1:

**Comment by GummiBoat** [comment]
@GlitchHead No, that's a little different. You know, that in Minecraft, you already are logged in automatically, if you start the launcher. But if you click on "Log out", you have to Log in again, and only that will give you a completely new session Id. So, as long as the other person doesn't log in again (on any computer), you'll be able to use the account. So the best thing to do, is to log out and in again, and then no Crash log on the internet will be valid for your Account. ^^

@mcccs, no. Technically, this is not illegal. It's the same as "scamming" accounts. Just, that you don't need the password anymore. It's their own fault, if they post their session id and don't change it.

**Comment by OMGchangeMYusername** [comment]
Who would've knew it can be used to steal his account..

**Comment by Elviond** [comment]
How can I get a SessionId ?

**Comment by Elviond** [comment]
How can I get a SessionId ?

**Comment by GlitchHead** [comment]
Well then this might actually be useful some people never log out of there launcher.

**Comment by GlitchHead** [comment]
Alright i just downloaded garploit 1.3 and tested it it surprisingly works and is not fake i already found 5 working accounts on paste bin... if your interested in testing it to here is the links i got it from
client garploit: https://mega.co.nz/#!8oRwjJJD!FElNIMHpjBS5xkJyO3Pb5Tf3oCL5v4akaw1xFVXG3So
crack (sort of but works): https://goo.gl/kKFPNd make sure to read the read me.

**Comment by Elviond** [comment]
Where can I find a SessionId ?

**Comment by GummiBoat** [comment]
@GlitchHead We should be careful using GarPloit tho. It displays your Session ID in the Start-Menu. If he got that, he can also send it to his own private list. (Not that it's difficult to change the Session, but in general.)

**Comment by Alexander01998** [comment]
> It displays your Session ID in the Start-Menu.

It displays something that they call a "hardware ID". It's probably a hash of the MAC address or something like that.

**Comment by Elviond** [comment]
Where can I find a SessionId ?

**Comment by GlitchHead** [comment]
anywhere goto pastebin.com and search for recent launcher logs.

**Comment by GummiBoat** [comment]
> It displays something that they call a "hardware ID". It's probably a hash of the MAC address or something like that.

Sorry, my fault, didn't thought that one through. Of course they would give you premium via HWID.

**Comment by GlitchHead** [comment]
i also just realized that a players session ID is there accessToken and there uuid mixed together separated by :
