### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by smf01** [Wurst-Imperium/Wurst-Client#103]
I downloaded the updated version of Wurst (1.6) and put it in the correct folder. Now, I press play on the Minecraft Launcher, and it takes a minute to load, then crashes. Is it just because of the update?

**Comment by GlitchHead** [comment]
update java

**Comment by smf01** [comment]
my java is updated

**Comment by GlitchHead** [comment]
do java -version and tell me output

**Comment by wuofwhat** [comment]
I have same problem and i have Java 8 Update 31

**Comment by Alexander01998** [comment]
Post the crash report.
