### ISSUE TITLE
deleted all my keybinds and now cant do anything. Help please looking for a sceenshot of them 

### ISSUE THREAD

**Issue by CrazedBeastKid** [Wurst-Imperium/Wurst-Client#1032]
I've tried deleting and reinstalling and still don't have them. I even redownloaded wurst and still cant do anything because of this. please help :D

**Comment by GummiBoat** [comment]
# *Duplicate: #545*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by CrazedBeastKid** [comment]
ok thx for that advice sorry im new, I did that and only found out how to add one of them back is there a list of them anywhere. Thanks

**Comment by GummiBoat** [comment]
No, there is no list anywhere, if you deleted them, they are gone.

**Comment by CrazedBeastKid** [comment]
O_o what I was hoping for was a screen shot, if that's possible. You know take a screen shot of them all in the options menu then I could manually re input them.

**Comment by GummiBoat** [comment]
Oh, you mean like the basic Keybinds, that Wurst gives you?

("B", ".t fastbreak")
("C", ".t fullbright")
("F", ".t fastplace")
("G", ".t flight")
("GRAVE", ".t speednuker")
("H", ".t /home")
("J", ".t phase")
("K", ".t multiaura")
("L", ".t nuker")
("LCONTROL", ".t clickgui")
("R", ".t killaura")
("U", ".t freecam")
("X", ".t x-ray")
("Z", ".t sneak")

there u go

**Comment by CrazedBeastKid** [comment]
Thank You so much :100:

**Comment by WurstContributer** [comment]
@CrazedBeastKid Wurst settings are not stored in the version folder.
They are stored at 
PC ``` C:\Users\Brandon\AppData\Roaming\.minecraft\wurst ```
Mac Sorry nothing of use here :C 
Delete the keybinds.json folder and the keybinds should be set to default.
