### ISSUE TITLE
what's new in wurst next update??

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1033]

**Comment by GummiBoat** [comment]
You can read that [here](https://github.com/Wurst-Imperium/Wurst-Client/releases/tag/v1.15).

**Comment by OMGchangeMYusername** [comment]
I think he meant what *will* be new in the next release,we don't know :c but @Alexander01998 might have a list of planned changes.

**Comment by GummiBoat** [comment]
Try these filters: `is:issue is:open label:confirmed `, should be, what's in the next Update most likely.

**Comment by OMGchangeMYusername** [comment]
no way they're all going to be added in one release,but yeah some might get added.
