### ISSUE TITLE
Add AirMove (Easy Move In Air)

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1034]

**Comment by GummiBoat** [comment]
I would really appreciate if you would start to provide a description, how you want some things to work. What is "Easy Move In Air" supposed to be?

You can activate Glide if you want to travel further if you are falling, but else, I have no clue what you're meaning.

**Comment by mcccs** [comment]
Maybe SmartMovingMod. But this is implossible whitout plugins.

**Comment by billyoz** [comment]
I Found This On Wolfram

**Comment by OMGchangeMYusername** [comment]
I guess he meant something like no drift?
@billyoz what's its name on Wolfram?

**Comment by billyoz** [comment]
Name In Wolfram Is Airmove

**Comment by billyoz** [comment]
[image: Inline image 1]

**Comment by pokeball99** [comment]
Oh its like double jump,it's in wolfram as he said
