### ISSUE TITLE
Fly upward if YesCheat+ is Enabled

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1036]
Fly Around is a Premium function of Garploit that allows to fly up and down

https://www.youtube.com/watch?v=NsOGHuPn7Mg
7:48

**Comment by Murplyx** [comment]
May I ask does anyone know how that works? If not I'll just see Wursts source when alex adds it since it has been confirmed, I am so curious.

**Comment by GummiBoat** [comment]
Basically you can't just fly upwards unlimited, as said in the video. The limit is 1 Block under from where you jumped. From that on, NoCheat+ assumes that you fall and it won't check if you're falling upwards or something like that. As long as you don't get to the Y level of the Block from where you jumped, it will never check your Y Coordinate again. You can't go too fast tho.
