### ISSUE TITLE
Skinblinker

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1037]
See this:
https://www.youtube.com/watch?v=NsOGHuPn7Mg
5:32

**Comment by Alexander01998** [comment]
This is similar to a Wurst cape, except that it's a skin.

If Minecraft can render GIFs, then blinking/animated Wurst capes are already possible.

**Comment by pokeball99** [comment]
well,u can make gifs from maps......

**Comment by Alexander01998** [comment]
Actually, it seems to be something different. These skins can be seen by everyone, not just users of the client.

**Comment by Whatisthisname** [comment]
Seriously we need this! It is so amazing!
GarPloit has some great features, but most seem like they've been copied from you.
If the feature where you can log in as another person could be implementet that would be great aswell.

**Comment by GummiBoat** [comment]
@Alexander01998 It's not, that the Skin is actually blinking, it's activating and deactivating the overlays (you know, what you can do since 1.8 with your skin) all at once.

**Comment by Alexander01998** [comment]
> It's not, that the Skin is actually blinking, it's activating and deactivating the overlays (you know, what you can do since 1.8 with your skin) all at once.

Sounds plausible, I'll give it a try.

**Comment by Meylama** [comment]
Here you can see how it can look if you are using "the right skin" for that: http://gyazo.com/9ec5dd5ea8a442a0b9f1849dea35a872 with such a skin, this mod will look awesome.

**Comment by Alexander01998** [comment]
My skin should already be compatible to SkinBlinker.

**Comment by Meylama** [comment]
By the way: some clients call it "SkinBlinker", some call it "SkinFlasher", and some call it "Spooky Skin". This mod has not only one name, so you can choose which name you would like to use.

By the way: Here is the source code of this mod from another client: http://hastebin.com/tobemezele.axapta

**Comment by 32rhys32** [comment]
I have an issue upon the skin-blinker or any other name you with to call it, I tried it out once as it was a new feature and as soon as I turned it off it removed the overlay on my skin, even if I turn the client off and go on a non hacked account the skin has still lost its overlay?! I have tried resetting to my skin with the overlay but it appears still gone, as well as shutting down minecraft, my computer and anything else open, the only way I can see it is by using skin blinker and it flashes again, should it do that or should it return to the overlay skin when turned off?

**Comment by pokeball99** [comment]
@32rhys32 please open up a new issue for this bug,so we can track it separately

**Comment by 32rhys32** [comment]
ok then

**Comment by 32rhys32** [comment]
here is the link https://github.com/Wurst-Imperium/Wurst-Client/issues/1426
