### ISSUE TITLE
Speed and Speedbypass if YesCheat+ is enabled

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1038]
Garploit has a Speed and Speedbypass function
https://www.youtube.com/watch?v=NsOGHuPn7Mg
6:20

**Comment by OMGchangeMYusername** [comment]
So fucking what? if Garploit has it,what's your point? want a simple way for all of this,open and issue named "Copy everything in Garploit to Wurst" and include this video to make everything easier.

**Comment by GummiBoat** [comment]
Well, it's easier to overlook if one or two things get rejected. Including multiple features in one Issue always is a bad idea. So what ravenje is doing, is okay.

But I think it should be called "FastWalk", sounds cooler.

**Comment by OMGchangeMYusername** [comment]
nah.. "Speeedu",sounds better :P

**Comment by ravenje** [comment]
Hm....

**Comment by iQuintennn** [comment]
Sanic mode is the best.

**Comment by OMGchangeMYusername** [comment]
I Literally Laughed My Fucking Ass Out. https://www.youtube.com/watch?v=BqDix0GPfoI.
0:10
