### ISSUE TITLE
Alts list.json will not be read.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#104]
i don't know what is causing this but the alts list will not be read for some reason on wurst v1.6 i get prompted with "alts list is empty" thing i click create random alts and restart wurst and the random created alts are not there. i just get the empty alts list prompt.

**Comment by MisterQuatsch** [comment]
What version have you use before?

**Comment by Alexander01998** [comment]
Duplicate: #72
