### ISSUE TITLE
Autosword not working

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#1040]
I enabled it while on creative with an iron axe in my hotbar,didn't work,took a bunch of tools,didn't work,took swords,didn't work,went into Survival mode,nothing worked,i think that's enough to say it's not working.

**Comment by Alexander01998** [comment]
Nope, working fine.

![Wurst Client AutoSword mod](https://cloud.githubusercontent.com/assets/10100202/8340394/7dce9be4-1abe-11e5-859a-eaa716c255e9.gif)

**Comment by OMGchangeMYusername** [comment]
It's not working for me. and sorry but what proves that you were using Autosword anyway? since you've set the mod list to Count.
http://puu.sh/iBrHx/655f5599b6.png
couldn't really upload my gif which which confirms what i said,idk why.
but is there any way it might not work? anything i might've done wrong so it didn't work???

**Comment by GummiBoat** [comment]
@Alexander01998 I did nothing that starting Minecraft, going on to my Survival, and running AutoSword.
![autoswordbug](https://cloud.githubusercontent.com/assets/10976441/8342366/da939c96-1acb-11e5-9957-b4315e8d220a.gif)

**Comment by OMGchangeMYusername** [comment]
So? ignoring this or what's goin' on?

**Comment by Bluscream** [comment]
@OMGchangeMYusername I dont think you know what autosword is. AutoSword is using the best **SWORD** in your hotbar to fight against an entity. Its not supposed to take a tool even if it makes more damage.

But ofc there is a suggestion for that: AutoSword should take the tool with the highest attack value if there is no sword in your hotbar.

**Comment by GummiBoat** [comment]
@Bluscream No, AutoSword is calculating the best possible method to deal damage to the target. And if there is no sword in your hotbar, it'll take the next tool with the best damage vs. entities.

```
if(item.getItem() instanceof ItemSword)
				speed = ((ItemSword)item.getItem()).func_150931_i();
			else if(item.getItem() instanceof ItemTool)
				speed =
					((ItemTool)item.getItem()).getToolMaterial()
						.getDamageVsEntity();
```

**Comment by Bluscream** [comment]
Ohh my fault. i thought its using the same methods as Resilience did :/

**Comment by OMGchangeMYusername** [comment]
@bluscream ... did you even read what i said in the first place?:
>I enabled it while on creative with an iron axe in my hotbar,didn't work,took a bunch of tools,didn't work,took **SWORDS**,didn't work,went into Survival mode,nothing worked,i think that's enough to say it's not working.

**Comment by Bluscream** [comment]
>  enabled it while on creative

Why the fuck should you PvP in creative lol

**Comment by TekkitCommando** [comment]
I think alexander is taking a break from wurst this week which i think is a good idea, guys a developer can only run so much and if he was born in 1998 he is like 16 or 17 so we just gotta let him recharge :)

**Comment by OMGchangeMYusername** [comment]
It's because i test mods on singleplayer-flat-creative world. And i was doing something about pvp so i tried AutoSword (thought it should be damn useful). But unfortunately it was not working so yeah..

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 Please fix this! This is really not working.
Anyone can confirm this too? @mcccs @pokeball99 Please try it guys, this mod is extremely useful and shouldn't be left buggy.

**Comment by PixelMaster3D** [comment]
I'll try. You'll have to wait though because I will need to finish re-adding the new network card to 32-bit system.
