### ISSUE TITLE
comparison of event API's (Wurst's VS DarkMagician6's)

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1041]
so is yours better?or are u not aware of DarkMagician6's? it is used in a lot of private clients,as well as a few public. here is a ref of the the api: https://github.com/TeamBattleClient/TeamBattleRemake/tree/master/TeamBattle/bin/minecraft/com/darkmagician6/eventapi

**Comment by scriptinator** [comment]
Umm. Each is unique in its own way. We don't need to compare them. This is not a forum. Invalid
