### ISSUE TITLE
Wurst-Spambot

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#1042]
I think wurst should have a spambot like system. There would be a button to spawn "dummy player." Then you could have them execute a command all at the same time like 
.bot .say YOU SUCK or .bot .drop
It would only be on a cracked server.
This could also be a way to integrate Wurst-Bot into Wurst-Client

**Comment by Nitrogen-Dioxide** [comment]
I think that you need 2 instances of minecraft to make 2 players in one server.

**Comment by WurstContributer** [comment]
Nope. You dont.

**Comment by mcccs** [comment]
Already confirmed: #128

**Comment by scriptinator** [comment]
@Alexander1998 I know Wurst-Bot is implemented, but it is kinda hard to spam with it. It would be much easier to have 1 Main console controlling all bots
