### ISSUE TITLE
HATS

### ISSUE THREAD

**Issue by 8bitPotato** [Wurst-Imperium/Wurst-Client#1045]
its like the /hat command on servers
you hold an item or whatever and turn on hat, and POOF! HAT! IT'S ON YOUR HEAD!

**Comment by GummiBoat** [comment]
# *Duplicate: #812*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
