### ISSUE TITLE
CrashPotion?

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#1047]
I guess it could work the same way as crash chest

**Comment by GummiBoat** [comment]
A Potion could never do what the CrashChest is doing.

**Comment by scriptinator** [comment]
What about nbt overload and whenever it is thrown(splash potion) the game can not render it and kicks players who are supposed to get the effect

**Comment by Alexander01998** [comment]
The TrollPotion already has the maximum amount of data that a potion can have (all potion effects), yet it doesn't kick anyone from the server.
