### ISSUE TITLE
Tpaura

### ISSUE THREAD

**Issue by Xx-SKRUBBY-xX** [Wurst-Imperium/Wurst-Client#1048]
its really good

**Comment by mcccs** [comment]
More Info: Yescheat plus = no
Example = kronos hack
Teleports to near players and kills them

**Comment by Glowstone82** [comment]
Probably make it automatically use the Blink hack to teleport

**Comment by Eyremba** [comment]
@Glowstone82 blink works only ~20 blocks far on NCP servers so it would not make sense
