### ISSUE TITLE
SessionStealer - ForceOP

### ISSUE THREAD

**Issue by wizardhax** [Wurst-Imperium/Wurst-Client#1049]
A SessionStealer that will make you op if the owner or admin joins the fake server. This is like the original SessionStealer but it is made differently.

**Comment by GummiBoat** [comment]
# *Duplicate: #465*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
