### ISSUE TITLE
AutoBlock

### ISSUE THREAD

**Issue by Tracder** [Wurst-Imperium/Wurst-Client#1050]
Hey,
Maybe a autoblock function when you fight, you automaticlly blocks the hits from the enemy. You can hit him. But he, not you (the player) (I dont mean you can take no damage, only reduced damage)

**Comment by mcccs** [comment]
Did you mean this: When Player A attacks you Wurst automatically goes to sword's slot and clicks right click?

**Comment by GummiBoat** [comment]
@mcccs No, more like BlockHitting, I guess?

**Comment by OMGchangeMYusername** [comment]
It's called Blockhitting on most of private clients xD
and it actually sounds better than Autoblock.

**Comment by Tracder** [comment]
Yep @mcccs , but with the feature you can attack AND block at the same time.
@OMGchangeMYusername Yeah that sounds better :dancer:  :dart:  :D

**Comment by Meylama** [comment]
AutoBlock is really nice :D How it looks if it is properly implemented: https://youtu.be/uKMPIjxFgv8?t=5m13s

Look 5:13 to 5:35

(No advertisement, just to demonstrate how this mod looks)

**Comment by pokeball99** [comment]
Don't add this,1.9 snapshots are around the corner,and blocking is removed in there

**Comment by OMGchangeMYusername** [comment]
I agree with @Meylama, i think you should think of adding more options to Killaura instead of making new mods. This should be implemented along with the other customizations i've suggested in an earlier issue.

**Comment by Meylama** [comment]
I agree also with @OMGchangeMYusername, I think there should be options for the Killaura like AutoBlock, RotationLimit, Delay (How long a player/entity must be in your range before it is attacked (to bypass Anti-Killaura plugins)), maybe also settings for RotationSpeed and MissRate, also to bypass AntiKillaura plugins which counts how many hits you do and how many of them hit the enemy.

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/combat/ModuleAutoBlock.java

https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/com/krispdev/resilience/module/modules/combat/ModuleKillAura.java#L44
