### ISSUE TITLE
HighJump affects mobs too in singleplayer

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1051]
If you are in survival on singleplayer and turn HighJump on, a for example zombie trying to reach you will also be affected by the mod and jump 6 times higher than normal. Is this supposed to happen?

**Comment by GummiBoat** [comment]
I don't think so.. here's a proof btw.

![ibelieveicanfly](https://cloud.githubusercontent.com/assets/10976441/8355514/0ed53530-1b50-11e5-8559-bc18b07cc804.gif)

**Comment by im4nthony** [comment]
lmao
