### ISSUE TITLE
AutoPotion

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#1052]
Throws Heal Potions at your feet automatticly

**Comment by GummiBoat** [comment]
# *Duplicate: #298*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by WurstContributer** [comment]
j
