### ISSUE TITLE
LSD issue

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1053]
Randomly when I leave the client on for a few hours and I join a server LSD turns on by itself it doesnt show on the left.

**Comment by OMGchangeMYusername** [comment]
It happens to me too,but it's too ok,i just open the GUI and disable it.

**Comment by Alexander01998** [comment]
You are probably talking about the LSD EasterEgg.

It is supposed to only appear in the main menu and to turn itself off once you join a world or server, but that never really worked correctly. I'm planning to remove this EasterEgg in Wurst 2.0.

**Comment by WurstContributer** [comment]
Well in the main menu : Nothing
Multiplayer list : Nothing
Server : LSD turns itself on...

**Comment by LolDatSec** [comment]
Keeping in mind this will be removed, I also noticed that if you try un-toggle it by misc>LSD, the cinematic camera will be activated, but can be manually deactivated by pressing the cinematic key.

**Comment by WurstContributer** [comment]
Cinematic camera bug has already been patched in Wurst v1.15

**Comment by LolDatSec** [comment]
Cool, didn't get any LSD easter egg so I can't tell.

**Comment by linuxcodefire** [comment]
lsd source code would be nice ;')

**Comment by GummiBoat** [comment]
@linuxcodefire this is an open source project.. so you just can get it yourself.

**Comment by OMGchangeMYusername** [comment]
[just for the heck of it] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/mods/LsdMod.java).
