### ISSUE TITLE
Mineshafts appear with Basefinder

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1055]
Mineshafts show as red marked when you have basefinder toggled, is this supposed to happen?

**Comment by GlitchHead** [comment]
if its suppose to or not it helps anyways.

**Comment by Alexander01998** [comment]
> is this supposed to happen?

Kind of, yes. BaseFinder works by scanning for blocks that people use to build their houses, and that includes wooden planks.
