### ISSUE TITLE
Alt manager not saving player names and just emails

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1059]
i used to be able to add alts that had emails but now when i add new alts in the latest version of wurst it just saves the email. Can someone please test this there self and tell me if its working for them or not just delete a alt and add it again.
yet if i import alts with emails it saves there username.

**Comment by GlitchHead** [comment]
i just deleted my wurst_rsa and wurst_rsa.pub in .ssh and deleted my key and alts.json i tryed to add a new alt still no change it saves the email but not the username in the alt manager.

**Comment by LolDatSec** [comment]
This is a 1.8 feature where you can change your minecraft name, so if don't think this is a issue at all.

**Comment by GlitchHead** [comment]
Im saying Migrated accounts that are logged in with a email when saved in the alt manager dont have there display name as the account to select they have the email to select and the username changing feature has not effected the alt manager at all.

**Comment by LolDatSec** [comment]
Now I understand. So you want the alts manager to save the username after it is grabbed on the previous login?

**Comment by WurstContributer** [comment]
Fix:Use the alt

**Comment by GlitchHead** [comment]
@WurstContributer Please do not comment if you don't have helpful information on the issue thank you.

**Comment by GlitchHead** [comment]
@LolDatSec yes its suppose to be doing that but its not.

**Comment by Alexander01998** [comment]
Pretty sure your IP got banned from Mojang's authentication servers.
When you add an alt, Wurst tries to log into it to get the username. If it can't do that, the email address stays there.

**Comment by GlitchHead** [comment]
@Alexander01998 Im changing my IP address with my VPN and no change it still saves the email address can you please test this on wurst Alexander and tell me if its working fine for you?

**Comment by Alexander01998** [comment]
Mojang has made some improvements to their authentication system, so most proxies will no longer work. Just wait a day or two until your own IP works again.

**Comment by GlitchHead** [comment]
@Alexander01998 i just made a GIF of this stuff happening here is:
![wurstaltproblems](https://cloud.githubusercontent.com/assets/8052644/9127332/18bd9a10-3c7f-11e5-89ca-a61ffffb3389.gif)
As you can see when i add a alt the email is not saved for some reason it is getting there username in the name section but when i save it the username is not saved also my alts are constantly changing there usernames when i click edit on them i see there new username i just cant save them.
also it is not my IP address wurst still gets there username when i type in there info i just cant save them!

**Comment by GlitchHead** [comment]
ill be removeing the GIF after your response i dont want everyone to know my alt names.

**Comment by WurstContributor** [comment]
@GlitchHead I have it on my clipboard already :trollface:

**Comment by GlitchHead** [comment]
There passwords are not included and these are private alts so Google wont help you :)

**Comment by OMGchangeMYusername** [comment]
Can't believe how people get alts, what about the original owners? did they kinda give up on minecraft?

**Comment by GummiBoat** [comment]
@OMGchangeMYusername There are monthly releases of stolen minecraft accounts. Plus there are enough kids that fall for easy tricks.

Yeah, I had something similar @GlitchHead, but after restarting the client, the problem fixed itself, additionally the names get loaded properly as well.

**Comment by GlitchHead** [comment]
Forgot to note that this does not happen when i import alts they all work fine when i import them.

**Comment by GlitchHead** [comment]
@Alexander01998 have you seen my comment ^

**Comment by Eyremba** [comment]
@GlitchHead for me, this bug happens only if I import alts with the import function. Then it only displays the email also if the account is working.
