### ISSUE TITLE
KillAura - "Playermodel looks strange on enemy"

### ISSUE THREAD

**Issue by capsload** [Wurst-Imperium/Wurst-Client#106]
When i have KillAura on, my View is now strange-ly moving around to the enemys, i want to have it like before, killaura shouldnt change my "view"

**Comment by Alexander01998** [comment]
KillauraLegit does that. Killaura & MultiAura shouldn't.

**Comment by capsload** [comment]
KillAuro and MultiAura does that too - my Screen points to the enemy.
Currently playing on Hypixel's Warlords. Aura also targeting the "team mates". But i think theres no way to only attack "enemy teams" right?

**Comment by Alexander01998** [comment]
OK, I will check later.

**Comment by capsload** [comment]
Ok cool. I've sent you a friend request, maybe we can play together to check things out!

**Comment by Alexander01998** [comment]
It's working fine for me.

**Comment by capsload** [comment]
Can you show me your configuration?

**Comment by Alexander01998** [comment]
> Can you show me your configuration?

```JSON
"Killaura": {
  "Killaura speed": 20.0,
  "Killaura range": 6.0
}
```

**Comment by Notchshero** [comment]
yes, team mates!

Please add an option "your team's color: <Selection>"

**Comment by capsload** [comment]
Did some video, can you see the strange movement of my character? He looks like, i dont know - aiming to something.

http://youtu.be/69lQgL7WzAQ

**Comment by Alexander01998** [comment]
That's a NoCheat+ server, right? NoCheat+ doesn't allow you to use the full Killaura range. Try setting it down to `4.25`.

**Comment by capsload** [comment]
Same Thing :( (its on hypixel warlords)

**Comment by Alexander01998** [comment]
> Same Thing :( (its on hypixel warlords)

Maybe they limited the speed too. The normal NoCheat+ only limits the range, but Hypixel's NoCheat+ is much more strict.
