### ISSUE TITLE
Enemy Armor//Sword HUD?

### ISSUE THREAD

**Issue by LolDatSec** [Wurst-Imperium/Wurst-Client#1060]
After seeing the power of .invsee, I was curious if it is possible to implement a HUD where you can see the enemy's (closest player in Field-Of-Vision) armour and what he is holding (in terms of weapon enchantment, name etc.)

**Comment by GummiBoat** [comment]
Generally Alexander doesn't want too much Information on the screen. And imagine to have the complete Armor+Weapon+Enchantments of one enemy on your screen...
