### ISSUE TITLE
Wurst Timer

### ISSUE THREAD

**Issue by knownfunnyman** [Wurst-Imperium/Wurst-Client#1063]
I have no Idea how to slow down time with the wurst timer, I looked it up and it said that there was a dial. There is no dial for the timer command on my client. What is going on? Is there a certain command?

**Comment by GummiBoat** [comment]
The Bottom Value. Under 1.0 will slow your vision, Over 1.0 will speed it up.

![](http://puu.sh/iD6n8/67af5436f7.png)
