### ISSUE TITLE
Is there any other code than the one in PhaseMod.java that makes Phase work?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1066]
I am experimenting with MCP and tried implement a Phase hack like wurst, and used the same code as there is in the PhaseMod.java, but nothing happens? Is there any other code that makes the mod work, like something added in net.minecraft...?

(And yes, I am testing on a *server with NCP*)

**Comment by Murplyx** [comment]
I *think* I found it so I'll leave it open, I removed the first line at net.minecraft/EntityPlayer.java in the update method:

 public void onUpdate()
    {
        //this.noClip = this.func_175149_v(); <-------
       ...

Is this how you did it alex?

**Comment by Alexander01998** [comment]
I don't remember it exactly. I think this code in `net.minecraft.entity.Entity` does it:

```java
public void moveEntity(double x, double y, double z)
    {
        //TODO: Client
    	//Enables NoClip.
        if
        (
        	this.noClip
        	|| WurstClient.INSTANCE.modManager.getModByClass(FreecamMod.class).isEnabled()
        	|| WurstClient.INSTANCE.modManager.getModByClass(PhaseMod.class).isEnabled()
        )
        {
        	//TODO: Client
        	//Fixes Freecam flight speed
        	if(this == Minecraft.getMinecraft().thePlayer && WurstClient.INSTANCE.modManager.getModByClass(FreecamMod.class).isEnabled())
        	{
        		this.func_174826_a(this.getEntityBoundingBox().offset(x * 10, y, z * 10));
        	}else
        		this.func_174826_a(this.getEntityBoundingBox().offset(x, y, z));
            this.func_174829_m();
        }
        else
        {
            ...
        }
    }
```
