### ISSUE TITLE
Improvement for Step Bypass

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1067]
I figured out a way to bypass step mod even better!

In StepMod.java in the "YesCheat+" part, replace:

    if (mc.thePlayer.isCollidedHorizontally && mc.thePlayer.onGround)
		mc.thePlayer.jump();

with

    if (mc.thePlayer.isCollidedHorizontally) {
		if (mc.thePlayer.onGround)
			mc.thePlayer.jump();
	
		mc.thePlayer.fallDistance = 0;
		mc.thePlayer.onGround = true;
    }

Edit: mc == Minecraft.getMinecraft()

**Comment by mcccs** [comment]
Please pull request it

**Comment by Murplyx** [comment]
This might sound really noob but I don't use git much and how am I gonna do that? (What should I select after clicking "pull request"?)

**Comment by Alexander01998** [comment]
Step already bypasses NoCheat+ completely.
