### ISSUE TITLE
How is flying upwards supposed to be added?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1069]
It has been confirmed that wurst will add a feature that makes NCP Flight able to fly up/down,
I tried implementing something like that, but it only works if you fly down. The only way afaik is to shoot up with a bow so you take damage and then you can fly up aswell. I wonder how is fly up going to be implemented in the next version, will it require the use of a bow? Also I've seen that you don't need a bow in the hacked client GarPloit, does anyone know how that works (with java code)?

**Comment by GummiBoat** [comment]
It won't need a bow, and you just need to fly up in the same speed you fall down, you only can fly up to the Y coordinate from where you jumped tho.

**Comment by Murplyx** [comment]
Could someone please share some sourcecode?

**Comment by GummiBoat** [comment]
I'm not going to give you something that you can just copy & paste, but it should pretty much be

```
double posY = Minecraft.getMinecraft().thePlayer.posY;
if(Minecraft.getMinecraft().gameSettings.keyBindJump.pressed && !Minecraft.getMinecraft().thePlayer.posY == posY){
     Minecraft.getMinecraft().thePlayer.motionY += 0.01;
}
```

but you have to try it out yourself.

**Comment by Murplyx** [comment]
You haven't even tried it yourself, it has syntax error: "!Minecraft.getMinecraft().thePlayer.posY == posY"

**Comment by GummiBoat** [comment]
Ah, yes, try to subtract 1 from posY.
