### ISSUE TITLE
Source code for the even better fly mod

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1072]
Could someone share/spoil(since it isnt out yet) the source for the new flight mod (the one where you also can fly up and down with NCP and not just glide)?

**Comment by scriptinator** [comment]
```	@Override
	public void onUpdate()
	{
		if(WurstClient.INSTANCE.modManager.getModByClass(YesCheatMod.class)
			.isEnabled())
		{
			if(!Minecraft.getMinecraft().thePlayer.onGround)
				Minecraft.getMinecraft().thePlayer.motionY = -0.02;
```

**Comment by Murplyx** [comment]
Thats just the source for the glide, not what i wanted, i wamt the source also for flying up and down

**Comment by Murplyx** [comment]
I guess you just read the title and missed the part 'even better'

**Comment by Murplyx** [comment]
See #1036

**Comment by Alexander01998** [comment]
Your question was already answered in #1036.
