### ISSUE TITLE
Asking For OP

### ISSUE THREAD

**Issue by MrFishykoi** [Wurst-Imperium/Wurst-Client#1076]
I've watched a video "How to get OP" using Wurst. I'm wondering does it work ? This is the link of the video: https://www.youtube.com/watch?v=jAWjHUyCqI4

**Comment by mcccs** [comment]
No. https://www.wurst-client.tk/wiki/Force_OP_(AuthMeCracker)/

**Comment by GummiBoat** [comment]
He probably did that on purpose as a plan with the original owner to get some video clicks. Read the wiki-link mcccs posted to get an understanding of how ForceOP actually works.
