### ISSUE TITLE
Sound if enable or disable a mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1077]
some hacked clients send a sound if i enable or disable a mod
can you add a Option to the Wurst options that enable or disable sending sounds if you turn on or off a mod?

a sound would for example random.click
(do /playsound random.click @p in a singeplayer world to hear it)

**Comment by Alexander01998** [comment]
When I added Kaboom, I tried to add the explosion sound to it, but it never played for some reason.

**Comment by OMGchangeMYusername** [comment]
This is completely useless.
I wanted to suggest #1078 ages ago,but i remembered when i saw this,sounds would lag minecraft i believe,so msgs would be better.

**Comment by awakened-game** [comment]
hmm, i could have sworn kaboom used to have sound with it, now my head hurts, and ive just awoken a dead issue havent i?
