### ISSUE TITLE
Unfair aimbot

### ISSUE THREAD

**Issue by wizardhax** [Wurst-Imperium/Wurst-Client#1081]
What unfair aimbot will do is that you can shoot or hit through walls.

**Comment by WurstContributer** [comment]
Duplicate:#784 Arrows can not go through walls

**Comment by GummiBoat** [comment]
784 is for KillAura through Walls and in no way a duplicate. But however, it's true, that Arrows are not supposed to go through walls, Minecraft Vanilla denies that.

**Comment by OMGchangeMYusername** [comment]
Not possible*
