### ISSUE TITLE
Cosmetic features

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1087]
Player size, ears, upside down, etc.

**Comment by billyoz** [comment]
Size,ears,upside down. I found this In KILO

**Comment by pokeball99** [comment]
Or....u can just program it and make a pull request,since this is open source

**Comment by OMGchangeMYusername** [comment]
@pokeball99 seriously,does he sound like a coder/developer judging by his issues so far?

This isn't really necessary  but it might be swaggy :D idk if i like it or not but let's see..

**Comment by TekkitCommando** [comment]
Addons would be good for the developers that made them, tho pull requests are good for the whole community :)
