### ISSUE TITLE
FastRender

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#109]
Disables animations. Great for slow computers.
It disables;
Banner-wind animation
Water animation 
Dropped item rotation
Day&Night
Chicken's wings
player arms 
player skins
etc

**Comment by mcccs** [comment]
Why? If you add this you won't see more OPTIFINE issues.

**Comment by mcccs** [comment]
Why? If you add this you won't see more OPTIFINE issues.
@Alexander01998

**Comment by TekkitCommando** [comment]
Why would you disable functions that are normal to minecraft :P

**Comment by OMGchangeMYusername** [comment]
exactly! like who would like minecraft when it has nothing of minecraft features?!?!
