### ISSUE TITLE
Is there anymore code for tracers than in the TracersMod.java class?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1093]
Is there anymore code than the one in TracersMod.java or RenderUtils.java that makes tracers work (in net.minecraft..)? Because I tested implementing it in MCP and when I walk the tracers bounce around the crosshair? Like something in you maybe edited in EntityPlayer's getEyeHeight method?

**Comment by GummiBoat** [comment]
/utils/RenderUtils.java

**Comment by Murplyx** [comment]
I am sorry forgot that and in the RenderUtils.java

**Comment by Murplyx** [comment]
I can't believe it! all that I needed 2 do was 2 disable view bobbing!

**Comment by Murplyx** [comment]
But the strange thing is that Wurst has bobbing enabled.??
