### ISSUE TITLE
How did you make Tracers compatible with Minecraft's View Bobbing?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1095]
I tried making a tracer mod in my client but the tracers bounce around when I walk if I have View Bobbing enabled. In Wurst though they don't even though View Bobbing is on, how did you make that?
Here's a video to show what I mean: https://vid.me/d0WD

**Comment by OMGchangeMYusername** [comment]
Yeah i'm interested too =D

**Comment by Alexander01998** [comment]
Tracers disable View Bobbing as soon as they are activated. Most people don't notice that.

**Comment by Murplyx** [comment]
And where in the code do they do that may I ask?

**Comment by wizardhax** [comment]
Murplyx is your client private or are you going to publish it somewhere?

**Comment by Murplyx** [comment]
When it is complete I will open source it, 100% free, non-profit and non commercial. I will make a website for it without ads and NO really annoying stupid adfly links.

**Comment by wizardhax** [comment]
because I like testing out people's hacked clients. If it is not going to be public maybe you can add me on Skype and if your willing you could send me the hacked client?
