### ISSUE TITLE
Gui to big.

### ISSUE THREAD

**Issue by rik11111** [Wurst-Imperium/Wurst-Client#1096]
my screen is smaller than the gui so a cant click target and som other tings

ssry for inglisch am a Dutchmen

**Comment by Alexander01998** [comment]
# *Duplicate: #910*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
