### ISSUE TITLE
redstone breaks by X-ray

### ISSUE THREAD

**Issue by rik11111** [Wurst-Imperium/Wurst-Client#1097]
when a open x-ray all the redstone breaks    (singleplayer but whit ma friends to)

**Comment by Alexander01998** [comment]
# *Duplicate: #250*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
