### ISSUE TITLE
Creative Player killing potion

### ISSUE THREAD

**Issue by g17123** [Wurst-Imperium/Wurst-Client#1098]
/give @a[c=1] minecraft:potion 1 16450 {display:{Name:Death Potion},CustomPotionEffects:[{Id:6,Amplifier:249,Duration:19999980},{Id:21,Amplifier:249,Duration:19999980}]}

**Comment by WurstContributor** [comment]
_*Duplicate: #1027*_
----------------------------------------------------------------------------------------------------------------------------------
![687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67](https://cloud.githubusercontent.com/assets/11792380/8398402/c712a68e-1da1-11e5-95ea-53e7e59632c9.png)
