### ISSUE TITLE
Parkour bot

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#110]
First you enable this hack, look at the block which you want to go.
If you look at 190 60 79
computer adds "y" 1  (190 61 79)
Then computer calculates how to go there.
Computer jumps to other blocks.
And it goes to there.

**Comment by Notchshero** [comment]
what is "mod"

**Comment by Alexander01998** [comment]
> what is "mod"

Every feature in Wurst that can be toggled with the `.t <mod name>` command is a mod.

**Comment by OMGchangeMYusername** [comment]
WoW this seems aweshome if it goes well! or at least it should jump to the block you choose!
like if it was a three or four blocks away it should help nailing it!
