### ISSUE TITLE
Java 1.8.0 required

### ISSUE THREAD

**Issue by CreeperGamingzz** [Wurst-Imperium/Wurst-Client#1105]
I started wurst and it said java 1.8.0 required so i installed it and restarted my minecraft i hit play wait and it says it aggain i go check my version of java it says: Java 8

Please help me 
thanks CreeperGamingzz

**Comment by GummiBoat** [comment]
Your System Details?

**Comment by TekkitCommando** [comment]
Maybe add Java 8 to your path, I doubt that's required just to play minecraft but it worth a shot, also I think this is just my preference but I like to restart my computer after installing a new version of java :)

**Comment by GlitchHead** [comment]
find the path your java 8 was installed then in the minecraft launcher goto edit profile and select the executable check box and point it the the java 8 executable if you do that it should work.

**Comment by TekkitCommando** [comment]
^ easier then adding it to your path i guess :P

**Comment by Alexander01998** [comment]
# *Duplicate: #142*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
