### ISSUE TITLE
How to disable the "." commands??

### ISSUE THREAD

**Issue by KekkoMenny** [Wurst-Imperium/Wurst-Client#1106]
How can I disable the "." commands so i can start a sentence in the chat with "." ?? If you're asking why is because a mod of a server asked me to write ".help" in the chat, but I cant because the commands pop up. Please help I really love this client <3 and I don't want to change it or use vanilla.

**Comment by GummiBoat** [comment]
# *Duplicate: #141*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by KekkoMenny** [comment]
Ahahahah you're the best thanks you really much, I'll search before asking a question next time, thanks!

**Comment by GummiBoat** [comment]
No Problem, you can close your Issue by yourself btw, there is a button next to the "Comment" button, so Alexander doesn't has to do it.
