### ISSUE TITLE
Auto Tpaccept

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1107]
I think you should add a mod to this client, that whenever someone sends a teleport request, then it will automatically accept it. I've seen this in some other clients.

**Comment by GlitchHead** [comment]
Already exists as a mod in wurst.

**Comment by GummiBoat** [comment]
# *Duplicate: #202*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by labcraft59** [comment]
it does?

**Comment by labcraft59** [comment]
OH and also make it so that you can see ALL of the hax and not just the ones that can fit on your screen! :/

**Comment by OMGchangeMYusername** [comment]
> OH and also make it so that you can see ALL of the hax and not just the ones that can fit on your screen! :/

set the GUI scale to normal.
