### ISSUE TITLE
CMD-BLOCK commands not working

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1110]
hello im trying to put a command in a command block like /op /stop /gamemode 1 bugzncheese1 and even /help and it said Invalid command please type /help for help and i did /help and said Invalid command please help?

**Comment by GummiBoat** [comment]
/op and /stop don't work with command blocks.

Try commands from which you know that they work. ("/give @p minecraft:stone" or sth. like that) And make sure, CommandBlocks are enabled. (There is a gamerule and an option in the config for servers.)

**Comment by trollmad3** [comment]
do you know witch command work?

**Comment by trollmad3** [comment]
@GummiBoat do you know what commands work? is there like a webisite that i can see

**Comment by GummiBoat** [comment]
Just search for Minecraft CommandBlock commands or sth like that, dunno
