### ISSUE TITLE
Remote Login

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1111]
Is it possible to add ssh to clients for remote hacking? my friend did it... but he was using c++

**Comment by linuxcodefire** [comment]
and telnet...

**Comment by ravenje** [comment]
Use putty if you has windows
if you use linux (Debian) install openssh (Arch) install openssh-client

**Comment by mcccs** [comment]
Why?

**Comment by linuxcodefire** [comment]
If you ssh hack you can download server files, delete files, and add files xD

**Comment by linuxcodefire** [comment]
Or just hijack it but that EXTREMELY COMPLEX CODE.
