### ISSUE TITLE
headroll

### ISSUE THREAD

**Issue by 8bitPotato** [Wurst-Imperium/Wurst-Client#1112]
You know how you can turn your head 360 degrees horizontally,
but what if you can do it vertically?

**Comment by OMGchangeMYusername** [comment]
Lol this would be so confusing,but it's unique i admit.

**Comment by Anonymous55** [comment]
Hey, Why dont you add a invisible head? Like other players would not see your head when you enable it. It could work, Same as the headless coding just maybe resize the head? Good luck with it Alexander :)

**Comment by Anonymous55** [comment]
Cant wait intill the next update! Hopefully Alexander doesnt add VIP since others will not like that.

**Comment by Anonymous55** [comment]
But i will be very sure to donate because this is the best client out there yet!

**Comment by Meylama** [comment]
@Anonymous55 you are dumb. How should a VIP system work on a OPEN-SOURCE client you fool?! That would not make sense. Anybody could download the source and remove the VIP check and finish.
