### ISSUE TITLE
Add ParkourJump

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1115]
ParkourJump jumps exactly when you're on the edge of a block, that way you can easily do 4 block jumps and 3 block and 1 block up jumps.

**Comment by GummiBoat** [comment]
# *Duplicate: #522*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
