### ISSUE TITLE
AutoDrop

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1116]
Similar to #847.

Keeps your inventory clear by instantly dropping all items that are beeing collected.

**Comment by GummiBoat** [comment]
# *Duplicate: #676*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
