### ISSUE TITLE
Opacity X-Ray

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1117]
With opacity X-Ray you can see where you are walking and also see all the ores

**Comment by GummiBoat** [comment]
> Wurst for Minecraft 1.7.X had opacity X-Ray, but Minecraft 1.8 broke it. -Alexander01998

~ not possible

**Comment by Murplyx** [comment]
If 1.8 broke it because it changed some code, how can it not be possible?

**Comment by OMGchangeMYusername** [comment]
Well,none of 1.8 client have this,so 99% it's not possible..

**Comment by Murplyx** [comment]
Well it must be possible but very hard maybe to implement

**Comment by GummiBoat** [comment]
It's simply not possible, because changing the opacity of solid blocks is not possible anymore. You can use an X-Ray Texturepack, where you delete everything except for a 1 pixel border, so you know where you walk.

**Comment by Murplyx** [comment]
Serenity has it, here's a way to do it: http://www.hackforums.net/showthread.php?tid=4753898

**Comment by Alexander01998** [comment]
> Serenity has it, here's a way to do it: http://www.hackforums.net/showthread.php?tid=4753898

This might be a fix for #247 too.

**Comment by Murplyx** [comment]
It is a fix for that, I implemented it my self, its easy

**Comment by OMGchangeMYusername** [comment]
um.. #1221?

**Comment by Alexander01998** [comment]
Sadly, it seems that this fix is not working. The thread is about Minecraft 1.8.3, so most of the code is completely different in 1.8. They say:

> you probably want to disable Minecraft's new cave culling algorithm as it will prevent certain chunks from rendering. Inside VisGraph.java I just prevent a blockpos from being added to the list. This will probably hurt performance a little, but it really shouldn't be a problem for most desktops.

But in Minecraft 1.8, there is no point where a `BlockPos` is being added to a `List`. There are two points where an `int` is being added to a `List` and one where a `BlockPos` is being added to a `BitSet`. Preventing any of those does not change the behavior of X-Ray at all.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 So did you figure out how it worked in 1.8? pretty sure it's working on Serenity.

**Comment by Murplyx** [comment]
I have it in my client, so its not impossible

**Comment by OMGchangeMYusername** [comment]
We all know it's not impossible.. I'm saying did he see how it works or not yet.

**Comment by Alexander01998** [comment]
> I'm saying did he see how it works or not yet.

No.

**Comment by Alexander01998** [comment]
I just found out that my Eclipse is broken: It doesn't recompile changed code while using the debug mode (a feature called Hotswap Bug Fixing), so it looked to me like changing the code as explained in the HF thread had no impact on the behavior of X-Ray.

I will try this again once I fixed my Eclipse.

**Comment by OMGchangeMYusername** [comment]
Lol what about my issue? Should I close it? since this is older so yeah..

**Comment by Alexander01998** [comment]
> Lol what about my issue? Should I close it? since this is older so yeah..

Closed it.
