### ISSUE TITLE
Are you sure Tracers automatically disable View Bobbing?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1119]
You said that View Bobbing was automatically disabled when Tracers where enabled in #1095, but I don't believe that since if I set View Bobbing to On and enable tracers, I can see that the arm is swinging. To make it more clear: https://vid.me/ocM2 as you can see the diamond is swinging up and down with Tracers enabled.

Also where and what did you edit in net.minecraft.. else that TracersMod.java to achieve this effect (not bouncing but still view bobbing)?

**Comment by Alexander01998** [comment]
> not bouncing but still view bobbing

Bouncing and view bobbing are the same thing. Therefore not bouncing means not bobbing.

> the diamond is swinging up and down

The hand swing is not part of view bobbing.

> where and what did you edit in net.minecraft.. else that TracersMod.java to achieve this effect

I don't remember that anymore, but you can look it up here on GitHub. All of the source code is there.

**Comment by Murplyx** [comment]
Omg! Didn't notice the minecraft.patch file! I am so sorry! I will never ask stupid questions again!
