### ISSUE TITLE
Target selection by name

### ISSUE THREAD

**Issue by Notchsheroo** [Wurst-Imperium/Wurst-Client#112]
An option for killaura:
-Team "nametag color selection"

**Comment by capsload** [comment]
Warlords? ;P

**Comment by Alexander01998** [comment]
I have a better idea: Selection based on the name with support for wildcards/regexes.

Every server handles team colors differently, so a pre-made regex like `§c*` (red color + any string) would only work on some servers.

Also, this would be a nice implementation for #23.
