### ISSUE TITLE
Command Book

### ISSUE THREAD

**Issue by idkmybffjill** [Wurst-Imperium/Wurst-Client#1120]
Hello,

I am trying to test the command book hack, but with no success. Is there certain requirements that the server has to have to use it? Or can only OPed players click the text in the books that activate the commands?

I have been trying to use the command book hack to force players to pay me all of there money when they click on the link, but no one can click on the link on the server. I havent tried this with an OPed player.

I put a random link as the book text, click sign, give it a title, click the command book button, and then type the command below.
/pay [name] [amount]                   and filling in the fields as necessary.

When players try to click on the link in the book nothing happens. i have tried using commands such as /home as well, but still nothing.

Thanks for your great client,
Jill

**Comment by GummiBoat** [comment]
Afaik the newer versions (1.8.5+) have patched this, try it on a bukkit server that only runs 1.8 or sth like that.
