### ISSUE TITLE
Make a new startup sceen something like KiLO has

### ISSUE THREAD

**Issue by wizardhax** [Wurst-Imperium/Wurst-Client#1126]
Title ^^^

**Comment by GummiBoat** [comment]
I dunno, I think it's fine like it is now and that KiLO's is a little bit too much.

**Comment by TekkitCommando** [comment]
If I hear one more thing about kilo I'm gonna go nuts

**Comment by WurstContributor** [comment]
@TekkitCommando Same.

**Comment by Alexander01998** [comment]
> If I hear one more thing about kilo I'm gonna go nuts

I agree.

**Comment by OMGchangeMYusername** [comment]
I was like,Who the fuck is talking about KiLO?? and then i noticed that you actually renamed the issue xD
