### ISSUE TITLE
PlayerFinder

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#113]
u can get coords during thunderstorms
this client has it implemented:
https://github.com/spacerocket/vapid/blob/master/me/pyr0byte/vapid/modules/ModuleSounder.java

**Comment by GlitchHead** [comment]
so like this will find were a lighting strike hit?

**Comment by pokeball99** [comment]
idk,i know it works because they disabled lighting on 2b2t.org because of it

**Comment by Alexander01998** [comment]
So it can roughly determine the position of far players during a thunderstorm? :zap:

**Comment by pokeball99** [comment]
yes,i belive so,but i can't test it as i explained in my previous comment

**Comment by Alexander01998** [comment]
I just looked at the source code again and noticed that it doesn't just wait for lightning strikes, but for any sound or particle effects. If this thing actually works, it can accurately track any player at any time.
