### ISSUE TITLE
Compile a new version

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#1130]
I know I am a noob. I have created a simple mod and I would like to use it in the minecraft launcher. I have tested it and it works fine in Eclipse. I know that you need to run recompile and reobsufacate in MCP, but that wouldn't compile Wurst with it. How would I compile a new Wurst version?

**Comment by scriptinator** [comment]
I figured it out take your bin folder from Eclipse and put it into the bin folder in MCP. Then run 
./reobfuscate.sh or reobfuscate.bat

**Comment by OMGchangeMYusername** [comment]
Thanks..

**Comment by scriptinator** [comment]
Instead export in eclipse using Runnable Jar
