### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1137]
@Alexander01998 Add a music player? This would be nice feature.

**Comment by scriptinator** [comment]
More information required. Like music on your computer? Just play music in the background. Other than that Minecraft has music built in

**Comment by UnidentifiedProfile** [comment]
DUPLICATE: #595

**Comment by OMGchangeMYusername** [comment]
:cry:

**Comment by linuxcodefire** [comment]
Holy crap stop calling out duplicates... not like i was here before...

**Comment by OMGchangeMYusername** [comment]
> not like i was here before...

You might as well never come again..

Can't you at least search if there was a similar suggestion before? you can find whatever you want if you read how to use the search function,it only takes three minutes.
