### ISSUE TITLE
Drop command for specific items

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1138]
Lets say you have the /give command and you give your self a 64 stack of diamond chestplates and then spam the Drop button in minecraft you will drop lots of chestplates and it will fill a players inventory that your throwing at fast and when the stack of diamond chestplates runs out you spawn a new stack of golden chestplates and repeat the process with different chestplates.

Now we just make a ".drop spam" command to spawn a 64 stack of any non stackable item and drop them one at a time fast and repeat.

I know about the .drop infinite command but its very slow for some unknown reason this is my alternative idea to it for the item drop spamming part that does not work well.

**Comment by Nitrogen-Dioxide** [comment]
Yea with a stack of chestplate, each drop will generate 64 of them
I noticed that, but doesn't had that idea.

**Comment by WurstContributor** [comment]
This would be good to ruin youtuber's videos 
1)Find them
2)Fill their inv

**Comment by Alexander01998** [comment]
I would rather do a `.drop item <item_name>` command to give the user more control over it.
