### ISSUE TITLE
Custom Wurst version not rendering § 

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#1139]
I compiled a custom wurst version and when running in launcher and eclipse it will not render §. It will render this question mark instead of § everywhere Wurst uses the § sign
![screen shot 2015-07-02 at 8 02 05 pm](https://cloud.githubusercontent.com/assets/6655672/8491867/4cb26eea-20f5-11e5-9bdd-7e02b933eb6f.png)

**Comment by GummiBoat** [comment]
There are two possible solutions for it. Try enabling UTF-8 for your Content Types. (Window->General->Content Types). There you can write "UTF-8" into the Default enconding field.

Otherwise, you still can use \u00A7 instead of §.
