### ISSUE TITLE
Set up proxy?

### ISSUE THREAD

**Issue by Woolworths** [Wurst-Imperium/Wurst-Client#1142]
How do I set up the proxy? I want to run the client through localhost:7070

**Comment by GummiBoat** [comment]
This has nothing to do with Wurst. Please read the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) before you post next time.

Btw, there are more than plenty Video tutorials on YouTube. You should find one fitting your expectations within 5 minutes.

**Comment by Woolworths** [comment]
Well no, I was wondering is there was a function that allows the use of proxy. For example, .proxy localhost:7070

**Comment by GummiBoat** [comment]
No, there is no feature yet, But #70 will cover that.
