### ISSUE TITLE
ArenaBrawl

### ISSUE THREAD

**Issue by George283312** [Wurst-Imperium/Wurst-Client#1146]
they mods dont kick in sometimes ive played 4 matches and it worked once for half the match i dont understand why. all the settings are set up and ive read the wiki on it but i cant resolve the issue only the killaura and others dont work, the only thing that works is the tracers and player/totem ESP work, its making it acctually worse if this can be fixed i would apreciate kindly.

**Comment by Nitrogen-Dioxide** [comment]
try to doo .t arenabrawl off  a few times and see if the error is solved
