### ISSUE TITLE
Copy signs

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1148]
Can you make autosign clone/copy text of signs on rightclick?

**Comment by GummiBoat** [comment]
How do you mean that? Like, you press CTRL+Rigthclick and you copy it? Please consider giving a few more informations on your idea.

**Comment by ravenje** [comment]
i mean: If autosign is enabled and i rightclick on a sign, the text on it will stored to autosign

**Comment by GummiBoat** [comment]
Oh, that seems like a good idea :)

**Comment by ravenje** [comment]
:D

**Comment by ravenje** [comment]
or alexander can make a new mod named Copysign to do tihs
