### ISSUE TITLE
spooky phase

### ISSUE THREAD

**Issue by llaurenss** [Wurst-Imperium/Wurst-Client#1149]
it should be nice if you could add this https://youtu.be/mWg_vstBa6E?t=38s. i have tried this with wurst but it didn't work https://youtu.be/56zRq2mw22c

**Comment by GummiBoat** [comment]
This pretty much is a horizontal NoClip (I think we should really call this like that, tbh). But it seems that you need to be stuck into blocks first in order for it to work. Btw, currently you can achieve the same thing, by activating Flight as soon as you traveled a bit further into the ground with VClip. It's really slow tho, so be careful with taking damage.

**Comment by llaurenss** [comment]
thanks i tried it and worked :)

**Comment by mcccs** [comment]
Worked for me too.
