### ISSUE TITLE
Import alt lists

### ISSUE THREAD

**Issue by mineee** [Wurst-Imperium/Wurst-Client#115]
Hi. Is there a way to add multiple alt accounts at once? I know I can gather cracked alts while in game but I want to add some premium alts.

Thanks

**Comment by GlitchHead** [comment]
like in game you can do .addalt (user) (password) ? or import a alt list to wurst?

**Comment by mineee** [comment]
As in importing an alt list. I looked through the wurst folders and couldn't find anything.

**Comment by Notchshero** [comment]
if you dont know premium alt's password, you can use it as cracked alt
