### ISSUE TITLE
Wurst bot-error

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1151]
Could not find or load net.minecraft.client.Main
i think wbot is not compatible with new wurst versions

**Comment by GummiBoat** [comment]
# *Duplicate: #1070*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Bluscream** [comment]
**#Duplicate: # **

![Please search for similar Issues before submitting yours.](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by mcccs** [comment]
Oh, thats my second duplicate. :(
