### ISSUE TITLE
Speedclicker

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1152]
A mod that clicks faster
.speedclicker left 10
.speedclicker right 100

**Comment by mcccs** [comment]
.click is better

**Comment by ravenje** [comment]
yes

**Comment by solidshadow96** [comment]
Yea that feature would ROCK for pvp
get 10 or 100 hits per click

**Comment by OMGchangeMYusername** [comment]
@solidshadow96 That won't work on AntiCheat servers..

**Comment by Alexander01998** [comment]
That wont work on any server.

**Comment by OMGchangeMYusername** [comment]
lol

**Comment by solidshadow96** [comment]
What about a hack where instead of 100hits per sec the button is spammed with a simulated jitter click
like if you hold the left button down it will spam left. this would also be good because there is no lock on feature and therefore you could not be ban as ealily. do you like that idea ???
