### ISSUE TITLE
Better font

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1153]
http://gifmaker.cc/PlayFrameAnimation.php?folder=201507042037zJURBA5WdWuVxbCt4kjH
![](http://winsupersite.com/site-files/winsupersite.com/files/uploads/2014/10/perf-opts.jpg)
The third tickbox in bottom. Bold text is better and could you please add this to wurst?

**Comment by Bluscream** [comment]
That is not minecraft or Wurst related, you have to change this setting in your Operating system!

**Comment by scriptinator** [comment]
Add that font to Minecraft through a resource pack. Invalid
