### ISSUE TITLE
creative hat and .hat command

### ISSUE THREAD

**Issue by llaurenss** [Wurst-Imperium/Wurst-Client#1156]
it should be nice if you could add something like creative hat, i found this hack on the hacked client serenity and it changes very fast blocks on your hat https://youtu.be/-WLf7gRKyuM and .hat command, .hat (block id) https://youtu.be/LYFDBnomP8g

**Comment by GummiBoat** [comment]
# *Duplicate: #812*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by ravenje** [comment]
Yes, duplicate #812
