### ISSUE TITLE
Full Block Phase and waypoints

### ISSUE THREAD

**Issue by HahBad** [Wurst-Imperium/Wurst-Client#1157]
this will be the best free hack client ever if it has full block phase where u can phase through caves to reach a person faction base etc, waypoints are an amazing way to mark certain locations without having to screenshot the coords.

**Comment by scriptinator** [comment]
Full block phase is impossible.

**Comment by GummiBoat** [comment]
@scriptinator "Full Block Phase" (or NoClip) is possible.

But for the future:
a) Please don't open an Issue that contains two or more enhancements.
b) Search for similar Issues.

Duplicate: #1149 & #408

**Comment by Bluscream** [comment]
# *Duplicate: #1149 & #408*

![Please search for similar Issues before submitting yours.](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by OMGchangeMYusername** [comment]
@Bluscream Thanks for confirming..
