### ISSUE TITLE
Multi-Keybinds

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1158]
on a server i play on i have multiple spawners and i farm them for xp all the time. I ALWAYS USE fightbot, Auto-Walk and Auto-Sprint. Those 3 hacks allow me to farm the grinder while afk. When i tried to set the fightbot auto-walk auto-sprint command to one Keybind, but  it wont work :( . If you could PLEASE add the feature where under keybinds u can link more than 1 hack to a single keybind that would be GREAT thankyou!

**Comment by scriptinator** [comment]
Duplicate #422
