### ISSUE TITLE
I have no idea what to call this

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#116]
add this,what ever it does
https://github.com/spacerocket/vapid/blob/master/me/pyr0byte/vapid/modules/ModuleYaw.java

**Comment by GlitchHead** [comment]
dafuq does dis do you dont have a  name to call it can well you seem to not know what is does but what if you do but you want to add this but dont want not not to do add this but if this is legit and you dont want to add remove then and export this please explain what this does.

**Comment by GlitchHead** [comment]
english please.

**Comment by pokeball99** [comment]
i think it might be something to this effect,idk looking at the source https://github.com/Wurst-Imperium/Wurst-Client/issues/84

**Comment by Alexander01998** [comment]
I already denied this in #84.
