### ISSUE TITLE
Autosoup

### ISSUE THREAD

**Issue by ScorchedSorcerer** [Wurst-Imperium/Wurst-Client#1160]
i have a bunch of different cracked servers with the soup heal thing and Wurst dosent have auto soup if wurst could have auto soup that would make peoples life easier
Thanks :)

**Comment by Alexander01998** [comment]
# *Duplicate: #83*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
