### ISSUE TITLE
.rotate command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1161]
A command to turn around directly

**Comment by GummiBoat** [comment]
How about a `.rotation <degrees>` command?

**Comment by WurstContributor** [comment]
@GummiBoat Sure.

**Comment by mcccs** [comment]
or .rotate x y

**Comment by OMGchangeMYusername** [comment]
oh that should be a better Flip,some clients have this Flip mod which rotates 180 things idk what are they called,but if the rotate amount is optional it'd be much better :+1:
