### ISSUE TITLE
Ghost mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1162]
A mod, that make you still alive after death
On death do not go to the respawn screen

**Comment by bob80333** [comment]
so....auto respawn with freecam at point of death?

**Comment by OMGchangeMYusername** [comment]
@bob80333 that's basically it,thanks for making it into words xD

**Comment by mcccs** [comment]
or godmode?

**Comment by Orcunegeacar** [comment]
@bob80333  is right.

**Comment by ravenje** [comment]
Wolfram has this function

**Comment by OMGchangeMYusername** [comment]
@ravenje we're not gonna steal it even if it does xD
but it should be "confirmed" and i think it's sorta easy to make
