### ISSUE TITLE
Making Yescheat versions seperate mod

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1165]

**Comment by OMGchangeMYusername** [comment]
More info required,i think that YesCheat+ is somehow confusing,like if the killaura is ok on this server and i want another thing to bypass,it edits every thing..
which a little confusing tbh,idk what he meant by this but i think you should change how it works.

**Comment by OMGchangeMYusername** [comment]
what about command settings? like `.killaura yeschaet+ false`? i think it's a good idea,to make things you want to be covered by YesCheat+ optional.
