### ISSUE TITLE
TNT arrow and fire arrow

### ISSUE THREAD

**Issue by 8bitPotato** [Wurst-Imperium/Wurst-Client#1166]
The TNT arrow is self explanatory. You shoot, hits thing, BOOM!
the fore arrow is when you shoot an arrow with fire enchantment on it, it sets fire to things like using flint and steel

**Comment by bob80333** [comment]
bows with flame can set things on fire AFAIK, and TNT arrows would be more of a mod, not in a hack client.  Hack clients do not add new items to the game, they bypass security and allow you to easily do damaging things to servers.

**Comment by GummiBoat** [comment]
As @bob80333 said, sadly it's impossible to add non-vanilla modifications to the game, that don't rely on the minecraft basics. (Well, it's possible, but not for a hacked client, that still wants to be able to join every server.)

And flame just can ignite TNT, but they don't (and can't) interact directly as a flint'n'steel, as they don't "place" a fireblock.

**Comment by TekkitCommando** [comment]
That might be a good suggestion for the MC Ultra client tho :P
