### ISSUE TITLE
Projectiles suggest

### ISSUE THREAD

**Issue by cooltalal111** [Wurst-Imperium/Wurst-Client#1167]
its basically a hack that makes a marker for the projectile stuff like arrows,potions,eggs and snowballs

**Comment by GummiBoat** [comment]
# *Duplicate: #168*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
