### ISSUE TITLE
Recommended Mods for Better Wurst! ( 1 Heart Regen Bind )

### ISSUE THREAD

**Issue by rakazet** [Wurst-Imperium/Wurst-Client#117]
Hey guys, rakazet here. Im a wurst user because this hacked client is the best for pvp and stuff. But something feels missing. I know you can regen hack, but it only works on few servers, 1 of them is mcsg. But when you use it, you'll get banned for 1 minute. So, why not 1 heart regen? I hope 1 heart regen can't be detected and can be activated with a single click. For example you are using kill aura and your 1 heart regen bind is left click. When you get damaged, just click left mouse button since you don't need to attack with mouse with killaura. You can always left click and get extra 1 heart. I hope you guys recommend it, thanks anyway :)

-Rakazet

**Comment by Notchshero** [comment]
Half heart! It is better

**Comment by Alexander01998** [comment]
That's not how Regen works. See #58.
