### ISSUE TITLE
kill aura fix

### ISSUE THREAD

**Issue by cooltalal111** [Wurst-Imperium/Wurst-Client#1173]
so when i  use kill aura on an entity (player,mod,etc) it lags and it suddenly look at the player's face .. it is annoying me because i lag alot and they can see that i am using it and it is just not working for me

**Comment by GummiBoat** [comment]
You can't blame the mod directly for making your minecraft lag. Try giving your minecraft [more memory space](http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/tutorials-and-faqs/1871637-tutorial-allocate-more-memory-for-minecraft), decrease your video settings, or use a low-resolution texture pack. Close everything in the background, that uses up unnecessary workspace.

**Comment by cooltalal111** [comment]
i didnt mean lag by lagging my game .. i meant lag by the llag-spike that sometimes happens

**Comment by Alexander01998** [comment]
# *Duplicate: #106*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
