### ISSUE TITLE
Invisible Players, can't hit them.

### ISSUE THREAD

**Issue by KekkoMenny** [Wurst-Imperium/Wurst-Client#1174]
![2015-07-08_11 03 17](https://cloud.githubusercontent.com/assets/13101289/8585494/c6c8cc4e-2625-11e5-86bc-07fa65681fd9.png)
![2015-07-08_17 24 33](https://cloud.githubusercontent.com/assets/13101289/8585495/c6e82058-2625-11e5-8389-2b4a2f6ad364.png)
Sometimes players become invisible and I can't hit them, the only think that can hit them is KillAura, is this my own problem??

**Comment by TekkitCommando** [comment]
Could've many reasons, idk anyone else got a solution?

**Comment by mcccs** [comment]
He/she is spectator

**Comment by KekkoMenny** [comment]
No, is not spectating, it just become invisible.

**Comment by GummiBoat** [comment]
@mcccs PlayerESP can't render People in Spectator mode.

This probably is a pretty common bug. As far as I know, it's caused by the minecraft version 1.8 and can only be fixed, with updating it. So you probably have to wait for Wurst 2.0, sorry.

**Comment by KekkoMenny** [comment]
Thanks :D
