### ISSUE TITLE
Add NBT tag to an item without being OP

### ISSUE THREAD

**Issue by ProFeeder** [Wurst-Imperium/Wurst-Client#1175]
Can you create a mod which allow a creative-mode player to add NTB tag to an item (like CrashChest, CrashItem, TrollPotion, etc)

**Comment by GummiBoat** [comment]
# *Duplicate: #342*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
