### ISSUE TITLE
Add Godmode,and antihunger

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#1176]

**Comment by GummiBoat** [comment]
That's kinda implemented. Regen & AutoEat (+FastEat). Otherwise it's not possible. And for the future, please don't open an Issue that contains multiple enhancements.

**Comment by wizardhax** [comment]
Godmode only works in older versions of NC+

**Comment by OMGchangeMYusername** [comment]
Yep and tbh i never found a server it's working on (with Huzuni and several clients that have this feature)..
servers must've known about this ages ago,i doubt you'll find a server that outdated..
