### ISSUE TITLE
Wurst Error ".Menue" Is not a valid Command

### ISSUE THREAD

**Issue by CoolRusher** [Wurst-Imperium/Wurst-Client#1177]
When I click on the left control is says ".Menue" is not a valid command. I have no clue what is wrong but when I got onto youtube and search it it seems that I'm the only one with this problem. Can someone please tell me what I need to do. Thanks!

**Comment by GummiBoat** [comment]
There is no `.menue` command. For a list of available commands, go to [this page](https://www.wurst-client.tk/wiki/Commands/).

**Comment by OMGchangeMYusername** [comment]
Did you bind ".Menue" to left ctrl? go to keybind manager and change it to ".t ClickGUI"

**Comment by CoolRusher** [comment]
Thank you, it was that I had binded it as .Menue and not .t ClickGUI.

On Thu, Jul 9, 2015 at 3:35 PM, OMGchangeMYusername <
notifications@github.com> wrote:

> Did you bind ".Menue" to left ctrl? go to keybind manager and change it to
> ".t ClickGUI"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wurst-Imperium/Wurst-Client/issues/1177#issuecomment-120137632>
> .
>

-- 


CONFIDENTIAL COMMUNICATION. THIS MESSAGE MAY NOT BE FORWARDED.

The information contained in this communication, including
any attachments, is confidential,constitutes privileged
communication, and is intended only for the use of the addressee.
This message may not be forwarded without prior consent from 
the sender. The information in this e-mail is also protected
by the rights afforded under Family Educational Rights and
Privacy Act (FERPA) and school district policies.  Any unauthorized
use, forwarding, distribution,disclosure, printing or copying is
strictly prohibited and may be unlawful.  If you have received this
communication in error, please notify us immediately at 802-879-8192
or return e-mail,and delete any copies of this message immediately.
Any inadvertent disclosure of this communication shall not compromise
the confidential nature of the communication.
