### ISSUE TITLE
Wurst 2.0 isn't auto updating

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1179]

**Comment by Alexander01998** [comment]
I made it that way when I added the auto updater and then forgot about it.

**Comment by Alexander01998** [comment]
Actually, the updater in Wurst v1.15 is disabled for some strange reason.

**Comment by Alexander01998** [comment]
As is the one in Wurst 2.0. Damnit!

**Comment by Alexander01998** [comment]
Just released v2.0.1 with a working auto-updater.

**Comment by pokeball99** [comment]
um....what was updated?from the commits u seem to just change the version from 2.0 to 2.0.1?

**Comment by Alexander01998** [comment]
[The file that broke it](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/assets/minecraft/wurst/updater) was correct in the repository, but not in the compiled Jar.
If it says `1`, the updater is enabled, if it says `0`, the updater is disabled.

**Comment by WurstContributor** [comment]
Well... That was easy.

**Comment by Alexander01998** [comment]
> Well... That was easy.

Not really. We now need to get as many people as possible to update to v2.0.1.
The only thing we have to tell them about the update are the Wurst news.

**Comment by OMGchangeMYusername** [comment]
> The only thing we have to tell them about the update are the Wurst news.

was about to say so :+1:

**Comment by WurstContributor** [comment]
@OMGchangeMYusername @Alexander01998 Or you could change it so Wurst 2.0 Users only see "Please update to Wurst 2.1 Immediately. Click here for more info"

**Comment by OMGchangeMYusername** [comment]
btw can't see news in 2.1 O.o?

**Comment by Alexander01998** [comment]
> Or you could change it so Wurst 2.0 Users only see "Please update to Wurst 2.1 Immediately. Click here for more info"

No I can't. Wurst 2.0 is already released and cannot be changed anymore.

> btw can't see news in 2.1 O.o?

Sometimes there are problems with the internet connection, restarting or reloading the main menu fixes that. Wurst 2.1 is not yet released though.

**Comment by WurstContributor** [comment]
@Alexander01998 If the news thing is connected to the internet, Can't You mess with it to do that?

**Comment by Alexander01998** [comment]
> If the news thing is connected to the internet, Can't You mess with it to do that?

I already did. The latest article is called "The Auto-Updater is broken! Please manually update to Wurst v2.0.1!".

**Comment by pokeball99** [comment]
https://img.shields.io/github/downloads/Wurst-Imperium/Wurst-Client/v1.15/total.svg
https://img.shields.io/github/downloads/Wurst-Imperium/Wurst-Client/v2.0.1/total.svg
https://img.shields.io/github/downloads/Wurst-Imperium/Wurst-Client/v2.1/total.svg

**Comment by TekkitCommando** [comment]
@Pokeball99 I think people still use wurst but don't update it even if there is an auto updater cuz they lazy

**Comment by TekkitCommando** [comment]
@pokeball99

**Comment by bob80333** [comment]
Everyone will update once minecraft has a new version.
