### ISSUE TITLE
Better Phase

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1182]
A better phase that allow to walk under blocks

(Client: Wolfram)
![s1](https://cloud.githubusercontent.com/assets/12088599/8629626/326cd9f8-275d-11e5-837e-5975b8168251.png)
![s2](https://cloud.githubusercontent.com/assets/12088599/8629632/39680b6a-275d-11e5-997c-cf750953e5b6.png)
![s3](https://cloud.githubusercontent.com/assets/12088599/8629635/3c19e3b0-275d-11e5-83a3-f4576317e23c.png)

This is not possible with wurst:
![s4](https://cloud.githubusercontent.com/assets/12088599/8629640/44b8010a-275d-11e5-937c-d5f02c6bee80.png)

**Comment by Nitrogen-Dioxide** [comment]
Resilience have this feature only. I think it is simple. put "when colided verticaly" should fix everything.

**Comment by Tropfer** [comment]
Thats Wolfram not Resielience

**Comment by OMGchangeMYusername** [comment]
@Tropfer he didn't even say that was "Resielience".. nor Resilience of course..
