### ISSUE TITLE
[I've tried EVERYTHING even your idea Alexander]

### ISSUE THREAD

**Issue by Ganjome** [Wurst-Imperium/Wurst-Client#1195]
Please do not close this thread, atleast help me without saying the exact shit i've been told about 60 times.

I've SEARCHED it. I've used method #142 I've done EVERYTHING.

I've removed my old versions with the terminal command!

Does anyone have skype or something to show me how to do it correctly?

**Comment by Ganjome** [comment]
I've also re-installed minecraft.

**Comment by Ganjome** [comment]
Also now that  I re-installed it and restarted minecraft WURST doesn't even show up in versions anymore.

http://prntscr.com/7rhdpz

**Comment by Alexander01998** [comment]
STOP!
