### ISSUE TITLE
New form of phase (noclip)

### ISSUE THREAD

**Issue by CactusOwnage** [Wurst-Imperium/Wurst-Client#1198]
A few clients have a new form of phase who would you allow to go trough blocks. You enable the mod and place sand/gravel above you. Then you are able to go where ever you want but you will take damage from suffocation.

**Comment by pokeball99** [comment]
U seem to have closed this,was this in error?

**Comment by CactusOwnage** [comment]
No, sorry I thought it was in the wrong section or something.

**Comment by Alexander01998** [comment]
# *Duplicate: #1149*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
