### ISSUE TITLE
ChestView

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1199]
the idea i'm suggesting came from playing factions where there was a chest blocked off by 2 pieces of cobblestone then i though humm maybe there is a hack client out there that allows you to view inside chest without permission or without even opening them. I also thought this would be nice if you wanted to open a chest see the chest GUI and see the items without the open chest animation. This might not be available to where u cant take items out but to see the contents would be nice :)

**Comment by PixelMaster3D** [comment]
Couldn't you add a entity scanner of what might be in there.

**Comment by PixelMaster3D** [comment]
This would be good for chest that are public to use like HG and Sky Wars. That was my next suggestion.
