### ISSUE TITLE
FuckCubik :)

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#12]
i suggest you make a tutorial on how to make models of your own :)
i really love that TNT model you made!
if you're not going to make a tutorial can you please share us that TNT model :3

**Comment by Alexander01998** [comment]
**Wrong repository** This is the *Wurst-Client* repo, not the [*Fuck-Cubik*](https://github.com/Fuck-Cubik/Fuck-Cubik) repo.
