### ISSUE TITLE
How did you recompile MCP to Java 8

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1202]
I try running recompile.bat in MCP and get this error "use -source 7 or later" (since I use a String in a Switch which requires Java 7) but where do I put that "-source 7" option? Which file in MCP and where? I assume you know this since Wurst 2.0 uses Java 8 and you must in somewhere have added that "-source 8".

**Comment by Alexander01998** [comment]
I just changed the Java version in Eclipse and MCP accepted it.

**Comment by Alexander01998** [comment]
Actually, it only accepted it for Wurst 2.0. Now with Wurst 2.1, I had to change a lot of things. Compiling a Wurst update used to be all automated, but at the moment, I am doing some of it manually.

At the moment, these are the steps I go through when compiling an update:
1. Eclipse export > Wurst.jar (without libraries)
2. Insert mc-assets (assets folder & slick library)
3. Packaging into ZIP file (that part is still automatic)

I will certainly re-automate this at some point, though.

**Comment by Murplyx** [comment]
I found it it like that also, exactly those steps. I used to compile in MCP, but I now use Eclipse which works and is 1000  times faster. TY
