### ISSUE TITLE
.addserver command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1206]
.add (name)@(server)
if (server) is not set, it add the current server

.add Gommeserver@gommehd.net
.add Greifserver1

**Comment by OMGchangeMYusername** [comment]
O,o what did you actually mean? is it about renaming the "Minecraft Server" thing above servers?

**Comment by GummiBoat** [comment]
No, he wants a command to add the current Server, or generally a server to your server list via command.

`.add <displayname> [ip]`

**Comment by ravenje** [comment]
Yes...

**Comment by Alexander01998** [comment]
`.add` could mean literally anything.
I would rather do `.addserver <ip>`.

**Comment by OMGchangeMYusername** [comment]
> `.add` could mean literally anything.

Agreed...

**Comment by mcccs** [comment]
> .add <displayname> [<ip>]
ip isn't optional.
.addserver <ip> [<name>]
