### ISSUE TITLE
Remote Veiw on the hack

### ISSUE THREAD

**Issue by BrandonMcPvp** [Wurst-Imperium/Wurst-Client#1208]
Umm why would you remote veiw and animal or a mob or a aurmer stand?! Why cant you just do that to players so you can find where there base is?! Glitch?

**Comment by bob80333** [comment]
RemoteView is for all entities.  Type in .remoteview <entity name> to spectate a specific entity/player.

**Comment by bob80333** [comment]
For clarification: .remoteview <Player Name> is the command to use for specific players.

**Comment by BrandonMcPvp** [comment]
How like is is .remoteveiw (playername)?

**Comment by TekkitCommando** [comment]
view*
