### ISSUE TITLE
Inventory Watcher

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1209]
A command that watch for a spezificy item in the inventory hotbar of a player

.invwatch id 137
.invwatch item stone
[Wurst] Found item 137 in hotbar of (player)
[Wurst] Found item stone in hotbar of (player)

**Comment by OMGchangeMYusername** [comment]
neat idea if it was to be used to find people with good gear on SG xD
but ah well.. not really necessary after all
