### ISSUE TITLE
Waypoints feature

### ISSUE THREAD

**Issue by wkuba500** [Wurst-Imperium/Wurst-Client#1215]
Like huzuni, but better! :)
.waypoint add [name]
.waypoint remove [name]
.waypoint hide [name] or .waypoint hideall
.waypoint tp [name]
.waypoints or .waypoint list

New future in .goto command:
.goto loc [location] - old
.goto waypoint [name] - new

Mini map future:
.minimap - show and hide minimap
.minimap toggle - toggle between map/caves/buildings

**Comment by GummiBoat** [comment]
# *Duplicate: #408*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
