### ISSUE TITLE
Better remote view & Inventory

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1216]
@Alexander01998 if you can... add better remote view for like players .rvp <playername>
If its possible remotely viewing inventory of someones else if your in creative.

**Comment by GummiBoat** [comment]
Remoteview is already able to target players. You need to choose "Player" or "All" in your target selection tho. (In the Click GUI at the bottom from the combat section).
It's not possible to view the full inventory of another player, the server is not giving that much information to the client, without additional plugins and permissions. But you already can use `.invsee <player>` to see the currently equipped items (Selected Hotbar Item and equipped armor) with enchantments etc.

And for the future: Please don't open an Issue, that contains multiple suggestions.
