### ISSUE TITLE
Wurst Waypoints

### ISSUE THREAD

**Issue by yoahi** [Wurst-Imperium/Wurst-Client#1218]
A waypoint mod would be similar to REI's minimap's waypoints. It would create a waypoint where you die, and would allow you to place waypoints wherever you want. (IE at a raid or base)

**Comment by Alexander01998** [comment]
# *Duplicate: #408*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
