### ISSUE TITLE
Crash glitch

### ISSUE THREAD

**Issue by momoman01** [Wurst-Imperium/Wurst-Client#1219]
In Wurst 1.4.2, most of the time when sand falls, or when gravel falls, it makes my game crash. It is like that when most fall objects like anvils. It also crashes when I go into this 1 specific lobby in servers. And It crashes when the ender dragon hits me.

**Comment by bob80333** [comment]
Why are you using Wurst 1.4.2? V2.0.1 is the latest version.  Also, we can't do anything without crash logs.

**Comment by Alexander01998** [comment]
That was all fixed long ago, just get the latest version.

**Comment by OMGchangeMYusername** [comment]
what about an "outdated" label :3 ?
