### ISSUE TITLE
Crashing When I Start Wurst

### ISSUE THREAD

**Issue by momoman01** [Wurst-Imperium/Wurst-Client#1220]
Crash Report:
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// But it works on my machine.

Time: 7/13/15 5:16 PM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 114470304 bytes (109 MB) / 314564608 bytes (299 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.32.20, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [([1.7]_Huahwi_Pack_64x stone sword fix]
	Current Language: Canadian English (Canada)
	Profiler Position: N/A (disabled)

**Comment by bob80333** [comment]
Update to java 8.

**Comment by momoman01** [comment]
I know that this is not entirely related to Wurst, but I deleted the old java, and installed the new Java 8. I know this as it says when I check the version under terminal. I have java 8 installed, but my Minecraft is not detecting it. Does someone know by any chance what I could try? (I have a MAC if you have not figured that out already.)

**Comment by bob80333** [comment]
I don't know, as @Alexander01998 has mentioned in the past
 ```
Wurst uses the terminal command java -version to find the java version.
 ```

**Comment by bob80333** [comment]
Perhaps try redownloading the launcher?

**Comment by momoman01** [comment]
I will try to fix the java later, but does anyone have the link to down load wurst 1.4.2? I deleted it, and cant find where to re download it.

**Comment by mcccs** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/releases/download/v1.4.2/Wurst-Client-v1.4.2.zip

**Comment by Alexander01998** [comment]
> does anyone have the link to down load wurst 1.4.2?

Don't download v1.4.2, get the [latest version](https://github.com/Wurst-Imperium/Wurst-Client/releases/latest)!
