### ISSUE TITLE
Fly Bypass Edit

### ISSUE THREAD

**Issue by LolrusX** [Wurst-Imperium/Wurst-Client#1222]
The "wall" that doesnt let you fly by it when you are using the fly bypass, it is actually too high. You still get set back if you go too high if you go up. If it is the right height, then i think it is not solid enough, because you can glitch through the wall kinda when you hit the ceiling and nocheat registers you as flying and you get teleported back. So either set the "ceiling" lower in the fly bypass, or make the ceiling more solid.

**Comment by GummiBoat** [comment]
Indeed, it needs to be 1 block lower than it is now, I forgot to add that to my last conclusion.

**Comment by Alexander01998** [comment]
All tested with the latest NoCheat+ build and working without any problems.

**Comment by llaurenss** [comment]
i also got teleported back

**Comment by llaurenss** [comment]
https://www.youtube.com/watch?v=mj1Z0FvySgE&feature=youtu.be

**Comment by LolrusX** [comment]
Thanks for the video lol
