### ISSUE TITLE
Client crashing while "Initializing game"

### ISSUE THREAD

**Issue by Garyz5** [Wurst-Imperium/Wurst-Client#1224]
# Hello @Alexander01998 and others!

I recently saw that there was a new release of Wurst and decided it was finally time to update. Formerly, I was using v1.3 and it was running almost perfectly(minor things here and there), but as of manually installing the latest version, the client crashing during the slash art portion of the loading screen.

I completely reinstalled my minecraft folder, and redownloaded the wurst client multiple times..I even tried downgrading to the original v2.0 and its still displaying the same issue.

Before anyone asks, YES I have verified java version.. I've manually uninstalled it, reinstalled it checked it through terminal, uninstalled it again, installed the JDK and am still encountering the same issue.

#### **Here is the detailed crash report that I am receiving:**
>---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why did you do that?

>Time: 7/14/15 2:00 AM
Description: Initializing game

>java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

>A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

>-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

>-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

>-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 136452320 bytes (130 MB) / 270647296 bytes (258 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.4.2 310.41.35f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

>	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by bob80333** [comment]
Hello!  Unfortunately, in the crash report, right below the minecraft version at the bottom, the java version is shown, and yours says:
 ```
Java Version: 1.6.0_65, Apple Inc.
 ```

**Comment by Garyz5** [comment]
damnit.. I don't understand how it didn't uninstall properly.. I followed java's website to the T and it still isn't working.

**Comment by Garyz5** [comment]
Can you explain to me why wurst/minecraft is using an older form of java when I've verified the version i truly have installed is Java 8?

![java version](https://cloud.githubusercontent.com/assets/8870054/8667782/e2534084-29d1-11e5-90f0-7987c9e0ac05.png)

**Comment by bob80333** [comment]
Try method 2 in the wiki:
https://github.com/Wurst-Imperium/Wurst-Client/wiki/Using-Wurst-with-Java-8

**Comment by Garyz5** [comment]
bob you are my hero and i love you.

![screen shot 2015-07-14 at 2 58 18 am](https://cloud.githubusercontent.com/assets/8870054/8667974/3496e560-29d4-11e5-94cc-8bc0918262d6.png)

**Comment by bob80333** [comment]
No problem  :smiley:

**Comment by Alexander01998** [comment]
A Mac user that actually **uses** the tutorial?! Mind blown. :smiley: 

We should point future duplicates to this issue instead of #142.

**Comment by Soundisimore** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/10/15 3:32 PM
Description: Initializing game

java.lang.NumberFormatException: For input string: "0�40.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at tk.wurst_client.files.FileManager.loadSliders(FileManager.java:369)
	at tk.wurst_client.gui.GuiManager.setup(GuiManager.java:197)
	at tk.wurst_client.Client.startClient(Client.java:46)
	at bsu.aj(Minecraft.java:588)
	at bsu.a(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at tk.wurst_client.files.FileManager.loadSliders(FileManager.java:369)
	at tk.wurst_client.gui.GuiManager.setup(GuiManager.java:197)
	at tk.wurst_client.Client.startClient(Client.java:46)
	at bsu.aj(Minecraft.java:588)

-- Initialization --
Details:
Stacktrace:
	at bsu.a(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:120)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 52314064 bytes (49 MB) / 241967104 bytes (230 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-8.28.32, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'Wurst'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

I tried to use .jar version but doesn't work
