### ISSUE TITLE
Fly in NoCheat+ Bypass

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#1227]
When i updated to Wurst 2.0.1 i was happy about the new flybypass. The only problem is, it works, but u get kicked for: Flying is not enabled on this Server.

Can this be fixed aswell?

**Comment by iQuintennn** [comment]
Thats a vanilla issue this cannot be fixed

**Comment by Alexander01998** [comment]
Minecraft kicks players for flying if they are not touching any blocks for at least 80 ticks (4 seconds).

There are two ways to bypass this:

1. Do not fly for more than 4 seconds.

2. Touch the ground or a wall at least every 4 seconds.
