### ISSUE TITLE
annoy doesnt work at mineplex

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#123]
annoy doesnt work at mineplex

**Comment by Notchshero** [comment]
it doesnt work at some servers. Because in some games the server adds §e or §something before the name. and i cant type .annoy §eNotchshero

**Comment by Alexander01998** [comment]
> Because in some games the server adds §e or §something before the name. and i cant type .annoy §eNotchshero

That is not the reason why it can't annoy players on Mineplex. It's because Mineplex has its own way of separating the username from the chat message.

The most common chat formats `<name> message` and `[rank] name: message` are supported in Wurst, but `random number name message` is not.
