### ISSUE TITLE
Wurst mod dropdown menu

### ISSUE THREAD

**Issue by Popper561** [Wurst-Imperium/Wurst-Client#1230]
When I press the left control button, and all the dropdown menus show up, the longer ones like combat are getting cut off on the bottom of my screen. I have them all the way at the top, but they still get cut off, so i don't know which mods I'm missing. Is there a way to change the size?

**Comment by Alexander01998** [comment]
# *Duplicate: #910*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
