### ISSUE TITLE
question - building

### ISSUE THREAD

**Issue by cooltalal111** [Wurst-Imperium/Wurst-Client#1231]
so i wanna ask you .. are there any commands for making or save custom builds ?? i want a command that saves the custom build i do and then paste it in another place/server .. any chances of having that ?

**Comment by Alexander01998** [comment]
No. That's because AutoBuild templates are more than just the blocks.
The order, the direction, etc. that the blocks were placed in matters as well.
See #245 for how to make AutoBuild templates.
