### ISSUE TITLE
Flybypass up dosn't work

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1235]
I tested fly bypass on my ncp server and it dosn't work

Here i fly:
![fly1](https://cloud.githubusercontent.com/assets/12088599/8681585/b2f268f0-2a68-11e5-9832-0e32087f0962.png)
And then i pressed space:
![fly3](https://cloud.githubusercontent.com/assets/12088599/8681635/fef1beae-2a68-11e5-93a7-29bc8e3ade4a.png)

Then it teleports me back :(

**Comment by ravenje** [comment]
This is so on all ncp servers :(

**Comment by OMGchangeMYusername** [comment]
I think you shouldn't go up. I might be misunderstanding tho.

**Comment by GummiBoat** [comment]
No, you CAN go up with the new bypass, but not higher than from where you started.

**Comment by OMGchangeMYusername** [comment]
that doesn't make sense... that basically means you can't go up.. No?

**Comment by GummiBoat** [comment]
As i said, not higher than from the point where you started. but you can go up. For example, You start on height 100. You fall down 10 Blocks, now you are on 90. As long as you don't reach 1.01 blocks over from where you started (that makes 98.99), you can fly upwards and NCP won't react.

**Comment by Alexander01998** [comment]
Duplicate: #1222
