### ISSUE TITLE
Reach mod

### ISSUE THREAD

**Issue by HeartOfShrapnel** [Wurst-Imperium/Wurst-Client#1236]
I was thinking that the client could add a toggle-able mod that would extend your reach, put in combination with some other mods that may/may not be implemented it could be quite useful (hitting players through walls, opening chests from far away, etc). Commands like .reach (number) or .r (#) etc would work to change how far your reach would be. 

![image](https://cloud.githubusercontent.com/assets/13339661/8685312/b1f2d6fa-2a4b-11e5-8e9e-b3e1c81de6f8.png)

^ Example

**Comment by GummiBoat** [comment]
I don't know if it's still possible (I thought that Minecraft patched that a while ago), but if it still is possible, it would come in handy as a slider in the Settings-Tab (Click-GUI) and a regular mod...

Btw, currently you should be able to achieve that by turning on Blink, flying to your target, hit it, turning Blink off and repeating that process. Kinda slow, but it should work...

**Comment by OMGchangeMYusername** [comment]
Thanks for the tip :D

**Comment by mcccs** [comment]
> Btw, currently you should be able to achieve that by turning on Blink, flying to your target, hit it, turning Blink off and repeating that process. Kinda slow, but it should work...

Nope, turn on blink fly to your target turn off, then attack

**Comment by OMGchangeMYusername** [comment]
didn't get to try it because my kwyboard is broken.. i cri nau :sob:

**Comment by Alexander01998** [comment]
Reach is patched.
