### ISSUE TITLE
ReverseAutotool ?

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1239]
This is a mod suggestion to add an option to Autotool, or a separate mod, to have the Autotool change its behaviour. Basically it would reverse the tool priority to consume lower-grade tools first, preferring wood over diamond, and unenchanted (don't know if it is accounted in autotool) over unenchanted.

In my mind this works like: if for example I have boh a stone pick and a diamond one: the stone one gets used first, unless the diamond one is selected.

**Comment by bob80333** [comment]
I would say make it a separate mod because the current autotool mod uses minecraft's internal effectiveness values and finds the highest one in the hotbar.

**Comment by haykam** [comment]
Maybe also choose lowest durability first also?
