### ISSUE TITLE
AutoTool could fetch tools also from inventory

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1240]
It would be cool if we could use Autotool without having to have the tools in the hotbar.

**Comment by bob80333** [comment]
I have a add-on suggestion for how it would work:
Open a new inventory windows, but empty, and without the crafting/armor.  Instead, have color selection where crafting/armor is.  Click on a color, then click on 1 hotbar slot and associated inventory slots.  They should become colored.  the mod now checks when the tool is @ 1 use left for the next tool to use of the same color.

**Comment by bob80333** [comment]
Or maybe instead of colors, have icons for every kind of tool?

**Comment by GummiBoat** [comment]
@bob80333 That's way too complicated, and you can't open new inventory windows as a client.

It should be simply what beppe said. It is able to take Items out of the Inventory. No need to get too complicated.

**Comment by beppe9000** [comment]
i was thinking of something more straight-forward: simply checking if there is any tool which is better than the best one in the hotbar, swapping them (i think we cannot use things from inventory direcly right?) and then use it.

**Comment by OMGchangeMYusername** [comment]
- **Don't put a dot at the end.** It's a headline, not a sentence.

Did you read the [Contributing guidelines] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md#issues)? It makes things easier.

**Comment by beppe9000** [comment]
@OMGchangeMYusername It was unintentional (my keyboard app puts it at the end of each phrase).

**Comment by OMGchangeMYusername** [comment]
I'm not blaming you, but be sure to read the guidelines before opening an issue, it makes it easier as i said. You see we're having problems at dealing with issues, especially the duplicates..
Take Optifine as an example,search for the second issue in this repository, you'll see what a i mean.
