### ISSUE TITLE
add rate option for Autobuild 

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1241]
I noticed that autobuild and instant bunker fail and only a block is placed.

**Comment by GummiBoat** [comment]
If the Server has NoCheat+, it'll block that you place blocks that fast. Try using YesCheat+. That should fix the problem. It's a bit slower, but it works.

**Comment by beppe9000** [comment]
also, is there any option for inputting stucture schematics? maybe that should be a separate structure building /replication mod?

**Comment by OMGchangeMYusername** [comment]
You can do so,by navigating to minecraft/Wurst and then autobuild custom,but you must be familiar with json first.

**Comment by beppe9000** [comment]
@OMGchangeMYusername can you point me to something documenting the syntax (not for json, but for block location)? Those coords look like are relative to the triggering block...

**Comment by Alexander01998** [comment]
> can you point me to something documenting the syntax (not for json, but for block location)?

#245
