### ISSUE TITLE
"Cannot contact authenticaiton server!" When adding alts

### ISSUE THREAD

**Issue by ilyaV1234** [Wurst-Imperium/Wurst-Client#1242]
Whenever I log in with my alt I get this error message. 
<img width="1792" alt="screen_shot_5" src="https://cloud.githubusercontent.com/assets/12741216/8711882/e4121dac-2b0a-11e5-89d5-e36bf50060d1.png">

My network monitor shows that it does contacts authserver.mojang.com . Does it mean their servers have blocked my IP or something? idk what I'm talking about, does anyone know why this happens?

**Comment by OMGchangeMYusername** [comment]
I think yes. they might've blocked your IP and you'll have to wait some time to get it working again.
i've heard that an account gets banned when used by over 10 IP's.. But it might be not true tho..

**Comment by GummiBoat** [comment]
Mojang blocks IPs that log in to too many different Accounts for 24 hours. Just wait a day, and you can log in again via Alt Manager.

**Comment by ilyaV1234** [comment]
I'll just use a VPN.
