### ISSUE TITLE
Proximity block highlighting 

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1243]
Many servers employ anti-xray methods that hide minerals if their distance to the player is beyond an arbitrary radius, so i conceived this mod... It would colorize visible blocks based on their distance to a block of a configured type (eg. diamonds). So if a block is directly touching a diamond ore it would be full green,else it would have some fainter green shade on it.

Also, having a configurable threshold for not colorizing the block would certainly be useful, along its main two settings (block type and max radius)

**Comment by OMGchangeMYusername** [comment]
I'd be glad if this goes well, I'm having problems with Anit X-ay plugins too..

**Comment by beppe9000** [comment]
Also, I find navigating in Minecraft with x-ray enabled isn't that great...

**Comment by OMGchangeMYusername** [comment]
That's why #1221 :+1:

**Comment by GummiBoat** [comment]
That's not possible. Anti X-Ray Plugins work, by manipulating the Chunk-Downloads that your Client does constantly. And if the Server doesn't tell you if there are Blocks at all, you can't test if it is touching a block or not.

For Example: We have the Structure (O Diamond X Stone)

XXXXX
XOOOX
XOXXX
XXXXX

Alright? So, now the XRay Plugin kicks in and says "ey! yo! dat diamond is not visible yet! i'mma change that to something else!" (the original block is stored inside the plugins data) So now it looks like

XXXXX
XXXXX
XXXXX
XXXXX

Now the server says, "Alright, thank you for your patience dear client, here is your chunk!" And that doesn't change until the XRay Plugin kicks in and says "ey! yo! dat diamond is visible! change it back!" and then it'll reset it back again to the first structure.

I hope you understand now, why your Idea is good, but it's sadly not possible.

**Comment by OMGchangeMYusername** [comment]
:cry: :cry:.. :sob:

**Comment by beppe9000** [comment]
Err, but I have seen certain servers (keinett prison) leave some margin between the "is visible" state and the "not yet", I think to compensate for lag, so theoretically this could be still possible on select servers. Not on every one tough :(

**Comment by OMGchangeMYusername** [comment]
but keinett is 1.7...

**Comment by GummiBoat** [comment]
No, the most "Anti Xray Plugins" currently try to be leightweight as much as possible, and they say, "as long as there is not air touching them, replace them with stone". That's why you sometimes see ores even on "Anti XRay Servers".
