### ISSUE TITLE
JokeArmor

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1245]
Moves your armor from armorslots to inventory. If someone tries to kill Wurst, Automagically wears armor

**Comment by Meylama** [comment]
Or to explain it right: It moves all your armor to the inventory, and if an other player comes into your range (like 10 or 15 blocks around you) it turns on the armor as fast as it can (NCP bypassing). This allows you to trick other players. They think that you have no armor, then they try to attack you, and then it turns on your armor and you can kill them.

**Comment by mcccs** [comment]
:+1:

**Comment by ravenje** [comment]
Nice idea

**Comment by ayciate** [comment]
would love to see

**Comment by PixelMaster3D** [comment]
True, but only trying to bypass nocheatplus or other up-to-date anti-hacks wouldn't allow this. Remember servers are always watching you and Logging Data for every minute made.
