### ISSUE TITLE
Error when enchanting with AutoArmor enabled

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1246]
https://gist.github.com/anonymous/dd770f880f721eec8148
![crash](https://cloud.githubusercontent.com/assets/11584045/8725402/b84f0b3a-2bdc-11e5-9ed9-e20c9ffaeb82.gif)

**Comment by GummiBoat** [comment]
If you let Wurst send the Error Report, it should land [here](https://www.wurst-client.tk/error-reports/) automatically. You don't need to open an Issue for that. :smiley:

**Comment by mcccs** [comment]
NOPE, i can't see it. I knew, but my problem is not xray

**Comment by EnderGamer21** [comment]
u have no lapis

**Comment by OMGchangeMYusername** [comment]
> u have no lapis

u sure?

**Comment by EnderGamer21** [comment]
yeah

**Comment by OMGchangeMYusername** [comment]
Lol It's not about whether he can enchant or not. The problem is that Autoarmor places armor when it's in you hotbar.

**Comment by EnderGamer21** [comment]
PLaces armor where

**Comment by EnderGamer21** [comment]
oh on the enchnat tabel

**Comment by OMGchangeMYusername** [comment]
yeah
