### ISSUE TITLE
Question: What are Emergency Messages for?

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1247]
345b25da65ac3a3384575b86afe56339c6484af7

Are they "news" sent by you to all players playing with wurst?
And how annoying are they? Just a normal MC chat MSG or a popup window?

**Comment by GummiBoat** [comment]
No, they are (as they say) probably emergency messages for situations, like the one we had with Wurst 2.0, that the Auto Updater isn't working. So in the future, if anything crazy happens, he can always send an emergency message, containing probably just an Update link.

And it is a message that pops up similar to the current Bug screen, inside Minecraft.

**Comment by mcccs** [comment]
Or an April 1 Joke

XD

**Comment by Alexander01998** [comment]
The message appears on startup, just like the old updater messages did.
