### ISSUE TITLE
NoRender

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1248]
First: NoRender was already suggested, but nobody could explain what it does, so it seems to be rejected.

Maybe some of you already experienced that: You are griefing a base, and the player has ~20 chests in his base. The chests are all full. Now you enable the nuker which nukes the chests. Because you nuke ~20 chests which are all full, it drops many items to the ground which lag you client and drop your FPS down to 10-15 (I experienced this yesterday). If you now enable the mod "NoRender", it stops rendering very laggy thinks, like this items on the ground. With NoRender enabled, you will still have 200 to 400 FPS. This is what NoRender does.

Maybe it would be possible to implement this, the primal thing of this mod is that it stops the rendering of items on the ground.

**Comment by mcccs** [comment]
So, you say: ALEXANDER IWANT THIS THING WHYDONTT YOU ADDD!

And everyone knows how 2 use it

**Comment by Alexander01998** [comment]
Duplicate: #593
