### ISSUE TITLE
PluginDiscover / PluginFinder [is working!]

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1249]
PluginDiscover / PluginFinder is a mod/hack which allows you to see which plugins a server has also if you have no permission for /plugins, /pl, etc.

This works on 90% of the servers, or basically on every server where you have tab complete.
Here is an example source code: http://hastebin.com/efedelixoh.avrasm

Like you can write "/noch" in chat and press the TAB key, and it completes it to "/nocheatplus" if the server has NoCheatPlus and the tab complete is not disabled, this mod does this but with the difference that it can print you all plugins in a clear list instead of a dump of commands like if you use "/" and TAB.

This feature would be nice because you can see which plugins or which anti-cheat plugins a server has, and also, if the server has a rollback plugin like LogBlock if you want to grief.

**Comment by GummiBoat** [comment]
I'd appreciate an implemtation, that makes things so much easier, than tabbing through the commands for an hour to know what exactly the server has.

**Comment by Alexander01998** [comment]
# *Duplicate: #431*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
