### ISSUE TITLE
ClickGUI keybind still resets on startup

### ISSUE THREAD

**Issue by Clean0nion** [Wurst-Imperium/Wurst-Client#125]
ClickGUI keybind reverts to LCONTROL each time Wurst is booted up. All other keybinds are fine.

Wurst: 1.6.1
OS: Windows 7
Java: Version 8 Update 31 (vendor Oracle Corporation)
RAM: 6GB
Bit: 64bit

I'd tell you what my default charset is but I don't know how to find out.

**Comment by Alexander01998** [comment]
Duplicate: #90
