### ISSUE TITLE
XRay Ore Percentages

### ISSUE THREAD

**Issue by bob80333** [Wurst-Imperium/Wurst-Client#1250]
Servers with plugins such as LogBlock can record the percentages of ores and other blocks mined
  Moderators can use this as evidence for banning/kicking an XRayer.  This addition would record block mined percentages for each server, and display this when XRay is enabled.  This would allow players to know if their percentages are skewed and to mine more stone.

**Comment by Bluscream** [comment]
Good idea for "vanilla" gamemodes ^^
