### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by bibbster777** [Wurst-Imperium/Wurst-Client#1252]
![crash-2015-07-16_10 24 15-client](https://cloud.githubusercontent.com/assets/13369372/8730390/32fa26c2-2ba5-11e5-8b3f-88c41fb66f85.png)
Not sure why it crashed.

**Comment by mcccs** [comment]
#1224 99% if mac

**Comment by GummiBoat** [comment]
The link to the picture is broken. Please copy and paste the error log properly.

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
