### ISSUE TITLE
Crypt Speak

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#1253]
I know that Java has native cryptography libraries, so this should be not so hard.
So, if we encrypt the string that is sent to the server on the chat, and only wurst users have the key? This should be very cool and funny.

The translated message should have an warning that it was from a wurst user. Oh, and if the message is a command it should ignore the command, like send "/r and .say" in a normal way.

The only problem, is that the encrypted messages should have less length because when you encrypt stuff, it becomes larger. I think there are different types of encrypt, so, some can be not so larger.

**Comment by bob80333** [comment]
Might get muted for spam though  :worried:

**Comment by Nitrogen-Dioxide** [comment]
@bob80333 na xD sometimes I send <random string 100> and anyone cares

**Comment by Alexander01998** [comment]
I thought about a feature like this long ago, but I could never find a good way to send the key to the other players.

What I thought of:

Idea|Reason why it failed
:---|:---
sending the key with `/tell`|admins can see it
copying the key to the clipboard so that the user could send it securely|OK, but makes broadcasting messages to all Wurst users impossible
`/tell <key>` to everyone so that all Wurst users see it|everyone else sees it as well
somehow detecting if others use Wurst before sending the key|servers could detect it as well

**Comment by bob80333** [comment]
Put the keypair in the code?

**Comment by GummiBoat** [comment]
Yes, I think putting the Key in front or at the end of the message shouldn't be obviously, as long as the key is not "SecretWurstKey" :smile:

**Comment by Meylama** [comment]
Or a masterserver is distributing the key to all Wurst clients, and the masterserver changes the key to another random key all 20 minutes.

**Comment by bob80333** [comment]
Send the key with the news every day and have the client save it to a text file in the .minecraft/Wurst folder?

**Comment by Meylama** [comment]
Yes, there are so many good ideas....

**Comment by Alexander01998** [comment]
Idea|Reason why it failed
:---|:---
putting the key into the source code|super easy to detect
putting the key in front of the message|super easy to detect
"masterserver" sending the keys to all Wurst clients|I don't have a "masterserver" that could do this
sending the key with the Wurst news|1. ruins the Wurst news 2. I would have to manually put it there every day

**Comment by bob80333** [comment]
New section of wurst website instead of news then, and make a script to auto generate and post new key every day.

**Comment by Alexander01998** [comment]
> New section of wurst website instead of news then, and make a script to auto generate and post new key every day.

Same as "masterserver".

**Comment by Meylama** [comment]
What do you have with your "super easy to detect"?! It is a kind of fun feature, and it is NOT to send anybody your address or any other private data about you. Because of this, it would not matter if anybody could "crack" the Wurst chat encryption.

**Comment by bob80333** [comment]
Admins would know who is using Wurst, and know who to ban for using a hacked client.

**Comment by Meylama** [comment]
@bob80333 every Wurst user could decide if he would like to use this feature (and have this risk) or if he would like to disable it and have no risk.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
Your site can't execute a internal script all the time?
