### ISSUE TITLE
Minecraft crashes before even getting into menu

### ISSUE THREAD

**Issue by lemonsand** [Wurst-Imperium/Wurst-Client#1254]
I have MacBook Pro but this issue never happened with any other client, Wrust seems interesting and i really hope you find solution this to everyone to enjoy.

**Comment by bob80333** [comment]
The 3rd today!  Please post the crash log, but 99% of the time Mac issues are old Java issues.  Refer to #1224 on how to update to Java 8.  Wurst requires Java 8.

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
