### ISSUE TITLE
Can´t start Wurst-Bot

### ISSUE THREAD

**Issue by IanJam22** [Wurst-Imperium/Wurst-Client#1255]
It says: Error:Couldn´t find or load net.minecraft.client.main
Please fix it i want to use it it is very cool

**Comment by GummiBoat** [comment]
# *Duplicate: #1070*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
