### ISSUE TITLE
Fixed Java 6/7/8

### ISSUE THREAD

**Issue by Philamusant009** [Wurst-Imperium/Wurst-Client#1256]
Hi, sooner this day I asked why my Wurst didn't work. It was because Minecraft wouldn't use Java 8. But I've came with a solution. If the minecraft.app use 1.6(it's because Mojang only have done a launcher in .exe that support Java 8), the minecraft.jar(linux version) don't. So all you got to do is go the http://minecraft.net  go to the download page, click on Show all platforms and you're done !

**Comment by mcccs** [comment]
Did you ask for this?: 
![ekran alintisi](https://cloud.githubusercontent.com/assets/11584045/8742328/ebfd9524-2c6c-11e5-945c-a6c9f198f85c.PNG)
or: Wurst needs java 8 because it has alt encryption?

**Comment by Philamusant009** [comment]
Yes, but the minecraft.APP will only take JRE 1.6  If you want to use Wurst, you need to download the minecraft.JAR, which will use your newest java version(java -version)
