### ISSUE TITLE
Wurst-Client Forums

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1258]
i think everyone would like wurst forums we can disusss what we will hack and what servers we will grief. Alexander01998 will choose what threads we can do like General Discussion 

Minecraft griefing and other stuff.

**Comment by pokeball99** [comment]
Probably would be rejected because that kinda crap takes a lot of maintenance

**Comment by TekkitCommando** [comment]
That's why you get community moderators

**Comment by pokeball99** [comment]
Like the moderators that would be in the wurst IRC?

**Comment by TekkitCommando** [comment]
Yes

**Comment by TekkitCommando** [comment]
Wurst has a large community

**Comment by Alexander01998** [comment]
> because that kinda crap takes a lot of maintenance

and because I just don't like forums.

**Comment by Bluscream** [comment]
Dont u hate social contact at all? :D

**Comment by Alexander01998** [comment]
No.

**Comment by TekkitCommando** [comment]
I think he just doesn't want to setup the software xD lol jk

**Comment by OMGchangeMYusername** [comment]
I also agree with poke and Alexander, forums would take more effort and Github is tons better&easier.

**Comment by GlitchHead** [comment]
IRC will be better

**Comment by Alexander01998** [comment]
> IRC will be better

IRCs are even harder to maintain: You need a good host, enough admins to watch it 24/7, a working AntiSpam plugin and you can't really ban spammers because they can change their name.
