### ISSUE TITLE
Manual Blink

### ISSUE THREAD

**Issue by Notchsheroo** [Wurst-Imperium/Wurst-Client#126]
Blink with start & stop buttons or changeable time limit (default is 3s).

**Comment by MisterQuatsch** [comment]
I realy hope somthin like this come to the client.
Because i dont realy like this Blink now.
But i want something when you press "b" there is a clone like in freecam and when you press it again its jump to you current position.

**Comment by trollmad3** [comment]
Good idea! :smile:
