### ISSUE TITLE
Bug With Opening The HackPage

### ISSUE THREAD

**Issue by NightSkys** [Wurst-Imperium/Wurst-Client#1260]
i cant open up the page with all the hacks on it help

**Comment by UnidentifiedProfile** [comment]
Esc > Wurst Options > Keybinds > If you see clickgui anywhere just hit edit, if you don't, click "new keybind", set the bind, and in the text box type .t clickgui

**Comment by GummiBoat** [comment]
# *Duplicate: #545*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
