### ISSUE TITLE
Spammer causing crashes

### ISSUE THREAD

**Issue by sh-t** [Wurst-Imperium/Wurst-Client#1261]
Whenever I use the spammer for any relatively low-duty spamming, it crashes after displaying the first message and the RAM usage spikes. No matter how much RAM I allocate, it always does this. Just freezes up until it crashes or I force it to exit.

Running Java 8 on Windows 7.

**Comment by pokeball99** [comment]
Please provide a crash log before creating issue

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.
