### ISSUE TITLE
SkinBlinker Bug

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1264]
If I disable the SkinBlinker feature, all layers of the skin are off and have to be manually re-enabled. SkinBlinker should save which layers of the skin are enabled and then restore this if SkinBlinker is disabled.

**Comment by mcccs** [comment]
Yeah, i can confirm that

**Comment by mcccs** [comment]
@Override
+	public void onDisable()
+	{
+		WurstClient.INSTANCE.eventManager.remove(UpdateListener.class, this);
+		for(EnumPlayerModelParts part : EnumPlayerModelParts.values())
+	//		Minecraft.getMinecraft().gameSettings.func_178878_a(part, true);
+	}
changng false to true may fix it, but not tested.

**Comment by OMGchangeMYusername** [comment]
Override will come here and say "hello" :P 
You don't know how to make a code block o.O?

**Comment by Bluscream** [comment]
```
@Override

public void onDisable()
{
WurstClient.INSTANCE.eventManager.remove(UpdateListener.class, this);
for(EnumPlayerModelParts part : EnumPlayerModelParts.values())
// Minecraft.getMinecraft().gameSettings.func_178878_a(part, true);
} // changing false to true may fix it, but not tested.
```

**Comment by Bluscream** [comment]
^ @mcccs ^
