### ISSUE TITLE
Public google analytics?

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1269]
So can we check how many Wurst users popular mods and stuff?

**Comment by mcccs** [comment]
So, do you want Alexander give his Google Password? No way.

**Comment by TekkitCommando** [comment]
lol

**Comment by WurstContributor** [comment]
@mcccs Im not asking him to give away his google password xD

**Comment by Alexander01998** [comment]
> So can we check how many Wurst users popular mods and stuff?

No, but I share the stats sometimes:

![popular Wurst Client mods](https://cloud.githubusercontent.com/assets/10100202/8754188/ff437cb6-2cc1-11e5-9404-abc98934b666.png)

![popular Wurst Client commands](https://cloud.githubusercontent.com/assets/10100202/8754186/ff01f52a-2cc1-11e5-9a48-90bd57dca3e3.png)

**Comment by Bluscream** [comment]
https://github.com/Wurst-Imperium/wurst-client.tk/pull/23

**Comment by mcccs** [comment]
WOW! Thx.
