### ISSUE TITLE
Double Ladder / Ladder Jump / Ladder Skip

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1270]
![2015-07-17_19 11 57](https://cloud.githubusercontent.com/assets/3318223/8752939/e7cabdec-2cb7-11e5-9cfe-98ca949e0aec.png)

I would love to have that mod that uses fly or something to skip 1 ladder to come to the next one.

**Comment by Alexander01998** [comment]
I have no idea how that works.

**Comment by GummiBoat** [comment]
Spider already does that.

![spider](https://cloud.githubusercontent.com/assets/10976441/8754844/9eedf5ee-2cc6-11e5-8a98-3e17509202f9.gif)

**Comment by Bluscream** [comment]
But spider isn't bypassing NCP i thought? :o

**Comment by GummiBoat** [comment]
This way of using spider is bypassing NCP.

![spiderncp](https://cloud.githubusercontent.com/assets/10976441/8757252/ec3dd118-2cd8-11e5-8aa4-ded798e9c22a.gif)

**Comment by Bluscream** [comment]
Nice, thanks for the info ^^

You love dat gif-maker, dont u? :D

**Comment by GummiBoat** [comment]
> You love dat gif-maker, dont u? :D

Well, of course, it makes things so much easier...

**Comment by Bluscream** [comment]
But its still somehow complicated to use spider when you're in a mobat situation. Much clients have it as toggable mod so if you are on a ladder and there is another ladder 2 blocks above you it will skip the "non-ladder" block automatically. this also works for the green plants. idk how they're called in english right now, lel

**Comment by GummiBoat** [comment]
They are called vines. Well, then keybind Spider... shouldn't be that hard...

**Comment by Bluscream** [comment]
![file_size](https://cloud.githubusercontent.com/assets/3318223/8762149/d09a59a2-2d70-11e5-8a99-ced5e65764a5.jpg)
![file_size_git](https://cloud.githubusercontent.com/assets/3318223/8762151/d3e5538c-2d70-11e5-822b-0f7f53d602b2.jpg)

------
![gyazo_gif](http://i.gyazo.com/2cdb2b7ba433fcff116e78b9917be18e.gif)

**Comment by GummiBoat** [comment]
Well, I'll add that to the Mods Information in the Wiki once I have the motivation to start it *sigh*

But we can't just make the complete mod NCP compatible, because currently it's not completely compatible.

**Comment by Bluscream** [comment]
> But we can't just make the complete mod NCP compatible, because currently it's not completely compatible.
Thats why i said
> Spider should be **half **NCP+ compatible then.
