### ISSUE TITLE
RangeESP

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1271]
A mod that draws a red line beforce the player shows the max attack/break range

**Comment by Bluscream** [comment]
I would love having is as a cube instead so you have a half-transparent cube around your body showing you how far you can reach with a attack for example.

**Comment by GummiBoat** [comment]
I think a circle is more fitting, because your range isn't cubic..

**Comment by Bluscream** [comment]
?

**Comment by GummiBoat** [comment]
@Bluscream Originally you had "cube" in your comment, I know it! :D

**Comment by bob80333** [comment]
[Sssh..](https://goo.gl/photos/DNPyEkPtfUMod3xq7)
