### ISSUE TITLE
Full GUI doesn't show

### ISSUE THREAD

**Issue by Kingtheempire** [Wurst-Imperium/Wurst-Client#1274]
Not all of the GUI shows and I am not able to use the cheats that are out of reach.
Graphics Information: AMD E2-1800 APU with Radeon HD Graphics 32-bits
Here are some screenshots showing what I see.
![screenshot 14](https://cloud.githubusercontent.com/assets/13384960/8754194/96d6cf0c-2c76-11e5-9973-cebe08d372b9.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/13384960/8754315/86b8cc50-2c77-11e5-88ef-4bfc645c7a93.png)
Also on a side note, trying to go on fullscreen via the video settings crashes the game.
The game output is below but i'm not if it says anything about the crash.

AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
11:38:40.700 [Thread-7] ERROR net.minecraft.client.audio.SoundManager - Error in class 'LibraryLWJGLOpenAL'
11:38:40.716 [Thread-7] ERROR net.minecraft.client.audio.SoundManager - Unable to initialize OpenAL.  Probable cause: OpenAL not supported.

**Comment by GummiBoat** [comment]
Adjust your regular Minecraft GUI Size, and the Wurst GUI will scale together with it.

**Comment by Kingtheempire** [comment]
Thanks, it works now, but only if the screen is maximized otherwise it's normal. Also what about the full screen crash?

**Comment by Alexander01998** [comment]
> Also what about the full screen crash?

The snippet you posted does not contain any information about a crash. As a rule of thumb, you should always post the complete crash log and put it into a Markdown code block.
