### ISSUE TITLE
NoCheat+ compatible NoSlowdown

### ISSUE THREAD

**Issue by Pkgts** [Wurst-Imperium/Wurst-Client#1275]
some things are blocked by ncp in slowdown, but moving while eating food and charging bows isnt. Maybe right clicking the command in the gui could let us choose what we cant no slowdown to work on? would help when on yeschest but want to move fast while charging bows

**Comment by GummiBoat** [comment]
I think a slider or command would be too much, it should be easier to just make NoSlowdown partially YesChat+ compatible.

**Comment by Meylama** [comment]
Here are two code examples for you how to make a NC+ bypassing NoSlowdown:

http://hastebin.com/osinifepak.java
http://hastebin.com/wiritategi.axapta
