### ISSUE TITLE
[Paste] Button on Signs

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1276]
a [Paste] button under the [Done] button on a sign, that paste text that copied with Ctl+c
because Ctl+V dosn't work on signs

**Comment by GummiBoat** [comment]
This is already implemented as `AutoSign`.

**Comment by ravenje** [comment]
No, why?

**Comment by GummiBoat** [comment]
Sure, it is o.o Activate AutoSign, Place one, write your text and then keep placing signs...

**Comment by ravenje** [comment]
No

**Comment by ravenje** [comment]
@Alexander01998 i mean for copy test from a text file and paste it on a sign
