### ISSUE TITLE
Survival sign op

### ISSUE THREAD

**Issue by wizardhax** [Wurst-Imperium/Wurst-Client#1277]
Could you make a vanilla survival sign-op for 1.8.3-
Flare has this feature it would be cool if you added it aswell :smile:

**Comment by GummiBoat** [comment]
Flare is 1.7.10

**Comment by wizardhax** [comment]
This feature was added in Flare 3.3

**Comment by GummiBoat** [comment]
Not even Flare 3.3 is debofuscated completely yet, and the one that originally did the work on it, stopped it.

**Comment by MyzticalTekkno** [comment]
@wizardhax you sure the feature added on flare 3 3?
@GummiBoat ur wrong XD, it is cracked now (Because flare have rare hacks, Flare Cracks rarely seen on google), and dont download from a guy named saladman, it has ~~RAT

**Comment by MyzticalTekkno** [comment]
heres a proof from a dude i trusted. ???: "If you downloaded and ran the jar uploaded by "saladman" on LeakForums, you have been infected!"

**Comment by GummiBoat** [comment]
@MyzticalTekkno Cracked and Deobfuscated are two completely different things.

**Comment by MyzticalTekkno** [comment]
yo gummi but i found a forum that have flare 3.3 cracked+rat-deob ( idk what that means XD)

**Comment by GummiBoat** [comment]
You don't need to make sure it's safe, since I won't be running it. And if you mean the HentaiEcchi Forum, I already was there.

**Comment by MyzticalTekkno** [comment]
didnt know you were there XD

**Comment by MyzticalTekkno** [comment]
wow it does have survival sign op :O


2015-07-19 3:13 GMT+08:00 BuddelBude <notifications@github.com>:

**Comment by Meylama** [comment]
@MyzticalTekkno: "but i found a forum that have flare 3.3 cracked+rat-deob ( idk what that means XD)"

cracked = you don't have to pay the original client, you can use is without buying it
deob = the source code is deobfuscated
rat (in this case) = they put the RAT from saladmans release deobfuscated and disabled into the ZIP file if you want to analyse the RAT.

**Comment by MyzticalTekkno** [comment]
they have cool hacks tho, but wurst is cooler :smile:

**Comment by wizardhax** [comment]
I didn't mean to click that button :P

**Comment by Elviond** [comment]
Can you share the link ? I'll try to check if it is clean with Cuckoo

**Comment by wizardhax** [comment]
Here's the link: https://mega.nz/#!UxUkmbgS!BzZzGH99Z3iAX_WQRZpMmMJfvWEl2OnFh4uobCvO7Ag

**Comment by MyzticalTekkno** [comment]
i test the hacked client, it was pretty good and cool, but the survival sign op is rarely worked on servers : \, this way and wurst's way is pretty hard, because your main point is getting op with hacks and those hacks are rarely usable in some server.

**Comment by Elviond** [comment]
Be careful with this link, it attempts to detect my virtual environment through the presence of a library and a file

**Comment by wizardhax** [comment]
Have you forgotten about this suggestion?
