### ISSUE TITLE
Combat List Not Short Enough To Fit

### ISSUE THREAD

**Issue by AssassinAvid** [Wurst-Imperium/Wurst-Client#1278]
The Combat mod list doesn't fit to where I can select mobs, only Players fits.
![2015-07-17_17 51 29](https://cloud.githubusercontent.com/assets/13387083/8757933/82ae573a-2cac-11e5-8a1c-9afd8ca6a32f.png)

**Comment by GummiBoat** [comment]
# *Duplicate: #1274*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Alexander01998** [comment]
Not a duplicate, this time it's actually too long.

**Comment by mcccs** [comment]
What's you screen resoulution?

**Comment by PixelMaster3D** [comment]
Looks like a 32 or 16 bit resolution.

**Comment by PixelMaster3D** [comment]
Mines 32 so I guess that's what the screen looks like.

**Comment by Alexander01998** [comment]
Fixed in #1515.
