### ISSUE TITLE
better pwnage

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#128]
Spawns 1-20 players. Then wurst command menu appears. "What will they do?"

Commands:

- Follow me
- type a command
- repeat what i say
- mine
- attack people which i attacked.
- use fight bot and kill users
- use autofish
- do what i do
- make a talking-scenario

**Comment by Alexander01998** [comment]
Exactly what I planned to do when I added Pwnage.

However, because Pwnage is still far from being finished and the development of it has been paused for an unknown period of time, that will have to wait.

**Comment by GlitchHead** [comment]
Lol you should just use darkbot or just copy darkbot stuff in pwnage and command them in wurst commands

**Comment by Alexander01998** [comment]
> Lol you should just use darkbot or just copy darkbot stuff in pwnage and command them in wurst commands

We will see when I get back to working on Pwnage. I'll probably need to rewrite some of the DarkBot code to make it integrate nicely with Wurst.

**Comment by Notchshero** [comment]
Here is it:
https://github.com/DarkStorm652/DarkBot

**Comment by Alexander01998** [comment]
> Here is it:
> https://github.com/DarkStorm652/DarkBot

I know. I have seen DarkBot before.
