### ISSUE TITLE
Make AutoArmor NCP+ compatible

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1281]
![autoarmor_ncp](https://cloud.githubusercontent.com/assets/3318223/8759631/d20d4092-2cf8-11e5-9473-0adcdd69bc07.jpg)

AutoArmor is moving the armor in the armor slots to fast on NCP Servers.

**Comment by Bluscream** [comment]
https://github.com/Wurst-IRC/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/inventory/FastClick.java#L43

This could help ;)

**Comment by Bluscream** [comment]
Note that NCP also has a "Drop" Limit: https://github.com/Wurst-IRC/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/inventory/Drop.java

**Comment by Alexander01998** [comment]
> Note that NCP also has a "Drop" Limit: https://github.com/Wurst-IRC/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/inventory/Drop.java

Already implemented.

> Also im asking myself if we could send different data to the server then the player while using nuker for example, cause NCP is checking if you are watching at the same block that you are trying to interact with (https://github.com/Wurst-IRC/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/blockinteract/Visible.java#L54). So we could just spoof that the player is looking at the block while the player is looking somwhere else (Already used in Headroll etc.)

Already implemented.

**Comment by Meylama** [comment]
46ms? I have looked into the source code of a private client with a very good working & fully bypassing AutoArmor, and it seems to user a 65ms delay. You can look at the source: http://hastebin.com/uyegubomuq.axapta
