### ISSUE TITLE
Question: How to use the Wurst-Bot?

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1283]
I found this: https://github.com/Wurst-Imperium/Wurst-Bot-launcher

U wrote: "Notice: This is only a launcher. Wurst-Bot itself is part of the Wurst Client."

But how to use it?

I tried to use cmd to execute your launcher:

![cmd](https://cloud.githubusercontent.com/assets/3318223/8759733/297390cc-2cfc-11e5-97c7-148780fb2033.jpg)

**Comment by Alexander01998** [comment]
Just open the `README.html` file. Installation & usage is explained there.

**Comment by Bluscream** [comment]
Didn't you mean the README.MD file? If yes, which one?

The one of Wurst-Bot-Launcher?
https://github.com/Wurst-Imperium/Wurst-Bot-launcher/blob/master/README.md

Or the one of Robot-Launcher?
https://github.com/Wurst-Imperium/Robot-Launcher/blob/master/README.md

Or the one of the Wurst-Client itself?
https://github.com/Wurst-Imperium/Wurst-Client/blob/master/README.md

**Comment by Bluscream** [comment]
Also you wrote: "Wurst-Bot cannot be started with a mod or command in Wurst, but this is planned for later." (https://www.wurst-client.tk/news/2015-04-03-Wurst-v1.11/)

**Comment by Bluscream** [comment]
You should probaly mention somewhere that you need this file and manual: https://github.com/Wurst-Imperium/Wurst-Bot-launcher/releases/latest

```
Starting Wurst-Bot...
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/opengl/OpenGLException
        at net.minecraft.client.main.Main.main(Main.java:54)
        at tk.wurst_client.bot.WurstBot.main(WurstBot.java:27)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.OpenGLException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
Drücken Sie eine beliebige Taste . . .
```

**Comment by Alexander01998** [comment]
Obviously you need to download the launcher before you can use it.

**Comment by Lukigon** [comment]
How. Do. I. Use. This. On. Linux?
