### ISSUE TITLE
God Hack, Crash Sign

### ISSUE THREAD

**Issue by LukasE7x7** [Wurst-Imperium/Wurst-Client#1289]
I have an idea for a God Hack. Maybe this could work with the Hurt Time. After you got hurt, you are in the Hurt Time for a moment. While this is active, you can't get hurt. The God Hack could slow down the Hurt Time and make the Time the Player is marked red unlimited.
The SignCrash. I know it from Wolfram. It is great to ban Players from their own servers without op or gamemode, but I must switch the client everytime i want to use it. It would be great if this were in Wurst, too.
(Sorry, English is not my first language)

**Comment by GummiBoat** [comment]
CrashSign will be implemented with #967.

And as far as I know, the hurt time gets calculated by the server and is counted down there as well, I don't think that the Client can play too much around there.

And for the future, please don't open an Issue that contains multiple suggestions. It makes things confusing while trying to keep an overview.

**Comment by Bluscream** [comment]
I would also love **GodMode**

It seems possible: https://github.com/Wurst-IRC/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/fight/GodMode.java
