### ISSUE TITLE
Custom item spawn (Creative)

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#1292]
Id like an option to spawn in a custom item in creative mode. Ex:
A +5 speed stick that makes me go superfast with a colored name and level 50 enchants

**Comment by GummiBoat** [comment]
# *Duplicate: #342*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by ravenje** [comment]
Duplicate: #342
https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67#342
