### ISSUE TITLE
Re-add "NoOverlay"

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1296]
Why did you removed the **NoOverlay** mod? And can you reimplement it?

But i would suggest the status texts on the left lower corner of the screen.

For example:

```
§cOn Fire!
§1Drowning!
§7Sleeping...
§6Pumpkin
```

**Comment by mcccs** [comment]
Yeah I agree with you! 1) Nooverlay 2) fix nohurtcam!

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/com/krispdev/resilience/module/modules/render/ModuleNoFireEffect.java

https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/com/krispdev/resilience/hooks/HookGuiIngame.java#L123

**Comment by Alexander01998** [comment]
> Why did you removed the NoOverlay mod? And can you reimplement it?

Wurst never had a "Nooverlay" mod.

**Comment by Bluscream** [comment]
Im actually pretty sure i have seen commits that removed NoOverlay. I just can't find them now ..
