### ISSUE TITLE
:bug: Highjump isn't really disabled in YCP Mode

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1299]
If you enable **YesCheat**+ while having **HighJump** enabled it will show **HighJump** red but it is still enabled.

**Comment by GummiBoat** [comment]
Confirmed.
![highjump](https://cloud.githubusercontent.com/assets/10976441/8765414/1c410eec-2e0b-11e5-8d5c-3f65e604e2a4.gif)

**Comment by Eyremba** [comment]
I can confirm it too.
