### ISSUE TITLE
Not an issue but an idea.

### ISSUE THREAD

**Issue by HeyImFanta** [Wurst-Imperium/Wurst-Client#1302]
Hey Alexander! Ive been thinking if it's possible to use .enchant in survival with no OP that would be really cool.

**Comment by GummiBoat** [comment]
Sadly that's not possible. You can't modify NBT Tags freely in survival mode.

**Comment by HeyImFanta** [comment]
GummiBoat, maybe some day in the future t will be possible.

**Comment by Alexander01998** [comment]
# *Duplicate: #667*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
