### ISSUE TITLE
Magic carpet

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#1306]
When you jump a block appears underneath you. Or you just jump on invisible blocks like when you have phase on with a server with a anti cheat.

**Comment by GummiBoat** [comment]
# *Duplicate: #781*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
