### ISSUE TITLE
Colored Sign text for creative mode

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1307]
It is possible to change the sign metadate in creative to make colored signs
can you make a gui that open on leftclick with a sign or a ColorSign button in the Fun menu?                for creative?
Menu style:
              Create Sign
                [Line 1]
                [Line 2] 
                [Line 3]
                [Line 4]
                [Done]

Colors: Way 1: Repalce all $ with § in the sign
Way 2: Possible to type § in the text boxes like in alt manager

**Comment by GlitchHead** [comment]
Duplicate 1225 & it is possible via NBT \"text\":\"Hello\",\"color\":\"aqua\
