### ISSUE TITLE
Crash (Java crash)

### ISSUE THREAD

**Issue by mcmiracle05** [Wurst-Imperium/Wurst-Client#1308]
I just downloaded Wurst and it was loading then when it loaded my minecraft crashed with this error
—————- Wurst Client Crash Report —————-
—- Please report this crash at: wurst-client.tk/bugs —-
// Ooh. Shiny.

Time: 7/12/15 9:09 PM
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
at tk.wurst_client.files.FileManager.init(FileManager.java:92)
at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
at net.minecraft.client.Minecraft.run(Minecraft.java:359)
at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
—————————————————————————————

— Head —
Stacktrace:
at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
at tk.wurst_client.files.FileManager.init(FileManager.java:92)
at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

— Initialization —
Details:
Stacktrace:
at net.minecraft.client.Minecraft.run(Minecraft.java:359)
at net.minecraft.client.main.Main.main(Main.java:127)

— System Details —
Details:
Minecraft Version: 1.8
Wurst Client Version: 2.0.1 (latest: unknown)
Operating System: Mac OS X (x86_64) version 10.9.5
Java Version: 1.6.0_65, Apple Inc.
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
Memory: 105221568 bytes (100 MB) / 262873088 bytes (250 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
Launched Version: Wurst
LWJGL: 2.9.2
OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-8.24.16, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [§lHudCraft(1), Justinwin8DoesYT's TexturePack]
Current Language: English (US)
Profiler Position: N/A (disabled)

Im pretty sure its because you need to have java 1.8 so if it is please somehow make Wurst compatible with java 1.6 too because my computer cant handle changing to java 1.8 and this client is my favorite and I really want it. Thanks again!

**Comment by TekkitCommando** [comment]
It would be too much annoying work to maintain a java 6 and java 8 version plus in java 6 version not all Wurst features would be there

**Comment by TekkitCommando** [comment]
This is a duplicate btw

**Comment by TekkitCommando** [comment]
If your computer can't handle a java upgrade you should get a new one xD

**Comment by mcmiracle05** [comment]
Im not getting a new mac

**Comment by mcmiracle05** [comment]
I reallllly want to play wurst and I cant :(

**Comment by TekkitCommando** [comment]
Ok if it's a Mac then it's not that it can't handle it, it's just java was made by people with windows and Mac doesn't automatically like and use new java versions like windows does

**Comment by TekkitCommando** [comment]
I would try to set Mac to use java 8 manually, download java 8 and delete java 6

**Comment by TekkitCommando** [comment]
This is a duplicate so this topic is gonna get locked

**Comment by mcccs** [comment]
#1224

**Comment by mcmiracle05** [comment]
I didnt dup it i just copyed my minecraft crash report

**Comment by TekkitCommando** [comment]
Its a duplicate because an error like this has been submitted before and already answered 300 times :P

**Comment by Alexander01998** [comment]
:apple: = :elephant: :dash: :speak_no_evil:
