### ISSUE TITLE
Session Stealer

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#1309]
This hack let's you use an account from another person that is playing on a specific server. It doesn't let you know the accounts password, but you can play with the account.
If you (Alexander) would put this feature in the client I would like it if you put in the minecraft menu.

**Comment by BoomBoomLHack** [comment]
you mean the session ID stealer?

**Comment by Creeperman8362** [comment]
just like the garploit one?

**Comment by Meylama** [comment]
I think yes he means a SessionID stealer like the garploit one, and yes this feature in Wurst would be nice.

**Comment by GummiBoat** [comment]
# *Duplicate: #1029*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Grievus** [comment]
Exactly like the Garploit one. I think it is an awesome idea.
