### ISSUE TITLE
Nothing f***ing happens!?!?!?!?

### ISSUE THREAD

**Issue by HavanHUN** [Wurst-Imperium/Wurst-Client#1311]
I downloaded the latest version (v2.1) of Wurst, I copied the "Wurst" folder from the .zip and placed it to "C:\Users\Felhasználó\AppData\Roaming\.minecraft\versions". I opened TeamExtreme Minecraft Launcher and I selected "release Wurst". I hit the Play button, but NOTHING happens. The "Game Output" is full empty. DAFUQ!?!?!?!??!?? What to do??????????

**Comment by GummiBoat** [comment]
What are your System Details? Are you using the newest Java Version? Dooes this happen with the regular Minecraft launcher too? Can you use other Clients on your Launcher?

Please consider giving these Informations, we need them in order to help you correctly.

**Comment by Bluscream** [comment]
![wurst_launcher](https://cloud.githubusercontent.com/assets/3318223/8767295/572427fe-2e58-11e5-8ae8-9729e4a4cdc8.gif)

**Comment by HavanHUN** [comment]
I use Windows 7 Ultimate 64bit and I use the newest Java Version. I don't have the original Minecraft, but in this client run every version smoothly (alpha, old beta, newest version 1.7.2, 1.8.x, Resilience too).

**Comment by Alexander01998** [comment]
> I don't have the original Minecraft, but in this client run every version smoothly

Cracked Minecraft isn't officially supported.
