### ISSUE TITLE
parkour hack

### ISSUE THREAD

**Issue by Pkgts** [Wurst-Imperium/Wurst-Client#1313]
makes you jump at the very edge of the block, and sometimes there is an option to boost your jump by one block

**Comment by GummiBoat** [comment]
# *Duplicate: #110*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Pkgts** [comment]
the other ones were closed, but this hack is possible, KilO has it and so does flare
