### ISSUE TITLE
Add more WSPAM Events

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1316]
![ac8eca97f9e7f8db2a548e6be61c077c](https://cloud.githubusercontent.com/assets/3318223/8767895/5b38dae2-2e6c-11e5-9ab4-4c3e40adfbec.png)

Please add more possible events to the WSPAM Autorun listener.

For example:

* leaveserver.wspam (add the commands in the file to a queue and when you click on disconnect in the ESC menu, the queue will be finished until the real disconnect gets called)
* leaveworld.wspam (add the commands in the file to a queue and when you click on save and leave in the ESC menu, the queue will be finished until the real leave gets called)
* getchatmsg.wspam (when the player gets a msg in the chat)

**Comment by Meylama** [comment]
Other event examples:

- "Hackusations" (this is if another player is calling you as a "Hacker" without any proofs): If anybody writex "<your name> hax", "<your name> haxor", "<your name> hacker", "<your name> killaura" etc. it executes hackusation.wspam which can spam for example "Nice dude, I call it skill :)"

- kill.wspam (if you kill a player)
