### ISSUE TITLE
Missing Hack

### ISSUE THREAD

**Issue by davidkoplik** [Wurst-Imperium/Wurst-Client#1317]
Hi,
I am really missing Safewalk in Wurst, it's great for SkyWars, I gotta use Wolfram for that... Please add Safewalk :)

**Comment by Bluscream** [comment]
To explain it: Safewalk is simple like **Sneak** without sneaking, it checks if the block you are tring to move on is air and if yes it blocks it so you cant fall down. But you can move at normal speed and even sprint while **SafeWalk** is enabled.

**Comment by davidkoplik** [comment]
Yeah, that is exactly why I want SafeWalk in Wurst, because you can sprint and walk normally :)

**Comment by davidkoplik** [comment]
Alexander, what is your opinion on that?

**Comment by Bluscream** [comment]
#308

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/movement/ModuleSafeWalk.java

https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/net/minecraft/entity/Entity.java#L648

**Comment by davidkoplik** [comment]
Bluescream thank you for helping.

**Comment by Bluscream** [comment]
@davidkoplik If you call that helping, then your welcome =)

**Comment by davidkoplik** [comment]
@Bluscream I don't know how to code :D

**Comment by TekkitCommando** [comment]
I got 60 java tutorials some of them I used to learn java you want them xD

**Comment by Bluscream** [comment]
@TekkitCommando Do you have setted up a complete development environment for wurst so you can make changes and compile the jar?

**Comment by TekkitCommando** [comment]
Not anymore but I can do that in 15 mins

**Comment by Bluscream** [comment]
Can you create and test it and send to me completly? With MCP a eclipse project and stuff?

**Comment by TekkitCommando** [comment]
I can try tomorrow it's really late for me right now :P

**Comment by Bluscream** [comment]
Yes, thanks :3

**Comment by TekkitCommando** [comment]
np 😀

**Comment by davidkoplik** [comment]
@TekkitCommando You can post your youtube link or whatever you have I would look at some Java tutorials, I wanna know at least something :)

**Comment by TekkitCommando** [comment]
Haha ok xD I will in the morning it's nearly 1 am :P

**Comment by davidkoplik** [comment]
Thanks

**Comment by davidkoplik** [comment]
@Alexander01998 Please take a look at it, it's really cool feature, and @Bluscream mentioned #308 , 2 more people would agree on that, and it's normal part of almost any other client, it's the feature I need the most...

**Comment by TekkitCommando** [comment]
@davidkoplik https://www.youtube.com/playlist?list=PL06F80381FDB1ED19 and https://www.youtube.com/playlist?list=PLFE2CE09D83EE3E28 I prefer Ulixava I haven't watched much of this other person. But yeah good place to start learning java :)

**Comment by bob80333** [comment]
@TekkitCommando
Could you send me the complete setup Wurst dev environment as well?  I was thinking of getting to the macro recorder when I have free time in a week or so.

**Comment by TekkitCommando** [comment]
Are you guys having a problem with mcp or somethin xD @bob80333

**Comment by Bluscream** [comment]
@TekkitCommando No i managed it to decompile minecraft with mcp like @Alexander01998 said in his wiki but i failed at making a Wurst project with eclipse ._.

**Comment by bob80333** [comment]
No, but I spent 2 hours on it and it was kinda broken.  I'm pretty inexperienced with eclipse.

**Comment by TekkitCommando** [comment]
xD

**Comment by TekkitCommando** [comment]
Yeah I am moving to a bigger house :) So when i get done moving my stuff I will start working on something for you guys :)

**Comment by bob80333** [comment]
@Bluscream @TekkitCommando
I managed to apply the patch, but adding the source folders and libraries turned nasty and I spent like an hour adding JVM arguments to try to fix it, but it failed. -_-

**Comment by TekkitCommando** [comment]
@bob80333 It all seems easy to me but i have been doing this for a while xD

**Comment by davidkoplik** [comment]
@TekkitCommando Thank you for the tutorials, I'll definitely look at it :)

**Comment by davidkoplik** [comment]
Also, @TekkitCommando how long have you been training Java until you could figure out how to add fly hack or make a Java software or something easy :D

**Comment by TekkitCommando** [comment]
Java 8 added some stuff and redid other but its basically the same, you want notice much change if any if your programming

**Comment by davidkoplik** [comment]
Oh okay
