### ISSUE TITLE
.echo command

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1318]
Maybe you want to add the .echo command that is in many clients and creates a **RAW** msg in the chat, so it doesn't has the "\<WURST\>" prefix. That is good for chat screenshots to spoof other players insulting you 'n stuff to admins.

https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/command/commands/CmdFakeChat.java (for skidding :D)

(https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/net/minecraft/command/ICommandSender.java)

**Comment by Meylama** [comment]
Cool idea, I know this feature as ".fakemessage". It is a really nice idea! :)

**Comment by davidkoplik** [comment]
Good idea!

**Comment by OMGchangeMYusername** [comment]
>https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/command/commands/CmdFakeChat.java (for skidding :D)

........

> It's not skidding if Krisp shared his source to the public.

someone said these...

**Comment by Bluscream** [comment]
The :D indicates that its a joke ._.

**Comment by OMGchangeMYusername** [comment]
#Learn2APOSTROPHE

**Comment by Bluscream** [comment]
#Learn2NotBeAGrammarNazi

**Comment by OMGchangeMYusername** [comment]
wooh i got rekt -.-...

**Comment by Bluscream** [comment]
finally u got it m9
