### ISSUE TITLE
.log command

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1319]
Should create a new line in the log with the text given as the parameters.

**Comment by pokeball99** [comment]
What's the purpose?

**Comment by Bluscream** [comment]
To find the part easier later. For example you do something type ".log mark123test" and then leter in the log file just search for "mark123test"

**Comment by 1337HaxorKiddie** [comment]
You can already type Sweg or /Sweg in chat and search it in you logs thats the samething i don´t see any reason why this mod should be implemented
