### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by davidkoplik** [Wurst-Imperium/Wurst-Client#1321]
Hello,
I really miss Optifine in Wurst, it makes it much faster and smoother, and I love the zoom function in Optifine. If it's possible, please add it, Alexander.

**Comment by pokeball99** [comment]
>optifine ever being in wurst in the first place....

**Comment by TekkitCommando** [comment]
Thats great there never was optifine in Wurst xD

**Comment by TekkitCommando** [comment]
Duplicate #2

**Comment by Bluscream** [comment]
@Alexander01998 Why aren't you assigning labels anymore?

**Comment by OMGchangeMYusername** [comment]
Ever heard of someone forgetting?
I don't think he did that on purpose, since other issues are already closed by the user who opened them in the first place..

**Comment by Alexander01998** [comment]
> Why aren't you assigning labels anymore?

Because I didn't know that the GitHub app can do that.
