### ISSUE TITLE
Arrow Dodger and YC+ bypass for fesbow

### ISSUE THREAD

**Issue by Egor1505** [Wurst-Imperium/Wurst-Client#1324]
I think you should make a mod in wurst which automatically detects and dodges from arrows. Also i thin k you should mak FastBow YC+ bypass

**Comment by GummiBoat** [comment]
# *Duplicate: #419*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

## For the future, please don't open an Issue that contains multiple suggestions!

(Btw, FastBow can't bypass NCP currently.)

**Comment by Egor1505** [comment]
Ok sorry!

**Comment by Bluscream** [comment]
![6f1c4bc897355e729bb44f1ea10e6335](https://cloud.githubusercontent.com/assets/3318223/8782356/25393c26-2f15-11e5-9a7a-2fd65b0c4b88.png)

**Comment by Egor1505** [comment]
Sooo! What do I do with it&

**Comment by GummiBoat** [comment]
@Bluscream that is not, that the mod is actually compatible, it's the newly implemented variable which controls wether the mod is compatible or not.
