### ISSUE TITLE
Simple but nice VClip enhancement

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1326]
I have an enhancement suggestion for VClip: ".vclip top" - teleports you to the top.

For example: If you are in a cave at 65 and the cave entrance is at 80, ".vclip top" will basically teleport you 15-17 blocks up like ".vclip 80" or ".vclip 82".

Important major advantage(!!!): You can bind ".vclip top" to a keybind and it will teleport you always up to the top (on vanilla servers), but with the normal vclip, you must every time calculate how high you must teleport yourself which makes it impossible to make it as keybind. ".vclip top" could also be used as emergency keybind to get quickly out of a cave.

**Comment by GummiBoat** [comment]
`.vclip` can only teleport up to 10 blocks on bukkit servers.
