### ISSUE TITLE
.fakemessage

### ISSUE THREAD

**Issue by davidkoplik** [Wurst-Imperium/Wurst-Client#1327]
Can you please add fakemessage? It's cool feature, anyone knows any client what has this?

**Comment by GummiBoat** [comment]
# *Duplicate: #721*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
