### ISSUE TITLE
.antiafk mode|time auto|jump|move||<sec>

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1333]
Please add more modes to the **AntiAFK** mod.

* auto (the default mode, checks 3x3 blocks horizontal and 3 blocks upwards of the players postion and uses the best suitable mode [if booth modes would work just use booth that will make it even harder to detect])
* jump (needs 3 blocks vertically space, works on most servers) [https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/movement/ModuleAntiAFK.java]
* move (works on servers with anti-anti-afk plugin (Examples: [afkTerminator](http://dev.bukkit.org/bukkit-plugins/afkterminator/), [AntiAFKPool](http://dev.bukkit.org/bukkit-plugins/antiafkpool/)), needs 3 blocks horizontal space) [https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/mods/AntiAfkMod.java]

time should be used as seconds to set the delay after the next action will be taken. for the most servers 60 secs are enough so we dont need to jump and run around liek a chiken xD
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/command/commands/CmdAntiAfkSet.java

**Comment by OMGchangeMYusername** [comment]
err.. hello?

**Comment by WurstContributor** [comment]
bluescream.exe has stopped responding.

**Comment by Alexander01998** [comment]
The current version of AntiAFK works on all servers, no matter what plugins they have (as you said).
If you really want the jump thing, you can do that with BunnyHop or Spammer.

**Comment by Bluscream** [comment]
> needs 3 blocks horizontal space)

Sometimes you dont have that much space.

**Comment by GummiBoat** [comment]
If you don't have 9 Blocks in total space, you should consider building a new house.

**Comment by Bluscream** [comment]
I wouldn't call a Instantbunker with Obsidian a house.

**Comment by GummiBoat** [comment]
Instantbunker has by default a 3x3 wide room inside.
