### ISSUE TITLE
InfiniteJump

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1334]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/movement/ModuleInfiniteJump.java

Not much to say exept that ^^

**Comment by GummiBoat** [comment]
So basically this is just another way to fly, right....?

**Comment by Bluscream** [comment]
Like the jetpack is, yes.

**Comment by OMGchangeMYusername** [comment]
No apparent need of this..

**Comment by davidkoplik** [comment]
It's not bad idea, like to trick people with selling potions, you'll throw it on yourself and jump twice for example XD

**Comment by OMGchangeMYusername** [comment]
Do you seriously think you can pick things that way?

**Comment by Alexander01998** [comment]
That's exactly what Jetpack does.
