### ISSUE TITLE
WireFrame

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1335]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/world/ModuleWireFrame.java

https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/net/minecraft/client/renderer/EntityRenderer.java#L1488

**Comment by Alexander01998** [comment]
I don't see any use in a WireFrame mod.
