### ISSUE TITLE
AutoTPAccept

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1336]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/player/ModuleAutoTPAccept.java

**Comment by GummiBoat** [comment]
# *Duplicate: #202*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Bluscream** [comment]
Thanks

**Comment by pokeball99** [comment]
@bluscream really?I know we take features of other clients,but u don't need to make a issue for every command/mod of other clients.....that's my job :D
