### ISSUE TITLE
AutoBlock

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1337]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/combat/ModuleAutoBlock.java

https://github.com/Bluscream/Resilience-Client-Source/blob/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/com/krispdev/resilience/module/modules/combat/ModuleKillAura.java#L44

**Comment by GummiBoat** [comment]
# *Duplicate: #1050*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by rasmusolle** [comment]
:) 1337

**Comment by OMGchangeMYusername** [comment]
XD

**Comment by kim-yannick** [comment]
1337 FTW!
