### ISSUE TITLE
.rod

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1338]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/command/commands/CmdRod.java

I dont know what it is for but probably it would be a "nice-to-have" x)

**Comment by GummiBoat** [comment]
If you don't even know what it is for, why do you want it? I don't even see what this stuff should be doing...

**Comment by Bluscream** [comment]
`super("rod ", "[Amount of Rods]", "Setting this to a high number may crash the server");`
so it seems to be eeeeviiiiill xD

**Comment by GummiBoat** [comment]
But it's totally incompleted.. there is no method, the only thing that is there, is.. if the command is recieved, return false. I don't know where there are rods, amounts or whatever.. seems just to be incompleted code :/

**Comment by OMGchangeMYusername** [comment]
Wow you even had no idea about what it does.. That's too weird..

And please refrain from doing this, I mean stop linking to resilience source in every suggestion or comment you post...

**Comment by Bluscream** [comment]
I stop when every Mod and command is migrated from Resilience so i can suggest Wurst as the "Resilience" for 1.8

**Comment by TekkitCommando** [comment]
xD

**Comment by OMGchangeMYusername** [comment]
> so i can suggest Wurst as the "Resilience" for 1.8

Skids are not appreciated in the whole hacking community, although i'm extremely fine with it and would actually appreciate skidding good things, it still doesn't feel so original..

**Comment by Bluscream** [comment]
It's not skidding if Krisp shared his source to the public.

**Comment by pokeball99** [comment]
^

**Comment by OMGchangeMYusername** [comment]
That still doesn't feel original.. but idc anyway.
