### ISSUE TITLE
kill aura 

### ISSUE THREAD

**Issue by Generalsparkles1** [Wurst-Imperium/Wurst-Client#1341]
my kill aura turns on even if i turn it off XD

**Comment by GummiBoat** [comment]
That's probably because of YesCheat+. If you have a key bound to MultiAura and activate it, while YesCheat+ is active, it'll automatically switch to KillAura, but it'll not turn it off, because you didn't toggle it. Just rebind your key from MultiAura to KillAura. That should solve the problem.

**Comment by OMGchangeMYusername** [comment]
More info required,that is too vague. Gummi is assuming you're using YesCheat+ and MultiAura which is less likely the case..
YesCheat+ and MultiAura are not used that much.. check out the most popular mods to see what i mean
![image] (https://cloud.githubusercontent.com/assets/10100202/8754188/ff437cb6-2cc1-11e5-9404-abc98934b666.png)
