### ISSUE TITLE
Item Magnet

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1342]
I think that if you could bring all items within an adjustable radius to you, that would be REALLY cool!

**Comment by WurstContributor** [comment]
No. Just No. ITS NOT POSSIBLE.

**Comment by GummiBoat** [comment]
# *Duplicate: #144*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by WurstContributor** [comment]
@GummiBoat Ty

**Comment by Nitrogen-Dioxide** [comment]
You guys know how to use blink right?

**Comment by WurstContributor** [comment]
Yea....

**Comment by labcraft59** [comment]
What does blink do?

**Comment by bob80333** [comment]
Temporarily stops sending movement packets, so it looks like you teleport a short distance.  After a certain amount of time you get kicked if you don't disable.  Once disabled, all the blocked packets are sent to the server at once.  So you enable it, run through area w/ items and to another area, then disable it and items appear in inventory.

**Comment by Nitrogen-Dioxide** [comment]
@bob80333 
I stole a lot of op stuff from op pvp fights xD

**Comment by labcraft59** [comment]
Ok?
