### ISSUE TITLE
Where's alexander?

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1346]
He's always (last 4 days) offline? What happened? 2 Days ago you logged in, closed optifine issue then you vanished again!
Again:
Wo bist du Alexander??

**Comment by Meylama** [comment]
Yes, really creepy. Da ich auch Deutsch spreche, was ist los Alexander? Falls du im Urlaub oder ähnliches bist hättest du eventuell ja kurz bescheid geben können damit sich niemand wundert wieso du so lange inaktiv bist. :D

**Comment by OMGchangeMYusername** [comment]
English please.... I've found out that most of the hacking community nowdays is German....
like wow i swear you guys are a lot..

**Comment by GummiBoat** [comment]
What he's doing and why he's doing that, is irrelevant for you, isn't it? It's not like he's supposed to work nonstop here.

**Comment by OMGchangeMYusername** [comment]
^^^

**Comment by pokeball99** [comment]
^^^^

**Comment by ravenje** [comment]
He is death xD

**Comment by Alexander01998** [comment]
I don't tell anyone when I'm on vacation because I know some people who would abuse it.

**Comment by OMGchangeMYusername** [comment]
I thought you were absolutely death O-O!!!!1!!

**Comment by Bluscream** [comment]
Same like Krisp:

http://www.hackforums.net/showthread.php?tid=4050106
http://www.hackforums.net/showthread.php?tid=4395446&pid=43282203#pid43282203
