### ISSUE TITLE
Add Optifine support and way to change the default button to open wurst.

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1347]
Yeah.. my minecraft dont wanna work really good without optifine :/ 
And i dont like it to press ctrl to open the window because i use that button to sprint in minecraft.

Also are you guys german because the name? I just wonder ^^

**Comment by bob80333** [comment]
There is a keybind changer.  .t ClickGui is the command to open the mods menu.  Optifine will never be added, see #2.

**Comment by pasi123567** [comment]
Okay i read it but thats no solutuon for me! I need to play with optifine since 1.8 because without it my minecraft will lag as f*ck. I also read all the updates optifine has made and when minecraft 1.8 came out they added lots of stabilisations on the fps and since that optifine update i can play minecraft normal again. 
When minecraft 1.8 came out there where much people asking and hating because of the low performance. And optifine i waited like 3weeks for an optifine update because minecraft didnt seem to fix it, then the 4th pre-release of optifine 1.8 came out and everything worked fine again.
Also i didnt changed anything on optifine like lower particles or anything like that.

I can make a video how my minecraft runs with and without optifine if you want me to.

**Comment by OMGchangeMYusername** [comment]
The thing is.. Alexander01998 is the one to decide.. 
I admit Optifine has made some performance enhancements for me too.

**Comment by pasi123567** [comment]
Those 2 optifine posts where the most important for me.
http://i.imgur.com/iQVsVbx.png
http://i.imgur.com/yRbj9i2.png

Pls add it i cant play with this awesome client without it :(

**Comment by WurstContributor** [comment]
@pasi123567 No.

**Comment by WurstContributor** [comment]
#Invalid

**Comment by Bluscream** [comment]
@WurstContributor stop beeing mean and rude! We're not @ HackForums !!!

**Comment by TekkitCommando** [comment]
Hack Forums, I got banned from there :P

**Comment by Bluscream** [comment]
@TekkitCommando, lel

![2f89786ffc1711fb8d3cb1840414e043](https://cloud.githubusercontent.com/assets/3318223/8843077/bd59e092-3103-11e5-8aa3-75f3ef221fbd.png)

**Comment by TekkitCommando** [comment]
lol

**Comment by TekkitCommando** [comment]
I go by a new alias on new things xD

**Comment by TekkitCommando** [comment]
@Bluscream Nice Leet Speak xD

**Comment by Bluscream** [comment]
@TekkitCommando I didn't wanted that ppl can just search bluscream on Google and find my HF acc, lel

**Comment by TekkitCommando** [comment]
@Bluscream xD

**Comment by Bluscream** [comment]
@TekkitCommando Never seen this b4 lol freakn 4w3sum: https://github.com/jshackles/Enhanced_Steam

**Comment by TekkitCommando** [comment]
@Bluscream fancy :)

**Comment by OMGchangeMYusername** [comment]
Guys this is fucking Github and it is the fucking Wurst repository! stop talking bullshit here..
@TekkitCommando this is @Bluscream's Skype "bluscreamlp" go talk shit there.

Plus i saw your acc earlier and it was horrible because of all the reps..
And i really i don't give a damn about HF, i just registered to download some stuff and all..

**Comment by Bluscream** [comment]
@OMGchangeMYusername but you bahave like 1 of dem ...

**Comment by TekkitCommando** [comment]
@OMGchangeMYusername you need a nap or somethin holy shit

**Comment by TekkitCommando** [comment]
@Bluscream I am trying to make a music player in java, i am 10% done :P

**Comment by TekkitCommando** [comment]
@OMGchangeMYusername I will stop talking "Bull Shit" as you call it, now

**Comment by OMGchangeMYusername** [comment]
Been sleeping for over 10 hours now, i just leave Github open and go somewhere else, i check new notifications from time to time so that's why..

**Comment by pasi123567** [comment]
So there will nothing happen? :(
This client is so nice :(

**Comment by bob80333** [comment]
Once Alexander adds Forge support, Optifine will be a possibility for the end user.

**Comment by bob80333** [comment]
It will have to be manually installed though.

**Comment by pasi123567** [comment]
No problem :) But thanks =)

**Comment by pasi123567** [comment]
So there will be no Forge support? D:

**Comment by WurstContributor** [comment]
@pasi123567 The forge support issues is already comfirmed.

**Comment by pasi123567** [comment]
So he will add forge.. but will it be possible to install optifine then?

**Comment by WurstContributor** [comment]
@pasi123567 if you add mods u will not be able to send the crash log to Alex.
