### ISSUE TITLE
Spammer input

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1349]
can you add a chatinput support for spammer?
Example (Spamfile):
/me %input%

Chat:
[Wurst] Enter spamfile input:

**Comment by GlitchHead** [comment]
hmmmm might be great for other things like advertizing or such heres a better example:
```
/msg %input1% Hey you really need to see this goto www.wwwdotcom.com its about %input1% also, %input2%.
```
And to use inputs you could do something like this:
```
.spammer spam MessageAd Notch "theres some stuff about your real name"
```
and quotes could be used for spaces in arguments.

**Comment by ravenje** [comment]
Yes, this is better, cool idea :D
