### ISSUE TITLE
Fight bot doesn't calculate range right

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#1350]
I think it is the same issue as trigger bot had.

**Comment by pokeball99** [comment]
Needs More info

**Comment by WurstContributor** [comment]
I comfirm. It tried to hit an armour stand floating way in the air.

**Comment by Nitrogen-Dioxide** [comment]
@pokeball99 
There is all the info needed here .-. Range slider don't work for fightbot, it is the same bug as trigger bot had.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
