### ISSUE TITLE
Spammer shuffle

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1352]
Not shown correctly: Look at this hastebin: http://hastebin.com/adisimadah.xml

**Comment by GummiBoat** [comment]
Pleaserino closerino (the button left from comment), becuz you just added that to your other issue #1351.

Thankerino.

**Comment by OMGchangeMYusername** [comment]
I literally thought this is #1351... You seriously opened another issue????!!!!!
