### ISSUE TITLE
Kicked For Flying When I Walk Off A Block

### ISSUE THREAD

**Issue by Enderman0807** [Wurst-Imperium/Wurst-Client#1353]
Doesnt happen to me all the time but it does happen often, when i walk off even a 1 block high area sometimes i get kicked for flying on multiplayer servers PLEASE FIX

**Comment by OMGchangeMYusername** [comment]
What did you have enabled back when that happened?

**Comment by mcccs** [comment]
Did you try without wurst

**Comment by Enderman0807** [comment]
I'll make another reply for what I have enabled because it's almost all the same things and I don't get kicked for flying when I walk off a block when I'm on optifine which is the only other thing I'm on other than wurst

**Comment by Enderman0807** [comment]
i had antiblind anticactus autoeat criticals fastladder fullbright healthtags itemesp mobesp nametags nofall noslowdown noweb playeresp playerfinder tracers and truesight also this is a vanilla server that its happening to me on

**Comment by OMGchangeMYusername** [comment]
Well.. The most suspicious thing here is Criticals, but still no one can help you without steps on how to reproduce it. And is it still happening?

**Comment by Alexander01998** [comment]
Mods that send a lot of packets (like Regen and FastEat) can sometimes cause you to be kicked for flying. Wurst tries to prevent this, but there is no way to guarantee that it will never happen.

**Comment by UnicornInExatacy** [comment]
you should add a rear view and a mini map
