### ISSUE TITLE
NameTags for sneaking players

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1354]
Nametags Mod does NOT work if the player is:

- Sneaking
- Behind a wall
- has an invisibility potion

Here you can see a player with a potion and another player behind a wall: (Nametags is enabled) http://gyazo.com/b5b2045cbc53b1ba4db5fa0963a806b8

**Comment by GummiBoat** [comment]
That's not a bug. That's an inteded feature from Mojang.

Nametags disappear, if the player is sneaking or is invisible. The one behind the wall was probably just sneaking or invisible too.

**Comment by Meylama** [comment]
But the Nametags Mod of other Hackclients can also show the Nametags through walls...

**Comment by GummiBoat** [comment]
Then we'll look that up and try to reproduce it. Thanks for your Issue.

**Comment by OMGchangeMYusername** [comment]
Can confirm, other clients have Nametags rendered even if the player is sneaking.

**Comment by Meylama** [comment]
@GummiBoat example source code: http://hastebin.com/zuborotopu.avrasm
