### ISSUE TITLE
Step Settings

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1356]
I've seen in Metro that step has a setting that lets you walk up 10 blocks! Very cool feature and I would die of happiness if it was in Wurst.

**Comment by Meylama** [comment]
Nice idea! :+1:

**Comment by OMGchangeMYusername** [comment]
But it won't bypass, wanted to note that just in case.

**Comment by JackFishbaugh** [comment]
I'm aware, but it doesnt have to. as long as you have to option to change the setting from 1 block (nocheat bypassed) to any number of blocks such as 10 it should be ok. It could also be a yescheat+ thing where it automatically puts it to one block if you have yescheat+ enabled, and an infinite number when yescheat is not on.

**Comment by Meylama** [comment]
@OMGchangeMYusername @JackFishbaugh Ever tried setting the step settings to 3, give you damage and then use step? :D 

On another client where you can set the step high, this works.
For example, set the step height to 3, go in front of the wall, type .damage 2 and then you can go up 3 blocks with step on a NCP server.

**Comment by JackFishbaugh** [comment]
the main server i mod on is mineplex, so i can just bypass their nocheat+. but thanks for the tip ill try it.

**Comment by Glowstone82** [comment]
@JackFishbaugh I DON'T WANT YOU TO DIE OF HAPPINESS! Lol!

**Comment by JackFishbaugh** [comment]
@Glowstone82  ok. ill die of sadness if it isn't added. better?
