### ISSUE TITLE
Semi-auto Fastbow

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1357]
Gives you the option to make fastbow a full-auto weapon or a semi-auto weapon. This way it looks more legit and you don't waste arrows as quickly if you don't want to!

**Comment by OMGchangeMYusername** [comment]
Duplicate #853 
I think this feature is good but yeah..

**Comment by JackFishbaugh** [comment]
okay thanks for the heads up. Just had to make sure
