### ISSUE TITLE
Mass Messaging

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1358]
Wurst has MassTPA, but that is only on servers with the command. What is an even better addition to the Chat section of Wurst, would be the ability to send ANYTHING to EVERY player in the server/lobby. So you could always use MassTPA, but you could also send a taunting message to all players using /msg, /tell, etc.. This way it works for ALL servers because you choose the command and the text to send!

**Comment by labcraft59** [comment]
Cool idea!

**Comment by trollmad3** [comment]
Awesome idea

**Comment by Nitrogen-Dioxide** [comment]
dupe #138

**Comment by GummiBoat** [comment]
^ you just stole what i just wrote.

**Comment by OMGchangeMYusername** [comment]
you always make a header and post that picture.. that's why people do it before you :P

**Comment by GummiBoat** [comment]
Dang it, I begin to slack off

**Comment by JackFishbaugh** [comment]
Did alexander reject the idea though??

**Comment by OMGchangeMYusername** [comment]
Nope, he just didn't make it yet.

**Comment by labcraft59** [comment]
I really want this one!

**Comment by JackFishbaugh** [comment]
^ it would be great... But i just dont want to have to manually put in the names of the people i sent it to. I want it to automatically send it to everyone in the server.
