### ISSUE TITLE
QUESTION:Will there be a wurst update next friday?

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1359]
I love the wurst updates it brings new stuff to wurst every friday and im so hyped for the next update! i dont even care if its just bug fixes. i am just wondering if @Alexander01998 is going to release a new update. thanks for reading

**Comment by JackFishbaugh** [comment]
im not sure... and no offense, but why are you asking this in the suggestion section?

**Comment by OMGchangeMYusername** [comment]
It's ok to ask questions.. but anyway stop opening more issues for the mean time, since he seems to not be able to manage them. sueggest/ask/report a bug when he comes back to action.

**Comment by GummiBoat** [comment]
The User are free to ask Questions via Issues too. That's why we have a special label for it.

And as long there is no other information, there will be an update, like usual.

**Comment by Alexander01998** [comment]
> QUESTION:Will there be a wurst update next friday?

Nope.

**Comment by trollmad3** [comment]
@Alexander01998 why?

**Comment by mcccs** [comment]
Because he'S in vacation.
Sausages needs vacations XD

**Comment by trollmad3** [comment]
@mcccs lol

**Comment by TekkitCommando** [comment]
Wurst ist gut xD
