### ISSUE TITLE
PotionESP

### ISSUE THREAD

**Issue by haykam** [Wurst-Imperium/Wurst-Client#1361]
Allows you to highlight entities with 2 things: either a box like other ESPs showing the potion color (like dark red for harming) or a box half the size of the potion effects you see in the inventory, that shows the icon and name. If it's possible you can also add time left.

**Edit:** Another feature: to change options, you'd do ".potionesp box" for the other-ESP like boxes and ".potionesp info" for the icon, name, and time left-style.

**Edit:** Thanks to OMGchangeMYusername's suggestion, there is another feature. There could also be text above the player's name tag in a smaller size, saying [Potion Effect] [Level] [Time]. You can toggle to that using ".potionesp small".

**Comment by OMGchangeMYusername** [comment]
duplicate #1360
