### ISSUE TITLE
Phase" gets through every block

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1363]
When i acctivate Phase im going trough all blocks.. even those who are under me.

**Comment by Meylama** [comment]
And what is the problem?! You know that it can also be used to pahse vertically....

**Comment by pasi123567** [comment]
I cant move when im falling constantly....
How can i change that?

**Comment by Meylama** [comment]
"I cant move when im falling constantly...."

*Facepalm* Phase is ONLY to go through walls/ceilings, it is NOT to have it activated all the time, so it is not needed to move...

**Comment by pasi123567** [comment]
How should i "Phase" trough a door when im "Phasing" trough the ground?

**Comment by Meylama** [comment]
Stand in front of the door, turn on phase, and constantly press "W"? Thousands of hackers learn this by trying it but you are only spamming stupid questions...

**Comment by pasi123567** [comment]
I cant press W because im flaiing dont you understand?

**Comment by Meylama** [comment]
Where are you falling?!

**Comment by pasi123567** [comment]
I falling trough the ground i cant go forward

**Comment by Meylama** [comment]
And WHERE?

**Comment by pasi123567** [comment]
What you mean Where?

**Comment by Meylama** [comment]
WHERE means where? Sinlgeplayer? HiveMC? 123IamAStupidNoob.us?

**Comment by pasi123567** [comment]
Phase doesnt work on Hive or SP. It only works on a NocheatPlus Server. 
Tell me a server where Phase work and i will test it there,

**Comment by Meylama** [comment]
It works everywhere, also on Hive.

**Comment by pasi123567** [comment]
Ill make a video can you wait? :)

**Comment by pasi123567** [comment]
https://youtu.be/0N4wS75DGUA
This is an innactive channel so its not advertisment or something

**Comment by Meylama** [comment]
And what is "unnormal" with that? Like I said, you must stand in front of a wall, or door, and then turn phase on...

**Comment by pasi123567** [comment]
I tried but doesnt work

**Comment by Meylama** [comment]
Where did you try it?

**Comment by pasi123567** [comment]
Ok works *Facepalm*
Sorry i thought it was a gltich with the ground

**Comment by Bluscream** [comment]
What the f*cking hell did i just read? I hope this was a BIG joke ...
