### ISSUE TITLE
GUI is not sharp

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1364]
When i play in maximized window with GUI set to "Big" the Wurst gui gets unsharp.

Normal: http://i.imgur.com/hUva1kk.jpg
Big:       http://i.imgur.com/XGSxAtz.jpg
Auto:     http://i.imgur.com/IsP4UAA.jpg

**Comment by Meylama** [comment]
On my PC, it is sharp. So it seems to have to do anything with your GPU / graphic card.

**Comment by pasi123567** [comment]
Could be. I have this on much hacked client but not on all.

**Comment by pasi123567** [comment]
Its still some sort of issue... 
I have newest Graphic Drivers Installed

**Comment by Alexander01998** [comment]
That's not blur, it's an intended shadow effect.

**Comment by pasi123567** [comment]
Oh just if you wonder Alex, this only happens when GUI set to big and playing on fullscreen.
My screen resolution is 1920x1080
