### ISSUE TITLE
Stuck in Water when Jesus is on

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1365]
When turning on Jesus while under water you are stuck.
Maybe make it so you can at least jump up?

**Comment by Meylama** [comment]
Jesus is ONLY to walk over water, not to go under water.... so just disable it..

**Comment by pasi123567** [comment]
Ok thanks.

**Comment by OMGchangeMYusername** [comment]
i fucking said that last time.
And STOP opening issues like a tard!
