### ISSUE TITLE
Cant swim up when "NoSlowDown" is on

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1366]
Thers no way to get out of the water when "NoSlowDown" is on because you cant swim up.

**Comment by Meylama** [comment]
Just disable it?

**Comment by pasi123567** [comment]
Yeah but maybe to swim up fast too?

**Comment by GummiBoat** [comment]
Just activate Jesus or something like that. Water is slowing you down (even going upwards), so the mod disables it.

**Comment by pasi123567** [comment]
Okay thanks :)
