### ISSUE TITLE
New buttons for Esc and Server kick menu

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1367]
When you get kicked from a server there should be a button "Reconnect with alt account"
The same +  "Reconnect" when you press the Esc button so you can quickly rejoin a server.

**Comment by WurstContributor** [comment]
*_Duplicate #One of my issues*_
(INSERT PICTURE HERE)

**Comment by GummiBoat** [comment]
# *Duplicate: #1121*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by pasi123567** [comment]
Yeah but mabe on the esc menu too?

**Comment by Alexander01998** [comment]
Not a duplicate.
