### ISSUE TITLE
Beginner mode for Keybind Manager

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1371]
Maybe a possibility to not write the command yourself and replace it to a list of the hacks your client has

**Comment by GummiBoat** [comment]
How exactly do you mean that? Keybinds are already implemented. You won't be able to rename the specific modules tho,

**Comment by pasi123567** [comment]
http://i.imgur.com/Ao4dC5t.png
I mean that there should be a list of all the mods and when you click a mod then the Command will automatically be in the command line

**Comment by OMGchangeMYusername** [comment]
why would you bind something you don't know?

**Comment by pasi123567** [comment]
Like instanr of typing ".t freecam" a button who fills that in automatically

**Comment by JackFishbaugh** [comment]
i tried following what u said, and now my d*** is stuck in a mouse hole. maybe be more specific??

**Comment by pasi123567** [comment]
Go in the Keybind manager then press "Add" and then you can type in a command there.
A list of commands to autofill it if you dont know how a mod is written.
Just to add keybinds faster

**Comment by pasi123567** [comment]
Or a Button that brings you in the commands Wiki of wurst

**Comment by JackFishbaugh** [comment]
i dont think this is necessary.

**Comment by pasi123567** [comment]
Maybe right click on a hack opens the keybing manager?

**Comment by Bluscream** [comment]
Just like Resilience had ^^
