### ISSUE TITLE
More Fun "Hacks"

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1373]
Here are a few i thought to myself.

Doggy Style: Walking on 4 Legs like a dog
Gltich: all body parts moving like crazy
Wurst: Just a flat body on the ground
Hitler: One hand up the other to the mouth (Maybe an different name)

I know this i hard to make but its possible, Something like this has the Hacked client "Metro"
Only that you can move the body parts manually on Metro.

**Comment by Meylama** [comment]
"Doggy Style: Walking on 4 Legs like a dog"

Not possible.

"Wurst: Just a flat body on the ground"

Not possible.

"Hitler: One hand up the other to the mouth (Maybe an different name)"

Dude, also not possible...

"Gltich: all body parts moving like crazy"

Not full possible, just partial.

**Comment by pasi123567** [comment]
You read the last text on the bottom?

**Comment by Meylama** [comment]
"You read the last text on the bottom?"

First: You edited the text AFTER my reply.
Second: it only look CLIENTSIDE or in singleplayer so, but it is not possible in multiplayer.

**Comment by pasi123567** [comment]
Yeah only Clientside! But still looks "Fun" you know? :D

**Comment by Meylama** [comment]
Yes, but still useless to do so much work for such a shit which is only clientside, you know? :D

**Comment by pasi123567** [comment]
It was just a suggestion.

**Comment by WurstContributor** [comment]
Invalid...
