### ISSUE TITLE
Theme Shop

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1374]
A Theme Shop where Players can make there own Themes for the client and publish them.

**Comment by Meylama** [comment]
Like said in your other thread: This was already suggested and it was rejected. And use the damn search function, you only make dubplicate issues...

**Comment by pasi123567** [comment]
I searched for it.... I didnt found it. Give me the Issue

**Comment by Meylama** [comment]
I don't have it, another peaple told it you.

**Comment by pasi123567** [comment]
I cant find it so theres no problem right?

**Comment by Meylama** [comment]
Yet: Another player TOLD YOU ALREADY that it was suggested and rejected.

**Comment by pasi123567** [comment]
How should i trust him he should have send me the link, Also he said something like that, so not the same

**Comment by Meylama** [comment]
He said also already:

"Why the hell should i pay money for a simple theme on a free client?"

So, why should Alexander implement hundreds of stupid shit functions which nobody needs?

**Comment by pasi123567** [comment]
i didnt say they need to buy them, it could be free, like an explorer of designs fans are creating

**Comment by Meylama** [comment]
And why should this be needed?! You need to learn Java to code a theme, so why should anybody do it?

**Comment by pasi123567** [comment]
Its just a suggestion stop beeing so rude...

**Comment by Meylama** [comment]
You do not suggest things, you only spam the issue section here with stupid issues...

**Comment by GummiBoat** [comment]
The only thing, that got rejected, is a specific updated GUI for Wurst 2.0. That you can design the GUI yourself was never mentioned anywhere. Although it would probably be really hard to implement.

**Comment by Bluscream** [comment]
#1362

**Comment by mcccs** [comment]
Do if you can, then make a p.r. in client.tk

**Comment by OMGchangeMYusername** [comment]
That'll be a waste of effort.. It's not like every pr will be accepted.
Do it (if you want) after he accepts it, it's meaningless if he didn't.

**Comment by Alexander01998** [comment]
I actually wanted to add a theme shop in Wurst 2.0, but ended up not doing it because that would have delayed the update even further.

**Comment by pasi123567** [comment]
ahh okay that sounds great :D
