### ISSUE TITLE
.enchant keeps undoing itself

### ISSUE THREAD

**Issue by Pkgts** [Wurst-Imperium/Wurst-Client#1375]
if i .enchant something in creative and then open inv or try to wear, it removes its enchants.

**Comment by GummiBoat** [comment]
You need a) Creative mode to enchant and b) try to click once on it after you enchanted it with the command in your inventory. Then it should stay. The server needs some time to realize, that the item has changed.

**Comment by Pkgts** [comment]
i was creative and op with * permission but ill do b) ty

**Comment by GlitchHead** [comment]
When i use .enchant or anything that changes items i open the creative inventory and close it the item will then be registered.

**Comment by MyzticalTekkno** [comment]
@Pkgts just put an item that u want to enchant, then type .enchant / all to enchant all items in ur bar
then open your inventory and check the items u enchanted for the enchantments to work.

**Comment by Bluscream** [comment]
I would suggest just adding some lines of code to move the enchanted item to a free slot in your inventory and back. That would stop ppl asking.

**Comment by Alexander01998** [comment]
# *Duplicate: #635*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by EnderGamer21** [comment]
![image](https://cloud.githubusercontent.com/assets/13387479/9215493/746acd9e-4079-11e5-8e92-1be594a6642a.png)
