### ISSUE TITLE
Namehistory

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1377]
Allows you to find the previous names of a player. (Like this website here for example: https://namemc.com/s?Gummiboat but ingame via ".name" or ".history")

Example source code from a client: http://hastebin.com/ujetekurup.coffee

This is a really nice feature. :)

**Comment by GummiBoat** [comment]
Why me as an example :(

**Comment by Meylama** [comment]
Because I needed a name with a huge history :D

**Comment by OMGchangeMYusername** [comment]
Serenity xD

**Comment by pokeball99** [comment]
Or kilo,but that's a skid of latemod (I think)

**Comment by pasi123567** [comment]
https://de.namemc.com/s?pasi123567
Now try find out how i changed my name in 5 days :P

**Comment by OMGchangeMYusername** [comment]
@pasi123567 wow how :c

**Comment by pasi123567** [comment]
My account got hacked and i sended it to Mojang :P
