### ISSUE TITLE
InGame calculator

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1378]
It is a nice feature: A InGame calculator with ".calc"
For example: ".calc 15 + 5"
This can sometimes be useful, for example, if you need to calculate quickly the distance between two coordinates.

Example sources:
http://hastebin.com/ilejukibey.coffee
http://hastebin.com/wihotayafu.axapta

**Comment by GummiBoat** [comment]
I really don't think that this is necessary. Really not. There are already plenty ways to calculate quickly. (Win+R and type "calc" and press enter), or just type it in your browser bar (If your standard search machine is google, the answer should appear as first entry in a visual calculator), or whatever.

**Comment by ravenje** [comment]
nice idea @Meylama

**Comment by OMGchangeMYusername** [comment]
Wow what's really good about a calculater in minecraft?

**Comment by pokeball99** [comment]
^

**Comment by Meylama** [comment]
"Wow what's really good about a calculater in minecraft?"

You are at a depth of 59, in a cave, you have teleport permissions and must go to the top at 164, fast! FAST! there is a player behind you! Hurry up! How many blocks must you teleport up! what...? you are not good at calculating things in your head...? Ouh damn, now you are dead. Why there was no calculator with which you could have calculated it... and you needed to long to open the windows calculator...

just as a damn simple example why it can be useful

**Comment by OMGchangeMYusername** [comment]
Wow i don't remember me being that dumb.. I'm good, I dunno about others..

**Comment by GummiBoat** [comment]
@meylama ... how do you know, that the top is at 164? And additionally, vclip can't teleport that far up. not even on vanilla servers. And you'd probably take pretty long writing. A damn good example, why it is useless.

**Comment by Meylama** [comment]
@GummiBoat did you read my text....?

"You are at a depth of 59, in a cave, you have teleport permissions and must go to the top at 164" [...]

**Comment by OMGchangeMYusername** [comment]
Still "how do you know that the top is at 164?","And you'll probably take pretty long writing".

**Comment by Meylama** [comment]
"Still "how do you know that the top is at 164?""

It was still just a damn example because there are hundreds of situations were it can be useful but nobody seems to savvy this.

**Comment by Alexander01998** [comment]
ProTip™: Always have a calculator on your desk. That's a much faster way to calculate than typing a chat command. Not to mention it works without Minecraft.
