### ISSUE TITLE
Crashes before it starts 

### ISSUE THREAD

**Issue by SJS184** [Wurst-Imperium/Wurst-Client#1379]
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by GummiBoat** [comment]
# *Duplicate: #1224*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by bob80333** [comment]
I just realized there's a typo in the 
https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67
"submiting"
vs
"submitting"

**Comment by OMGchangeMYusername** [comment]
Lol never piad attention XD
Now fix that shit Gummi.

**Comment by GummiBoat** [comment]
![687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67](https://cloud.githubusercontent.com/assets/10976441/8979983/c0509200-36ad-11e5-9cb3-a282fcad194c.png)
?

**Comment by OMGchangeMYusername** [comment]
Maybe
![c0509200-36ad-11e5-9cb3-a282fcad194c](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by GummiBoat** [comment]
Nono, mine is definitely better.

**Comment by mcccs** [comment]
@OMGchangeMYusername 
@GummiBoat 
![untitled](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
Beat this! 3D render XD By me

**Comment by OMGchangeMYusername** [comment]
Meh i'd prefer Gummi's on this one.. Although mine is the best :stuck_out_tongue:

**Comment by mcccs** [comment]
Ok ,ill re-render adding blocks and players to this render.

**Comment by OMGchangeMYusername** [comment]
Btw guys that guy got deleted :P 
I just reported him but i doubt it was because of me

**Comment by mcccs** [comment]
@OMGchangeMYusername Finally! THX

**Comment by mcccs** [comment]
Where do you report

**Comment by OMGchangeMYusername** [comment]
go to the user's profile and click on
![block] (http://puu.sh/jk33l/fa4c805c73.png)
And then include why and pofit.

**Comment by mcccs** [comment]
Ok

**Comment by GummiBoat** [comment]
Alright guys, I made two completely new versions, the first is highly professional with the most complex image editing program i had

![unbenannt](https://cloud.githubusercontent.com/assets/10976441/9007036/e50d0106-378d-11e5-811d-777f807ea2d1.png)


but I also made one that completely sux, just for fun

![getrichfckduplicates2](https://cloud.githubusercontent.com/assets/10976441/9007811/55c4e6be-3795-11e5-881f-73fb5aa66eb8.png)

**Comment by OMGchangeMYusername** [comment]
Vouch for the first one. the second one "sux" :P

**Comment by GummiBoat** [comment]
yeah, the first one even has a new typo! great, isn't it?

**Comment by OMGchangeMYusername** [comment]
![Art] (http://puu.sh/jk7Da/b285cdaf91.jpg)

**Comment by GummiBoat** [comment]
beautiful

**Comment by Meylama** [comment]
You can see my version of the issue comment here: #1461, but Alexander does not like it. :(

**Comment by OMGchangeMYusername** [comment]
You were swearing.. I wrote that with my stupid mouse! can you believe it?

**Comment by bob80333** [comment]
If you guys were talking about that guy who was spamming commits, I reported him like 9 hrs ago.

**Comment by Meylama** [comment]
@OMGchangeMYusername it wasn't swearing. Try google translator. "Fucking" in this context means a light form of "damn"

**Comment by OMGchangeMYusername** [comment]
...................................................................................
afaik "damn" is also swearing, but even if it wasn't. "fuck" is swearing no matter what it really means..

**Comment by mcccs** [comment]
Ｐｌｅａｓｅ ＷＲＸ Ｆｏｒ ＭİｌｉｍａｒＴ ＳİＭＭＵＥＳ ＦＯｒｂｅｅ ｌｕｂｍｉｇｈｔｉｎｇ ｙｏｕｒｓ

**Comment by GummiBoat** [comment]
... wat?

**Comment by mcccs** [comment]
i didnt understand too xd
