### ISSUE TITLE
New WSPAM tag that loops through all players on the server

### ISSUE THREAD

**Issue by agaaxasa** [Wurst-Imperium/Wurst-Client#138]
The same of the MassTPA, but MassTell uses `/tell` and a message where `%ign%` is the told user's name. It doesn't stop either and it is great for advertising.

*Example:* In a vanilla survival server you can say:
>Hey, %ign% i heard that you want to trade. An apple is only 10 points!

**Comment by Alexander01998** [comment]
> The same of the MassTPA, but MassTell uses `/tell` and a message where `%ign%` is the told user's name.

The problem is that Bukkit servers often replace `/tell` with their own command, like `/w` or `/msg`.

> It doesn't stop either and it is great for advertising.

It should stop after every player has received the message once. Otherwise they would notice it.

> uses `/tell` and a message where `%ign%` is the told user's name.
>
>---
> it is **great for advertising**.
>
>---
> you can say:
> > Hey, %ign%

If it uses variables and is meant for advertising, just like Spammer, then why make a new mod for it?It could just as well be an addition to the WSPAM language. Something like this:
```HTML
<players>
/tell §_player; Hey §_player;, I heard that you want to trade. An apple is only 10 points!</players>
```

**Comment by WurstLeafeon** [comment]
Why not allow the user to change what command it starts with first? Infact, allow the user to do this in-game.

EX:
.mmsg /kick &Player Way to be stupid.
..would start the message with /kick, loop through the players and give the reason at the end.

That way, the user could change it to .mmsg /msg &Player or use /tell, or basically any command in the server.
This would make it easy to do a mass-ban/kick, whereas the user just has to type .mmsg /ban &Player.

**Comment by Alexander01998** [comment]
> Why not allow the user to change what command it starts with first? Infact, allow the user to do this in-game.

Because WSPAM is way more flexible than that.

**Comment by GlitchHead** [comment]
this will be very useful for many things actually instant OP all DEOP all clear whilelist and other things... this would also help if your in a panic situation and need to deny all players from a perm but with this you should also add when its scanning the tab menu for it to blacklist a player so if your making it mass /manuaddp <player1> -* /manuaddp <player2> -* /manuaddp <player3> -* but it will skip a specific player.
