### ISSUE TITLE
EdgeJump (Modified Version of #110)

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1380]
This was kinda brought up in #110, but instead of a bot, it just automatically jumps on the very edge of a block. This would require less work than typing out coordinates.

This or you just right click the surface of the block u want to go to an it jumps there for you. This is still less work than typing out coordinates.

**Comment by OMGchangeMYusername** [comment]
#522.

**Comment by JackFishbaugh** [comment]
shoot. lol sorry.
