### ISSUE TITLE
MonsterESP and AnimalESP

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1381]
This is possible right? All Wurst has is MobESP (Not that it is bad). This should be an easy and nice feature for Wurst.

**Comment by OMGchangeMYusername** [comment]
Yes it is possible, but these shouldn't be new mods. Should be a simple option for MobESP, since they're all mobs so yeah.

**Comment by JackFishbaugh** [comment]
sure yeah that works as well. as long as you have to option to make them separate ESPs
