### ISSUE TITLE
Blink Settings

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1382]
Gives you the option to put a timer on blink so that it automatically updates the packets in a certain number of seconds. For example, 1-Infinity, or 1 second to never updating until the mod is disabled.

I really hope this isn't a dupe.

**Comment by OMGchangeMYusername** [comment]
I agree.

**Comment by mcccs** [comment]
Blink +freecam?

**Comment by OMGchangeMYusername** [comment]
da actual fuck? took it as a pulse like thing, where i don't have to manually enable/disable it.
It should do that every specific amount of time.

**Comment by JackFishbaugh** [comment]
^

**Comment by Nitrogen-Dioxide** [comment]
You can do that with spammer but it is good to have options.

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide Please delete your reply or change it to whatever you want, he will most likely close this and put "Already implemented" if he sees your reply. (gonna change this afterwards)

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername 

Well, you can't be 100% sure of that...

**Comment by mcccs** [comment]
@OMGchangeMYusername 
Already implemented.
Im not joking, https://github.com/Wurst-Imperium/Wurst-Client/pull/446 replaced

**Comment by JackFishbaugh** [comment]
but all i want is a blink setting that lets you choose when the movement packets automatically update. thats it.

**Comment by OMGchangeMYusername** [comment]
@mcccs... Please use your mind, we know we can do that by pressing a key every time, but we're saying it'd be useful to have an automated process. 
The "already implemented" Nitrogen said is right however, it's useful to have it ready for a lot of people who rarely use spammer. (in fact i bet no one of the ordinary users use it, no offense at all.)

**Comment by Alexander01998** [comment]
> so that it automatically updates the packets in a certain number of seconds.

Blink used to work like that, but it wasn't very convenient.

**Comment by JackFishbaugh** [comment]
... :(
