### ISSUE TITLE
TAO

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1384]
"They are Open"
Usablefor 
ExtraInventory 
Steal whenever u want
Fast steal
How does it work?
WHile u look at chest, if someone knockbacks you 10 blocks away chest ui doesnt close, so this mod
Opens all near chests and says to server: i opened chest A, then B but i didnt close them, but they are close, you can open them whenever u want with .tao command. .tao leave says to server : i closed all chests. You can steal chests whenever u want, and faster stealing more inventory!(can autosteal work at same time on all chests

**Comment by GummiBoat** [comment]
The server won't allow this. It closes every inventory automatically, if you are more than ~15 blocks or so from the source away. And if the chunk is not even loaded, the client can not access the information in it, which includes chests as well.
