### ISSUE TITLE
Copying structures

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1385]
It would be really cool if we coudl do something like worldedit: select an area and replicate it anywhere else. Also integration of this with the autobuild structure list would be awesome.

**Comment by GummiBoat** [comment]
# *Duplicate: #710*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by beppe9000** [comment]
i searched and found nothing. i have no guilt xD

**Comment by GummiBoat** [comment]
Don't worry. I am just retarded enough to know almost every Issue...

**Comment by pokeball99** [comment]
^ im just too lazy too comment,dont want to have a "wiki" war

**Comment by TekkitCommando** [comment]
I am am too lazy to look up issues so i dont post suggestions xD

**Comment by OMGchangeMYusername** [comment]
@beppe9000 `is:issue autobuild in` nothing's hard too look for..

**Comment by beppe9000** [comment]
my bad, i searched for th title of my issue

**Comment by OMGchangeMYusername** [comment]
lol any word would do, you'll definitely find it as long as it relate to what you want.
