### ISSUE TITLE
Stealth Mode

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1386]
Often some moderator will ask for screenshots of your client. The Logo in the upper-left corner should be disableable in the options!

**Comment by GummiBoat** [comment]
# *Duplicate: #19*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by Meylama** [comment]
@GummiBoat it is NOT a duplicate. The other is because he would like to report hacker, but this one is because of screensharing. On some servers you MUST do screensharing with the admins or you can not play on this server.

**Comment by OMGchangeMYusername** [comment]
@Meylama It IS a duplicate, look at #26 and #74. It has been obviously rejected.

**Comment by Meylama** [comment]
@OMGchangeMYusername it was rejected because it was suggested to report another hacker or for recording, but it wasn't suggested for screensharing with an admin.

**Comment by OMGchangeMYusername** [comment]
Did you read all the duplicates?

**Comment by Meylama** [comment]
Well, forget it, I will make my own Wurst Version with a button to disable the logo and other visual things...

**Comment by TekkitCommando** [comment]
@Meylama is that supposed to intimidate us, Wurst is the 3rd or 4th most popular hacked client on Wizard Hax I doubt it will be replaced by a fork that adds two things this isn't CraftBukkit and Spigot

**Comment by Meylama** [comment]
@TekkitCommando why should it be replaced....? It is my own Wurst Version, private, not released, and will not be released.

**Comment by TekkitCommando** [comment]
@Meylama I apologize I am in a bad mood for some reason xD sorry

**Comment by OMGchangeMYusername** [comment]
Lol.

**Comment by LolDatSec** [comment]
@Meylama just substitute the wurst logo with a blank png file, problem solved. :palm_tree: :)

**Comment by pokeball99** [comment]
^

**Comment by Meylama** [comment]
@LolDatSec Thanks, nice idea! :+1:

**Comment by LolDatSec** [comment]
Np mate. :smile:
