### ISSUE TITLE
.skinsteal command

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1388]
".skinsteal [Username]" to steal the skin of a player and save it to the Wurst folder.

This would be much more simple than:
.addalt
Go to alt Manager
Press "Stealskin"
Go back to alt manager
Press "Delete"
Go back to mainscreen
Go to "Multiplayer"
Join the server again
See a player with a nice skin, have to do the same steps again....

**Comment by OMGchangeMYusername** [comment]
I agree. Haven't changed my skin in a while so would love this.

**Comment by mcccs** [comment]
I'll love this command and i hope the "Skin" button will come to Altmanager
