### ISSUE TITLE
Disable commands

### ISSUE THREAD

**Issue by LastIdi0t** [Wurst-Imperium/Wurst-Client#1389]
a thing to disable/change the prefix for a command so when they ask to type a . you can type it with a button in the clickgui would be nice

**Comment by Meylama** [comment]
@LastIdi0t you ever heared of ".say".....? Just type ".say .help" or ".say ." you....

**Comment by GummiBoat** [comment]
# *Duplicate: #141*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
