### ISSUE TITLE
Can you make regen hack regen really fast when you eat golden apples on servers with no natural regeneration?

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#139]
What I mean is that on Hypixel UHC I have tried to use the Regen hack and it is not working. It might be because I have YesCheat+ enabled, but Hypixel UHC has no natural regeneration. Please look into this issue as soon as possible.

Thanks, 
Edtlogin

**Comment by Alexander01998** [comment]
Regen already does that, but Hypixel's NoCheat+ blocks it.
