### ISSUE TITLE
Where is alexander?

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#1390]
Well as you guys can see... this is the 200 issue here.

Anyone have news from him?

**Comment by Meylama** [comment]
He is in vacation. Or dead.

**Comment by JackFishbaugh** [comment]
^hes dead.

**Comment by agucova** [comment]
I can probably take the project xD

**Comment by Meylama** [comment]
Well  @agucova, then take it :D

**Comment by JackFishbaugh** [comment]
@agucova can i be your manager? :]

**Comment by Meylama** [comment]
@agucova can I be your manager too? :D

**Comment by OMGchangeMYusername** [comment]
DUPLICATE #1346 
Can you stop this? @Nitrogen-Dioxide thought you wouldn't do such thing..

**Comment by TekkitCommando** [comment]
@Alexander01998 I think @Meylama, @JackFishbaugh, and @agucova are planning to overthrow you 0-0

**Comment by pokeball99** [comment]
LOL @TekkitCommando indeed they are,maybe they are the fbi trying to undermind @Alexander01998 ,or maybe there just accounts i made,we might never know :O
