### ISSUE TITLE
Crash: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by agucova** [Wurst-Imperium/Wurst-Client#1391]
My Java Version is not compatible!
You will need to change your compiler compliance level back to 1.7 in your IDE. This can be done in the prefences settings of your IDE for example in Eclipse go to Windows ---> Prefences then select Java and expand it then select Compiler and change the compliance level to 1.7. Am sure this will work from there

**Comment by GummiBoat** [comment]
How about you just update your Java? :) There's an [entire Wiki Page](https://github.com/Wurst-Imperium/Wurst-Client/wiki/Using-Wurst-with-Java-8) on how to do so.

**Comment by bob80333** [comment]
Wurst 2.0 and onwards takes advantage of some Java 8 features.

**Comment by TekkitCommando** [comment]
Did he just tell the developer to change the Java Version just for him, that's great xD

**Comment by agucova** [comment]
The compatibility problem makes even some 1.8 version to fail.

**Comment by bob80333** [comment]
If you are using a Mac, running the Linux launcher should fix the problem.

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
