### ISSUE TITLE
Teleporting Freecam

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1395]
So, when you turn on Teleport Freecam, then go somewhere, and turn it off, then it would teleport you there. Is this possible?

**Comment by Meylama** [comment]
No this is not possbible.

**Comment by GummiBoat** [comment]
This is already implemented and is called `Blink`.

**Comment by Meylama** [comment]
@GummiBoat Blink is not the same what he means. I think he means flying with freecam 200 blocks away and also through walls etc, with teleport.

**Comment by GummiBoat** [comment]
Well, that's - as you said - impossible, on Bukkit Servers. Even on Vanilla it's difficult.
