### ISSUE TITLE
Something to ignore invisible players

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1396]
My favorite skywars server was ruined for me forever because it made it so BowAimbot aims at something invisible (that is not a player), and moves around way too quick. I want it to be bypassed so that I can play (the fun way) on skywars.

**Comment by GummiBoat** [comment]
You should probably select "Players" only in your Target-Selector. You can reach that via ClickGUI in the Combat Tab.

**Comment by labcraft59** [comment]
I did...

**Comment by bob80333** [comment]
Perhaps they are using invisible armor stands?

**Comment by labcraft59** [comment]
maybe... the server is piston mc... heard of it?

**Comment by labcraft59** [comment]
This is the ip: MC.PISTONMC.COM

**Comment by labcraft59** [comment]
then go to skywars with bowaimbot

**Comment by Meylama** [comment]
I have investigated a little bit: they use a simple anti-killaura plugin (or to say it exactly: this one: https://www.spigotmc.org/resources/aac-advanced-anti-cheat-hack-kill-aura-blocker.6442/) which spawns invisible NPC's to check if you have killaura. This also disturbs BowAImbot.

**Comment by labcraft59** [comment]
Oh wow. That's mean.

**Comment by OMGchangeMYusername** [comment]
#809

**Comment by labcraft59** [comment]
Yay! This would be great!

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

As I saw on that plugin... the players doesn't have name problaly (or a very strange name). So it is not hard to bypass that right?

**Comment by PixelMaster3D** [comment]
That could be but if the person were to disable name tags and hide players name then it would be confusing the hack.

**Comment by Eyremba** [comment]
@Nitrogen-Dioxide No, this plugin gives the fake-players random Names, and if you are in PvP, the player above you gets visible, so an a feature to ignore invisible entities would not be useful against this plugin.

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 

I noticed that, ignore flying players would be useful too? ( if there is a way to know if the other entities is on the ground )
