### ISSUE TITLE
Suggestion: Optifine

### ISSUE THREAD

**Issue by C0de-Ninja** [Wurst-Imperium/Wurst-Client#1401]
Integrate Optifine into wurst

**Comment by TekkitCommando** [comment]
No :) Duplicate #2

**Comment by pokeball99** [comment]
can we just put something in wurst it self saying we wont add optifine?

**Comment by TekkitCommando** [comment]
I got an idea xD

**Comment by TekkitCommando** [comment]
I am bored, Hopefully Alexander doesn't get mad about that pr hmmm
