### ISSUE TITLE
CrashChest Auto drop

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1406]
in order to give a player crash chest u either have them take them from a chest or u drop it on them. it takes a while to drop it on them so if u can have the .throw command for the chests accept its automatic. basically when u get the chest it keeps dropping stacks of it infinitly till u turn it off

**Comment by OMGchangeMYusername** [comment]
That might be part of `.drop`. Since Throw is not supposed to drop things, it basically throws more things at once (only for snowballs and eggs i assume).
