### ISSUE TITLE
what does timer affect?

### ISSUE THREAD

**Issue by Pkgts** [Wurst-Imperium/Wurst-Client#1407]
what are the uses? does it make mobs spawn faster from grinder or crops grow faster? is there a limitation to how i can use it in multiplayer?

**Comment by pokeball99** [comment]
....it's 1 am in the morning for me,can someone else explain this for him/her?

**Comment by LolDatSec** [comment]
@Pkgts it only affects your own physics as far as know, fall, jump, move, I think animated texture too, but not other entities' interaction.

(Works on vanilla.)

**Comment by mcccs** [comment]
Affects M.Cy. .taco command

**Comment by GummiBoat** [comment]
It should render everything x times so fast.

**Comment by OMGchangeMYusername** [comment]
Basically what @LolDatSec said, it can't change anything controlled by the server, and it doesn't work on non vanilla servers.

**Comment by Meylama** [comment]
@OMGchangeMYusername wrong, it works not only on vanilla servers. It works also on Bukkit, Spigot, etc. The important point is that NCP is BLOCKING timer, if a Bukkit or Spigot server has no NCP, you can also use the timer there.

**Comment by GummiBoat** [comment]
NCP is not blocking timer. But since you are actually x times so fast, NCP will block it, if you are too fast for a "normal" person. So you can still activate Timer on NCP Servers, but you can't go over 1.2 or sth like that. Everything slower than 1.0 works fine too.

**Comment by Meylama** [comment]
Yes @GummiBoat, that was that what I meaned.

**Comment by OMGchangeMYusername** [comment]
I've tried every single value on NCP servers, it never works..

**Comment by OMGchangeMYusername** [comment]
idk what was wrong with me, i actually meant anticheat servers but felt like changing the phrase a little..? dunno~~
