### ISSUE TITLE
Fakebreak

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1408]
a mod, that breaks block with only one hit like in gamemode and hide them
like blink or freecam does it if you walk away and break blocks

**Comment by Meylama** [comment]
It would be only possible if you are not more than 5 blocks away from the block, else it can not be broken.

**Comment by ravenje** [comment]
no i mean fake break it
client side render clicked blocks as air

**Comment by OMGchangeMYusername** [comment]
how can it be helpful?

**Comment by ravenje** [comment]
Fakegreifs, fun :D

**Comment by GummiBoat** [comment]
@OMGchangeMYusername There was a glitch (I don't know if it still works or not), when you walk into those fake blocks, and log out & in again, you'll get teleported into safety (mostly on top of the structure).

**Comment by Meylama** [comment]
"no i mean fake break it
client side render clicked blocks as air"

You mean like doing a gamemode 1 for freecam, so when you are in freecam you can break blocks client-side like being in creative mode?
