### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by IIYaNkIeII** [Wurst-Imperium/Wurst-Client#141]
Could u add .Prefix to Wurst please.

**Comment by GlitchHead** [comment]
wtf will dis do explain more please. thanks.

**Comment by IIYaNkIeII** [comment]
It lets you set prefix to wurst commands for example you need to put a dot infront of a wurst command so it can work but with prefix it lets you change what u have to put infront of the client command. It can help u when u have to prove you dont have a hack client by saying something with a dot infront of It.(if its not clear you can search what are prefix in minecraft hack client)

**Comment by Krowit** [comment]
Isnt that possible already by .say

**Comment by IIYaNkIeII** [comment]
Oh lol I guess, I didn't know that was in wurst well thank you.
