### ISSUE TITLE
.lore command

### ISSUE THREAD

**Issue by HeartOfShrapnel** [Wurst-Imperium/Wurst-Client#1410]
Uses the same shortcuts as .rename, hold the item (creative mode only) and rewrite an item's lore
example: .lore $d$l$oFabulous!
would make the items description/lore a pink bold italic "Fabulous"

**Comment by OMGchangeMYusername** [comment]
#342 should do that, but it's not implemented yet, also visit #604 just in case.

and please read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository, mainly the issues section.

**Comment by Meylama** [comment]
"example: .lore $d$l$oFabulous!"

Please remeber that there can be more than 1 row/line in a lore.

So it should be ".lore row text" like ".lore 1 $l&6Test"

**Comment by HeartOfShrapnel** [comment]
Some commands have /give disabled or changing metas on items disabled, meaning someone like me with no permission to apply "vanilla" meta to an item couldn't change item lores. I'd like a little way around this and also and easier way to create custom item lores.

**Comment by ravenje** [comment]
Duplicate #604

**Comment by MyzticalTekkno** [comment]
@HeartOfShrapnel , 2 Reasons
1. Its an Operator Command.
2. You could make SignOp With it and many server aware on that being happened
