### ISSUE TITLE
AnnoyCmd description

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#1412]
@Info(help = "Annoys a player by repeating everything **he** says."
What if its a **she**??

**Comment by Bluscream** [comment]
>.> #INVALID

**Comment by Meylama** [comment]
"he", the player. And now stop opening fucking useless issues.

**Comment by mcccs** [comment]
XD

**Comment by Alexander01998** [comment]
Come on, don't be a feminist.

**Comment by Murplyx** [comment]
I am not a feminist :P
