### ISSUE TITLE
Annoy feature broken?

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1415]
![u6ug3uv](https://cloud.githubusercontent.com/assets/13311598/8958733/ca13f0b8-3606-11e5-921e-5d129df361d0.png)

I annoyed "marco213" in this example but no messages of him were repeated.
Is this feature broken?

**Comment by mcccs** [comment]
some servers change their name
In mineplex:
6MCCCS
the number is your level

**Comment by OMGchangeMYusername** [comment]
Didn't know about that. @mcccs so how can i annoy someone on mineplex?

**Comment by Meylama** [comment]
"some servers change their name
In mineplex:
6MCCCS
the number is your level"

This could be here the same, but with the clan-tag I think. Like in this case, the clan tag of "marco213" is "MM".

**Comment by GummiBoat** [comment]
No, annoy only works if a few conditions are met tho.

The conditions are:
* Message starts with `<name>`
* Message contains `name>`
* Message contains `] name:`
* Message contains`]name:`

Since none of this applies to `] name :`, it won't get repeated.

**Comment by Meylama** [comment]
Thanks for your explanation @GummiBoat! :)

**Comment by Alexander01998** [comment]
Any decent servers using `] name :`?

**Comment by Meylama** [comment]
The server on which is way playing was a german ~800 Slot cracked Server, so it would be really nice to implement the Pull-Request of GummiBoat and this patch.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 Hypixel.

**Comment by OMGchangeMYusername** [comment]
And i just checked out, they use `[VIP] Name:`

**Comment by Alexander01998** [comment]
> And i just checked out, they use [VIP] Name:

`] name:` (without a space before the `:`) is already implemented.

**Comment by Alexander01998** [comment]
I don't think this will be worth it, as no decent servers are using `] name :`.
