### ISSUE TITLE
New command suggestion: ".ignore"

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1416]
".ignore" - ignores a player and does not display his chat messages on your client. (for example if anybody is insulting you etc.)
Basically like the /ignore of the essentials plugin but client-side.
1. not every server has essentials.
2. on many servers you have no permission for /ignore

**Comment by OMGchangeMYusername** [comment]
:+1: it'd be totally useful.

**Comment by LolDatSec** [comment]
Would be interesting to see how nickname handles though.

**Comment by OMGchangeMYusername** [comment]
??

**Comment by LolDatSec** [comment]
Essentials `/nick` command changes how a username is displayed to the client.

**Comment by GummiBoat** [comment]
@LolDatSec well, since the client probably will search for text that's being sent for him, you'd have to ignore the nickname.

Or maybe it would work with UUID, since every client can access others UUIDs.

**Comment by LolDatSec** [comment]
@GummiBoat works too, I wasn't thinking. :smile:
