### ISSUE TITLE
Get java 8?

### ISSUE THREAD

**Issue by wuofwhat** [Wurst-Imperium/Wurst-Client#142]
I updated my java to java 8 and its telling me to update java to java 8.
Why?

**Comment by wuofwhat** [comment]
Verified Java Version
Congratulations!
You have the recommended Java installed (Version 8 Update 31).

**Comment by Alexander01998** [comment]
You probably have multiple versions of Java installed and are launching Minecraft with an old version.

You can solve this problem by simply uninstalling all old Java versions, so that only the newest Java 8 version remains.

As a side effect, this will also make your computer more secure, because you will no longer be affected by all the security flaws of the old Java versions.

**Comment by wuofwhat** [comment]
"You can solve this problem by simply uninstalling all old Java versions, so that only the newest Java 8 version remains."

I am not sure how to do this :/ 
Plz tell me.

**Comment by Alexander01998** [comment]
> I did it but still says get java 8!

Open the console and type `java -version`. It will tell you your real Java version, which is either 1.6 or 1.7. Not only is this the most accurate way to check your Java version, but it's also the way how Wurst checks your Java version. So as long as Wurst shows that message, you are not using Java 8.

**Comment by wuofwhat** [comment]
java version "1.7.0_17"
Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)


Strange i am sure there is something wrong then i am not sure how to fix it.

**Comment by GlitchHead** [comment]
Java version "1.7.0_17" is Java 1.7 not 8.... try this: in the edit profile section of the launcher try setting the executable to the javaw.exe in the java 8 folder that is in your program files.

**Comment by wuofwhat** [comment]
![java](https://cloud.githubusercontent.com/assets/10894844/6540300/7d42d08e-c49f-11e4-90a5-2d63201fa869.jpg)

**Comment by Alexander01998** [comment]
Try the new Minecraft launcher. It has the latest Java 8 built in.

**Comment by huoh** [comment]
try java 8

**Comment by huoh** [comment]
just like alex say'd

**Comment by huoh** [comment]
hi wuofwat my friend!

**Comment by wuofwhat** [comment]
I tried and its still not working.

**Comment by huoh** [comment]
try again

**Comment by GlitchHead** [comment]
now try and find were Java is stored you may have Java 8 but your JAVA_HOME is not set to it its set to 1.7.0 so use this thing called "google" and search how to change JAVA_HOME mac and set it to were the Java 8 bin folder is located.

**Comment by SuperJuicy** [comment]
I am having the same problem but when I go to terminal and type "java -version" it sys I am using 1.8. But when I open the latest version of Wurst it says I am in 1.6

**Comment by Alexander01998** [comment]
> I don't know what else to do. SOMEONE PLEASE HELP! @Alexander01998

Just look at the comments above - plenty of methods to solve that problem.

**Comment by SuperJuicy** [comment]
I think the problem might be that I have multiple versions of Java on my computer. I'm not sure how to do this so can  you please tell me how. Im on a Mac. Thank you

**Comment by SuperJuicy** [comment]
All the solutions above haven't worked. I sent you a Skype request. Please add it so we can try to figure out what the issue is. @Alexander01998 Thanks!

**Comment by Alexander01998** [comment]
Anyone still struggling with this, have a look at #1224.
