### ISSUE TITLE
i have a large rainbow changing line on my screen

### ISSUE THREAD

**Issue by Pkgts** [Wurst-Imperium/Wurst-Client#1421]
as if its a tracer... but even w/ tracers turned off its still there... pointing towards the west

**Comment by pokeball99** [comment]
thats likely player finder

**Comment by Pkgts** [comment]
i dont think so because it shows up even when im the only one on servers

**Comment by pokeball99** [comment]
player finder is broken so it just show a near by lighting strike

**Comment by Pkgts** [comment]
the rainbow is consistent on every server i join
its not jut for one server

**Comment by GummiBoat** [comment]
Could you make a screenshot?

**Comment by Pkgts** [comment]
update: restarted client and its gone

if it comes back ill tell you guys w/ a screenshot

**Comment by Alexander01998** [comment]
1. It is PlayerFinder.

2. PlayerFinder is not broken, it's supposed to work like that.

3. This Issue is a duplicate. I'm using the GitHub app right now, so I can't look up the other Issue's number.
