### ISSUE TITLE
better .ip

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1422]
in flare u can get the real ip,not just the hostname,here is the deofcucated flare
https://mega.co.nz/#F!M8QhQRob!D8T-A4E9LT75mM8tZYQHlg (its Flare 3.5.zip,im just too lazy to just point u to that)
use for this would be for the server finder

**Comment by GummiBoat** [comment]
WindowsKey+R -> Write "Cmd" (without "") + Enter -> write "ping HOSTNAME" -> rightclick, select -> select the ip and press enter -> ... -> profit.
![swag](https://cloud.githubusercontent.com/assets/10976441/8963399/4a64654a-3620-11e5-8ca4-24de155f3a15.gif)

**Comment by pokeball99** [comment]
i know that method,but this would be ingame

**Comment by ravenje** [comment]
Noobs

**Comment by LolDatSec** [comment]
DNS resolution...
There is a built in java function for it I think.
In PHP it is `gethostbyname($domain);`

**Comment by WurstContributor** [comment]
yey alex is back. And kumfrimed not ded.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
Giving the port is possible too right? Because bunguee cord servers have different ports/ips for each server.

**Comment by Alexander01998** [comment]
> Giving the port is possible too right? Because bunguee cord servers have different ports/ips for each server.

Wouldn't be practical, as port scanning takes about 15 minutes per server (1024 servers => 10,667 days to run Server Finder once) and most servers use the default port (25565) anyways.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

At least it is easy to find the default ports (http ftp...)

**Comment by LolDatSec** [comment]
@Nitrogen-Dioxide 
On most linux systems binding to port 1-1024 requires you to be superuser or root.
So if you have nmap and you are keen, you can do this `nmap -sV -p 1025-65535 <ip/hostname>`.
I have seen servers with 150 instances of minecraft vulnerable to botting attacks.
