### ISSUE TITLE
Syncstop Button

### ISSUE THREAD

**Issue by Meylama** [Wurst-Imperium/Wurst-Client#1423]
If you use the Serverfinder Mod in Wurst, it can add up to 100 servers to your multiplayer server list.
BUT: Every time you do anything in this list (for example, joining a server and then go back to the multiplayer menu), it pings and synchronizes all of this 100 servers..... and this takes time.... and time.... and time...

Therefor, there should be a button in the multiplayer menu to stop this synchronisation. So Wurst will keep the slot amount, the MOTD, ping and player count from the last synchronisation in a cache, so that you can join/test server by server, rename them, delete them, add them etc. without that minecraft have to synchronize all few seconds all ~100 servers which can take A LOT of time for this ~100 servers with a slow internet connection 

I think such a feature should be possible

**Comment by 1337HaxorKiddie** [comment]
Good idea, i have the Same problem!

**Comment by Alexander01998** [comment]
Joining a server and then going back to the server list does **not** reping them. If it appears to you like it does, that means that you didn't give it enough time to finish the first ping.

Btw: The maximum is much higher than 100 servers. I've had close to 200 servers sometimes.

**Comment by 1337HaxorKiddie** [comment]
OK than it don't ping again BUT for me minecraft Freezes every time when i go to the Multiplayer GUI(Not only the firsttime Ehen i startet the Client)
