### ISSUE TITLE
Skin blinker bug

### ISSUE THREAD

**Issue by 32rhys32** [Wurst-Imperium/Wurst-Client#1426]
I have an issue upon the skin-blinker or any other name you with to call it, I tried it out once as it was a new feature and as soon as I turned it off it removed the overlay on my skin, even if I turn the client off and go on a non hacked account the skin has still lost its overlay?! I have tried resetting to my skin with the overlay but it appears still gone, as well as shutting down minecraft, my computer and anything else open, the only way I can see it is by using skin blinker and it flashes again, should it do that or should it return to the overlay skin when turned off?

**Comment by GummiBoat** [comment]
# *Duplicate: #1264*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by 32rhys32** [comment]
@GummiBoat I have read this yet do not understand the concept, it does not elaborate where to put the code or how to use it to enable the 3d layers, and I am still left with a bugged skin

**Comment by Meylama** [comment]
"it does not elaborate where to put the code or how to use it"

Nothing. Just wait for the next Wurst released.

And if you already didn't get it, you can activate the damn layers manually in the minecraft settings.

**Comment by 32rhys32** [comment]
where do I find the mc settings and what section? @Meylama

**Comment by Meylama** [comment]
"where do I find the mc settings and what section?"

I think you never heared about google, right..?

**Comment by 32rhys32** [comment]
I have I am new to this, I am not sure what I am doing at the moment

**Comment by 32rhys32** [comment]
i have got it working thank you

**Comment by OMGchangeMYusername** [comment]
I literally came assmad here because of the comment on the original suggestion issue, but Gummi did it before me :P
