### ISSUE TITLE
.zoom

### ISSUE THREAD

**Issue by ObamaBinLaden** [Wurst-Imperium/Wurst-Client#1429]
could you maybe add a .zoom like zoom mod and optifine so that we can zoom in it can come in handy when you want to see stuff far away, thank you
p.s.
maybe a .minimap or something would be cool ;D

**Comment by GummiBoat** [comment]
# *Duplicate: #324*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)
