### ISSUE TITLE
.search

### ISSUE THREAD

**Issue by davidkoplik** [Wurst-Imperium/Wurst-Client#1431]
What does it do?

**Comment by Meylama** [comment]
Just read in the Wiki instead of making fucking issues for your trash.
https://www.wurst-client.tk/wiki/Main_Page/

**Comment by GummiBoat** [comment]
@Meylama please keep calm. There always are new people. @davidkoplik As Meylama mentioned, there is a wiki page for every command. To be more specific, here's the [wiki entry for search](https://www.wurst-client.tk/wiki/Commands/search/).

**Comment by davidkoplik** [comment]
Thank you!
