### ISSUE TITLE
.wms

### ISSUE THREAD

**Issue by davidkoplik** [Wurst-Imperium/Wurst-Client#1432]
What is it supposed to do?

**Comment by Meylama** [comment]
Just read in the Wiki instead of making fucking issues for your trash.
https://www.wurst-client.tk/wiki/Main_Page/

**Comment by GummiBoat** [comment]
All commands are explained on our Wiki, that Meylama linked :) To be more specific, [here is the link](https://www.wurst-client.tk/wiki/Commands/wms/) to the .wms page.

**Comment by LolDatSec** [comment]
It is these type of contributions that do more harm than good. Please use the wiki like @GummiBoat specified, and please read CONTRIBUTING.md, it exists for a reason! :smile_cat: 
https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md

**Comment by davidkoplik** [comment]
Thanks to all of you!

**Comment by davidkoplik** [comment]
But still... What is it useful for?

**Comment by OMGchangeMYusername** [comment]
Maybe recording? or a reminder of any sort? 
maybe a spam file with this command typing things you should remind when on that specific server? (just an idea flew to my mind :P)

**Comment by OMGchangeMYusername** [comment]
"Question" label ?
