### ISSUE TITLE
Suggestion: Magnet and player hide

### ISSUE THREAD

**Issue by SongHout** [Wurst-Imperium/Wurst-Client#144]
As you know sometime some server having a drop party! More people causing lag and a hack mod that suck all item drop!

**Comment by pokeball99** [comment]
y not add magnet?its would be a useful hack that could be use for a multitude of things

**Comment by Alexander01998** [comment]
> y not add magnet?its would be a useful hack that could be use for a multitude of things

In a nutshell: Because Minecraft doesn't work that way.

**Comment by 1337HaxorKiddie** [comment]
I don´t now if this is working without Water, but if you have Jesus enabled and Item-Drops are on the ground of the Sea i can wlk with Jesus about the Items and i can pick them up. Although the Items can be 100 Blocks under me.
