### ISSUE TITLE
Macros 

### ISSUE THREAD

**Issue by IIYaNkIeII** [Wurst-Imperium/Wurst-Client#146]
Could u add Macros to wurst , this is like binds but instead of you adding a key to a mod in wurst you can add a key to a command you whant to do  like the mod /home u can change it to /sethome or something else. Thank you

**Comment by IIYaNkIeII** [comment]
For the command you could do .macro add (/what ever command) (what ever key u whant)

.macro add /spawn R

**Comment by MisterQuatsch** [comment]
No,
ther are many programs out that can do that.

**Comment by GlitchHead** [comment]
this was already added #131 just wait for the next update in wurst.

**Comment by Alexander01998** [comment]
Duplicate: #34
