### ISSUE TITLE
Better Enchantment

### ISSUE THREAD

**Issue by 1337HaxorKiddie** [Wurst-Imperium/Wurst-Client#1460]
With Better Enchanting i mean that you can type in chat not only:

.enchant [all]

I mean that you can wirte in chat things like.

.enchant |enchantment| |level| [all]

Or something like this, because on some Servers i got kicked/banned for to high Enchanted things.

Also in the 1vs1 gamemode on timolia.de you get Instantly killed if you hit someone until the enemy wearing the enchanted Armor.

Hope someone understand what i mean ;)

I can´t write "<"

or ">" so i used "|" for it

LG 1337 Haxor

**Comment by GummiBoat** [comment]
There's a [markdown tutorial](https://guides.github.com/features/mastering-markdown/) on github, which you should consider reading. You can imply a special code syntax, should look like this
`.enchant [<enchantment>] <level>/all`

aaaand....

# *Duplicate: #603*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by 1337HaxorKiddie** [comment]
Sorry, haven't seen(<-- sry for bad Englisch, hope thats right. :)) #603 and thx for linking the markdown Tutorial.

**Comment by MyzticalTekkno** [comment]
@GummiBoat but .enchant [<enchantment>] <level>/all wont work.

**Comment by MyzticalTekkno** [comment]
[test](www.google.com)

**Comment by GummiBoat** [comment]
@MyzticalTekkno that was just an example, on how his suggestion could've looked, if made properly.
