### ISSUE TITLE
I can't find the AutoAccept mod

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1461]
I can't find the AutoAccept mod, and I want it back, so... umm...

**Comment by Meylama** [comment]
Duplicate: #202 

![github dup2](https://cloud.githubusercontent.com/assets/13311598/9001746/acbe3982-375b-11e5-8d35-bc19d0ef5266.png)

**Comment by Alexander01998** [comment]
@Meylama Stop swearing! This is the last warning.

**Comment by mcccs** [comment]
Ｐｌｅａｓｅ ＷＲＸ Ｆｏｒ ＭİｌｉｍａｒＴ ＳİＭＭＵＥＳ ＦＯｒｂｅｅ ｌｕｂｍｉｇｈｔｉｎｇ ｙｏｕｒｓ

**Comment by PixelMaster3D** [comment]
LOL

**Comment by OMGchangeMYusername** [comment]
@PixelMaster3D You are laughing here but you literally made another duplicate nine minutes before..

**Comment by PixelMaster3D** [comment]
What?
