### ISSUE TITLE
ChestStealer for specific items

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#150]

**Comment by GlitchHead** [comment]
What do you mean? Please include more info.

**Comment by Edtlogin** [comment]
I mean that you should make a mod like AutoSteal, except you can tell it what items to steal from the chest you open.

**Comment by OMGchangeMYusername** [comment]
this would be sort of handy but i guess it's not too important..

**Comment by Alexander01998** [comment]
It needs a good implementation, something that is fast and easy to use.

**Comment by pokeball99** [comment]
U could just make it look for the ID of the items and just steal anything with that ID,right?

**Comment by Alexander01998** [comment]
> U could just make it look for the ID of the items and just steal anything with that ID,right?

Yes, that is the easy part. Making it possible to update the list of items to steal in only a second is the tricky part.

For instance, say you run out of food and want to add all food items to the list. Once you got enough food, you want to remove all food items from the list. Typing in all the IDs using a command would take forever. A GUI with a search bar would be a little faster, but still way too slow.

**Comment by pokeball99** [comment]
Have presets?

**Comment by Edtlogin** [comment]
I don't mean anything like what you said about the food. I mean that it steals an item NO MATTER WHAT, like steal food even if your hunger bar is full. When you type that item into the GUI,  it'll keep stealing that item from chests if they have it.

Good wishes,
Edtlogin

**Comment by Alexander01998** [comment]
> I don't mean anything like what you said about the food. I mean that it steals an item NO MATTER WHAT, like steal food even if your hunger bar is full. When you type that item into the GUI, it'll keep stealing that item from chests if they have it.

I didn't mean that either. I talked about the player manually adding & removing items from the list of items to steal.

**Comment by pokeball99** [comment]
As I said,u can just have presets,and many have able to be toggle able by a keybind

**Comment by pokeball99** [comment]
Or better yet just make it like a spam file,with the preset set table via say .cheststeal <file> on:off
