### ISSUE TITLE
Poison, dropped item trajectories.

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1516]

**Comment by GummiBoat** [comment]
What?

**Comment by mcccs** [comment]
Same trajectories but with potion bottles' dropped items' physics

**Comment by GummiBoat** [comment]
So, another trajectories mod? You know how Alex thinks about trajectories?

**Comment by OMGchangeMYusername** [comment]
Wow.. mccs can you please stop opening issues? Trajectories itself is for every throwable item, you'll find it working for such items in mostly every client, so yeah the actual mod should already do this.

**Comment by mcccs** [comment]
Ok ill
