### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1517]
Block PArty HAck and speed

**Comment by 1337HaxorKiddie** [comment]
Only 1 Mod in 1 Issue! Speed is already in Wurst.

**Comment by EnderGamer21** [comment]
really

**Comment by EnderGamer21** [comment]
whats speed called

**Comment by EnderGamer21** [comment]
i mean speed by faster than sprint

**Comment by EnderGamer21** [comment]
whered u go

**Comment by EnderGamer21** [comment]
speed i mean speed by faster than auto sprint and add that to nocheat+ or was i

**Comment by EnderGamer21** [comment]
plz fix resource packs every time i try to put a resource pack it crashes

**Comment by OMGchangeMYusername** [comment]
Invalid. Are you stupid? no you are not. But please use your mind.
YOU suggested speed before and i told you it's duplicate #1038.
BlockParty is also a duplicate #528, Search for old issues!!

**Comment by EnderGamer21** [comment]
srry

**Comment by EnderGamer21** [comment]
plz make remote view farther when i target a specific entity  it say it cannot spot i used it in servers they did not logout 
so cold u make the remoteview longer so it can reach farther

**Comment by GummiBoat** [comment]
You should open seperate Issues for seperate suggestions. So, if you have any furter Ideas, search if someone already suggested it and if not, create a new Issue. That's simple, isn't it?

And remoteview should work as long as the player is in a rendered chunk. That depends on you, not on the client. You can change that under ESC -> Options -> Video Settings -> View Distance.

**Comment by OMGchangeMYusername** [comment]
Nope. Don't open more issues and ask here if you got any more dumb questions.
This will be "invalid" anyway.

**Comment by 1337HaxorKiddie** [comment]
@EnderGamer21 Can you please stop spamming if you have a prblem search for it:https://github.com/Wurst-Imperium/Wurst-Client/issues

If you not found the issue that you wanted to suggest than you can open a Issue

**Comment by GummiBoat** [comment]
@OMGchangeMYusername everyone is free to open new Issues and contribute to the client, whilst he should regard the  8contributing guidelines 9.

**Comment by OMGchangeMYusername** [comment]
What would be the point if he opens ten issues which are all either duplicate or half stupid questions?
I'm saying let's use this chance to make the issues less, this will be invalid anyway so ask whatever you want @EnderGamer21. (**New** suggestions should be in new issues of course).

**Comment by GamingGamer12** [comment]
oh my brothers first comment
