### ISSUE TITLE
How to modify the auto-updater and message in source code?

### ISSUE THREAD

**Issue by PieCrafted** [Wurst-Imperium/Wurst-Client#1518]
Just for shits and giggles, I would like to know where to change the option to get the auto update from and where the wurst client gets its "emergency messages" from the developer.

I would love to play around with it all.

**Comment by OMGchangeMYusername** [comment]
The [Auto-updater] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/update/Updater.java).
I didn't get what you mean by the "message" did you mean Wurst news?

**Comment by GummiBoat** [comment]
[Updater](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/update/Updater.java) and [emergency messages](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/message/gui/GuiMessage.java).

**Comment by OMGchangeMYusername** [comment]
Oh i see :c

**Comment by PieCrafted** [comment]
Thanm you :)
