### ISSUE TITLE
Fast Driving In a Minecart without rails

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1519]
u can drive in aminecart like a car without needing rails or any other kind of rails

**Comment by GummiBoat** [comment]
I think that's a plugin...

**Comment by EnderGamer21** [comment]
whats it called

**Comment by EnderGamer21** [comment]
whered u get it

**Comment by EnderGamer21** [comment]
anyway it wolud be cool if u could do that in sigleplayer it would be uesful or a rp
it would be useful

**Comment by 1337HaxorKiddie** [comment]
@EnderGamer21 it seems like you are New in the Coding scene.

**Comment by Nitrogen-Dioxide** [comment]
Minecart is an entity, so, I think that only the server have control of it.

**Comment by mcccs** [comment]
^
