### ISSUE TITLE
Lagger

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#152]
Makes lags and slows down the server. The other players will die because they lag.

**Comment by OMGchangeMYusername** [comment]
dosen't make any sense.

**Comment by Alexander01998** [comment]
Duplicate #52

**Comment by OMGchangeMYusername** [comment]
i don't think he meant something close to the creative dropper (coz he said the other players will die)
he must've meant something that has to do with pvp.
anyway i still think it's too hard if not impossible to make such a mod.
