### ISSUE TITLE
Sign Aura

### ISSUE THREAD

**Issue by 1337HaxorKiddie** [Wurst-Imperium/Wurst-Client#1521]
Sign Aura means that Wurst automaticly clicks on every Sign in the range of the player. But why?

Easy Answer! On big servers like hive or gomme, its sometimes difficulty to come in a lobby because they are mostly full. But if Wurst clicks automaticly every Sign in range it should be pretty easy to connect to a lobby.

**Comment by OMGchangeMYusername** [comment]
Useless. I really don't see the point of a whole mod although i find some hard time on HiveMC..
Also how is it supposed to work?

**Comment by 1337HaxorKiddie** [comment]
How is it supposed to work? Uhm like Chest Aura? U know?

**Comment by OMGchangeMYusername** [comment]
I mean there are "full" signs, and there are "booting" signs. How would Wurst handle them?

**Comment by 1337HaxorKiddie** [comment]
Wurst can check if the sign Text changed, i think. And anway it doesn't matter if loading or not.

**Comment by OMGchangeMYusername** [comment]
Still i really don't see why it'd be necessary, disable players and find an empty map.

**Comment by 1337HaxorKiddie** [comment]
What?! Disabke players what the fuck are you talking?

**Comment by OMGchangeMYusername** [comment]
![wow..] (http://puu.sh/jkpMF/e7710874ff.png)

**Comment by OMGchangeMYusername** [comment]
If you still didn't get it, rightclick the lime dye so it becomes gray and you won't see anyone.
That makes it easier to pick a map.

**Comment by 1337HaxorKiddie** [comment]
Ohh, sry i was confused now i know what you mean, but anway go on Timolia.de or some other Servers. Also if you disable the players you have like a second time to click in the sign else the Server is full.

**Comment by GummiBoat** [comment]
@1337HaxorKiddie hold rightclick while the server is restarting.

**Comment by 1337HaxorKiddie** [comment]
Go in Timolia and you See there are no restarting Servers because its a cloud system also on GommeHD

**Comment by Alexander01998** [comment]
Gomme kicks everyone who doesn't buy VIP after just a few seconds.

For the other servers:
> hold rightclick while the server is restarting together with fastplace. easy entry every time.

**Comment by OMGchangeMYusername** [comment]
I'm not German and I've tried GommeHD ages ago because someone said it has a very solid anticheat, the thing that sucked is there's absolutely nothing in english :o

**Comment by Meylama** [comment]
@OMGchangeMYusername they have now /language english
