### ISSUE TITLE
30 FoV Toggling (AKA Zooming)

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1522]
Maybe add the only good thing about optifine? It could be a setting with a key like optifine, or a wurst mod that u can add a keybind for. This can be useful.

**Comment by OMGchangeMYusername** [comment]
Duplicate #324.

**Comment by OMGchangeMYusername** [comment]
Read this [article] (https://help.github.com/articles/searching-issues/) about searching issues, it makes things tons easier for both of us.

**Comment by Bluscream** [comment]
@JackFishbaugh So the zoom in Optifine is basically just toggleing your FOV to the lowest value, lol?
