### ISSUE TITLE
Wurst not saving logs

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1526]
For some reason when i start the wurst client like normal and join servers and chat then leave and quit game there are no logs in  ``` .minecraft/log/latest.log ``` i have cleared my logs and tested it again nothing. when i start this with a normal minecraft version logs are saved and it creates a new latest.log

**Comment by pokeball99** [comment]
who says u can't edit your logs?

**Comment by Bluscream** [comment]
@paris-ci But when you dont have any log at all they also will be suspicious / ban you cause they think you deleted it.

**Comment by Alexander01998** [comment]
Fixed. It was the compiler not putting `log4j.xml` into the Jar.
