### ISSUE TITLE
x-ray doesn't work as it should am I doing something wrong or is it a bug

### ISSUE THREAD

**Issue by grossly** [Wurst-Imperium/Wurst-Client#1527]
Hey,

Is this a bug?

x-ray shows water, lava, leaves, tall grass, glass and other blocks that I haven't added to the x-ray block manager. I've seen other clients work where you can choose exactly what you want to see so, how can I get rid of this stuff and only show the things I want to see, if it is possible, please.

Example - Note: this is a picture using x-ray:
![untitled](https://cloud.githubusercontent.com/assets/13602988/9022871/526875b6-3854-11e5-8b5c-624de19f6da1.png)

Thank you.

**Comment by GummiBoat** [comment]
# *Duplicate: #211*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by mcccs** [comment]
are u on mac? xeay for mac doesnt worl

**Comment by grossly** [comment]
I'm using a  PC. Sorry if this is a duplicate, I didn't see it.

Thanks.

**Comment by grossly** [comment]
I'll close this, since I now see that it is a duplicate of duplicates.
