### ISSUE TITLE
Longjump

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1528]
Like highjump, but forward

**Comment by mcccs** [comment]
:+1:

**Comment by 1337HaxorKiddie** [comment]
I think thats not possible (NCP+ bypassed)

**Comment by 1337HaxorKiddie** [comment]
Probably, but then you can usw fly anyway because you are slow.

**Comment by ravenje** [comment]
@paris-ci no, its not possible to bypass this

**Comment by OMGchangeMYusername** [comment]
Literally no point of this, sorry.
I'd agree if it has a new form of bypass or anythin', but adding more flight-like mods won't help unless it has a different way of bypassing.

**Comment by 1337HaxorKiddie** [comment]
@OMGchangeMYusername +1

**Comment by Alexander01998** [comment]
Would be very hard to control. Try using Jetpack while sprinting, that does the same thing.
