### ISSUE TITLE
Are hacked clients legal?

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#153]
Are hacked clients legal?

**Comment by OMGchangeMYusername** [comment]
dude! please tell me you're kidding!

**Comment by Alexander01998** [comment]
Yes.

It's like cheating in chess: You violate the rules of the game, but that doesn't mean you violate the law.

**Comment by pokeball99** [comment]
u use mcp to make this client,but it say u can't do that,what about that?

**Comment by Alexander01998** [comment]
> u use mcp to make this client,but it say u can't do that,what about that?

It's basically the same concept: Violating their rules does not mean violating the law.
