### ISSUE TITLE
Block hunt mod

### ISSUE THREAD

**Issue by Zalcens** [Wurst-Imperium/Wurst-Client#1530]
Hello there, Wurst already got a prophuntESP, that works well, but many blockhunt servers also make the players to disquise as a mob, the prophuntESP does not detect those, so i would just ask if you guys at Wurst could try making this one possible :+1: would be pretty easy to win then, plus servers that enables mobdisquise, may this then work on those?

**Comment by GummiBoat** [comment]
Have you tried using MobESP?

**Comment by WurstContributor** [comment]
@GummiBoat You said you were retarded enough to remember 1529 issues right? Isn't this a dupe?

**Comment by Zalcens** [comment]
MobESP shows all mobs, not the UUID of ppl disquising as mobs

**Comment by GummiBoat** [comment]
# *Duplicate: #81*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

*My bad.*

**Comment by OMGchangeMYusername** [comment]
AND THAT IS THE MOMENT WHERE GUMMI SCREWED UP! YOU SHOULD RETIRE SOON!
No seriously what's the big deal if you forgot it?

**Comment by mcccs** [comment]
Fun Fact: I explored Prophunt Esp (Yea im not lieing
> I found something: Enabling Truesight draws small boxes under fake blocks.

**Comment by Bluscream** [comment]
Very easy to read :D

![lol](http://i.gyazo.com/f67be925fb784fc929883ba814283456.png)

**Comment by OMGchangeMYusername** [comment]
Meh.. It's obvious the guy will notice the search bar.. but the original is just better. (my typo-free version ;))
