### ISSUE TITLE
a console key?

### ISSUE THREAD

**Issue by ObamaBinLaden** [Wurst-Imperium/Wurst-Client#1531]
maybe like bind "~" console so when we open it u can type the command you want and it's maybe like with weepcraft it would help a lot ;D

**Comment by GummiBoat** [comment]
# *Duplicate: #1301*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by OMGchangeMYusername** [comment]
I don't think this is a duplicate, at all. First off that guy didn't even intend suggesting it to wurst, nor did he explain anything about it. (that issue is most likely "invalid")
It can't be a duplicate simply because "console/command line" is in title.
> you can toggle everything via Chat, so a command line (i guess you mean one like in the old Nodus versions) won't be really needed.

I do agree to this tho, was about to say same thing here but well you said it already~

**Comment by pokeball99** [comment]
nice work on the new dupe image @GummiBoat

**Comment by OMGchangeMYusername** [comment]
@pokeball99 go [here] (https://github.com/Wurst-Imperium/Wurst-Client/issues/1379).

**Comment by Bluscream** [comment]
@GummiBoat the Wurst logo in your new image looks like poop to me in that angle : :o:

**Comment by 1337HaxorKiddie** [comment]
I don´t think that a console is helpfull, that´s only a new useless feature. I think it would be more help full if we have it like this: 

![like this u know](https://cloud.githubusercontent.com/assets/11871421/9025432/78c5df54-3904-11e5-9796-4db366d79286.JPG)

**Comment by Huanjohn** [comment]
@1337HaxorKiddie However, if the console is in the chat bar, the amount characters would likely still be limited. Having a console separate from the chat bar could remove the character limit, and possibly even allow "§" (the formatting character) to be used in the console.

**Comment by 1337HaxorKiddie** [comment]
Anyway i like the Console in Chat more. Probably he add both of it.
