### ISSUE TITLE
Better AutoSteal

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1532]
Make it to where when you click on the chest, it steals all the stuff inside but then it also closes the chest right away. This would be even more efficient than pressing esc every time to close the chest because all you would have to do is right click the chest and move on.

**Comment by OMGchangeMYusername** [comment]
lol you don't have to press esc.. Press E instead.

**Comment by JackFishbaugh** [comment]
@OMGchangeMYusername lol xD.

**Comment by mcccs** [comment]
Maybe Dupe: #1000
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by PixelMaster3D** [comment]
Yeah. What you would also want to add is an item restriction on what to not grab like bowls or seeds.     (don't ask why, they had it in HG.)

**Comment by awakened-game** [comment]
i wouldn't recommend adding this, i mean, there are so many things that could go wrong...
1. you could be lagging and the server puts items back (thus happens to me a lot)
2. the server could also have some plugin that FORCES you to take them out slowly, one at a time. (again, a lot)
3. people seeing it will go: "woah he just opened and closed that so fast, and he took ALL the items! haaax! ban him! ban him! ban him! ban him! waaaaaah! :'(" .... for example, kids, you know.

i already have the first two problems, i wouldnt like a third.... unless you can configure a "close after this much time" option.... yeah do that.

**Comment by Alexander01998** [comment]
> 1. you could be lagging and the server puts items back (this happens to me a lot)
> 2. the server could also have some plugin that FORCES you to take them out slowly, one at a time. (again, a lot)

This is only happening to you because you are using AutoSteal on a NoCheat+ server without using YesCheat+. It's a very common mistake.

**Comment by JackFishbaugh** [comment]
@awakened-game alexander answered the first two, and in response to 3, kids will do that any way. its not a real issue.
