### ISSUE TITLE
Jesus breaks dropped items

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1535]
Enabled Jesus, and placed a Falling block. The GIF explains it

![crash 2](https://cloud.githubusercontent.com/assets/11584045/9026458/8fa8f182-3938-11e5-8b29-3a447fa28be1.gif)

**Comment by GummiBoat** [comment]
Please remove the 2nd gif.

**Comment by 1337HaxorKiddie** [comment]
@GummiBoat but the Remix was Awsome :(

**Comment by GummiBoat** [comment]
It wouldn't be awesome if you had epilepsy.

**Comment by 1337HaxorKiddie** [comment]
Yess... , thats right :/ but i havent got it :D

**Comment by mcccs** [comment]
1) scene size should be under 1/4
2) scene shouldn't contain red
3) you should watch it in small screen
4)~~it should be under 6 seconds~~ it's a gif, so unlimited
5) ~~You should be under 7 or over 19~~ Possiblity: 5%
6) https://en.wikipedia.org/wiki/Denn%C5%8D_Senshi_Porygon (i DID watch this episode)
7) i made a taco version
https://cloud.githubusercontent.com/assets/11584045/9033080/f357deca-39cc-11e5-9b76-ab60e398230e.gif

**Comment by Alexander01998** [comment]
I'm pretty sure that cannot be fixed, as Jesus works by making the water solid.
