### ISSUE TITLE
Fightbot is unstable

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1536]
1) fightbot selects an entity
2) fightbot goes to it
3) changes decision and goes to another entity.

Solution: Fightbot selects entity on update, My Idea is 
1) fightbot selects entity when enabled
2) fightbot goes to it
2.5) clicks once
3-1) entity dies 3-2) tests invicible
4) fightbot selects entity

**Comment by Bluscream** [comment]
But what should it do to invincible entities?

**Comment by haykam** [comment]
Test if it is invincible, like if it isn't a wither or enderdragon, and after 5-10 hits it changes.
