### ISSUE TITLE
Wurst

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1537]

**Comment by 1337HaxorKiddie** [comment]
And now?

**Comment by GummiBoat** [comment]
Please don't abuse the Issues section. This is not a forum.

Consider reading the [contributing guidelines](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) so it won't happen again.

**Comment by Bluscream** [comment]
If you want a chat where you can quickly get answers to your questions, use [this](https://gitter.im/Bluscream/Wurst-IRC).
