### ISSUE TITLE
Comamndblock viewer

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1538]
a mob that allows to see the commands in commandblock in survival mode

**Comment by Nitrogen-Dioxide** [comment]
There are so many things that only the server controls it :/ .

I think that you send a packet "Hey I'm opening a cmd block." and the server "asks him self": "Is he in creative and op?". If any of that is false, he will send "you can't open it".

**Comment by GummiBoat** [comment]
Exactly what @Nitrogen-Dioxide said. That's simply impossible.

**Comment by 1337HaxorKiddie** [comment]
Also not with viewing NBT tags?

**Comment by GummiBoat** [comment]
I don't know if the server gives so much information about the chunk, especially that block

**Comment by ravenje** [comment]
But the command is a nbt tag, like text on signs
why its impossible to read in survival?

**Comment by Bluscream** [comment]
[![WIR HABEN UNS VERIRRT «» Minecraft Varo 3 # 16 | HD](https://i.ytimg.com/vi/xKV5pzZHD7U/hqdefault.jpg)](https://www.youtube.com/watch?v=xKV5pzZHD7U "WIR HABEN UNS VERIRRT «» Minecraft Varo 3 # 16 | HD")

**Comment by Bluscream** [comment]
[![WIR HABEN UNS VERIRRT «» Minecraft Varo 3 # 16 | HD](https://i.ytimg.com/vi/xKV5pzZHD7U/hqdefault.jpg)](https://www.youtube.com/embed/xKV5pzZHD7U "WIR HABEN UNS VERIRRT «» Minecraft Varo 3 # 16 | HD")

**Comment by Bluscream** [comment]
What are you talking about?

**Comment by GlitchHead** [comment]
@Bluscream Ha your getting stalked.

**Comment by PixelMaster3D** [comment]
Actually you don't have to be op and in creative to read CMDs for it. But to change it, yes you need to be op and in creative for that to happen.

**Comment by Eyremba** [comment]
@GummiBoat It is not impossible. :)

And @Alexander01998: Here is the source code for that: http://hastebin.com/bikoqezeju.java

You can look at a command block and if you write ".getcmd" into the chat, you will get the command in the chat:

![2015-08-13 01_36_14-serenity b35](https://cloud.githubusercontent.com/assets/13738234/9239503/ae8c9708-415c-11e5-895b-58af493ab697.png)

**Comment by pokeball99** [comment]
remove pending confirmation?

**Comment by pokeball99** [comment]
and for #1857 #1833 #1823 #1802 #1797 #1791 #1422 #1394 #1237 #1182 and #135 as well, sorry for doing this all in one thread,dont want to open up a issue for this,and dont want to go though all the issues and "spam" that,don't have the time even right now

**Comment by Alexander01998** [comment]
> and for #1857 #1833 #1823 #1802 #1797 #1791 #1422 #1394 #1237 #1182 and #135 as well? sorry for doing this all in one thread,dont want to open up a issue for this,and dont want to go though all the issues and "spam" that,don't have the time even right now

Having both <kbd>accepted</kbd> and <kbd>pending confirmation</kbd> in one issue is valid.
Only <kbd>accepted</kbd> and <kbd>pending decision</kbd> would conflict.
