### ISSUE TITLE
Jesus hack bug

### ISSUE THREAD

**Issue by huoh** [Wurst-Imperium/Wurst-Client#154]
when i use jesus hack on server and then disconnect and reconnect on 3 blocks deep water i somehow spawn under the water.

**Comment by Alexander01998** [comment]
Quite honestly, I wouldn't worry myself about that.

**Comment by huoh** [comment]
its still quite brutal if you lets say have enchanted diamond fulls and multiaura on and you are eating/afk then loose connection and then you loose all your stuff. ;(
