### ISSUE TITLE
Enable Gitter Chat

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1540]
https://gitter.im/Wurst-Imperium/Wurst-Client

just like

https://gitter.im/Bluscream/Resilience-Client-Source

**Comment by pokeball99** [comment]
dupe of ...um @gummiboat,what was it again?

**Comment by pokeball99** [comment]
gitter could be our irc,idk how he could get it into the client,but it would work

**Comment by GummiBoat** [comment]
# *Duplicate: #89 , #447*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by Bluscream** [comment]
Since @Alexander01998 denied the orginal for no reason i do see a sense in avoiding spamming ppl's email accounts i made a Wurst-Chat [![Wurst Gitter Live Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Bluscream/Wurst-IRC?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
