### ISSUE TITLE
Not whitelisted Button

### ISSUE THREAD

**Issue by Bluscream** [Wurst-Imperium/Wurst-Client#1544]
Add Not whitelisted Button to Server Cleanup. (If thats possible)

**Comment by GummiBoat** [comment]
Nope, sadly we can't check in advance if a server is whitelisted or not

**Comment by Bluscream** [comment]
Of course. The client can "fake connect" and check if the server responds with a "Not whitelisted" msg.

**Comment by awakened-game** [comment]
hmm, not sure how that would work, considering you can change what the server sends as the whitelisted msg.

**Comment by kim-yannick** [comment]
This would also be cool to find cracked servers.
