### ISSUE TITLE
ItemSize command

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1546]
https://gist.github.com/pokeball99/171d615c740de69a0c79
modifies the stack size,idk if this code still works,or if this will get rejected by the .give nbt issue
but oh well

**Comment by Bluscream** [comment]
Its cool but alexander wont add it cause he doesn't add anything by now ...

**Comment by GummiBoat** [comment]
> cause he doesn't add anything by now
if you want faster releases, then contribute.


It should work, but the thing is... why do you need to increase the stacksize in creative mode? I don't know if you can pass them to another player, without changing the size back to 64...

**Comment by Alexander01998** [comment]
> why do you need to increase the stacksize in creative mode?

^
