### ISSUE TITLE
Chest stealer update

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#155]
Itsjerryand harry's server has an anti-chest steal plugin. I open the chest and the items appear with half second delay. Please create an algorithm like this:
I open the chest
It tries to steal everything
0.5 second delay
It tries to steal everything

And at some servers i press steal button, it tries to steal everything but it can only get 2 items.Please create an algorithm like this: 
I click the steal button
It tries to steal everything
If it cant steal everything 
It steals 2 items
delay 0.5 seconds
It steals 2 items
........

**Comment by Alexander01998** [comment]
Already implemented. Just enable YesCheat+.
