### ISSUE TITLE
SkyBase Finder/ESP 

### ISSUE THREAD

**Issue by Mw333u1** [Wurst-Imperium/Wurst-Client#1550]
It find skybases when the player loads chunks around him and loads the chest like chest esp but Chest esp doesnt Render in the skybases if you walk below them!!!!!!

**Comment by pokeball99** [comment]
so maybe have it detect for blocks above normal gen limit and then makes u looks up or something?

**Comment by Mw333u1** [comment]
Yeah or it pops a counter in the screen saying how many chest are in the
current chuncks around the players.


2015-08-02 20:15 GMT-06:00 pokeball99 <notifications@github.com>:
