### ISSUE TITLE
Head Lookdown

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1551]
The name seems weird so ill do my best to explain and a use for this... Have you ever seen a minecraft skin that has the face of a player is were there head would be on a normal skin? Look at the images they will explain most of it... Now i came up with a idea like the headless mod but instead of the head being down it will be looking down at all times and you can still look around like normal client side..
![2015-08-02_21 35 54](https://cloud.githubusercontent.com/assets/8052644/9029804/1682c3c4-395f-11e5-875c-2f841a40870d.png)
![2015-08-02_21 36 26](https://cloud.githubusercontent.com/assets/8052644/9029805/17a81e98-395f-11e5-8522-9983160dd13b.png)
Or if you could even make it so that were you look the top of your head will focus on that position.

**Comment by GummiBoat** [comment]
Oh my god this is hilarious... but isn't the `Tired` mod already doing this?

**Comment by GlitchHead** [comment]
well its moving the head up and down slowly i want this mod to make the head stay down.

**Comment by 1337HaxorKiddie** [comment]
It would be cool if we could change the position of the head with a simple command.
