### ISSUE TITLE
Weird speak

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1555]
So... It's like you say this: Hello. It will say: |-|3110

**Comment by pasi123567** [comment]
Or it says H3110

**Comment by OMGchangeMYusername** [comment]
We had the whole speak things in this issue #941

**Comment by mcccs** [comment]
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
