### ISSUE TITLE
Troube In Mineville

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#156]
Make a hack that lets you see all the traitors :100:  :) Would be so easy in hive.mc XD

**Comment by Alexander01998** [comment]
I've never played Trouble in Mineville or Trouble in Terrorist Town. Is there a way to detect the traitors?

**Comment by Loltage23** [comment]
No, But there could be a red box around them and btw play it before you add it in and it either says if ur a traitor a terrorist or a detective and whilst on the subject why not add in a hack that lets you be an automatic terrorist. :100:

**Comment by Alexander01998** [comment]
> No, But there could be a red box around them

If there is no way to detect them, then there is no way to make a hack that detects them.

> and whilst on the subject why not add in a hack that lets you be an automatic terrorist.

Hacking works with logic, not with magic.
