### ISSUE TITLE
PotionEffects

### ISSUE THREAD

**Issue by IIYaNkIeII** [Wurst-Imperium/Wurst-Client#159]
This will let u see what potion effect you have when you turn it on, if you add it could you make it show the effects in the top left corner of the sceen. Thanks

**Comment by Alexander01998** [comment]
I don't like having too much data on the screen. It's just distracting.

**Comment by OMGchangeMYusername** [comment]
Please add this mod,Its quite useful when thinking about it!
And you don't really have to make cover half of the screen!
It should be pretty simple,here's a good PotionHUD
[PotionHUD] (http://puu.sh/hb6EW/a351290db0.jpg) it should be really simple as that!
It should be optional too.
