### ISSUE TITLE
NoSlowdown

### ISSUE THREAD

**Issue by Xmeesho** [Wurst-Imperium/Wurst-Client#16]
When you eat or drink you don't get slowdown.
:grinning:

**Comment by Notchshero** [comment]
And When using bow.

**Comment by IIYaNkIeII** [comment]
Please add this to the client

**Comment by Alexander01998** [comment]
This one even blocks slowdown from water. :surfer:

**Comment by GlitchHead** [comment]
wait a sec does this mean under water walking?

**Comment by Alexander01998** [comment]
> wait a sec does this mean under water walking?

It should, yeah.

**Comment by OMGchangeMYusername** [comment]
but NoSlowDown underwater wouldn't be NCP bypassed no?.though,you can make another different one that works underwater too.

**Comment by Alexander01998** [comment]
> but NoSlowDown underwater wouldn't be NCP bypassed no?

Probably not. As far as I know, NoCheat+ has a maximum allowed speed for walking in water, just like it has a maximum speed for walking on soul sand and walking while using items.
