### ISSUE TITLE
Armor Status

### ISSUE THREAD

**Issue by IIYaNkIeII** [Wurst-Imperium/Wurst-Client#160]
This will show you you`re armor drability like when you press the E key and could you make it drag and drop also you could pin it to when you press esc key you could still see it.

**Comment by Alexander01998** [comment]
Most armor has so much durability that you don't need to care about it. So unless you're wearing gold armor, this would be a waste of screen space & performance.

**Comment by MyzticalTekkno** [comment]
you can just press F3 and H the same time and check your inventory to see the durability of many armors and swords and other stuff.
Check more commands that might be usefull for you :stuck_out_tongue: http://minecraft.gamepedia.com/Controls

**Comment by OMGchangeMYusername** [comment]
@MyzticalTekkno please tell me you're not serious.. you're in a pvp bruh and your armor might go down really fast, only opening your inventory might take your life..

**Comment by Bluscream** [comment]
I agree with this!
