### ISSUE TITLE
fapping mod

### ISSUE THREAD

**Issue by huoh** [Wurst-Imperium/Wurst-Client#161]
this mod would be quite awkward to use but it would look like steve was fapping xD

**Comment by Alexander01998** [comment]
Come on. :unamused:

**Comment by pokeball99** [comment]
U r so immature,but gave me a good laugh just thinking of a hack of this

**Comment by Nitrogen-Dioxide** [comment]
twerk is very possible xD

**Comment by pokeball99** [comment]
this needs the "not serious" label on it
