### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by Robert8298** [Wurst-Imperium/Wurst-Client#163]
When ever i launch Wurst it doesn't open, it just takes me to the Game Output tab for my player. Can someone help me?

**Comment by Alexander01998** [comment]
> Can someone help me?

Only if you tell us that game output.

**Comment by Robert8298** [comment]
I didn't get any output. It was a blank when I saw it.
it was blank. This glitch prevents me from using any version higher than
1.5.1

**Comment by Alexander01998** [comment]
> This glitch prevents me from using any version higher than 1.5.1

That's definitely caused by an outdated Java version. See #142 for more info.
