### ISSUE TITLE
BowAimbot Predictions

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1646]
Flare has a setting in BowAimbot that can predict where the target will go next making it MUCH more accurate. It is possible, but it would be a work in progress. I hope you consider it!

(Please don't be a dupe... I tried searching for similar issues.)

**Comment by mcccs** [comment]
Trajectories Makes him sick.
Time calculation will kill him.

**Comment by OMGchangeMYusername** [comment]
Nothing would hurt if he skidded thier prediction mod, it's quite useful tbh.

**Comment by mcccs** [comment]
Yeah i think we need a helper for this mod.
@Huanjohn Could you please help Alexander for implementing this mod?

**Comment by Alexander01998** [comment]
That should be pretty easy to do. Minecraft already provides the current position, last position and current momentum, which is more than enough to calculate the next position.

**Comment by JackFishbaugh** [comment]
YEEESSS

**Comment by Glowstone82** [comment]
Yeah. This is a great idea

**Comment by Edtlogin** [comment]
:+1: :facepunch:
