### ISSUE TITLE
A command similar to .enchant and .rename which adds item attributes or potion effects to potions

### ISSUE THREAD

**Issue by Yuval1999** [Wurst-Imperium/Wurst-Client#1649]
/

**Comment by OMGchangeMYusername** [comment]
duplicate #342, look up 705 too.

**Comment by Alexander01998** [comment]
# *Duplicate: #672*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
