### ISSUE TITLE
Invsee command (yes it is possible)

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#165]
Heres a invsee command that the hacked client Resilience have...
I tried to make it based on the source code but failed.
well.. heres a screenshot about the invsee command... it enables you to see something on a "target" hand and armor. it is VERY useful... never get scammed, since i can see the enchants/ammount/name/iten-damage wehn buying something. i will leave a screenshot.
Sadly Krisp_dev stoped coding resilience months ago. and i got this version months ago too.
Almost anyone have this version of resilience. Anyone know that it is possible "invsee"
If you want the .jar, contact me on nitrogen.dioxide99@gmail.com (only for the wurst developer)

the invsee command screenshot http://postimg.org/image/b4m3wry6h/

**Comment by Alexander01998** [comment]
:heavy_check_mark:

**Comment by Krowit** [comment]
Maby it's possible to have the potion effects shown too, that would round the thing up :P

**Comment by Alexander01998** [comment]
> Maby it's possible to have the potion effects shown too, that would round the thing up :P

It shows you everything it would show in the normal inventory screen provided that it has the required data. So if it knows the potion effects of the other player, it will show them too.

You can try that out with Resilience's Invsee. If it shows you the potion effects, the Invsee in Wurst will do that as well.

**Comment by GlitchHead** [comment]
Omfg epic

**Comment by Nitrogen-Dioxide** [comment]
The invsee of resilience does not show the potion effects. Idk but i think it is possible to make that too, because if a player send a packet "i have sharpness I" he will send "i have strenght II" too.

**Comment by Alexander01998** [comment]
> The invsee of resilience does not show the potion effects. Idk but i think it is possible to make that too, because if a player send a packet "i have sharpness I" he will send "i have strenght II" too.

As I said earlier, it shows everything it would show in the normal inventory screen if it has the data. So if it doesn't show the potion effects, then it doesn't have that data.

**Comment by Alexander01998** [comment]
> The invsee of resilience does not show the potion effects.

Just tested. It **does** show the potion effects.

![](https://cloud.githubusercontent.com/assets/10100202/6548148/c98f8134-c5ef-11e4-80d2-ecffd0547fe1.png)
