### ISSUE TITLE
.give any block (probably will work only in creative mode.

### ISSUE THREAD

**Issue by Yuval1999** [Wurst-Imperium/Wurst-Client#1650]
if its possible to give a player a command block if hes in creative why not make it for any block?

**Comment by OMGchangeMYusername** [comment]
because you can get that without even using a hacked client.

**Comment by Alexander01998** [comment]
# *Duplicate: #342*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
