### ISSUE TITLE
.addsessionid command

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#1653]
I would like to have a command in wurst that adds sessionid's with names to a list and if there is a newer sessionid for a player you added to a list Wurst will refresh the list and put the newer ids in and remove the older ones. This feature would be useful if wurst is going to have an sessionid stealer.

**Comment by Creeperman8362** [comment]
except that sessionids are pretty much useless after 24hours, or atleast the ones i find on pastebin.

**Comment by GummiBoat** [comment]
@Creeperman8362 You need the complete Session Token, which is "SessionID:UUID" (or the other way around, I don't remember that currently). The Token doesn't run out, until the person logs out of the minecraft client manually. (The little button in the start screen)

**Comment by Creeperman8362** [comment]
most ppl logout after 24 hours, and sometimes my thing says "Invalid session" connecting to servers when i havent logged out at all. go on pastebin and search for sessionids and try some that are 1-2 days old. and then try to use them.

**Comment by GummiBoat** [comment]
@Creeperman8362 I used one, that was over 1 month old. Session ID's don't run out that easily.

**Comment by Creeperman8362** [comment]
then why do all the pastebin ones dont work after 1 day?

**Comment by Grievus** [comment]
It is just a question. What do I have to type in google to search for good sessionids on pastebin?

**Comment by Grievus** [comment]
how can I find sessionids with names on google?

**Comment by Glowstone82** [comment]
This will be useful for people with cracked Minecraft or people who get banned from servers for hacking or wutever. WE NEED THIS

**Comment by Eyremba** [comment]
@Creeperman8362 for me, the pastebin ones worked but you must search on pastebin for new session IDs.
