### ISSUE TITLE
Invisibility Potion Bypass

### ISSUE THREAD

**Issue by HeartOfShrapnel** [Wurst-Imperium/Wurst-Client#1656]
For creative servers with invisible potions disabled, a potion that is just a water splash but with a "side effect" of invisibility forever. Pretty much the TrollPotion with just invisibility. I would find it useful for trolling, etc on creative servers.

**Comment by ravenje** [comment]
plese with hiden particles :D

**Comment by labcraft59** [comment]
Yes!

**Comment by PixelMaster3D** [comment]
Agree to move forward with this plan but when I use the potion they don't show effects or apply them to me.
