### ISSUE TITLE
.priority (PvP)

### ISSUE THREAD

**Issue by HeartOfShrapnel** [Wurst-Imperium/Wurst-Client#1657]
Makes killaura/legit/multi only target a specific mob or player. Far easier than friending everyone nearby. 
possible other names;
.target (name)
.only (name)

**Comment by Alexander01998** [comment]
# *Duplicate: #112*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
