### ISSUE TITLE
ProphuntESP Showing Animals

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1659]
Many servers with prophunt also let you change into animals, but ProphuntESP doesn't show them. If there is a way make it work it would be great.

**Comment by WurstContributor** [comment]
Not possible + Dupe

**Comment by Alexander01998** [comment]
# *Duplicate: #81*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
