### ISSUE TITLE
Timer speeds below 0.1

### ISSUE THREAD

**Issue by TheIonosphere** [Wurst-Imperium/Wurst-Client#1661]
As Nocheat+ does not block timer speeds below 1, having some speeds significantly slower than 0.1 available on the slider could allow you to effectively freeze your motion and remain stationary in mid-air.
This would be useful as a panic command when falling.

**Comment by HeartOfShrapnel** [comment]
Then how would you turn it back up? Doesn't the timer affect the GUI speeds, too?

**Comment by Alexander01998** [comment]
> Then how would you turn it back up? Doesn't the timer affect the GUI speeds, too?

Yes it does. Setting the Timer speed to 0 would freeze your client completely.

**Comment by TheIonosphere** [comment]
To clarify, I meant something like 0.01. Slow enough to place a bucket of water, but not enough to make it impossible to turn off.

**Comment by TheIonosphere** [comment]
While I see now that a timer speed of 0 is not possible, a speed of 0.01 or even 0.001 could still be very useful. For example a person falling in mid air could enable timer at that speed, use the /home command and not have it cancelled due to movement as they have not moved far enough.
