### ISSUE TITLE
Midas Touch (More like air walking)

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1662]
This is an idea I got from InstantBunker. With instant bunker, you can instantly add an entire structure around you, even in survival mode. You can also add a keybind to this which makes the bunker even more instant. With this idea of instantly placing blocks, even in the air, I thought of the idea to use a stack of blocks to make a bridge in the air by just walking forward, backwards, left, or right. How it would work is that you turn on the mod (lets just call it MidasTouch for now), and then just walk around or jump. if you walked off an edge, a block would automatically be placed in front of you so you wouldn't fall. If you jump, a block would be placed under you so that your elevation would not decrease. You would be able to simply walk off a giant mountain because you are making a bridge as you go!

This could be pulled off by reading when you are on the the very edge of a block. On whatever edge you are on of that block, the MidasTouch would come alive and create the automatic bridge under your feet. So for example, if you moved to the very edge of the left side this block, the MidasTouch block would be added next to the left of that block, instantly.

The only problem I could see happening with this is not being able to descend. I'm sure we'll think of something. Like maybe shifting to the edge of a block would tell MidasTouch to make a one block descent. It could be anything.

**Comment by OMGchangeMYusername** [comment]
Dupe #781?

**Comment by JackFishbaugh** [comment]
no i dont think so... that one is just putting a block under you. this one automatically places it in front of you when you walk.

**Comment by OMGchangeMYusername** [comment]
Seen some clients with it, two names for now. ScaffoldWalk and MagicCarpet.
About the mod itself, I think it's SO GOOD and we need it.

**Comment by JackFishbaugh** [comment]
Ok cool! I have honestly never seen it... I thought I was being original :(. Oh well. I hope its added!

**Comment by Alexander01998** [comment]
# *Duplicate: #781*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
