### ISSUE TITLE
Get Player Heads In Creative Servers And Coloured Text Generator

### ISSUE THREAD

**Issue by GrassBlock** [Wurst-Imperium/Wurst-Client#1666]
Getting Player Heads In Creative Servers Would Be Fun! And It Will Be More Better With Coloured Text. Example: You Can Rename Things In The Anvil With Coloured Text. And Heads Can Be Get By The .head <playername> Command.

**Comment by GummiBoat** [comment]
You already can rename items with the `.rename` command. Color codes are supported, you have to use $ instead of § and $$ if you want to type a $.

And for the head:
# *Duplicate: #1186*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by OMGchangeMYusername** [comment]
Why did you do this ? :(

**Comment by GlitchHead** [comment]
The .give command could do this anyways....

**Comment by OMGchangeMYusername** [comment]
I was typing my reply but suddenly Gummi's reply popped up >_<
