### ISSUE TITLE
Flight does not work with jumping boosts

### ISSUE THREAD

**Issue by TheIonosphere** [Wurst-Imperium/Wurst-Client#1667]
When under the effect of Jump Boost (I or II) with Yescheat+ enabled on a server with Nocheat+, flight does not work and you are sent back to where you started.

I think the solution might be to have wurst detect these effects and adjust the height it sends you up initially to compensate for the increased jump distance.

**Comment by GummiBoat** [comment]
You shouldn't be affected by jump boost... as soon as you see, that you're getting teleported into the air slightly, just start walking before you touch the block below you again. I know, it's a bit difficult to pull off for the first time, but you'll get used to it.

**Comment by cleveravi** [comment]
how to you add a bug label?

**Comment by GummiBoat** [comment]
Oh, and please try making a video or gif, how it happens and what you have activated, because I just can't reproduce it...

![flight](https://cloud.githubusercontent.com/assets/10976441/9103293/b74fcfa0-3bfc-11e5-90bf-4318d3ffd611.gif)

**Comment by TheIonosphere** [comment]
Would being in creative mode affect whether NoCheat+ blocks you from doing it in that .gif? In creative mode the plugin would not prevent somebody from flying, and I experienced the bug in survival mode.
The mod bypasses it whenever the jump boost effect is not applied for me.

**Comment by GummiBoat** [comment]
Still can't reproduce it.

![Fly_Jump_boost](https://cloud.githubusercontent.com/assets/10976441/9115975/28697de8-3c62-11e5-9b46-6a6bfb80833a.gif)
