### ISSUE TITLE
Stuck in Report bug screen

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1669]
When ever wurst encounters a problem wurst has encountered a bug screen thing when ever i try to exit the screen it just pops up again instantly or nothing happens and im stuck in the screen. i know that the client is not frozen because i see chat moving and players moving around in the backround.

**Comment by PixelMaster3D** [comment]
Can you show a picture of what it looks like?

**Comment by Alexander01998** [comment]
This is caused by an error that cannot be fixed by disabling the mod that caused it. So the same error occurs again on the next update.

**Comment by 1337HaxorKiddie** [comment]
That means that the Screen pops every tick again up?
