### ISSUE TITLE
item receipes mod

### ISSUE THREAD

**Issue by huoh** [Wurst-Imperium/Wurst-Client#167]
since there are no mods like this one in 1.8 i considered giving you this idea
when you have a crafted item for example diamond armours, you could press lets say insert key when holding the item to see the crafting receipe.

**Comment by Alexander01998** [comment]
> since there are no mods like this one in 1.8

CraftBook, Not Enough Items, Too Many Items, ...

Also, once you start using hack clients, you have played the game long enough to know all the recipes by heart.

**Comment by huoh** [comment]
thats true but still
