### ISSUE TITLE
Hide GUI(s)

### ISSUE THREAD

**Issue by CanDoCool** [Wurst-Imperium/Wurst-Client#1670]
Would it be possible for you to implement a command, perhaps ".hide", which will allow a player to hide the GUI(s) and HUD, it will also block (with your new 'system') mods that are visible or change visual aspects through the client's interface. This will cover the whole "Render" tab.

Also, would it be possible to make to disable all wurst commands other than ".show" in order for the player to re-enable the GUI(s).

Thanks and good luck <3

**Comment by GlitchHead** [comment]
Duplicate #19
