### ISSUE TITLE
NoMineFall - Avoid dying in a dumb way

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1671]
This, when active would hightlight the block under the player if there is a pit underneath (with an optional threshold, or if there is enough fall space to die, or if there is void) and optionally prevent / slow down mining.

**Comment by labcraft59** [comment]
Isn't that cave finder? I'm not sure...

**Comment by GummiBoat** [comment]
CaveFinder just shows you where caves are, it doesn't prevent you from falling down edges automatically.

**Comment by TheIonosphere** [comment]
It would be difficult to classify what counts as a pit and what is intentional. For example you might have a large fall with water at the bottom. The closest thing which could be realistically implemented would be a safewalk mod, combined with use of the already existing CaveFinder.

**Comment by davidkoplik** [comment]
What? Use X-Ray man! Safewalk would be more usable than this!

**Comment by PixelMaster3D** [comment]
That would. All you have to do is shade the blocks a little.

**Comment by OMGchangeMYusername** [comment]
@davidkoplik X-Ray is totally the wrong choice at this point, unless we get X-Ray opacity.
