### ISSUE TITLE
Command concatenation

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1672]
How do scripting work? Can I concatenate commands in keybinds panel?

**Comment by GlitchHead** [comment]
yes you can just create a WSPAM script and add as many commands as you want and save it then in the key bind menu make a keybinds command .spammer spam (script name)

**Comment by beppe9000** [comment]
thanks

**Comment by OMGchangeMYusername** [comment]
Duplicate #422 
Please search old issues next time.
