### ISSUE TITLE
Anybody know of a completely "Hackers allowed" server?

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1676]
Well, do ya?

**Comment by PixelMaster3D** [comment]
Yes, some sky wars server

**Comment by GlitchHead** [comment]
This is not a forum.

**Comment by PixelMaster3D** [comment]
True, but it's a suggestion form

**Comment by PixelMaster3D** [comment]
I'm suggesting something

**Comment by GlitchHead** [comment]
This is a "suggestion" forum but for new features to be added to the client this does not have anything to do with this client.

**Comment by PixelMaster3D** [comment]
Well read my suggestions

**Comment by pokeball99** [comment]
2b2t.org has no rules at all,so hack away,there is ncp on there though,but again....
>This is not a forum

**Comment by labcraft59** [comment]
Umm... thanks!
