### ISSUE TITLE
INV. See (Player Edition) Improvement

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1677]
Able to see what players have. How this works is items will show over people heads for what they have. For that to happen is to have a scanner scan the players range or your range when you come near them. When a player picks up the items the scanner scans and stores for later reference. Once the player(s) die the inv data will reset. But for some servers the keep inv. Is on so there should be options and a seperate data to remeber these setting when joining a server like joining mineplex for instance it will recall that setting from that data list.

EDITED: Also there should be a cmd and be able open a player inv from far locations on a GUI chest format. I also hope in the future that you can steal player items as well but seeing it.

**Comment by labcraft59** [comment]
Yes, and it would also be awesome if you could steal the items in the inventory / chest too!

**Comment by PixelMaster3D** [comment]
Yes, it be also cool to show you what armor they have,too!

**Comment by PixelMaster3D** [comment]
Ops.

**Comment by OMGchangeMYusername** [comment]
> Able to see what players have and what are in chest.

We already have `invsee` command, it only shows the armor and the item he's holding tho.
A history log might be a good idea, to show what he held during the last three or five minutes is a nice.
I believe the chest thing is not possible, #1199.

But you suggested more than one feature in one issue, this is invalid.
Please read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository. 
#### "Always search your Issue before opening a new one. Creating duplicates is slower for everyone!"

**Comment by PixelMaster3D** [comment]
True yes I say more but it's all in one section of seeing inv. for that is a lot ask. If you seen an Inv. see plugin then you should look closely on how they sourced before being comped. if I have to make a separate issue for the chest then I will.

**Comment by PixelMaster3D** [comment]
And , yes I know, that I made a duplicate by accident from iPhone so this isn't easy for a small phone.

**Comment by OMGchangeMYusername** [comment]
Wow this is so messed up.
