### ISSUE TITLE
FireBlock

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1678]
When you turn on the mod, and use flint and steel, a line of fire appears one block behind you. This is used to escape people chasing you by making a huge trace of fire behind you. If you spam the flint and steel, you can make several walls of fire making it even more effective.

The length of the wall of fire needs to be adjustable!

I would say this is better than putting a wall of blocks behind you because those aren't deadly and if they are like dirt, would be easy to get past. Also, flint and steel lasts a long time.

**Comment by PixelMaster3D** [comment]
Good idea but that would be similar to placing down many entity since therefore it will be blocked

**Comment by OMGchangeMYusername** [comment]
Duplicate #805.
Search old issues please! read [this article] (https://help.github.com/articles/searching-issues) to learn how to easily find what you want.

**Comment by 1337HaxorKiddie** [comment]
I think NCP+ will block this.

**Comment by Alexander01998** [comment]
> Also, flint and steel lasts a long time.

No, it doesn't. And that's the problem with this idea. It would probably work for a couple of seconds, but then the flint and steel would break.
