### ISSUE TITLE
Trajectories

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#168]
you should add a mod that shows where will the arrows land,quick example in the pic.
![2015-03-08_19 40 15](https://cloud.githubusercontent.com/assets/10786571/6546612/84a1df00-c5cb-11e4-9d95-3002b708061f.png)

**Comment by Alexander01998** [comment]
I have no idea how the algorithm for that works.

**Comment by Nitrogen-Dioxide** [comment]
it is a HUGE algorithm, a lot of clients use this same algorithm.

http://pastebin.com/rSUDnrC0

**Comment by OMGchangeMYusername** [comment]
well it's already implemented in a lot of hacked clients before!
wurst should have it!

**Comment by Notchshero** [comment]
Will you add it?

**Comment by Krowit** [comment]
this would be cool if it'll work with enderpearls too :D

**Comment by Alexander01998** [comment]
> it is a HUGE algorithm...
> 
> http://pastebin.com/rSUDnrC0

Thanks.

**Comment by pokeball99** [comment]
@Alexander01998  whats keeping the Trajectories branch from being merge?it looks like its complete

**Comment by Alexander01998** [comment]
It doesn't draw the line correctly. Sometimes the line goes much further than the arrow and sometimes the arrow goes much further than the line.

**Comment by Spassvogelw** [comment]
if it is only sometimes, I would be glad if you can implent it in the WIPs.

**Comment by pokeball99** [comment]
@Spassvogelw,not possible,he removed the WIP class,and anything he doesn't get done just sits in the branch

**Comment by WurstContributer** [comment]
10 times...

**Comment by Meylama** [comment]
@Alexander01998 Here is another Trajectories source code for you: http://hastebin.com/ayotuziyuz.avrasm
