### ISSUE TITLE
Logo.

### ISSUE THREAD

**Issue by jjws600** [Wurst-Imperium/Wurst-Client#1682]
I believe there should be an option to remove the wurst logo from the screen, so that it is not in the way, and / or so people cant see it.

**Comment by mcccs** [comment]
Duplicate: #19
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by jjws600** [comment]
You haven't done it, just add a hotkey, all i'm asking.

**Comment by TekkitCommando** [comment]
We ain't gonna do it

**Comment by mcccs** [comment]
f1 f3
