### ISSUE TITLE
Regen doesn't react on Extra Hearts

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1684]
Title says all ^^^

**Comment by Alexander01998** [comment]
I'm pretty sure extra hearts cannot be regenerated.

**Comment by PixelMaster3D** [comment]
It really doesn't work. I tried.

**Comment by OMGchangeMYusername** [comment]
Well he said it's supposed to not work..

**Comment by PixelMaster3D** [comment]
OK. Just making sure. :)

**Comment by PixelMaster3D** [comment]
I was seeing that Nodus does regen on extra hearts and I thought that you had that too.

**Comment by WurstContributor** [comment]
@Alexander01998 Timer reacts to Extra Hearts. So is it possible to timer one certain thing?

**Comment by PixelMaster3D** [comment]
That could work.

**Comment by GummiBoat** [comment]
@Alexander01998 There are two versions of extra hearts.

minecraft:absorption (the yellow ones, that golden apples give you), won't be regenerated, but
minecraft:health_boost are temporary red ones, that also regenerate, but are not affected by Regen.

**Comment by PixelMaster3D** [comment]
And what side are you on? It works or doesn't work.

**Comment by GummiBoat** [comment]
> but are not affected by Regen.

Since Regen has a condition, that your health can't be higher than 20, we'd need to check if the player has the potion affect health boost, then check the potion level and then apply the regen effect accordingly to that.

So, it could be implemented, but as I said, it can't be obtained that easily anyways...

**Comment by PixelMaster3D** [comment]
I'll check for bypass for that.
