### ISSUE TITLE
Player and Mob Radar

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1685]
Track players movements and see how far away they are. And also track mobs too.

https://m.youtube.com/watch?v=69HrnvV4sSM

**Comment by OMGchangeMYusername** [comment]
Duplicate #303, when will you actually look for old similar issues?

**Comment by PixelMaster3D** [comment]
Yes, but I'm trying to convince why want this added to the client. This would be a very great layout and would also track movement. The previous one were rejected. This would probably be great enhancement for if there were moving blocks to look at.

**Comment by OMGchangeMYusername** [comment]
He already accepted a minimap (not made yet), so a radar isn't really necessary.

**Comment by PixelMaster3D** [comment]
Well then this would be a great example of what to start on.

**Comment by PixelMaster3D** [comment]
I could get part of the source to make this.

**Comment by OMGchangeMYusername** [comment]
I can get the whole source, but it's not about the source. He just rejected it.

**Comment by PixelMaster3D** [comment]
This would put in contribute of moving entity and with color this would show what's moving in area of region. Once that happens this could help with, including but limited to, Block Hunt, HG, ect.

**Comment by PixelMaster3D** [comment]
As you said:

"He already accepted it"

Now you say:

"He rejected it."

What that supposed to mean?

**Comment by OMGchangeMYusername** [comment]
Where exactly did i say "He accepted it", and where exactly did i say "He rejected it"?

**Comment by PixelMaster3D** [comment]
OMGchangeMYusername commented 29 minutes ago
He already accepted minimap (not made yet), so a radar isn't really necessary.

**Comment by PixelMaster3D** [comment]
OMGchangeMYusername commented 23 minutes ago
I can get the whole source, but it's not about the source. He just rejected it.

**Comment by OMGchangeMYusername** [comment]
These are seperate comments, the first one was about the minimap, but the second one was about the radar.
> I could get part of the source to make this.

I was assuming you're talking about the radar source, which is more likely because this issue is about radar..

**Comment by PixelMaster3D** [comment]
Yes but I was focusing on the map too. But whatever works.

**Comment by Alexander01998** [comment]
> Yes, but I'm trying to convince why want this added to the client.

GitHub doesn't work this way. If you create duplicates on purpose, you're not going to convince anyone. You're just spamming. And if you continue to spam, you will get banned for it.

**Comment by PixelMaster3D** [comment]
I don't look for duplicates, I make an issue whenever it Comes in my head. Sorry for helping.

**Comment by OMGchangeMYusername** [comment]
You'll basically get banned if you purposely continue doing this, you *must* look for older issues before opening yours.

**Comment by PixelMaster3D** [comment]
Very dumb reason to get ban. But this iPhone 3G isn't capable of the updated browser now.

**Comment by OMGchangeMYusername** [comment]
Well you're being annoying while *knowing* you are, I'd honestly ban you if you actually did it.
Take some time to look for old issues, that'll help if you're willing to help in the first place.

**Comment by PixelMaster3D** [comment]
Ism now on a friends comp.
