### ISSUE TITLE
Ignore/Hide entity cmd/mod

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#1686]
My idea is something that works like middle click friends, but makes any combat mod ignore a entity.

So, you keybind a key to a .ignore command, then, when you click that key facing an entity (any entity, not only players), it will ignore that entity until you do that again.

Desc of the cmd/mod:

Makes combat mods ignore a entity by facing then and running this command.

I think this will fix a lot of things, (anti killaura mods; armor stands; dead "bed" players).

**Comment by PixelMaster3D** [comment]
That will actually work. But what bothers me is running around clicking the players after finding them "resting"  is lot of clicking to do.
