### ISSUE TITLE
Ghost Hack

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1687]
Could it be possible to have a hack to always relive again?

https://m.youtube.com/watch?v=I-FiVpKZFPc

**Comment by GummiBoat** [comment]
The video is from 03/2014. This was patched a long time ago. We have something similar (Invisibility), which sadly only works for vanilla servers.

**Comment by PixelMaster3D** [comment]
But I think this is different. This uses a auto respawn that ,from the looks of it, it fools it by making it think he respawned from where he was and was sent to the "correct" spawn from fake data. That or was somehow disabled.

•Just an estimation•

**Comment by Alexander01998** [comment]
> But I think this is different. This uses a auto respawn

That's the same thing that Invisibility uses. It's probably the exact same mod, with the only difference being that it is now patched on Bukkit servers.
