### ISSUE TITLE
Book Hack 

### ISSUE THREAD

**Issue by EnderTheEpicMC** [Wurst-Imperium/Wurst-Client#1689]
U should add a Book Hack where we type a URL but when u sign the book there is a command key space and u type what command give book to an Admin and Boom ur command worked. Thank you

**Comment by OMGchangeMYusername** [comment]
It's already implemented.

**Comment by mcccs** [comment]
Duplicate: https://github.com/Wurst-Imperium/Wurst-Client/releases/tag/v1.13
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by OMGchangeMYusername** [comment]
@mcccs That's not a duplicate.. issues like this are "already implemented".
And there are no duplicates of releases anyway..
