### ISSUE TITLE
Weird Charcters

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#169]
Wurst shows weird distorted charcters instead of mod names on mod menu

**Comment by scriptinator** [comment]
![2015-03-08_11 42 17](https://cloud.githubusercontent.com/assets/6655672/6547039/3cc60f6e-c588-11e4-9eb1-7242d7135a84.png)

**Comment by Alexander01998** [comment]
That was fixed in [Wurst v1.6](https://github.com/Wurst-Imperium/Wurst-Client/releases/tag/v1.6).
