### ISSUE TITLE
.goto Update

### ISSUE THREAD

**Issue by LukasE7x7** [Wurst-Imperium/Wurst-Client#1690]
It would be awesome if .goto could do Jump'nRuns!
At the moment, a problem is: Goto sees that there is a way where it must jump, but it does not jump. It goes to the block it must jump on, but it jumps not on it.

It would not be easy to let it do hard jumps too, but if Goto could be used as Jump'nRun Bot..., that would be great!

And I did not find a way to turn Goto off. If Goto failed, I found no way to stop it.

**Comment by mcccs** [comment]
#110
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
