### ISSUE TITLE
WorldStealer

### ISSUE THREAD

**Issue by LukasE7x7** [Wurst-Imperium/Wurst-Client#1691]
I don't know if this possible, but I have an idea.
"WorldStealer" or ".stealworld <worldname>" could save the loaded piece of the world you are standing in in a singleplayer world, or something else to save structures.

**Comment by mcccs** [comment]
#67
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by EnderGamer21** [comment]
its useful the mods so useful to crete ur own servers to play with ur friend in minecraft realms
