### ISSUE TITLE
Go to paralyzed me and won't turn off even after I reached the destination

### ISSUE THREAD

**Issue by Vengance666** [Wurst-Imperium/Wurst-Client#1692]
I was looking through some commands and found this, so I tried it out and I got paralyzed up against a wall trying to get to the coords. I went on to a different world and went to the coords, but I still can't move at all!

**Comment by Vengance666** [comment]
Idk what to do

**Comment by Vengance666** [comment]
Some one pls respond I literally can't do anything because of this! Is there a command that will turn it off? Do I have to re-install Wurst? What do I do?!

**Comment by 1337HaxorKiddie** [comment]
Restart the Game should work.

**Comment by GummiBoat** [comment]
# *Duplicate: #834*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
