### ISSUE TITLE
Anti Hunger

### ISSUE THREAD

**Issue by nicolay0001** [Wurst-Imperium/Wurst-Client#1694]
plz make a mod/hack that makes you never go hungry

**Comment by nicolay0001** [comment]
Plz make a antiban hack (cant be banned from servers)

**Comment by OMGchangeMYusername** [comment]
AntiHunger is technically impossible, but Flare has a feature "AntiHunger" which fights hunger a little bit.
not completely preventing it tho. 
antiban hack is impossible, you must have another account or an alt and change your IP if it was IP ban.

Please don't suggest more than one feature in one issue, and look for old issues just in case.
The [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) basically tells you what to do, please read it.
