### ISSUE TITLE
About .say

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1696]
.say doesn't work good
Why?
if someone says type in the chat bar 100 dots, it is impossible:
I can type maximum 100 characters.
.say(space) .....
In wurst i can type
.say(space) 95 characters!!!
I cant type 100 characters!

**Comment by GlitchHead** [comment]
Sid someone actually ask you to type 100 dots?

**Comment by mcccs** [comment]
No.

**Comment by GummiBoat** [comment]
Use WSPAM, if you really need the 5 extra characters.

**Comment by OMGchangeMYusername** [comment]
Lol this is so meaningless, who would tell you to type 100 dots?

**Comment by solidshadow96** [comment]
because to check if your a hacker or not with the .say command it takes up 5 slots therefor the player that hacks can only type 95 . while non hackers dont type .say allowing them to type the full 100 slots. man thats actually smart i might start using that

**Comment by OMGchangeMYusername** [comment]
Isn't that a little suspicious?

**Comment by GummiBoat** [comment]
Which admin counts 100 dots every time a new player joins again, just to check if they are not using any hack clients?

And again, just use WSPAM.

**Comment by OMGchangeMYusername** [comment]
Yeah pretty much.

**Comment by solidshadow96** [comment]
very true

**Comment by Eyremba** [comment]
"Which admin counts 100 dots every time a new player joins again, just to check if they are not using any hack clients?"
@GummiBoat: There are plugins for that xD on spigot forums you can also find a plugin which bans every player if he does not write ".legit" into the chat xD

**Comment by GummiBoat** [comment]
@Eyremba Well, then... again. set up a WSPAM script for that you could even utilize the repeat tag. And for the .legit we have .say.

**Comment by Eyremba** [comment]
for those which are to lazy: http://pastebin.com/hHmMabmf :D

**Comment by GummiBoat** [comment]
@Eyremba
> utilize the repeat tag

I know I'm retarded. And yup, the plugin is faster than the chat messages. That's because its getting the messages first, then your client will get them back.
![dottester](https://cloud.githubusercontent.com/assets/10976441/9264588/57b75b94-4228-11e5-9d87-e10bdcd564f5.gif)

WSPAM-"Script" used: `.say <repeat 100>.`

**Comment by Eyremba** [comment]
lol can you send me the download link to this plugin so that I can test it myself? I don't find it on google xD

**Comment by GummiBoat** [comment]
This is only testing for 100 dots though. Nothing else. [Download](https://mega.co.nz/#!wplhkYzQ!9c1ObJGA0lzI7bcWmG2ppgvRIMce7Y_FANwQc7tPmRQ) I compiled it on CraftBukkit, I don't know if it's working on Spigot.

**Comment by Eyremba** [comment]
Thanks. :D I also found this: http://dev.bukkit.org/bukkit-plugins/dotlegit/

You must write ".say .legit" into the chat, but this noobs forget about ".say .say .legit" xD
