### ISSUE TITLE
AutoAmor ForceField

### ISSUE THREAD

**Issue by vitormendes45645** [Wurst-Imperium/Wurst-Client#1697]
why do not you put the hack ForceField hitting while defends  and the AutoArmor another armor boot time, if the equipped armor break, I'm Brazilian so if my English is bad and google translator's fault
Sorry

**Comment by mcccs** [comment]
invalid:
you can't put 2 suggestions in an issue

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by vitormendes45645** [comment]
então porque falaro que era nessa porra que dava sugestões ??

**Comment by vitormendes45645** [comment]
so why falaro it was in this motherfucker that gave suggestions ??

**Comment by vitormendes45645** [comment]
fuck if I can not for 2 tips

2015-08-09 7:52 GMT-03:00 Alexander01998 <notifications@github.com>:

**Comment by vitormendes45645** [comment]
and I am not English asshole

2015-08-31 21:20 GMT-03:00 Vitor Mendes <vitormendes716@gmail.com>:

**Comment by Eyremba** [comment]
@Alexander01998 please remove this annoying kid which can not watch his language from the repository

**Comment by PixelMaster3D** [comment]
Lets remind ourselves this person is Brazilian. What she is trying to say is... Why not have it where that when the armor breaks, it will replace it with another armor in your inventory. Automatically. Without trying to put it in there or using the auto-armor.
