### ISSUE TITLE
Scroll for hacks

### ISSUE THREAD

**Issue by Wymii** [Wurst-Imperium/Wurst-Client#1698]
Hey guys its not really an issues its just something to help people with smaller screens.... Could you please instal a scroll bar so we can see all the hacks... and as a request from one of my fellow users could you please install a G-Mode mod... Please and Thank you :)

**Comment by EnderGamer21** [comment]
God Mode is impossible

**Comment by 1337HaxorKiddie** [comment]
Regen is like Godmode.

**Comment by EnderGamer21** [comment]
u can go into wurst source code and expirment and try to find a way for godmode but i dont think thers a way

**Comment by Wymii** [comment]
Where would i find the source code??.... Im a newbie when it comes to coding and things.... My main reason for this post was in fact the Scroll bar to see all the mods on a to smaller screen... as im running a 32 inch screen and i cant see all the options.

**Comment by Wymii** [comment]
For instance the "Target" option opens outside of the screen :/

**Comment by EnderGamer21** [comment]
press f1 when ur in minecraft and ur minecraft client will go big

**Comment by Wymii** [comment]
Does that make (wurst) go to full screen or something??

**Comment by 1337HaxorKiddie** [comment]
Yes.

**Comment by Wymii** [comment]
The game auto full screens (in F11) F1 however does nothing... :/
A scroll bar is seemingly needed atm.

**Comment by Wymii** [comment]
While in full screen I still encounter the same problem :/

**Comment by 1337HaxorKiddie** [comment]
Buy a new Screen.

**Comment by Wymii** [comment]
Fuck That..... Im linked up to a 32" tv screen that should be ample enough to cover the Hack List.

**Comment by OMGchangeMYusername** [comment]
Yeah, no need for a whole new monitor. Just set the GUI scale to normal and it should be fine.

**Comment by mcccs** [comment]
https://www.wurst-client.tk/news/2015-07-01-Wurst-2.0-status/

**Comment by Wymii** [comment]
Thank you @OMGchangeMYusername that helped a bunch :D

**Comment by OMGchangeMYusername** [comment]
You're welcome :)
But be sure to read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md), it helps both of us.

**Comment by Alexander01998** [comment]
# *Duplicate: #1278*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
