### ISSUE TITLE
HoldClick

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1699]
Like fast place or fast break where it breakes a block very fast i was wondering if u can make a hack that when the place or attack button is held down it spamms the specific button in game. I think this woulf be usefull for pvp and ppl who cannot jitterclick and there is no chance you can get ban cuz there is no lock-on.

**Comment by pokeball99** [comment]
Can someone translate this wall of text in english? XD

**Comment by EnderGamer21** [comment]
it mean when u hold the attack button it just attacks witout u clicking it a bunch of times

**Comment by GummiBoat** [comment]
@pokeball99 He basically wants, that the mouse behaves a little bit like a keyboard. As long as you press the key, the signal gets repeated very quickly.

I personally think, that this is really not necessary. For the rightcicks, we have `FastPlace`, which basically does the exact same thing. And hitting stuff is limited. A) Minecraft "cancels" the "destroy-stage" everytime you begin a new action (e.g. sending a click again) and B) mobs, monsters and players have a so-called "hurt-time". That's a time, that specifies the time before the target can be damaged again, which is also the reason, why we don't kill people with a wooden sword on full Killaura speed instantly.

Thanks for reading.

**Comment by Alexander01998** [comment]
# *Duplicate: #1152*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
