### ISSUE TITLE
BlockReachHack

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1700]
With the new .ghosthand hack the player must be 2 blocks through a wall for it to work unlike 4 blocks reach in normal minecraft. this hack will run simultaneously with the .ghosthand. Most hacks such as multi aura allows the player to reach farther than the normal player please allpy this for blocks thankyou

**Comment by OMGchangeMYusername** [comment]
I think it has to be two blocks to work? Might be wrong but I don't think you can make it reach further.

**Comment by WurstContributor** [comment]
Or freecam :P
