### ISSUE TITLE
Arrowviewer/Arrowcam mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1701]
a mod that works like remoteview, if you shoot a arrow and the mod is enables it set you'r view to the arrow
if the hit a entity or a block the view switch back to player

**Comment by solidshadow96** [comment]
That would be good and seems possible because arrows act as  entitys. please add this

**Comment by OMGchangeMYusername** [comment]
What's the point of this? like why would we use it?

**Comment by mcccs** [comment]
Great but Alexander won't love it

**Comment by 43ee3g** [comment]
to look cool and if your shooting someone from a mile away

**Comment by C0de-Ninja** [comment]
I think the point of this is also observation, so you can shoot an arrow over a wall and see where everything is, so you know there are no traps or iron doors or whatever?

**Comment by C0de-Ninja** [comment]
plus it looks cool
What?

*shrug*

**Comment by OMGchangeMYusername** [comment]
ok...

**Comment by Nitrogen-Dioxide** [comment]
This will looks awesome with timer set to 0.5 haha.

**Comment by pokeball99** [comment]
Thus is useless,we have free cam......

**Comment by Eyremba** [comment]
@pokeball99 this mod works like trajectories/projectiles to aim with the bow, it is NOT like freecam you...

**Comment by GummiBoat** [comment]
I already can see the montages with this, lol

**Comment by OMGchangeMYusername** [comment]
@GummiBoat I'm imagining something like NFS Rivals when flying in the air, but with pixelized buildings and an arrow instead of Koenigsegg :heart:

**Comment by Edtlogin** [comment]
I see how this would work. I also see about 3141526 ways this would be useful.
1. Arrows could be fired from a distance to see what's in the distance.
2. Could be used to make sure AimBot is accurate
...

**Comment by OMGchangeMYusername** [comment]
> 1. Arrows could be fired from a distance to see what's in the distance.

Freecam.
> 2. Could be used to make sure AimBot is accurate.

Enable sounds, there's a sound effect in minecraft that plays when your arrow hits.

**Comment by C0de-Ninja** [comment]
Im actually confused about what he meant, did he mean it shows the flight path before? or while the arrow is flying?

**Comment by Eyremba** [comment]
@C0de-Ninja Arrowcam renders like you were the arrow. https://youtu.be/f1aISCjCrnA?t=1m1s
