### ISSUE TITLE
Auto soul plis 

### ISSUE THREAD

**Issue by hackrex** [Wurst-Imperium/Wurst-Client#1702]
auto soup !!!!

**Comment by pokeball99** [comment]
Dupe

**Comment by hackrex** [comment]
Autosoup to complete the hack

**Comment by EnderGamer21** [comment]
UAto Soup is like fast eat or auto eat And is implmented kinda

**Comment by OMGchangeMYusername** [comment]
Duplicate #83.
Please search for old issues next time.

**Comment by mcccs** [comment]
THis is not a duplicate of #83
It was in old.wurst-client.tk in old times.

**Comment by OMGchangeMYusername** [comment]
... ?

**Comment by mcccs** [comment]
It was in WuCl's site in 6 months early

**Comment by OMGchangeMYusername** [comment]
wow you appear to be a little dumb.. unless you're joking.
