### ISSUE TITLE
This is not a Issue 

### ISSUE THREAD

**Issue by JohnBmx** [Wurst-Imperium/Wurst-Client#1703]
Hey can you add a disable button so when people get you to type * . Or .Help in the chat you can because when you do it atm a list of stuff comes up meanning you cant type .help or somthing

**Comment by EnderGamer21** [comment]
do ,. they wont notice

**Comment by GlitchHead** [comment]
or .say

**Comment by GummiBoat** [comment]
# *Duplicate: #141*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
