### ISSUE TITLE
NameTag Disguise

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1704]
Hide name tag when playing and will let you change names in game. Also if player (OP) types that name then mod will search for name on to text or cmd form.

**Comment by PixelMaster3D** [comment]
Also when cmd is run aply for player except bad ones like ban or kick. Including deop and jail.

**Comment by PixelMaster3D** [comment]
Also last issue for now.

**Comment by OMGchangeMYusername** [comment]
Changing your name so other people see you with another name is impossible (with a hacked client).
But if it's about the name *you're* seeing then it is planned.

**Comment by GummiBoat** [comment]
Please don't open an Issue that contains multiple suggestions. Thanks.

**Comment by PixelMaster3D** [comment]
It's not impossible. You have to make your own launcher for it or modify one.

**Comment by OMGchangeMYusername** [comment]
@PixelMaster3D Please settle this for me, are you ignorant or you were just a little bit drunk?
