### ISSUE TITLE
.help faker

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1706]
Some server players are often asking to write ".help" in the chat because they know if you cant do it you have hacks installed.
Maybe writing in chat ".helpFake" sends the text?

**Comment by Alexander01998** [comment]
# *Duplicate: #141*
![](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
