### ISSUE TITLE
Save and load your list of activated mods

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1711]
This feature would be cool because sometimes i panic and have to enable all mods again. It would also be cool to have various sets like for griefing or pvp.

**Comment by WurstContributor** [comment]
Dupe of one of my issues :P

**Comment by GummiBoat** [comment]
# *Duplicate: #656*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
