### ISSUE TITLE
Flight bypass does not work even in the latest release

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1712]
I am running the latest version of NCP, but even an older version i had on my computer did not worked.

But also before the update of Wurst i had this problem. It seems to only happen to me.

Here is a small video i recorded: https://youtu.be/KigzROvWpOs

**Comment by 1337HaxorKiddie** [comment]
I haven´t got damage, fly only works if you get damge. Can it be that the server has falldamge disabled?

**Comment by kim-yannick** [comment]
I disabled godmode and it does not even work (but i now get damage automatically before enabling). Rarely, if i'm not teleported back, i can glide (not fly upwards) some meters and will then be kicked by vanilla. I tried it with both of the NCP versions. BTW, the older NCP version is 3.12.0-Beta2.

**Comment by 1337HaxorKiddie** [comment]
K, idk

**Comment by GummiBoat** [comment]
> only works if you get damge

^ that

> kicked by vanilla

You need to touch a block (side or bottom is enough), then vanilla won't kick you. Otherwise it always will, since you are too long in the air.

**Comment by 1337HaxorKiddie** [comment]
I meant that

**Comment by TheIonosphere** [comment]
In the Garploit client, you can remain in the air for 30 seconds before it kicks you, seemingly bypassing the four second limit. How does that work?

**Comment by 43ee3g** [comment]
it all depends on how fast you're flying

**Comment by Alexander01998** [comment]
> In the Garploit client, you can remain in the air for 30 seconds before it kicks you, seemingly bypassing the four second limit. How does that work?

It doesn't. They just always use it on servers that have the vanilla flight kick disabled to make it look like that.

**Comment by kim-yannick** [comment]
It really doesnt work. Here is a video of "flying" with damage enabled: http://youtu.be/Eaig1dctMC8

**Comment by GummiBoat** [comment]
You need to reactivate flight every time you want to jump off a cliff and you can't go higher than one block deeper than your startpoint.

**Comment by TheIonosphere** [comment]
I have linked to a video of Garploit's flight bypass working for almost 30 seconds on a server which kicks wurst's after 4:
http://i.imgur.com/xcWpaXS.gifv
So it definitely does bypass the limit somehow.

**Comment by 1337HaxorKiddie** [comment]
I think if you fly UP you get earlier kicked than normal.
