### ISSUE TITLE
CrashSword or CrashPickaxe

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1713]
.enchant gives you Fortune 127. It is possible to get enchantments up to Short.MAX_VALUE. If you do that with Fortune or Looting and mine an ore in survival or kill a mob with the sword you should be able to crash servers (and clients) due to too many dropped items. A protection against too many entities would also be cool.

**Comment by 1337HaxorKiddie** [comment]
I think your client will crash first or you get kicked.

**Comment by kim-yannick** [comment]
You're right. I tried in SP at first, but in MP the server does not crash and the client will lag extremely.

**Comment by Alexander01998** [comment]
# *Duplicate: #755*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
