### ISSUE TITLE
Useful Spammer scripts

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1715]
I decided to share some of my spammer scripts here are some:
gun.wspam
![gun](https://cloud.githubusercontent.com/assets/8052644/9156021/4799a464-3e91-11e5-8c81-bd507e8bc3cb.png)
that's the only chat-art spam file i made all the other spam files i made are for other things.

WordEditNuker - Set this to a keybind of choice ".spammer spam WorldEditNuker"

exeGROUP - If you get OP on a server or login to a owner some how run this if the server has group manager It will add Alts that you added to the script with the permission * and other stuff It also adds command blocks at Y: 3 (bedrock level) wherever you were standing when you ran the script And all commands are hidden from Other in game staff unless they have a command spy plugin or check console logs:
http://pastebin.com/PUjkun4v

exePEX - Same thing as exeGROUP but for PermissionsEx 
http://pastebin.com/yws796b8

Download:
https://drive.google.com/file/d/0B_0FPr5dumEWSkJSaWV3TTNFbU0/view?usp=sharing

**Comment by Alexander01998** [comment]
Please use variables and `<repeat>` tags in the "exeGROUP" and "exePEX" scripts to make them more user friendly and to reduce the file sizes.

**Comment by GlitchHead** [comment]
Updated It.

**Comment by GummiBoat** [comment]
> use variables

You forgot something ;P Here you go: [exeGroup](http://pastebin.com/B02ZF5n6) and [exePex](http://pastebin.com/LTF33bjB). :heart:

**Comment by Eyremba** [comment]
Some of my spammer scripts:

InventoryFiller.wspam: http://pastebin.com/jipsfxx5
Fills the inventory of all players with unstackable items, again and again, to annoy them.
Needed permission: /give

ShotToGround.wspam: http://pastebin.com/74R3kcP4
Teleports all players on the server under the bedrock. (They will die.)
Needed permission: /tp

TellrawSpammer.wspam: http://pastebin.com/FNUNBKcj
Uses /tellraw to spam the whole chat full with random shit.
Needed permission: /tellraw

EdgeOfWorld.wspam: http://pastebin.com/ZXx92EUS
Teleports all players on the server to the end of the map. (Pos. 29999999, 80, 29999999)
Needed permission: /tp

TitleSpammer.wspam: http://pastebin.com/FutkcYR0
Uses /title and the MC 1.8 title feature to annoy the whole server.
Needed permission: /title
Example:
![2015-08-11_00 08 20](https://cloud.githubusercontent.com/assets/13738234/9185676/24178e24-3fbe-11e5-8928-91f809181edf.png)

TNT_Disaster.wspam: http://pastebin.com/8f2jaHni
Summons tons of TNT everywhere where you walk. It spawns primed TNT above you in a rectangle form. Destroys a really big part of the map. I recommend to use it with a spammer delay of 50ms if there is no AntiCommandSpam plugin.
Needed permission: /summon

**Comment by Alexander01998** [comment]
@Eyremba Please open a separate Issue for that.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
