### ISSUE TITLE
.stoplag command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1717]
.stoplag on
.stoplag off
A command that hides all entitys (Players,items,PrimedTnt)
to stop some lags

**Comment by GummiBoat** [comment]
# *Duplicate: #1686*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by ravenje** [comment]
GummiBoat i Search before i open this issue, but i don't found #1686

**Comment by labcraft59** [comment]
Yeah! This would be awesome!!!

**Comment by Alexander01998** [comment]
It's this one:

# *Duplicate: #593*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
