### ISSUE TITLE
.ignore (player)

### ISSUE THREAD

**Issue by H1DD3NxD0NUT** [Wurst-Imperium/Wurst-Client#1721]
This command ignores a player when no one has the perms to do /ignore. This is helpful for those spammers that u cant ignore.

**Comment by Alexander01998** [comment]
# *Duplicate: #1416*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
