### ISSUE TITLE
About #1526

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1726]
İ pressed quit game in Wurst but launcher says, you didnt quit, the game crashed!
![image](https://cloud.githubusercontent.com/assets/11584045/9166141/62f15d82-3f5a-11e5-8ce2-2bde8a26087b.jpg)

**Comment by Alexander01998** [comment]
Please include the crash log that has been saved to `...\.minecraft\hs_err_pid3892.log`.

**Comment by mcccs** [comment]
https://gist.github.com/mcccs/a13a5dffaf1af803410c

**Comment by labcraft59** [comment]
Notch_s_hero
xD

**Comment by mcccs** [comment]
I knew, i checked for my session id.
xD

**Comment by Creeperman8362** [comment]
turn vbos off

**Comment by Alexander01998** [comment]
> https://gist.github.com/mcccs/a13a5dffaf1af803410c

Looks like a JRE bug. Try reinstalling your Java.
