### ISSUE TITLE
Add a new Wurst loading screen

### ISSUE THREAD

**Issue by H1DD3NxD0NUT** [Wurst-Imperium/Wurst-Client#1729]
The original one is old so a new one would look nice for wurst

**Comment by mcccs** [comment]
I'll try

**Comment by mcccs** [comment]
Alexander is at vacation.
Do it yourself and open a PR

**Comment by H1DD3NxD0NUT** [comment]
if I make a good one will you use it as a loading screen?

**Comment by 1337HaxorKiddie** [comment]
How should we know this?!

**Comment by H1DD3NxD0NUT** [comment]
ok. I'll try to make a good one

**Comment by OMGchangeMYusername** [comment]
I don't think he'll accept any design, it's actually better to leave it to him. Since you never know how he likes it.
