### ISSUE TITLE
Mass tpahere

### ISSUE THREAD

**Issue by H1DD3NxD0NUT** [Wurst-Imperium/Wurst-Client#1730]
Just like mass tpa but it teleports players to you not to them.

**Comment by mcccs** [comment]
#242
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by GlitchHead** [comment]
This is not a duplicate of #242 at all that issue has to do with the click gui mod list going off screen...

**Comment by H1DD3NxD0NUT** [comment]
How was it a dup? I did search up mass tpahere and there was no other.

**Comment by OMGchangeMYusername** [comment]
@paris-ci Way to go :D
