### ISSUE TITLE
.getpos of <name>

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#1732]
The .getpos command also lets you see positions of other people.

**Comment by 1337HaxorKiddie** [comment]
That only will work if the player is rendered

**Comment by mcccs** [comment]
Dup
#487
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by Nitrogen-Dioxide** [comment]
xD cinema 4D or maya or 3d max

**Comment by mcccs** [comment]
@Nitrogen-Dioxide Wrong: http://Blender.org

**Comment by Alexander01998** [comment]
Needs another parameter before the name so that it won't mess with `.getpos copy`.

**Comment by mcccs** [comment]
@Alexander01998 Why did you delete my duplicate comment?

**Comment by Alexander01998** [comment]
Because it's not a duplicate.
