### ISSUE TITLE
AntiFirework

### ISSUE THREAD

**Issue by H1DD3NxD0NUT** [Wurst-Imperium/Wurst-Client#1735]
Disables firework particles

**Comment by pasi123567** [comment]
Not needed in my opinion

**Comment by H1DD3NxD0NUT** [comment]
well for the people who lagg with fireworks it will be helpful to them

**Comment by OMGchangeMYusername** [comment]
um.. wouldn't that be part of #593? Might be a seperate mod but I guess they're the same.
