### ISSUE TITLE
Ability to turn off the client.

### ISSUE THREAD

**Issue by Kayomi** [Wurst-Imperium/Wurst-Client#1738]
If there is a staff member that wants to screen-share with you, there needs to be a feature to disable the client completely and enable it again when you restart your game.

**Comment by GummiBoat** [comment]
# *Duplicate: #19*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by EnderGamer21** [comment]
its disabling when u dont want to cheat
