### ISSUE TITLE
Gray screen while starting up.

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#174]
Yesturday on my hacked client wurst after my wurst hacked client was loading it was just a gray screen

Please help!!!!!

**Comment by Alexander01998** [comment]
Post the crash report.

**Comment by trollmad3** [comment]
---- Please report this crash at: wurst-client.tk/bugs ----
// I let you down. Sorry :(

Time: 3/11/15 4:18 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at tk.wurst_client.module.modules.ForceOP.getName(ForceOP.java:54)
	at tk.wurst_client.gui.GuiManager.setup(GuiManager.java:152)
	at tk.wurst_client.Client.startClient(Client.java:57)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:613)
	at net.minecraft.client.Minecraft.run(Minecraft.java:444)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.module.modules.ForceOP.getName(ForceOP.java:54)
	at tk.wurst_client.gui.GuiManager.setup(GuiManager.java:152)
	at tk.wurst_client.Client.startClient(Client.java:57)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:613)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:444)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.7 (latest: unknown)
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 69717272 bytes (66 MB) / 235569152 bytes (224 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5570 GL version 4.4.13084 Compatibility Profile Context 14.301.1001.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Canadian English (Canada)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Delete (or rename) `options.json` in your Wurst folder (default: `.minecraft\wurst`).

**Comment by trollmad3** [comment]
Thanks! :)
