### ISSUE TITLE
Hostname suggester

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1744]
.ip says
Current server's ip: 184.xxx.xx.x
My idea is: It should search for a hostname
Current server's ip: 184.x.x.x Hostname: hsjsjs.fdndm.com

How does it work?
http://tejji.com/ip/ip-address-to-url.aspx?ip=184.154.39.146

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by Alexander01998** [comment]
# *Duplicate: #1422*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
