### ISSUE TITLE
Can't Copy Heads in Wurst

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#1745]
I can't copy heads in servers. (control+middle mouse) when I copy head,Steve's head comes to my slot. But in vanilla mc I can copy heads and banners. My keybinds' list:

{
  "B": ".t fastbreak",
  "C": ".t fullbright",
  "F": ".t fastplace",
  "G": ".t flight",
  "H": ".t /home",
  "J": ".t phase",
  "K": ".t multiaura",
  "R": ".t killaura",
  "RSHIFT": ".t ClickGUI",
  "U": ".t freecam",
  "X": ".t x-ray",
  "Z": ".t sneak"
}

**Comment by mcccs** [comment]
Disable Middle click friends in  Wurst opts.

**Comment by Orcunegeacar** [comment]
Ok. I will try it.

**Comment by Orcunegeacar** [comment]
No. It's not working. I closed all things. (middle click friends,news,analtyics....) Still I'm taking steve's head. and it's saying 
![image](https://cloud.githubusercontent.com/assets/11218527/9196254/03912682-4032-11e5-85df-4f2334cb99ed.png)

I'm in omegarealm.com (creative server)

**Comment by GummiBoat** [comment]
Head's can't be copied, not even in creative mode. you need to get it in survival, and then go to creative and multiply it, or give it to you with the /minecraft:give command.

**Comment by Orcunegeacar** [comment]
No, I can copy heads in omegarealm.com with 1.8.8 or 1.8.X ||| Maybe it's a plugin but I can copy them in vanilla minecraft with control + middle mouse. But I can't copy heads in Wurst.

**Comment by Orcunegeacar** [comment]
I guess it fixed in 1.8.7?

**Comment by Orcunegeacar** [comment]
If Wurst uses older version. maybe it's the problem.

**Comment by Eyremba** [comment]
Wurst uses 1.8.0

**Comment by mcccs** [comment]
Mojang says its fixed in https://mojang.com/2015/08/minecraft-snapshot-15w33a/
