### ISSUE TITLE
Random alt accounts from this list!

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1748]
http://www.accountgen.net/minecraft/index.php
This is a website who is really often updating there accounts and nearly all of them will work always.

Maybe making the default button to add some account change to some real Premium accounts?

**Comment by pokeball99** [comment]
Comfirmed not scam site,idk how he would scrape it,but we could come up with something

**Comment by OMGchangeMYusername** [comment]
None worked for me. Also the skin of every account is the same, won't use it.

**Comment by pasi123567** [comment]
http://i.imgur.com/ExWzEB2.png

**Comment by 1337HaxorKiddie** [comment]
You can See if you are Banner vor not. If you are not banned and the credentails are wrong it says: Invalid Username vor Password but if you are Blockes it says: Invalid credentails vor something like that.

**Comment by 43ee3g** [comment]
this would be easier to get
http://alt.site90.net/AccountGen.php

**Comment by pokeball99** [comment]
@43ee3g indeed that would be

**Comment by OMGchangeMYusername** [comment]
poke is everything working?

**Comment by WurstContributor** [comment]
INVALID. DAMMIT.

**Comment by OMGchangeMYusername** [comment]
@WurstContributor Why?

**Comment by OMGchangeMYusername** [comment]
It's a suggestion, to take alts from this site automatically. But none of thier alts worked for and I'm not banned.

**Comment by WurstContributor** [comment]
Oh sorry.

**Comment by pokeball99** [comment]
Lol he deleted his comment

**Comment by Alexander01998** [comment]
These sites would go down if all of the Wurst users scraped alts from them.

**Comment by Eyremba** [comment]
@pasi123567 please tell me which checker you used to check the alts. :)

(Sorry for this short off-topic)

**Comment by GummiBoat** [comment]
@Eyremba use [this one](http://www.mpgh.net/forum/showthread.php?t=766566).

**Comment by pasi123567** [comment]
um.. i just logged in with them in minecraft?

**Comment by Eyremba** [comment]
@GummiBoat I know this checker, but I was interested because of this "Your IP is blocked from Mojang" :D I never saw a checker which is able to tell you this.

**Comment by GummiBoat** [comment]
That is not the checker, that is an information given on the linked site. (FAQ)

**Comment by DataPools** [comment]
Use this one:
minecraftleaks.com
