### ISSUE TITLE
Add Trajectories Hack

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1750]
Please add the Trajectories hack. 

I REALLY want to see where my snowballs and that stuff will land in SkyWars.
Items I want for trajectories:
Snowball
Ender Pearl
Bow
Fishing Rod
Egg
And all the other projectiles.

GREAT JOB ALEXANDER FOR MAKING WURST. BEST CLIENT EVER!!!!!!!!!!!!!!!!!!!!

**Comment by GummiBoat** [comment]
# *Duplicate: #168*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by Glowstone82** [comment]
I could not find any
