### ISSUE TITLE
Game crashes when clicking the 'Resource Pack' button

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1752]
When I go onto Wurst and click on the change resource pack thing, the game goes blank. I can't click anything. I thinks its a crash.
![wurst crash](https://cloud.githubusercontent.com/assets/13759066/9217197/c63657ea-4107-11e5-8a32-dae19880415e.jpg)
 What is that?

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by Alexander01998** [comment]
# *Duplicate: #1287*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
