### ISSUE TITLE
My alts keep disappearing

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1753]
HELP! No matter what I do, my alt list keeps disappearing when I reload Wurst. All my alts get deleted for some reason. I tried many times. I also deleted all the Wurst files and downloaded it again but still, my alts go missing

**Comment by 1337HaxorKiddie** [comment]
Have you also re-installed the Wurst Folder/Settings? That means not only the Folder in the versions Folder

**Comment by Alexander01998** [comment]
# *Duplicate: #570*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
