### ISSUE TITLE
Must make MultiAura settings better

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1754]
Whenever I use MultiAura on Hypixel, I get kicked for hitting too fast. Can you please add a hit speed setting of '
![minecraft 0002](https://cloud.githubusercontent.com/assets/13759066/9217259/72e6b1d8-4108-11e5-86de-3666acb4195d.jpg)
1'

**Comment by Alexander01998** [comment]
MultiAura cannot bypass NoCheat+.
