### ISSUE TITLE
Better Fast-Ladder

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1759]
Please make fast ladder better by making it when I touch the ladder, I will be teleported right to the top in an instant like the some other hack clients

**Comment by Alexander01998** [comment]
> I will be teleported right to the top in an instant like the some other hack clients

That is probably a step hack set to a very high amount, so it will be covered by #1356.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 No, there are clients with FastLadder doing this, it's possible but it's sometimes buggy. Anyway I'm happy with the current one and I think it's fast enough.

**Comment by Eyremba** [comment]
@Alexander01998 here is the source for it: http://hastebin.com/usobitugij.avrasm

If you go to a ladder, it will teleport you up, but only the first 10 blocks/ladders. The rest is done with normal FastLadder. Please note that this "LadderTP" is blocked in 2 or 3 NCP Versions, but not in all and not in the newest, so this "LadderTP" should only be a option for FastLadder, which can be switched on or off.
