### ISSUE TITLE
FightBot in SkyWars

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1763]
When I use FightBot in SkyWars, the bot makes me fall off my island. Probably make it so I don't die like that.
:-)

**Comment by 1337HaxorKiddie** [comment]
I think that´s really hard to make but idk probably Alexander know how he can do this.

**Comment by Alexander01998** [comment]
# *Duplicate: #135*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by OMGchangeMYusername** [comment]
@Glowstone82 You can also use MagicCarpet on Skywars when he makes it ;) It's so amazing and useful.
