### ISSUE TITLE
FakeHacker

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1764]
We need a hack that will make it look like other people are hacking even though they aren't.

**Comment by Alexander01998** [comment]
> What is the point of that ?

Revenge. You know, all these kids today screaming "OMG Hax! I saw ur invisibility hack!!1". This would allow you to report them back.

**Comment by mcccs** [comment]
go to assets remove wurst picture.add optifine logo

**Comment by OMGchangeMYusername** [comment]
@paris-ci XD
What about making FakeHacker turn it off? just when using it?

**Comment by Glowstone82** [comment]
@Alexander01998 LOL

**Comment by Alexander01998** [comment]
> With the wurst logo on the report vid ?

No. Just type into the chat "[annoying kid] is using ForceField!! Everyone report them!". And then the other annoying kids will yell at the annoying kid that annoyed you.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 Thought it's about making him look hacking in *your* view, how would you make him look hacking to other players?

**Comment by mcccs** [comment]
Go near him and another player, Killaura with NoSwing

**Comment by OMGchangeMYusername** [comment]
Since when did Wurst have NoSwing O.o

**Comment by Eyremba** [comment]
Yes @OMGchangeMYusername, "FakeHacker" is a client-side rendering which renders that a player has Killaura, so you can record it, upload it, get him banned. :D

**Comment by JackFishbaugh** [comment]
BUUUUT, like @OMGchangeMYusername said, when you turn on FakeHacker, it should automatically hide on your screen any signs of Wurst. Or even disable all of your mods temporarily... temporarily... THAT GIVE ME AN IDEA. I'll check to see if its already been suggested.

**Comment by JackFishbaugh** [comment]
@OMGchangeMYusername Yes the hack needs to hide any signs of Wurst. And NoSwing should also be added.

**Comment by OMGchangeMYusername** [comment]
I know what it does.. I'm asking does he know a way of making it look like he's hacking to others..
Which is likely impossible but I don't really care about this. 
Some children may use it to accuse completely innocent people ._.

**Comment by Eyremba** [comment]
@OMGchangeMYusername "FakeHacker" is already is many clients like Metro and others. In some clients it is hidden under the mod name "Frame". So it is already used to harm innocent people

**Comment by OMGchangeMYusername** [comment]
@Eyremba Dude I swear I know it's in Metro and Wolfram, I've tried it too but didn't really report.
Plus I was kinda joking when I said it's used to accuse innocent people, but still true.

**Comment by PixelMaster3D** [comment]
You have to report innocent players but noobs and staff.

**Comment by PixelMaster3D** [comment]
Like- the owner was hacking and say it to the admins. :trollface: or post it on YouTube or Facebook, you know the media for humiliation.

**Comment by PatoTheBest** [comment]
@Alexander01998 why did you close this?
