### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by Glowstone82** [Wurst-Imperium/Wurst-Client#1768]
Sometimes, my Wurst client just crashes for no reason. 

I have 8GB RAM
3.3Ghz CPU Quad Core
Windows 10
2 TB HDD

**Comment by 1337HaxorKiddie** [comment]
Crash report?

**Comment by Glowstone82** [comment]
My Minecraft Launcher doesn't log my Minecraft for some reason

**Comment by OMGchangeMYusername** [comment]
Don't tell me you're a mac user.

**Comment by GummiBoat** [comment]
@OMGchangeMYusername > Windows 10

...

btt, "just crashes for no reason" is not enough... please try out again and again what crashes your client, and keep the launcher itself open, so you'll always have the game output ready to paste here. you know how to do that, do you?

**Comment by Alexander01998** [comment]
> My Minecraft Launcher doesn't log my Minecraft for some reason

Wurst v2.2 will fix that.

**Comment by OMGchangeMYusername** [comment]
@gummiboat XD sorry.
