### ISSUE TITLE
Session ID account stealer

### ISSUE THREAD

**Issue by AbsoluteGamer** [Wurst-Imperium/Wurst-Client#1770]
Look here: https://www.youtube.com/watch?v=NsOGHuPn7Mg

This could go well with Force-OP and the alt manager

Please?

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by Alexander01998** [comment]
# *Duplicate: #1029*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
