### ISSUE TITLE
Export / Import Keybinds

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1772]
Like the Multiplayer export/import button
save the keybinds as file and import them

**Comment by OMGchangeMYusername** [comment]
Every client stores keybinds in different look, so it's not like it's gonna work for other clients. Wurst has it like this :
```
{
  "B": ".t fastbreak",
  "C": ".t fullbright",
  "F": ".t fastplace",
  "G": ".t flight",
  "GRAVE": ".t blink",
  "H": ".t /home",
  "I": ".t tracers",
  "M": ".t autobuild",
  "MINUS": ".say /spawn",
  "R": ".t killaura",
  "RSHIFT": ".t clickgui",
  "V": ".t autosprint",
  "X": ".t x-ray",
  "Y": ".t autosteal",
  "Z": ".t sneak"
}
```
While some others use `Mod=number` or `mod:button`
You can go to Wurst directory and open Keybinds json and just copy paste it wherever you want.

**Comment by Alexander01998** [comment]
> save the keybinds as file and import them

They are already being saved in a file and therefore can already be imported & exported.

**Comment by OMGchangeMYusername** [comment]
lol yeah xd
But there's no point of doing that as I said.

**Comment by Alexander01998** [comment]
> But there's no point of doing that as I said.

One could use it to create a backup of their settings or to install Wurst on another computer with the same settings.
