### ISSUE TITLE
Wurst Installer

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1775]
I think it will make Wurst more popular. I know you are too busy but it takes 30 seconds to create an installer!
Just change sources and click build!
http://www.clickteam.com/install-creator-2
https://www.dropbox.com/s/kynkj9fxi22gp0y/Install.iit?dl=0
https://www.dropbox.com/s/t60ly38nn2d6wk1/12.exe?dl=0

**Comment by Alexander01998** [comment]
If I decide to make a Wurst installer, I'll do it myself. Those third party tools usually aren't very good or have some kind of advertisement/spam included.

**Comment by mcccs** [comment]
@Alexander01998 update: i found an offical pretty easy way.
press windows button and r then type
iexpress
its official

**Comment by Alexander01998** [comment]
That's pretty cool!

**Comment by OMGchangeMYusername** [comment]
@mcccs GJ bruh!

**Comment by Eyremba** [comment]
You could also use InnoSetup (http://www.jrsoftware.org/isinfo.php), also a pretty nice tool to make an Installer, it is also free and has NO spam or advertising.

**Comment by mcccs** [comment]
But it needs script

**Comment by mcccs** [comment]
But it needs script

**Comment by Eyremba** [comment]
@mcccs there is a setup-wizard which creates the script for you...

**Comment by GlitchHead** [comment]
I do not think a wurst installer will be useful... its not that hard to add a folder to your versions and you don't ever have to do it again because of the auto updater.
