### ISSUE TITLE
All Wurst disable

### ISSUE THREAD

**Issue by 12FMSV12** [Wurst-Imperium/Wurst-Client#1776]
I dont know if ther's any button on wurst that can disable all the entire hack client. For exaple, i'm useing the hack and some one tell i'm hacking, the owner come to me and says : " say on shat .legit"
I cant because i'm using the hack. It was reelly nice if you make an button to disabela all, the wurst on the screen, tall the chat commands, all the things, like a minecraft default. (for exaple that button can be in options)
THX :)

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by Alexander01998** [comment]
# *Duplicate: #1389*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by WurstContributor** [comment]
@Alexander01998 Umm you led him to a dupe.
