### ISSUE TITLE
.mobview command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1777]
A command that change the super secret settings to the view of mobs

.mobview creeper » Creeper
.mobview enderman » Invert
.mobview spider » Spider

List of super secret settings:
http://minecraft-de.gamepedia.com/Super_Secret_Settings

**Comment by OMGchangeMYusername** [comment]
hm.. not sure how I feel about this but it's kinda clever.

**Comment by 1337HaxorKiddie** [comment]
Thats a good idea, not very usefull but cool.
