### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#1779]
Wot?
http://youtu.be/faXCva0IVYk

**Comment by EnderGamer21** [comment]
Disable all then renalble ur hacks u avtaavted

**Comment by WurstContributor** [comment]
Didn't Help.

**Comment by GlitchHead** [comment]
Enable VBOs

**Comment by WurstContributor** [comment]
Nope.

**Comment by GlitchHead** [comment]
so its not helping you? i enabled VBOs in my video settings in minecraft and it stopped happening for me.

**Comment by mcccs** [comment]
@WurstContributor im sure, sight distance is too long for your slow computer

**Comment by Alexander01998** [comment]
> @WurstContributor im sure, sight distance is too long for your slow computer

That's it. We've had a very similar thing in #478. Just set the distance lower or get a better graphics card and it'll be fine.
