### ISSUE TITLE
Damage command (also makes Flight bypass possible)

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#178]
Well... first I will explain glide.. this glide is better, because when you got hit by anything (cactus/player-hit) it will bypass anti cheat o ALL servers... there is no servers that have protection to this glide O.o . If you glide too much, it will disconnect you saying that "flying is not enabled on this server" , the same way a fly module do.

here the code for the glide...

http://pastebin.com/1b9GwcpG

But, if there is no player to hit you (or cactus xD) ? It will work with the damage command, it "simulates" a player hit/cactus. Damage command can kill you too :D. Oh damage only works if fall damage is enabled too, areas with fall damage disabled will not work. Annnnd another thing that this miracle command can do, when the ground is made of glass blocks, you can teleport down when doing .damage 1 O.o (if there is air below the glass).

here the code for the damage command....

http://pastebin.com/rethdHb4

**Comment by Nitrogen-Dioxide** [comment]
sorry, making the desc now. pressed enter while editing the title '-'

**Comment by Nitrogen-Dioxide** [comment]
Well... first I will explain glide.. this glide is better, because when you got hit by anything (cactus/player-hit) it will bypass anti cheat o ALL servers... there is no servers that have protection to this glide O.o . If you glide too much, it will disconnect you saying that "flying is not enabled on this server" , the same way a fly module do.

here the code for the glide...

http://pastebin.com/1b9GwcpG

But, if there is no player to hit you (or cactus xD) ? It will work with the damage command, it "simulates" a player hit/cactus. Damage command can kill you too :D. Oh damage only works if fall damage is enabled too, areas with fall damage disabled will not work. Annnnd another thing that this miracle command can do, when the ground is made of glass blocks, you can teleport down when doing .damage 1 O.o (if there is air below the glass).

here the code for the damage command....

http://pastebin.com/rethdHb4

**Comment by OMGchangeMYusername** [comment]
is that another Resilience client thing?

**Comment by Nitrogen-Dioxide** [comment]
yes...... sorry about that, but the .jar of the resilience is public

**Comment by OMGchangeMYusername** [comment]
i know but people always talk about this weird client...

**Comment by trollmad3** [comment]
This client is awesome! i dont know why its weird........ PLUS IT HAS FORCEOP (Authmecracker) Its really awesome!

**Comment by Nitrogen-Dioxide** [comment]
i think I'm the only here talking about this client lel.

**Comment by OMGchangeMYusername** [comment]
>i think I'm the only here talking about this client lel.

i didn't say "people always talk about this client **here**"
i often search for hacks and stuff so i saw a lot of people talking about it!
oh and by the way my friend at school was talking about it too..

**Comment by GlitchHead** [comment]
the client resilience is so weird it has a fake "ForceOP" in it that says "sending packets to the server...." stuff and makes a fake op popup in chat and deops you.... making the player think they were op for 1 second.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 I was trying to make this mod, but it looks like it isn't possible on 1.8 anymore. for  
" C03PacketPlayer.C04PacketPlayerPosition " on 1.7 there is 4 floats and 1 boolean.
But for 1.8 it removes the " theplayer.getY " and just keeps the bounding box. so for 1.8 it is 
(Float X,  Float bounY, Float Z, Boolean)
instead of
(Float X, Float bounY, Float Y, Float Z, boolean)
I tested, and it doesn't damages you anymore :/ .
