### ISSUE TITLE
Forcing Mods with YesCheat+ Enabled.

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1781]
Maybe add a feature to YesCheat+ that when YesCheat+ is enabled, you can double click a blocked mod (such as MultiAura because it does not bypass NoCheat+) and it forces it to turn on. I know many servers with NoCheat+ that still allow these "Non-NoCheat+-able" mods (Mineplex for instance because they have a modified version of NoCheat to fit nicely into their server).

If I turn on YesCheat+, I want it to block mods that will not work on a NoCheat server. But I also want to be able to turn on some of these mods because I am aware of what I am doing. I would be able to have some mods blocked and some turned on. It shouldn't be an all-or-nothing type of thing. That's my opinion.

The double click to force mods to work would be VERY nice, and it adds more flexibility to YesCheat+.

**Comment by GummiBoat** [comment]
If you already know the NoCheat on the Server, then disable YesCheat+ and enable the hacks you know will work. Simple isn't it?

**Comment by Eyremba** [comment]
@GummiBoat But if their NoCheat blocks for example step? Then you have to enable YesCheat+ to get it to work, but then you can not use MultiAura or other mods...

I like your idea @JackFishbaugh

**Comment by JackFishbaugh** [comment]
@Eyremba Exactly. And yes that would be a good idea. Maybe Yellow for forced mods? It would be like a stop light. Green is "On", Red is "Blocked, and Yellow is "Forced"
