### ISSUE TITLE
Even Better FastLadder (Addon to #1759)

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1782]
It is possible for FastLadder to be able to go up ladders with a gap. (It's in Flare)
| _ _ |
| _ _ |

| _ _ | ^ One ladder missing making a gap
| _ _ |
| _ _ |

FastLadder should include this. And I think it is NoCheat+ Bypassable.

**Comment by 1337HaxorKiddie** [comment]
And teleporting

**Comment by GummiBoat** [comment]
# *Duplicate: #1270*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by JackFishbaugh** [comment]
gotcha. btw i didnt know spider did this! :D
