### ISSUE TITLE
AirHang

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1785]
Enables Freecam while falling.
Freecam prevents falling.

**Comment by OMGchangeMYusername** [comment]
I doubt that..

**Comment by TheIonosphere** [comment]
I tried using it while falling on a nocheat+ server, it sends you back to where you started and deals damage equivalent to how far you have fallen already. Useful if you have fallen, but it does not let you stay in the air for more than 4 seconds.

Flight does the same thing.

**Comment by mcccs** [comment]
Flight kicks you

**Comment by OMGchangeMYusername** [comment]
Wait let's get this straight, what will this feature do? where would you use it?

**Comment by GummiBoat** [comment]
Flight doesn't kick you if you use it that way. It's a common way to cheat in a jump'n'run.

**Comment by mcccs** [comment]
Think;
In dragon escape you r' the first and you are the last one alive
use this hack, mineplex will say:
1000 gems: alive for 45000 minutes!

**Comment by OMGchangeMYusername** [comment]
Wouldn't that kick you "for flying not enabled"?

**Comment by mcccs** [comment]
let's try

**Comment by mcccs** [comment]
noo

**Comment by mcccs** [comment]
it works!

**Comment by OMGchangeMYusername** [comment]
err.. you tried it in one single minute?

**Comment by mcccs** [comment]
Yeah

**Comment by OMGchangeMYusername** [comment]
ok. So I go on Mineplex now, play dragon escape, enable freecam while falling, and tada?

**Comment by mcccs** [comment]
Yep

**Comment by mcccs** [comment]
Nop!

**Comment by mcccs** [comment]
Play dragons
In dragon escape it duznt give gems for minutes

**Comment by mcccs** [comment]
And don't enable while falling

**Comment by mcccs** [comment]
enable when entering the game

**Comment by mcccs** [comment]
@OMGchangeMYusername did it work?

**Comment by GummiBoat** [comment]
@mcccs Uhm... well, it IS working, indeed. But... I don't get gems for surviving an amount of minutes or something like that.

**Comment by Eyremba** [comment]
Um... @mcccs there is an edit function, you know? You made now 6 single posts...

**Comment by mcccs** [comment]
I blocked them with my adblockplus.

**Comment by OMGchangeMYusername** [comment]
You're lying.

**Comment by 43ee3g** [comment]
doesn't just telling the server you're dead strop you from falling? and it bypasses ncp

**Comment by mcccs** [comment]
no iwasnt
i really blocked when i sent my other message

**Comment by GummiBoat** [comment]
Then disable Adblock ô.o C'mon, this is github!

**Comment by Alexander01998** [comment]
> Uhm... well, it IS working, indeed. But... I don't get gems for surviving an amount of minutes or something like that. But Blink is doing the exact same thing. You just need to stop sending packets and you won't get kicked. But it's pretty obvious that you're hacking.

Well, good to know, but there is no need to make a new mod for this, as that mod would just be a copy of Freecam.
