### ISSUE TITLE
Mcmmo acrobatics (nofall)

### ISSUE THREAD

**Issue by Zalcens** [Wurst-Imperium/Wurst-Client#1786]
I've been testing around a bit, and nofall does not seem to trigger McMMO's acrobatics, is there a way to trick the system by thinking we took the damage but really we didn't?

**Comment by 1337HaxorKiddie** [comment]
Not really, there are clients having that but its really difficult to code i think.

**Comment by GummiBoat** [comment]
> there are clients having that

name them, if there really are some. I think, it's impossible, because McMMOs Acrobatics is relying on fall damage. NoFall is avoiding that you get falldamage (duh). I don't know if you can corrupt packages that say you got fall damage, but I don't think so.

**Comment by 1337HaxorKiddie** [comment]
Saint

**Comment by GummiBoat** [comment]
> Saint

The newest Saint has a rat in it. Anyways, Saints NoFall is similar to Blink. And no, it doesn't work with Acrobatics. (The activated mods are top right, for everyone that's confused by the screen.)

[Link to 68Frame 12MB Gif..](http://www.gfycat.com/FinishedDopeyFiddlercrab)
