### ISSUE TITLE
A SESSION LOGIN

### ISSUE THREAD

**Issue by Draconnian** [Wurst-Imperium/Wurst-Client#1787]
being able to login to someones elses session

**Comment by mcccs** [comment]
#1653 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by linuxcodefire** [comment]
We need one of these but session ID is impossible to get without bukkit plugin... If you know a site please share xD

**Comment by Eyremba** [comment]
@linuxcodefire it is not impossible. I find everytime tousands of working ID's on pastebin.

**Comment by linuxcodefire** [comment]
yes but a custom search to get these from paste bin would be nice.

**Comment by GummiBoat** [comment]
All it takes are two keywords in the search engine and you get [these results](http://pastebin.com/search?cx=013305635491195529773%3A0ufpuq-fpt0&cof=FORID%3A10&ie=UTF-8&q=minecraft+client.log&sa.x=0&sa.y=0&sa=Search)

**Comment by linuxcodefire** [comment]
@GummiBoat Well Thank you!

**Comment by GummiBoat** [comment]
And [here](http://pastebin.com/eS4e4Hi5) is a little present for you.

**Comment by Eyremba** [comment]
@GummiBoat I would like to cry.... so many session ID's (I also found a lot of them) but we can not use it with Wurst :'( 

I hope that @Alexander01998 will implement #1653 before Mojang patches anything...
