### ISSUE TITLE
Ability to write colored/formatted chat messages

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1788]
Add a mod that allows you, when activated, type & in the chat, which will be sent as § to the server.

**Comment by GummiBoat** [comment]
If you send the formatting character (§) as a client (that counts too, if the client is replacing it for you), you'll be kicked instantly, without the message being sent.

**Comment by kim-yannick** [comment]
Is this a protection feature of Vanilla?

**Comment by OMGchangeMYusername** [comment]
Yes.

**Comment by GummiBoat** [comment]
@OMGchangeMYusername Yup, but that's using JSON. And that isn't relying on the formatting character.

**Comment by OMGchangeMYusername** [comment]
Well I said it's a vanilla command, which can type colored chat. Permissions and such don't matter :p 
Also I didn't say it relies on `§`.

**Comment by GummiBoat** [comment]
Korintenkacker. :heart:
