### ISSUE TITLE
AimBot

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#179]
please add aimbot!
i can't explain it properly but when i hit it automatically aims to the nearest player,it should not turn around to people behind but instead it adjusts your aim to the player who's in your sight.
it should ignore the friends just as killaura.

**Comment by Alexander01998** [comment]
AimBot is useless. It's just as detectable as Killaura, but much slower.

**Comment by OMGchangeMYusername** [comment]
well,it's not like i can't use killaura anymore.
but please consider finishing the teams system and stuff.
i wanted aimbot because when i play any team based pvp games with killaura,i end up hitting my teammates stupidly.

**Comment by Alexander01998** [comment]
> i wanted aimbot because when i play any team based pvp games with killaura,i end up hitting my teammates stupidly.

That's why Wurst has TriggerBot, the non-detectable alternative to AimBot.

**Comment by OMGchangeMYusername** [comment]
well triggerbot **NEVER** works for me!!!!!
it just dosen't work.

**Comment by trollmad3** [comment]
Just use Bowaimbot. Its the same thing except you can only use it on a bow. if you want aimbot. then code it yourself :+1:
