### ISSUE TITLE
Possible Player Glitch

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1790]
their was this client that bent player animation and made nocheatplus FREAKED OUT and then the plugin broke it was so bad. so if you can recreate player animation moving many different directions fast it could possible crash people on servers...

* Needs to be tested...
* I believe im on to something.
@Alexander01998

**Comment by Alexander01998** [comment]
> their was this client

What client?

> it could possible crash people on servers...

I highly doubt that that would work.

**Comment by linuxcodefire** [comment]
@Alexander01998 
garpoit hacked client cracked... its easy to crack it shut off you WIFI and click login as premium and turn wifi back on... then access cheats some of them make no cheat plus freak out

**Comment by PixelMaster3D** [comment]
I found a video about this client: https://m.youtube.com/watch?v=NsOGHuPn7Mg

**Comment by PixelMaster3D** [comment]
It's garploit linuxcodefire.

**Comment by linuxcodefire** [comment]
Yeah.

**Comment by linuxcodefire** [comment]
@Alexander01998 atlessed take out nocheatplus because its glitched so bad

**Comment by Alexander01998** [comment]
As far as I know, GarPloit doesn't have a feature like that.

**Comment by linuxcodefire** [comment]
@Alexander01998 sorry for wasting your time again :'( its just all mod enabled at once... and flying fast.
