### ISSUE TITLE
Flying & Mining

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1791]
Yes fast break fixes it up but it tends to glitch and if fast break is blocked while your flying you should be able to mine faster.

Usually you mine slow when flying.

@Alexander01998

**Comment by GummiBoat** [comment]
It's a vanilla feature, that your breaking speed gets slowed down while being in the air/falling, so you won't (for example) break the blocks beneath you too quickly and getting massive fall damage.

**Comment by linuxcodefire** [comment]
At leased a option to disabled this if you want to..
