### ISSUE TITLE
Warning mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1792]
a mod that wans if a special player come in you'r range

.warning (player)

.warning Griefer
if wurst find the player "Grifer" in you'r range it say a warning
[Wurst] Found player Griefer at (location of player)

**Comment by linuxcodefire** [comment]
umm i don't know own detection of this would work but *thumb's up*.

**Comment by OMGchangeMYusername** [comment]
Honestly I don't see how this would be useful but, isn't it better to tell you how many blocks he's away instead of giving you coords?

**Comment by ravenje** [comment]
Or so:
[Wurst] Found player Griefer at (location of player), he is (blocks) away!
