### ISSUE TITLE
☠ Mid-Air Walking

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1793]
A *Mod* that lets you walk in mid air... in world of Warcraft its possible to hack the game to were player is floating in mid-air on nothing (air) and the air is solid so here just walking above normal ground level.

Basically you turn a mod on in mid air and it acts like blocks be-nigh your feet and prevent you from falling so you just walk at like *200 100 200* and stay floating till you turn mod off then you fall,fly or glide..  I Though this would be fun so players could be light *HOW IS HE WALKING IN MID AIR???*

**Comment by GummiBoat** [comment]
# *Duplicate: #781*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

Also, please don't put Unicode Characters in your title. That's somehow.. really unnecessery.

**Comment by linuxcodefire** [comment]
...
