### ISSUE TITLE
TestforWspam

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1794]
In wspam is there a way to have a testfor command. in other words can there be a command that tests for words in chat. if not please add a feature where if a word listed is said in chat it will run a wspam script

**Comment by GummiBoat** [comment]
Generally being able to set up a command on a wanted word (or multiple words) would be a neat idea. Basically like Keybinder just with word(s) instead of keys.

**Comment by Alexander01998** [comment]
# *Duplicate: #389*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
