### ISSUE TITLE
KeySpam

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1795]
in wspam there is no way to simulate a key being pressed. Please add this in where you can have a command press a key and for how long you want it to be held for. 

e.g:   .keypress w(the key) 10(how long-seconds)
e.g:   .mousepress 1(mouse button) 10(how long-seconds)

**Comment by OMGchangeMYusername** [comment]
Duplicate #1152.
Please search for old similar issues next time.

**Comment by TheBoyIsHere** [comment]
and click option! if there is hold...

**Comment by solidshadow96** [comment]
THANKYOU so much for accepted this will help me out alot
