### ISSUE TITLE
Suggestion for the id and name option in Ghosthand, Search, Nuker, X-Ray

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1796]
Its not needful to use "name" and "id" option as single arguments because no minecraft block name contains a numer, maby you can change it to that if the argument is a number like "1" set the searched block to stone, and If the argument only contains "a-z" and "_"  it set the searched block to stone

**Comment by Eyremba** [comment]
This would not be only for ghosthand, if you change it at ghosthand, you must also change it in xray, nuker, and search. This mods use also "name" and "id"

**Comment by ravenje** [comment]
ok

**Comment by Alexander01998** [comment]
> if the argument is a number like "1" set the searched block to stone, and If the argument only contains "a-z" and "_" it set the searched block to stone

It's much easier than that, as the `name` option already accepts both names and IDs.
Try `.search name 1`, it works.
