### ISSUE TITLE
.craft command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1797]
A command that craft items
Work:
User type in: .craft crafting_table or .craft 58
Wurst check if player has 4 wooden planks in his inventory
if this is true wurst make the player craft a workbench
if this is false wurst say: [Wurst] You don't have 4 of Planks in you'r inventory!

maby that is possible:
if the target block is a crafting_table it use this for crafting the block

this is not a duplicate of https://github.com/Wurst-Imperium/Wurst-Client/issues/359

**Comment by linuxcodefire** [comment]
YAS!

**Comment by GummiBoat** [comment]
Partially #359 i'd say

**Comment by ravenje** [comment]
but this is not a duplicate of https://github.com/Wurst-Imperium/Wurst-Client/issues/359

**Comment by GummiBoat** [comment]
> Partially

**Comment by ravenje** [comment]
Yes, Partially

**Comment by ravenje** [comment]
And the comamnd is very useful for some spam scirpts
.craft stone_swrod
.craft stone_pickaxe
.craft stone_axe
.craft stone_shovel
etc

**Comment by OMGchangeMYusername** [comment]
Not really necessary.. Let's be honest here are you that lazy to craft a crafting table?
Plus, as Gummi said it will be complicated, that's just too much..

**Comment by Alexander01998** [comment]
There might be an easy way to do this, we'll see.

**Comment by solidshadow96** [comment]
Yesss please add this the feature would rock
