### ISSUE TITLE
PotionClear Mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1799]
A mod like PotionSaver
but this clear all potion effects instant on walking

**Comment by EnderGamer21** [comment]
what would this be ueseful fo ror  can bind PotionSaver to a letter and turn it of and on

**Comment by GummiBoat** [comment]
# *Duplicate: #1665*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by ravenje** [comment]
@GummiBoat sorry i searched PotionClear not PotionKiller

**Comment by OMGchangeMYusername** [comment]
@ravenje Never search what you want! You want PotionClear right? search only for "potion" and try to find what you want, if you didn't, open a new issue.
