### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1800]
So that you can send an announcement across the whole server.

**Comment by Eyremba** [comment]
Not possible.

**Comment by labcraft59** [comment]
:(

**Comment by labcraft59** [comment]
Ok?

**Comment by GummiBoat** [comment]
It's called "Chat Message".

**Comment by labcraft59** [comment]
Oh...

**Comment by labcraft59** [comment]
Oh also, where is "Auto tpaccept" hack?

**Comment by Eyremba** [comment]
You could only try a hack like the book hack to get OP and then use "/title" or "/tellraw" to announce anything... or "/say" or "/broadcast"

**Comment by GummiBoat** [comment]
It's in progress.

**Comment by labcraft59** [comment]
ok?

**Comment by labcraft59** [comment]
Fly+ YesCheat+ Does not work on NoCheat+ servers btw

**Comment by labcraft59** [comment]
and book hack, cmd hack, and sign hack do not work either

**Comment by Eyremba** [comment]
Fly+ YesCheat+ Does work. And the book hack also works if you pay attention on the dependencies...

**Comment by labcraft59** [comment]
Umm... I will try later?

**Comment by labcraft59** [comment]
Also, here's my server: s8.minespan.com:25749

**Comment by labcraft59** [comment]
Sorry random...

**Comment by labcraft59** [comment]
Ooh also, add /kill @e

**Comment by labcraft59** [comment]
Oh and on milestones it says 100% complete on wurst 2.2... so why is it not out yet?

**Comment by GummiBoat** [comment]
Alexander releases on fridays and lives in germany. It's 1:49 currently there, I think you can wait about 14 hours or so.

**Comment by labcraft59** [comment]
k cool!

**Comment by labcraft59** [comment]
Hey I got #1800!

**Comment by OMGchangeMYusername** [comment]
> It's called "Chat Message".

True.

**Comment by OMGchangeMYusername** [comment]
@labcraft59 so.. what?

**Comment by labcraft59** [comment]
K

**Comment by labcraft59** [comment]
Huh?

**Comment by OMGchangeMYusername** [comment]
What if you got 1800?

**Comment by labcraft59** [comment]
I don't know...

**Comment by labcraft59** [comment]
;(

**Comment by labcraft59** [comment]
Adjustable FastLadder?

**Comment by OMGchangeMYusername** [comment]
Fucking stop spamming. look for old issues, we had some fastladder talk earlier.

**Comment by labcraft59** [comment]
...

**Comment by OMGchangeMYusername** [comment]
I'm curious what do you mean with "..."? Like how am I supposed to take it as?

**Comment by labcraft59** [comment]
like LANGUAGE DUDE!

**Comment by OMGchangeMYusername** [comment]
@labcraft59 You're really getting on my nerves.. Have any more questions? If no, kindly fuck off.

**Comment by labcraft59** [comment]
:broken_heart:

**Comment by EnderGamer21** [comment]
@OMGchangeMYusername  dont be so mean its because some people are new to wurst coding and stuff like that im also a newbie

**Comment by Alexander01998** [comment]
> @OMGchangeMYusername dont be so mean its because some people are new to wurst coding and stuff like that im also a newbie

^

**Comment by OMGchangeMYusername** [comment]
@labcraft59 Opened several issues before, he knows how it works. That's why I was a little pissed..
Plus he asked off topic things and changed the title.. This issue is clearly invalid.

**Comment by GlitchHead** [comment]
._.

**Comment by labcraft59** [comment]
Sorry...

**Comment by PixelMaster3D** [comment]
So he knows but that no reason not be nice. He probably thought that he would pinpoint a few ideas to everyone thinking about.

**Comment by pokeball99** [comment]
@OMGchangeMYusername man u kinda got some anger problems,this is like what? The 2nd or 3rd time u have don't something like this? Relax man,this is the internet,not your job

**Comment by OMGchangeMYusername** [comment]
@PixelMaster3D & @pokeball99 we're done with this thing.

**Comment by PixelMaster3D** [comment]
We know. Your just pissed now for pointing out your behavior issues.

**Comment by OMGchangeMYusername** [comment]
@PixelMaster3D Dude I really don't care what you think of me, at all! Just saying we're done with this, no need to start another "anger problems".
