### ISSUE TITLE
Invseewarner mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1802]
A mod that wans the wurst user if his inventoy modifyd by the server (/invsee)

**Comment by OMGchangeMYusername** [comment]
I'm guessing this is impossible, how would a client know that the admin is using /invsee?

**Comment by ravenje** [comment]
Thats impossible, but i mean if you'r inventory was modifyed by the server

**Comment by OMGchangeMYusername** [comment]
Oh I see..

**Comment by EnderGamer21** [comment]
oh i get it

**Comment by Eyremba** [comment]
Nice idea :+1:

**Comment by linuxcodefire** [comment]
how can something pend confirmation and also be accepted?

**Comment by OMGchangeMYusername** [comment]
@linuxcodefire pending confirmation is about whether he can make it or not, like if it's possible or so.
Accepted means the idea itself is neat and he want to add it, just till he finds out how it works.
