### ISSUE TITLE
Wurst-2.2: Cavefinder defect

### ISSUE THREAD

**Issue by Eyremba** [Wurst-Imperium/Wurst-Client#1805]
Without cavefinder:
![2015-08-14_09 33 05](https://cloud.githubusercontent.com/assets/13738234/9269235/d1e964e0-4267-11e5-9a1f-83faa2587505.png)

With cavefinder:
![2015-08-14_09 33 17](https://cloud.githubusercontent.com/assets/13738234/9269239/db4e6738-4267-11e5-856d-d7c00a31161a.png)

Also tested in some other situations. It does not work.

**Comment by Alexander01998** [comment]
Working fine.

![2015-08-14_09 37 47](https://cloud.githubusercontent.com/assets/10100202/9269271/364e3c62-4268-11e5-80a3-23b4de176f60.png)

**Comment by Eyremba** [comment]
@Alexander01998 

With cavefinder and opened inventory:
![2015-08-14_09 40 41](https://cloud.githubusercontent.com/assets/13738234/9269317/a7364b54-4268-11e5-85b2-ced3deca5524.png)
Working.

With cavefinder and inventory closed...
![2015-08-14_09 40 32](https://cloud.githubusercontent.com/assets/13738234/9269327/b88fe4fa-4268-11e5-94e8-8e916ca922c3.png)
Not working...

**Comment by Alexander01998** [comment]
Also working for me. Are you using some kind of weird OS or weird graphics card?

![2015-08-14_09 50 39](https://cloud.githubusercontent.com/assets/10100202/9269441/faa4d3b8-4269-11e5-8111-7f5b99222bbd.png)

**Comment by Eyremba** [comment]
I am using Microsoft Windows 8.1 with a NVIDIA GeForce GT 650M graphics card.

**Comment by Alexander01998** [comment]
> I am using Microsoft Windows 8.1 with a NVIDIA GeForce GT 650M graphics card.

That's not weird.

Were these two screenshots taken at the same location?
And is that stone or something else? (Try looking at it with F3, it should say "minecraft:stone" and "variant: stone".)

**Comment by Eyremba** [comment]
Um.... I flight now across the map over 500 blocks away. Now I read this, and here it works. Here is also "minecraft:stone" and "variant:stone"
I have no plan why it didn't work at the other position.

**Comment by Alexander01998** [comment]
Then let's just say that it's resolved. I have no idea what could have caused that either.

**Comment by Eyremba** [comment]
weird....

![2015-08-14_10 34 38](https://cloud.githubusercontent.com/assets/13738234/9270207/1dde6fe6-4270-11e5-9051-9dc7be89a280.png)

It is "minecraft:stone" and "variant:stone"
