### ISSUE TITLE
ClickBot mod

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1806]
A mod that allows you to auto click. It should feature a configurable delay, mouse button selection and should work even if the window is not focused.

**Comment by Alexander01998** [comment]
# *Duplicate: #1152*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by kim-yannick** [comment]
I searched for clicker... How did i not found the duplicate?

**Comment by Alexander01998** [comment]
> I searched for clicker... How did i not found the duplicate?

Sometimes the GitHub search is a little weird. They are open for [feedback](https://github.com/contact) though.

**Comment by OMGchangeMYusername** [comment]
I'm.. pretty sure I said this is a duplicate of #1152 already. Maybe my connection is the reason?
