### ISSUE TITLE
autoupdater doesnt Work!!!!

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1807]
@Alexander01998  Why?

**Comment by mcccs** [comment]
Nope,it started to update.

**Comment by kim-yannick** [comment]
AutoUpdater updates the game everytime it is closed.

**Comment by mcccs** [comment]
no, it starts with a delay

**Comment by Alexander01998** [comment]
Wurst only checks for updates when you start Minecraft.
There may be a delay if you have a slow internet connection.
