### ISSUE TITLE
AntiPotion does not work in creative mode

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1809]
Another bug i found with AntiPotion. A 3rd bug is following...

**Comment by GummiBoat** [comment]
That is intended. The mod itself requires you to be in survival mode for it to work. AntiPotion only blocks bad potions like poison for you. You're not affected by stuff like this in Creative mode.

**Comment by kim-yannick** [comment]
Ok, the real problem is that some potions are not blocked even in survival. This is in another issue i created.
