### ISSUE TITLE
.goto cant jump

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#181]
it cant jump when using .goto command

**Comment by Alexander01998** [comment]
It can jump. Things like jumping up or down a hill are absolutely no problem.

The only thing it can't do is jump over a gap. Jumping over gaps is a very difficult task for an artificial intelligence - even Minecraft's Zombie AI can't do that. However, the artificial intelligence in Wurst can do these two things:

1. fly over gaps if Flight is enabled,
2. jump down the gaps and climb back up if NoFall & Spider are enabled

**Comment by Notchshero** [comment]
found a solution! ENabled bunnyhop
