### ISSUE TITLE
On-the-fly processing for Spammer

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1813]
Commands like this:
```
<repeat 1000>
<random string 60>
```
take a long time to process before spamming starts.

I would recommend using a `StringBuilder` or generating on-the-fly.

**Comment by mcccs** [comment]
Wrong coded script:
<repeat 1000>
<random string 60>
</repeat>

**Comment by Eyremba** [comment]
@mcccs this is just an example of him, so ist does not matter. But yes, <repeat 1000> and such bing things take a lot time to start

**Comment by kim-yannick** [comment]
The problem only seems to happen for `<random>`, even if the random string has a length of 1. If i repeat some fixed string over and over it does not affect the performance. So a `StringBuilder` might not fix the issue. I'm currently cloning the code and setup a dev env to see how i can fix this.

**Comment by mcccs** [comment]
I think it should connect random.org

**Comment by kim-yannick** [comment]
What is wrong coded at the script?

**Comment by kim-yannick** [comment]
OK, @mcccs, you're right. I think this is something like a XML formatting, so i closed the `<repeat>` tag using `</repeat>` and now its about 100 times faster.

**Comment by Alexander01998** [comment]
> OK, @mcccs, you're right. I think this is something like a XML formatting, so i closed the <repeat> tag using </repeat> and now its about 100 times faster.

It's more like HTML: You don't have to close it, but it's easier if you do.

**Comment by Alexander01998** [comment]
I am planning to re-write the WSPAM processor to do on-the-fly processing instead of pre-processing, as that will be necessary to do infinite `<repeat>` tags and a lot of more advanced things.

**Comment by Eyremba** [comment]
@Alexander01998 if you re-write this, can you then also implement #616 (.spammer cancel) command?
