### ISSUE TITLE
Resource Packs activate wobble.json shader

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1818]
When i change my resource packs, LSd effect happens..

**Comment by mcccs** [comment]
![1](https://cloud.githubusercontent.com/assets/11584045/9271459/bd02d2a8-4282-11e5-9e22-6b690cc3cea9.gif)

**Comment by Eyremba** [comment]
"But it works on my PC!" :D I have changed my ressource packs without problems a few minutes ago.

**Comment by mcccs** [comment]
Me too a few minutes ago;
but not now

**Comment by Alexander01998** [comment]
It appears that this only happens when switching ResourcePacks after using LSD.
