### ISSUE TITLE
HD font

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1820]
It will be nice if we install Wolfram-like Chat font.

**Comment by GummiBoat** [comment]
You can do that yourself by using a texture pack.

**Comment by mcccs** [comment]
oh

**Comment by mcccs** [comment]
Wait! i need mcpatcher to do this?

**Comment by GummiBoat** [comment]
No. You can just use a texture pack OR replace the file with the chat font in your mc folder (i don't know anymore where it is, but there is one)

**Comment by 1337HaxorKiddie** [comment]
AppData\Roaming\.minecraft\resourcepacks\YOUTEXTUREPACK\assets\minecraft\textures\font

There you go i think thats it.
