### ISSUE TITLE
Enter long wurst commands via chat line

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1821]
It is currently only possible using the spammer.

You may think why? I am currently developing a `.give` command to get items with custom NBT data, which can be very long. I don't want to change the vanilla patch (because this is complicated), so i'm submitting this as an issue.

**Comment by mcccs** [comment]
#1696

**Comment by Alexander01998** [comment]
If you need an item with lots of NBT data, pasting the command into the Spammer should be pretty convenient.
