### ISSUE TITLE
(Question) Where to put .wspam files

### ISSUE THREAD

**Issue by Whatisthisname** [Wurst-Imperium/Wurst-Client#1822]
^
I tried putting it in the spam folder with like death.wspam and some join and levega,e.wspam stuff.
wjen i did  .spammer file [any of the names in the folder] it didnt work.
What am i doing wrong

**Comment by mcccs** [comment]
press windows button + r
%appdata%/.minecraft/wurst/spam

**Comment by Alexander01998** [comment]
> I tried putting it in the spam folder with like death.wspam

That means you have put them into `.minecraft\wurst\spam\autorun`. That should work if you type `.spammer spam autorun/yourfile.wspam`.

Normally, you would just put them into the parent folder of `autorun`, the `spam` folder.
