### ISSUE TITLE
The font is blurred

### ISSUE THREAD

**Issue by TheIonosphere** [Wurst-Imperium/Wurst-Client#1826]
![untitled](https://cloud.githubusercontent.com/assets/13650573/9275983/fe4cf660-4298-11e5-9230-8291aa753f50.png)

I am using windows 8.

**Comment by mcccs** [comment]
Come on Wurst!
Opposite of #1514 !

**Comment by TheIonosphere** [comment]
It was working on the previous version. I think that fixing it on windows 10 broke it on windows 8.

**Comment by mcccs** [comment]
Yeah https://github.com/Wurst-Imperium/Wurst-Client/commit/f11d07f9f93c35d703a50362e29cac9de546a550 broke it

**Comment by Alexander01998** [comment]
There must be something fishy in the OpenGL settings. The same thing is working fine in F*ck Cubik.

![Slick2D fonts in F*ck Cubik](https://cloud.githubusercontent.com/assets/10100202/9278532/b1a947dc-42b1-11e5-9df2-79a96edc799c.png)

**Comment by Spassvogelw** [comment]
Strange, im using Windows 10 an it is blurred too

**Comment by mcccs** [comment]
@Alexander01998 i have an idea, first you decided to add Roboto. But when doing experiments you fixed segoe. I think you should bring Roboto back. Because Segoe is a system font, OSs can change, but   
Assets/wurst cannot be changed with updates.

**Comment by Alexander01998** [comment]
Look how clean that is:

![nice wurst font](https://cloud.githubusercontent.com/assets/10100202/9306918/944f935c-44fb-11e5-9b2e-2f660d2f1bc8.png)
