### ISSUE TITLE
.drop for CrashItem

### ISSUE THREAD

**Issue by kim-yannick** [Wurst-Imperium/Wurst-Client#1827]
The cool thing about this is you don't need to copy the item at all. It will just generate and drop the item automatically several times.

**Comment by 1337HaxorKiddie** [comment]
Dupelicate.

**Comment by kim-yannick** [comment]
Of which issue?

**Comment by OMGchangeMYusername** [comment]
Duplicate #1406.

**Comment by kim-yannick** [comment]
I think i am searching for the wrong keywords everytime. How do you find duplicates so easy?

**Comment by OMGchangeMYusername** [comment]
Mostly because I remember there were similar issues, but too find this easily, type `is:issue drop in`.
You'll find a bunch of issues and there is what you want. It depends on the keyword tho.

**Comment by Whatisthisname** [comment]
Lol live comment

**Comment by Whatisthisname** [comment]
But its a pretty good idea imo
