### ISSUE TITLE
Wurst opens two minecraft windows.

### ISSUE THREAD

**Issue by Whatisthisname** [Wurst-Imperium/Wurst-Client#1828]
When I select wurst at Edit profile, after that press Play, it opens 2 minecraft windows.
(only the right one works)
![image](https://cloud.githubusercontent.com/assets/12211068/9277144/7dfbe402-42a8-11e5-8d37-a85f0a6b102b.png)
I know inception picture

**Comment by 1337HaxorKiddie** [comment]
Yes, thats right for me too and i wonder why.

**Comment by Alexander01998** [comment]
# *Duplicate: #289*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
