### ISSUE TITLE
smart eat idea

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#1829]
like AutoEat, but smarter for what you are eating
like if u have stakes its eats when u have 16 hunger bars its eat and fill all
-ps antiEat: u can choose food to not eat (like potato for obsidian braker plugin)

**Comment by Alexander01998** [comment]
The "smart eating" thing is just a myth. It doesn't matter if you lost one hunger point and eat a whole steak. That will give you extra saturation, so it will take much longer until you need to eat something again.

And considering how deadly it can be to have low hunger in a fight, it's actually much smarter to eat the food as soon as you can.
