### ISSUE TITLE
For minecraft servers:join a server if you are banned

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#183]
Now before you post a RAGE :angry:  comment. please read what im about to say. :+1: So lets say you get banned on a server for Anti-knockback Time till unban 4 days. And probably you are angry right now. and your looking on youtube for ANTI unban and thers a :hankey: ton of virus that say Free unban tool no virus!!! VERY LEGIT! and when you click on Multiplayer on the bottum left thers Unban. Now this tool will use a proxy so you can join back to the server. and do whatever you were doing. and the unbanner tool will be BUILT in to the client its self. You can also chose how long you want the proxy active. (Like 12 hours or 4). I think this should be added to the client. Do you? :question:

**Comment by Alexander01998** [comment]
Duplicate: #70
