### ISSUE TITLE
potion apply command for .potion

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1830]
The normal potion command only allows you to add or set potion effects to potions. i would like if you could apply a effect to your player instead of working with a potion bottle for servers that have potions blocked.

**Comment by Alexander01998** [comment]
Applying potion effects to yourself is impossible, and I'm pretty sure that the new NBT data in Minecraft 1.8 didn't change that.

Have you tried the command with a water bottle yet? That should bypass it.
