### ISSUE TITLE
RightclickNuker 

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1832]
Like nuker but for rightclick

**Comment by OMGchangeMYusername** [comment]
That's kinda useless.

**Comment by pokeball99** [comment]
@OMGchangeMYusername not as useless as u might think,as if u could use that(also known as just ClickNuker) if u want to control your nuking,maybe has is as
~~~
.Nuker mode manual
~~~

**Comment by GlitchHead** [comment]
When you think of ideas.... Please think of a use for it before submitting this issue.... And add that use to the description....

**Comment by ravenje** [comment]
@GlitchHead this is useful because some server's use plugins that add tools that destroy block on rightclick
and very useful in survival games  with autosteal or with a flint and steel

**Comment by OMGchangeMYusername** [comment]
@pokeball99 He said nuker for rightclick, I don't see the use of that.

**Comment by OMGchangeMYusername** [comment]
Yep still useless.

**Comment by OMGchangeMYusername** [comment]
I think the flint and steel is thing is in #805

**Comment by ravenje** [comment]
Ok.

**Comment by pokeball99** [comment]
@OMGchangeMYusername yes his idea of for right click is kinda useless,but we could do it like i said

**Comment by Alexander01998** [comment]
Pretty much the same as BuildRandom.
