### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1834]
Whne i open wurst  pclick singleplayer  or multiplayer it opens tw o wurst wich none is real i have close minecraft and repen it in WUrst 2.2

**Comment by GlitchHead** [comment]
dafuq?

**Comment by EnderGamer21** [comment]
let me tell u without messing up when i open wurst i click singleplayer or multiplayer it open two tabs (wurst minecraft) wihic none of them is real i have to close them and reopen it again

**Comment by linuxcodefire** [comment]
@GlitchHead Love your comment but you name sounds familiar... Wilton? :)

**Comment by GlitchHead** [comment]
No idea who you are.

**Comment by OMGchangeMYusername** [comment]
Duplicate #289. Search for old similar issues please.
And this is not really a problem O.o I can use Wurst normally when it happens.
