### ISSUE TITLE
Silent Bow Aimbot

### ISSUE THREAD

**Issue by TerryyyD** [Wurst-Imperium/Wurst-Client#1835]
Would it be possible to add a Bow Aimbot that instead of looking at the target, you can look at any angle, just like Killaura.

e.g: Like Nodus.

**Comment by linuxcodefire** [comment]
that would be useful evade idea!

**Comment by OMGchangeMYusername** [comment]
Duplicate #732.
Please read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
And make sure to search old issues next time.
