### ISSUE TITLE
Autocommand

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1838]
Automatic execute a command if you have low hearts
.autocommand (Hearts)
.t autocommand

**Comment by OMGchangeMYusername** [comment]
What will this autocommand do?
Is it something that enables other things if you're low on health?

**Comment by Eyremba** [comment]
WSPAM has autorun scripts like "death", "joinserver", and "joinworld". Maybe also make this "lowhealth" also as a WSPAM autorun script?

**Comment by linuxcodefire** [comment]
@Alexander01998 accepted? :P

**Comment by PixelMaster3D** [comment]
No. He's still deciding.
