### ISSUE TITLE
.disguise command for mobs

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1839]
A command that disguise the player as any mob :D (Clientside)
.disguise pig
.disguise zombie
.disguise clear
thats not very useful but funny :D

**Comment by labcraft59** [comment]
Awesome idea!

**Comment by GummiBoat** [comment]
> thats not very useful

You said it yourself.

**Comment by PixelMaster3D** [comment]
It could be useful but a certain point. But this would have to make your name tag disguised.

**Comment by 43ee3g** [comment]
I don't think it's possible unless its in singleplayer

**Comment by PixelMaster3D** [comment]
Then go fool the mind then.

**Comment by 43ee3g** [comment]
why do that when you can 
1. open2lan
2. set allow cheats to true
3. do /gamemode 1

**Comment by PixelMaster3D** [comment]
Then troll them while disguised so they can't see you and destroy or annoy them at best.

**Comment by 43ee3g** [comment]
you should really start trolling players and get off singleplayer...

**Comment by PixelMaster3D** [comment]
I don't play single player unless I was at school doing LAN to the whole school district.
