### ISSUE TITLE
How do I use hack for minecraft version 1.7 and down?

### ISSUE THREAD

**Issue by yycyyc** [Wurst-Imperium/Wurst-Client#184]
I can only use hack in minecraft version 1.8
How do I use hack on version 1.7 or what client do I have to download for version 1.7?
I tried downloading wurst 1.7 but it still gets opened in minecraft version 1.8..
help me please

**Comment by Alexander01998** [comment]
The old MC 1.7.X versions of Wurst can be found on the [downloads page](https://www.wurst-client.tk/downloads/) by clicking on the `<< Old Stuff` button.
