### ISSUE TITLE
Opening the mod list

### ISSUE THREAD

**Issue by XSkillzzZ** [Wurst-Imperium/Wurst-Client#1840]
As soon as I deleted all my key bindings  I couldn't open my mod list with L control... I have tries putting the bindings back,deleting and re downloading the client but nothing works....Please fix this because I cant use the client until this is fixed

**Comment by pokeball99** [comment]
Type
~~~
.t open gui
~~~
Into the chat

**Comment by GummiBoat** [comment]
# *Duplicate: #545*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
