### ISSUE TITLE
Inventory Glitch/Bug

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1841]
When you have an affect on you (like speed or haste) and you open your inventory, the inventory does a weird flashing and shaking thing.

**Comment by GummiBoat** [comment]
Not for me...

![inventory](https://cloud.githubusercontent.com/assets/10976441/9287962/092f71be-4331-11e5-8763-fcf830fb9158.gif)

**Comment by mcccs** [comment]
Duplicate: #1818

**Comment by JackFishbaugh** [comment]
no not a dupe. that issue has nothing to do with it. also might have been a mod i had turned on plus the potion effect. ill check now

**Comment by mcccs** [comment]
but same effect: wobble.json:
I found a way to solve it. Find wobble.json and delete it. XD

**Comment by JackFishbaugh** [comment]
oh i see. ok. yeah im not getting the litch any more.
