### ISSUE TITLE
Could you please put auto-soup hack please

### ISSUE THREAD

**Issue by TheMineRagged123** [Wurst-Imperium/Wurst-Client#1844]
these days i have been playing KitPvP. Then, I realize that many people said auto soup hackers in the server. they said it could let you drinks the soup while you are hitting with your sword. So could you please alexander make that auto-soup please. 
Thanks for  reading.

**Comment by GummiBoat** [comment]
# *Duplicate: #83*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by TheMineRagged123** [comment]
Ok then i am just asking. Sorry for the inconvenience. I am just suggesting. But thanks anyway. I appreciate it. Sorry for the inconvenience
