### ISSUE TITLE
Question: What are the hidden mods in Wurst

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#1846]
Title says it

**Comment by GummiBoat** [comment]
What is the point in hiding them, if we would say it public? C'mon, this project is open source, you can find it yourself.

**Comment by OMGchangeMYusername** [comment]
I guess he meant Easter :egg:s..
I only know `.taco` :P

**Comment by mcccs** [comment]
X wurst

**Comment by OMGchangeMYusername** [comment]
Oh yeah I just remembered :P

**Comment by pokeball99** [comment]
Santa hat

**Comment by mcccs** [comment]
^
- I want to grif

**Comment by Alexander01998** [comment]
They are mods that cannot be enabled through the ClickGUI. Sometimes used for EasterEggs and sometimes for advanced commands like `.goto`.
