### ISSUE TITLE
Anti-Junk

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#1849]
Just a suggestion, when you click this it automatically removes any useless items. So if you have a diamond pickaxe and a couple wooden ones it would automatically drop the wood ones and any stone or gold pickaxes. Also enchantments would be taken into account. But if you had two enchanted things they would both stay.

**Comment by OMGchangeMYusername** [comment]
Duplicate #676. Please look for old issues next time.
