### ISSUE TITLE
force static water

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1852]
When you place a bucket of water is is normal water that flows. My mod +/ command makes water placed down from bucket makes water stay still. Good way to have player say wtf or troll them. @Alexander01998

**Comment by Eyremba** [comment]
#1823 should solve this.
(".give id 8")

**Comment by linuxcodefire** [comment]
If its from a bucket will look funner

**Comment by kim-yannick** [comment]
@Eyremba No, this is a technical block which cannot be obtained in 1.8 anymore.

**Comment by linuxcodefire** [comment]
thats a lie :{
