### ISSUE TITLE
Text Radar

### ISSUE THREAD

**Issue by TheIonosphere** [Wurst-Imperium/Wurst-Client#1855]
Apologies if this has already been suggested, but a search did not find anything so I will post it:

A text radar similar to one in the client Weepcraft would list all nearby players and their distances from you.
It is useful because you can see who is nearby immediately, regardless of what direction.

**Comment by GummiBoat** [comment]
# *Duplicate: #303*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by TheIonosphere** [comment]
That is a regular radar, I was talking about a text one which is a list of nearby players.

**Comment by GummiBoat** [comment]
It's basically the same.

**Comment by PixelMaster3D** [comment]
Yes, only in text form. Still useful though...
