### ISSUE TITLE
Xray still breaking redstone

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1856]
In the last update the bug was fixed where using xray break's all redstone. this is now fixed but if the player interacts with any redstone with x-ray on it will then break the redstone please fix this.

E.G: if you have xray on and you click a button all the redstone within the players reach will be destroyed

see proof at https://youtu.be/L6mJ3kQ46pI

**Comment by Eyremba** [comment]
Freecam and Ghosthand are also breaking redstone at the moment. Tested in Singleplayer

**Comment by GummiBoat** [comment]
# *Duplicate: #250*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by Alexander01998** [comment]
> In the last update the bug was fixed where using xray break's all redstone.

No, it wasn't.

**Comment by TheBoyIsHere** [comment]
why allways say duplicate? u cant just try to fix it?
