### ISSUE TITLE
.author command works for all items

### ISSUE THREAD

**Issue by GrassBlock** [Wurst-Imperium/Wurst-Client#1858]
The .author command will work on diamond swords, armors, etc. I mean like, if i select an item with my mousepointer, it shows the enchantment and stuff. But i need the feature to modify it for example,  
Line 1: Diamond Sword
Line 2: {Enchantment}
Line 3: {number} Attack Damage

![untitled](https://cloud.githubusercontent.com/assets/13658526/9291471/971b0fae-43ec-11e5-855c-f480a8d7a5a6.png)
And Modify It To...
Line 1: Diamond Sword
Line 2: {Enchantment}
Line 3: {Custom Text For Example: By Steve}
Line 4: {number} Attack Damage

**Comment by pokeball99** [comment]
I think the author nbt tag is only can be on books,am I wrong? Or am I misunderstanding the OP?

**Comment by GummiBoat** [comment]
#342 is able to do this.

**Comment by linuxcodefire** [comment]
It would be more like .give command with lore: added
