### ISSUE TITLE
Killaura glitch

### ISSUE THREAD

**Issue by jangwar01** [Wurst-Imperium/Wurst-Client#186]
I don't know if its just me but when i use killaura (any of them) it make me continuously jump and it slows me down so much making it impossible to kill pretty much anyone unless their just standing still

**Comment by jangwar01** [comment]
It also happened just in general (when I'm trying to attack someone)

**Comment by Alexander01998** [comment]
Sounds like you have Criticals enabled without knowing what they work with mini-jumps. :wink:

**Comment by jangwar01** [comment]
lol thanks i just relized
