### ISSUE TITLE
Highjump-Phase-Jesus fix

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1863]
When you enable these some weird things happen. The fix is:
Wurst should come with vanilla server jar. Whenever i click singleplayer it should start the server. Server GUI shouldn't appear.

**Comment by linuxcodefire** [comment]
Minecraft realm is missing to xD

**Comment by Alexander01998** [comment]
# *Duplicate: #1051*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

(also, it's much easier to fix than that)
