### ISSUE TITLE
Wiki Suggestion

### ISSUE THREAD

**Issue by awakened-game** [Wurst-Imperium/Wurst-Client#1864]
So, I just remembered this and it was too late too include it in the suggestions when I took the feedback survey, since I submitted that like an hour and a half ago, well here 'tis:

There should be a wiki page on both Wurst-Bot and Hook Manager, I managed to make an automated script to run Wurst-Bot with the latest client, as Alexander01998's batch script is completely outdated and broken, so that runs fine, although it would be difficult for normal users to run.

Also I compiled the Wurst-Bot GUI after replacing about 1/4 of the code and linking that extra swing lib I've never heard of, but I cant see how the GUI interacts with the Wurst-Bot, they dont communicate at all, the buttons do nothing and i cant really see why it even exists.

And Hook Manager, don't have a clue what it can handle, how it should be used, or why its got so many gibberish class names in .jars. all I know is I can write code that does nothing, then paste the Hook Manager class into the .jar and watch it do _more_ nothing.

This stuff needs documenting, seriously.... but less of a priority than Wurst for 1.9 of course, so whichever can be done first the fastest.

**Comment by pokeball99** [comment]
Um I need a wall of text traslator here

**Comment by linuxcodefire** [comment]
I want to know about hook manager to but i think @Alexander01998 shut it down..

**Comment by mcccs** [comment]
no: it is in beta

**Comment by Alexander01998** [comment]
> as Alexander01998's batch script is completely outdated and broken

I updated the script (quite a while ago actually) so that it works with the later Wurst versions again.

> Also I compiled the Wurst-Bot GUI after replacing about 1/4 of the code and linking that extra swing lib I've never heard of, but I cant see how the GUI interacts with the Wurst-Bot, they dont communicate at all, the buttons do nothing and i cant really see why it even exists.

You mean the Robot launcher? Well, that's the reason why it doesn't have any releases. There is nothing to release yet.

> And Hook Manager, don't have a clue what it can handle, how it should be used, or why its got so many gibberish class names in .jars. all I know is I can write code that does nothing, then paste the Hook Manager class into the .jar and watch it do more nothing.
> 
> This stuff needs documenting, seriously....

I know, but I don't really care about Hook Manager anymore, as I'm not going to use it for Wurst.
