### ISSUE TITLE
Hacker Proof

### ISSUE THREAD

**Issue by rockyrush** [Wurst-Imperium/Wurst-Client#1865]
People on servers want me to do .legit to prove im not a hacker. of course i am so i would like there to be a way to put periods but not make it a command

**Comment by Eyremba** [comment]
Ever heared of .say?

**Comment by mcccs** [comment]
.say .legit

**Comment by rockyrush** [comment]
thank u i did not know about that

**Comment by Alexander01998** [comment]
# *Duplicate: #141*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
