### ISSUE TITLE
crashing abuse for admins/creative...

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1866]
Do like a "." Command and crash someone... by like adding lots of xp orbs at one player forcing them to crash or hooking plugins having them creat inetorys 9*12800 for example

**Comment by mcccs** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/pull/1737 ?

**Comment by linuxcodefire** [comment]
@mcccs alteraively like that but just forcing suject my way..

**Comment by Alexander01998** [comment]
> adding lots of xp orbs at one player forcing them to crash

That would only lag.

> hooking plugins having them creat inetorys 9*12800

That would require that plugin.

You could do `/invsee` and fill their inventory with CrashChests, though.
