### ISSUE TITLE
.goto Bug

### ISSUE THREAD

**Issue by LukasE7x7** [Wurst-Imperium/Wurst-Client#1867]
I liked to see that Goto can jump, but there is now a really bad Path-Finder bug.
This is a really funny path for the survival mode:
![2015-08-16_16 40 24](https://cloud.githubusercontent.com/assets/13395383/9293724/11f11194-4436-11e5-8a21-e1600652e246.png)
So, it seems like something went wrong while updating Goto.

Another Problem is that Goto jumps at the end of the path sometimes. It jumps at one point and I can't control myself any longer. To do ".goto ~ ~ ~" does not help.

**Comment by GummiBoat** [comment]
The first one is probably generated while you had the capability to fly. As soon as the path once is calculated, it won't change until you deactivate/activate it again.

To stop goto from controlling you if something bad happens, use `.t goto off`.
