### ISSUE TITLE
Coloring Item Names

### ISSUE THREAD

**Issue by MrFlameMC** [Wurst-Imperium/Wurst-Client#1868]
With the ".rename" command I was wondering if you could make it support "&(Color Code Here)" or like "%(Color Code Here)" to create an item with a colored name like: "&aShreked."

**Comment by GummiBoat** [comment]
That's Already implemented, use $ instead of &. So it looks like `.rename $aShreked`

**Comment by Eyremba** [comment]
It supports already colors with "$"

**Comment by MrFlameMC** [comment]
THANKS

So sorry, I should have looked at the .help rename page.

**Comment by GummiBoat** [comment]
There's also a [wiki on every command](https://www.wurst-client.tk/wiki/Main_Page/), the mod list is in progress. :)
