### ISSUE TITLE
AutoEnchant for survival mode

### ISSUE THREAD

**Issue by jangwar01** [Wurst-Imperium/Wurst-Client#187]
You should add a auto enchanter that works in both single player and multi player where if a player puts a enchant able item in the enchant table it automatically gives it the best possible enchantes or even better you could make it so we choose our enchants

**Comment by Orcunegeacar** [comment]
It can make lag in servers. I guess if you do that on any multiplayer server. You're gonna kick from server or crash the game. Because when we put a item in enchantment , we wait a lot. But if it's gonna be superfast. What can game do?

**Comment by jangwar01** [comment]
Well maybe they can make it so it does not enchant in like 1 seconds and it takes a few seconds

**Comment by Orcunegeacar** [comment]
Yeah its works if it waits

**Comment by Alexander01998** [comment]
> It can make lag in servers. I guess if you do that on any multiplayer server. You're gonna kick from server or crash the game. Because when we put a item in enchantment , we wait a lot. But if it's gonna be superfast. What can game do?

There is actually a trick to do this in vanilla Minecraft and it doesn't cause any lag or kicks from the server.

1. Put the unenchanted item and the lapis into the enchanter.
2. Take a stack of more than one item (e.g. 23 cobblestone blocks).
3. Try to put the stack into the enchanter, where the unenchanted item is.
4. It will instantly refresh the list of possible enchantments.

**Comment by Orcunegeacar** [comment]
genius 0_0
