### ISSUE TITLE
More autorun spamemr scripts

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1870]
Rain.wspam » If weather change to is rain it dose some
Sun.wspam » Like rain.wspam but for sun
Day.wspam » If time change to day it run stuff
Night.wspam » Same like day but for night
Damage.wspam » If you take damage it do some stuff
Attack.spam » If you attack an entity it do some stuff

**Comment by PixelMaster3D** [comment]
I see where this would be useful too.

**Comment by solidshadow96** [comment]
Duplicate: #389

Please search for similar Issues before submitting yours.

**Comment by ravenje** [comment]
@solidshadow96 this is not a duplicate -.- from #389

**Comment by OMGchangeMYusername** [comment]
Yep that's a duplicate, you could've made it in the form of a comment on the original issue. No need for a new one.

**Comment by solidshadow96** [comment]
agreed

**Comment by MyzticalTekkno** [comment]
<B><I>Duplicate #389</B></I>
<img src="https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png" alt="Please search for similar Issues before submitting yours." style="max-width:100%;">

**Comment by solidshadow96** [comment]
Bruh we already said its a dupe

**Comment by Eyremba** [comment]
@MyzticalTekkno if @Alexander01998 added "Enhancement" as label INSTEAD of "duplicate", then it does not matter and you no longer have to SPAM with saying "duplicate"
