### ISSUE TITLE
NoCheat+ patched .damage

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1871]
If YesCheatPlus is enabled .damage works like if i enable fly
it dosnt work on ncp servers with falldamage enabled :/

**Comment by Eyremba** [comment]
".damage" and the "Fly" if "YesCheat+" is enabled has been fixed recently by NoCheatPlus. So @Alexander01998 must design a new damage bypass. And yes there are many ways to do this. nearly each private hackclient which got leaked has its own working damage bypass.
