### ISSUE TITLE
One-Hit Kill

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#1872]
A mod that lets you hit anything and kill it with one hit.

**Comment by Eyremba** [comment]
Not possible.

**Comment by 43ee3g** [comment]
possible




in creative mode

**Comment by PixelMaster3D** [comment]
Not possible but coul result to multi-aura.

**Comment by OMGchangeMYusername** [comment]
That's impossible, unless you have a certain sharpness level on your weapon; which has nothing to do with a hacked client.
