### ISSUE TITLE
.targetinvsee

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1873]
Like the normal invsee
but this shows the inventory of the target
and works with mobs & players
useful to see the enchantments of the armor of zombies or so
plese add this because its very very useful for some things

**Comment by PixelMaster3D** [comment]
That's what I tried explains to them oblast issue.

**Comment by GummiBoat** [comment]
Mobs have no inventory. Their armor is saved in their spawndata itself.

**Comment by ravenje** [comment]
Yes but its possible to display his items like invsee

**Comment by ravenje** [comment]
And some server's use a § before the player nametag
§7playernametag
I can't use invsee at this players

**Comment by Alexander01998** [comment]
> And some server's use a § before the player nametag
> §7playernametag
> I can't use invsee at this players

They don't actually modify the name. Just type in the name without the server-made decorations.
