### ISSUE TITLE
Enderport

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1874]
Teleport behind the person and fight him when hit.

**Comment by ravenje** [comment]
Blink ?

**Comment by PixelMaster3D** [comment]
When a player comes to attack or hit (somewhere along the lines) you appear right behind them facing them to attack them.

**Comment by PixelMaster3D** [comment]
Assuming it could follow the rule vclip when attacked.

**Comment by OMGchangeMYusername** [comment]
@PixelMaster3D How would he teleport? something that has to do with enderpearls?

**Comment by GummiBoat** [comment]
# *Duplicate: #1048*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by OMGchangeMYusername** [comment]
@GummiBoat I still really don't understand that mod, why would they want it if there's no way it could bypass?

**Comment by GummiBoat** [comment]
Because funny mods are funny, no need to bypass everything.

**Comment by OMGchangeMYusername** [comment]
aooo.. k...

**Comment by PixelMaster3D** [comment]
It's a PvP mod. Not because it's funny but it's a way to avoid harm from players.

**Comment by GummiBoat** [comment]
>  avoid harm from players.

and instantly get reported by them. aye.

**Comment by PixelMaster3D** [comment]
This is a little diff. From #1048 because is tp to them this away but near to kill them.

**Comment by PixelMaster3D** [comment]
And here is where you can find a source. From a file. A jar file. Test and tell me if it works.

http://minecraft-client.blogspot.com/2013/07/updated-wrath-v280-amazing-aura.html?m=1

**Comment by GlitchHead** [comment]
@PixelMaster3D That link seems VERY legit.
#Malware

**Comment by GummiBoat** [comment]
> #Malware

Not exactly, but...

![](http://puu.sh/jFmqV/548fbbb9d1.jpg)

**Comment by Alexander01998** [comment]
Exactly...

![virus spam site](https://cloud.githubusercontent.com/assets/10100202/9327925/9f1331c8-45a4-11e5-9056-5726a2322a01.png)

**Comment by OMGchangeMYusername** [comment]
Yep. These surveys make me want to puke.

**Comment by PixelMaster3D** [comment]
Then I will get an another "legit" source for it.

**Comment by PixelMaster3D** [comment]
I've used this site before, so the only thing to do is have an account to get it. No survey.

http://www.mpgh.net/forum/showthread.php?t=592367

**Comment by PixelMaster3D** [comment]
I have it ready for download. The version is 1.4.7. Couldn't find newest version.

Drive.google.com/file/d/0B1BISc3bD9-uNG1TNjlGaFQwTTQ/view?usp=sharing

**Comment by GummiBoat** [comment]
@PixelMaster3D ... there isn't even a main class for starting the client.

**Comment by PixelMaster3D** [comment]
I just reliased that. Hold on.

**Comment by PixelMaster3D** [comment]
I don't think playing on the client really matters thou. You still check the source for it.

**Comment by GummiBoat** [comment]
But the source is a) screwed up and b) there is no enderport. And it surely does matter to play, because experiencing how it works is important.

**Comment by GlitchHead** [comment]
@PixelMaster3D Seems legit.

**Comment by PixelMaster3D** [comment]
This private client is really hard to get.

**Comment by PixelMaster3D** [comment]
Found one now (on wizardhax site) that didn't take forever.

http://www.wizardhax.com/2013/01/26/minecraft-1-4-7-hacked-client-wrath-download/

**Comment by OMGchangeMYusername** [comment]
1.4.7?!

**Comment by mcccs** [comment]
http://www.wizardhax.com/2045/21/26/minecraft-4-4-7-hacked-client-wrath-download/ is better

**Comment by PixelMaster3D** [comment]
Yeah. That was the last version before going private.
