### ISSUE TITLE
between lags

### ISSUE THREAD

**Issue by TigrexHD** [Wurst-Imperium/Wurst-Client#1881]
With Wurst I've always between lags every 10 seconds. If i play without wurst than not.

**Comment by Alexander01998** [comment]
What are you trying to say?

**Comment by TigrexHD** [comment]
All 10 sec i have a lag for 1 sec.

**Comment by PixelMaster3D** [comment]
He's saying with the client it lags due to mods that are enabled to play the game. Without the mods, the original client has nothing to run so it runs smoothly with system.
