### ISSUE TITLE
Command key

### ISSUE THREAD

**Issue by triblion2000** [Wurst-Imperium/Wurst-Client#1882]
Changing the command key from . to something else as people always get banned because they can't type a . in chat make it something odd like a backwards slash instead that never gets typed because . is commonly used to prove your not hacking and you get banned if you can't do it so changing it would be a good idea

**Comment by Alexander01998** [comment]
# *Duplicate: #141*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
