### ISSUE TITLE
Wurst Installer for 2.2

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#1883]
Hello, I made a Installer for Wurst. It's installing Wurst to your .minecraft/versions folder automaticlly. The "Wurst Installer" Supports all Windows versions. (Sorry but it only supports Windows,Maybe I'll do a Installer for Mac and Linux later.) You can download it for free in this link. (It's installing Wurst 2.2)

DOWNLOAD LINK: http://www.mediafire.com/download/60ki5b8kelqkn57/Wurst_Installer.exe

If you want to do this Installer the default Installer for Wurst I want a little credit :smile: (My name is Orçun)

This Installer supports 9 languages.
I didn't give you credit in installing. Sorry for that but They will open Wurst and they are going to see your name in Left top.

There is no source code for it. (who cares? "I made it in InstallForge")
There is a Mozilla Public License in Installer. You have to accept for install.
You can choose a location for it but DO NOT change the default location.
You installed it! Select ready button and open the default minecraft launcher. (you need a premium account but don't worry. You can open "Wurst" in other Launchers.)
You can uninstall it from the versions folder. (Uninstall Wurst)

Whew. I worked hard for that :smile:  it gave me so much errors but I fixed them. Thanks for downloading and creating Wurst. Alexander :)

(Before install make sure you deleted .minecraft/versions/Wurst)

**Comment by Orcunegeacar** [comment]
I'm uploading the setup to Mediafire... I'll give the link..

**Comment by Orcunegeacar** [comment]
Size of Setup is 56.37MB

**Comment by Eyremba** [comment]
56,37MB setup?! What the fuck did you packed into it?! I made also an Installer Setup for the newest Wurst Version, but this Installer has only 9,89MB...

**Comment by Orcunegeacar** [comment]
Calm down. I said I imported a music (wav file) to loading screen. The wav files are very big.

**Comment by 1337HaxorKiddie** [comment]
remove it we dont need useless things.

**Comment by Orcunegeacar** [comment]
Some persons don't know how to install clients for minecraft. It's not useless.

**Comment by Eyremba** [comment]
I don't think that @Alexander01998 wants a 56MB big installer for Wurst, just so big because you have a music wav file in it..

**Comment by Orcunegeacar** [comment]
Alright. I'll delete the music and upload it again. (3th time)

**Comment by Orcunegeacar** [comment]
I added a download link. You can download and run it. (Before install make sure you deleted .minecraft/versions/Wurst

**Comment by GlitchHead** [comment]
why was music in the installer .-.

**Comment by GummiBoat** [comment]
# *Duplicate: #1775*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by mcccs** [comment]
@Orcunegeacar My idea is, it shouldn't be packed with Wurst. When you download it, it should automatically download newest version.

**Comment by mcccs** [comment]
207 MB!!!!!

**Comment by Orcunegeacar** [comment]
@mcccs I will change icons and images. 
I didn't translate Turkish language. I'm already a TURKISH person. I made this installer in InstallForge (You can translate your own but you can add another language)
Location is correct because installer is installing Wurst folder to your versions folder. But I'll try that later.
