### ISSUE TITLE
Item-Crash - Chest

### ISSUE THREAD

**Issue by 12FMSV12** [Wurst-Imperium/Wurst-Client#1884]
Does the crash Chest still working on newst verssions or.. it's pached ?

**Comment by 1337HaxorKiddie** [comment]
I haven´t seen a server that as patched this except play.gotpvp.net (idk if the ip is right.)

**Comment by Alexander01998** [comment]
Works everywhere as far as I know.

**Comment by Eyremba** [comment]
Yes, but there is a server which seems to have it patched, because if you fill the inventory of a player with this chests, the player crashes, but he can rejoin and after rejoining he has no chests in his inventory. It seems that the fix deletes this items from the inventory at rejoin.
