### ISSUE TITLE
DDOS feature

### ISSUE THREAD

**Issue by auererik** [Wurst-Imperium/Wurst-Client#1886]
is this Possible to add a DDOS command do crash some kiddy server with low Ram

**Comment by Eyremba** [comment]
Duplicate #976 https://github.com/Wurst-Imperium/Wurst-Client/issues/976 DDoSing is illegal and against the law. So no, it will not be implemented, and if you do it, you will go to jail.

**Comment by 43ee3g** [comment]
yes it is illegal but you won't be punished unless you do $3000 worth of damage and this is a client not a booter

**Comment by JackFishbaugh** [comment]
lol some feature this would be. there is no way to do this, but you can crash vanilla servers with some kind of mod. it is in flare. i think it just overloads the server with something, not illegal, and it crashes it.

**Comment by ravenje** [comment]
Dos not ddos
for DDOS you need more then computer
