### ISSUE TITLE
Parkour Mod

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1887]
Bypasses Nocheat+ and makes jumps when you reach the edge and go to next ledge near you.

**Comment by JackFishbaugh** [comment]
dupe #110

**Comment by JackFishbaugh** [comment]
I suggested this too by the way. I love this feature so much!

**Comment by OMGchangeMYusername** [comment]
It's duplicate #522. The other one means an automated bot, this one is simply jumping at the edge.

**Comment by JackFishbaugh** [comment]
@OMGchangeMYusername will he add it soon???

**Comment by PixelMaster3D** [comment]
Oops! Forgot to check. My bad Alex.
