### ISSUE TITLE
Latest version doesn't work for mac?

### ISSUE THREAD

**Issue by ItsKKayla** [Wurst-Imperium/Wurst-Client#1889]
Hi Wurst Team! I have tried several times to download your latest version of Wurst but it brings me back to the loading or crash screen. Why is this happening and am I the only one this is happening to?

**Comment by mcccs** [comment]
#1224 ![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
