### ISSUE TITLE
Force-op Sign

### ISSUE THREAD

**Issue by BarneyisFat** [Wurst-Imperium/Wurst-Client#1890]
Used it in 1.8.3 Followed The Instructions and doesn't work

**Comment by JackFishbaugh** [comment]
vanilla or spigot?

**Comment by BarneyisFat** [comment]
How Can You Tell? Its A Cr Server

**Comment by BarneyisFat** [comment]
us.lichcraft.com Its what it is called

**Comment by JackFishbaugh** [comment]
If it has plugins, it isn't vanilla. If it does, it is spigot or bukkit.

**Comment by BarneyisFat** [comment]
o it is spigot
