### ISSUE TITLE
blowing up helpers

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#1892]
i have some ideas for mods. will help alot for faction players!
1.cannon builder- a bot thet build a cannon from many types
if something is missing he say:
[wurst] cannon bot has found missing: "ITEM"
2.tnt falling shower- something thet show you a range thet a cannon will blow the tnt to him
based on a longggg code :laughing: 
3.ceggs placer - make the server think thet u place the cegg in a block but he is in water
(no idea how it will be but ok ill give u an idea :grinning:  )

**Comment by mcccs** [comment]
invalid

**Comment by GummiBoat** [comment]
> cannon builder

AutoBuild.

> .tnt falling shower

... what? I doubt that's possible

> ceggs placer 

wtf is a cegg?

And finally, please don't put multiple suggestions into one Issue. That'll probably reject your Issue without the need to give a reason.

**Comment by GlitchHead** [comment]
ceggs are creeper eggs for raiding N00BS

**Comment by GlitchHead** [comment]
I am a noob giving me the right to call others noobs


© 2015 **Noob conduct**

**Comment by LolDatSec** [comment]
@TheBoyIsHere is probably new to cracking.
- TNT cannon: autobuild template, description can be found here: https://www.wurst-client.tk/news/2015-03-08-Wurst-v1.6-&-1.7/ (I think auto build should be documented, I might drill into it after I'm home and send a pull request later.)
- Trajectory prediction: interesting but near impossible to implement, it can best give a approximate range that varies, do some test on your own SSP world. Long code is not automatic magic.
- Creeper eggs placer: `.throw` or `.t FastPlace`.
