### ISSUE TITLE
duplicate item

### ISSUE THREAD

**Issue by SongHout** [Wurst-Imperium/Wurst-Client#1893]
In minecraft PE when you using XModGames, whenever you pick up 1 item, it multiply to 99.
I wonder if this is possible in minecraft PC too?
If it is then it must be super OP

**Comment by 1337HaxorKiddie** [comment]
For Servers Impossible, but in Singleplayer it should work

**Comment by GummiBoat** [comment]
It is possible and it's called Creative Mode.

**Comment by linuxcodefire** [comment]
its possible on server just difficult and you don't have direct OP access...

**Comment by JackFishbaugh** [comment]
mc pe is too different from pc. especially with modding
