### ISSUE TITLE
Bowaimbot

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1894]
When targeting far targets, it kicked me for 
"invalid moving packets"

**Comment by Eyremba** [comment]
I can confirm this, but I am not sure what really triggers this "Invalid moving packets."

**Comment by OMGchangeMYusername** [comment]
Maybe because your direction changed so fast&accurately? Myabe :p

**Comment by Alexander01998** [comment]
Maybe there is something wrong with the algorithm that causes it to output nonsense if the target is too far away.

**Comment by TheBoyIsHere** [comment]
i have an idea thet aimbot is shotting the entity you are looking at not the nearest
sometimes its looks whird u wonna shot a playar away from u and u do 180 rotate and shot another player :-1:
