### ISSUE TITLE
.pickup command / mod

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1895]
A mod that only pick up a selected item type
.pickup name diamond_sword
if the mod is enabled and you destory a chest or kill a player with full invenory wurst only pick up diamond swords and ignore the other items

**Comment by GlitchHead** [comment]
Duplicate: #804
---------------------------------------------------------------------------------------
![a2111686109_2](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by EnderGamer21** [comment]
dupe #1695

**Comment by EnderGamer21** [comment]
#1590

**Comment by Eyremba** [comment]
@EnderGamer21 this is a completely other issue...

**Comment by EnderGamer21** [comment]
u could not do that because typing that would take longer than just picking it up u can create auto pickup
wich picks it up

**Comment by Alexander01998** [comment]
#676 does the same thing, but more efficiently.
