### ISSUE TITLE
Broken Link...

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1896]
"If you have trouble setting it up in Eclipse, read the wiki page "How to Debug Wurst in Eclipse"."
That page is gone
"https://www.wurst-client.tk/wiki/How-to-Debug-Wurst-In-Eclipse/"

**Comment by linuxcodefire** [comment]
@Alexander01998

**Comment by EnderGamer21** [comment]
Dupe #1695

**Comment by BoomBoomLHack** [comment]
https://www.wurst-client.tk/wiki/Tutorials/How-to-Debug-Wurst-In-Eclipse/
