### ISSUE TITLE
.invsee for entitys

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1897]
.invsee for entitys
like goto or follow
.invsee Zombie

**Comment by Eyremba** [comment]
Duplicate: https://github.com/Wurst-Imperium/Wurst-Client/issues/1873

**Comment by GlitchHead** [comment]
Duplicate: #1873
---------------------------------------------------------------------------------------
![a2111686109_2](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by EnderGamer21** [comment]
zombies dont have inventory
