### ISSUE TITLE
Command for editing written books

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1898]
A command that change a written book back to a normal book without lost the contained pages (Creative)
.book

**Comment by LolDatSec** [comment]
Strip JSON data and writing them again on another book. Cool idea.

**Comment by EnderGamer21** [comment]
why would it be useful  u can just .author to change the name of the book

**Comment by LolDatSec** [comment]
Further editing the book maybe?

**Comment by EnderGamer21** [comment]
@LolDatSec ur right

**Comment by Elephantlovr33X** [comment]
I think He means, To UN- Publish the Book, That is already published, For you can Edit it AGAIN
Btw that would Be AWESOME
