### ISSUE TITLE
Sign crash(er)

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#1899]
Create a sign and write something cute on it. Place sign and click it when you want to boot server players

**Comment by LolDatSec** [comment]
Do you mean sending arbitrarily large sign data to the server to cause a memory overflow Denial of Service? Or just a empty concept?

**Comment by PixelMaster3D** [comment]
I'm not specific about it. I just saw a video that got me an idea about this.

**Comment by PixelMaster3D** [comment]
As long there is a concept that works, then I'm fine with it.

**Comment by GummiBoat** [comment]
# *Duplicate: #967*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by PixelMaster3D** [comment]
Well I bring this up because there is now another bypass for it.
