### ISSUE TITLE
Incase you report hackers/ Suggestion

### ISSUE THREAD

**Issue by ShadowSeeker2003** [Wurst-Imperium/Wurst-Client#19]
You should have a feature to allow you to hide the Wurst symbol during gameplay so you wont get caught incase you want to report someone else

**Comment by OMGchangeMYusername** [comment]
why would you report a fellow hacker?
and what if he was using wurst too?
for me it's so selfish to report someone when you're hacking too!

**Comment by Alexander01998** [comment]
@OMGchangeMYusername is right: That's unfair.

**Comment by Notchshero** [comment]
Press F1

**Comment by GlitchHead** [comment]
-_-

**Comment by GlitchHead** [comment]
The logo can get a bit annoying.

**Comment by 1337HaxorKiddie** [comment]
It seems like the users what this feature.

**Comment by 1337HaxorKiddie** [comment]
It looks like* sry can't seit cuz im on my mobile
