### ISSUE TITLE
Leaf glitching

### ISSUE THREAD

**Issue by jangwar01** [Wurst-Imperium/Wurst-Client#190]
Not sure if its the server I'm on, i doubt it but for some reason sometimes when I'm jumping off leafs i start spazzing out on me and glitching instead of just falling off  and i eventually get kicked for flying of course

**Comment by jangwar01** [comment]
@Alexander01998 when i jump off of blocks. For example on those kit pvp servers where you jump off the spawn to pvp i start glitching back and forth and get kicked for flying

**Comment by Alexander01998** [comment]
> when i jump off of blocks. For example on those kit pvp servers where you jump off the spawn to pvp i start glitching back and forth and get kicked for flying

Sounds like you had Sneak enabled without noticing it.

**Comment by jangwar01** [comment]
No i guarantee you i did not have crouch on

**Comment by Alexander01998** [comment]
> No i guarantee you i did not have crouch on

Not crouch, the Sneak mod in Wurst.
