### ISSUE TITLE
Invsee bug report

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1900]
If the server modiy the nametag above the player's head its not posisble to use .invsee (player) =/

![2015-08-18_23 53 47](https://cloud.githubusercontent.com/assets/12088599/9345772/c054d9b6-4614-11e5-8170-5028e92e2d0f.png)

![2015-08-18_23 52 37](https://cloud.githubusercontent.com/assets/12088599/9345762/9e0f895a-4614-11e5-8ed0-c08ddb5e9ad0.png)

Because this nametag contains §

![2015-08-18_23 55 08](https://cloud.githubusercontent.com/assets/12088599/9345794/f8508b12-4614-11e5-93d7-dc0fc4596d7d.png)

**Comment by ravenje** [comment]
Plese fix this bug

**Comment by LolDatSec** [comment]
Minecraft servers only allow alphanumerical and the underscore character, so `$,&,@,#,^,*` can all be character candidates.
