### ISSUE TITLE
Ranged BowAimbot

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#1901]
A hack that allows you to choose the closest Entity, the 2nd, the 3rd, the last etc...

**Comment by labcraft59** [comment]
To shoot. sorry forgot that

**Comment by EnderGamer21** [comment]
already implmented its called bow aimbot

**Comment by GummiBoat** [comment]
# *Duplicate: #809*

![](https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)
