### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1902]
All entitys with my name has a green nametag!

![2015-08-19_01 48 00](https://cloud.githubusercontent.com/assets/12088599/9347045/bb9ad06e-4624-11e5-9f17-1d703d1b81f8.png)
![2015-08-19_01 48 04](https://cloud.githubusercontent.com/assets/12088599/9347044/bb99aa40-4624-11e5-8a4a-a4242b26a2dc.png)
![2015-08-19_01 48 06](https://cloud.githubusercontent.com/assets/12088599/9347043/bb95c4de-4624-11e5-94c6-f40628d5c46c.png)

With or without nameprotect enabled
Test it self!

**Comment by EnderGamer21** [comment]
is ur username Me  and u can middke ck=lick the pig to turn it off it works any player or anmila with a nametagu can friend them so whrn u use kill aura whenit has all encabled it wont attack the green because its ur friend

**Comment by Alexander01998** [comment]
As @EnderGamer21 said: You added that name to your friends list.
