### ISSUE TITLE
.reset command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1903]
Like .rename but this reset the item name to default

![screenshot-minecraft 1 8](https://cloud.githubusercontent.com/assets/12088599/9347085/7336543c-4625-11e5-8f43-6f9b83127e78.png)
![screenshot-minecraft 1 8-1](https://cloud.githubusercontent.com/assets/12088599/9347086/73368d58-4625-11e5-8d27-ec82ab8475f3.png)

**Comment by PixelMaster3D** [comment]
A cheaper way for renaming. XD

**Comment by Alexander01998** [comment]
The command needs a different name, though.

**Comment by GummiBoat** [comment]
@Alexander01998 `.rename clear`? That would mean, that you can't rename your item to "clear" with this command, but... I think that's really no problem.

**Comment by EnderGamer21** [comment]
@GummiBoat  or .t rename clear
