### ISSUE TITLE
CrashItem for Spawneggs

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1904]
CrashItem also rename spawn eggs to crash the server
on plotme server's you can't spawn mobs
but villagers and they can't be renamed using a nametag without a trick (trick is with a netherportal)

**Comment by GummiBoat** [comment]
Villagers can also be renamed if someone else has their inventory opened. So use a 2nd instance of minecraft and open the inventory of the villager with your alt account, then rename the villager.
