### ISSUE TITLE
MultiAura and KillAura Bug?

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1906]
Not sure if this is a bug or just something annoying that is in the game. But when you attack players with a KillAura (this doesn't happen with mobs), you get slowed down drastically.

**Comment by Eyremba** [comment]
@Alexander01998 is far as I know this only happens if KIllaura & Criticals or MultiAura and Criticals are active, so this slow down seems to be a Criticals bug and not a Killaura bug.

**Comment by 43ee3g** [comment]
Its probably not a bug but attacking something breaks your sprint

**Comment by 1337HaxorKiddie** [comment]
Yes.

**Comment by JackFishbaugh** [comment]
it could be because of criticals.
