### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1907]
You don't need to be 18 to get donates.
Coinwidget.com

**Comment by Alexander01998** [comment]
It's not just about PayPal or Bitcoin, it's about all the laws that are connected to it.

Here in Germany, it's generally not possible for someone under the age of 18 to make money in any other way than a part-time job (delivering newspapers, cashier at McDonalds, that kinda crap).

An exception to this can only be made by a law court. And before they do that, they want a detailed plan of my expected income and expenses (I don't have any expenses, but they don't care), the approval of my parents, a 25€ fee and I don't know what they'll come up with next.

By the time all of that is done, I'll probably already be 18.

**Comment by pokeball99** [comment]
well,for the people that want to donate anyway,can u suggest where they donate to instead?
