### ISSUE TITLE
Better Killaura for 1.9

### ISSUE THREAD

**Issue by HeartOfShrapnel** [Wurst-Imperium/Wurst-Client#1911]
Delay between attacks so that you always hit when your "charge meter" is full.

**Comment by linuxcodefire** [comment]
umm?

**Comment by EnderGamer21** [comment]
i know but 1.9 mineplex or other servers didint update till 1.9 snapshot and 1.9 didint come yet the snapshot did

**Comment by HeartOfShrapnel** [comment]
When it does come out, I mean. I'm asking Alexander to be ready for when 1.9 is released.

**Comment by OMGchangeMYusername** [comment]
That's too early. It will come out at least after two months.
And no server uses snapshots.. It's unsecure af.

**Comment by mcccs** [comment]
No it isn't http://minecraft.gamepedia.com/Damage#Attack_cooldown

**Comment by Alexander01998** [comment]
I have to wait for MCP to update to 1.9, so it's way too early to make suggestions for that.
And once it is updated, I'll have to adjust the Killaura anyways.
