### ISSUE TITLE
Wurst Client 2.0.1 crashes: Initializing game [MAC]

### ISSUE THREAD

**Issue by WurstPlayerEver** [Wurst-Imperium/Wurst-Client#1912]
![1b0899a91d41bc0ea07760df8b9ab4aa-2](https://cloud.githubusercontent.com/assets/13874395/9365490/dae0056a-467f-11e5-8b6c-3382d3b5a2b9.png)
While I ran 2.0.1 on my Mac, Wurst was just sitting there with a black screen.
While I was waiting, my application closed and told me it crashed..
Any anwser to this?

**Comment by Alexander01998** [comment]
# *Duplicate: #1224*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
