### ISSUE TITLE
A rainbow kinda Tracer thingy that points to an unknown block.

### ISSUE THREAD

**Issue by Artamiel** [Wurst-Imperium/Wurst-Client#1913]
So I was playing Block Hunt on Mineplex when I saw this rainbow tracer going to an invisible block. I turned off tracers and chestesp but the invisible block still had a greenbox around it and there was still a rainbow line leading to the invisible block. What is it? ![](http://i.imgur.com/cInFStj.png)

**Comment by Artamiel** [comment]
I found it again in the lobby pointing to the void, but when I explored it, it tped me back to spawn.http://prntscr.com/86jyar

**Comment by Alexander01998** [comment]
# *Duplicate: #222*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
