### ISSUE TITLE
Download Plugin list

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1915]
Some server let you do /pl for plugin list. Be nice if you could download this on bukkit, spigot, ext servers. so you wouldn't have to copy it all..

if ./pl doesn't work you should be able to check 2 ways.. 
(if /pl don't work try /?)

/? works on most servers of /pl doesn't work.

... Save to a txt file :D
@Alexander01998 possibly a command? :D

**Comment by Eyremba** [comment]
Duplicate #1249

**Comment by linuxcodefire** [comment]
@Eyremba well its a new day... new time and lot different from 0-1000 -.- that was like back in 1.7 this is 1.8

**Comment by Eyremba** [comment]
@linuxcodefire I suggested the same, and my source code was from a 1.8 hack client so it is up to date.

**Comment by linuxcodefire** [comment]
@Eyremba -.-

**Comment by Alexander01998** [comment]
> that was like back in 1.7

Everything here is for Minecraft 1.8. Wurst was closed source in 1.7.

> Duplicate #1249

Actually #431. It might say NoCheat but it works for any plugin and is much more reliable than `/pl` or `/?`.
