### ISSUE TITLE
NoCheatPlus Patched Phase

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1916]
Phase don't work with newest version of nocheatplus

**Comment by EnderGamer21** [comment]
actavate yes cheat +

**Comment by linuxcodefire** [comment]
@EnderGamer21 
still patched

**Comment by Eyremba** [comment]
#1780 will close this.

**Comment by EnderGamer21** [comment]
@Eyremba no its not the same

**Comment by Eyremba** [comment]
@EnderGamer21 it must not be the same *facepalm* this linked issue will add more phase modes and this phase modes are NCP bypassing! Read the issue I linked instead of only reading the headline.

**Comment by linuxcodefire** [comment]
+Bug ;)

**Comment by linuxcodefire** [comment]
Bug ;)

**Comment by JackFishbaugh** [comment]
It is the same. I was saying how Phase is very broken, and only works on old NCP builds. And it needs to be updated
