### ISSUE TITLE
.repair command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1918]
Command to repair damaged items (Creative)

**Comment by OMGchangeMYusername** [comment]
There's something called midclick as far as my shallow knowledge of Minecraft goes.

**Comment by Eyremba** [comment]
@OMGchangeMYusername Yes there is a midclick but it will copy it with all NBT-Tags so the damage is also copied....

**Comment by OMGchangeMYusername** [comment]
Ah yes I was dumb.. But would copying it and using anvil to repair it take that long?

**Comment by OMGchangeMYusername** [comment]
K never mind..

**Comment by linuxcodefire** [comment]
Still be a ok.. idea :)
