### ISSUE TITLE
.leave msg <message>

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1919]
.fakekick (message)
^
$ as colors

A command that works like .leave, but this show a custom kick message

Very useful for screenshots that say: "You are banned by CoolAdmin123: $4NOW I WILL GRIEF THE SERVER!" and the serverowner will think CoolAdmin123 Griefen and not you xD

**Comment by ravenje** [comment]
and realy helpful to get unbanned by faking the kickmessage of a server :/
Example: "You are banned from ServerMod123: Hacking"
possible fakemsg: "You are banned from ServerMod123: Unban at 5 August 2015"
and say to another servermod in teamspeak: "He forget to unban me!" or so

**Comment by JackFishbaugh** [comment]
cool idea. i like it

**Comment by kim-yannick** [comment]
I think i can implement this, but maybe its too late to add this into 2.3.

**Comment by kim-yannick** [comment]
Should it really leave the server or just show the GUI for a screenshot?

**Comment by EnderGamer21** [comment]
what if u hack a person that has a wurst hacked client shouldnt be there be like a thing so when u acdentaly steal a player that also has the same hacked client it should tell u another wurst player
so u dont steal his acount

**Comment by kim-yannick** [comment]
@EnderGamer21 Has this something to do with that issue? No. Also a collection of all Wurst users could make servers ban all of them.

**Comment by linuxcodefire** [comment]
Sorta like login hack :p

**Comment by solidshadow96** [comment]
Very useful

**Comment by PixelMaster3D** [comment]
agreed.

**Comment by KhantKyaw** [comment]
When will it added?
