### ISSUE TITLE
DOX on Alexander01998

### ISSUE THREAD

**Issue by Keked420** [Wurst-Imperium/Wurst-Client#1920]
![keked](https://cloud.githubusercontent.com/assets/13878830/9373424/81eaf2f8-46a7-11e5-826b-a95a4e345bc7.PNG)
![keked](https://cloud.githubusercontent.com/assets/13878830/9373443/bfd7bab0-46a7-11e5-8427-74d65630d444.PNG)

You mad bro?

**Comment by pokeball99** [comment]
Dox on alex? Um.....

**Comment by Keked420** [comment]
@Alexander01998 u mad brah?

**Comment by EnderGamer21** [comment]
close this issue this instant

**Comment by JackFishbaugh** [comment]
im confused. i also see no dox. only some fat mother f**ker named wesley. im just confused??

**Comment by JackFishbaugh** [comment]
wait, is this alex's twitter? and is that a picture of him?

**Comment by OMGchangeMYusername** [comment]
Don't mind these scum! Skid everything to make Wurst better.
You must be Garkolym after all..

**Comment by JackFishbaugh** [comment]
@OMGchangeMYusername who is he? he seems very.. unintellegent.
