### ISSUE TITLE
SessionStealer?

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1922]
![keked](https://cloud.githubusercontent.com/assets/7843719/9385328/15b5595e-4713-11e5-9b60-b5a90b7f8a47.PNG)

It says you made a sessionstealer wiki page and i cant find a link on it..... help

**Comment by mcccs** [comment]
http://wurst-client.tk/wiki/Special_Features/Force_OP_(Session_Stealer)/

**Comment by trollmad3** [comment]
@mcccs do you have steam because i really wanna add you

**Comment by mcccs** [comment]
No.

**Comment by Eyremba** [comment]
@Alexander01998 if I read the wiki article about the SessionStealer, it seems that you have to enter only the SessionID, but does this really work with ONLY the SessionID? I have seen this feature in another client, and there you have to enter also the username (which is also in the logfile):

[12:24:13] [Client thread/INFO]: Setting user: xxxxxxxxx28
[12:24:13] [Client thread/INFO]: (Session ID is token:7vvvvvvvvvv96cee15634624bbf:xxx)

As far as I know, you must also enter SessionID and Username in GarPloit.

**Comment by kim-yannick** [comment]
@Eyremba The username will be automatically fetched from the UUID using the Mojang API.

**Comment by Eyremba** [comment]
@kim-yannick cool, nice idea :+1:

**Comment by kim-yannick** [comment]
@Alexander01998 Where are the 37 premium accs from?

**Comment by Alexander01998** [comment]
> if I read the wiki article about the SessionStealer, it seems that you have to enter only the SessionID, but does this really work with ONLY the SessionID? I have seen this feature in another client, and there you have to enter also the username (which is also in the logfile):

And that's how I beat those clients, by making the features better. I did the same thing with AutoBuild, Nuker, the AltManager and a bunch of other features. They have all been in other clients before, but Wurst's version of them is the best one.

As @kim-yannick said, the session ID contains the UUID of the player, which can be converted into the username. That not only makes it easier to use (by only having one thing to paste from the log), but also ensures that it keeps working when the username changes.

> Where are the 37 premium accs from?

http://mpgh.net/. It used to be over 300 alts, but most of them changed their password by now (and I've been too lazy to get new ones).
