### ISSUE TITLE
Crash Issue - Mac (Yosemity, Java 8)

### ISSUE THREAD

**Issue by lukashol** [Wurst-Imperium/Wurst-Client#1924]
I am not able to start the Wurst client, so I tried to Update to Java 8 Update 60, alltough I get this Error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

System Details:

Mac OSX Yosemity 10.10.5
Java 8 Update 60
Wurst v2.2

**Comment by mcccs** [comment]
#1224

**Comment by mcccs** [comment]
It is YosemitE

**Comment by lukashol** [comment]
I updated to Java 8, removed the old Java versions like it was described in the tutorial and downloaded the newest minecraft launcher. When i started the launcher the log said that my java version is '1.6.0_65' and i am not able to start the wurst client with the same error like before. What to do now?

**Comment by linuxcodefire** [comment]
Just emulate it!

**Comment by lukashol** [comment]
Now there is no more Java Plugin in Library/Preference Panes/ or in Library/Internet Plug-ins/ where it should be. After installing java 8 again, there are no Java Files in these folders...

**Comment by lukashol** [comment]
@linuxcodefire how to emulate it?

**Comment by linuxcodefire** [comment]
Run it as a different version google to run it as different os... if mac removed this feature... it's been awhile since I used mac.

**Comment by lukashol** [comment]
Ok, i think i know the problem. I reinstalled the old Apple Java 6 and tried method 2 from here 
https://github.com/Wurst-Imperium/Wurst-Client/wiki/Using-Wurst-with-Java-8

This tutorial says that the new minecraft launcher brings java 8 with it automaticly.
My java control panel says i have java 8 update 60. I still cant start wurst. same error like before.

**Comment by linuxcodefire** [comment]
Uninstall all java and reinstall fastest one. Restart also.

**Comment by lukashol** [comment]
FUCK YESS it works! I tried to use an older version of Wurst (i used 2.0.1) and it works without any Errors!

**Comment by linuxcodefire** [comment]
-.-

**Comment by lukashol** [comment]
I thought that it works, because I didn't get the same error like before, but it doesn't.
Now I got this:



---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// But it works on my machine.

Time: 20.08.15 19:20
Description: Initializing game

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.files.FileManager.saveAlts(FileManager.java:410)
	at tk.wurst_client.files.FileManager.init(FileManager.java:92)
	at tk.wurst_client.WurstClient.startClient(WurstClient.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.0.1 (latest: unknown)
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 143286072 bytes (136 MB) / 271912960 bytes (259 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.4.2 310.41.35f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by linuxcodefire** [comment]
Again completely remove java restart... reinstall latest java restart then try it again. @lukashol

**Comment by lukashol** [comment]
I completely removed Java. All versions. Everything. I restarted. I installed Java 8 Update 60. Restart. Didn't work. I reinstalled the old Apple Java 6.Restart.  Didn't work. I installed Java 8 Update 60 again. Restart. Doesn't work. It's a waste of time. 3 hours waste of time -.-

**Comment by GlitchHead** [comment]
@lukashol this issue will help you #1224

**Comment by lukashol** [comment]
@GlitchHead I read this 3 times. I tried it so many times. I used the 1224 issue. I also tried to use the same version like in 1224. It didn't work.

**Comment by GlitchHead** [comment]
@lukashol If none of these solutions are working for you try this:
Find your java 8 directory and go into the bin folder and copy the directory you should have something like this:
```/random/java/dir/bin```
add this to it
```/random/java/dir/bin/java```
goto your minecraft launcher and goto edit profile and check executable and replace everything with ```/random/java/dir/bin/java```

**Comment by linuxcodefire** [comment]
@GlitchHead agreed

**Comment by lukashol** [comment]
Can't find Java directory. Asking google said it's in Library/Java but that java folder doesnt exist. Searched "java" in the finder, no folder found. :-1:

**Comment by lukashol** [comment]
Installed Java 8 again, restarted. Found nothing. Installed Java 8 again, restarted, Java Folder in Library exists. In Library/Java/JavaVirtualMachines/ is no java 8. only java "1.6.0.jdk"

**Comment by lukashol** [comment]
System Preferences/java says i have java 8 update 60 -.-

**Comment by lukashol** [comment]
I will stop trying that shit. Sometimes the Java folder in Library exists, sometimes not without changing anything. Sometimes in Library/Internet-Plugins there is an Java file, a few minutes later without changing anything there is no more java file. I hate Java, i hate oracle, i hate osx and i will this all now. Thank you guys for trying to help me but it looks like I am to stupid, oracle is to stupid or my mac is trolling me (._. )

**Comment by lukashol** [comment]
@GlitchHead in /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/ is a folder called "bin" but i couldn't find any folder called "dir" in my library :/

**Comment by Alexander01998** [comment]
> A little "update" to my problem: I reinstalled the old Apple Java 6 and tried method 2 from here 
> https://github.com/Wurst-Imperium/Wurst-Client/wiki/Using-Wurst-with-Java-8
> 
> This tutorial says that the new minecraft launcher brings java 8 with it automaticly.
> My java control panel says i have java 8 update 60. I still cant start wurst. same error like before.

That's odd, the new Minecraft launcher has worked for everyone so far. Are you sure you downloaded the right launcher? I remember some people saying that Mojang has a .jar version and a .exe version, and that only one of them works on Mac.

**Comment by lukashol** [comment]
@Alexander01998 i went to http://minecraft.net/download and downloaded the Minecraft.dmg, opened this and copied the Minecraft.app into my Applications folder.

**Comment by lukashol** [comment]
@Alexander01998 YOU ARE MY HERO <3 
WHY THE FUCK did nobody tell me that i have to download the MINECRAFT.jar launcher and not the minecraft.app launcher???? I WASTED 5 HOURS WITH THAT AND IT'S SO EASY : :o:

**Comment by Alexander01998** [comment]
I'll add a note on the tutorial that you need the Jar version. :wink:
