### ISSUE TITLE
FastFall

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1927]
A mod that increases how fast you fall down. It should be adjustable. It is in Metro, but it is not adjustable in Metro.

**Comment by linuxcodefire** [comment]
Umm?

**Comment by TheIonosphere** [comment]
You can already control your falling speed (along with the speed of everything else) using timer, with a multiplier from 0.1 to 10.

**Comment by JackFishbaugh** [comment]
It isn't the same as timer, it only increases how fast you fall. You take anymore fall damage with it.

**Comment by JackFishbaugh** [comment]
I don't want to use timer for this. Timer makes everything go fast. I only want to reach the ground fast

**Comment by JackFishbaugh** [comment]
Example of me using it: https://gyazo.com/faee5a4038fcdebeb4c08a1aa4a934d6
