### ISSUE TITLE
All U Want Mod

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#1928]
Hey Alexander. There is a mod called "All U Want Mod". Its possible to 100% customize your items, and get it. (in Creative mode) IT WORKS ON SERVERS TOO! But Sadly the Developer doesnt seem to update the mod.
That was a so cool mod, maybe you can add a similar feature to wurst with making your own items.

Ikr its already integrated to make custom potions. If u would add that, this would be the only mod/client
in 1.8 who have this feature what can be used in multiplayer (creative) servers.

**Comment by ravenje** [comment]
Yes, ALL U WANT is the best mod of the world, but this wurst is a hacked client, not a modloader =
You can use .rename to rename you'r tools ($ as color codes)

and read this: https://github.com/Wurst-Imperium/Wurst-Client/issues/342

**Comment by Alexander01998** [comment]
Wurst can do all of that already. Try the `.give`, `.potion` and `.rename` commands.

**Comment by Tropfer** [comment]
Yes i didnt know about the new 2.3 Update. But now i have the problem:
You cannot type long commands in the chat so u cannot really get special items. Please Make the .give type screen seperate where u can type unlimited (like the command block)

**Comment by Alexander01998** [comment]
Just type it into the Spammer instead of the chat bar.

**Comment by Tropfer** [comment]
Um i got this:
![2015-08-21_14 52 58](https://cloud.githubusercontent.com/assets/13330912/9408583/80824a60-4814-11e5-804b-692cf4c50ec2.png)

**Comment by Tropfer** [comment]
could someone answer me?

**Comment by pokeball99** [comment]
No :)

**Comment by EnderGamer21** [comment]
@Tropfer  did u type .and then ur thing

**Comment by Tropfer** [comment]
Yes...

**Comment by ravenje** [comment]
@Tropfer
the .give comamnd on you'r screen are multipe lines
it must be in 1 line

Example:
.give iron_sword 1 0 {display:{Name:Name,Lore:[Lore]}}

Try to paste you'r command in a commandblock, press Ctl+a and then ctl+c and try it again to paste in spammer

**Comment by EnderGamer21** [comment]
did u type .give then ur thing

**Comment by Orcunegeacar** [comment]
Geforce GT 220 supports Windows 10? Reply please

**Comment by Tropfer** [comment]
?

**Comment by Orcunegeacar** [comment]
I mean I have Geforce gt 220 GPU. Does it support Windows 10? Because In the past I installed Windows 10. the screen was terrible. I downgrade to Windows 7.

**Comment by Orcunegeacar** [comment]
But maybe now they are supporting it. Maybe :disappointed:

**Comment by Tropfer** [comment]
Oh you mean the screen was very dark? Well i think  they dont support it.  It always happen on the pc of my parents that the screen gets very dark. Then they nede to install the Intel Video Driver...

Im still on windows 7 i dont want Windows 10

**Comment by Orcunegeacar** [comment]
Actually no. My resolution was bad and limited. But anyway I found an information and they don't support it :disappointed:  but thank you a lot.
