### ISSUE TITLE
TItleaim

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1929]
A shoot helper that displays a title and zoom in
![2015-08-20_22 09 41](https://cloud.githubusercontent.com/assets/12088599/9396975/d6fdf992-4798-11e5-954f-28507977e0ed.png)
![2015-08-20_22 09 45](https://cloud.githubusercontent.com/assets/12088599/9396976/d72047fe-4798-11e5-8962-078e220e732f.png)
![2015-08-20_22 09 46](https://cloud.githubusercontent.com/assets/12088599/9396978/d741d5d6-4798-11e5-98f1-11177ac63360.png)
![2015-08-20_22 09 59](https://cloud.githubusercontent.com/assets/12088599/9396977/d741dcc0-4798-11e5-9e5c-ec3639cb02cb.png)

**Comment by EnderGamer21** [comment]
its awesome

**Comment by PixelMaster3D** [comment]
What an improvement

**Comment by solidshadow96** [comment]
cool

**Comment by OMGchangeMYusername** [comment]
Would be very amazing. But.. How can he make it O.o

**Comment by solidshadow96** [comment]
using the /title command i think

**Comment by OMGchangeMYusername** [comment]
I already know that's like title command. But I'm saying is it possible to make it act like Trajectories?

**Comment by solidshadow96** [comment]
hmmm

**Comment by EnderGamer21** [comment]
of u have slowwness it zooms in and with title cmd it wil be that but ther hast o be some way to get slowness but not get affected by it

**Comment by EnderGamer21** [comment]
o wait the noslowdown

**Comment by solidshadow96** [comment]
xD

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
