### ISSUE TITLE
See Where Mobs Can Spawn

### ISSUE THREAD

**Issue by BarneyisFat** [Wurst-Imperium/Wurst-Client#1930]
Something Like this

https://gyazo.com/8e15d3f0a8dd7f60c8400362db6a9ad2

**Comment by linuxcodefire** [comment]
I love this idea!

**Comment by BarneyisFat** [comment]
@Alexander01998 Pls :\?

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
