### ISSUE TITLE
Impersonate msg command

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#1931]
If there is a way to send a /msg to a person but intead of it saying 
eg: solidshadow96->%player%
it could change the name of the player sending the msg so you could fake being someone else.
command e.g: .fakemsg (player) (wanted display name) (msg)

**Comment by PixelMaster3D** [comment]
like .fakemsg (Target) Coolman "This server sux!!!"

<Coolman> This Server Sux!!!

like that?

**Comment by Elephantlovr33X** [comment]
That Would Be AWESOME!

**Comment by OMGchangeMYusername** [comment]
Not possible.

**Comment by linuxcodefire** [comment]
Yes it possible but difficult needs op then you can pull plugs

**Comment by solidshadow96** [comment]
it hides your name when sending a msg and changes it to somthing else

**Comment by Eyremba** [comment]
@solidshadow96 this is impossible, because the SERVER adds your name to the chat message.

**Comment by solidshadow96** [comment]
yes
PLEASE add this it would make the client AMAZING

**Comment by OMGchangeMYusername** [comment]
@linuxcodefire wow.. Who the fuck would want to impersonate someone when he's already op??
Plus that's totally not what he meant.

**Comment by linuxcodefire** [comment]
...

**Comment by solidshadow96** [comment]
...

**Comment by OMGchangeMYusername** [comment]
Don't be stupid. If you have something to say, say it bluntly. The "..." is not even funny anymore..
Being op and impersonating someone is pointless, you can simply ban him if you want to.

I'll simply apologize if I missed something, like a real way of using it.

**Comment by linuxcodefire** [comment]
@OMGchangeMYusername sorry to cause trouble :/

**Comment by solidshadow96** [comment]
Same dude i just thought it might be usefull to troll people with also you could impersonate an admin. and dont even say noone would be that stupid cuz there are 4yr olds that play this

**Comment by solidshadow96** [comment]
true
