### ISSUE TITLE
Using .invsee on disguised players

### ISSUE THREAD

**Issue by Elephantlovr33X** [Wurst-Imperium/Wurst-Client#1932]
Herro! I love Wurst, it is My FAVORITE client! 
But I play in servers that have sometimes players In /disguise When they are Pvping.
And when im about to Pvp People I like to check what they Have With .invsee (player)
Im wondering IF ITS Possible to have .invsee to also invsee  people with a Disquise as a  mob or something. 
If its Possible
welp, that was My Suggestion!
Please Reply!
Thanks!

**Comment by Alexander01998** [comment]
Should be possible, you just need to know their name.

**Comment by Elephantlovr33X** [comment]
I do type in there name right, because I am able to Use the Tab Key on my Keboard.
Also I was close to them when Doing it.
It says "Player Not Found" 
@Alexander01998

**Comment by Alexander01998** [comment]
It depends on how the server handles it. Some servers make the players invisible while others remove them completely. In the latter case, you can't view their inventory.
