### ISSUE TITLE
Weird font.... 

### ISSUE THREAD

**Issue by Eyremba** [Wurst-Imperium/Wurst-Client#1933]
![elv17dz](https://cloud.githubusercontent.com/assets/13738234/9403609/c78f939e-47e8-11e5-862c-894d6f4baae3.png)

Look at "AntiBlind", "BaseFinder", "CaveFinder", "ChestESP", and "Freecam"
"e" are further down than other letters, the "S" seems to be bigger than "E" and "P"
The "h" of "ChestESP" is slightly further above the other letters etc.
This looks a bit... weird...

**Comment by Alexander01998** [comment]
What is your Wurst version, operating system and screen resolution?

**Comment by Eyremba** [comment]
Wurst 2.3, Windows 8.1, 1920x1080

**Comment by Orcunegeacar** [comment]
It's same here. you forget fullbright too bro. My system:
Wurst 2.3,Windows 7,1336x768
This bug started in 2.3
That wasn't in 2.2

**Comment by Orcunegeacar** [comment]
I guess you designed fonts only for Windows 10? right? Because you were working on Windows 10

**Comment by Orcunegeacar** [comment]
@Alexander01998
