### ISSUE TITLE
this client is bad :(

### ISSUE THREAD

**Issue by DevilDemon001** [Wurst-Imperium/Wurst-Client#1935]
where are attributtes or what is with subtitles btw i cant control the ench command i want to control that like the potion command pls do that and this client is king :+1:

**Comment by 1337HaxorKiddie** [comment]
use the .give command, like .give minecraft:diamonf_helmet 0 0 {ench:[{id:7,lvl:127},{id:1,lvl:127}]}

if you do this you will get a enchanted Item, you can see more nbt tags here: http://minecraft.gamepedia.com/Tutorials/Command_NBT_Tags#Items

**Comment by solidshadow96** [comment]
hmmm first of all ive been using this client for 5 yrs and i LOVE it never will ever change from it. second it would be nice to be able to control the enchants but plz dont say this client sucks it doesent

**Comment by Alexander01998** [comment]
This place is meant for suggesting features and reporting bugs in an objective matter. Opinions and feedback can be submitted through social media, e-mails, and occasionally through feedback surveys.

**Comment by OMGchangeMYusername** [comment]
Just to clarify, Selecatble enchantments have been already suggested. #603
