### ISSUE TITLE
.give command Too Little Space

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#1937]
Hey. There is a new command in Wurst called .give

I was so happy when i saw that it supports nbtdata. So i did go to a Potion generator (online website) and generated a custom potion. then when i pasted the command i noticed that the chat hasn't enough space for commands such this. That is sad. Maybe the .give command could have a seperate bar to type the command (like the command block has). I hope this get fixed soon.

**Comment by linuxcodefire** [comment]
So more chat space... that would be nice spend hug ass chats

**Comment by GlitchHead** [comment]
enter the .give command in the spammer

**Comment by linuxcodefire** [comment]
But use a shortcut have @Alexander01998 add it xD

**Comment by EnderGamer21** [comment]
even if u do /give sam thing so theres no was of fixing it

**Comment by MyzticalTekkno** [comment]
@GlitchHead Thanks for giving me that information Glitch :smiley: that helps me alot, my brain is not popping me out that idea before :laughing:

**Comment by Tropfer** [comment]
Thanks
