### ISSUE TITLE
.potion Lore

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#1938]
How i can add Lores to the potions?
![image](https://cloud.githubusercontent.com/assets/13330912/9411574/010bfb42-4827-11e5-9363-1aa31b410f0d.png)

**Comment by linuxcodefire** [comment]
Agreed

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire That was a question.

**Comment by 1337HaxorKiddie** [comment]
Try to make you potion with the .give command, because with the command you can lores.
