### ISSUE TITLE
Colors in .give!

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1939]
Plese add $ colors to .give
like in .rename

**Comment by OMGchangeMYusername** [comment]
Why don't you just use rename on the item you just got? or does it not work that way? (I never really use .give)

**Comment by ravenje** [comment]
finitely i can use wurst to make item lores, but not with colors =((
Plese add color support for .give

**Comment by Alexander01998** [comment]
> finitely i can use wurst to make item lores, but not with colors =((
> Plese add color support for .give

I'm pretty sure that color codes can also be added using an NBT tag.
