### ISSUE TITLE
The pointless command.. warning it's pointless!

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1940]
Simply type .pointless watch the magic and wonders of nothing happening! It's fool proof!

**Comment by JackFishbaugh** [comment]
it is already implemented. just type .pointless, and nothing with happen. there done.

**Comment by linuxcodefire** [comment]
Lol..

**Comment by OMGchangeMYusername** [comment]
The pointless issue.. warning it's pointless! #1940.

**Comment by linuxcodefire** [comment]
Good thing it's not sharp.

**Comment by Alexander01998** [comment]
Already implemented: `.nothing`

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 Is that an Easter :egg:?

**Comment by Alexander01998** [comment]
No, it can actually be quite useful with the Spammer. Say you have something like this:

```HTML
<!-- comment
-->
.t nuker on
```

This will output an empty message before enabling Nuker.

```HTML
<!-- comment
-->.nothing
.t nuker on
```

This will not output an empty message. It will do `.nothing` and then enable Nuker.
