### ISSUE TITLE
See People In /v For TrueSight

### ISSUE THREAD

**Issue by BarneyisFat** [Wurst-Imperium/Wurst-Client#1941]
Title Says All

**Comment by solidshadow96** [comment]
More information required

**Comment by linuxcodefire** [comment]
Isn't that was truesight does?

**Comment by BarneyisFat** [comment]
Nope It Sees inv entites like invisible armor stand

**Comment by Eyremba** [comment]
@BarneyisFat no it shows invisible entities and players, also admins with /v

**Comment by solidshadow96** [comment]
it runns a player scanner in the area to detect if any entitys are near and if they are it creates a vague image of the player. but because /v is part of bukket it does not work along with gamemode 3(spectator)

im not saying to have true site see /v'ed admins just please add /gamemode 3 players

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
