### ISSUE TITLE
Give command create Templates

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#1942]
I saw the give command Templates i want to create my own for the .give commands because i made 50 foot long commands ex: 
``` .give chest 1 0 {BlockEntityTag:{Items:[{id:mob_spawner,Count:64,Slot:0,tag:{display:{Name:"EnderDragon Spawner"},BlockEntityTag:{EntityId:EnderDragon}}}]}} ```

I would love if i could save that as a template named Ender Dragon Chest

**Comment by 1337HaxorKiddie** [comment]
Yes, thats also my question how can we create item templates.

**Comment by solidshadow96** [comment]
save it as a wspam script

**Comment by Eyremba** [comment]
To create your own Give-Templates is only possible with WSPAM, because the real templates are hardcoded in the source-code.

**Comment by 1337HaxorKiddie** [comment]
kk thx

**Comment by Usernamer** [comment]
You can also use key binds.

**Comment by 1337HaxorKiddie** [comment]
Yes, right.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
