### ISSUE TITLE
Font Bug in 2.3

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1943]
Under every Capitalized "S" and "O", there are strange pixels. The "S" has two of them, and the "O" has only one.

Proof: https://gyazo.com/8966b4cea380e6b23bb2bd742c9d215b (Zoom in too see better)

More Proof: https://gyazo.com/854d107a72b87922e74d21ba79af78d0
https://gyazo.com/84b05506715c35656fb489b708f30743

**Comment by Eyremba** [comment]
Similar issue #1933
