### ISSUE TITLE
Colors in spammer

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1944]
Plese allow spammer to use § in . commands
like .give

**Comment by linuxcodefire** [comment]
Sounds good!

**Comment by GlitchHead** [comment]
check out my 50 foot long command that i made!!!!! but i then realized that mojang sucks and in 1.8.8 servers you cant place down spawners unless your OP .-.
(gives chest with lots of spawner types)
``` .give chest 1 0 {display:{Name:"All Spawners"},BlockEntityTag:{Items:[{id:mob_spawner,Count:64,Slot:0,tag:{display:{Name:"EnderDragon Spawner"},BlockEntityTag:{EntityId:EnderDragon}}},{id:mob_spawner,Count:64,Slot:1,tag:{display:{Name:"Wither Spawner"},BlockEntityTag:{EntityId:WitherBoss}}},{id:mob_spawner,Count:64,Slot:2,tag:{display:{Name:"Giant Spawner"},BlockEntityTag:{EntityId:Giant}}},{id:mob_spawner,Count:64,Slot:3,tag:{display:{Name:"Creeper Spawner"},BlockEntityTag:{EntityId:Creeper}}},{id:mob_spawner,Count:64,Slot:4,tag:{display:{Name:"Wolf Spawner"},BlockEntityTag:{EntityId:Wolf}}},{id:mob_spawner,Count:64,Slot:5,tag:{display:{Name:"Iron Golem Spawner"},BlockEntityTag:{EntityId:VillagerGolem}}},{id:mob_spawner,Count:64,Slot:6,tag:{display:{Name:"TNT Spawner"},BlockEntityTag:{EntityId:PrimedTnt}}},{id:mob_spawner,Count:64,Slot:7,tag:{display:{Name:"EnderCrystal Spawner"},BlockEntityTag:{EntityId:EnderCrystal}}},{id:mob_spawner,Count:64,Slot:8,tag:{display:{Name:"Wither Skeleton Spawner"},BlockEntityTag:{EntityId:Skeleton,SpawnData:{SkeletonType:1}}}},{id:mob_spawner,Count:64,Slot:9,tag:{display:{Name:"Skeleton Spawner"},BlockEntityTag:{EntityId:Skeleton}}},{id:mob_spawner,Count:64,Slot:10,tag:{display:{Name:"Guardian Spawner"},BlockEntityTag:{EntityId:Guardian}}},{id:mob_spawner,Count:64,Slot:11,tag:{display:{Name:"Elder Guardian Spawner"},BlockEntityTag:{EntityId:Guardian,SpawnData:{Elder:1}}}},{id:mob_spawner,Count:64,Slot:12,tag:{display:{Name:"Villager Spawner"},BlockEntityTag:{EntityId:Villager}}},{id:mob_spawner,Count:64,Slot:13,tag:{display:{Name:"Zombie Spawner"},BlockEntityTag:{EntityId:Zombie}}},{id:mob_spawner,Count:64,Slot:14,tag:{display:{Name:"Zombie Pigman Spawner"},BlockEntityTag:{EntityId:PigZombie}}},{id:mob_spawner,Count:64,Slot:15,tag:{display:{Name:"Slime Spawner"},BlockEntityTag:{EntityId:Slime}}},{id:mob_spawner,Count:64,Slot:16,tag:{display:{Name:"Magma Cube Spawner"},BlockEntityTag:{EntityId:LavaSlime}}},{id:mob_spawner,Count:64,Slot:17,tag:{display:{Name:"Ghast Spawner"},BlockEntityTag:{EntityId:Ghast}}},{id:mob_spawner,Count:64,Slot:18,tag:{display:{Name:"Enderman Spawner"},BlockEntityTag:{EntityId:Enderman}}},{id:mob_spawner,Count:64,Slot:19,tag:{display:{Name:"Horse Spawner"},BlockEntityTag:{EntityId:EntityHorse}}},{id:mob_spawner,Count:64,Slot:20,tag:{display:{Name:"Sheep Spawner"},BlockEntityTag:{EntityId:Sheep}}},{id:mob_spawner,Count:64,Slot:21,tag:{display:{Name:"Ocelot Spawner"},BlockEntityTag:{EntityId:Ozelot}}},{id:mob_spawner,Count:64,Slot:22,tag:{display:{Name:"Rabbit Spawner"},BlockEntityTag:{EntityId:Rabbit}}},{id:mob_spawner,Count:64,Slot:23,tag:{display:{Name:"Pig Spawner"},BlockEntityTag:{EntityId:Pig}}},{id:mob_spawner,Count:64,Slot:24,tag:{display:{Name:"Sand Spawner"},BlockEntityTag:{EntityId:FallingSand,SpawnData:{Time:1}}}},{id:mob_spawner,Count:64,Slot:25,tag:{display:{Name:"Chicken Spawner"},BlockEntityTag:{EntityId:Chicken}}},{id:mob_spawner,Count:64,Slot:26,tag:{display:{Name:"Silverfish Spawner"},BlockEntityTag:{EntityId:Silverfish}}}]}} ```

**Comment by Alexander01998** [comment]
> Colors in spammer

Not possible. The server would kick you.

> Plese allow spammer to use § in . commands
> like .give

Duplicate: #1939
