### ISSUE TITLE
Lua hacks.

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1945]
A system were user can hack with lua like scripting but since it's lua it's more difficult to stop.

**Comment by awakened-game** [comment]
use forge, connect to a server with CC installed, done..... probably LEARN lua first.

**Comment by trollmad3** [comment]
Does anyone remember the *cough cough* virus from gmod? ah good times

(im talking about this beacuse its a lua virus)

**Comment by Alexander01998** [comment]
This isn't ComputerCraft.
