### ISSUE TITLE
.modify command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1946]
A command modify nbt data tags on current item (Creative)
.modify add {display:{Name:$4Name}}
.modify add {SkullOwner:Player}
.modify remove SkullOwner

**Comment by linuxcodefire** [comment]
Great idea!

**Comment by kim-yannick** [comment]
Nice, maybe I implement this soon.

**Comment by solidshadow96** [comment]
nice idea add it plz

**Comment by Usernamer** [comment]
If .give can do this, definitely you can do this with .modify.

**Comment by MyzticalTekkno** [comment]
>A command modify nbt data tags on current item (Creative)
.modify add {display:{Name:$4Name}}
.modify add {SkullOwner:Player}
.modify remove SkullOwner

Well .give feature now released & can give you stuff with NBT Tags but .modify is better i think.

**Comment by kim-yannick** [comment]
How should nested tags be handled? Using dots like in Java programming? Like `.modify remove display.Name`?

**Comment by Usernamer** [comment]
.give is limited anyways for NBT due to the character limit; another reason to add it. By the way, .modify should let you merge 2 lore NBT.

**Comment by MarvMarv** [comment]
There also could be a GUI for NBT editing. That you can see the NBT Tags from an Item and edit them. Like a normal JSON String editor. Just in Minecraft. I hope you know what I mean.

**Comment by Orcunegeacar** [comment]
@MarvMarv there is a .give command. If it is not enough, you can use Spammer for your NBT editing. Also GUI for NBT editing is a great idea :smile:

**Comment by MyzticalTekkno** [comment]
@Orcunegeacar True!

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
