### ISSUE TITLE
.title command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#1947]
Shows a title
.title times 10 10 10
.title title Title and
.title subtitle $4Colors

**Comment by linuxcodefire** [comment]
Isn't their already /title command?

**Comment by solidshadow96** [comment]
yea but that runns on single player and on servers if your op this command would run on only the players screen within the client

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
