### ISSUE TITLE
Scrape Feature!

### ISSUE THREAD

**Issue by SuperSushil** [Wurst-Imperium/Wurst-Client#1949]
So I got this feature , its a scraping feature where you scrape usernames from a server not like the whole server but the Players in the Mini game or lobby 
to use this scrape feature is .scrape and it saves to the wurst folder 
PS I am new to this GitHub so sorry if I did something wrong also I took inspiration from Weepcraft

**Comment by linuxcodefire** [comment]
Well I believe this was asked before but good luck.

**Comment by SuperSushil** [comment]
KK thanks

**Comment by pokeball99** [comment]
Dupe of..... um, @Gummiboat a little help?

**Comment by JackFishbaugh** [comment]
lol @pokeball99 .

When you need help finding,
A previous issue

Who you gonna call?

@Gummiboat!!!

**Comment by mcccs** [comment]
#278 ![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by linuxcodefire** [comment]
-.-

**Comment by PixelMaster3D** [comment]
Weepcraft has it. There's your confirmation. For issue #278
