### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.item.ItemCloth cannot be cast to net.minecraft.item.ItemArmor

### ISSUE THREAD

**Issue by WurstLeafeon** [Wurst-Imperium/Wurst-Client#195]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oops.

Time: 3/14/15 3:12 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.item.ItemCloth cannot be cast to net.minecraft.item.ItemArmor
	at tk.wurst_client.module.modules.AutoArmor.onUpdate(AutoArmor.java:66)
	at tk.wurst_client.event.EventManager.fireEvent(EventManager.java:36)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:140)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)
	at net.minecraft.world.World.updateEntities(World.java:1705)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2451)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1350)
	at net.minecraft.client.Minecraft.run(Minecraft.java:464)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.module.modules.AutoArmor.onUpdate(AutoArmor.java:66)
	at tk.wurst_client.event.EventManager.fireEvent(EventManager.java:36)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:140)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1887)
	at net.minecraft.world.World.updateEntity(World.java:1856)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 152586
	Entity Name: LeftClickLink
	Entity's Exact location: -2552.50, 52.00, 744.40
	Entity's Block location: -2553.00,52.00,744.00 - World: (-2553,52,744), Chunk: (at 7,3,8 in -160,46; contains blocks -2560,0,736 to -2545,255,751), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1705)

-- Affected level --
Details:
	Level name: MpServer
	All players: 61 total; [EntityPlayerSP['Player'/152586, l='MpServer', x=-2552.50, y=52.00, z=744.40], EntityOtherPlayerMP[''/-1, l='MpServer', x=-2519.50, y=54.00, z=741.50], EntityOtherPlayerMP[''/-2, l='MpServer', x=-2518.50, y=54.00, z=744.50], EntityOtherPlayerMP[''/-3, l='MpServer', x=-2519.50, y=54.00, z=747.50], EntityOtherPlayerMP['JTessarolo'/152482, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['justinansley2000'/144203, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['chappell13'/152011, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['Ulbesher9'/151830, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['jacky52815'/150778, l='MpServer', x=-2545.47, y=49.00, z=739.53], EntityOtherPlayerMP['jobodrengene'/151868, l='MpServer', x=-2544.03, y=49.00, z=747.28], EntityOtherPlayerMP['tjmacca'/152195, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['flyinchipmunk5'/151025, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['MrjjBlast'/146966, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['PCN10'/152078, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['Swaegger'/152585, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['PlaynoTheBerserk'/152584, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Mikolaj468'/152583, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['bashetmolletje'/152582, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Pokefan5'/152581, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Dratur'/152580, l='MpServer', x=-2552.50, y=50.31, z=744.38], EntityOtherPlayerMP['Sp4rt14tLTV'/152579, l='MpServer', x=-2551.59, y=50.00, z=743.97], EntityOtherPlayerMP['unreal_dino1'/152578, l='MpServer', x=-2552.50, y=50.75, z=744.38], EntityOtherPlayerMP['awesomevil'/152577, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['MrBizeps'/152576, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['JikkevBeek'/152502, l='MpServer', x=-2541.06, y=50.00, z=742.88], EntityOtherPlayerMP['Diik_Browne_'/152569, l='MpServer', x=-2538.69, y=50.00, z=748.84], EntityOtherPlayerMP['GrFranklin'/151865, l='MpServer', x=-2530.16, y=50.00, z=746.50], EntityOtherPlayerMP['JJJ3108'/152429, l='MpServer', x=-2538.44, y=50.00, z=745.31], EntityOtherPlayerMP['boendal2'/152219, l='MpServer', x=-2539.50, y=50.00, z=750.88], EntityOtherPlayerMP['Kylscrab'/152214, l='MpServer', x=-2530.00, y=50.00, z=744.06], EntityOtherPlayerMP['ChassyMan'/152303, l='MpServer', x=-2541.56, y=50.00, z=745.81], EntityOtherPlayerMP['MrAztul'/151792, l='MpServer', x=-2540.63, y=50.00, z=745.94], EntityOtherPlayerMP['Cloit'/145159, l='MpServer', x=-2534.25, y=52.84, z=754.66], EntityOtherPlayerMP['TheMagicEyeball'/151973, l='MpServer', x=-2539.59, y=50.00, z=753.53], EntityOtherPlayerMP['luddenord'/152575, l='MpServer', x=-2539.69, y=50.00, z=764.66], EntityOtherPlayerMP['deathattack10'/152393, l='MpServer', x=-2537.72, y=50.00, z=765.47], EntityOtherPlayerMP['Phinman25'/152223, l='MpServer', x=-2542.34, y=50.00, z=765.56], EntityOtherPlayerMP['toto3010'/152308, l='MpServer', x=-2541.28, y=50.00, z=757.78], EntityOtherPlayerMP['Shulk_SSB'/144822, l='MpServer', x=-2545.09, y=50.00, z=725.97], EntityOtherPlayerMP['aka'/152505, l='MpServer', x=-2542.19, y=50.00, z=722.41], EntityOtherPlayerMP['DamienJoey'/152509, l='MpServer', x=-2535.59, y=50.00, z=731.81], EntityOtherPlayerMP['DarkN974'/152496, l='MpServer', x=-2542.50, y=50.00, z=721.44], EntityOtherPlayerMP['samaniek'/152491, l='MpServer', x=-2536.25, y=50.00, z=735.59], EntityOtherPlayerMP['erik1808'/152488, l='MpServer', x=-2541.34, y=50.00, z=721.84], EntityOtherPlayerMP['sammy2910'/152489, l='MpServer', x=-2539.53, y=50.00, z=722.28], EntityOtherPlayerMP['Zozasus'/152494, l='MpServer', x=-2542.38, y=50.00, z=720.50], EntityOtherPlayerMP['2002MC2002'/152459, l='MpServer', x=-2539.94, y=50.00, z=731.13], EntityOtherPlayerMP['APACHE'/152571, l='MpServer', x=-2540.94, y=50.00, z=722.34], EntityOtherPlayerMP['S_Hosman'/152570, l='MpServer', x=-2540.31, y=50.00, z=721.28], EntityOtherPlayerMP['orchibald4ever'/152013, l='MpServer', x=-2534.09, y=50.00, z=729.53], EntityOtherPlayerMP['Smackdown707'/152002, l='MpServer', x=-2543.19, y=53.84, z=731.31], EntityOtherPlayerMP['paimon10'/152547, l='MpServer', x=-2540.63, y=51.00, z=720.53], EntityOtherPlayerMP['DarkBlate'/152536, l='MpServer', x=-2540.63, y=50.00, z=722.66], EntityOtherPlayerMP['OlolowStudios'/152142, l='MpServer', x=-2537.75, y=50.00, z=726.59], EntityOtherPlayerMP['storeposer'/147330, l='MpServer', x=-2550.66, y=51.00, z=773.28], EntityOtherPlayerMP['SladePT'/151242, l='MpServer', x=-2586.75, y=45.00, z=761.16], EntityOtherPlayerMP['BobbyGuard44'/152397, l='MpServer', x=-2546.94, y=51.00, z=718.59], EntityOtherPlayerMP['jackson123121'/152508, l='MpServer', x=-2542.50, y=62.81, z=717.03], EntityOtherPlayerMP['DarkShadowMo'/151716, l='MpServer', x=-2524.09, y=69.00, z=716.69], EntityOtherPlayerMP['TheMachintruc6'/152029, l='MpServer', x=-2509.50, y=79.47, z=746.53], EntityOtherPlayerMP['Implog'/143101, l='MpServer', x=-2630.50, y=96.00, z=728.28]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -2553.00,52.00,744.00 - World: (-2553,52,744), Chunk: (at 7,3,8 in -160,46; contains blocks -2560,0,736 to -2545,255,751), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Level time: 771009371 game time, 24000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 165 total; [EntityOtherPlayerMP[''/-1, l='MpServer', x=-2519.50, y=54.00, z=741.50], EntityOtherPlayerMP['unreal_dino1'/152578, l='MpServer', x=-2552.50, y=50.75, z=744.38], EntityOtherPlayerMP[''/-2, l='MpServer', x=-2518.50, y=54.00, z=744.50], EntityOtherPlayerMP['Sp4rt14tLTV'/152579, l='MpServer', x=-2551.59, y=50.00, z=743.97], EntityOtherPlayerMP[''/-3, l='MpServer', x=-2519.50, y=54.00, z=747.50], EntityOtherPlayerMP['MrBizeps'/152576, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['awesomevil'/152577, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['bashetmolletje'/152582, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Mikolaj468'/152583, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Cloit'/145159, l='MpServer', x=-2534.25, y=52.84, z=754.66], EntityOtherPlayerMP['Dratur'/152580, l='MpServer', x=-2552.50, y=50.31, z=744.38], EntityOtherPlayerMP['Pokefan5'/152581, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['PlaynoTheBerserk'/152584, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Swaegger'/152585, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['PCN10'/152078, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['Ulbesher9'/151830, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['MrjjBlast'/146966, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityArmorStand['Armor Stand'/30, l='MpServer', x=-2608.50, y=43.00, z=790.50], EntityArmorStand['Armor Stand'/31, l='MpServer', x=-2608.50, y=43.00, z=794.50], EntityArmorStand['Armor Stand'/32, l='MpServer', x=-2608.50, y=43.00, z=798.50], EntityOtherPlayerMP[''/-1, l='MpServer', x=-2519.50, y=54.00, z=741.50], EntityPlayerSP['LeftClickLink'/152586, l='MpServer', x=-2552.50, y=52.00, z=744.40], EntityOtherPlayerMP[''/-2, l='MpServer', x=-2518.50, y=54.00, z=744.50], EntityOtherPlayerMP[''/-3, l='MpServer', x=-2519.50, y=54.00, z=747.50], EntityArmorStand['Armor Stand'/56, l='MpServer', x=-2607.50, y=43.00, z=767.50], EntityArmorStand['Armor Stand'/57, l='MpServer', x=-2595.50, y=43.00, z=767.50], EntityArmorStand['Armor Stand'/58, l='MpServer', x=-2607.50, y=43.00, z=770.50], EntityOtherPlayerMP['GrFranklin'/151865, l='MpServer', x=-2530.16, y=50.00, z=746.50], EntityArmorStand['Armor Stand'/59, l='MpServer', x=-2607.50, y=43.00, z=776.50], EntityArmorStand['Armor Stand'/60, l='MpServer', x=-2607.50, y=43.00, z=773.50], EntityArmorStand['Armor Stand'/61, l='MpServer', x=-2607.50, y=43.00, z=779.50], EntityOtherPlayerMP['jobodrengene'/151868, l='MpServer', x=-2544.03, y=49.00, z=747.28], EntityArmorStand['Armor Stand'/62, l='MpServer', x=-2595.50, y=43.00, z=776.50], EntityArmorStand['Armor Stand'/63, l='MpServer', x=-2595.50, y=43.00, z=770.50], EntityArmorStand['Armor Stand'/64, l='MpServer', x=-2595.50, y=43.00, z=773.50], EntityArmorStand['Armor Stand'/65, l='MpServer', x=-2595.50, y=43.00, z=779.50], EntityArmorStand['Armor Stand'/66, l='MpServer', x=-2594.50, y=43.00, z=794.50], EntityArmorStand['Armor Stand'/67, l='MpServer', x=-2594.50, y=43.00, z=790.50], EntityOtherPlayerMP['Ulbesher9'/151830, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityArmorStand['Armor Stand'/68, l='MpServer', x=-2594.50, y=43.00, z=798.50], EntityOtherPlayerMP['chappell13'/152011, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['justinansley2000'/144203, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['JTessarolo'/152482, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['flyinchipmunk5'/151025, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['justinansley2000'/144203, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['tjmacca'/152195, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['jobodrengene'/151868, l='MpServer', x=-2544.03, y=49.00, z=747.28], EntityOtherPlayerMP['jacky52815'/150778, l='MpServer', x=-2545.47, y=49.00, z=739.53], EntityOtherPlayerMP['deathattack10'/152393, l='MpServer', x=-2537.72, y=50.00, z=765.47], EntityOtherPlayerMP['PlaynoTheBerserk'/152584, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['OlolowStudios'/152142, l='MpServer', x=-2537.75, y=50.00, z=726.59], EntityOtherPlayerMP['Swaegger'/152585, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['PCN10'/152078, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['MrjjBlast'/146966, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['BobbyGuard44'/152397, l='MpServer', x=-2546.94, y=51.00, z=718.59], EntityOtherPlayerMP['Dratur'/152580, l='MpServer', x=-2552.50, y=50.31, z=744.38], EntityOtherPlayerMP['Pokefan5'/152581, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['bashetmolletje'/152582, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['Mikolaj468'/152583, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['MrBizeps'/152576, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['awesomevil'/152577, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['unreal_dino1'/152578, l='MpServer', x=-2552.50, y=50.75, z=744.38], EntityOtherPlayerMP['Sp4rt14tLTV'/152579, l='MpServer', x=-2551.59, y=50.00, z=743.97], EntityOtherPlayerMP['Diik_Browne_'/152569, l='MpServer', x=-2538.69, y=50.00, z=748.84], EntityOtherPlayerMP['Katamari007'/152574, l='MpServer', x=-2532.16, y=50.00, z=745.56], EntityOtherPlayerMP['OukalhasHD'/152484, l='MpServer', x=-2530.50, y=50.00, z=747.69], EntityOtherPlayerMP['JikkevBeek'/152502, l='MpServer', x=-2541.06, y=50.00, z=742.88], EntityOtherPlayerMP['GrFranklin'/151865, l='MpServer', x=-2530.16, y=50.00, z=746.50], EntityOtherPlayerMP['boendal2'/152219, l='MpServer', x=-2539.50, y=50.00, z=750.88], EntityOtherPlayerMP['JJJ3108'/152429, l='MpServer', x=-2538.44, y=50.00, z=745.31], EntityOtherPlayerMP['Cloit'/145159, l='MpServer', x=-2534.25, y=52.84, z=754.66], EntityOtherPlayerMP['MrAztul'/151792, l='MpServer', x=-2540.63, y=50.00, z=745.94], EntityArmorStand['Armor Stand'/105, l='MpServer', x=-2566.44, y=50.25, z=730.69], EntityOtherPlayerMP['ChassyMan'/152303, l='MpServer', x=-2541.56, y=50.00, z=745.81], EntityArmorStand['Armor Stand'/106, l='MpServer', x=-2561.66, y=48.63, z=770.69], EntityOtherPlayerMP['Kylscrab'/152214, l='MpServer', x=-2530.00, y=50.00, z=744.06], EntityItemFrame['entity.ItemFrame.name'/107, l='MpServer', x=-2545.50, y=51.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/108, l='MpServer', x=-2544.50, y=54.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/109, l='MpServer', x=-2545.50, y=54.50, z=773.97], EntityOtherPlayerMP['luddenord'/152575, l='MpServer', x=-2539.69, y=50.00, z=764.66], EntityItemFrame['entity.ItemFrame.name'/110, l='MpServer', x=-2546.50, y=53.50, z=773.97], EntityOtherPlayerMP['JJJ3108'/152429, l='MpServer', x=-2538.44, y=50.00, z=745.31], EntityOtherPlayerMP['TheMagicEyeball'/151973, l='MpServer', x=-2539.59, y=50.00, z=753.53], EntityItemFrame['entity.ItemFrame.name'/111, l='MpServer', x=-2547.50, y=53.50, z=773.97], EntityOtherPlayerMP['deathattack10'/152393, l='MpServer', x=-2537.72, y=50.00, z=765.47], EntityItemFrame['entity.ItemFrame.name'/112, l='MpServer', x=-2548.50, y=53.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/113, l='MpServer', x=-2549.50, y=53.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/114, l='MpServer', x=-2550.50, y=53.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/115, l='MpServer', x=-2551.50, y=51.50, z=773.97], EntityOtherPlayerMP['Shulk_SSB'/144822, l='MpServer', x=-2545.09, y=50.00, z=725.97], EntityItemFrame['entity.ItemFrame.name'/116, l='MpServer', x=-2551.50, y=54.50, z=773.97], EntityItemFrame['entity.ItemFrame.name'/117, l='MpServer', x=-2552.50, y=54.50, z=773.97], EntityOtherPlayerMP['toto3010'/152308, l='MpServer', x=-2541.28, y=50.00, z=757.78], EntityItemFrame['entity.ItemFrame.name'/118, l='MpServer', x=-2553.50, y=54.50, z=773.97], EntityOtherPlayerMP['Phinman25'/152223, l='MpServer', x=-2542.34, y=50.00, z=765.56], EntityOtherPlayerMP['samaniek'/152491, l='MpServer', x=-2536.25, y=50.00, z=735.59], EntityItemFrame['entity.ItemFrame.name'/120, l='MpServer', x=-2543.50, y=54.50, z=773.97], EntityOtherPlayerMP['DarkN974'/152496, l='MpServer', x=-2542.50, y=50.00, z=721.44], EntityOtherPlayerMP['DamienJoey'/152509, l='MpServer', x=-2535.59, y=50.00, z=731.81], EntityOtherPlayerMP['aka'/152505, l='MpServer', x=-2542.19, y=50.00, z=722.41], EntityOtherPlayerMP['2002MC2002'/152459, l='MpServer', x=-2539.94, y=50.00, z=731.13], EntityOtherPlayerMP['Zozasus'/152494, l='MpServer', x=-2542.38, y=50.00, z=720.50], EntityOtherPlayerMP['sammy2910'/152489, l='MpServer', x=-2539.53, y=50.00, z=722.28], EntityOtherPlayerMP['erik1808'/152488, l='MpServer', x=-2541.34, y=50.00, z=721.84], EntityOtherPlayerMP['Smackdown707'/152002, l='MpServer', x=-2543.19, y=53.84, z=731.31], EntityOtherPlayerMP['storeposer'/147330, l='MpServer', x=-2550.66, y=51.00, z=773.28], EntityOtherPlayerMP['tjmacca'/152195, l='MpServer', x=-2552.50, y=52.00, z=744.38], EntityOtherPlayerMP['orchibald4ever'/152013, l='MpServer', x=-2534.09, y=50.00, z=729.53], EntityOtherPlayerMP['S_Hosman'/152570, l='MpServer', x=-2540.31, y=50.00, z=721.28], EntityOtherPlayerMP['APACHE'/152571, l='MpServer', x=-2540.94, y=50.00, z=722.34], EntityOtherPlayerMP['DarkBlate'/152536, l='MpServer', x=-2540.63, y=50.00, z=722.66], EntityOtherPlayerMP['paimon10'/152547, l='MpServer', x=-2540.63, y=51.00, z=720.53], EntityOtherPlayerMP['storeposer'/147330, l='MpServer', x=-2550.66, y=51.00, z=773.28], EntityOtherPlayerMP['2002MC2002'/152459, l='MpServer', x=-2539.94, y=50.00, z=731.13], EntityOtherPlayerMP['OlolowStudios'/152142, l='MpServer', x=-2537.75, y=50.00, z=726.59], EntityOtherPlayerMP['Kylscrab'/152214, l='MpServer', x=-2530.00, y=50.00, z=744.06], EntityOtherPlayerMP['BobbyGuard44'/152397, l='MpServer', x=-2546.94, y=51.00, z=718.59], EntityOtherPlayerMP['boendal2'/152219, l='MpServer', x=-2539.50, y=50.00, z=750.88], EntityOtherPlayerMP['SladePT'/151242, l='MpServer', x=-2586.75, y=45.00, z=761.16], EntityOtherPlayerMP['Phinman25'/152223, l='MpServer', x=-2542.34, y=50.00, z=765.56], EntityOtherPlayerMP['TheMachintruc6'/152029, l='MpServer', x=-2509.50, y=79.47, z=746.53], EntityOtherPlayerMP['DarkShadowMo'/151716, l='MpServer', x=-2524.09, y=69.00, z=716.69], EntityOtherPlayerMP['jackson123121'/152508, l='MpServer', x=-2542.50, y=62.81, z=717.03], EntityOtherPlayerMP['JTessarolo'/152482, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['DarkShadowMo'/151716, l='MpServer', x=-2524.09, y=69.00, z=716.69], EntityOtherPlayerMP['TheMagicEyeball'/151973, l='MpServer', x=-2539.59, y=50.00, z=753.53], EntityOtherPlayerMP['samaniek'/152491, l='MpServer', x=-2536.25, y=50.00, z=735.59], EntityOtherPlayerMP['erik1808'/152488, l='MpServer', x=-2541.34, y=50.00, z=721.84], EntityOtherPlayerMP['sammy2910'/152489, l='MpServer', x=-2539.53, y=50.00, z=722.28], EntityOtherPlayerMP['Zozasus'/152494, l='MpServer', x=-2542.38, y=50.00, z=720.50], EntityOtherPlayerMP['Implog'/143101, l='MpServer', x=-2630.50, y=96.00, z=728.28], EntityOtherPlayerMP['DarkN974'/152496, l='MpServer', x=-2542.50, y=50.00, z=721.44], EntityOtherPlayerMP['JikkevBeek'/152502, l='MpServer', x=-2541.06, y=50.00, z=742.88], EntityOtherPlayerMP['Shulk_SSB'/144822, l='MpServer', x=-2545.09, y=50.00, z=725.97], EntityOtherPlayerMP['aka'/152505, l='MpServer', x=-2542.19, y=50.00, z=722.41], EntityOtherPlayerMP['jackson123121'/152508, l='MpServer', x=-2542.50, y=62.81, z=717.03], EntityOtherPlayerMP['DamienJoey'/152509, l='MpServer', x=-2535.59, y=50.00, z=731.81], EntityOtherPlayerMP['Smackdown707'/152002, l='MpServer', x=-2543.19, y=53.84, z=731.31], EntityVillager['Villager'/196, l='MpServer', x=-2541.00, y=50.00, z=721.00], EntityOtherPlayerMP['SladePT'/151242, l='MpServer', x=-2586.75, y=45.00, z=761.16], EntityOtherPlayerMP['chappell13'/152011, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityVillager['Villager'/203, l='MpServer', x=-2538.00, y=50.00, z=766.00], EntityOtherPlayerMP['orchibald4ever'/152013, l='MpServer', x=-2534.09, y=50.00, z=729.53], EntityWither['§aCoupon §c§lWARLORDS§a for §e§l56%§a off ranks §estore.hypixel.net'/-1234, l='MpServer', x=-2519.50, y=52.01, z=744.38], EntityArmorStand['§e§lRIGHT CLICK'/210, l='MpServer', x=-2519.50, y=54.13, z=741.50], EntityArmorStand['§bMage'/211, l='MpServer', x=-2519.50, y=54.44, z=741.50], EntityArmorStand['§e§lRIGHT CLICK'/212, l='MpServer', x=-2518.50, y=54.13, z=744.50], EntityArmorStand['§bWarrior'/213, l='MpServer', x=-2518.50, y=54.44, z=744.50], EntityArmorStand['§e§lRIGHT CLICK'/214, l='MpServer', x=-2519.50, y=54.13, z=747.50], EntityArmorStand['§bPaladin'/215, l='MpServer', x=-2519.50, y=54.44, z=747.50], EntityVillager['Villager'/216, l='MpServer', x=-2538.50, y=50.00, z=739.50], EntityOtherPlayerMP['DarkBlate'/152536, l='MpServer', x=-2540.63, y=50.00, z=722.66], EntityVillager['Villager'/223, l='MpServer', x=-2538.50, y=50.00, z=749.50], EntityOtherPlayerMP['TheMachintruc6'/152029, l='MpServer', x=-2509.50, y=79.47, z=746.53], EntityOtherPlayerMP['paimon10'/152547, l='MpServer', x=-2540.63, y=51.00, z=720.53], EntityOtherPlayerMP['ChassyMan'/152303, l='MpServer', x=-2541.56, y=50.00, z=745.81], EntityOtherPlayerMP['MrAztul'/151792, l='MpServer', x=-2540.63, y=50.00, z=745.94], EntityOtherPlayerMP['flyinchipmunk5'/151025, l='MpServer', x=-2552.50, y=50.00, z=744.38], EntityOtherPlayerMP['toto3010'/152308, l='MpServer', x=-2541.28, y=50.00, z=757.78], EntityOtherPlayerMP['jacky52815'/150778, l='MpServer', x=-2545.47, y=49.00, z=739.53], EntityOtherPlayerMP['S_Hosman'/152570, l='MpServer', x=-2540.31, y=50.00, z=721.28], EntityOtherPlayerMP['APACHE'/152571, l='MpServer', x=-2540.94, y=50.00, z=722.34], EntityOtherPlayerMP['Diik_Browne_'/152569, l='MpServer', x=-2538.69, y=50.00, z=748.84], EntityOtherPlayerMP['luddenord'/152575, l='MpServer', x=-2539.69, y=50.00, z=764.66], EntityOtherPlayerMP['Implog'/143101, l='MpServer', x=-2630.50, y=96.00, z=728.28]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3006)
	at net.minecraft.client.Minecraft.run(Minecraft.java:486)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.8 (latest: 1.8)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105928384 bytes (101 MB) / 407015424 bytes (388 MB) up to 1559494656 bytes (1487 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1500M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8610G GL version 4.3.12618 Compatibility Profile Context 13.251.9001.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [Test]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by WurstLeafeon** [comment]
Due to this I am unable to join Warlords on Hypixel.

**Comment by Alexander01998** [comment]
Duplicate: #180
