### ISSUE TITLE
some worng for regen

### ISSUE THREAD

**Issue by snsnhacker** [Wurst-Imperium/Wurst-Client#1950]
hi Alexander the Wurst-Client There are some problems for Regen When I try to fly to  I make sure that a successful experiment I saw that blood when they fall and decreases blood can back again quickly and this is a very good thing, but when I tried that I try this experiment again noted that the blood level began to decline and can not return of blood like what I thought tried to fix the problem and try to do the Setting to do Regine high or low level such as what you have done for (arena brawl level) and (fast break speed) and (flight speed) and (kaboom power) and (kill aura speed) (and pls do regen level) and I hope that helped you to fix regen Thank you :)

**Comment by Eyremba** [comment]
This is hard to read, but it seems to that you want a switch for the regen-speed like speedmine-speed and fly-speed.

Nice idea, maybe also with ".regenpackets" where you can switch how many packets regen should use.

**Comment by snsnhacker** [comment]
Thank you very much Eyremba but I don't know exactly how many packets
Thank you for comment :)

**Comment by EnderGamer21** [comment]
i hope alexander checks this

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
