### ISSUE TITLE
Make other people invisble

### ISSUE THREAD

**Issue by Spassvogelw** [Wurst-Imperium/Wurst-Client#1952]
I would like a setting to make other minecraft players invisible.
This would be useful if you are on a server trying a parcour, but there are so many players that you cant see any stone. Also it is useful if there are many people on the server and it is lagging or something similar.

**Comment by TheIonosphere** [comment]
Also a natural extension of this idea would be disabling mobs and other types of entity.

**Comment by OMGchangeMYusername** [comment]
Oh this is duplicate #593

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
