### ISSUE TITLE
Queston:i got Banned From Mineplex for perament what do i do?

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#1956]
Title says it all

**Comment by trollmad3** [comment]
Get a alt

**Comment by pokeball99** [comment]
1.use a alt or sessionid if you weren't ip ban
2.if you were ip ban,then....idk,use a vpn? Idk if this will work for mc but try https://www.betternet.co/ it's a truly free vpn,use it on my phone all the time,works for Windows and what not

**Comment by EnderGamer21** [comment]
what does ip ban mean

**Comment by EnderGamer21** [comment]
its not my computer someone banned me for hacking in regen i got hit 7 times and still lived

**Comment by solidshadow96** [comment]
It means any computer connected to your internet will not be allowed onto the server. try using somthing called ghost ip changer and it will change your ip to some where else so you can rejoin.
if that does not work than it means you are player ban and you would to create an alt

**Comment by GlitchHead** [comment]
This is not a forum. (I know this is a question but it does not have to do with the wurst client)

**Comment by EnderGamer21** [comment]
8if i create a alt it would not ley e join so  can someone give me  a session id of someone plz

**Comment by MyzticalTekkno** [comment]
>Title says it all

**Comment by JackFishbaugh** [comment]
@EnderGamer21 Here are some alts for you. And Mineplex doesn't ip ban. But if you ever got ip banned from any server, use this http://www.cyberghostvpn.com/. If will spoof your ip and works with Mojang's auth servers. Most of the alts are muted. But if you ever get your account back, tell Mineplex to go fuck themselves. If you want to hack on Mineplex, https://www.youtube.com/watch?v=pZ5n4nwLIEQ watch that. If you want more alts, or if you need help, add my skype fishballs.alts :).

kittywallbridge@gmail.com:gracew27
kendrickk74@yahoo.com:Jeremia7
junkmail70@comcast.net:HWG9tbK9av
josephharrysmall@gmail.com:TRUSTNO1
jzet72@gmail.com:nomad123
jooothegreat@gmail.com:emma2001
joshua@lamoulton.org:moulton88
john.kast@sbcglobal.net:butter2020
keith.macadangdang@yahoo.com:popup808
joshuahernandez756@outlook.com:joshkills756

**Comment by MyzticalTekkno** [comment]
@JackFishBaugh
4 Working 6 Not Working
Thanks for sharing btw,
Dont share in public, mojang is aware of public shared minecraft accounts.

**Comment by JackFishbaugh** [comment]
Its ok. Mojang's new system gets rid of alts really quick. it wont matter too much.

reecearony@yahoo.com:warchol4
jtandtt@shaw.ca:5tt062
kirby.kho@gmail.com:creeper1
ferreradria@yahoo.com:jhonatan28
Joshjohnston@live.com.au:3/05/2003
rhysjolly87@gmail.com:rhys2006

6 more that work to replace not working ones

**Comment by MyzticalTekkno** [comment]
@JackFishbaugh Nice! Thanks for sharing

**Comment by JackFishbaugh** [comment]
@MyzticalTekkno np!

**Comment by MyzticalTekkno** [comment]
@JackFishbaugh how do you get those alts by the way?

**Comment by JackFishbaugh** [comment]
@MyzticalTekkno places...




fishballs.shop on skype

**Comment by MyzticalTekkno** [comment]
@JackFishbaugh okay, i have places too to get alts XD

**Comment by MyzticalTekkno** [comment]
15 Places

**Comment by JackFishbaugh** [comment]
xD

**Comment by MyzticalTekkno** [comment]
i Found 3 Places thats new XD lucky

**Comment by linuxcodefire** [comment]
Skype styuff

**Comment by EnderGamer21** [comment]
CyberGhost works i have a question its not about wurst but i went to a site called MInelplex Upgrades is that a real site or a scam site Because it tells u can get ranks uf u enter ur pazword and username btw im a kid

**Comment by JackFishbaugh** [comment]
@EnderGamer21 lololol. I want you to think long and hard about that one.

**Comment by MyzticalTekkno** [comment]
@EnderGamer21 You Can't Thats just a trick bro, the website owner just trick people, steal your accounts/alts and sell them to people, and it's a total lie, why? minecraft server have tri-force protection system (depends on their hosting provider) and MOD / ADMIN Can't rankup people to any ranks they want, Mineplex is hard to hack, especially that rank hack.

**Comment by mcccs** [comment]
go to http://mineplex.com/appeals

**Comment by EnderGamer21** [comment]
@mcccs  they lowerd my days of being banned for 39 days i wikll go on lobbys that dosent have moderators

**Comment by trollmad3** [comment]
@EnderGamer21  Do you have steam beacuse i want to add you beacuse we can grief together

**Comment by EnderGamer21** [comment]
Yes  trollmad3

**Comment by PixelMaster3D** [comment]
Can you still bypass mineplex custom source if you have the source?

**Comment by PixelMaster3D** [comment]
Like examining it for a bypass.

**Comment by trollmad3** [comment]
@EnderGamer21 my username is http://steamcommunity.com/id/therealevilotto/ add me plez

**Comment by JackFishbaugh** [comment]
@PixelMaster3D yes you can bypass their ncp and their custom MAC. if you want i can teach you

**Comment by MyzticalTekkno** [comment]
@JackFishBaugh, but if they use Paramount, you are dead and banned.

**Comment by trollmad3** [comment]
@EnderGamer21 my username is http://steamcommunity.com/id/therealevilotto/ add me plez

**Comment by EnderGamer21** [comment]
im a kid i dont have 5 dollars to pay to get i started 3 days ago with steam

**Comment by BoomBoomLHack** [comment]
@EnderGamer21 ask you parent ._.

**Comment by Eyremba** [comment]
Dudes stop talking off-topic or all of you will be banned from this repository!

**Comment by JackFishbaugh** [comment]
@Eyremba ?

**Comment by Creeperman8362** [comment]
looks like u forgot to use a vpn while sesionstealing somebody on mineplex, or you posted ur sessionid.

**Comment by trollmad3** [comment]
@EnderGamer21 whats ur steam name ill add you

**Comment by Eyremba** [comment]
@trollmad3 you are still off-topic, @Alexander01998 said it often enough that this is NOT a forum.

**Comment by trollmad3** [comment]
@Eyremba Shut up already i just want to add @EnderGamer21 on steam so i can grief with him

**Comment by Eyremba** [comment]
@trollmad3 watch your language or @Alexander01998 bans you faster than you can see. You can also make a conversation with him over his profile!

**Comment by EnderGamer21** [comment]
@trollmad3  i cant because im updating steam and i have to pay 5$ and i dont have but il tell when my Steam finishes updating

**Comment by trollmad3** [comment]
@Eyremba  thug life

**Comment by Eyremba** [comment]
@trollmad3 be careful or you will have a "jail life" :)

**Comment by trollmad3** [comment]
@Eyremba oh sure...wow i can go to jail for saying thug life

**Comment by Eyremba** [comment]
Hopefully @Alexander01998 will close this issue where all is nursery school behaviour of some retarded kids here.

**Comment by EnderGamer21** [comment]
@trollmad3  my username is GamingGamer122

**Comment by trollmad3** [comment]
@EnderGamer21 can i have your steam url its not showing up :

**Comment by EnderGamer21** [comment]
How do i do that

**Comment by EnderGamer21** [comment]
how do i get a stream url

**Comment by EnderGamer21** [comment]
Steam is not working it keeps deleting itself il tell u the url oncce i find out how to fix it

**Comment by trollmad3** [comment]
@EnderGamer21 http://steamcommunity.com/id/therealevilotto sign in on the browser and add me on there

**Comment by Creeperman8362** [comment]
@Eyremba "Shut up" is not bad language.

**Comment by EnderGamer21** [comment]
wheni type in my url it says bad length please give me a id @trollmad3

**Comment by EnderGamer21** [comment]
My url is http://steamcommunity.com/id/

**Comment by Eyremba** [comment]
@paris-ci yes. That's the reason why @Alexander01998 should close this off-topic trash..
