### ISSUE TITLE
Add text about session stealer in readme.md?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#1957]
Title says all

**Comment by linuxcodefire** [comment]
Don't do that "title says all" just copy it again.

**Comment by solidshadow96** [comment]
Please leave more information where the information box is located. please do not say title says it all or your suggestion will not be taken onto account

**Comment by awakened-game** [comment]
@solidshadow96 Your english is terrible.

**Comment by GlitchHead** [comment]
@awakened-game That was unnecessary.

**Comment by solidshadow96** [comment]
@awakened-game dude no need to be a buzz kill if ur gonna be one just leave bro
