### ISSUE TITLE
How to edit in Eclipse?

### ISSUE THREAD

**Issue by Aboose** [Wurst-Imperium/Wurst-Client#1958]
I'm quite new to Java but understand the basics. I was wondering how you would go about getting it into Eclipse?

**Comment by solidshadow96** [comment]
i duno man Why are you asking this on the wurst forums. are you wondering on how to right eclipse into wspam cuz if so wspam doesnt run on eclipse or at least i dont belive it does.

also just a question wspam runs of java right???

**Comment by solidshadow96** [comment]
like normal notepad stuff?

**Comment by awakened-game** [comment]
https://www.wurst-client.tk/wiki/Tutorials/How-to-Debug-Wurst-In-Eclipse/
