### ISSUE TITLE
Bring back the old blink! (it makes you think that your lagging)

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1959]
I really miss the old blink it makes pvping a lot easyer

i really want it back please bring it back

**Comment by 1337HaxorKiddie** [comment]
Blink got replaced?

**Comment by ravenje** [comment]
I hope fullblink will be added soon

**Comment by OMGchangeMYusername** [comment]
It never worked to begin with.
and you can make a spammer script that enables & disables Blink every three seconds.

**Comment by Eyremba** [comment]
Yes @ravenje I hope too that FullBlink will be added soon. It is sooo nice :D You can shoot an arrow with your bow around a corner with it. :D

**Comment by jtrent238** [comment]
what is blink?

**Comment by 1337HaxorKiddie** [comment]
If Enabled Blink will send no Movement packets to the Server. For other players it looks like your lagging, because if you have a Bad pi g the same Thing happens.

**Comment by awakened-game** [comment]
hmm, i didnt know blink was gone, its still assigned to my B key

**Comment by Artamiel** [comment]
its not gone its still here it was improved from the better one. I was and still am able to get to different islands in Mineplex in Bridges by using blink before bridges fall, usually without getting kicked.

**Comment by Artamiel** [comment]
also trollmad3 the new blink still helps with pvp.
