### ISSUE TITLE
Application - SPECIAL REQUEST!

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#196]
Hello Alexander01998. I wanna create an application for Wurst. I'm going to do that on Visual Studio 2013 Desktop. I'm gonna write in C#. In this (my thinks) you can convert keybinds,automatic install "Wurst" Hacked Client,Show random servers to hack (weak servers),Wurst News,Editable mods (like
enchantment level 127 to 45 or 165),Special Launcher for Wurst (Just Wurst),A web browser to https://www.wurst-client.tk ,Auto Updater for Wurst versions. Please Confirm my idea. If you say yes I'm going to start this project. All credits is yours...

**Comment by GlitchHead** [comment]
o_o

**Comment by Orcunegeacar** [comment]
I know. When I'm writing this I was saying. "It's gonna be huge project for Wurst" but it's not. You can do that too. Just you need to know a programming language and java

**Comment by Alexander01998** [comment]
Confirmed.

In terms of credits, I highly recommend you to read the [License](https://www.mozilla.org/MPL/2.0/) so that you know your rights and obligations.

**Comment by Orcunegeacar** [comment]
![image](https://cloud.githubusercontent.com/assets/11218527/6651968/11846fd4-ca66-11e4-9622-3ade4458de20.png) I started. Is it good?

**Comment by Alexander01998** [comment]
> I started. Is it good?

If you want it to look like the original loading screen, the background color should be `#202020`.

**Comment by Orcunegeacar** [comment]
I'm going to try to add it.

**Comment by Orcunegeacar** [comment]
![image](https://cloud.githubusercontent.com/assets/11218527/6652087/331a2d74-ca6a-11e4-827d-e9606a2fc570.png) I added these buttons. And they work well. And When you press the Wurst's Logo,it's gonna open Wurst Client.

**Comment by Orcunegeacar** [comment]
What should I add next?

**Comment by Orcunegeacar** [comment]
@Alexander01998 Uhh.. I guess Wurst News button doesn't open. I tried a lot. Need a help little here. How did you add Wurst News in Minecraft when I open it. It's in the ground. Like this. I need a code to open it in messagebox. If it doesn't work  I need to open it from WebBrowser

**Comment by Alexander01998** [comment]
> @Alexander01998 Uhh.. I guess Wurst News button doesn't open. I tried a lot. Need a help little here. How did you add Wurst News in Minecraft when I open it. It's in the ground. Like this. I need a code to open it in messagebox. If it doesn't work I need to open it from WebBrowser

Just look at the code, it's all there. It basically reads the RSS feed and then displays the headlines.

**Comment by Orcunegeacar** [comment]
I'm working hard for it. I'm not writing this in java. I'm writing c#. When the alpha version finished. I'm gonna post a video to youtube. and give a link to you. ok?

**Comment by Alexander01998** [comment]
See Orcunegeacar/Wurst-App#1.

**Comment by Orcunegeacar** [comment]
Ok

**Comment by Orcunegeacar** [comment]
Wurst App failed because it was really hard for me. I'm thinking.... what about a extension for DreamBrowser (https://github.com/Orcunegeacar/Dream-Browser) When you're surfing in the internet. You can launch the wurst with a button. Maybe Open The Wurt's github online page and news.. Like that. I can do that. I'm going to share it Wurst-App like a extension. The Users are going to copy it to dream browser's extensions place. Than BOOOM. The Special App-Extension for Wurst.

**Comment by Orcunegeacar** [comment]
There is still no button for extensions. But I'm going to add it to Settings form.

**Comment by Orcunegeacar** [comment]
I'm going to add a theme for dream browser too.

**Comment by Orcunegeacar** [comment]
@Alexander01998

**Comment by GlitchHead** [comment]
o_o

**Comment by pokeball99** [comment]
any progress on this?
