### ISSUE TITLE
Session ID grabber

### ISSUE THREAD

**Issue by wizardhax** [Wurst-Imperium/Wurst-Client#1961]
Is it possible to get someones session ID from the server? Instead from them telling you it?

**Comment by solidshadow96** [comment]
i dont think so

**Comment by linuxcodefire** [comment]
Impossible already tried. Based on uuid string encryption...

**Comment by MyzticalTekkno** [comment]
Totally Impossible...

**Comment by solidshadow96** [comment]
not totally but there would at least have to be a way to have access to their computer.

**Comment by solidshadow96** [comment]
i might even get started on a virus that steals there session code and sends it back to the owner through skype

**Comment by pokeball99** [comment]
Or just make a client that gives the sessionid's to the owners website....

**Comment by linuxcodefire** [comment]
But if I ever figure it out ill share it.

**Comment by solidshadow96** [comment]
Can someone send me the directory to the session id note i cant seem to find it im on windows 8

**Comment by MyzticalTekkno** [comment]
@solidshadow96 i don't know how to find it on server logs, but you can find it from Minecraft Launcher Game Output, that should help you with the directory.

**Comment by Alexander01998** [comment]
> Can someone send me the directory to the session id note i cant seem to find it im on windows 8

`.minecraft/logs/`
