### ISSUE TITLE
Suggeting to Add Noweather

### ISSUE THREAD

**Issue by Elephantlovr33X** [Wurst-Imperium/Wurst-Client#1962]
Hello! 
I am suggesting To add Noweather.
Noweather is for the Player wont see the weather, like rain or Snow, It will see the clouds but No Rain or snow. 
This Could Be usefull For players (such as me) That Lag a lot. And Sometimes Rain/snow Make some Players Lag. Also Sometimes Rain Or snow can get in the way of People who are Pvping, it might distract them. If You could add this, that would be Awesome!
Thanks :D

**Comment by tonyawojo** [comment]
Good idea

**Comment by solidshadow96** [comment]
yep plz add it

**Comment by OMGchangeMYusername** [comment]
Duplicate #256.
For the sake of your dead grandpa look for old similar issues next time.

**Comment by linuxcodefire** [comment]
New time...

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
