### ISSUE TITLE
FriendlyFire

### ISSUE THREAD

**Issue by JackFishbaugh** [Wurst-Imperium/Wurst-Client#1963]
A mod that tells Wurst not to attack certain players based on what color name tag they have.

Ex: You are on blue team. Wurst sees that you have a blue name tag, and so it knows not to attack everyone with the same color name tag.

Yes, I am aware that you can just type ```.friends add <username>```, or middle click someone to keep Wurst from attacking them. But that is only meant for permanent friends that you never want to attack, ever. In most servers, teams change every single round, and trying to run around and find out who is on your team so you can middle click them, is a hassle big waste of time. (After all, kids can't stand still to let you middle click them)

An addition to this mod would be the option to use dyed armour instead of name tags. This would only be an option if it is useful for the circumstances.

**Comment by solidshadow96** [comment]
Very true and a good feature. cant it just testfor a blue player name and it auto add it to friends list then delete them?

**Comment by JackFishbaugh** [comment]
I don't know if it would be a good idea to bring this in with ```.friends```. It might get implemented in the wrong way.

**Comment by mcccs** [comment]
#112 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by JackFishbaugh** [comment]
I did search. But I didnt find anything..

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues

**Comment by JackFishbaugh** [comment]
@pokeball99 github needs to add moderators.
