### ISSUE TITLE
Items on Freecam Bug

### ISSUE THREAD

**Issue by SecretGamer123** [Wurst-Imperium/Wurst-Client#1964]
All dropped items are shaking when you enter Freecam
![2015-08-23_14 15 07](https://cloud.githubusercontent.com/assets/13926319/9427190/8218f886-49a1-11e5-9eab-f5645608acb7.png)
![2015-08-23_14 15 06](https://cloud.githubusercontent.com/assets/13926319/9427191/8221b002-49a1-11e5-91a3-2cfaf8735c7f.png)
![2015-08-23_14 15 06_2](https://cloud.githubusercontent.com/assets/13926319/9427192/8223272a-49a1-11e5-9b45-1ee06dfcb91b.png)

**Comment by linuxcodefire** [comment]
Good bug.

**Comment by Orcunegeacar** [comment]
So? It's not important

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
