### ISSUE TITLE
Items on Freecam Bug 

### ISSUE THREAD

**Issue by SecretGamer123** [Wurst-Imperium/Wurst-Client#1965]
Items are shaking when you enter Freecam
![2015-08-23_14 15 07](https://cloud.githubusercontent.com/assets/13926319/9427200/032a7616-49a2-11e5-838d-bc044a1b4977.png)
![2015-08-23_14 15 06](https://cloud.githubusercontent.com/assets/13926319/9427201/047d9174-49a2-11e5-8a81-bee9c81bd130.png)
![Uploading 2015-08-23_14.15.06_2.png…]()

**Comment by MyzticalTekkno** [comment]
Duplicate #1964 
https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png

**Comment by labcraft59** [comment]
You posted 2 of the exact same. #1964 was also yours...
