### ISSUE TITLE
[Proxy] Lost Connection To The Server

### ISSUE THREAD

**Issue by MangoAssassin** [Wurst-Imperium/Wurst-Client#1966]
Whenever I have wurst enabled and try to join a server, it joins for a second and then disconnects me giving me the error stated above.

**Comment by linuxcodefire** [comment]
Is it a kick message or error screen? Because proxy could be blocked by server.

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire a proxy is a ip and Minecraft supports ip-bans.

**Comment by linuxcodefire** [comment]
Their are plugins to stop proxies though. Try change proxy to different kind or type.

**Comment by MangoAssassin** [comment]
Im not using a proxy though

**Comment by linuxcodefire** [comment]
Restart minecraft.

**Comment by BoomBoomLHack** [comment]
Bungeecord error maybe?

**Comment by Creeperman8362** [comment]
try disabling nuker.

**Comment by MangoAssassin** [comment]
Thanks Creeperman8362, that worked.
