### ISSUE TITLE
Feature request: OptiFine and templates

### ISSUE THREAD

**Issue by Lunofe1509** [Wurst-Imperium/Wurst-Client#1968]
1. Wurst would have much more FPS and less laggs, so why not putting OptiFine in it :D?

2. what about a feature, that let the user save actived hacks to a text file, which can be loaded again, that the user dont have to activate again all hacks?

Sorry if I put this in the wrong caption or anyone other requested this before. Totally new to Github and co.

**Comment by WurstContributor** [comment]
INVALID + DUPE #2
