### ISSUE TITLE
/op xXD7ooMYxCraftXx

### ISSUE THREAD

**Issue by xXD7ooMYxCraftXx** [Wurst-Imperium/Wurst-Client#197]

**Comment by OMGchangeMYusername** [comment]
ههههههههههههه عربي صح؟

sorry he must've misunderstood the way this works xD
i don't know him personally but i knew from his name.

**Comment by GlitchHead** [comment]
صحيح

**Comment by OMGchangeMYusername** [comment]
lol the good old google?
