### ISSUE TITLE
.whois

### ISSUE THREAD

**Issue by NinjaYouBro** [Wurst-Imperium/Wurst-Client#1970]
A command that can get other player's ip address would be great. You can get a player's ip with /whois but only admins have permission so you would probably have to do something with that.

**Comment by RaizeWormwood** [comment]
It should be possible to do this, after all, to my belief, you are on the same server so in a way you would be able to view people's ip addresses that are on the same server as you. Mark me if I am wrong.

**Comment by Orcunegeacar** [comment]
Yeah. It'll be good and workable but... Why do you need it?

**Comment by NinjaYouBro** [comment]
Check if people are using an alt on the same ip to catch people.

**Comment by solidshadow96** [comment]
There is a website that is ment for ddosing but dont use it for that there is a think called skype resolver and it tells you the ip of the person based on their skype

**Comment by solidshadow96** [comment]
its called vboot

www.vbooter.org

**Comment by linuxcodefire** [comment]
Illegal!

**Comment by GlitchHead** [comment]
As of right now there is no current way to resolve a players ip from there username.

**Comment by WurstContributor** [comment]
Duplicate

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues

**Comment by WurstContributor** [comment]
@pokeball99 WE GET THE MESSAGE.
