### ISSUE TITLE
Killaura Configuration

### ISSUE THREAD

**Issue by RaizeWormwood** [Wurst-Imperium/Wurst-Client#1971]
Ah yes, I do not believe this has been talked about yet, but Killaura does not have any configurations other than the "Target" option. I believe there should be a small area in which you can configure these mods to your liking.

For example you could configure the distance of which KillAura attempts to attack enemies, aswell as tell Wurst what enemies to attack over others. 

Say you want to attack a player, and also a zombie. Killaura normally notices the zombie closest and will start attacking it instead of the player. What we could instead do, is set the player to a higher priority than other creatures, and when the player is killed or out of reasonable range, killaura will attack the zombie. (Or other mob)

".killaura priority set (Player, Hostile, Passive, Neutral)" would be the command version.

".killaura range set (Range increment of a block. 0.1, 0.2, 0.3...)

Aswell as different commands and sub-commands for Killaura and possibly Multiaura.

**Comment by linuxcodefire** [comment]
:O

**Comment by OMGchangeMYusername** [comment]
> Say you want to attack a player, and also a zombie. Killaura normally notices the zombie closest and will start attacking it instead of the player. What we could instead do, is set the player to a higher priority than other creatures, and when the player is killed or out of reasonable range, killaura will attack the zombie. (Or other mob)
> 
> ".killaura priority set (Player, Hostile, Passive, Neutral)" would be the command version.

I agree to this; Killaura priority is pretty neat. But I don't seem to understand what you meant by "range".. We do have an option in the settings "Killaura range" and you can set it to what you want.

**Comment by PixelMaster3D** [comment]
Target priority range. Who to kill first? Mob or player? Let's see who a big threat.

**Comment by PixelMaster3D** [comment]
Defining target priority no matter if a zombie is close to you but will revert to certain distance.

**Comment by Eyremba** [comment]
@PixelMaster3D on another client, you can set as "Kill-Priority" of the Killaura on strongest (strongest equipped player), mouse (nearest to your mouse), closest to you etc, and much more.

**Comment by PixelMaster3D** [comment]
ik.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
