### ISSUE TITLE
Wurst doesn't bypass Paramount (Anti Cheat System) ?

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#1972]
Paramount is a anti cheating system like NoCheatPlus. Paramount created by Sir java. I just watched this video ( https://www.youtube.com/watch?v=r_IAxkQi_Z4 ) and Wurst's Killaura system seems doesn't work. Actually we don't need to break paramount now. It's not completed yet and all servers is still using NCP right now. But If paramount disables all hacked client's cheats (Killaura,Speed,Regen,Flight etc.)?  (I don't think Server owners will use paramount but We need to bypass this thing.)

(Paramount's anti cheat system on hacked clients)
Wurst by @Alexander01998 :https://www.youtube.com/watch?v=r_IAxkQi_Z4
Huzuni:https://www.youtube.com/watch?v=t7K5XwcUG_c
Wolfram:https://www.youtube.com/watch?v=_Aaxrrb1jxc
Metro:https://www.youtube.com/watch?v=l5EJBXMj6yU
Xenon:https://www.youtube.com/watch?v=kpVOq6z524A

We don't have the source code of Paramount now but when it relased. It will be so hard to break this 'AntiCheatSystem'.

You can watch the Saint vs. Paramount. (Detailed) 
https://www.youtube.com/watch?v=p6d3GVWZw3c

**Comment by Orcunegeacar** [comment]
This Plugin also gives messages to console panel (server owners') and they can see who is cheating. :disappointed:

**Comment by solidshadow96** [comment]
Wow i cant belive it actually stops it

**Comment by pokeball99** [comment]
Well,a hack client maker would know how to stop there own hacks,plus with all the clients being deofcated and what not is making it easier for them to patch this crap,
Aka,time for a complete from scratch rework of wurst

**Comment by mcccs** [comment]
Actually, Paramount is Viacom's movie company.

**Comment by mcccs** [comment]
Found something! Paramount summons invisible entities! Killaura Legit should not attack them!

**Comment by Orcunegeacar** [comment]
I believe Wurst can bypass 'Paramount' in the future. Actually Paramount only stops original and classic hacks.

**Comment by Orcunegeacar** [comment]
You can see this article in this forum. It writed by Sir java (creator of nodus client)

https://www.spigotmc.org/threads/wip-paramount-most-powerful-anticheat-system-ever-made.85100/

**Comment by Alexander01998** [comment]
Paramount won't succeed, no need to worry about it.

I've seen so many of these seemingly perfect anti hack plugins that ended up getting abandoned after just a few weeks, before even being finished or being used anywhere.

**Comment by Orcunegeacar** [comment]
You are right. All Server owners will not trust a 'hacked client maker'. So they will still use NCP. Classic one :smile:
