### ISSUE TITLE
Auto-Complete

### ISSUE THREAD

**Issue by Usernamer** [Wurst-Imperium/Wurst-Client#1974]
When I am typing commands, it should be easier for me to find out what to put next. For example, .potion would auto-complete as .potion [add/remove] [all name status effects] and you would put everything else. For example, all the numeric things wouldn't autocomplete.

**Comment by linuxcodefire** [comment]
like pressing TAB to finish? (the line)

**Comment by OMGchangeMYusername** [comment]
This is basically what #1531 will do, most likely. I'm not sure because Alexander didn't say what he would implement of the ideas in that issue.

**Comment by PixelMaster3D** [comment]
Like that just without the console.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
