### ISSUE TITLE
Better TrueSight

### ISSUE THREAD

**Issue by Usernamer** [Wurst-Imperium/Wurst-Client#1975]
Sometimes, it'd be nice to have TrueSight without opacity, and it would also show the player's usernames. It could also only show a certain type of mob, so it wouldn't show chunk-loading mobs or armor stands. It could change like this:

.truesight opacity [0-100%]
.truesight names [on/off]
.truesight targets list
.truesight targets add [mobname/hostile/passive/players/armorstands]
.truesight targets remove [mobname/hostile/passive/players/armorstands]

**Comment by linuxcodefire** [comment]
well good idea?

**Comment by MyzticalTekkno** [comment]
Use ESP, that should work

**Comment by awakened-game** [comment]
i think it would be great if we could see players in vanish mode, unless its using packet type vanish, that would be impossibe, you can still hear MOST players in vanish though, because in factions the staff always break things and open things in my bases, i can hear them

**Comment by MyzticalTekkno** [comment]
>because in factions the staff always break things and open things in my bases

@awakened-game that means the staff is thinking that you're hacking, or item duplicating, 

>because in factions the staff always break things

well it is faction aspect that staff / people always break things in your bases/raid.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
