### ISSUE TITLE
fake lag mod.

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#1976]
Cause client lots of lag to help trick owner into restarting server or trying to fix it.

**Comment by MyzticalTekkno** [comment]
I Think thats impossible, but you can use blink so you can fakely lagged.

**Comment by awakened-game** [comment]
easy, connect through Tor, that will slow it down, a lot

**Comment by trollmad3** [comment]
@awakened-game Do you have steam and if you do can i add you please?

**Comment by awakened-game** [comment]
i do but i dont use it, well rarely at least, i hate the fact you buy an empty disc in a store, then have to download it, so the game costs maybe $80, then the data charges to download it probably reach the thousands, i pay $15 per GB, mortal kombat x is like 30 something GB, so $450 for the data, $80 for the game.

Id rather just buy an $80 game ON the disc, not an empty disc with a download code.

**Comment by MyzticalTekkno** [comment]
@awakened-game 
True.

**Comment by pokeball99** [comment]
@Alexander01998 we need to tag these,there are over 4 pages of unlabeled issues
