### ISSUE TITLE
Fly Bypass Updated?

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#1977]

**Comment by MyzticalTekkno** [comment]
Wow! That's nice, even nicer if wurst have that feature.

**Comment by OMGchangeMYusername** [comment]
![image] (http://puu.sh/jMF0Z/e72e91c466.png)

@Alexander01998  I don't know what he actually said, but you kinda get the idea. Can he take Wurst down just like that?

**Comment by 1337HaxorKiddie** [comment]
@OMGchangeMYusername I think that they can´t get @Alexander01998 down cuz only Garkolym can report Alex for Copyright. But that doesn´t matter cuz Alexander don´t copied and even if Alex copied, Garkolym has no Copyright on this sources.

**Comment by Orcunegeacar** [comment]
@1337HaxorKiddie  You are right. It's not easy to get Wurst down.

**Comment by Alexander01998** [comment]
> @OMGchangeMYusername I think that they can´t get @Alexander01998 down cuz only Garkolym can report Alex for Copyright. But that doesn´t matter cuz Alexander don´t copied and even if Alex copied, Garkolym has no Copyright on this sources.

Exactly. Just keep calm and ignore him, he only does it because he wants attention.

**Comment by mcccs** [comment]
@Alexander01998 my issue isn't about taking down Wurst?!

**Comment by Orcunegeacar** [comment]
Lol @mcccs  :smile:
