### ISSUE TITLE
Buged blink.

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#198]
The issue #190 talks about it, when you enable blink, you starts lagging in a random loop.
Blink is broken right now. But i think resilience..... again... have the fix '-'.
It is a manual blink. 
http://pastebin.com/vmQyRrXS

Thanks for all your great support!

**Comment by Alexander01998** [comment]
> The issue #190 talks about it, when you enable blink, you starts lagging in a random loop.

That one was caused by Sneak, not Blink.

> Blink is broken right now. But i think resilience..... again... have the fix '-'.
> It is a manual blink. 
> http://pastebin.com/vmQyRrXS

That Blink works exactly the same way as the Blink in Wurst.
