### ISSUE TITLE
Text is all messed up

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#1985]
![capture](https://cloud.githubusercontent.com/assets/7843719/9446890/720ca45a-4a51-11e5-97e4-42ac78e65ed1.PNG)

please fix

**Comment by EnderGamer21** [comment]
wtf

**Comment by awakened-game** [comment]
i.... dont see anything wrong... am i not seeing something? looks fine to me, besides the highlighting you added

**Comment by awakened-game** [comment]
yeah i see it now in mine, weird

**Comment by trollmad3** [comment]
@awakened-game do you have steam? if so can i add you?

**Comment by Alexander01998** [comment]
What is your screen resolution and operating system?

**Comment by trollmad3** [comment]
@Alexander01998  Screen resolution is 1680 x 1050 And my operating system is windows 10

**Comment by Alexander01998** [comment]
OK. What's your Java version? If it's not Java 8 update 60, try updating to that.

**Comment by trollmad3** [comment]
@Alexander01998 Can you send me a link to it?

**Comment by Alexander01998** [comment]
http://java.com/download

**Comment by trollmad3** [comment]
I think i have it how do i check my java version?

**Comment by Alexander01998** [comment]
1. Right click the Windows logo
2. Click "Programs and Features"
3. Look for something that starts with "Java 8 Update"

**Comment by Alexander01998** [comment]
Did it work before you updated to v2.3.1?

**Comment by Eyremba** [comment]
I have the same problem. Windows 8.1, 1920x1080, Wurst 2.3.1, in Wurst 2.3 it was another font bug.

**Comment by trollmad3** [comment]
@Alexander01998 It was working fine on version 2.3 the text was all fine but now it got fked up

**Comment by Orcunegeacar** [comment]
The best font was in 2.2 :disappointed:
