### ISSUE TITLE
Font glitches

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#1986]
On the new wurst 2.3.1 update the n is just a box and other letters are glitching :telephone_receiver:

**Comment by awakened-game** [comment]
duplicate #1985

**Comment by Alexander01998** [comment]
What is your screen resolution and operating system?

**Comment by ayciate** [comment]
Windows 10. I my resolution is 1920 x 1080

**Comment by Alexander01998** [comment]
> Windows 10. I my resolution is 1920 x 1080

That's the same that I have. Please post a screenshot of the font.

**Comment by ayciate** [comment]
![wurst](https://cloud.githubusercontent.com/assets/12588174/9450610/9001f9ec-4aa1-11e5-91d4-35d5ec197a96.PNG)

**Comment by Alexander01998** [comment]
What's your Java version? If it's not Java 8 update 60, try updating to that.

**Comment by ayciate** [comment]
![wurs2t](https://cloud.githubusercontent.com/assets/12588174/9451007/024f5cfe-4aa4-11e5-9c87-9d65eecb9991.PNG)
Still the n and others are glitching very less but it is still there :dragon_face:

**Comment by Alexander01998** [comment]
Wait, is that happening because of your ResourcePack?

**Comment by ayciate** [comment]
Just de-selected all the resource packs, nothing changed as far I can see.

**Comment by Alexander01998** [comment]
Just downloaded a random ResourcePack, nothing changed for me either.

But it worked for you in Wurst 2.3, right?

**Comment by ayciate** [comment]
Yep
Nothing wrong with 2.3
