### ISSUE TITLE
CaveFinder

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#1988]
When activate cavefinder it flicks on then off but it still shows as on. When on a menu  cavefinder activates. I have latest java and wurst 2.3.1. Pretty sure it worked on 2.3.

**Comment by Eyremba** [comment]
Duplicate #1805 

![bba4482e-36ed-11e5-8536-77bb1fca1d7e](https://cloud.githubusercontent.com/assets/13738234/9464138/beed7f44-4b21-11e5-9241-62378c5fe337.png)
