### ISSUE TITLE
Add NBT tag editor

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#1991]
An NBT tag editor for noobs like me. For some reason the .give 1 1 0 NBT tag doesn't work. You should add one with gui saying " NAME " "LORE" "ENCHANT" "MAX STACKS" and try to make it like "All u want" mod that won't work in 1.8 please i have a shop where I sell hacked items and idk how to use NBT tags

**Comment by 1337HaxorKiddie** [comment]
If you do .give leather_boots 1 0 {ench:[{id:7,lvl:127}]HideFlags:63} you get cool Leather Boots with thorns, its really easy to give items NBT Tags.

**Comment by im4nthony** [comment]
Can u teach me how? I can make playerheads and stf but idk how to make things like custom lores and names with color

**Comment by 1337HaxorKiddie** [comment]
Look here: http://minecraft.gamepedia.com/Tutorials/Command_NBT_Tags

You can see much NBT tags, at the beginning its a bit difficult but you will understand it after some tests  ;)

**Comment by im4nthony** [comment]
OK I just thought NBT tags were different with this client
