### ISSUE TITLE
ExtendYaw

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#1996]
Ideally this mod would **remove (or increase) the vertical view axis orientation max angle** (I think is known also as `yaw` value, by default it has caps at `0°` and `90°`), enabling people to look (aim at) the sides of the block below them without having to back-walk.

 This may help in many building situations, at least in my opinion. It is a trivial modification, but I think other clients do not have it.

This picture should illustrate the problem enough:

![The screenshot](http://i.imgur.com/YVI09g1.png)

(*I have no idea about possible keywords to search dupes for this, so I only tried `yaw`*)

**Comment by Creeperman8362** [comment]
this ^

**Comment by OMGchangeMYusername** [comment]
It's not a duplicate, and it's a very nice feature if it was to be implemented.

**Comment by awakened-game** [comment]
cool idea, but you would need a reset button too, id imagine you would forget which way is up in some places, maybe not, im just thinking that

**Comment by beppe9000** [comment]
I was thinking about allowing an user-determined (a variable/option would hold it) number of degrees of additional liberty, with a default (imo) of 20°.
