### ISSUE TITLE
.ip player ips

### ISSUE THREAD

**Issue by Branden567** [Wurst-Imperium/Wurst-Client#1998]
you should add a command where you can either scrape all player ips, or a command like ".ip (players name)"then it'll show you the players ip on screen

**Comment by pokeball99** [comment]
impossible without console access

**Comment by awakened-game** [comment]
i wish .ip worked on bungie servers, but it only gives you the IP of where you connected, such as the hub, not the actual server you are on

**Comment by Eyremba** [comment]
@awakened-game this would not help you if you had the server-ip on a bungie server network.

**Comment by linuxcodefire** [comment]
well you can do advanced tracerout of server and get ips =.=
