### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Nate415k-** [Wurst-Imperium/Wurst-Client#2]
I think you should add Optifine to your modded client. I really enjoy this mod and from experience I think it's one of the best for 1.8 but I cannot run it as smoothly due to not having optifine. Please take my suggestion into consideration.

**Comment by Alexander01998** [comment]
OptiFine has too many bugs and crashes too often. If I added it, those bugs and crashes would be in Wurst and I couldn't do anything to fix them.

For me, OptiFine has never increased the performance at all. In fact, it decreased the performance.

**Comment by pokeball99** [comment]
well it your opinion if it does not increase you preformence,but for me i have tried the metro client,with optifine built in,giving me 30+ frames,but with the latest wurst release,i brought me down to 10-5 fps.and besides if it did not work,y would it be so successful after so long

**Comment by pokeball99** [comment]
Well,how about just have a optifine version and a non optifine version,and dont accept crashes from the optifine version?

**Comment by Alexander01998** [comment]
> Well,how about just have a optifine version and a non optifine version,and dont accept crashes from the optifine version?

Back in the old days, when it was all about the bugs, this might have been a possible solution, although it would have caused some problems. (e.g.: I couldn't prevent OptiFine users from ignoring all my warnings and sending me their OptiFine crashes anyways.)

But nowadays, there is another important reason why I don't want OptiFine in Wurst: the amount of people who think that OptiFine magically makes everything fast and that everything without it must be slow.

I could just add a fake OptiFine options menu, a random Zoom mod and some useless background calculation that causes lag, then say that I added OptiFine and release that version, and then get tons of comments from people telling me how fast it is. If I hadn't forgotten about April Fools Day again, I would have probably done that prank.

However, when I make actual performance enhancements, these same people tell me how Wurst becomes slower in every update. They actually said this in v1.9, which almost *doubled* everyones FPS.

This phenomenon is known as [groupthink](http://en.wikipedia.org/wiki/Groupthink) and I am not going to fall for it.

**Comment by WurstContributer** [comment]
Now lets see how many times this was F**KING REFRENCED!

**Comment by WurstContributer** [comment]
21 times.....

**Comment by scriptinator** [comment]
I agree with @Alexander1998 it is so annoying of what people think of optifine. I believe that you actually should make the fake optifine version. And release it, but say it is Wurst-Optifine and was based off of optifine.

**Comment by WurstContributer** [comment]
Plan: Make a version of Wurst with optifine and show ppl how optifine would affect Wurst's Preformance

**Comment by Nate415k-** [comment]
I don't understand how optifine would effect its performance. I'm currently using another hacked client with optifine and everything works just fine.

**Comment by GlitchHead** [comment]
optifine does not just instantly make minecraft run faster the way it works is in video options you can disable particles water effects the sky or animations to increase FPS for slow computers.

**Comment by Bluscream** [comment]
I want optifine too. I will try to put the jar's together and probably even write a installation routine for it.

**Comment by OMGchangeMYusername** [comment]
Dunno why is this considered as a new notification for me,but i just realized that this issue has the label "question" instead of "confirmed" which most of the rejected suggestions have.

**Comment by DataPools** [comment]
@Alexander01998 I think you should have optifine in the client. Not for the zoom mod, but for the ability to turn off particles that lag you like rain

**Comment by bob80333** [comment]
Vanilla minecraft already has the ability to lower/turn off particles.

**Comment by DataPools** [comment]
It can not turn off rain particles, even if you turn particles to minimal
