### ISSUE TITLE
Troll Speak

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#2000]
![TrollSpeak](https://cloud.githubusercontent.com/assets/13103085/9481576/1ba9b354-4b51-11e5-9627-80b1325cfdb0.jpg)

**Comment by labcraft59** [comment]
Top left...

**Comment by Creeperman8362** [comment]
i dont think thats wurst

**Comment by EnderGamer21** [comment]
he means alex should add it

**Comment by Nitrogen-Dioxide** [comment]
errr what does it makes?

**Comment by OMGchangeMYusername** [comment]
You literally found this picture at mchacks.net and decided to make it a suggestion, do you know what it does?

**Comment by labcraft59** [comment]
1t m4k3s y0u sp34k l1k3 th1s

**Comment by im4nthony** [comment]
Ya add it and fancy chat

**Comment by Alexander01998** [comment]
> 1t m4k3s y0u sp34k l1k3 th1s

That is usually known as LeetSpeak. We already have an Issue for that suggestion: #941.

**Comment by labcraft59** [comment]
But you didn't add it...
