### ISSUE TITLE
.screenshot command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#2001]
A command that makes a screenshot like F2
But this hides anything form wurst
(The Logo,Travers,PlayerESP,Item/Mob Esp)

**Comment by RaizeWormwood** [comment]
This seems rather interesting but, you can just disable them all manually. I mean having a shortcut would be nice but is it necessary?

**Comment by Eyremba** [comment]
Some clients also have ".imgur" which takes a screenshot and uploads it automatically to imgur for you so you can share the link very easy.

**Comment by pokeball99** [comment]
^ thanks to there api,but that could be abused to make imgur charged Alex money

**Comment by Eyremba** [comment]
"^ thanks to there api,but that could be abused to make imgur charged Alex money" wtf..? No it can't. Everybody can upload images to imgur for free, and the client is uploading the screens over your own IP and over your own PC, so it is like you were uploading it through your browser.

**Comment by pokeball99** [comment]
@Eyremba ~~yes,they can do it for free...manualy,but with a api,if he goes over a certain number of uploads~~
wait,just looked it up
>Free Usage

The Imgur API is free for non-commercial usage. Your application is probably free if you don't plan on making any money with it, or if it's open source.

Heavy Free Usage

If your application is free, but isn't going to work with our rate limiting, then we might be willing to white-list it. Fill out this form submit your white-list request. We will review your request, and if granted, will give you all the access your awesome app desires!

**Comment by Eyremba** [comment]
@pokeball99 as far as I know, you can also implement it without the API.

**Comment by awakened-game** [comment]
add wget? also, i take screenshots by disabling any visual mods in the shot, not all of them, then press F1 to disable the GUI (because of wurst logo and dancing taco), then F2 for the shot
