### ISSUE TITLE
Add invsee creative

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#2002]
Invsee creative and u can copy their items to your inventory

**Comment by Orcunegeacar** [comment]
Actually it will be very good! You can copy crash item and crash chest to their inventory! OMG. Think that! You can crash their game. They will never get into server. I don't know if it's possible but it is the best idea! @Alexander01998

**Comment by im4nthony** [comment]
Lol no I mean say u are in creative and u want to get an op sword that they have, u can just copy it from their inventory without them knowing... Mtght only  work on creatuve

**Comment by Janskill** [comment]
I don't think it's possible to look in player inventories as your client doesn't have enough information. It only knows which item a player is holding in his hand and which armor he is wearing. So I think an inv see hack is pretty much impossible.

**Comment by Eyremba** [comment]
@Janskill Wurst ALREADY HAS an invsee command, so if you have no idea, then you should think about it before you write anything which is totally wrong.

**Comment by 1337HaxorKiddie** [comment]
@Eyremba If you type .invsee PLAYER you see also only the item they holding in hand, so if you have no idea, then you should think about it before you write anything which is totally wrong.

**Comment by trollmad3** [comment]
@Eyremba It doesent work for creative....so we need it

**Comment by WurstContributor** [comment]
I think this is impossible. Because the inventory of the player is server sided.

**Comment by trollmad3** [comment]
@WurstContributor can you please add me on steam we can grief together and troll on servers i even know some that are unprotected  my steam name is http://steamcommunity.com/id/therealevilotto/

**Comment by OMGchangeMYusername** [comment]
All replies aren't really satisfying, 
@Orcunegeacar That is impossible, you can't put things into other's inventorys just like that. 
@Eyremba Wurst's invsee is only for survival.
And this issue is a duplicate, @WurstContributor you should've redirected them to #1211.
@trollmad3 Please stop talking about your steam in every issue, this is not forums.

**Comment by Eyremba** [comment]
@1337HaxorKiddie your just a kid. It displays really more. You can also see the armour, the durability, and the enchantings. So you should think about it before you write anything which is totally wrong.

**Comment by WurstContributor** [comment]
@trollmad3 I've stopped using steam about 3 years ago. ugh.

**Comment by 1337HaxorKiddie** [comment]
@Eyremba But not the whole inventory as you said in your first command here.

**Comment by Eyremba** [comment]
@1337HaxorKiddie I NEVER said "the whole inventory", I only said that what he said (that Wurst has no ".invsee") is wrong, I didn't say more.

**Comment by PixelMaster3D** [comment]
Its possible. But the chance could be for is about 1% easier than that. Don't say its impossible. It really is possible but the odds of doing it is slim. Maybe you can add a data leakier that tries to grab what is being sent to the server

**Comment by Orcunegeacar** [comment]
Spoiler alert: I'm creating an Wurst Installer App (not done but take 5 days to do search,fix bugs,important things) :smile:
