### ISSUE TITLE
Random mods activating

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#2004]
I joined a server and LSD mod was enabled. The UI said it was not.

Another time a player said "your head looks strange": i think this is some of those misc mod that got activated. The UI said nothing was activated.

Another time i started seeing tons of artifact, flickering whenever i turned the view. The UI said nothing was active, but i believe some combination of render mods activated.

Now, maybe this has to do with keybings being read also when not in-game or chatting i my opinion.

**Comment by awakened-game** [comment]
*>inb4 "but it works on my machine!"

**Comment by Alexander01998** [comment]
> Now, maybe this has to do with keybings being read also when not in-game or chatting i my opinion.

That won't happen.

> I joined a server and LSD mod was enabled. The UI said it was not

> Another time i started seeing tons of artifact, flickering whenever i turned the view. The UI said nothing was active, but i believe some combination of render mods activated.

That happens when you press the <kbd>Super Secret Settings</kbd> button in the (vanilla) options menu.

> Another time a player said "your head looks strange": i think this is some of those misc mod that got activated. The UI said nothing was activated.

That could mean that you disabled the Mod List in the Wurst Options menu.

**Comment by Nitrogen-Dioxide** [comment]
Spider is activating randomly for me too.

**Comment by beppe9000** [comment]
>That could mean that you disabled the Mod List in the Wurst Options menu.

That was the first thing that I did double-check.
