### ISSUE TITLE
NBT tag editor

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#2005]
I know I made s thread like this already but, we should have a command like .NBT and we can add them like that, because if we make a written book the tags go away when u write in it

**Comment by MyzticalTekkno** [comment]
<b><i>Duplicate #1991</b></i>
<img src="https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png" alt="Please search for similar Issues before submitting yours." style="max-width:100%;">

**Comment by PixelMaster3D** [comment]
He knows MyzticalTekkno. You don't have to remind us.

**Comment by MyzticalTekkno** [comment]
@PixelMaster3D  reminding is the best thing.

**Comment by Eyremba** [comment]
@MyzticalTekkno no it is not, your issues will be deleted then, you will get banned, and all was useless.

**Comment by MyzticalTekkno** [comment]
@Eyremba  
1. deleting a thread without a forward reason doesn't even make any sense.
2. Still he could ask that with his first thread, rather than making another one.
3. He could ask that with his first thread, because the topic he first created and he created now is ~~The same
