### ISSUE TITLE
In-game suggestion form

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#2007]
An in-game suggestion/feedback form in the Wurst esc-menu page. It could post to github, or to a google form.
I think that this project could benefit from a split of bug reports and suggestions/feedback.

**Comment by PixelMaster3D** [comment]
50/50% chance it'll probably get submitted. State a better reason why. Maybe add a example. But this is useful in a different way. When the client crashes the report will be sent automatically.

**Comment by Alexander01998** [comment]
I have a similar plan that I've been working on for about a week. If it works well, I might integrate that into Wurst.
