### ISSUE TITLE
PotionSaver bug

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#2008]
i ate a god apple while PotinSaver is on and go into fire
when i came out of the fire the fire doesnt stop when i stand

**Comment by Eyremba** [comment]
And....? This is NOT a bug, this is how PotionSaver works. If you stand, it wil save your effect. Does not matter if good potion, bad potion, or fire.

**Comment by OMGchangeMYusername** [comment]
Wait Wurst doesn't have an AntiFire?

**Comment by Eyremba** [comment]
Wurst has an AntiFire, but not NCP bypassing. There are also NCP bypassing "AntiFire" mods in private clients like "Firion" and "Zoot", but be carefully there are also shitty clients like Wolfram which name their AntiFire "Zoot" but NOT NCP bypassing.

**Comment by awakened-game** [comment]
i dont get the whole NCP thing, i installed it on a local server to test what is detected and how it displays, and i got nothing, EVERY hack passed NCP without anything more than "NCP enabled" in the console.
ANTI-CheatPlus however, blocks what it normally should, so i dont get what im doing wrong, does NCP have unlisted dependencies?
oh and at the time i had no permissions and no OP either, JUST NCP was installed.

**Comment by Eyremba** [comment]
@awakened-game you have done something wrong. If you have NO permissions and you are NOT OP, then NCP will flag you for nearly every mod in Wurst which is not a rendering mod (like ESP or tracers)
