### ISSUE TITLE
Typo: singlepalyer

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#201]
wurst > wspam > autorun > joinworld.wspam

  Runs whenever you join a singlepalyer world.
"palyer"

**Comment by OMGchangeMYusername** [comment]
if you have time to correct every single spelling then you should make it all in one issue and CHANGE the title! why does it have to be "Bad spelling"?
you're supposed to say "spelling mistakes" and stuff them all in one issue.
