### ISSUE TITLE
Suggestion Potions

### ISSUE THREAD

**Issue by TheKritix** [Wurst-Imperium/Wurst-Client#2012]
To be able to switch names on potion and create all potions in Creative to bypass the item ban-list on servers.. I would like to change the name myself in the client. For example the KillerPotion just got banned on one of the servers i mainly play on, but if i'm able to change the name to bypass the ban-list it would be awesome. Maybe to add all potions and be able to change name in the client.

**Comment by Eyremba** [comment]
1. dude you have ".rename"..... *facepalm*
2. They don't ban the name, they ban the item ID's and you can NOT change the ID's.

**Comment by 1337HaxorKiddie** [comment]
Btw if you type .rename $rYOUTEXT the text will be set to default that means the text is not Italic.

**Comment by TheKritix** [comment]
Not sure if you understand what I mean, I want to change the name of the killerpots before I spawn it. The server I play on use name for ban list and not id so I wanna change the name before I spawn it

**Comment by Eyremba** [comment]
@TheKritix just download the Wurst source, rename it in the code, recompile it, and use your own version for this server.

**Comment by TheKritix** [comment]
Tried but kept crashing
