### ISSUE TITLE
Better Forceop

### ISSUE THREAD

**Issue by xXxHelperxXx** [Wurst-Imperium/Wurst-Client#2014]
This is not a super good force op create one for premium and the session stealer doesnt work for me

**Comment by Eyremba** [comment]
#Invalid - you ever read the rules for opening an issue here..?

**Comment by Alexander01998** [comment]
Wurst has three Force OPs so far, two of them work on premium servers and all of them have detailed tutorials on the Wurst wiki:

1. [AuthMe Cracker](https://www.wurst-client.tk/wiki/Mods/Force_OP_(AuthMeCracker)/)

2. [BookHack](https://www.wurst-client.tk/wiki/Special_Features/Force_OP_(BookHack)/)

3. [Session Stealer](https://www.wurst-client.tk/wiki/Special_Features/Force_OP_(Session_Stealer)/)
