### ISSUE TITLE
.potionedit

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#2017]
With the killer potion there is a health boost of 127 therefore killing people in creative. If there was a way to edit an potion to have an effect such as instant damage 1000 or regen 1000 it would be amazing. By holding a potion and typing .potionedit add/remove effect instantdamage 5000 it would add instant damage onto the potion

**Comment by EnderGamer21** [comment]
there is type .potion while holding one

**Comment by 1337HaxorKiddie** [comment]
The biggest enchantment/amplifier is: 32767
