### ISSUE TITLE
AutoTPA Accept

### ISSUE THREAD

**Issue by agaaxasa** [Wurst-Imperium/Wurst-Client#202]

**Comment by GlitchHead** [comment]
bad idea lots of people tpa trap.

**Comment by OMGchangeMYusername** [comment]
>bad idea lots of people tpa trap

exactly,i feel like he spams sometimes.

**Comment by Nitrogen-Dioxide** [comment]
It is not a bad idea..... sometimes too many people tpa to you, and you cant tpaccept all because each tpa request removes the previous ones. Great for parties xD.
Great idea.

**Comment by GlitchHead** [comment]
Yea when YOU are the one tpa trapping people i gess this could be good

**Comment by Alexander01998** [comment]
> Tpaccept only friends ?

Yup.

**Comment by Bluscream** [comment]
Here is example source code for you @Alexander01998 https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/player/ModuleAutoTPAccept.java

**Comment by Meylama** [comment]
@Alexander01998 Instead of a "AutoTPA Accept" Mod, a "AutoTPA" Mod with the settings ".autotpa accept" (Auto accept all TPA requests) and ".autotpa deny" (Auto deny/reject all TPA requests) would be much better.

**Comment by Meylama** [comment]
But it can be annoying, so a way to AutoDeny it would also be nice.

**Comment by OMGchangeMYusername** [comment]
Implying you guys are always getting tpa rquests..
