### ISSUE TITLE
To @Alexander01998

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#2020]
Hello @Alexander01998 GarkolymHD  Wants to talk to you privately on Skype

His skype is garkolym 

He really wants to talk to you privatly about his client and your client

                                       -From trollmad3

**Comment by Creeperman8362** [comment]
this might not go well for us...

**Comment by 1337HaxorKiddie** [comment]
@trollmad3 Please delete this issue, its just useless Alexander knows whats up and this is no issue

**Comment by trollmad3** [comment]
@1337HaxorKiddie GarkolyhmHD just wants to talk to alex

**Comment by 1337HaxorKiddie** [comment]
@trollmad3 No shit Sherlock
