### ISSUE TITLE
Add setblock

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#2021]
You can maybe add .setblock as if it were doing / setblock ~~~ we can use this for entities like armor stands and add nbts that u can't place like {small:1} because I tried /give with that and it didn't work.

**Comment by im4nthony** [comment]
Or maybe add .summon and have it place a spawn egg

**Comment by 1337HaxorKiddie** [comment]
.setblock would probably work, in player range. But not somewhere else. And .summon with entitys and/or entitydata is Impossible.

**Comment by im4nthony** [comment]
I don't mean setblock an any location I mean /setblock ~ ~ ~ so we can add entity data

**Comment by trollmad3** [comment]
k

**Comment by 1337HaxorKiddie** [comment]
You know that a block has no Entity data.

**Comment by im4nthony** [comment]
Explain Armor Stands

**Comment by 1337HaxorKiddie** [comment]
What?

**Comment by im4nthony** [comment]
Armor stands are blocks with entity values

**Comment by 1337HaxorKiddie** [comment]
k i think i know what you mean.
