### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#2022]
Where are you @Alexander01998 ? There are so many issues,suggestions and questions to answer. Is it your rest day?

**Comment by GlitchHead** [comment]
You stop. Your not helping.

**Comment by Eyremba** [comment]
@Orcunegeacar He is dead again. Or maybe again in vacation.

**Comment by Alexander01998** [comment]
> @Orcunegeacar He is dead again. Or maybe again in vacation.

I released an update 2 days ago. How am I dead?!

**Comment by Eyremba** [comment]
@Alexander01998 it is just a joke because of this annoying kids with their "where is alexander????????"
