### ISSUE TITLE
No Symbol or mods

### ISSUE THREAD

**Issue by H1DD3NxD0NUT** [Wurst-Imperium/Wurst-Client#2027]
Add an option to the modlist that will get rid of the list of mobs, the wurst symbol and version symbol or have it so the hidden option turns off the wurst symbol and version. we can all hide it if we need to record and we dont want to hack and dont want to switch our version and for other reasons that people might have

**Comment by rasmusolle** [comment]
1. Duplicate
2. I'm with you
