### ISSUE TITLE
.nameprotect

### ISSUE THREAD

**Issue by Walthall** [Wurst-Imperium/Wurst-Client#2028]
self explanatory, you put in someones username like .nameprotect test tset
and it changes "test" to "tset"

**Comment by Eyremba** [comment]
#Duplice #748 

![990e8990-3842-11e5-809e-a06b796a4328](https://cloud.githubusercontent.com/assets/13738234/9540858/1fdd2c6c-4d63-11e5-94e2-35304d2bc632.png)
