### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by agaaxasa** [Wurst-Imperium/Wurst-Client#203]
Adds a compass, an ender eye and a clock to your screen.and shows coordinates.

**Comment by GlitchHead** [comment]
F3

**Comment by OMGchangeMYusername** [comment]
but this one can be actually nice.
because sometimes i feel like it's too hard to find the coords xD
and the ender eye seems good but what kind of server that makes you look for an end portal?

**Comment by Alexander01998** [comment]
> Adds a compass, an ender eye and a clock to your screen.and shows coordinates.

Coordinates can be useful, but compass, clock & ender eye are overkill.

> iTools

Not with that name!

> F3

:+1: 

> and the ender eye seems good but what kind of server that makes you look for an end portal?

A vanilla server.

**Comment by GlitchHead** [comment]
you should also include a copy coordinates to clipboard.

**Comment by WurstLeafeon** [comment]
Why not draw an ESP over where a compass is pointing? The server should be telling you where the compass should be pointing, including the X and Z. Drawing an ESP over where it's pointing at could give you exactly where spawn is, exactly where your bed is, or exactly where the nearest player is (HungerGames).
There's also a few more minigames that uses the compass to point towards your target, half of which the target is completely invisible.
