### ISSUE TITLE
All u want mod

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#2030]
Basically like the allu wan mod bit called different

**Comment by solidshadow96** [comment]
wtf more info requried

**Comment by BoomBoomLHack** [comment]
umm you can use .give

**Comment by im4nthony** [comment]
.give is good but not fun I have s hacked item shop in cosmic craft and people don't like waiting am about for an item

**Comment by Eyremba** [comment]
Duplicate #1928
#rejected and denied.

![bba4482e-36ed-11e5-8536-77bb1fca1d7e](https://cloud.githubusercontent.com/assets/13738234/9540902/a09609b4-4d63-11e5-9289-bc1efd50f193.png)
