### ISSUE TITLE
QUESTION: Can you add fullblink in the next wurst update???

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#2031]
Can you add fullblink in the next wurst update???

**Comment by BoomBoomLHack** [comment]
What is "fullblink"? Skin blinker?

**Comment by Eyremba** [comment]
No..... @BoomBoomLHack you can also just search here in the issues for "Fullblink"...

**Comment by ravenje** [comment]
I realy need it =(

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by ravenje** [comment]
@1337HaxorKiddie Duplicate??? Why????

**Comment by 1337HaxorKiddie** [comment]
Because this feature was suggested in #1065

**Comment by Eyremba** [comment]
@1337HaxorKiddie retarded? read the issue, this is a REMINDER for Alexander that he should at it in the next update, it isn't a suggestion.

**Comment by TheIonosphere** [comment]
It would definitely be a useful feature

**Comment by mcccs** [comment]
@TheIonosphere yup
