### ISSUE TITLE
Alt list not save

### ISSUE THREAD

**Issue by Delivator** [Wurst-Imperium/Wurst-Client#2032]
First time i start the Client and click on Alt Manager it asks if i want to creatate sone random alts and i click on Yes. Then i add a new Alt (My Premium Account) and click Add. After that i click on Canel to go back to the menu and exit the game. After restart the Alt list ist empty again and i have to add all accounts again.

**Comment by 1337HaxorKiddie** [comment]
Thats a bug i think.

**Comment by Delivator** [comment]
@1337HaxorKiddie Ok how can i move?

**Comment by 1337HaxorKiddie** [comment]
I don´t know, i don´t saw this before. Can it be that you Wurst Folder got deleted?

**Comment by Delivator** [comment]
No, the wurst folder is still there and the alts.json is also there and when i add some alts (first startup) the alts.json get updated but when i restart wurst the list (not the file) is empty

**Comment by 1337HaxorKiddie** [comment]
Than thats a bug.

**Comment by Delivator** [comment]
Yeah ok :/

**Comment by Orcunegeacar** [comment]
Same here* You just add alts and close minecraft and they're gone. boom :smile:

**Comment by Delivator** [comment]
Is it fixed now?

**Comment by Alexander01998** [comment]
Yes.
