### ISSUE TITLE
add any picture to a map

### ISSUE THREAD

**Issue by MicroChip321** [Wurst-Imperium/Wurst-Client#2033]
if u can make something that lets you add any picture you want to minecraft maps :3 can be usefull in creative servers to sell them xD

**Comment by pokeball99** [comment]
can this be done?like without op,and only gm1?gotta do some research on this....

**Comment by BoomBoomLHack** [comment]
you can't. its server-sided.

**Comment by GlitchHead** [comment]
This might actually be possible.

**Comment by pokeball99** [comment]
not excatly up to date,but this could be use as a base for the mod: https://github.com/LB--/MCModify/blob/java/src/main/java/com/lb_stuff/mcmodify/minecraft/Map.java

**Comment by MicroChip321** [comment]
so any news if its possible?

**Comment by pokeball99** [comment]
i think it is,but its likely not going to be put in for a while,unless someone makes it and does a PR, @Alexander01998 tends to accept stuff but not code them untill months later

**Comment by animemaster** [comment]
Shouldn't it be possible to do it the old fashioned way?  Wurst has a build bot, just use that to lay down blocks to fill in the map.

**Comment by MicroChip321** [comment]
NO!!!

**Comment by PixelMaster3D** [comment]
Are you guys saying ,like, use a map and upload as a schematics file then run the command and that will copy whatever was in the schematics?

**Comment by PixelMaster3D** [comment]
It is possible to run a file in a schematic form but unless you want to run a world, it is impossible.

**Comment by MicroChip321** [comment]
no no no like the spammer thing you upload a png and it will go in the map

**Comment by PixelMaster3D** [comment]
Not possible. The only way you can have it uploaded it is if the server can record this kind of data being sent and the bukkit records on what is happening to the map. You can upload it on a regular server and it will work, but that is about it.

**Comment by Alexander01998** [comment]
> @Alexander01998 tends to accept stuff but not code them untill months later

That's because the suggestions are coming in waaay faster than I can implement them (even though I release an update every week). The feedback app helps a lot with this, as it allows me to add the most requested features first.
