### ISSUE TITLE
The command which be automatically executed at low health

### ISSUE THREAD

**Issue by Egor1505** [Wurst-Imperium/Wurst-Client#2035]
I wantet to suggest to add a hack whch automatically execute a command you want when you are at low health and low hunger. FOr example I am playing on server with /feed and /heal commands and sometimes when i fight against a lot of players a have low health bar and sometimes I don't succes to press my keybind. So I suggest Wurst should do it for you!

**Comment by 1337HaxorKiddie** [comment]
Duplicate.

**Comment by BoomBoomLHack** [comment]
What @1337HaxorKiddie said. Dupe of #1838
