### ISSUE TITLE
Question:What does .annoy do

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2036]
Title says all

**Comment by trollmad3** [comment]
It baiscly copys what every the person is saying

If you do .annoy Alexander01998 

and if Alexander01998 says im a skid 

and then you will say im a skid

**Comment by Eyremba** [comment]
Search in the Wurst wiki. This message says all.

**Comment by Usernamer** [comment]
Repeats messages for a certain person. Syntax: .annoy <player>
