### ISSUE TITLE
.give glitch

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2037]
whenver i get heads using .give but if they change their skin it dosnet work it only gives their old skin

**Comment by Alexander01998** [comment]
What NBT data are you using? And does it work properly with the vanilla `/give` command?

**Comment by EnderGamer21** [comment]
i use it on multiplayer i use .give  397 1 3 {SkullOwner:Notch}

**Comment by GlitchHead** [comment]
it does not work properly with /give..... so this does not have to do with WURST.
