### ISSUE TITLE
.modlist command

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#2041]
.modlist save 1 will save your current mods list
.modlist load 1 will load your mods list #1.
.modlist delete 1 will delet mods list #1.

**Comment by EnderGamer21** [comment]
Dupe let me check which one

**Comment by EnderGamer21** [comment]
@mcccs  will finde a dupe or will Gummi boat

**Comment by 1337HaxorKiddie** [comment]
@EnderGamer21 #1339

**Comment by Tropfer** [comment]
Nice Idea

**Comment by EnderGamer21** [comment]
@1337HaxorKiddie thx

**Comment by 1337HaxorKiddie** [comment]
@EnderGamer21 No problem.

**Comment by Alexander01998** [comment]
Duplicate: #656
