### ISSUE TITLE
websites that claim free premium accounts

### ISSUE THREAD

**Issue by WindFenix** [Wurst-Imperium/Wurst-Client#2042]
it's kinda unrelated with the hack client itself but I was wondering if you could tell me about websites that claim that they can give you free premium accounts. Are they legit, are some not, or are they all scams? I don't want to get any viruses, so if you respond that would be awesome :)

**Comment by Orcunegeacar** [comment]
Please close that issue. Buying FREE premium accounts aren't legit. If you really want a premium account. Check this out http://www.accountgen.net/minecraft/index.php

Again, Do not post issues or questions like this.

**Comment by PixelMaster3D** [comment]
Harsh man.

**Comment by PixelMaster3D** [comment]
To answer the truth. No. There isn't a way to get them unless from Alts or from owner server giveaways but to actually get one in an instant no.

**Comment by pasi123567** [comment]
Orcunegeacar You have the website pretty sure from me :package :P 
Just wanna to tell you that the website isnt going to update anymore.
He said in skype that he cant update it anymore because is paypal account got blocked.
SO he cant pay the website anymore.

**Comment by Orcunegeacar** [comment]
ok
