### ISSUE TITLE
Font Fix for Wurst (Works in only Windows) %75!

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#2043]
I was searching some things and I found a fix for Font Bug in Wurst. It is now clean but not FULLY clean. It's working like %75 (Wurst's font designed for Windows 10 but I'm going to teach you how to fix this font bug in 7/8/8.1 also XP

For the fix, you will need these things:

- Nvidia GPU (Example: GT 220,nvidia gtx 660.....Any Nvidia GPU)
- Font Better(Faithful) ResourcePack (or texturepack :smile: )
DOWNLOAD LINK: http://www.mediafire.com/download/8vs7gboerfp11y8/Font_Better_for_Wurst.zip
- 32 Bit Windows XP/7/8/8.1/10 for font's better quality (Can be 64 bit too)
- DirectX 10 or better (11,12) Actually it can be 9 too.

Now I'm going  show you how to fix that 'Bug'

- UPDATE YOUR GRAPHICS CARD'S DRIVER.
You can download the last and updated driver for your GPU in here: http://www.geforce.com/drivers

- USE FONT BETTER (or FAITHFUL RESOURCE PACK)
It's better than the original Minecraft resource pack for Wurst.

- Update to DirectX 11 (If you have it already you can pass this step)
http://getintopc.com/softwares/development/directx-11-free-download/

Thank you for reading this :smile: 
It's going to be 75% better than the old Wurst Font. (I said 75%. Not fully clean)
If you can't find your 'drivers'. You can comment and I'll reply you.

To: @Alexander01998 
Message: I tested and I wanted to share with you. :+1:

**Comment by Orcunegeacar** [comment]
Detailed: @Alexander01998  uses Windows 10 right now and he is optimizing Wurst for Windows 10 or something like that. Fonts are diffrent in Windows 10. Only Wurst 2.2* is the newest and clean version for fonts.

**Comment by Orcunegeacar** [comment]
NEW FIX: Follow these steps #2043 and update Windows 10! So easy and 100% working! :smile:

**Comment by Alexander01998** [comment]
This is a place for suggesting features and reporting bugs.
It is not a forum.
It is not a wiki.
It is not a chat room.
It is not the comments section of a random YouTube video.
And it is certainly not a place to share tutorials. Please stop doing that.
