### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#2046]
I know Wurst has a font problem. I need to upgrade Windows 10 to fix this problem in my PC.

I installed Windows 10 in the past but screen was terrible. I knew I have to update drivers. When I update the last version it didn't let me. Not supported os (this message poped out) I have Geforce GT 220 right now. I have the last drivers right now. In the past there was no drivers like this. (341.81 update) Using Windows 7 now. Ultimate 32 bit.

Does Windows 10 support Geforce GT 220? (QUESTION) My  pc supports Windows 10 but I don't know how to fix that resolution problem. 

My Monitor = 1336 x 768

I know I talked weird xD (Need a answer quick)

**Comment by Alexander01998** [comment]
This is the issue tracker of the Wurst Client, not the support center of NVIDIA.

**Comment by Orcunegeacar** [comment]
Thank you :smile:
