### ISSUE TITLE
WSPAM delays and loops

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#2047]
Example: You are in a creative server and want to adverstise for your skin comp.
You type this in WSPAM:

/chat global
[delay:500ms]
COME TO MY SKINCOMP NOW!
[delay:600ms]
/chat local
[delay:20000ms]
[loop]

**Comment by pokeball99** [comment]
Just do .spammer delay (number)

**Comment by Alexander01998** [comment]
Already implemented. Use `<repeat>` for loops and `.spammer delay` for delays.
