### ISSUE TITLE
Join, Rejoin, Leave

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#2048]
(Join) Example:

.join [ip] - Leaves the current server and instantly joins the another one

(Rejoin) Example:

.rejoin - Rejoins the server

And maybe a Rejoin button too :smile: 

(Leave) Example:

.leave - Leave the server (maybe could be useful for WSPAM

**Comment by EnderGamer21** [comment]
.leave is already implmented

**Comment by pokeball99** [comment]
Invalid
