### ISSUE TITLE
Disable Wurst

### ISSUE THREAD

**Issue by Tropfer** [Wurst-Imperium/Wurst-Client#2049]
There should be an option to hide, or Disable wurst. Like a button in options with:

Wurst: On/Off

**Comment by JackFishbaugh** [comment]
you mean the logo right? cause if so then this is a dupe.

**Comment by Tropfer** [comment]
No, mean the whole client (except the enable buttons in the settings

**Comment by BoomBoomLHack** [comment]
umm you mean the panic button?
