### ISSUE TITLE
Infinite Delay For Blink

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#205]
You enable blink, it starts counting down the time, then you disable it and you "teleport".
It is better, because you can really "teleport". Blink changing the position each 3 seconds is kinda... not useful.

Think about this situation, a op diamond guy killed another op diamond guy, then the all op stuff is on the ground, because he have a full inventory. Then you stay away, enable blink, walk trough the items, go away again and disable blink ,so you can hook the items! Because for the server, you passed trough the items, but you will stay away safely. I've done that so many times xD.

Sorry about my bad English and all your patient with me o/.

**Comment by Alexander01998** [comment]
Duplicate: #126

**Comment by Nitrogen-Dioxide** [comment]
crap didn't notice that issue.

**Comment by OMGchangeMYusername** [comment]
hmm mm!
you're working hard mr.Alexander!
thank you so much,i apologize if i'm being a bit annoying sometimes.
