### ISSUE TITLE
ender pearl helper

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#2051]
i saw thet on some issues but no one do thet for one thing
snomething thet when u hold a ender pearl on your hand u can teleport into the rigth spot u want
it will be helpful

**Comment by solidshadow96** [comment]
Alex doesn't know the algorithm and it wont work

**Comment by mcccs** [comment]
#168 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
