### ISSUE TITLE
Add Paralyze hack and Unpush please

### ISSUE THREAD

**Issue by Creepy11** [Wurst-Imperium/Wurst-Client#2055]
Hello! (i don't speak english, please forgive)
I love Wurst client, the best client ever!
It would be cool if it had Paralyze hack to make someone unable to move when the other walk in you.
Video:
https://www.youtube.com/watch?v=BUSTo9jNvM0 (it the same for 1.8.x)
-----------------------------------------------------------------------------------------------------------
Unpushable: no one can walk in you! if someone try, he will be pushed! :dancer: 
Video: https://www.youtube.com/watch?v=k2iqPFx2hBY

Thanks you Alexander for this awesome client and i hope it will be added :dancer:

**Comment by pokeball99** [comment]
Invalid

**Comment by mcccs** [comment]
Nopush is called antiknockback and i think i found paralyze source cod2e http://www.hackforums.net/archive/index.php/thread-4144049.html

**Comment by Eyremba** [comment]
Paralyze is easy, but can not bypass NCP so it can only be used in vanilla.

**Comment by Creepy11** [comment]
Nope, paralyze can perfectly bypass NCP it just crash vanilla servers if
the code of paralyze is with 2000 packets/s, it just don't crash in NCP

**Comment by Eyremba** [comment]
Just try it on the NCP testing server, it will throw out nearly 20 NCP flags/s. The many movement_packets are detected by NCP as moving_morepackets or something like this.

**Comment by kcxx** [comment]
Stand still. You need to have full hp and hunger bar.
