### ISSUE TITLE
Wallhack

### ISSUE THREAD

**Issue by Cyntrex** [Wurst-Imperium/Wurst-Client#2056]
First of all im from Germany so if my English isnt the best im sorry. So. A Wallhack would be nice where you can see Mobs / Player thru the wall :)

**Comment by WurstContributor** [comment]
I think this was once in Wurst But pulled out. Not sure :/

**Comment by TheBoyIsHere** [comment]
mobESP
playerESP
Trackers
itemESP
they some of the first mods thet added
pleas check before sending issues!

**Comment by TheIonosphere** [comment]
Those ones are different because they do not tell you which type of mob it is. You can use freecam to see them, but that is inconvenient as you cannot do anything else while using it.

**Comment by solidshadow96** [comment]
Yes i think this would be nice i know mobESP and playerESP is there but also it could work where you can see the armor of a mob and what it is holding

**Comment by EnderGamer21** [comment]
or xray u can see through walls  to see nametags better or mobs

**Comment by solidshadow96** [comment]
True but x-ray makes all surrounding disappear if wallhacks were added it would act like xray but only for a specified target

**Comment by awakened-game** [comment]
Hmm, this REALLY reminds me of the old skinhack for UT99, haha, but that ran with directx so it was much easier to do, this might be no problem considering a "wallhack" is actually built-in to minecraft 1.9 as an effect, so when Wurst for 1.9 is here, i could see this feature included.

@Alexander01998 , possible future feature?
