### ISSUE TITLE
An hack that individue the session log

### ISSUE THREAD

**Issue by Luma00** [Wurst-Imperium/Wurst-Client#2058]
Instert a tool that find session log of players please if it's possible and spider nocheatplus bypass finally the godmode and .effect that gave you the effect you want (strenght exc...)

**Comment by solidshadow96** [comment]
yes please add this where inside wurst it uses something based along the password stealer tool shown on  http://www.wizardhax.com that it locates the Session token and pastes it into a text document where it can then be copied into your session stealer.

**Comment by EnderGamer21** [comment]
inavild u cant put to much issuse in one and godmode is not posiiblea and search up the thing which u put because it can come and its a dupe but theres a lot so invalid
