### ISSUE TITLE
why Converter.jar does not run ?

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#206]
help plz  !!

**Comment by OMGchangeMYusername** [comment]
it does.

**Comment by Nitrogen-Dioxide** [comment]
right click ---> open with.. select all java options possible.

**Comment by osa219** [comment]
i download it and i Pressed but NOTHING  happening .

**Comment by GlitchHead** [comment]
goto the directory in terminal or command prompt and do java -jar Converter.jar

**Comment by Alexander01998** [comment]
> i download it and i Pressed but NOTHING happening .

The converter is entirely written in Java 8, so it won't start if you try to run it with an older version.

**Comment by osa219** [comment]
oh I did not know thanks :)
