### ISSUE TITLE
More space to edit NBT.

### ISSUE THREAD

**Issue by MarvMarv** [Wurst-Imperium/Wurst-Client#2063]
Hello dear Alex,

could you make a GUI for the ".give" command. Like the "CMD-Block" or something like that?
And give it more space than the chat? Because if you have a long NBT term you can´t create the item.
That would be very helpful.

Greetings.

**Comment by WurstContributor** [comment]
Just use spammer.

**Comment by Alexander01998** [comment]
# *Duplicate: #1937*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
