### ISSUE TITLE
This easter egg is to hard too find!

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#2066]
I think we need to add this to syntax. The people will love it.
https://github.com/Wurst-Imperium/Wurst-Client/blob/9ff549763845c1aedb16a92cdc23806b92d0eaac/Wurst%20Client/src/tk/wurst_client/commands/LeaveCmd.java#L35

**Comment by Eyremba** [comment]
I know this already :D I took a look at the source 1 month ago. :D

**Comment by mcccs** [comment]
Yeah i did too.

**Comment by pokeball99** [comment]
maybe it's bugged?

**Comment by Artamiel** [comment]
you guys know the easter egg .taco?

**Comment by Eyremba** [comment]
@Artamiel omg dude we all know this but this is COMPLETELY different.

**Comment by Alexander01998** [comment]
Easter Eggs can't be too hard to find, they can only be too easy.
