### ISSUE TITLE
[WSPAM] replicate function

### ISSUE THREAD

**Issue by Eyremba** [Wurst-Imperium/Wurst-Client#2068]
Example:

(replicate 20)A(/replicate)

Output: AAAAAAAAAAAAAAAAAAAAA (20x "A")

This is very useful, for example for (crashing)NBT-Tags. (examlple: make a sign with very much replicating characters, like crashsign)

Or another example:
".rename (replicate 5000)WurstClient(/replicate)" would rename the item to "WurstClientWurstClientWurstClientWurstClientWurstClientWurstClientWurstClientWurstClientWurstClientWurstClient [...]"

**Comment by mcccs** [comment]
Already implemented
<repeat 5>a</repeat>

**Comment by pokeball99** [comment]
^

**Comment by Eyremba** [comment]
"Already implemented"

@mcccs I think this would spam

a
a
a
a
a

instead of aaaaa

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 

No because repeat needs the enter character.

    <repeat 5>1</repeat>
Will output
    1111

and 

    <repeat 5>
    1
    </repeat>

will output

    1
    1
    1
    1
    1

**Comment by mcccs** [comment]
@Nitrogen-Dioxide Yup

**Comment by Eyremba** [comment]
Thanks
