### ISSUE TITLE
MCP 10.7 for  Minecraft 1.9 snapshots.

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#2069]
I found this .zip file in the internet. My friend told me he didn't test it but However its saying its working in 1.8.8. ? I didn't opened it in eclipse but it seems like it stealed by someone from MCP.

![image](https://cloud.githubusercontent.com/assets/11218527/9586743/47557d6e-5027-11e5-8b3f-eefd44f21b08.png)

**Comment by Orcunegeacar** [comment]
![image](https://cloud.githubusercontent.com/assets/11218527/9586779/6c8a8bd8-5027-11e5-9ef0-8d4ecfe92518.png)

**Comment by 1337HaxorKiddie** [comment]
Is the file virus clean?

**Comment by Eyremba** [comment]
Please send me the link, I analyse it if clean or not.

**Comment by Alexander01998** [comment]
That looks like a nice thing, but I doubt that it will work with Minecraft 1.9 if it's intended for Minecraft 1.8.8. I tried using the MCP for Minecraft 1.8 on Minecraft 1.8.3 in the past and that ended up in a giant mess.

**Comment by Orcunegeacar** [comment]
Yeah my friend told me (when he is downloading) its working with latest 1.8 version and 1.9 snapshots. It will not work when 1.9 released I guess. Some one cracked this. 
![image](https://cloud.githubusercontent.com/assets/11218527/9589742/0926c766-5039-11e5-9604-23f305c3b9cc.png)

**Comment by Orcunegeacar** [comment]
It's not a virus. The zip file is actually mcp 9.10 but some guys cracked or change it to 1.9 snapshots and they are saying its works.

**Comment by Orcunegeacar** [comment]
You can select which minecraft version you want to edit. (1.8.8 or snapshots). I opened decompile.bat it said 1.9 snapshots are not editable but you can see the source code. I didn't installed it because I deleted eclipse.

**Comment by Orcunegeacar** [comment]
I mean this is mcp 9.10 but you can edit 1.9 snapshots too. This is not official I guess.

**Comment by Orcunegeacar** [comment]
I scaned it with trojankiller. Not found anything I guess.

**Comment by 1337HaxorKiddie** [comment]
Can you give us a download vor something like that, it would be nice Form you. ;)
