### ISSUE TITLE
When I Launch Wurst 2.3 it crashes 

### ISSUE THREAD

**Issue by Awsomeguy660** [Wurst-Imperium/Wurst-Client#2070]
Every time I launch Wurst 2.3 it crashes my game immediatly

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.

**Comment by PixelMaster3D** [comment]
Same thing.
