### ISSUE TITLE
Question about packets...

### ISSUE THREAD

**Issue by RaizeWormwood** [Wurst-Imperium/Wurst-Client#2071]
Hello. Ok so you opened this window so you must want to know what the hell I want. And here it is!

Ok, so I want to know, if in time, it will ever be possible to make a Packet Sender, (As of what I know, no clients have this), so here's what I mean.

The ability to send server packets directly into a server's log/console. Like, a command, or a movement error, pretty much anything that can be a packet in some way. Could be used for a force-op, immediate server shut down, banning players, or also sending false movement packets for flying to make someone get kicked for flying. Stuff like that.

I am in no way requesting this, but merely asking if the wurst team thinks in any day it would be possible in a client. Maybe this could lead to an idea in the future. So please, let me know if this is possible or not.

EDIT: In a way you could think of this as a console grabber, but not directly a console grabber in this case.

**Comment by 1337HaxorKiddie** [comment]
I think this is Impossible, but as you said no one did this before.

**Comment by Alexander01998** [comment]
> Could be used for a force-op, immediate server shut down, banning players, or also sending false movement packets for flying to make someone get kicked for flying.

Packet's can't do that.

**Comment by PixelMaster3D** [comment]
This is also a question too.

**Comment by RaizeWormwood** [comment]
It was a question so..
