### ISSUE TITLE
Auto-Build Creator / Recorder

### ISSUE THREAD

**Issue by Janik020301** [Wurst-Imperium/Wurst-Client#2072]
An Auto-Build command, with that you can make your own autobuild scripts without any problems using an text editor.

It builds in the direction where you  looking at and makes the startpoint at an predefined point by the user.

**Comment by awakened-game** [comment]
Hmm, by the title I thought you meant something different, but you can already create auto-build scripts in any text editor. Maybe not CLI text editors though.

What I thought you meant, was add a Record Placement button to write the auto-build to a text file or in the chat.

**Comment by Janik020301** [comment]
I mean, its not very easy to write a script in a text editor.
It would be cool, when i could build something, it records it, and it could build it every time, like the record feature in the AndroidApp "Minebot" for Minecraft PE, but it writes it down to a auto-build script.

**Comment by bob80333** [comment]
Wouldn't this be just a watered down version of #817?

**Comment by BoomBoomLHack** [comment]
@bob80333 Maybe. But this one records player placing block & save it to an autobuild file.

**Comment by WurstContributor** [comment]
Duplicate #(INSERT @GummiBoat HERE)

**Comment by PixelMaster3D** [comment]
Similar to this issue: #817
