### ISSUE TITLE
can you make auto switcher customize able 

### ISSUE THREAD

**Issue by MichaelPekarek** [Wurst-Imperium/Wurst-Client#2073]
I Will like to have auto switch customizeable so I could use this with any thing if you can make this happen that will be amazing.

**Comment by linuxcodefire** [comment]
Umm?

**Comment by awakened-game** [comment]
I think AutoBlock should be added, similar to this but maybe a duplicate, not actually blocking like protecting from damage, but AutoBlock as in  when a stack of blocks run out, switch to the next stack in the hotbar.
