### ISSUE TITLE
Best Hack Client 

### ISSUE THREAD

**Issue by WindFenix** [Wurst-Imperium/Wurst-Client#2074]
I know this has nothing to do with the hack client but i just wanna say that you have made the best hack client that i have ever seen. it's simple to use, you are always active in the forums, and always taking suggestion. you have maximize my trolling experience in servers and made it soooo much easier compare to other clients. I just want to say thank you for making this Hack Client

I can't wait for what the future holds for Wurst

**Comment by linuxcodefire** [comment]
@Alexander01998

**Comment by awakened-game** [comment]
Heh, I agree, although that's kinda the point of Wurst, some features are the same, sure, but they are better, more stable and efficient.
The client has never let me down, and only ever crashed once, and that was on purpose so.... yeah.

Hopefully things will evolve so far that Wurst users are unbannable! (until its patched i guess) just like some private clients.

**Comment by Alexander01998** [comment]
Thanks for the feedback!

**Comment by pokeball99** [comment]
can we have maybe a "praise/vouch" label for stuff like this?
