### ISSUE TITLE
Can make throw work on Mineplex Appler kit

### ISSUE THREAD

**Issue by Artamiel** [Wurst-Imperium/Wurst-Client#2075]
Ye I wanna be able to throw like 16 apples at once at someone that would be cool

**Comment by linuxcodefire** [comment]
So throw like snowball but other objects?

**Comment by Artamiel** [comment]
like the appler kit in mineplex yes

**Comment by PixelMaster3D** [comment]
A throw bypass?

**Comment by Artamiel** [comment]
no
like be able to throw 24 apples in Bridges at someone
throw only works with right click

**Comment by PixelMaster3D** [comment]
throw as in drop apples or throw as in toss snowballs?

**Comment by EnderGamer21** [comment]
toss snoballs

**Comment by PixelMaster3D** [comment]
so you want to pelt them with apples?

**Comment by Artamiel** [comment]
I wanna pelt em with apples 24 at a time not nsowballs

**Comment by PixelMaster3D** [comment]
I understand that. You're trying to say that you just throw apples instead of dropping them. Like bypass item drop. Is this what you're saying?

**Comment by Artamiel** [comment]
no. You know the Bridges kit in Mineplex? Appler? I want to throw like 24
apples at once

**Comment by Alexander01998** [comment]
Wurst's Throw and FastPlace already work for any item. If it doesn't work on Mineplex, that means they blocked Throw and/or FastPlace.
