### ISSUE TITLE
Inventory Leak suggest

### ISSUE THREAD

**Issue by jens1o** [Wurst-Imperium/Wurst-Client#2076]
I want to suggest this Mod. So the Player are able to see what the other Player have in his Topbar and his arms, not via Chat, but via Hologram.

Like that. (This is a private client.)

![hack](https://cloud.githubusercontent.com/assets/11234139/9602139/6e9fc21a-50a6-11e5-876b-ea97e01130ae.png)

Sorry for my bad English :D

**Comment by jens1o** [comment]
oops, I am sorry, I created this in the wrong Category.

**Comment by Eyremba** [comment]
It is called ArmourESP

**Comment by mcccs** [comment]
.invsee?

**Comment by jens1o** [comment]
"not via Chat, but via Hologram."
@mcccs does this answer you're Question?

**Comment by solidshadow96** [comment]
Nah armor esp is better than invsee it lists all armor and wepons held but with the enchants beside it
