### ISSUE TITLE
item duplication

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#2077]
i see #1893 but in pc
something in survival thet duplicate an item or just give you ghost item (0 from it)

**Comment by 1337HaxorKiddie** [comment]
Impossible for servers.

**Comment by EnderGamer21** [comment]
@TheBoyIsHere  watch a video on how to get a item with 0 and in survival u can duplicate any item to get multiple

**Comment by PixelMaster3D** [comment]
You could use Cheat Engine to get many items.

**Comment by EnderGamer21** [comment]
yeah that too

**Comment by TheBoyIsHere** [comment]
the problme that i cant
everything needs to try many times and 1 from 100 times it will work
wurst cant add a mod thet do thet for us?

**Comment by MyzticalTekkno** [comment]
>You could use Cheat Engine to get many items.

@PixelMaster3D you can't use cheat engine for online hacking, and cheat engine only read the minecraft process (java.exe), not the server process...

**Comment by PixelMaster3D** [comment]
True, but it also tracks data made to the server. If you have an another program (don't ask me) then you can re-arrange data that the client sends.

**Comment by Gark0lym** [comment]
You cant change the amount serverside ...

**Comment by 1337HaxorKiddie** [comment]
@Gark0lym No shit sherlock.

**Comment by MyzticalTekkno** [comment]
> True, but it also tracks data made to the server. If you have an another program (don't ask me) then you can re-arrange data that the client sends.

@PixelMaster3D it doesn't tracks data made from the server, server is like a home, and you cant just edit the home if you wasnt the home owner, you gotta sneak in and cheat engine doesnt support data tracker, only support process watcher :stuck_out_tongue: and editing value of an entity is impossible, server arrange all automaticly, and if you edit the value of an entity, the server will change it back to the normal entity. Examp: editing 4 diablo to 64 diablo (keep in mind DiaBlo is Diamond Block), and the server thinks (hey, how could 4 diablo turned to 64 diablo??? *server reading the database book* nope! its still 4 *changed 64 diablo to 4 diablo*.

**Comment by Eyremba** [comment]
@Gark0lym is right. You could change the amount of things etc. in MC 1.4.6 and before as far as I remember, but since MC version 1.5.2 the items and ID's are fully serverside and can not be changed by the client.

**Comment by TheBoyIsHere** [comment]
so... how to dope glitch?

**Comment by PixelMaster3D** [comment]
Gark0lym wasn't your name banned. i get updates and this was your named was banned. and i also checked an ip and it said that it had two registered under that ip. And to answer MyzticalTekkno question. yes you cant just change it automatically. there is another force in play.
