### ISSUE TITLE
the Tracers make your hand (skin) colored .

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#208]
Example when i be Among a lot of players my skin colored According to the player near me ,if he was 

close my hand will be red and if he was Far from me my hand will be green .

**Comment by Alexander01998** [comment]
Working fine for me.

![](https://cloud.githubusercontent.com/assets/10100202/6653685/d4e11402-ca9b-11e4-9e8f-761dc242f692.png)

**Comment by GlitchHead** [comment]
no what he means in first person i have this problem to i have a weird trolling skin thats all white no other colors and at random times the hand will be the color of tracers like green or red its a bit weird

**Comment by Nitrogen-Dioxide** [comment]
Happens to me too, I thought  it was a Easter egg lel.

**Comment by xeZx** [comment]
Maybe he means that
(I have the bug just above the clouds)
![2015-03-15_10 39 36](https://cloud.githubusercontent.com/assets/11485682/6655396/bfadc526-caff-11e4-8f09-01a1390da37e.png)

**Comment by Nitrogen-Dioxide** [comment]
lets leave that as an Easter egg lel.
