### ISSUE TITLE
A 16 year old sayin hes gonna ban me

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2081]
i know hes like 6 or 7 but hes annoying and now searched yp the client is user name is 
DrunkMc-pnada  something

**Comment by BoomBoomLHack** [comment]
What are yout talking about?

**Comment by 1337HaxorKiddie** [comment]
Whats a yp?! You means ip?

**Comment by EnderGamer21** [comment]
oops i dinit mean yp it was a accdent

**Comment by EnderGamer21** [comment]
o

**Comment by EnderGamer21** [comment]
this is not important so i closed it

**Comment by 1337HaxorKiddie** [comment]
@EnderGamer21 Thank you :)
