### ISSUE TITLE
Auto .t Panic

### ISSUE THREAD

**Issue by Keepo123** [Wurst-Imperium/Wurst-Client#2082]
Today i was thinking about a feature that could allow players who use xray or nuker etc to not be able to be reported by other players by adding in an option that automatically disables all mods when a player gets in view distances of you (or with optional ranges). Unless they're added to your friends list.

additon = auto /spawn or /home or leave incase the server has the distance you see someone at really low. so if they get close they wont be able to see your name since you will be gone from there.

**Comment by 1337HaxorKiddie** [comment]
You can close this one yourself! :d

**Comment by solidshadow96** [comment]
Wow very smart thinking u got it from hack busters right? very smart though. it would be cool if anyone thats not on your friends list is near if auto panics

**Comment by Keepo123** [comment]
woofless his hacker busters ? :p i watch that but i got the idea when i was using nuker on an OP prison server and someone in the chat suddenly said to me turn around and he was right behind me. so it gave me the idea to prevent it by auto panic so if they are behind you you instantly stop.

**Comment by solidshadow96** [comment]
oh lol nice 
please add this feature
