### ISSUE TITLE
A Optifine or zoom add-on

### ISSUE THREAD

**Issue by SolitudePrincess** [Wurst-Imperium/Wurst-Client#2084]
You should make something like optifine on the hack

**Comment by EnderGamer21** [comment]
he cant optifine makes it too laggy i think or wasit something

**Comment by BoomBoomLHack** [comment]
Dupe: #2
![SearchForDupePlease]
(https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png)

**Comment by jens1o** [comment]
Wait, before closing. I think he mean the Zoom. Is this impossible? You cut the View. I want to have only this(Zoom). Not the others Features.

**Comment by pokeball99** [comment]
@jens1o he already has accepted in a separate issue( @gummiboat link the issue,can't be bothered to  look for it right now)

**Comment by mcccs** [comment]
Duplicate: #1861 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
