### ISSUE TITLE
Suggestion For LowFire!

### ISSUE THREAD

**Issue by Elephantlovr33X** [Wurst-Imperium/Wurst-Client#2085]
Ok welp!
When I Pvp, And I get shot or hit with fire aspect/Flame, I HATE the fire! it gets in my Way!
It makes me lag! Ik some Texture packs make it so the fire is low, but NOT ALL!
I would Like something Called LowFire, it works, by showing the Fire VERY low that is on you. 
Like very low! It would really Help me! and Other people! 
Add it if you can!
Thanks!

**Comment by Orcunegeacar** [comment]
?Do you mean you want anti fire?

**Comment by 1337HaxorKiddie** [comment]
I think he means the fire layer on screen

**Comment by Eyremba** [comment]
"I would Like something Called LowFire"

Only possible by using PvP ressource packs, this RP's use low fire.

**Comment by 1337HaxorKiddie** [comment]
Not only in Resource packs change able also with a moded client.

**Comment by PixelMaster3D** [comment]
What shes saying is Have where you can see visibly through the fire.
