### ISSUE TITLE
FastStart

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#2087]
When i click Play or Play offline Wurst (or 1.x.x) starts with 1 minute delay. I found a way to start in 10 seconds!

1) Open Minecraft Launcher
2) Launch Wurst
3) Don't quit Wurst! Go to versions/ Wurst
4) Select Natives-xxxxxxx with largest number
5) [Tick this box](http://windows.microsoft.com/en-us/windows7/prevent-changes-to-a-file-by-setting-it-to-read-only)
6) Quit Wurst.
7) See how fast it opens!

What do i want?
Can you add this option to Wurst Options pls? Wurst will be the first client with this option!

**Comment by 1337HaxorKiddie** [comment]
Nice.
