### ISSUE TITLE
The lag

### ISSUE THREAD

**Issue by TiddlyGinger** [Wurst-Imperium/Wurst-Client#2090]
When I play a mine game on a sever or on some servers, I come a cross really bad lag.

**Comment by labcraft59** [comment]
Lol how many fps? I have about 0 fps ALWAYS.

**Comment by pokeball99** [comment]
dupe #2 (i somewhat agree that with those of us that have the less than perfect pc/laptops that can't spend ~1k plus for a gaming pc do have trouble,but @Alexander01998 is somewhat stubborn and will not add optifine,and while i do agree with his reasoning,it would be nice)
