### ISSUE TITLE
1.9 cooldown pvp

### ISSUE THREAD

**Issue by castelbuilder123** [Wurst-Imperium/Wurst-Client#2097]
On the server timolia.de is a gamemode 1vs1, you can enable a feature like in 1.9 a cooldown. only if the cooldown is over you do full dmg. please add a killaura mode for this

**Comment by TheBoyIsHere** [comment]
wurst is 1.8 cilent when 1.8 will come they meybe will do something :smile:

**Comment by castelbuilder123** [comment]
and timolia is a 1.8 server
