### ISSUE TITLE
Jesus affects items and mobs

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2098]
Jesusu affects items and mobs in singleplayer whneever i try ro run awy it happens mobs and if i kill them in watter the rotten flesh floatss instead of falling
i have wurst  2.3.2

**Comment by EnderGamer21** [comment]
anyone gonna coment on this issue

**Comment by PixelMaster3D** [comment]
i cant try at school but maybe later when i test this

**Comment by EnderGamer21** [comment]
ok
