### ISSUE TITLE
Github Protected Freature

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#2099]
Please use this to protect on how some mods work, so you wont become Mojang:copyright: top hack check. And Nocheatplus as well. They look at the top hack clients that does this.
 https://github.com/blog/2051-protected-branches-and-required-status-checks

Repost: I have noticed the mistake in the link.

**Comment by solidshadow96** [comment]
OMG @Alexander01998 Please set up a secure website like this so we can still use Wurst make it so we have to add a valid minecraft username that uses wurst to enter so its harder for mojang

**Comment by pokeball99** [comment]
u guys dont understand how this works.....

**Comment by PixelMaster3D** [comment]
What i'm saying is that you secure some projects so they cant look at the source you made in the past. This will prevent anybody from checking the sources and make it harder to look through and know what the problem is.

**Comment by PixelMaster3D** [comment]
Ill have this closed until i see the response they reply back to me.

**Comment by Alexander01998** [comment]
> This will prevent anybody from checking the sources and make it harder to look through and know what the problem is.

That is wrong. The article that you linked to is entirely about preventing accidental force-pushes. These protected branches are still open source and still visible by anyone.

**Comment by PixelMaster3D** [comment]
I have understood that and i am still doing research. Please be patience for a sec.

**Comment by PixelMaster3D** [comment]
There is a way but you have to pay for by going to billing page. https://github.com/Wurst-Imperium/Wurst-Client/milestones . I have seen that you have to pay for this so i offer $100 in transaction to an account that you have to support this.
