### ISSUE TITLE
Invisibility

### ISSUE THREAD

**Issue by CactusOwnage** [Wurst-Imperium/Wurst-Client#2101]
Does the invisibility not work anymore? I tried it on my own 1.8 vanilla server and it didn't work. But I got the message "You should now be invisible"

**Comment by BoomBoomLHack** [comment]
i think it only work in pure 1.8 (no 1.8.x)

**Comment by Eyremba** [comment]
@CactusOwnage it makes you only invisible for 1 another player which is in your near. If there is no player online except for you, nothing will happen.

**Comment by Alexander01998** [comment]
What @Eyremba said.
