### ISSUE TITLE
Question to all: Lagg Hack

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#2102]
Could you control what you send to the server

EX.

 Running up a path (activate Lagg) Run down a path and and chose a spot in minecraft (de activate Lagg) and it will send certain coordinates on where you are.

**Comment by PixelMaster3D** [comment]
For better explanation:

Being chased by PVP'er and want to get away from him/her. Activate Lagg, run all the way to the other side and deactivate Lagg, then that data will be sent to the server. And when the looks, he dosent see you.

**Comment by CactusOwnage** [comment]
Thats basically blink from what I can understand.

**Comment by PixelMaster3D** [comment]
Yeah, but why not control what you send to the server?

**Comment by Creeperman8362** [comment]
wel if u were running away you would get hit and then teleport, and then NCP+ sends you back.
