### ISSUE TITLE
Hand Item Hide 

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2104]
Hides the item in the hand 
example : I hold a diamond sword in my hand but with this hack set my hand empty (Hide) or put something else like dirt block ... to make others dont see that I held diamond sword to kill someone :D

Thanks !

**Comment by PixelMaster3D** [comment]
From what i know, and this may be false but, i dont think thats possible.

**Comment by WurstContributor** [comment]
@PixelMaster3D It could be possible. By making the player look like he is holding something by is actually holding their fist. The second they swing/right click It switches to that item

**Comment by Eyremba** [comment]
@PixelMaster3D it is possible, there is already a client with this feature. As far as I know it is called "ItemDisguise" or "ItemSpoof" in this client.

**Comment by PixelMaster3D** [comment]
Then nvm rhe comment.
