### ISSUE TITLE
Next Wurst Features

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2105]
What is the next wurst update features ?
I Really Hard Waiting for it ;)

**Comment by PixelMaster3D** [comment]
you can check by looking at the milestones https://github.com/Wurst-Imperium/Wurst-Client/milestones

**Comment by Al00X** [comment]
All of this accepted suggestions will be added to next wurst ??

**Comment by Al00X** [comment]
some of this accepted not added yet :(

**Comment by PixelMaster3D** [comment]
What he has accepted is what he might put into wurst.
