### ISSUE TITLE
alts idea

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#2106]
a botton on alts thats back you to normal player (the player u start with him).

**Comment by BoomBoomLHack** [comment]
Correction:
```A button on the alt manager screen that switch back to the original player that you start up Minecraft with.```
Useful for switching between main & alt accounts.

**Comment by TheBoyIsHere** [comment]
yes!
my english is bed...

**Comment by 1337HaxorKiddie** [comment]
bad*
