### ISSUE TITLE
Leaked Triggerbot

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#2108]
This is a triggerbot that is custom-coded. I was wondering if you can find this useful to Bypass KillAura.

https://www.mediafire.com/?t4lqzuxi84i3851

**Comment by BoomBoomLHack** [comment]
BetterHorses? xD

**Comment by GlitchHead** [comment]
@PixelMaster3D do you just search up random minecraft hacks and copy the first link you see and post it here?

**Comment by Nitrogen-Dioxide** [comment]
xD

**Comment by Eyremba** [comment]
@BoomBoomLHack 
@GlitchHead 
@Nitrogen-Dioxide 

Really dudes? Nobody of you knows the "BetterHorses" GhostClient?! I am frightened, that nobody of you knows this GhostClient. It is basically a HackClient as a Forge Mod, with another name for case of screensharing etc.

**Comment by PixelMaster3D** [comment]
This was from a friend who doesn't want it anymore. I thought this might be useful.

**Comment by Alexander01998** [comment]
> I was wondering if you can find this useful to Bypass KillAura.

Killaura already bypasses NoCheat+. I fixed that in v2.3.1

**Comment by Nitrogen-Dioxide** [comment]
@PixelMaster3D 

Killaura is just crasy now, it remembers latemod killaura,
