### ISSUE TITLE
X-Ray always showing non-solid blocks

### ISSUE THREAD

**Issue by MinecraftZip** [Wurst-Imperium/Wurst-Client#211]
When I use xray I can see fences, grass, mushroom, leaves, and webs. I had them disabled so I shouldn't be seeing them.

**Comment by eveythingistaken** [comment]
This was posted a month ago. There have been like 3-5 updates since then. Why is it not fixed

**Comment by TekkitCommando** [comment]
Either code it yourself or wait for @Alexander01998 to fix it when he can, Complaining does not fix issues but just annoys people

**Comment by OMGchangeMYusername** [comment]
@eveythingistaken there are even older suggestions but he's free whether to add them now or add them two years later.
but that doesn't mean asking "why is it not fixed?" is wrong,you may ask but you have to be patient too.

**Comment by eveythingistaken** [comment]
It seems like an easy fix that's all.

**Comment by TekkitCommando** [comment]
I understand, it will be gotten to eventually

**Comment by pokeball99** [comment]
Is there any plan of this being fixed?
