### ISSUE TITLE
Add an refresh session button

### ISSUE THREAD

**Issue by BoomBoomLHack** [Wurst-Imperium/Wurst-Client#2110]
Use for renewing your session without restarting Minecraft.

**Comment by GlitchHead** [comment]
goto the alt manager and click "use" again or use direct login.

You should also change your password people get invalid session when someone else logs in to them.

**Comment by DataPools** [comment]
@GlitchHead Not always, it can happen if you have went to long without renewing your session, or you have simply logged in on another computer
