### ISSUE TITLE
Default Blink keybind

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#2113]
Blink is a essential hack, and the **Z** keybind is one of the best for that.

So, this makes people use it more often (since not so much know that it even exists) .

**Comment by awakened-game** [comment]
so bind it to Z if you want to, nothing stopping you, i have mine bound to B.

**Comment by Alexander01998** [comment]
<kbd>Z</kbd> is already bound to Sneak.
I use <kbd>V</kbd> for Blink, but didn't add it to the defaults because that would be annoying for TeamSpeak users, as most of them use <kbd>V</kbd> as their push-to-talk key.

**Comment by awakened-game** [comment]
i use Ctrl+T for my push-to-talk, but it kinda collides with the built in hotkeys that you cant disable, its ok if TS is minimized or out of focus though.

**Comment by Eyremba** [comment]
"Z" is not really good for Blink because you must be able to toggle it with one hand during you walk etc. That's the reason why I have Blink also on "V" like @Alexander01998
