### ISSUE TITLE
Killaura and bowaimbot dont target people on ur team

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#2115]
The game detects your team, and wont try to attack ppl on your team This would be a cool suggestion.

**Comment by awakened-game** [comment]
Uuuumm.. this is already a feature, for a while now, just add them to your friends list, middle-clicking your friends is the fastest way to add them, their name, bounding box and tracer line will all turn blue, i enabled, then they wont be targeted.

**Comment by TheIonosphere** [comment]
For small teams it is possible to temporarily add them each to the friends list, but what if you are playing a game with a hundred people on each team and it changes every round?

The main difficulty is that different games use different methods of identifying who is on each team, red/blue names, yellow/green etc.

**Comment by Creeperman8362** [comment]
@awakened-game i dont have a middle click button, and it takes too much work
