### ISSUE TITLE
Add GUI For .give and .potion

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2118]
Hi , Can you add GUI for .give and .potion ?
this can be  very good and :star: special :star: 
this feature will make .give and .potion very faster use and easier ... 

thankYou

**Comment by awakened-game** [comment]
i guess you could clone the creative inventory for the .give GUI, but i cant imagine what a .potion GUI would do or have.

**Comment by Al00X** [comment]
a GUI like this ... 
![gui](https://cloud.githubusercontent.com/assets/12069672/9698579/7aa54574-53d2-11e5-98c2-e67a9ffe82ee.png)

Very Ugly Paint lol :D , but this is just Suggestion ;)
if alexander add it wurst will be great

**Comment by PixelMaster3D** [comment]
An easy way to novices.

**Comment by Al00X** [comment]
:| , i know it's take some time to create this , i just give this suggestion for better wurst !

**Comment by pokeball99** [comment]
Dupe of....one second let me get it
