### ISSUE TITLE
.edit command !

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2119]
Hi , .edit command will change : Name , enchant , effect , (nbt things) etc ....
this command is like give but this will just edit the current item ...
also for potions 

Thanks !

**Comment by awakened-game** [comment]
i /think/ this is a dupe, but its still a good idea that many would want

**Comment by MyzticalTekkno** [comment]
@awakened-game yeah, that is a cool idea, higher than a good idea xD, and it can edit any entity easily without using .give / .potion
