### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2120]
Where I can see the full list of wurst ?

**Comment by Alexander01998** [comment]
There is an outdated list at http://www.wizardhax.com/wurst/, but no up-to-date list anywhere.

I think we should add a `/features` page on https://www.wurst-client.tk/.

**Comment by Al00X** [comment]
this is nice alexander :D thankyou ! wurst is greatest client I ever seen ;)

**Comment by awakened-game** [comment]
yeah the in-game command isn't very useful, as it doesn't give much info at all
