### ISSUE TITLE
Oops , Alt manager reset always BUG :(

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2122]
Hi , when I add alts to wurst then I restart game and click on alt manager message comes : want to add random alts :\ ? , and my all custom alts gone ...
can you fix this bug .. ? or what is wrong with it ?

**Comment by awakened-game** [comment]
Maybe a permissions issue with write access to that directory, try changing the game location in the profile settings

**Comment by Nitrogen-Dioxide** [comment]
@Al00X 

#570 Have Alexander explaining how to fix.

**Comment by Al00X** [comment]
thankyou !
