### ISSUE TITLE
Request! Change the Players!

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#213]
In this title, I mean what about changing the players' cameras. Example: My Username is XXnotchXX
I want to change cameras with XXherobrineXX. I can control him but he can't. He's gonna think,he's lagging so bad.

**Comment by Orcunegeacar** [comment]
Also there is a plugin too. I guess its icu or something like that

**Comment by Alexander01998** [comment]
This is only available as a PlugIn because it's only possible as a PlugIn.

In a nutshell: A player on a server can only control himself while the server can control all players.

**Comment by Nitrogen-Dioxide** [comment]
That is not possible :'D
