### ISSUE TITLE
SlowHunger

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#2132]
It slows down hunger allowing you to live sprint ect for more time. Just like timer but only on hunger?

**Comment by Alexander01990** [comment]
Great idea, I think I have to send quite a lot C03PlayerPackets

**Comment by Alexander01990** [comment]
I'll try it, with the worldguard settings, maybe it works ;)

**Comment by Alexander01990** [comment]
It doesnt work, i think its impossible

**Comment by ayciate** [comment]
Damn. What about without wg?

**Comment by Alexander01990** [comment]
What do you mean with "wg"?

**Comment by ayciate** [comment]
Worldguard

**Comment by Alexander01990** [comment]
I try to import worldguard to my client, maybe it works :) But it takes much time!

**Comment by Alexander01990** [comment]
Have you an idea, how it works?

**Comment by ayciate** [comment]
Not very much of a coder XD
But maybe instead of your hunger you could eat but it wouldn't consume the item? Maybe

**Comment by PixelMaster3D** [comment]
Like saying 1/7 of a bread bread = 3 lives restored.

**Comment by ayciate** [comment]
I guess so

**Comment by Eyremba** [comment]
There are already 2 clients with "Anti-Hunger" features which slows down your hunger and you get really less hunger, so it seems to be possible.

**Comment by PgBiel** [comment]
I agree! Can't wait to see that appear to the cliente.

**Comment by ayciate** [comment]
Whoop whoop :dancers:
