### ISSUE TITLE
Invincibility Mod

### ISSUE THREAD

**Issue by danielz3d** [Wurst-Imperium/Wurst-Client#2134]
I have an idea that could be added to the Wurst client, invincibility. While active you cannot take any damage, similar to god mode in the plugin essentials. This could be put in the category: Misc. Thanks for reading, I hope it's added!

**Comment by GlitchHead** [comment]
Impossible as of right now sadly...

**Comment by solidshadow96** [comment]
no its possiible
alexander wont add it but it makes it so people cant touch you or get near you plus there is auto eat+fast eat+regen which basically makes it so you take damage but regain it instantly so u kinda take no damage
