### ISSUE TITLE
autobuild problem

### ISSUE THREAD

**Issue by FlappyVeus** [Wurst-Imperium/Wurst-Client#2137]
in server that dont have nocheat+ autobuild is not working okey. its places only 10% of all autobuild,for example sphere is only 3 blocks. with yescheat+ all is working okey but its longer. How can i instantly spawn autobuild?

**Comment by HeartOfShrapnel** [comment]
They have custom nocheat or different plugins. For now you'll have to deal with it, because there are limitations.
