### ISSUE TITLE
.head

### ISSUE THREAD

**Issue by FlappyVeus** [Wurst-Imperium/Wurst-Client#2138]
command: ,head 'nick' , instead of .give 397 1 3  {SkullOwner:"_"}  for instant get heads

**Comment by mcccs** [comment]
#1186 ![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by TheBoyIsHere** [comment]
meybe on creative?
