### ISSUE TITLE
Nocheat+ checker

### ISSUE THREAD

**Issue by Wikiwiki007** [Wurst-Imperium/Wurst-Client#2139]
It would be cool if the auto server adder could check if the server have a nocheat plugin

**Comment by Eyremba** [comment]
Invalid because duplicate #431

![bba4482e-36ed-11e5-8536-77bb1fca1d7e](https://cloud.githubusercontent.com/assets/13738234/9703924/1504a900-5493-11e5-80af-cc25fa736f0f.png)

**Comment by Wikiwiki007** [comment]
i searched "nocheat+ checker" and i got ne results

**Comment by Eyremba** [comment]
@Wikiwiki007 don't be a dumb and search for "nocheat"....

**Comment by awakened-game** [comment]
i do this manually, if i type /ncp and it says "no permission" or similar, its obviously installed, if it says "unknown command" it is not

**Comment by Eyremba** [comment]
@awakened-game NCP gives you the same "Unknown command" message out like other plugins. So you can not detect it this way.

**Comment by awakened-game** [comment]
@Eyremba the default unknown command message, "Unknown command. Try /help for a list of commands" i have never seen a plugin say that before, ncp never has.
