### ISSUE TITLE
Is Click Gui deleted?

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#214]
I didn't read the features a lot but when I click LEFTCONTROL (my default button for click gui) It's saying that. 
![image](https://cloud.githubusercontent.com/assets/11218527/6658401/d90adaf6-cb70-11e4-9b58-f969318b0818.png)

**Comment by Orcunegeacar** [comment]
I tried the change the button too but nothing happens

**Comment by Alexander01998** [comment]
Post your keybind list (default: `.minecraft\wurst\keybinds.json`).

**Comment by Orcunegeacar** [comment]
{
  "B": ".t fastbreak",
  "C": ".t fullbright",
  "F": ".t fastplace",
  "G": ".t flight",
  "GRAVE": ".t speednuker",
  "H": ".t /home",
  "J": ".t phase",
  "K": ".t multiaura",
  "L": ".t nuker",
  "R": ".t killaura",
  "RSHIFT": ".t clickgui",
  "U": ".t freecam",
  "X": ".t x-ray",
  "Z": ".t sneak"
}

**Comment by Orcunegeacar** [comment]
It's still doing like that when I downloaded 1.6.1 or 1.7

**Comment by Orcunegeacar** [comment]
This is the options.json file 
{
  "autoReconnect": false,
  "cleanupFailed": false,
  "cleanupOutdated": true,
  "cleanupRename": true,
  "cleanupUnknown": true,
  "forceOPDontWait": true,
  "middleClickFriends": true,
  "spamFont": false,
  "renameForceOPEvenThoughTheNameIsTechnicallyCorrect": true,
  "WIP": true,
  "wurstNews": true,
  "arrayListMode": 0,
  "autobuildMode": 1,
  "targetMode": 0,
  "fastbreakMode": 0,
  "forceOPDelay": 1000,
  "nukerMode": 1,
  "searchID": 116,
  "serverFinderThreads": 64,
  "spamDelay": 1000,
  "throwAmount": 16,
  "forceOPList": "C:\\Users\\Win7\\AppData\\Roaming\\.minecraft\\wurst"
}

**Comment by Orcunegeacar** [comment]
And this is the modules.json

{
  "Annoy": {
    "enabled": false
  },
  "AntiAFK": {
    "enabled": true
  },
  "AntiBlind": {
    "enabled": false
  },
  "AntiKnockback": {
    "enabled": false
  },
  "AntiSpam": {
    "enabled": false
  },
  "ArenaBrawl": {
    "enabled": false
  },
  "AutoArmor": {
    "enabled": false
  },
  "AutoFish": {
    "enabled": false
  },
  "AutoMine": {
    "enabled": false
  },
  "AutoRespawn": {
    "enabled": false
  },
  "AutoSign": {
    "enabled": false
  },
  "AutoSprint": {
    "enabled": false
  },
  "AutoSteal": {
    "enabled": false
  },
  "AutoSwitch": {
    "enabled": false
  },
  "AutoTool": {
    "enabled": false
  },
  "AutoWalk": {
    "enabled": false
  },
  "BaseFinder": {
    "enabled": false
  },
  "Blink": {
    "enabled": false
  },
  "BowAimbot": {
    "enabled": false
  },
  "BuildRandom": {
    "enabled": false
  },
  "BunnyHop": {
    "enabled": false
  },
  "ChestESP": {
    "enabled": false
  },
  "ClickGUI": {
    "enabled": false
  },
  "Criticals": {
    "enabled": false
  },
  "Derp": {
    "enabled": false
  },
  "Dolphin": {
    "enabled": false
  },
  "Drop": {
    "enabled": false
  },
  "FastBreak": {
    "enabled": false
  },
  "FastBow": {
    "enabled": false
  },
  "FastEat": {
    "enabled": false
  },
  "FastLadder": {
    "enabled": false
  },
  "FastPlace": {
    "enabled": false
  },
  "FightBot": {
    "enabled": false
  },
  "Flight": {
    "enabled": false
  },
  "Follow": {
    "enabled": false
  },
  "AuthMeCracker": {
    "enabled": false
  },
  "Freecam": {
    "enabled": false
  },
  "Fullbright": {
    "enabled": true
  },
  "Glide": {
    "enabled": false
  },
  "GoTo": {
    "enabled": false
  },
  "Headless": {
    "enabled": false
  },
  "HealthTags": {
    "enabled": false
  },
  "HighJump": {
    "enabled": false
  },
  "/home": {
    "enabled": false
  },
  "InstantBunker": {
    "enabled": false
  },
  "Invisibility": {
    "enabled": false
  },
  "Invsee": {
    "enabled": false
  },
  "ItemESP": {
    "enabled": false
  },
  "Jesus": {
    "enabled": false
  },
  "Jetpack": {
    "enabled": false
  },
  "Kaboom": {
    "enabled": false
  },
  "Killaura": {
    "enabled": false
  },
  "KillauraLegit": {
    "enabled": false
  },
  "Liquids": {
    "enabled": false
  },
  "LSD": {
    "enabled": false
  },
  "MassTPA": {
    "enabled": false
  },
  "Miley Cyrus": {
    "enabled": false
  },
  "MobESP": {
    "enabled": false
  },
  "MultiAura": {
    "enabled": false
  },
  "NameProtect": {
    "enabled": false
  },
  "NameTags": {
    "enabled": false
  },
  "NoFall": {
    "enabled": false
  },
  "NoHurtcam": {
    "enabled": false
  },
  "NoSlowdown": {
    "enabled": false
  },
  "NoWeb": {
    "enabled": false
  },
  "Nuker": {
    "enabled": false
  },
  "NukerLegit": {
    "enabled": false
  },
  "Overlay": {
    "enabled": false
  },
  "Panic": {
    "enabled": false
  },
  "Path": {
    "enabled": false
  },
  "Phase": {
    "enabled": false
  },
  "PlayerESP": {
    "enabled": false
  },
  "PlayerFinder": {
    "enabled": false
  },
  "ProphuntESP": {
    "enabled": false
  },
  "Protect": {
    "enabled": false
  },
  "Pwnage": {
    "enabled": false
  },
  "Regen": {
    "enabled": false
  },
  "RemoteView": {
    "enabled": false
  },
  "Search": {
    "enabled": false
  },
  "Sneak": {
    "enabled": false
  },
  "Spammer": {
    "enabled": false
  },
  "SpeedNuker": {
    "enabled": false
  },
  "Spider": {
    "enabled": false
  },
  "Step": {
    "enabled": false
  },
  "Taco": {
    "enabled": false
  },
  "Throw": {
    "enabled": false
  },
  "Timer": {
    "enabled": false
  },
  "Tracers": {
    "enabled": false
  },
  "TriggerBot": {
    "enabled": false
  },
  "TrueSight": {
    "enabled": false
  },
  "X-Ray": {
    "enabled": false
  },
  "YesCheat+": {
    "enabled": false
  },
  "AutoBuild": {
    "enabled": false
  }
}

**Comment by Orcunegeacar** [comment]
I want to delete and install it again but it won't let me. If you can't help me I'm going to try delete it with  unlocker

**Comment by Orcunegeacar** [comment]
hello!?

**Comment by Orcunegeacar** [comment]
Need a help over here :smile:

**Comment by Alexander01998** [comment]
Working fine for me, even if I change it to `RSHIFT`.

**Comment by Orcunegeacar** [comment]
the default one was control right?

**Comment by Orcunegeacar** [comment]
I mean ctrl

**Comment by Alexander01998** [comment]
`LCONTROL`

**Comment by Orcunegeacar** [comment]
It was the default one. I changed it to RSHIFT when my wurst version was 1.6 or 1.6.1 ..... 

I downloaded 1.7 then  the click gui  went away from me

**Comment by Orcunegeacar** [comment]
Now I write commands :sad: 😭 .t fullbright, .t authmecracker

**Comment by Nitrogen-Dioxide** [comment]
Delete the wurst folder... and install it again, it should fix. I think :hand:

**Comment by GlitchHead** [comment]
RSHIFT?

**Comment by OMGchangeMYusername** [comment]
lol the `but it works on my machine!` label is funny :laughing:

**Comment by pokeball99** [comment]
i lol'ed on the sight of that too

**Comment by Orcunegeacar** [comment]
I tried everything! I deleted ALL wurst files and json files and java files. EVERYTHING! I uninstalled it. I installed it again. Nothing happens.

**Comment by Orcunegeacar** [comment]
Still saying nothing. Should I write .t clickgui or .t ClickGui or ClickGUI

**Comment by Orcunegeacar** [comment]
OK GUYS I FIXED! THE PROBLEM WAS... IN MY KEYBINDS. IT WAS LIKE THIS! ".t clickgui" BUT I CHANGED TO ".t ClickGUI" AND IT WORKED!
