### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by The-creeper-cow** [Wurst-Imperium/Wurst-Client#2140]
it would be handy if you intergrate a minimap that would be awesome i hope you can do it

**Comment by TheBoyIsHere** [comment]
duplicate
but i dont think someone was think it will be uesful
i like it!

**Comment by mcccs** [comment]
#238
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
