### ISSUE TITLE
NbtEditor

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2142]
QUESTION !

is There any NbtTag editor like All U Want ( FOR 1.8 )

I Saw " .give " and " .potion "  but I want something easier ( I suggested to put GUI for .give and .potion )
but , not accepted yet :smile: 

mod for litemod , forge or anything , I saw some people using nbtedit in game 

thanks

**Comment by Alexander01990** [comment]
Bad idea, but thanks

**Comment by Al00X** [comment]
@Alexander01998 Excuse Me , but this is Question :smile:

**Comment by Alexander01998** [comment]
This is not a forum, please don't use it as one.

**Comment by PixelMaster3D** [comment]
No there's is not.
