### ISSUE TITLE
Theme changer

### ISSUE THREAD

**Issue by TomBMTH** [Wurst-Imperium/Wurst-Client#2143]
It's been on a few hacked clients, where you can change the theme of the GUI, usually to other type of hacked clients (Huzuni, Metro, Nodus etc). To be honest, I don't really like the style of Wurst GUI, so adding this can be good customisation to make it suit the user.

**Comment by pokeball99** [comment]
Can't remember if this is a dupe or not,either way would love it

**Comment by mcccs** [comment]
#1374 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
