### ISSUE TITLE
Can't find 'Chat' hacks when i press Ctrl 

### ISSUE THREAD

**Issue by LocalFluf25** [Wurst-Imperium/Wurst-Client#2148]
When i press Ctrl to find the hacks i want to turn on i can't find Chat :( Please help

**Comment by EnderGamer21** [comment]
to find what caht the gui?

**Comment by WurstContributor** [comment]
Make your gui smaller.

**Comment by Alexander01998** [comment]
If you can't find it, you can reset your GUI by deleting `gui.json` in `%appdata%\.minecraft\wurst`.
