### ISSUE TITLE
add any symbols

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2149]
u can in chat becasue thers a thing my compuet does it change keybinds so when i press shift and this '
button it turns into a heart i seacrched up symbols but there are not many symbols

**Comment by awakened-game** [comment]
On windows, Press Win+R and type "charmap", make sure the font at the top is set to Arial, most, if not all symbols here will work, keybind any as needed.

**Comment by labcraft59** [comment]
۞۝۩₪▓☺☻☼
