### ISSUE TITLE
Backpack

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2150]
dont know if its impossible
but this is the thing u can put a chest down put items in it break it and it wont fall out it will be in till u place it down

**Comment by linuxcodefire** [comment]
it should be possible.

**Comment by EnderGamer21** [comment]
yay!

**Comment by EnderGamer21** [comment]
can u comment on my other issuse add symbols

**Comment by Eyremba** [comment]
Would only be possible in GameMode 1 with NBT manipulations.

**Comment by 1337HaxorKiddie** [comment]
@Eyremba yes.

**Comment by EnderGamer21** [comment]
it fine
