### ISSUE TITLE
Add Something like QuickBow suggestion

### ISSUE THREAD

**Issue by Elephantlovr33X** [Wurst-Imperium/Wurst-Client#2153]
So!
Something called QuickBow that would go into the Combat area. But the point of adding is this, for your Bow to Charge Up Quicker. It would come it handy when your pvping with bows, It would do more damage to the player, if its charged up more. Some people (like me) Don't like to use Aimbot. But Need something for bow hacks. I would like something like that to be added, where your Bow charged up quicker. 
Thank you!

**Comment by awakened-game** [comment]
Already implemented, FastBow.
Unless you mean instant pulback, but no rapid fire, in that case, the following should be added:

.fastbow mode normal
.fastbow mode single

**Comment by EnderGamer21** [comment]
not implmented she means pullback not rapidfire

**Comment by PgBiel** [comment]
@EnderGamer21 Yuppers.
@awakened-game "Unless you mean instant pullback, but no rapid fire[...]" Yep. That's what she meant.
