### ISSUE TITLE
.stealsession <username>

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#2158]
This will give you their session id if they are on the same server

.stealsession Steve wil copy Steve's session ID to my clipboard

**Comment by 1337HaxorKiddie** [comment]
I think thats Impossible, because the Server wont give you the Information about this.

**Comment by Eyremba** [comment]
This is impossible. The server NEVER has the session ID, only the Minecraft Launcher.
