### ISSUE TITLE
.getip <username>

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#2159]
Gets someones IP address.

.getip Steve

[Wurst] Steve's IP address is 127.0.0.1

**Comment by Eyremba** [comment]
This is impossible.

**Comment by solidshadow96** [comment]
some what it is possible but hard

**Comment by kcxx** [comment]
Can't you make skulls with custom url, and some serverside script? I think it works 1.8.4 and below.

**Comment by Alexander01998** [comment]
> Can't you make skulls with custom url, and some serverside script? I think it works 1.8.4 and below.

That's actually a pretty good idea, but it couldn't tell what IP belongs to what player unless there is only one player seeing the skull.

**Comment by BarneyisFat** [comment]
Can Easily ddos thats fucked up

**Comment by pokeball99** [comment]
dont think this can work,didn't they whitelist the skin server only? i dont think version would matter
