### ISSUE TITLE
InventoryWalk

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#216]
Like. when you open a inventory, you cant walk, the same as other types of storage. This mod disable the "stop". Like a no slowdown for open something and chat.

**Comment by OMGchangeMYusername** [comment]
i think i saw it on other client it's called inventory walk.
i don't know if it works with chests but that seems very good if added to wurst

**Comment by OMGchangeMYusername** [comment]
ok Alexander i wanna ask you about this,are you planning to "confirm" this? coz this seems awesome tbh! but ofcourse it's better in **Wurst** :heart: 
![invwalk](https://cloud.githubusercontent.com/assets/10786571/7610280/3d0e308e-f984-11e4-8d3e-4bc53763aff1.gif)
