### ISSUE TITLE
Wurst-Bot Session Login

### ISSUE THREAD

**Issue by awakened-game** [Wurst-Imperium/Wurst-Client#2160]
Could you add an option to Wurst-Bot to login with a session ID, like the main client?
Would be handy.

**Comment by 1337HaxorKiddie** [comment]
Good idea!

**Comment by awakened-game** [comment]
What is your avatar? Not sure if it's a grub from Flushed Away or a Plonster

**Comment by 1337HaxorKiddie** [comment]
Idk how this Avatar is called. Sry.

**Comment by solidshadow96** [comment]
same lol

**Comment by Alexander01990** [comment]
Im waiting for the GarPloit update

**Comment by 1337HaxorKiddie** [comment]
@Alexander01990 Faker.

**Comment by Alexander01990** [comment]
@1337HaxorKiddie You are the Faker!

**Comment by 1337HaxorKiddie** [comment]
@Alexander01990 why iam?

**Comment by MissgeburtAlexander** [comment]
Copy&Pasting wurde erfolgreich durchgeführt!

**Comment by 1337HaxorKiddie** [comment]
@MissgeburtAlexander Reported. Please don´t insult anyone!

**Comment by solidshadow96** [comment]
Can someone give me the directory to the session id i cant fund one PLEASE!!??

**Comment by PixelMaster3D** [comment]
I will please hold on.
