### ISSUE TITLE
.head

### ISSUE THREAD

**Issue by Jonnie32004** [Wurst-Imperium/Wurst-Client#2161]
you should be able to do .head <playername> to get their head thats it

**Comment by mcccs** [comment]
#1186 ![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by Alexander01990** [comment]
.skin head

**Comment by 1337HaxorKiddie** [comment]
@Alexander01990 No, its not. There is no command like .head or .skin

**Comment by EnderGamer21** [comment]
@Alexander01990  no there isnt

**Comment by Jonnie32004** [comment]
oh sry

**Comment by 1337HaxorKiddie** [comment]
@Jonnie32004 No problem just search for it next time :)
