### ISSUE TITLE
crash and kept hacks on the normal minecraft account 

### ISSUE THREAD

**Issue by Deadlyduck** [Wurst-Imperium/Wurst-Client#2162]
I crashed while on wurst client and then i logged on with my normal nonhacked client and i kept my full bright on. so then i logged off onto the hack client and clicked the panic button and logged back on with my normal minecraft account and it was still there i dont know if you can fix this but if you can please fix.

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.

**Comment by beppe9000** [comment]
to fix the fullbright thing you could try changing the gamma slider in the settings

**Comment by PgBiel** [comment]
I already experienced that... I don't remember the fix, but I'm pretty sure it IS real: The fullbright keeps on the normal MC Client.

**Comment by PgBiel** [comment]
Let me try to explain what Deadlyduck is trying to say.
1st: "Crash": I have no idea, he didn't even TRY to explain that friggin crash.
2nd: "Kept on MC Client": Yes, what he means is: He activated the FullBright hack, in which would make it so he could see EVERYTHING, like if with night vision. However, he LEFT the client, and the FullBright hack's effects were active at the NORMAL CLIENT, not the HACKED CLIENT. So basically, he means the hack is still active in the normal client and he tried to disable it and he tried the PANIC button that disables all hacks, so yeah.
I hope you get it, Alex. ~
