### ISSUE TITLE
Filled Chest Esp

### ISSUE THREAD

**Issue by championriven** [Wurst-Imperium/Wurst-Client#2163]
So this is probably a duplicate, but I was too lazy to look and see, but if it's not, is it possible to make a filled chest esp? Because there is nothing more frustrating than finding a protected base and after days and hours of work you finally get into it and find.... EMPTY CHESTS! O.o

**Comment by Eyremba** [comment]
No it is not possible.

**Comment by pokeball99** [comment]
Yea,the inventory of chest and other tile enties are stored server sided

**Comment by 1337HaxorKiddie** [comment]
@Eyremba and @pokeball99 yes right, but if the player is in range of the chest the player could heck automaticly if the chest is filled or not, like chest aura.

**Comment by mcccs** [comment]
@Eyremba See;Holoinventory mod.

**Comment by Eyremba** [comment]
@mcccs Holoinventory mod is like opening a chest the normal way: It only works if the chest is ~5 blocks around you in your range.
