### ISSUE TITLE
.smite?

### ISSUE THREAD

**Issue by labcraft59** [Wurst-Imperium/Wurst-Client#2166]
It will strike any player: .smite (playername). Will this work or is it impossible?

**Comment by labcraft59** [comment]
(It will strike them with lightning)

**Comment by 43ee3g** [comment]
Possible client side that you will only see the lightning, maybe useful for reports for staff abuse

**Comment by labcraft59** [comment]
Well, it would be better if it could be real lightning...

**Comment by FlareHAX0R** [comment]
I don't think this is possible w/out proper perms server-side.

**Comment by PixelMaster3D** [comment]
Not possible.
