### ISSUE TITLE
Hacked client 52

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2167]
its on the dark web on the other side i heard thers godmode i heard so i try to find it but i cant

**Comment by BoomBoomLHack** [comment]
can you give me the website link (tor address)?

**Comment by Orcunegeacar** [comment]
Is it in Deep Web? Wow

**Comment by BoomBoomLHack** [comment]
I have tried multiple Tor search engine but I found nothing. :(
Also, is this a hoax?

**Comment by Alexander01998** [comment]
Sources or it didn't happen.

**Comment by Alexander01998** [comment]
Proof or it didn't happen! :P

**Comment by GlitchHead** [comment]
._.
