### ISSUE TITLE
Nbt edit in game source code

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2168]
https://github.com/DavidGoldman/NBTEdit thers the link to visit the site to get the source code for nbt
i think there are source codes

**Comment by EnderGamer21** [comment]
nvm its 1.7.10

**Comment by EnderGamer21** [comment]
nvm its 1.7.10

**Comment by EnderGamer21** [comment]
i think o found a 1.8 one

**Comment by PixelMaster3D** [comment]
t does not really matter if it's 1.7.10. It can be converted.

**Comment by PixelMaster3D** [comment]
I have had a chat the owner and he said it should be 1.8 compatible. It also uses Forge.

**Comment by PixelMaster3D** [comment]
https://github.com/DavidGoldman/NBTEdit/issues/2#issuecomment-138643977

**Comment by PixelMaster3D** [comment]
There is an updated version for the 1.8.

https://github.com/emx2000/NBTEdit
