### ISSUE TITLE
.item name color

### ISSUE THREAD

**Issue by EnderGamer21** [Wurst-Imperium/Wurst-Client#2169]
THis is what it does u type .item ex diamond_sword &1 &1 is blue so when u click enter it will be the color name Hope ist not impsoible

**Comment by BoomBoomLHack** [comment]
You mean colorcodes in items?

**Comment by 1337HaxorKiddie** [comment]
Can it be that you mean .rename? @EnderGamer21

**Comment by EnderGamer21** [comment]
@BoomBoomLHack  yes
@1337HaxorKiddie  np not .rename because u cant do &1diamond sword and it will show color
will it?

**Comment by Eyremba** [comment]
@EnderGamer21 on ".rename" you must use "$" instead of "§" or "&", this can also all be found on the Wurst wiki but everyone seems to lazy to look into it...

**Comment by EnderGamer21** [comment]
it can?
why i=use $ instad of & or § WHY Will it work if it does i will close this issue

**Comment by EnderGamer21** [comment]
it is proven i should read wiki more

**Comment by EnderGamer21** [comment]
NOW IM GONNA CLOSE THIS ISUUSE

**Comment by GamingGamer12** [comment]
i forgot my paz for this acount the one i used to say CLOSED

**Comment by Alexander01998** [comment]
> i forgot my paz for this acount the one i used to say CLOSED

You can ask the [GitHub Support](https://github.com/contact) to reset your password.

**Comment by GamingGamer12** [comment]
ok ALexander
