### ISSUE TITLE
sky base finder

### ISSUE THREAD

**Issue by TheBoyIsHere** [Wurst-Imperium/Wurst-Client#2170]
when i play servers there are a lot of sky bases on sky
the problme is thet the sky chunks load slow or use freecam
i think about a mod thet will solve it
a mod thet tell you if there is a block in the sky above you
a long story for 1 mod :smile:

**Comment by awakened-game** [comment]
hmm, no, if the skybase is too high to see, Wurst cant see it either as it hasn't been loaded.

**Comment by FlareHAX0R** [comment]
Use the BaseFinder hack.
