### ISSUE TITLE
ghosthand

### ISSUE THREAD

**Issue by SkillAura** [Wurst-Imperium/Wurst-Client#2173]
sorry for adding another question to the long list but how do i use ghosthand never learned? or just a link or video that would teach me would be great thanks a lot

**Comment by Alexander01998** [comment]
1. Set the block using the `.ghosthand` command, e.g. `.ghosthand name chest`.

2. Enable the GhostHand mod.

3. You can now reach this block through walls, e.g. if you used the example command above and you find a chest that's inside of a house, you can now open that chest from outside of that house.

The same effect can also be achieved by enabling Freecam and flying through that wall. Some people find it easier to use GhostHand, while others find it easier to use Freecam.

**Comment by SkillAura** [comment]
your amazing alex thanks
