### ISSUE TITLE
Fixed Altmanager

### ISSUE THREAD

**Issue by RockSmasher87** [Wurst-Imperium/Wurst-Client#2175]
I love the wurst client and i try to get as many alts on pastebin as i can so i try to import them but when i import them and try to log in using the alt manager i cant. i was hoping u could fix this.

**Comment by pokeball99** [comment]
more info needed

**Comment by RockSmasher87** [comment]
ok

**Comment by PixelMaster3D** [comment]
Are you saying it's broken? Like as, it will not login or won't save?

**Comment by awakened-game** [comment]
i get this too, if you try to login too many times (about 4) mojang deny any request, whether the password is correct or not, it even locks you out of your own account, but not session IDs

**Comment by RockSmasher87** [comment]
it says "Cant authenicate server" or something like that even if the info is correct

**Comment by awakened-game** [comment]
the solution is to use a different IP every time it does it, until @Alexander01998 fixes wursts exessive login attemts
