### ISSUE TITLE
Question: How can I play wip wurst versions?

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#2179]
Or isn't this possible?

**Comment by pokeball99** [comment]
your talking about build versions? dupe of #1885

**Comment by Alexander01998** [comment]
A tutorial for that can be found here: https://www.wurst-client.tk/wiki/Tutorials/How-to-Debug-Wurst-In-Eclipse/

Note that it requires experience with Eclipse, Git and the MCP.
