### ISSUE TITLE
No headhit

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#2180]
A hack that makes it so when walking off an edge with a roof above you it times it perfect so you jump without hitting your head on the roof. this would be good for parkour and good for getting away from people in pvp

**Comment by awakened-game** [comment]
so... you want the hitbox to be shorter? not sure if that's possible

**Comment by 1337HaxorKiddie** [comment]
@awakened-game Yes, impossible.

**Comment by Eyremba** [comment]
@1337HaxorKiddie No, the HitBoxes in Minecraft can be manipulated by the client.

**Comment by awakened-game** [comment]
@Eyremba yes, the client, meaning the server would keep its normal hitbox checks and make you bump it anyway

**Comment by kcxx** [comment]
You can do this jump without hacks. So it must be possible to make this easier with hacks.

**Comment by solidshadow96** [comment]
NO NO NO i mean just for timing. in parkour when a block is above you, you have to time the jump perfect right at the edge of the block or else you will hit your head and fail. so this hack will test for when a player is at that edge making it almost as if there is no block there. It would be good if also the hack could highlight the block that the client will go to almost like an auto parkour runner. this would be good for Escape the dragon on mineplex

**Comment by awakened-game** [comment]
i just use safewalk, go to the verry edge possible, and jump

**Comment by solidshadow96** [comment]
I know but then u dont get momentum

**Comment by awakened-game** [comment]
move before you jump, obviously
