### ISSUE TITLE
Flight issue?

### ISSUE THREAD

**Issue by PgBiel** [Wurst-Imperium/Wurst-Client#2181]
Hello,
Recently I was playing on some servers with NCP+...
and I saw that Flight would bypass NCP+ with YCP+ enabled.
So I enabled YCP+ (The "YesCheat+" mod) and I selected Flight.
Then, I jumped, once, and I was stuck in air and I was going down, slowly, until I reached the ground and then I could move again.

Any idea of what's this?
If you need a  gif/video you can ask me for it.

**Comment by awakened-game** [comment]
Yeah, I have no idea why this happens, but 90% of servers, Fly just jumps up slightly and stopps there, you can only go back down slowly, NCP or no NCP, a few servers, that last 10%, Fly actually works fine, although its verry stiff as the movement has no decay rate, just a sudden stop.

**Comment by Eyremba** [comment]
This is because NCP has fixed the damage-fly-bypass of Wurst.

**Comment by awakened-game** [comment]
@Eyremba 
>NCP or no NCP
doesn't matter

**Comment by PgBiel** [comment]
so we need a fix..
