### ISSUE TITLE
Newest versions of Wurst not working?

### ISSUE THREAD

**Issue by Soundisimore** [Wurst-Imperium/Wurst-Client#2182]
I am using 1.3.1 because new versions of Wurst are not working.
I tried troubleshooting for an hour before I gave up. I remember it ended with:
ended in bad state. exit code 1

I am on Mac. If you need it all, ask me.

Thanks

**Comment by WurstContributor** [comment]
UPDATE JAVA.

**Comment by Soundisimore** [comment]
I have... I uninstalled, reinstalled, went back onto java site, installed, none of it worked.

**Comment by Alexander01998** [comment]
See #1224.
