### ISSUE TITLE
How to use chest steal?

### ISSUE THREAD

**Issue by Soundisimore** [Wurst-Imperium/Wurst-Client#2183]
Sorry for asking such a dumb question, but can you just tell me what the command/mod is?
Thanks

**Comment by awakened-game** [comment]
Normal steal or Auto Steal? Normally you just click the "Steal" button at the top of a container menu and it takes all the items you can carry, Auto Steal takes anything you can carry as soon as you open the container.

**Comment by Soundisimore** [comment]
Ahhh which version is it in?

**Comment by awakened-game** [comment]
AutoSteal was introduced in v1.6
ChestStealer, the button, was introduced in v1.5

**Comment by ex0rpass** [comment]
Step one Turn it on

Step two walk to a chest

Step three  *grabs it all*

step four PROFIT

when you enable it. it will pick up all of the items
