### ISSUE TITLE
1.9 fight cheat

### ISSUE THREAD

**Issue by Egor1505** [Wurst-Imperium/Wurst-Client#2189]
As you know in 1.9 weapons will have a "cooldown" and shields. So I would suggest for 1.9 that instead constant weapon hold and hitting with it, like killaura does (and it will become pointless in 1.9) wurst will hit 1-2 times than change to a shield for the "cooldown" time and then hit again.

**Comment by Alexander01998** [comment]
# *Duplicate: #1911*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)

**Comment by Egor1505** [comment]
Not a duplicate! I have added an "Shield" idea to it!
