### ISSUE TITLE
No Damage

### ISSUE THREAD

**Issue by DirtyDan2425** [Wurst-Imperium/Wurst-Client#219]
A feature that restricts damage from players, mobs, suffocating, drowning, and any other way you can be hurt

**Comment by OMGchangeMYusername** [comment]
would that even work on servers that don't have any AntiCheat plugin :stuck_out_tongue_winking_eye: ?

**Comment by pokeball99** [comment]
suffocating and drowning can be prevented with freecam

**Comment by Alexander01998** [comment]
Damage is handled by the server.
