### ISSUE TITLE
Blindspot Alert

### ISSUE THREAD

**Issue by PixelMaster3D** [Wurst-Imperium/Wurst-Client#2197]
Able to be alerted whose incoming behind you so you can be prepared to fight or run away from the player.

**Comment by awakened-game** [comment]
currently i just use Tracers, when the line is red, watch out!

**Comment by PixelMaster3D** [comment]
But tracers are in the way and you may not know where they could they be pointing at. They could be pointing left or right but you wont have a very good visual about where exactly.

**Comment by TheIonosphere** [comment]
This would be solved by a text radar with player distances.

**Comment by PixelMaster3D** [comment]
But Alex doesn't want a text radar. (So i think. He already said discarded a few).

**Comment by FlareHAX0R** [comment]
I might try to make a pull request for this later tonight

**Comment by TheIonosphere** [comment]
He accepted the text radar in #1855

**Comment by FlareHAX0R** [comment]
@TheIonosphere  ohk

**Comment by PixelMaster3D** [comment]
Nvm. I must have been thinking map radar. Sorry about that @TheIonosphere.

**Comment by PixelMaster3D** [comment]
True. But you would be to busy attacking your enemy to look at the radar. You might get a few glimpse on the radar. Though you would be worried about what you have right now.
