### ISSUE TITLE
Quakeaura

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#2198]
This hack will atomatticly aim at a player from a long distance so you can shoot him directly in dah face in quakecraft.

**Comment by GamingGamer12** [comment]
bowaimbot is already implmented

**Comment by PgBiel** [comment]
He means Quakecraft. In quakecraft it uses Hoes as the weapon.

**Comment by FlareHAX0R** [comment]
Will work on sometime this week. Probably today/tomorrow

**Comment by PixelMaster3D** [comment]
Duplicate of #55
