### ISSUE TITLE
xRay Block IDs for 1.8 Blocks

### ISSUE THREAD

**Issue by JamesJebson** [Wurst-Imperium/Wurst-Client#2199]
Hi,

I can't for the life of me work out what ID or name to put for 1.8 blocks such as Andesite, Diorite etc.
I have tried their names with capitals, lowercase, datavalue such as 1/1 01/1 1#1 etc.

Any help with what ID or name to use for these blocks?

Thanks

**Comment by pokeball99** [comment]
Meta data doesn't work with wurst's xray

**Comment by GamingGamer12** [comment]
if u check with f3 and h it will show minecraft:stone id

**Comment by JamesJebson** [comment]
F3 doesn't help because you still need to give the variant of stone to add Diorite etc to the xray list. Hopefully Alexander can help.

**Comment by awakened-game** [comment]
Diorites numerical ID is 1:3, try that

**Comment by Alexander01998** [comment]
At the moment, Wurst mods that use block IDs cannot be set to blocks with a specific metadata (such as stone variants).
