### ISSUE TITLE
Auto updater setting

### ISSUE THREAD

**Issue by Creeperman8362** [Wurst-Imperium/Wurst-Client#2200]
I would like to see a auto updater setting that lets you disable it. It can go in the Wurst options. I find it an inconvenience when it updates automatically when I want to go hackin'.

**Comment by Nitrogen-Dioxide** [comment]
@Creeperman8362 

Sadly that is not a good idea, @Alexander01998 made it auto updates because some updates have hot fixes. And a user that disable the update all the time come here and make a dupe issue.

**Comment by awakened-game** [comment]
Hah, I devised a solution to version control ages ago, let me show you:
![image](https://cloud.githubusercontent.com/assets/12572393/9832546/9b707874-59c1-11e5-8ae9-1cee4c87db58.png)
And if i need to change versions for any reason, i just change my profile to run from a different location so the files in the Wurst data folder aren't damaged, so far i just switch between 1.3.1, and the latest, when i need to use 1.7.x or 1.8.x

**Comment by Alexander01998** [comment]
> And a user that disable the update all the time come here and make a dupe issue.

This has been a big problem in the past. Roughly 80% of the users rejected all updates.
