### ISSUE TITLE
Make Fightbot turns smooth

### ISSUE THREAD

**Issue by BarneyisFat** [Wurst-Imperium/Wurst-Client#2203]
make the turns like the mouse instead of turning to them immediately

**Comment by PgBiel** [comment]
^, Yeah, so people wouldn't say "THEY HAX I SAW IT OMG LOOK I SAW HIS HEAD IMMEDIATELLY TURNIN OMG IM REPORTING U BANNED !!!! ENJOY UR BAN!"

**Comment by awakened-game** [comment]
yeah, like 160ms slower
