### ISSUE TITLE
Scaffold

### ISSUE THREAD

**Issue by MicroChip321** [Wurst-Imperium/Wurst-Client#2205]
can you please add the Scaffold Feature to the Wurst client?

if you dont know what it does. please look at this video
https://www.youtube.com/watch?v=qD_3QiaaEzo
:3

**Comment by Eyremba** [comment]
Duplicate...

**Comment by mcccs** [comment]
<b>Duplicate: #781 </b> 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by MicroChip321** [comment]
xD coudnt find it sorry
