### ISSUE TITLE
proxy doesn't work

### ISSUE THREAD

**Issue by llaurenss** [Wurst-Imperium/Wurst-Client#2206]
what do i wrong?
![proxy doesn t work](https://cloud.githubusercontent.com/assets/12222665/9830785/e8799fbe-593b-11e5-9de3-83dd6e6b9943.gif)

**Comment by awakened-game** [comment]
either its not a socks proxy, or that proxy has been used and banned before, or, the more likely thing, that server detected the proxy and banned it.

**Comment by llaurenss** [comment]
No it's working with proxifier

**Comment by GamingGamer12** [comment]
do u kno what is mineplex ip i need to know

**Comment by Eyremba** [comment]
I can confirm that it does not work. :/

**Comment by PixelMaster3D** [comment]
Mineplex IP is 199.83.134.3. But why not Mineplex.com?

**Comment by Alexander01998** [comment]
Does it also happen with the `proxy` command in Wurst-Bot?

**Comment by llaurenss** [comment]
yep
![wurst bot proxy](https://cloud.githubusercontent.com/assets/12222665/9971400/d73fa4c6-5e5b-11e5-8c92-fb1a57f31baf.gif)

**Comment by DataPools** [comment]
Same issue...

**Comment by Alexander01998** [comment]
It seems that Mojang's new auth servers can detect normal proxies. I've been told that it works fine when using elite proxies.

**Comment by ZzerLo** [comment]
Alexander i am having a problem with proxies as well could you tell me some free good ones to use

**Comment by PixelMaster3D** [comment]
You can use a list of proxys from nalhost.com @ZzerLo
