### ISSUE TITLE
Secret-Messages in Wurst

### ISSUE THREAD

**Issue by FlightCoder** [Wurst-Imperium/Wurst-Client#2207]
Some Servers dont support /msg or /tell or /whisper
But with the secret-message mod you can send encrypted messages in the chat and guys, who own wurst too, can read it :)

So if the message starts with x:, then it must be encrypted :p
Hope you like it, sry for my grammar, im german...

maybe you can change the encryption with a password :dango:

**Comment by JamesJebson** [comment]
I used a client that can do this, you start encrypted messages with %. If Alexander likes the idea I can share with him the mod code.

**Comment by awakened-game** [comment]
duplicate, @Alexander01998 has already talked about this

**Comment by GamingGamer12** [comment]
@FlightCoder its server sided for most servers

**Comment by FlightCoder** [comment]
@GamingGamer12 facepalm

**Comment by JamesJebson** [comment]
@GamingGamer12 It's really not, it posts encrypted messages into the chat. Other players will see for example: "<Player> Z29kIGlzIGdyZWF0IHByYWlzZSBhbGxhaA=="

But all other players that use that same client will see the real message instead.

**Comment by Nitrogen-Dioxide** [comment]
@JamesJebson 

Take a look at this issue: #1253

**Comment by beppe9000** [comment]
it's like saing "hey i am looking for a ban"

**Comment by 1337HaxorKiddie** [comment]
@JamesJebson god is great praise allah Whaaaaat?!

**Comment by JamesJebson** [comment]
@Nitrogen-Dioxide Look at this client, it is the one i have used that includes encrypted chat https://github.com/italiceyeball/v

@1337HaxorKiddie Relax it was just an example :smile:

**Comment by 1337HaxorKiddie** [comment]
@JamesJebson Okay, okay i just wondered me.
