### ISSUE TITLE
Pimmel

### ISSUE THREAD

**Issue by FlightCoder** [Wurst-Imperium/Wurst-Client#2209]
Ich, Garkolym, habe Alexander01998 das mit dem Vanish früher mal vorgeschlagen (Test) :)
Dieser Account gehört ebenfalls mir :)) Deshalb Kopf hoch, ich habe nichts gestohlen, Lukas Schwab labert Müll und ist ein dummes kind :))

**Comment by awakened-game** [comment]
does not work if they dont send packets, also the ping list can be customized, only real way is to query the server, unless they disabled it or hide it.

**Comment by FlightCoder** [comment]
-.- i have it already in my client you genius

**Comment by 43ee3g** [comment]
screenshot of how it works?
yes it is possible but that doesn't mean that method works
it is possible to get the names of vanished players, but not their location

**Comment by FlightCoder** [comment]
@43ee3g oh my god, you are so stupid

**Comment by bob80333** [comment]
@43ee3g It's only supposed to find the usernames of those who are in vanish mode.

**Comment by Eyremba** [comment]
@paris-ci omg READ dumb READ!!!! ---> "-.- i have it already in my client you genius"

**Comment by Eyremba** [comment]
@paris-ci it also sends packets which can be detected.

**Comment by mcccs** [comment]
i found how to use this https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-65040

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder Der typ is so lächerlich... Ich frage mich wie man so treist sein kann...

**Comment by FlightCoder** [comment]
Irgendwer benutzt meinen Account

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder Github support?

**Comment by FlightCoder** [comment]
Warum github support?

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder Na wenn jemand dein acc benutzt solltest du vllt. mal dein PW ändern...

**Comment by FlightCoder** [comment]
Du solltest lieber kein GitHub benutzen :dango:

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder Und wieso weil ich hier so behinderte Leute wie dich treffe oder was?

**Comment by FlightCoder** [comment]
Nein, weil du ein HaxorKiddie bist :100:

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder Und du bist... Humor behindert?!

**Comment by FlightCoder** [comment]
Lade mal die Seite neu und gucke dir das Profilbild an :dancer:

**Comment by FlightCoder** [comment]
Willst du auch ein tolles Profilbild?

**Comment by 1337HaxorKiddie** [comment]
@Garkolym Ich hab angst...

**Comment by FlightCoder** [comment]
Keine Angst, es passiert nichts

**Comment by 1337HaxorKiddie** [comment]
@FlightCoder You don´t say...

**Comment by 1337HaxorKiddie** [comment]
Da kennt sich jemand mit Github aus... @Alexander01998

**Comment by 1337HaxorKiddie** [comment]
Gut Kevin ich hab zwar keine ahnung was du vor hast aber mach weiter...

**Comment by FlightCoder** [comment]
Ich habe auch keine Ahnung Kiddie

**Comment by 1337HaxorKiddie** [comment]
Du bistn krasser typ weist du das?

**Comment by 1337HaxorKiddie** [comment]
Noch da Adam14x?

**Comment by mcccs** [comment]
@Alexander01998 Garkolym came back!

**Comment by pokeball99** [comment]
Reported

**Comment by Alexander01998** [comment]
Was ist ist denn hier wieder los?!
