### ISSUE TITLE
AutoParkour

### ISSUE THREAD

**Issue by FlareHAX0R** [Wurst-Imperium/Wurst-Client#2214]
If this is on, you will need to select the blocks you need to jump to (in order)

Then, the client will calculate the best way to do it, and, then, well do it.

**Comment by GamingGamer12** [comment]
umm i thinkn its imposible

**Comment by FlareHAX0R** [comment]
You sure? It would just involve calculating, then following a path.

**Comment by awakened-game** [comment]
Wurst can barely handle calculating .goto paths (pathfinding always fails for me), so these really short paths might work, plus jumps

**Comment by 1337HaxorKiddie** [comment]
I think its extremly difficulty to code something like this. It would be easyer if you could select a block with your crosshair and wurst try to jump there.

**Comment by mcccs** [comment]
I guess....

Duplicate: #817 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by 1337HaxorKiddie** [comment]
@mcccs That´s not the same.

**Comment by mcccs** [comment]
But mine is better

**Comment by PixelMaster3D** [comment]
@GamingGamer12, this is possible. @FlareHAX0R, there is a hack client with Parkour mod, http://www.wizardhax.com/2014/12/24/minecraft-1-8-1-8-1-hacked-client-kryptonite-with-optifine-download/. @mcccs, Yours  is good, but then you would have to do it yourself while recording.
