### ISSUE TITLE
Hack templates

### ISSUE THREAD

**Issue by Egor1505** [Wurst-Imperium/Wurst-Client#2217]
My idea is to create Cheat templates! So for example for BedWars I need one set of cheats, for parkour absolutely diffent! So my idea is to create something like that
1) You turn on ALL hacks for bedwars
2) you write .template set bedwars
3) then you bind on it like .t template bedwars
4) then you activate this bind, all cheats you had on while setting template are activating!
Then you can do a few more templates for other minigames (Parcour SG etc.)
P.S. I will also  make easier to reset all cheats after .t panic.

**Comment by mcccs** [comment]
#656 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)
