### ISSUE TITLE
Proxy dosnt work 

### ISSUE THREAD

**Issue by chriskjpk** [Wurst-Imperium/Wurst-Client#2218]
i tryed to change my ip adress on minecraft with wurst with a neu alt, if i tryed to connect do a server it faild "your ip is banned".
i tryed again and it dosnt work.
please help or fix that.
ps: sorry for my English i am from germany

**Comment by 1337HaxorKiddie** [comment]
The server detects if you trying to spoof your ip.

**Comment by chriskjpk** [comment]
ok i try it on a kiddy server

**Comment by Alexander01998** [comment]
# *Duplicate: #2206*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
