### ISSUE TITLE
Haxplosion mod

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#2219]
If this mod is enabled it will turn all of the other mods on. It's an explosion of hacks so it is a haxplosion (the 'x' is just for swagness). This mod is just for fun.

**Comment by FlareHAX0R** [comment]
This would be mayhem for whoever activated. Plus, half the mods wouldn't activate due to YC+ being turned on.

**Comment by Grievus** [comment]
youre right but this mod can also be coded that YesCheat+ won't be enabled

**Comment by FlareHAX0R** [comment]
But still, it would be absolute mayhem. Also blink and freecam would activate...

**Comment by Grievus** [comment]
You're right

**Comment by Orcunegeacar** [comment]
Also it will crash your PC. :trollface:  What about calling it PCrasher?

**Comment by Grievus** [comment]
LOL

**Comment by mcccs** [comment]
oea But it crashes mac and linux too
how about calling it 
PcMacLinuxUnixCrasher

**Comment by Elviond** [comment]
Mac is a PC...

**Comment by mcccs** [comment]
http://lowendmac.com/2008/the-mac-is-a-personal-computer-but-it-is-not-a-pc/
