### ISSUE TITLE
rainbow tracer lines

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#222]
tracer showing a strange rainbow coloured line wich pointing on an empty block. i cant even turn off by turning off tracer mode

![2015-03-16_15 22 45](https://cloud.githubusercontent.com/assets/11147727/6668068/70b876a4-cbf0-11e4-8a27-a4a58dbf03f5.png)

**Comment by Alexander01998** [comment]
That's PlayerFinder. It found something there.

**Comment by Le0pold** [comment]
nope it was just anonoying me without having playerfinder on

**Comment by Le0pold** [comment]
perhaps .... PFUDOR :O ?

**Comment by Alexander01998** [comment]
> without having playerfinder on

You had PlayerFinder on, I can see that in the screenshot.

> perhaps .... PFUDOR :O ?

Perhaps, mit 'ner Menge LSD.
