### ISSUE TITLE
No Milestone?

### ISSUE THREAD

**Issue by GamingGamer12** [Wurst-Imperium/Wurst-Client#2221]
il close this when i get a response

**Comment by 1337HaxorKiddie** [comment]
That´s not an issue.

**Comment by solidshadow96** [comment]
IKR!!!! NO MILESTONE WHY WAS CRASH HEAD REMOVED AND WHAT WAS EVEN ADDED NOTHING!!!!!!!!!!!!

**Comment by GamingGamer12** [comment]
@solidshadow96  calm down

**Comment by solidshadow96** [comment]
xD

**Comment by Alexander01998** [comment]
When the [Wurst Feedback App](https://feedback.wurst-client.tk/) rolled out, I changed my mind on the changes for v2.4.
