### ISSUE TITLE
[ BUG ] Missing Letter.

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#2222]
![bug](https://cloud.githubusercontent.com/assets/11218527/9838414/ba6cc936-5a65-11e5-8adc-a6fac69fec3f.png)

Here it is. I guess you missed ( I ) letter.

**Comment by GamingGamer12** [comment]
for me when i chexked its there the I is there

**Comment by Nitrogen-Dioxide** [comment]
@Orcunegeacar 

I think it is because you are using windows 7, on windows 8.1 the I are there.

**Comment by mcccs** [comment]
@orcunegecar your problem is tr version windows.i already report this but alexanfer did nothin: (

**Comment by mcccs** [comment]
Sooo. ..
Duplicate #994

**Comment by Orcunegeacar** [comment]
Yeah I'm using TR (Turkish) version. Maybe it's the problem :) thanks for noticing. @mcccs

**Comment by Alexander01998** [comment]
So far, it appears to be a graphics card issue.
I know that it's not the OS, not the screen size and not the Java version.
It's unlikely to be caused by your language, as some people using `EN_US` had the same problem.

**Comment by Orcunegeacar** [comment]
I updated all my drivers and my graphic card isn't so bad. These issues (font,missing letters) began when you updated to windows 10. There was no issue when the latest version was 2.2

I'm thinking it's windows 10's bug not my machine. All other clients working well. (hacked clients)

**Comment by Alexander01998** [comment]
> I'm thinking it's windows 10's bug not my machine. All other clients working well. (hacked clients)

I've seen people using Windows 10 and having the same issue (#1986, #1985), so it's definitely not caused by Windows 10.
