### ISSUE TITLE
Can not open, Crashes

### ISSUE THREAD

**Issue by Attroxhippo** [Wurst-Imperium/Wurst-Client#2223]
this is what happens
![untitled_23](https://cloud.githubusercontent.com/assets/14272068/9846399/4b39c6f8-5b15-11e5-95dc-01510dd8c234.jpg)

**Comment by Alexander01998** [comment]
# *Duplicate: #*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
