### ISSUE TITLE
Chest Stealer Update

### ISSUE THREAD

**Issue by MicroChip321** [Wurst-Imperium/Wurst-Client#2224]
Make the chest Stealer in YesCheat+ Faster like serenity

**Comment by MicroChip321** [comment]
Make the Chest Stealer In YesCheat+ Faster like serenity

**Comment by labcraft59** [comment]
Good idea. ☺

**Comment by nerdtron123** [comment]
yes

**Comment by nerdtron123** [comment]
Just turn off YesCheat+

**Comment by MicroChip321** [comment]
most servers patched it :/ theres a kind of chest stealer wuts faster
