### ISSUE TITLE
Regen

### ISSUE THREAD

**Issue by coopercool123** [Wurst-Imperium/Wurst-Client#2226]
Regen is not working anymore :-1: :(
Only the food bar is regen!

**Comment by kcxx** [comment]
Regen is only for servers without NCP

**Comment by PixelMaster3D** [comment]
Works on Mineplexs games.

**Comment by solidshadow96** [comment]
Yea mineplex uses MAC instead of NCP stupids xD it doesnt detect any hacks execpt sometimes timer and sometimes flying

**Comment by PixelMaster3D** [comment]
Exactly! (P.S. If you want to know a server that doesn't have any anti hack enabled got Lobby-2 and join Turf Wars 5.)

**Comment by PixelMaster3D** [comment]
Don't tell anyone else or Mineplex itself.

**Comment by ex0rpass** [comment]
@PixelMaster3D do you have steam?

**Comment by PixelMaster3D** [comment]
No. But i'll make one later though in my free time.

**Comment by mcccs** [comment]
Some months ago mineplex told it change mac to ncp

**Comment by ex0rpass** [comment]
@PixelMaster3D Okay
