### ISSUE TITLE
Please add a Aimbot to Wurst 

### ISSUE THREAD

**Issue by GappleGodPvP** [Wurst-Imperium/Wurst-Client#2227]
Please add a Aimbot to Wurst wich just AIMS on your Enemy (Mob,player) if you are going to add it make sure that it doesn`t aim for your friends

**Comment by 1337HaxorKiddie** [comment]
This should ve a killaura mode.

**Comment by GamingGamer12** [comment]
aimbot is already implmented

**Comment by 1337HaxorKiddie** [comment]
@GamingGamer21 As far as i know not.

**Comment by mcccs** [comment]
Duplicate #1229

**Comment by GamingGamer12** [comment]
or its dupe not already impmented
