### ISSUE TITLE
Suggest to add TeamKillaura

### ISSUE THREAD

**Issue by Elephantlovr33X** [Wurst-Imperium/Wurst-Client#2229]
Well, When im playing a Game, With your own team, You most likely have the same armor, and My KillauraLegit ALWAYS goes for People that are on my team. And it also takes to Long to Friend Them. So I want a Killaura that Detects your teams Armor, or name tag color, so the Killaura doesn't go for them. If its Possible, Please add it.

Thank you!

**Comment by FlareHAX0R** [comment]
Or maybe make TeamKillAura not target people with the same colored name as you.

**Comment by PixelMaster3D** [comment]
This was already discussed but you can try to make a Pull for it.

**Comment by labcraft59** [comment]
Or maybe like a "same team target" or "other team target"

**Comment by mcccs** [comment]
duplicate #112

**Comment by labcraft59** [comment]
This is the BEST idea ever!!! And by the way, mcccs, #112 is not the same

**Comment by labcraft59** [comment]
And it's already accepted, so I guess this does not matter anymore...
