### ISSUE TITLE
SmartAura

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#2232]
Recently my friend coded his own minecraft client and in it he made somthing called smart aura. its a type of aura that has many options that can be changed in the pause menu. im assuming it would be added under wurst options if this mod is add. anyways the mod allows the client to only attack invis entitys only or not invis enititys also it can target people with the strongest armor and or people with the weakest armor. it is basically kill aura but with more options and i think it should be added. it would also be cool for killaura/smartaura if you middle clicked a mob it would then prioritize that mob so instead of the player attacking the cows infront of him it would rather attack the chicken behind him. almost like the friend feature exept for mobs

**Comment by labcraft59** [comment]
Cool idea!

**Comment by solidshadow96** [comment]
thx
