### ISSUE TITLE
How do i code for this client?

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2238]
I see people helping with the client with pull requests how do i make one?

**Comment by mcccs** [comment]
Looooong story;
Learn MCP
Learn Java
Learn Git

**Comment by ex0rpass** [comment]
@mcccs I know how to code i just dont know how to summit it to the wurst-client github

**Comment by FlareHAX0R** [comment]
1. Fork it
2. Make a patch-x branch in your fork
3. Submit your code to the patch-x branch
4. Make a pull request to pull the patch-x from the fork into the master branch on this repo
