### ISSUE TITLE
Where To Post Suggestions From Now On

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-Client#2239]
If you haven't seen it yet, I recently created a [Feedback App](https://feedback.wurst-client.tk/) for Wurst.

Suggestions made there can be voted on by others, making it much, much easier for me to see which features are the most popular. This also saves me a lot of time, as I don't have to read every single suggestion ever made. Instead, I can focus on the popular suggestions.

If you've been here for a while, you know there's lots of stuff going on every day. Good suggestions, bad suggestions, duplicates, etc. are being added all the time. You can probably imagine how much time it takes me to read all of that. (and that's why I'm no longer reading most of it)

Using the Wurst Feedback App instead of the Issue Tracker also has an advantage for you: You get a **fair** chance that I will use your suggestion. If it's good, people will vote for it and it will get a higher priority. Whereas here, the chance of me reading your suggestion, liking it, approving & accepting it, and then still remembering it the next time I select the changes for the next Wurst update, are quite low.

I released the Wurst Feedback App about two weeks ago. The blog post with more details can be found here: https://www.wurst-client.tk/news/2015-09-04-Feedback-App-released/

**Comment by ex0rpass** [comment]
Awesome!

**Comment by kcxx** [comment]
It needs comment section

**Comment by Alexander01998** [comment]
> It needs comment section

It's not meant for discussions.

**Comment by solidshadow96** [comment]
Its just for alexander to view suggested mods

**Comment by PixelMaster3D** [comment]
Then can't you add where you would find the issue for the suggestions on each feedback? Like, when they go to post feedback about the request there should be an another column on which issue it is.

**Comment by ex0rpass** [comment]
@PixelMaster3D What is your steam url?

**Comment by labcraft59** [comment]
So you won't even consider #2166 ?

**Comment by beppe9000** [comment]
@Alexander01998 maybe cloning/transferring suggestions from this repository (filtering out actual issues) and make them votable on that feedback platform. You could for example use [this script](https://github.com/controlgroup/CSV-GitHub-import-export) to get the issues.

**Comment by Alexander01998** [comment]
> Then can't you add where you would find the issue for the suggestions on each feedback? Like, when they go to post feedback about the request there should be an another column on which issue it is.

The Wurst Feedback App doesn't require GitHub Issues, it's a system on it's own.

> cloning/transferring suggestions from this repository (filtering out actual issues) and make them votable on that feedback platform would be a good move.
> 
> You could for example use this script to get the issues.

There are a lot of duplicates off-topic Issues here, so it would take quite a while to filter that out.

The good suggestions are probably already in the Wurst Feedback App. And if not, someone will add them soon.

**Comment by labcraft59** [comment]
Ok...
