### ISSUE TITLE
Server Editor

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#224]
Could you add a console panel to edit servers. I mean can you add the cmd of the server (I know its hard but....) Maybe you can copy and paste codes to cmd and make the same console panel in server.? If you can do that. It'll be awesome for hack and grief

**Comment by Orcunegeacar** [comment]
Maybe I'll try to add it to my "Wurst App"

**Comment by Alexander01998** [comment]
> Could you add a console panel to edit servers. I mean can you add the cmd of the server (I know its hard but....) Maybe you can copy and paste codes to cmd and make the same console panel in server.? If you can do that. It'll be awesome for hack and grief

I don't understand this.

> Maybe I'll try to add it to my "Wurst App"

While we're at it, I'd like to remind you that you have to **distribute the source code** of Wurst-App.

You have licensed Wurst-App under terms of the MPL v2, including this:

```
3.2. Distribution of Executable Form

     If You distribute Covered Software in Executable Form then:

     a. such Covered Software **must also be made available in Source Code Form**,
        as described in Section 3.1, and You must inform recipients of the
        Executable Form how they can obtain a copy of such Source Code Form by
        reasonable means in a timely manner, at a charge no more than the cost
        of distribution to the recipient; and (...)
```

If Wurst-App uses any of the Wurst-Client source code, resources or other licensed material, then my license also requires you to distribute the source code.

```
3.3. Distribution of a Larger Work

     You may create and distribute a Larger Work under terms of Your choice,
     provided that You also comply with the requirements of this License for
     the Covered Software. If the Larger Work is a combination of Covered
     Software with a work governed by one or more Secondary Licenses, and the
     Covered Software is not Incompatible With Secondary Licenses, this
     License permits You to additionally distribute such Covered Software
     under the terms of such Secondary License(s), so that the recipient of
     the Larger Work may, at their option, further distribute the Covered
     Software under the terms of either this License or such Secondary
     License(s).
```

**Comment by Orcunegeacar** [comment]
No I don't use your source code. Because You wrote "Wurst" in java right?. And I'm writing the Wurst-App in C# programming language in Visual Studio. I can't write the same thing. I'm not doing a client. I'm creating a app for "Wurst".

**Comment by Alexander01998** [comment]
> No I don't use your source code. Because You wrote "Wurst" in java right?. And I'm writing the Wurst-App in C# programming language in Visual Studio. I can't write the same thing. I'm not doing a client. I'm creating a app for "Wurst".

OK, but you still need to distribute the source code. As I said in the comment above, your own license requires you to do that.

**Comment by Orcunegeacar** [comment]
But I didn't finish the alpha version yet. When It's done. I'm going to share it.
