### ISSUE TITLE
Cannot connect to authencation servers?

### ISSUE THREAD

**Issue by tkggear** [Wurst-Imperium/Wurst-Client#2242]
when i go to add an alt what does that mean

**Comment by mcccs** [comment]
İf you logged in too many alts you need to wait 24 hOurs or restart your pc

**Comment by Alexander01998** [comment]
# *Duplicate: #1242*
![Please search for similar Issues before submitting yours.](https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png)
