### ISSUE TITLE
Why is .invsee for survival only?

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#2244]
Why?

**Comment by labcraft59** [comment]
I have no idea...

**Comment by Alexander01998** [comment]
Because it would crash in creative mode.

**Comment by WurstContributor** [comment]
-_-

**Comment by GamingGamer12** [comment]
How???

**Comment by pokeball99** [comment]
Might be because of the creative mode inv would conflict with the survival mode like gui?

**Comment by Alexander01998** [comment]
> Might be because of the creative mode inv would conflict with the survival mode like gui?

Exactly.

**Comment by pokeball99** [comment]
well, @Alexander01998 why can't that be fixed? sounds easy enough.

**Comment by im4nthony** [comment]
@Alexander01998 make it in survival when u do .invsee and don't tell the server about it so fake it basically

**Comment by WurstContributor** [comment]
@im4nthony You don't have to fake it... You can just change the gui and shit.

**Comment by im4nthony** [comment]
easier to fake it tho

**Comment by WurstContributor** [comment]
I still don't get what "Fake" means I mean fake what?

**Comment by im4nthony** [comment]
easier to make you in gms without telling the server and switch back to gms when you stop .invsee

**Comment by beardowny22** [comment]
Well, coding a client is NOT as easy as you think it is

**Comment by TekkitCommando** [comment]
It's not easy it's challenging
