### ISSUE TITLE
Is this a possible way to bypass anti xray?

### ISSUE THREAD

**Issue by rakazet** [Wurst-Imperium/Wurst-Client#2246]
Since the suggestions tab isn't working properly I will just post it here, it seems to be more lively.

We all know the normal xray, but the worst part is hypixel's complicated anti xray [UHC]. We can only mine ores that are visible in caves. People need to use cavefinder and look closely for ores, and it's so hard. Can you add a mode of Xray where it only highlights blocks that are visible in caves? I think it's possible :)

**Comment by labcraft59** [comment]
**Good idea!**

**Comment by GamingGamer12** [comment]
HOw do u do that Labcraft59

**Comment by ex0rpass** [comment]
Dupe #99

**Comment by Alexander01998** [comment]
> Since the suggestions tab isn't working properly

What do you mean by that?

> I will just post it here, it seems to be more lively.

We are no longer using the Issue Tracker for suggestions.

**Comment by rakazet** [comment]
My suggestions seem to disappear all the time :(. Also is this hack possible? You know blocks in caves are 100% real

**Comment by PixelMaster3D** [comment]
So you are saying that you should highlight it what you want? Like if i cant see the diamond ore because of UHC then it should be highlighted. Is that it?

**Comment by rakazet** [comment]
No. I've xrayed on hypixel by using cavefinder. I found alot of gold and diamonds using cavefinder and I find it pretty annoying to find ores manually using cavefinder. Since we do know blocks in caves are real ( the proof is that I found ores with cavefinder ), I want alexander to consider in making a new mode of xray, where it only highlights ores that you can see using cavefinder. Which means that the hack will only highlights blocks that is in the cave ( You don't need to mine cobblestone to get the ores, you can mine it simply by going in to the cave )

**Comment by rakazet** [comment]
I don't know if people understand what I mean from "Ores in caves". Tell me if you need more explanation

**Comment by Alexander01998** [comment]
> My suggestions seem to disappear all the time :(. Also is this hack possible? You know blocks in caves are 100% real

They don't stay on the front page forever, but you can always find them though the search bar: https://feedback.wurst-client.tk/?q=anti+xray
