### ISSUE TITLE
Criticals Mod not working

### ISSUE THREAD

**Issue by wised** [Wurst-Imperium/Wurst-Client#2247]
When I enable the mod it doesn't work, I see the automatic little jump, but no critical effect **bold** yes I have particles on maximum.

**Comment by wised** [comment]
I have no idea why **bold** was inserted.

**Comment by ex0rpass** [comment]
@wised It works you just dont see it working

**Comment by Alexander01998** [comment]
You might be on a server that blocks Criticals.
