### ISSUE TITLE
Mineplex Anticheat

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#2249]
i found its source code, i can post the link if it can help Wurst's YCP development?

**Comment by PixelMaster3D** [comment]
@mcccs do you mean M.A.C or Mineplex custom NoCheatPlus?

**Comment by mcccs** [comment]
NCP, May 2015

**Comment by PixelMaster3D** [comment]
So you're talking about Mineplex custom coded NCP. Right?

**Comment by mcccs** [comment]
Yup, no-obfuscated.

**Comment by PixelMaster3D** [comment]
Oh. There's a leaked version on Leak Forums. https://leakforums.net/thread-286804

**Comment by mcccs** [comment]
@PixelMaster3D It isn't mine is May 2015, leak forums is 2013

**Comment by PixelMaster3D** [comment]
They could have been added on the day the guy put them there. But you could be true.
