### ISSUE TITLE
The Ctrl button doesn't work.

### ISSUE THREAD

**Issue by EpicNerd7** [Wurst-Imperium/Wurst-Client#2250]
I'm using the latest 2.4 version and when ever I press the ctrl button to change what I'm using it doesn't some up anymore, now I'm stuck with annoying things like auto sprint

**Comment by PixelMaster3D** [comment]
Is the Ctrl on your keyboard broken?

**Comment by EpicNerd7** [comment]
ctrl works, wurst doesn't

**Comment by EpicNerd7** [comment]
I deleted and re installed and it works now
