### ISSUE TITLE
Wurst 2.5

### ISSUE THREAD

**Issue by awakened-game** [Wurst-Imperium/Wurst-Client#2253]
I just saw a notification for wurst that said: 
"Wurst 2.5 - OP-Sign in Survival, Redesigned Main Menu"
and it takes me to https://www.wurst-client.tk/news/2015-09-25-Wurst-2-5/
then says 404, then i went to the releases on github and its not here...?

**Comment by pokeball99** [comment]
He reverted it soon after

**Comment by awakened-game** [comment]
oh, any idea what the problem was?

**Comment by ex0rpass** [comment]
@awakened-game He probably accidentally released it on the wrong date. Then he removed it

**Comment by mcccs** [comment]
Duplicate: Wurst-Imperium/wurst-client.tk/#53

**Comment by awakened-game** [comment]
@mcccs not a duplicate, thats an entirely seperate repository

**Comment by Alexander01998** [comment]
> He probably accidentally released it on the wrong date. Then he removed it

^

**Comment by PixelMaster3D** [comment]
Case Closed.
