### ISSUE TITLE
Wurst Client when opened says Java Exception Has occured

### ISSUE THREAD

**Issue by beardowny22** [Wurst-Imperium/Wurst-Client#2267]
How do I fix this? Wurst is the best client so far and I really really want it...

**Comment by beardowny22** [comment]
It says Java Exception has occured

**Comment by PixelMaster3D** [comment]
Is ther an error log that comes with it?

**Comment by beardowny22** [comment]
Yes, there is

**Comment by PixelMaster3D** [comment]
Can you post it here?
