### ISSUE TITLE
OP-Sign not working?

### ISSUE THREAD

**Issue by WurstLove** [Wurst-Imperium/Wurst-Client#2268]
Hello! I recently updated my wurst 2.4 to Wurst 2.5 and the newest improvement was OP-Signs in survival! So i was excited to try this on some 1.8.5 vanilla servers. Me and my friends found some and we were excited to try and grief them only to find out that it won't work. To confirm this me and my friends spent 5 minutes and made a 1.8.3 Vanilla Gratis server, and it still didnt work!

**Comment by mcccs** [comment]
Op sign cannot run some commands like /ban

**Comment by 1337HaxorKiddie** [comment]
@WurstLove for me its working good! And @mcccs if the sign can run the /op command it can also run the /ban command.

**Comment by awakened-game** [comment]
signs dont work for me either, oh and triangle.gs is shit, their ftp is rarely up and you cant start you server without it, i just says error when you try to start it

**Comment by mcccs** [comment]
@awakened-game I have the same error, but 1 year ago.

**Comment by WurstLove** [comment]
Am I supposed to put something on the signs? And I don't use ban for the op signs, only the op command

**Comment by ex0rpass** [comment]
@1337HaxorKiddie can i add you on steam? we can hack with the op sign

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Sorry i haven´t got Steam.

**Comment by Alexander01998** [comment]
> Am I supposed to put something on the signs?

You shouldn't even be able to put something on the signs. If you are, that might mean that you are doing something wrong.

I'm uploading a video tutorial for it at the moment, which should be done in a few hours.

**Comment by ex0rpass** [comment]
@Alexander01998 What channel will it be uploaded on?

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass I think just normal here: https://www.youtube.com/channel/UCrPIKlDsHSwrNyEhgItxzQQ

**Comment by MyzticalTekkno** [comment]
@1337HaxorKiddie 
i've tested the survival op sign on this server
pigman.biz (1.8.4 Vanilla)
still doesn't work v.v

**Comment by mcccs** [comment]
@myzticaltekkno yeah i tried it on my 1.8.3 server but didnt workk

**Comment by MyzticalTekkno** [comment]
@mcccs dang!

**Comment by MyzticalTekkno** [comment]
@mcccs dude lets play agar.io in mc
incraftion.com:25603

**Comment by 1337HaxorKiddie** [comment]
@MyzticalTekkno Your server isn´t a vanilla server, it claims to be a vanilla server but its not.

**Comment by MyzticalTekkno** [comment]
how do you notice that the server wasn't a vanilla?

**Comment by 1337HaxorKiddie** [comment]
@MyzticalTekkno The easiest way to check it is typing /help, on your server are commands like /me or /trigger shown but in in vanilla is no command called /me or /trigger .

**Comment by mcccs** [comment]
@1337HaxorKiddie but mine? mine was downloaded from mojang.com

**Comment by 1337HaxorKiddie** [comment]
@mcccs I don´t know, for me it works. If the mod is enabled it should work.

**Comment by 1337HaxorKiddie** [comment]
@mcccs when did you downloded it?

**Comment by mcccs** [comment]
Yesterday

**Comment by 1337HaxorKiddie** [comment]
@mcccs From here: https://minecraft.net/download ?

**Comment by mcccs** [comment]
No https://mojang.com/2015/02/minecraft-1-8-2-is-now-available/

**Comment by 1337HaxorKiddie** [comment]
@mcccs Okay, i don´t know it should work.

**Comment by MyzticalTekkno** [comment]
@mcccs you can easily download older version of minecraft server launcher on minecraft.net
like the new minecraft server launcher link is
https://s3.amazonaws.com/Minecraft.Download/versions/1.8.8/minecraft_server.1.8.8.jar
so... if you want to download older one                                /\                    /\
                               change the first one                      first.  |  second.       |
to the version you want (ex: 1.8.1, 1.8.2,etc) and the second one with the version you want (ex: minecraft_server.(version you want).jar)

**Comment by 1337HaxorKiddie** [comment]
@MyzticalTekkno No, that aren´t vanilla commands, this server is based on the 1.8 and not on a snapshot.

**Comment by MyzticalTekkno** [comment]
@1337HaxorKiddie 
Hmmm... i think you are wrong kidd...
[/trigger & /me command is an vanilla command](http://minecraft.gamepedia.com/Commands#Summary_of_commands)

**Comment by 1337HaxorKiddie** [comment]
@MyzticalTekkno Yup, sorry i was wrong you are right, but anyway this Server is not vanilla. Because /tpa is really not a vanilla command.
