### ISSUE TITLE
Quakecraft. hack for the server mc.hypixel.net

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#227]
Since there is a command for Arenabrawl on mc.hypixel.net I think there shoud be a command for the quakecraft. like the hack called InstaGib or Aimbot for quakecraft. Can there please be a hack for this?

**Comment by OMGchangeMYusername** [comment]
i guess this would be Duplicate #55 
Although I Massively Agree To It :+1:

**Comment by OMGchangeMYusername** [comment]
Dude a lot of hacked clients have it!
i always have to install another clients to use it :cry: 
#### Please add it!!!

**Comment by OMGchangeMYusername** [comment]
Please add this!!
i feel that a lot of people will be happy about it and will download Wurst for QuakeAura!
i think the more special gamemode hacks you add the more popular the client will be!
for example Cyanit has Block Party hack and it's awesome!!!
