### ISSUE TITLE
cannot contact authentication servers/alts geting deleted on restart 

### ISSUE THREAD

**Issue by TheNeonGuy** [Wurst-Imperium/Wurst-Client#2274]
if i try tho put a alt with password on it say cannot contact auth servers and if i leave the alts menu and go back it will delete the alts

**Comment by 1337HaxorKiddie** [comment]
@TheNeonGuy Probably your IP is banned or the accounts your are banned.

**Comment by TheNeonGuy** [comment]
@1337HaxorKiddie if it right like one from https://minecraftleaks.com/ and i know this is real i was testing a few with huzuni and it only happens with ones like that and if i import the screen flashes red if it premeum

**Comment by 1337HaxorKiddie** [comment]
@TheNeonGuy Sorry, i don't really understand.
