### ISSUE TITLE
how to get on servers cuz they want three . in chat

### ISSUE THREAD

**Issue by sacredgreed** [Wurst-Imperium/Wurst-Client#2275]
some servers have its own "anticheat plugin"
and they want you to write in chat ... but if i write 3x . its only spam wurst bad comand

please can you make it that if i write three . in chat ican login to server ?
and wurst will not spam ?

**Comment by pokeball99** [comment]
do in WSPAM "<repeat 3>.say .</repeat>"(can't remember if that the way the tags are done)

**Comment by mcccs** [comment]
.say threedots
İ coudnt write three dots,mobile keyboard fleksy sucks.

**Comment by l3399l** [comment]
.say .............................................................................I don't hack!

**Comment by Alexander01998** [comment]
Type `.say ...`.
