### ISSUE TITLE
Perm Stare

### ISSUE THREAD

**Issue by xDeadweightx** [Wurst-Imperium/Wurst-Client#2278]
For some random reason (when using your client) I just look at the ground. I dont know why but it wont let me look anywhere else.

**Comment by Alexander01998** [comment]
You are probably using Derp, Tired or HeadRoll on a NoCheat+ server. Turn that off and you'll be fine.

**Comment by xDeadweightx** [comment]
Incorrect im not

**Comment by xDeadweightx** [comment]
Here is a video also: https://www.youtube.com/watch?v=-tJepqf1UwM
