### ISSUE TITLE
GhostHand enhancement

### ISSUE THREAD

**Issue by Eyremba** [Wurst-Imperium/Wurst-Client#2279]
Currently you can use ".ghosthand id ID" or ".ghosthand name NAME", but it should also be possible to use (for example) ".ghosthand entity" (allows you to interact with entities through walls, for example with villagers) and ".ghosthand players" which allows you to interact with players through walls, for example hitting them through walls.

**Comment by Alexander01998** [comment]
Please use the [Wurst Feedback App](https://feedback.wurst-client.tk/) for suggestions.
