### ISSUE TITLE
Why there is no Channel for Wurst in Youtube?

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#228]
Ok I found a channel about Alexander01998. But there is no video about "Wurst". What about creating a channel about Wurst's news, easter eggs, about, challenges, features. If you want to create a channel I can help you. Just saying..

**Comment by Alexander01998** [comment]
Because...

- I'm a coder, not a YouTuber;
- I don't have a decent video editing software at the moment;
- it would slow down the development of Wurst.

**Comment by Orcunegeacar** [comment]
Ok :)

**Comment by CheeseX123** [comment]
I'm a coder, not a YouTuber
Well, why can't you code and record at the same time? 
Set-up your coding stuff and plant out what you wan't to do.
Then record.
And if you're a coder then you can obviously get decent recording software, or if you have NVIDA then use that.
I don't have a decent video editing software at the moment
I can give you a torrent link to sony vegas pro 13 which is what i use to edit some videos which i do have on my own youtube channel. 
it would slow down the development of Wurst.
Only way that could happen is if you fuck around too much editing whatever you recorded. or if your computer can't handle the recording program and your coding.
