### ISSUE TITLE
Perm Stare - Closed without a reply

### ISSUE THREAD

**Issue by xDeadweightx** [Wurst-Imperium/Wurst-Client#2280]
So my other was closed. The information he said was incorrect. I stare at the ground or my cursor just randomly appears to be looking anywhere. I am not sure why because this doesn't happen on the normal minecraft. Not using derp or anything and this still happens on the single player worlds.
Here is a video also: https://www.youtube.com/watch?v=-tJepqf1UwM

**Comment by 1337HaxorKiddie** [comment]
@xDeadweightx This video is private. Change it to unlistet.

**Comment by xDeadweightx** [comment]
Updated
