### ISSUE TITLE
OP Sign does not work in Survival

### ISSUE THREAD

**Issue by DataPools** [Wurst-Imperium/Wurst-Client#2282]
Proof:
https://youtu.be/lMyNNvq2bsc

**Comment by ex0rpass** [comment]
@DataPools Can i add you on steam? you can add me on http://steamcommunity.com/id/therealevilotto/

**Comment by DataPools** [comment]
Pardon me, Alexander, but both duplicate issues were closed and you said that the servers were faking to be vanilla, but I don't think it works in vanilla either

**Comment by ex0rpass** [comment]
@DataPools Did you add me? We can hack togeter on driffent servers because i saw you record some videos

**Comment by Alexander01998** [comment]
> but I don't think it works in vanilla either

Look, I know that it works in vanilla. I've published [two](https://www.youtube.com/watch?v=lVm3I4Y3Pao) [videos](https://www.youtube.com/watch?v=Ix-LmaFFvj4) of griefing with it in the past week, I've griefed a server with it just a few hours ago and I've seen other people griefing with it [here on GitHub](https://github.com/Wurst-Imperium/Wurst-Client/issues/2283) and [on YouTube](https://www.youtube.com/watch?v=uG-5TQWLvms).

**Comment by DataPools** [comment]
Sorry, I posted this before I knew the video came out. I just tried it out now is there something I am doing wrong in the video?

**Comment by ex0rpass** [comment]
@DataPools Add me on steam and i will show you http://steamcommunity.com/id/therealevilotto/

**Comment by Alexander01998** [comment]
@ex0rpass Stop with the steam stuff!

**Comment by Alexander01998** [comment]
> Sorry, I posted this before I knew the video came out. I just tried it out now (It still does not work) is there something I am doing wrong in the video? I think I followed the tutorial correctly

It's always possible to run into a server where it wont work. Just try another one, I'm sure you'll find find one that works.

**Comment by DataPools** [comment]
I found the problem. I was playing on 1.8.3 Vanilla servers where it apparently does not work. Just tested out on 1.8 and it does work. Thanks for helping me through my stupidity :)

**Comment by ex0rpass** [comment]
@DataPools I have some 1.8 vanilla servers.

Want to go griefing?
