### ISSUE TITLE
Op sign not working? Read this

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2284]
So you want to go griefing with your friends? Or on your own? :sob: 

Simply follow these simple steps!

Step one. Go on https://www.reddit.com/r/mcservers/ or http://www.planetminecraft.com/resources/servers/?order=order_latest

Step two  FOR REDDIT go to the NEW area and you will find newly started servers  ( make sure its 1.8 vanilla FOR PLANET MINECRAFT go on latest then for any type pick Vanilla Then for Any game version pick 1.8 

Step three Join the server get some wood make a sign then.....

Step five Post it on hackforums or github that you got op. and then people will join and grief it with you!

HAPPY GRIEFING!!!!!

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Good idea but i have a good to, get a nitrado (Or any other big hoster like g-portal) Minecraft-Server Ip (i use this website: http://www.minecraft-serverliste.com/ ). This ip should look like this: 128.65.215.208 . If you have that change the number after the last dot to 1 like this: 128.65.215.1 . If you have done that, open wurst go to Multiplayer, Serverfinder and fill in the modified Ip (128.65.215.1). Press Search and you will get about 100 servers.

NOTICE: If you find a Ip with letters like this: firealex.elemtiux.net and you are on windows, open up the CMD Console and write in it: ping firealex.elemtiux.net . If you done that it should look like this: 

![ping servers](https://cloud.githubusercontent.com/assets/11871421/10262303/2af29a20-69c3-11e5-9364-cf878bdf3180.JPG)

if it doesn´t look like this you did something wrong but as you can see in the picture is a numeric ip: 148.251.135.226 and with this numeric ip you can do the first part that i explained.

Sorry for bad english and correct me am i wrong.

**Comment by LolDatSec** [comment]
Get a few minecraft hosting providers's ips, then
```bash
nmap -sV -p 1025-65534 [host-ip]
```
Find about 1000 servers.

**Comment by Alexander01998** [comment]
This is not a forum, please don't use it as one.

**Comment by 1337HaxorKiddie** [comment]
@Alexander01998 But we have no other platform where we wurst users can interact together! Or am i wrong?

**Comment by Alexander01998** [comment]
> But we have no other platform where we wurst users can interact together! Or am i wrong?

YouTube, Twitter, whatever. Just not here, this is an issue tracker.

**Comment by ex0rpass** [comment]
@Alexander01998 Then why dont we make a forum page?

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Thats also my idea, but anyone must pay for the page.

**Comment by ex0rpass** [comment]
@1337HaxorKiddie Should i just make one?

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass If you know how and you want to do it, why not.

**Comment by ex0rpass** [comment]
@1337HaxorKiddie and @Alexander01998 http://wurst.enjin.com/home

Just made one

I will update it later on :smile:

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Okay, looks good.

**Comment by Alexander01998** [comment]
> @1337HaxorKiddie and @Alexander01998 [removed]
> 
> Just made one
> 
> I will update it later on

I don't want a Wurst forum.

**Comment by 1337HaxorKiddie** [comment]
@Alexander01998 But why?

**Comment by ex0rpass** [comment]
@Alexander01998 YouTube, Twitter, whatever. Just not here, this is an issue tracker.

You said "whatever" So that got me thinking to make a forum page

**Comment by Alexander01998** [comment]
> But why?

Forums & IRCs are extremely hard to moderate and protect against spam, especially if they are created by someone else, because then I have no control over it.

**Comment by ex0rpass** [comment]
@Alexander01998 Do you want me to make you admin?

**Comment by Alexander01998** [comment]
> Do you want me to make you admin?

No.
