### ISSUE TITLE
OP-Book

### ISSUE THREAD

**Issue by nerdtron123** [Wurst-Imperium/Wurst-Client#2285]
Same concept of op-sign but op-book and when a server operator clicks text it executes command

**Comment by ex0rpass** [comment]
@nerdtron123 We have that already....

Get a book 

Then wright in it

then click on the right Command Link

Then type in a command

ta da

**Comment by 1337HaxorKiddie** [comment]
@nerdtron123 @ex0rpass NOTICE: Some servers patched that also.

**Comment by LolDatSec** [comment]
Book hack existed since like 7 updates ago...

**Comment by nerdtron123** [comment]
one that uses json data?

**Comment by Alexander01998** [comment]
https://www.wurst-client.tk/wiki/Special_Features/Force_OP_(BookHack)/
