### ISSUE TITLE
The Update Box

### ISSUE THREAD

**Issue by EZAwesomeness** [Wurst-Imperium/Wurst-Client#2286]
I dunno what it is called but i think it is the "Update Box". The problem is i can't remove it or cancel the update. It's always there. It is the big box on the upper right corner and i cant remove it, Pls. help i need quick answers!

**Comment by 1337HaxorKiddie** [comment]
@EZAwesomeness Disable internet while start.

**Comment by LolDatSec** [comment]
Open task manager and kill it, its Wurst-Updater.jar.

**Comment by Alexander01998** [comment]
That's on purpose.
Before Wurst had this auto-updater, about 80% of all users rejected all updates, used incredibly outdated versions and then complained about bugs that were fixed months ago.
That was a nightmare.
