### ISSUE TITLE
Remoteview DOES NOT WORK

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2287]
When i try to use remove view it doesent wanna work.

i did .remoteview addy6 (my friend) it switched to him for 1 secound then came back to me

fix plez

**Comment by llaurenss** [comment]
i can confirm.
![wurst](https://cloud.githubusercontent.com/assets/12222665/10266785/c0ccbf7c-6a76-11e5-94bb-2496d4696bd7.gif)

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Duplicate (#2235) of your own issue!
