### ISSUE TITLE
[Idea] Serverfinder/cleanup filters

### ISSUE THREAD

**Issue by FlareHAX0R** [Wurst-Imperium/Wurst-Client#2288]
Like, what version, include spigot and/or craftbukkit, etc...

And for the finder, it should have something like "Did not meet filter: x" if a server is working, but did not meet the filter.

**Comment by DataPools** [comment]
I support. Really awesome for griefing

**Comment by ex0rpass** [comment]
@DataPools Can i add you on steam? http://steamcommunity.com/id/therealevilotto/

**Comment by Alexander01998** [comment]
@ex0rpass Stop with the Steam stuff! Last warning.

**Comment by Alexander01998** [comment]
> Like, what version, include spigot and/or craftbukkit, etc...
> 
> And for the finder, it should have something like "Did not meet filter: x" if a server is working, but did not meet the filter.

We are no longer using the Issue Tracker for suggestions. Please use the [Wurst Feedback App](https://feedback.wurst-client.tk/) instead.
