### ISSUE TITLE
[BUG] Cant see settings in the gui.

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#229]
So i opened up my gui and i cant see Settings in the gui for the update 1.8 And i cant see it for the 1.8 update and now i cant change my Killaura speed or clicks :angry: please reply back i dont know if this is a glitch or something that happend. Please reply back

**Comment by Orcunegeacar** [comment]
Please send a picture.

**Comment by Orcunegeacar** [comment]
There is warning in the all versions. Take a look 
NOTICE: If you are updating from Wurst v1.6 or an earlier version, you need to download & run Converter.jar as well. This is the last part of the Format Update, so this is also the last time you need to do this.

**Comment by Orcunegeacar** [comment]
Download the Converter.jar and run it.

**Comment by Alexander01998** [comment]
Delete (or rename) `.minecraft\wurst\gui.json`. That will fix it.

**Comment by trollmad3** [comment]
Whee is it?

**Comment by Orcunegeacar** [comment]
click on the windows logo if you're using windows. then write %appdata%
