### ISSUE TITLE
Crash Sign

### ISSUE THREAD

**Issue by nerdtron123** [Wurst-Imperium/Wurst-Client#2291]
sign that disconnects players that render it

**Comment by MyzticalTekkno** [comment]
<b><u><i>Duplicate #967</b></u></i>
<img src="https://cloud.githubusercontent.com/assets/10786571/8988252/bba4482e-36ed-11e5-8536-77bb1fca1d7e.png" alt="Please search for similar Issues before submitting yours please." style="max-width:100%;">
