### ISSUE TITLE
Over-wall Aimbot

### ISSUE THREAD

**Issue by C0de-Ninja** [Wurst-Imperium/Wurst-Client#2294]
Select a target via chat .aimbot target <name of player> or click them? idk.

Basically an aimbot mod that lets you use PlayerESP to see someone and if there is a wall between you It shoots over it and hits them. Dunno if its possible but it'd be really awesome to have in games where people make a giant wall you have to climb over or break.

**Comment by 1337HaxorKiddie** [comment]
@C0de-Ninja Possible, but why with aimbot and not with killaura?

**Comment by Alexander01998** [comment]
We are no longer using the Issue Tracker for suggestions. Please use the [Wurst Feedback App](https://feedback.wurst-client.tk/) instead.
