### ISSUE TITLE
Recover Alt Password

### ISSUE THREAD

**Issue by DataPools** [Wurst-Imperium/Wurst-Client#2295]
Hi, I have forgotten the password to an alt I have. It is in the Wurst Alt Manager. How can I recover it?

**Comment by 1337HaxorKiddie** [comment]
@DataPools I don't know it it works but i think in the wurst folder should be a txt file called "Alts" or something like that. If not than i have no idea.

**Comment by mcccs** [comment]
Goto wurst folder.Copy your key and alts.json http://lmgtfy.com/?q=Rsa+decrypt+online

**Comment by Alexander01998** [comment]
You can copy it from the password field.
