### ISSUE TITLE
Click Aimbot

### ISSUE THREAD

**Issue by C0de-Ninja** [Wurst-Imperium/Wurst-Client#2296]
When you click it automatically flicks your cursor at the nearest target in range, so you never miss a hit, but it only attacks when you click, unlike KillAura.

(pretty much a melee aimbot)

**Comment by Alexander01998** [comment]
We are no longer using the Issue Tracker for suggestions. Please use the [Wurst Feedback App](https://feedback.wurst-client.tk/) instead.
