### ISSUE TITLE
Customize Folder

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#2297]
A Customize folder in the wurst folder where users can put custom .java files to simple create custom mods and . commands

**Comment by l3399l** [comment]
I thought that ages ago haha, but I noticed that this is **really insecure** and makes a **very high possibility of bugs**.

**Comment by Alexander01998** [comment]
> I thought that ages ago haha, but I noticed that this is really insecure and makes a very high possibility of bugs.

^
