### ISSUE TITLE
Updater is not multiplatform

### ISSUE THREAD

**Issue by nerdtron123** [Wurst-Imperium/Wurst-Client#2298]
On mac/linux you cant use the auto updater

**Comment by DataPools** [comment]
It is a .jar, if you have java you should be able to run it.

**Comment by mcccs** [comment]
yes it is but itduznt work

**Comment by Alexander01998** [comment]
It's because Macs don't have `cmd.exe` to run the Jar.

**Comment by mcccs** [comment]
But we have terminal, it can run sh files

**Comment by DataPools** [comment]
They have Terminal and Macs can still run .jar files

**Comment by mcccs** [comment]
http://stackoverflow.com/questions/14581099/script-to-run-jar-file-on-mac-os-x

**Comment by nerdtron123** [comment]
So.. fix it...
