### ISSUE TITLE
criticals dont work

### ISSUE THREAD

**Issue by sacredgreed** [Wurst-Imperium/Wurst-Client#2299]
realy crit dot work :/ what i need to ddo to make it easy to kill

**Comment by ex0rpass** [comment]
Talk to the lord of gaben

**Comment by Alexander01998** [comment]
> Talk to the lord of gaben

Talk to the gabel :fork_and_knife: 

Where are these people coming from? Pretty sure I redirected all links to the Wurst Feedback App.

**Comment by ex0rpass** [comment]
@Alexander01998  Nice label
