### ISSUE TITLE
what easter eggs?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#230]
what in here is a easter egg?

**Comment by Alexander01998** [comment]
That's secret! :stuck_out_tongue_closed_eyes:

**Comment by pokeball99** [comment]
it is anything to do with a santa hat?

**Comment by Alexander01998** [comment]
> it is anything to do with the santa hat?

Maybe...

**Comment by pokeball99** [comment]
time to dig....into some source code

**Comment by pokeball99** [comment]
could u confirm how many easter eggs there are?

**Comment by Alexander01998** [comment]
> could u confirm how many easter eggs there are?

Nope.
