### ISSUE TITLE
Bugsss pls fix it

### ISSUE THREAD

**Issue by nikos44** [Wurst-Imperium/Wurst-Client#2301]
Hi! i love your hack and yeah i want to report some bugs like a problem with the settings in 2.5 and i want to add clickaimbot,velocity and fix the book hack thx !!!!!!! WURST FOR EVER !!!!!!!

**Comment by mcccs** [comment]
> Clickaimbot?

Rejected
> Velocity?

Anti Velocity? -It's called AntiKnockback
> Fix the Bookhack?

There's nothing fixable. Some updated servers can block this

> I want to report some bugs

And also we no more use Github issue tracker. We're using [Wurst Feedback App](https://feedback.wurst-client.tk)
