### ISSUE TITLE
Dont Create a issue unless its a bug 

### ISSUE THREAD

**Issue by GamingGamer12** [Wurst-Imperium/Wurst-Client#2305]
Use the Wurst FeedBack

**Comment by 1337HaxorKiddie** [comment]
@GamingGamer12 And why you do it then?

**Comment by ex0rpass** [comment]
@1337HaxorKiddie  Because hes telling people that this is a bug tracker

**Comment by 1337HaxorKiddie** [comment]
@ex0rpass Yeah, right but that should be clear and this here is no bug.

**Comment by beppe9000** [comment]
People is bugged...

**Comment by linuxcodefire** [comment]
Lol
