### ISSUE TITLE
Force OP Sign not working

### ISSUE THREAD

**Issue by mybuttstinks** [Wurst-Imperium/Wurst-Client#2306]
Hello! I recently got into a 1.8 vanilla and bukkit server. I have been informed dat it only works 1.8 - 1.8.3. I tried the Force OP sign and it did not work, Including the Command book, none of those things work. Please help

**Comment by TheNeonGuy** [comment]
the command block will only work on servers with them turned on and the op
sign is for only vanilla

**Comment by Alexander01998** [comment]
With OP-Sign, it's always possible to run into a server where it won't work. Just try another one, I'm sure you'll find one that works. I recommend using the [ServerFinder](https://www.wurst-client.tk/wiki/Special_Features/Server_Finder/) to get servers for it, that increases your chances of finding ones that work.

With BookHack, an admin must click on the book in order for it to work.
