### ISSUE TITLE
Official launcher cant see wurst in versions list

### ISSUE THREAD

**Issue by FlappyVeus** [Wurst-Imperium/Wurst-Client#2310]
what must i do?

**Comment by mcccs** [comment]
1) restart launcher
1.5) I assume that you installed wurst like other mods
2) check the versions folder, there must be a wurst folder there, in that folder there must be wurst.jar and wurst.json

**Comment by Alexander01998** [comment]
What @mcccs said.

**Comment by FlappyVeus** [comment]
still not works. wurst files is on versions folder. launcher is restarted over 9000 times. what did you mean in 1.5?
