### ISSUE TITLE
Can not use damage value with .give

### ISSUE THREAD

**Issue by DataPools** [Wurst-Imperium/Wurst-Client#2311]
I tried to give myself an invisible potion with a specific NBT value and I couldn't specify damage values

**Comment by 1337HaxorKiddie** [comment]
@DataPools Yes, because an invisible potion can't give you damage.

**Comment by DataPools** [comment]
Have you heard of "damage values." Like coarse dirt is like the id of 3:1 the damage value is the value after the colon. it is kinda like a subset of a certain item.

**Comment by 1337HaxorKiddie** [comment]
@DataPools Ahh, okay I know what you mean but should work. As far as i know are all nbt tags are working.

**Comment by Alexander01998** [comment]
NBT tags are independent of damage values, so what is your problem?

**Comment by DataPools** [comment]
I would like to make an invisible potion, but with an nbt tag if showing no particles

**Comment by Huanjohn** [comment]
@DataPools You can just make it invisibility 128 or more, potion effects over 127 show no particle effects.
