### ISSUE TITLE
.ping Command

### ISSUE THREAD

**Issue by Wurst-is-Best** [Wurst-Imperium/Wurst-Client#2312]
On its own .ping show your ping and with a username after it, it shows their ping. Also pressing tab should show everyones exact ping.

**Comment by mcccs** [comment]
Duplicate: #1979

**Comment by Wurst-is-Best** [comment]
Not exactly...

**Comment by mcccs** [comment]
How about merging these commands?

**Comment by Wurst-is-Best** [comment]
Lol, mine is merging the commands and yours is just half of what I said. +1:  :D

**Comment by mcccs** [comment]
But mine includes laggcheckrr

**Comment by Wurst-is-Best** [comment]
:(
