### ISSUE TITLE
No slowdown on BlockWeb.

### ISSUE THREAD

**Issue by mossyblog** [Wurst-Imperium/Wurst-Client#2314]
Noticed you had no slow-downs on BlockWeb in Minecraft Source..

 public void onEntityCollidedWithBlock(World worldIn, BlockPos pos, IBlockState state, Entity entityIn)
    {
    	if(WurstClient.INSTANCE.modManager.getModByClass(NoSlowdownMod.class).isActive())
    		return;
        entityIn.setInWeb();
    }
Will fix that.

**Comment by Alexander01998** [comment]
There already is a NoWeb mod for that.
