### ISSUE TITLE
Forceop Sign Not Working

### ISSUE THREAD

**Issue by MiseroMax** [Wurst-Imperium/Wurst-Client#2316]
No server I find works at all.
50.31.103.68:25565
is one that is up atm. 
Anyone else getting this problem? (Wurst 2.6)

**Comment by 1337HaxorKiddie** [comment]
@MiseroMax This server looks extremly like an 1.8 server. But the damage hack is not working that means they have a anticheat or something like that and it is impossible ti burn on it. I think its a spigot server or something like this.

**Comment by MiseroMax** [comment]
Hm. Well then, back to looking at the bottoms of sites like 44mcservz.biz

**Comment by BoomBoomLHack** [comment]
![2015-10-12_07 47 14](https://cloud.githubusercontent.com/assets/9440126/10427240/cc9ced8c-70b5-11e5-8a0e-47337d1927bd.png)
lol

**Comment by DataPools** [comment]
Any version above 1.8 it is patched on and will not work, for some reason

**Comment by MyzticalTekkno** [comment]
@DataPools like alexander said
works for some vanilla servers &
doesn't work for some vanilla servers.
