### ISSUE TITLE
Light level detecter

### ISSUE THREAD

**Issue by Whatisthisname** [Wurst-Imperium/Wurst-Client#2317]
*Detector

A feature that will show the light level with a number on top of the block texture, and make it red if mobs can spawn there. Should be under the Render tab.
----------------------------------------------
I know this shouldn't be posted here, but I didn't wanna bother making a new account on the feedback app. Would someone be so nice and add this?

**Comment by Whatisthisname** [comment]
Sorry, It already exists, duplicate. Still, ad it to the feedback app.

**Comment by 1337HaxorKiddie** [comment]
@Whatisthisname Really? It doesn't took more than one minute!

**Comment by mcccs** [comment]
F3?
