### ISSUE TITLE
Crash Chest /give command

### ISSUE THREAD

**Issue by im4nthony** [Wurst-Imperium/Wurst-Client#2319]
How would I /give <otherplayer> Crash chest? I know I can drop it to them but to make things simpler what would be the command to give someone a wurst chest. This is not a request to add a feature I just wanna know how to do it

**Comment by nerdtron123** [comment]
you can't give it to someone else unless you have op.

**Comment by im4nthony** [comment]
Ugh I do have OP how do I do it?
