### ISSUE TITLE
Nuker attempts to destroy covered blocks

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#2320]
I enabled nuker and overlay, and i see the nuker hopelessly trying to destroy a diagonal block that is not visible (adjacetnt to air) , only to be denied by cheat protection.

You could add maybe a "visible" mode for nuker, but I think that it should be the default behaviour for nuker...

**Comment by ex0rpass** [comment]
This will help you #2330


@Alexander01998  Close it.

**Comment by beppe9000** [comment]
This is older than that.
