### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by SGLMerlijn** [Wurst-Imperium/Wurst-Client#2322]
2 of my rows of hacks are exactly inside of eachother, so i can't get them out of eachother, and i can't select any of the hacks that are behind the bigger row of hacks. please tell me a way how to get these two rows out of eachother.
PS Sorry for my bad englisg :)

**Comment by mcccs** [comment]
Click n hold the hack title. Then move it to somewhere

**Comment by SGLMerlijn** [comment]
i know but i cant do that

**Comment by SGLMerlijn** [comment]
i not noob with wurst

**Comment by SGLMerlijn** [comment]
the upper part is out of my screen

**Comment by mcccs** [comment]
Could you please give us a screenshot? (F2 Default)

**Comment by SGLMerlijn** [comment]
![2015-10-13_17 31 38](https://cloud.githubusercontent.com/assets/15091960/10459560/62c3f100-71d0-11e5-8838-9edf626e6f54.png)

**Comment by mcccs** [comment]
Oops. 

Goto .Minecraft/wurst and delete gui. Json

**Comment by SGLMerlijn** [comment]
its not the right name

**Comment by im4nthony** [comment]
ok simple. go to settings and change gui size to small then move it somewhere and put it back to where it was before... happened before to me

**Comment by SGLMerlijn** [comment]
which settings?
the wurst options?

**Comment by im4nthony** [comment]
no video settings

**Comment by SGLMerlijn** [comment]
still cant pick them up

**Comment by SGLMerlijn** [comment]
it just goes more to the left, but i have to get it down

**Comment by beppe9000** [comment]
The solution (in code) is to limit the Y coordinate of mod groups to positive values.

**Comment by SGLMerlijn** [comment]
and how do i do that?

**Comment by beppe9000** [comment]
You fork wurst fix the error and then send a pr. If don't understand this leave this task to the ones who do.
