### ISSUE TITLE
How to include code added to MCP in a pull request?

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#2324]
I'm in the process of adding some mods and commands. Some of them require some code in the MCP decompiled sources. How do I include these modifications as well? Do I have to make a patch file and patch the existing `minecraft.patch` in order to update it?

**Comment by DataPools** [comment]
You make a patch file, I believe. It is illegal to distribute modified MCP code

**Comment by beppe9000** [comment]
Yes, even unmodified code distribution is illegal.

**Comment by l3399l** [comment]
@Nitrogen-Dioxide tried to do that a lot of times, but it seems that only @Alexander01998 has the control of it :/ .

**Comment by Alexander01998** [comment]
> @Nitrogen-Dioxide tried to do that a lot of times, but it seems that only @Alexander01998 has the control of it :/ #2213

I'm pretty sure that @Nitrogen-Dioxide's PC handles line breaks differently and that that's the reason why the patch looks different when he tries to generate it. It works fine for the majority of people.

**Comment by l3399l** [comment]
The only person I saw modifying this patch file was @BuildTools, and he doesn't generated a new patch file (he only modified 1 line), so, without seeing anyone reproduce this patch file is hard to know if other people can generate it :/.

https://github.com/Wurst-Imperium/Wurst-Client/commit/7bba308a4d97f017f20b001c9991f612f7b29c6b

History of patch file: 
https://github.com/Wurst-Imperium/Wurst-Client/commits/master/patch/minecraft.patch

**Comment by beppe9000** [comment]
I have an idea: we could use a source-tagging system to achieve self-contained somemod.java files.

*I will expand on this onche i get to a desktop pc.*

**Comment by mcccs** [comment]
Great

**Comment by l3399l** [comment]
The idea is perfect but... It looks like alexander is ignoring it :/

**Comment by Alexander01998** [comment]
@beppe9000 You are reinventing the wheel there. This is exactly what Git does, only with a different syntax.

**Comment by beppe9000** [comment]
So, why aren't there self-contained mod files, if Git does that?
