### ISSUE TITLE
please stop closing ang give link to help

### ISSUE THREAD

**Issue by sacredgreed** [Wurst-Imperium/Wurst-Client#2325]
One word criticals > you are jumping a little in air, BUT you dont deal crit dmg
you only use crit cheat, all see you have it .... ,BUT dont exist
please repair it in java or delete it immediately  

                                                      your lovely kid

**Comment by DataPools** [comment]
In order to get a critical you must jump. Crits are also random, the mod just jumps for you

**Comment by Alexander01998** [comment]
That probably means that you are on a server that has patched Criticals.
