### ISSUE TITLE
Freecam and Blink

### ISSUE THREAD

**Issue by storayy** [Wurst-Imperium/Wurst-Client#2328]
I was wondering how the Freecam and Blink code work, mainly freecam. I do not understand how it is cancelling packets without it being called in FreecamMod.java. Explanation on how it is being done?

**Comment by im4nthony** [comment]
lul noob

**Comment by storayy** [comment]
@im4nthony No, my freecam works fine. I cancel player movement and re-track WASD to a new camera with EntityRenderer. I'm just confused on how @Alexander01998's code works.

**Comment by im4nthony** [comment]
lul noob

**Comment by mcccs** [comment]
@im4nthony Come on, don't be rude

**Comment by im4nthony** [comment]
lul nub.. sry I was trolling idk myself xD
