### ISSUE TITLE
A way to remove the active hacks and client name from the top left.

### ISSUE THREAD

**Issue by Nick1234567** [Wurst-Imperium/Wurst-Client#233]
It is a must have for YouTube!

**Comment by Orcunegeacar** [comment]
Never.

**Comment by Orcunegeacar** [comment]
Because he worked a lot for the client, and there is a lot of way to edit the client. But please be good at the creator of the client. He works ever second to add new things to client

**Comment by OMGchangeMYusername** [comment]
well the mod names can be disabled from options but the logo or whatever must be in there.
why do you record with hack anyway?

please add a command `.disable wurst` it could be a great alternative,it completely closes wurst and let you play vanilla 1.8 till you close minecraft and reopen wurst :wink:
