### ISSUE TITLE
Bug with Wurst

### ISSUE THREAD

**Issue by Thoooooooooomas** [Wurst-Imperium/Wurst-Client#2331]
When I installed Wurst, the sound of my earphones did not walk(work) any more while on my telephone they walk very well, it walks any more with no earphone no matter the mark, while without, I have of the sound, if you know why this bug intervened and how for repairing him I would be grateful for it, thank you in advance.

**Comment by 1337HaxorKiddie** [comment]
@Thoooooooooomas 2 Things, 1. Learn english, 2. #2330

**Comment by BoomBoomLHack** [comment]
@Thoooooooooomas wtf are you talking about?
