### ISSUE TITLE
Spammer

### ISSUE THREAD

**Issue by chr100** [Wurst-Imperium/Wurst-Client#2335]
I need to know how to use spammer it doesnt make sense. there is a button that says spam and when i click it it writes it 1 time only the ms is on 200 so it should do it all the time. Alexander pls help me becouse i know how to bypass all anticheat with this method!!!!! :dancers: Add me on skype if you wanna know: chrholst10001

**Comment by 1337HaxorKiddie** [comment]
#2330 READ IT!

**Comment by im4nthony** [comment]
you dum
bass
