### ISSUE TITLE
A Tutorial on how to chain OptiFine to Wurst

### ISSUE THREAD

**Issue by xXStriateXx** [Wurst-Imperium/Wurst-Client#2336]
Hello Alexander, Wurst is a great client and i would love to use it HOWEVER i need optifine because i have a pretty crappy comp, ive seen from other posts you wont add it. could you atleast make a vid or something to show how you chain OptiFine to Wurst? it would be gladly appreciated thanks =)

**Comment by LolDatSec** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/issues/2330

**Comment by mcccs** [comment]
Also #2

**Comment by TekkitCommando** [comment]
Use the new suggestion thing as well

**Comment by TekkitCommando** [comment]
And if you want to learn how to integrate optifine into a client, stop being lazy and look it up on YouTube. Alexander doesn't have to do every little thing :)
