### ISSUE TITLE
Game crashes when nuker turns on next to a mob or player.

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2337]
Please fix

**Comment by ex0rpass** [comment]
@Alexander01998  Can you fix it or are you just going to ignore me :sob:

**Comment by PixelMaster3D** [comment]
#2330. This is the only way he'll talk to you.

**Comment by PixelMaster3D** [comment]
Pretty sad, Right?

**Comment by ex0rpass** [comment]
@PixelMaster3D  I already saw that. But i wanted to be come a thug.
