### ISSUE TITLE
Is there a forum that posts servers to grief?

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2339]
Since we are not allowed to post on this forum i will now be moving (NOTE I WILL STILL DOWNLOAD WURST AND SUPPORT IT ^_^) to a new forum that posts servers to gref and about minecraft hacking YES I KNOW hackforums and mpgh unknowncheats, Does anyone know any?

**Comment by ex0rpass** [comment]
@Alexander01998  I just want to know. jesus.......it wont harm anyone. and after i find a good website ill leave this github crap hole 4ever (ill still support wurst)

**Comment by pokeball99** [comment]
@ex0rpass this has been asked many times before,no theres not,because it would be alot for alex to manage

**Comment by ex0rpass** [comment]
@pokeball99  No. I dont want him to make one either me or the community. I just  want to see if there is any websites about minecraft hacking and griefing
