### ISSUE TITLE
Site not loading at school

### ISSUE THREAD

**Issue by linuxcodefire** [Wurst-Imperium/Wurst-Client#2341]
Ur site isnt loading at all at my school.

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire READ IT! #2330

**Comment by linuxcodefire** [comment]
@1337HaxorKiddie @Alexander01998 i cant access the freaking page at freaking school... How do i post... On the page if it wont ---- load...

**Comment by 1337HaxorKiddie** [comment]
@linuxcodefire 1. Why do you want to acces the site at your school? 2. Wich site? 3. I think the IT Admin on your school has blocked this page, ask him if you really want to see the page at the school.

**Comment by Huanjohn** [comment]
Have you tried using a proxy to connect?

**Comment by liach** [comment]
@linuxcodefire I agree with you. At school I cannot even use proxies as the computer does not allow them to run.

**Comment by mcccs** [comment]
also try hidemyass.com/proxy

**Comment by PixelMaster3D** [comment]
@linuxcodefire I must ask a question before i give you this info. Does your school allow jar to run? Does your school allow VPN connections? Do you know how to setup a VPN connection?

**Comment by linuxcodefire** [comment]
@PixelMaster3D  its a ipad so no files can be downloaded.. No appstore access.

**Comment by PixelMaster3D** [comment]
Hmm. So you try to download a file off the App Store or are you trying to download it off the internet?
