### ISSUE TITLE
I know that you don't want new issues but...

### ISSUE THREAD

**Issue by l3399l** [Wurst-Imperium/Wurst-Client#2344]
Take a look at this mod I made.... Its quite useful.

https://github.com/l3399l/Wurst-Client/blob/51b48fb5594cdd98a327478958c886d3138b2cb9/Wurst%20Client/src/tk/wurst_client/commands/CopyItemCmd.java

And... I changed give cmd a little (you can give/drop items at any slot). Added getnbt to copy nbt tags from held items.

https://github.com/l3399l/Wurst-Client/commit/53704670278d8a8a830db21a06f67b1d7a80fc4d

**Comment by 1337HaxorKiddie** [comment]
@l3399l Okay, it looks good, BUT as you told, use the Wurst Feedback App!

**Comment by l3399l** [comment]
Btw, just raided a server by copying an item from admin's hand.

The item was a pickaxe that doesn't care about protected land '-'
