### ISSUE TITLE
When using proxy it says the auth servers are currently down for maintenance  

### ISSUE THREAD

**Issue by ex0rpass** [Wurst-Imperium/Wurst-Client#2348]
Please fix

**Comment by mcccs** [comment]
Mojang can detect proxies, you need a better proxy

**Comment by cristiansc1993** [comment]
anonymous proxies identify themselves as proxies, try using a high anonimous one

**Comment by null-dev** [comment]
Why not we just disable proxies for authentication and only use them for connecting to the server.

**Comment by cristiansc1993** [comment]
That's a very good idea unless the server keeps a record of your IP logs, in this case would be useless and very hard if not impossible to know if they do as every admin makes pretty-much whatever they want
