### ISSUE TITLE
how do I use wurst timer

### ISSUE THREAD

**Issue by dfr453** [Wurst-Imperium/Wurst-Client#2354]
How do I use wurst timer

**Comment by mcccs** [comment]
type .t timer to enable timer and adjust timer speed in settings frame

**Comment by dfr453** [comment]
Ok thanks I love the speed!! <3 Wurst in general!! Alexander your epic!!!!!

**Comment by mcccs** [comment]
Also, @dfr453 wurst has an online wiki ([wurst-client.tk/wiki](https://wurst-client.tk/wiki)). Check it out!
