### ISSUE TITLE
Auto Tool Update?

### ISSUE THREAD

**Issue by xDeadweightx** [Wurst-Imperium/Wurst-Client#2361]
I created an autotool update for the client. Let me know what you think:
http://pastebin.com/U4LxHnGW

It should grab your the best tool from any where in your inventory. That also includes it not being on your hotbar (1-9). If it isn't on your hotbar then it will switch places with slot one. ^^

**Comment by ThisTestUser** [comment]
Better to add this to the pull requests. Issues probably won't be read.

**Comment by xDeadweightx** [comment]
Ah i tried to do that but it wont let me post
