### ISSUE TITLE
built-in world mapper

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#238]
i know they have many mods for this but it be cool to have this integrated into wurst

**Comment by lmftiv** [comment]
I'll 2nd this. I have been missing this for a long time.. :)  Jmapper would be nice..

**Comment by JamesJebson** [comment]
This will be great as I know other 1.8 clients have this, but the client's are not as good as Wurst :)

**Comment by pokeball99** [comment]
what i would recommend to implement for this is voxel map,as it is pretty flushed out plus it would knock out #408 too
