### ISSUE TITLE
White Screen Error

### ISSUE THREAD

**Issue by webboytm** [Wurst-Imperium/Wurst-Client#241]
Sometimes when you turn around (or what i have experienced) the Minecraft screen turns white for a second then goes back to normal.

**Comment by webboytm** [comment]
well i don't know what is causing this, this is a brand new gaming computer built just for gaming. This is the only mod that has done this to me

**Comment by webboytm** [comment]
Never mind, just a quick uninstall and re-install fixed it

**Comment by Orcunegeacar** [comment]
Sometimes it's white when I'm in water too. I guess a mod doing this.
