### ISSUE TITLE
make large mod tabs scrollable

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#242]

**Comment by pokeball99** [comment]
what i mean is that say the tabs render,combat and movement,which are the largest tabs,make them so they show 3 or 4 at the same time and make a little scrollbar on them

**Comment by Alexander01998** [comment]
> what i mean is that say the tabs render,combat and movement,which are the largest tabs,make them so they show 3 or 4 at the same time and make a little scrollbar on them

Unless you mess up your settings, the frames perfectly fit onto any screen.
