### ISSUE TITLE
How to make autobuild jsons

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#245]
You can open the .json with a notepad, but when i try to modify it, wurst crashes, is there a way to make auto build templates as the tutorial?

**Comment by Alexander01998** [comment]
> You can open the .json with a notepad, but when i try to modify it, wurst crashes

That means your JSON code is invalid. The easiest way to find & fix the error is to use a JSON editor, such as [Atom](http://atom.io) or [F*ck Cubik](http://fuck-cubik.wurst-client.tk).

> is there a way to make auto build templates as the tutorial?

Assuming that you are familiar with [JSON](http://json.org):

- An AutoBuild template is a JSON object with a `blocks` property.

- The `blocks` property is a JSON array containing the blocks in the order you want to place them.

- Each block is a JSON array of either 3 integers (`X`, `Y`, `Z`) or 4 integers (`X`, `Y`, `Z`, `side`).

- The 3 integer blocks & 4 integer blocks cannot be mixed, meaning that one AutoBuild template can only use one type of block.

**Comment by Nitrogen-Dioxide** [comment]
Thanks!
