### ISSUE TITLE
make fly in wurst better ...

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#246]
Before i was know about wurst i was have x-ray mod and Were his features like fly and xray and ...
when i was flying with the mod in Survival mode When you fly to high Distance and back down I did not die and "you have fallen from a high place" Message did not come to me ,but wurst contrary so try to make fly in wurst  like the mod and this is the mod : http://www.mediafire.com/download/74dohz9uyafu6z7/XRay-1.8.1-v2.14.2.jar

**Comment by Alexander01998** [comment]
Use NoFall.

**Comment by osa219** [comment]
in servers too ?
becuse its work in servers
