### ISSUE TITLE
X-Ray not showing all ores

### ISSUE THREAD

**Issue by Gulle123** [Wurst-Imperium/Wurst-Client#247]
The blocks like diamond a gold etc sometimes disappear when im using it and then i have to turn the camera another angle to see them again

**Comment by Alexander01998** [comment]
Currently, this is the only known fix:

1. Enable Freecam
2. Fly into solid block

**Comment by pokeball99** [comment]
can confirm,but for me its does chucks,i just spam the xray toggle till it goes back to normal

**Comment by osa219** [comment]
you Should try to solve the problem :(

**Comment by aidam400** [comment]
I have this proble too. Please Help me I cant mine

**Comment by Alexander01998** [comment]
Fixed in 240446743d8d21165244605d1787b36c60680bbd, I got confused with the numbers.

**Comment by Alexander01998** [comment]
It's not completely fixed, but definitely a lot better now:

before
![broken X-Ray](https://cloud.githubusercontent.com/assets/10100202/9226964/75bce734-4111-11e5-9eda-b3d90e4a1490.png)

after
![fixed X-Ray](https://cloud.githubusercontent.com/assets/10100202/9226970/7a933f06-4111-11e5-9893-beea076c350a.png)
