### ISSUE TITLE
rough schedule on version releases? 

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#248]
so is it going to be about once a week,every other week or what?

**Comment by Nitrogen-Dioxide** [comment]
Ok, so you think alexsander will make a version for day? ALONE? be patient there is other things to add on wurst before your "world mapper", he is doing a GREAT work, don't push him to add features fast, for FREE because YOU want...

**Comment by Alexander01998** [comment]
> so is it going to be about once a week,every other week or what?

Once per week, every Friday.

> be patient there is other things to add on wurst before your "world mapper", he is doing a GREAT work, don't push him to add features fast, for FREE because YOU want...

I don't implement the issues in any specific order. Instead, I implement my own ideas and the issues based on how much I like them, how much time they consume, etc.

**Comment by pokeball99** [comment]
@Nitrogen-Dioxide i was not be "pushy' with the question i just ask a simple question that would be asked sooner or later,i just did it first
