### ISSUE TITLE
X-Ray destroys Redstone

### ISSUE THREAD

**Issue by JTLCraft** [Wurst-Imperium/Wurst-Client#25]
Whenever I add in a mod (X-ray, True sight, ect) on my single player world it deletes my red stone tickers. This is very frustrating because i need to see if my invisible mobs were spawned correctly and whenever I turn on true sight all my red stone clocks are gone. This is a very good mod for multi-player severs but it seems that there are quite a few bugs left to sort out. If you want video evidence then send me a email at jakob99lentz@gmail.com and I will send you the video that I just took of me setting up my ticker then using x-ray then turning it off and having the ticker vanish. I repeated the process a few times, pausing the video so that I can set up the red stone again at some points.
![screenshot 1](https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t34.0-12/10965795_353409791518884_1489574565_n.jpg?oh=62f3a78c31ab4d2bccbe62075e02270a&oe=54DE1DDE&__gda__=1423903310_a4c7c9dfe46e818597190cf58a5fbd50)

![screenshot 2](https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t34.0-12/10984774_353409794852217_309215306_n.jpg?oh=b194abdb89ad7aa88d8f6a82c9d75819&oe=54DF2E42&__gda__=1423850911_e9cae7496803d5e505a26e5edbb73ef0)

![screenshot 3](https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t34.0-12/10997054_353409801518883_2057964070_n.jpg?oh=57868b41c8f72905c99bcffdb4599815&oe=54DE4CA9&__gda__=1423855353_b4cafb0c7ac54fe2824df650dc4a9931)

**Comment by Alexander01998** [comment]
The screenshots are broken, please re-upload them.
