### ISSUE TITLE
Colored chat messages are gone

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#252]
the chat isn't colored anymore. Yes, i checked my mulitplayer settings

**Comment by WaffleMonkey** [comment]
Same

**Comment by WaffleMonkey** [comment]
While talking and bugs and stuff could you please add optifine and I'm new to github.

**Comment by MrMinecraft15** [comment]
Same

**Comment by OdinGG** [comment]
Same!

**Comment by Spassvogelw** [comment]
Links and other Chat functions arent working too

**Comment by solidshadow96** [comment]
yea same the chat is working fine but all text color is not working and can not be seen im not shure if this is regarding the server text compatibility with wurst or its just a bug but this needs to be fixed. this problem did not occer on the last version of wurst before 1.9 thnkyou and please try and fix this!!!

**Comment by ZyCoShaDY** [comment]
Same issue.

**Comment by championriven** [comment]
Yup, all my servers the color in chat won't work.

**Comment by Laqured** [comment]
Same

**Comment by trollmad3** [comment]
Same hear.....PLEASE FIX IT
