### ISSUE TITLE
LSD not deactivating cinematic camera when disabled

### ISSUE THREAD

**Issue by nizilu** [Wurst-Imperium/Wurst-Client#260]
if you turn off the LSD Mod the mouse effect isn't deactivated ~~and you must restart Wurst to turn it off~~
sorry for my bad english, im from germany ;D

**Comment by Alexander01998** [comment]
> and you must restart Wurst to turn it off

Nope! This can be done with a (vanilla) keybind.

**Comment by Nitrogen-Dioxide** [comment]
In the "old days" cinematic camera was F8 by default, idk why they removed it.

**Comment by Alexander01998** [comment]
> In the "old days" cinematic camera was F8 by default, idk why they removed it.

It can be re-added in the options.

**Comment by Nitrogen-Dioxide** [comment]
Yea, it is quite no sense to remove a keybind xD .
