### ISSUE TITLE
1.9 version causing lots of lag on servers.

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#264]
Wurst 1.9 is not working on servers, the latency is going over 700 ms then, you disconnect.

**Comment by Alexander01998** [comment]
Tested on dozens and dozens of servers and working just fine.

You must have found a broken server...

**Comment by Nitrogen-Dioxide** [comment]
I tested on a lot of servers too, with diferent launchers etc etc, the same thing :/ .

**Comment by Orcunegeacar** [comment]
Maybe its the web connection. Was this happennig before

**Comment by Orcunegeacar** [comment]
before the version 1.9

**Comment by Nitrogen-Dioxide** [comment]
No, with version 1.8 of wurst it is fine, another thing that happens, is that i cant mine blocks, it looks like i am at adventure mode, but not. Used panic to disable all the modules but does not fix anything. For some reason, wurst starts alocating a lot of ram (1.3 GB-1.5 GB) and and lags everthing.
![sem titulo](https://cloud.githubusercontent.com/assets/11248300/6762616/b501eab6-cf42-11e4-99b2-331858d52b24.png)

**Comment by Nitrogen-Dioxide** [comment]
It have a high cpu usage too, about 70% of my processor

**Comment by Nitrogen-Dioxide** [comment]
I think that there is a module that starts looping and looping again, causing everthing.

**Comment by OMGchangeMYusername** [comment]
well that happened to me too!
it's not precisely everything or everytime but sometimes my fps goes down to 0!
**which i never saw before!**
