### ISSUE TITLE
Website link broken http://www.wurst-client.tk/news/feed.xml

### ISSUE THREAD

**Issue by Pickraft** [Wurst-Imperium/Wurst-Client#27]
Hello. It's "That Guy" here to hopefully helpfully harass you.
The page http://www.wurst-client.tk/news/feed.xml is broken.

**Comment by Notchshero** [comment]
no, it is'nt

**Comment by Alexander01998** [comment]
It's working fine for me. Please re-open this issue with more information.

**Comment by Pickraft** [comment]
When I go to the page it gives me this:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
<channel>
<title/>
<description/>
<link/>
<atom:link href="/news/feed.xml" rel="self" type="application/rss+xml"/>
<item>
<title>New Website</title>
<description>
<p>After about two weeks of coding, the new Wurst Client website is finally here! Just like the Wurst Client, this website is open source. You can find it’s source code at <a href="https://github.com/Wurst-Imperium/wurst-client.tk">GitHub.com/Wurst-imperium/wurst-client.tk</a>.</p>
</description>
<pubDate>Sun, 08 Feb 2015 00:00:00 +0100</pubDate>
<link>/news/2015-02-08-new-website/</link>
<guid isPermaLink="true">/news/2015-02-08-new-website/</guid>
</item>
</channel>
</rss>

**Comment by Pickraft** [comment]
![wurst pic](https://cloud.githubusercontent.com/assets/10984804/6195167/5ba56ffc-b380-11e4-8f7a-a561da5dd9c8.png)

**Comment by Alexander01998** [comment]
It's an RSS feed, it's supposed to look like that.
