### ISSUE TITLE
Killaura attacking client player when Freecam is enabled

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#275]
When i enable freecam and killaura, it attacks to me.

**Comment by OMGchangeMYusername** [comment]
lol.

**Comment by Nitrogen-Dioxide** [comment]
It can damage you too? LOL damage command.

**Comment by Alexander01998** [comment]
> It can damage you too? LOL damage command.

No, it just attacks the fake player placed by Freecam.

**Comment by Nitrogen-Dioxide** [comment]
awww :/ xD
