### ISSUE TITLE
Turn off Wurst

### ISSUE THREAD

**Issue by Wolves95** [Wurst-Imperium/Wurst-Client#276]
Please add a way to turn off Wurst either in Options or in the GUI.

**Comment by pokeball99** [comment]
Duplicate #233

**Comment by OMGchangeMYusername** [comment]
It should be a command `.disable wurst` i feel like i suggested it before but i might've stopped at the midst of writing.
it doesn't close minecraft but instead it turns everything to full vanilla 1.8.x/1.7.x mode.
and you have to restart minecraft to use wurst again.

**Comment by OMGchangeMYusername** [comment]
rejected **._.**
