### ISSUE TITLE
FIX for extreme lag in 1.9 .

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#277]
Found a fix for #264 . Delete the Modules.json BEFORE updating to 1.9. (If you have this error for sure) . Since it doesn't affect everyone.

**Comment by OMGchangeMYusername** [comment]
lol is it not working? or did you just realise it was your bad @Nitrogen-Dioxide ?

**Comment by Nitrogen-Dioxide** [comment]
no, it was really strange :p the solution is delete the modules.json in wurst folder, so, reload it .-. .
