### ISSUE TITLE
colored chat bug plz fix

### ISSUE THREAD

**Issue by missingtexture** [Wurst-Imperium/Wurst-Client#280]
on server with name or letters that can use colored chat it make it not work
not useing wrust v.9
![2015-03-21_15 31 39](https://cloud.githubusercontent.com/assets/8990711/6766723/91263a3a-cfd7-11e4-9a4d-921aaab21b99.png)
using wurst ![2015-03-21_15 29 05](https://cloud.githubusercontent.com/assets/8990711/6766718/6ebc1bd6-cfd7-11e4-8d2b-0becda54a0b0.png) it worked fine in wurst v.8

**Comment by pokeball99** [comment]
giving it a blank cause's a error with github
