### ISSUE TITLE
Killbot Bug

### ISSUE THREAD

**Issue by noway13** [Wurst-Imperium/Wurst-Client#282]
On mineplex survival games, when someone dies a dead body entity appears on the ground. When Killbot is on, it targets & attacks these entities, which gets annoying.

**Comment by Alexander01998** [comment]
> when someone dies a dead body entity appears on the ground. When FightBot is on, it targets & attacks these entities,

If these entities are represented by mobs, you can make Wurst ignore them by setting it to only target players.

If they are represented by fake players and share the same name, you can add them to your friends list instead.
