### ISSUE TITLE
Prophunt ESP Not Working

### ISSUE THREAD

**Issue by ZyCoShaDY** [Wurst-Imperium/Wurst-Client#287]
Affter updating, ProphuntESP seems to not work anymore, please fix this! lol I only play on Blockhunt Now.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
First poorly written tag there is

**Comment by ZyCoShaDY** [comment]
Sorry, I used to use "ProphuntESP" to you know, cheat. 
It would show red blocks indicating where "fake" blocks were.
It worked until the 1.9 update. Now it only shows my block as red, no others.

**Comment by eveythingistaken** [comment]
Same issue with me. Plz fix

**Comment by wkuba500** [comment]
ZyCoShaDY z Polski?

**Comment by Alexander01998** [comment]
Tested & disconfirmed.

![](https://cloud.githubusercontent.com/assets/10100202/7088837/6cece72a-df97-11e4-8632-871943d651e3.png)

**Comment by eveythingistaken** [comment]
It only works on mineplex no other servers. Is it because they're different plugins?
