### ISSUE TITLE
Force OP Usage

### ISSUE THREAD

**Issue by Ambuz** [Wurst-Imperium/Wurst-Client#288]
I don't find the "How to use" button can You guys explain me? Thanks For The help ;D

**Comment by pokeball99** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/wiki/ForceOP-(a.k.a.-AuthMeCracker)

**Comment by Alexander01998** [comment]
> I don't find the "How to use" button can You guys explain me? Thanks For The help ;D

Maybe I should add some blinking rainbow colors to the button...

![](https://cloud.githubusercontent.com/assets/10100202/6768657/bb9e6e02-d079-11e4-90a7-8bf4a777e9eb.png)

**Comment by pokeball99** [comment]
there should be a "omg its right there" label for things like this
