### ISSUE TITLE
Black window bug?

### ISSUE THREAD

**Issue by mikamika83** [Wurst-Imperium/Wurst-Client#289]
When in fullscreen mode, it opens 2 windows.
First is black, and the second is the game window.
![image](https://cloud.githubusercontent.com/assets/7735415/6768322/c697b152-d07d-11e4-9388-d78624ceb285.png)

**Comment by Alexander01998** [comment]
Wurst automatically maximizes the Minecraft window by creating its own maximized window and putting Minecraft inside of it. In fullscreen mode, Minecraft breaks out of that window and creates a new one.

If you always play Minecraft in fullscreen mode, you wont need this feature. You can disable it in the Wurst options.
