### ISSUE TITLE
Suggesting Mods

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#29]
hey i have some mods to suggest and i think it'd be magnificent if you add them!
1-QuakeAura,a really helpful mod which would be loved by a lot of wurst users!
2-fake NPCs ESP, for example when they ask you to kill a diguised guy and he's a mob.
3-Fast Friend list, lists all the names of players in your current game,and one click should add the plyer to your friends and u can click again to unfriend him (it appears the same way as render or movement)
4-ChestStealer,i think this has een suggested before. but it'd be nice to see it!
finally we want you to inform us of the next updating time,coz it's been quite a while with no updates

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
