### ISSUE TITLE
The chat doesn't show any colors.

### ISSUE THREAD

**Issue by TCHDeath** [Wurst-Imperium/Wurst-Client#295]
Has anyone noticed that whenever someone uses colored chat, it doesn't show up as a color when you're using wurst?

**Comment by GlitchHead** [comment]
Update wurst there is a new version.

**Comment by Nitrogen-Dioxide** [comment]
Version 1.9.1 fixed that.

https://github.com/Wurst-Imperium/Wurst-Client/releases

**Comment by TCHDeath** [comment]
I did update to v1.9.1 and it still doesnt work

**Comment by TCHDeath** [comment]
Oh nevermind
