### ISSUE TITLE
1.9.2 Error

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#297]
Downloaded the last version. And Opened 20 (actually 15 :laughing:) mods. And crashed lol :smile:  I know the problem is my RAM but the mods are really taking memory from ram so much. Need quick&small codes in client.

**Comment by Nitrogen-Dioxide** [comment]
Is antifire enabled?

**Comment by Orcunegeacar** [comment]
Yes I was enabling every mod and when I'm pressing the antifire and anti buttons. It crashed

**Comment by Nitrogen-Dioxide** [comment]
I think antifire and antipotion is quite "broked" never use it if you are on multiplayer.

**Comment by Alexander01998** [comment]
Duplicate: #269
