### ISSUE TITLE
AutoPotion

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#298]
I thought of a mod called "AutoPotion" , a mod that trows regen potions automatically.

**Comment by Orcunegeacar** [comment]
There is a mod called Regen. (Regeneration). It helps you to heal faster

**Comment by Nitrogen-Dioxide** [comment]
@Orcunegeacar 

Without NCP for sure, with autoheal, it auto trows regen potions (NCP bypassed).
