### ISSUE TITLE
Force OP Screen

### ISSUE THREAD

**Issue by Ambuz** [Wurst-Imperium/Wurst-Client#299]
When i click force OP nothing happens that screen doesn't poppus And nothing happens What Is the problem? Am i making any mistake?

**Comment by Alexander01998** [comment]
What are your system details?

**Comment by mcccs** [comment]
try to disable fullscreen

**Comment by Ambuz** [comment]
Max OSX Yosemite 512 MB VRAM 8 GB RAM Nvidia GeForce320M Intel HD Graphics
Isn't un fullscreen

**Comment by Alexander01998** [comment]
It might be behind the Minecraft window.

**Comment by Ambuz** [comment]
I needed to re install the client And The Launcher and it worked 👌
