### ISSUE TITLE
.invsee showing wrong inventory in creative mode

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#301]
When I tried to do this in Creative Mode it showed my own Inventory. ~~By '1 of an item' I mean that there will be items, but if there were 32 it will only show as 1.~~

**Comment by OMGchangeMYusername** [comment]
@ICouldntUseMyRealNameSoIHaveThis Same Here xD
also,i think it's supposed to only show the item he's holding and his armor no?

**Comment by Nitrogen-Dioxide** [comment]
.... Is it possible to .invsee someone into creative, and middle click (duplicate) his items O.o .

**Comment by Alexander01998** [comment]
> .... Is it possible to .invsee someone into creative, and middle click (duplicate) his items O.o .

No, you are not actually accessing his inventory.

**Comment by OMGchangeMYusername** [comment]
> No, you are not actually accessing his inventory.

well that's a neat idea! i don't say make it possible by middle clicking but what about something that copies everything about the item and make you have an identical one? it may be a command.
