### ISSUE TITLE
New Auto-Build Templates

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#302]
I want some new auto-build templates, here a screenshot with my ideas:
![sem titulo](https://cloud.githubusercontent.com/assets/11248300/6771910/0373b1da-d0cd-11e4-8a7f-9a1e9a735943.png)

LOL just kidding, I made it all. Here the names and amount of blocks (respectively):

Download Link: http://bit.ly/1bmPtsN

Sphere : 32 blocks
3x3Cube : 27 blocks
2x2Cube: 4 blocks
Dot : 6 blocks
3x3wall : 9 blocks
PillarSmall : 3 blocks
PillarHuge : 8 blocks
Cross : 6 blocks

The 3x3Wall is so useful, it bypass NCP easily.

**Comment by OMGchangeMYusername** [comment]
how to use them? i mean how to add them to the autobuild list ingame?
(i'm supposed to know that but i don't remember)

**Comment by Nitrogen-Dioxide** [comment]
Go to your .minecraft folder (You should know that) but now, don't go to versions folder, but to wurst folder, then, go to:
.minecraft/wurst/autobuild , there should be some templates there, download the new templates, and copy it there.
The exact location of this folder:

C:\Users\(YOUR-USER)\AppData\Roaming\.minecraft\wurst\autobuild

**Comment by Nitrogen-Dioxide** [comment]
Tip : Set the PillarHuge in auto build, jump and place a block below you, keep jumping xD, great for skywars lel.

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide didn't know it was that simple :blush: 
oh and Thank You for sharing them :+1:

**Comment by pokeball99** [comment]
i wonder if its possible to make a lavacast with this by delaying the lava placement with water

**Comment by mcccs** [comment]
i hope to see them at https://www.wurst-client.tk/downloads/add-ons/autobuild/ :)
