### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#303]
Pretty simple. I don't care about colors, but here's some anyway:
Player (Non-Friended) - Red (Arrow-Shaped)
Player (Friended) - Blue (Arrow-Shaped)
Player (Yourself) - Orange and/or Light Yellow. (Circle-Shaped)
Mob (Hostile) - Red (Square-Shaped)
Mob (Friendly) - Green (Square-Shaped)
Mob (Neutral) - Yellow (Square-Shaped)
(Again, this is your decision) Mobs are turned off by default.
The command can go in the Render or Misc tab (Or you can just leave it as a hidden mod)

**Comment by mcccs** [comment]
isn't this the same of  #107

**Comment by OMGchangeMYusername** [comment]
it's the same but still,it's possible.
