### ISSUE TITLE
Better Blink

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#307]
You might know this, but the Wolfram 2.0 client recently came out, and I installed it to test if it was better then wurst. It is not except for 1 OP mod. That mod is Blink. I know wurst has this, but the wolfram is different. Here's how it works. I set my keybind for it as Q, So I press Q, I come out of my body while my body stays where I was, then when I press Q again, my body teleports to where I am. It's kind of hard to explain in text, so go try it out. If you got that I'd so happy.

**Comment by Alexander01998** [comment]
Duplicate: #126
