### ISSUE TITLE
Radar and/or Player shower

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#309]
One issue wurst has, is there is no radar or anything like that. It's got the pin to screen button, but there's nothing that I would want to pin to my screen. If you don't know what a player shower is, it just shows exactly what u look like.

**Comment by GlitchHead** [comment]
Tracers

**Comment by OMGchangeMYusername** [comment]
> If you don't know what a player shower is, it just shows exactly what u look like. 

This is what i call,**Completely useless**
