### ISSUE TITLE
I'm sorry but how to get a cloak like a wizard

### ISSUE THREAD

**Issue by TemaHD** [Wurst-Imperium/Wurst-Client#311]
I'm sorry but how to get a cloak like a wizard

**Comment by Alexander01998** [comment]
You missed the opportunity for that.

[![video](https://i.ytimg.com/vi_webp/VNDtXyG2ODw/mqdefault.webp)](https://www.youtube.com/watch?v=VNDtXyG2ODw)

[![video](https://i.ytimg.com/vi_webp/iYx4gJJznBA/mqdefault.webp)](https://www.youtube.com/watch?v=iYx4gJJznBA)
