### ISSUE TITLE
Wall hack

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#312]
I saw some hacked clients have Wallhack like you can shoot threw it. I Think that will be really good for
the hacked client. With the wallhack you will be able to shoot THREW the wall with a bow and arrow. and  troll some people :trollface:

**Comment by Alexander01998** [comment]
As far as I know, entities other than players are entirely controlled by the server.

**Comment by trollmad3** [comment]
Well on the nodus hacked client it has wallhack that you can shoot threw the wall. I think its a good idea

**Comment by OMGchangeMYusername** [comment]
lol, the wallhack shows you where are the entities at,it's logic is the same as xray.
and it doesn't make you able to **shoot through** the walls...

oh and i've seen the **wallhack** naming in other clients and it's exactly the same as xray..
