### ISSUE TITLE
Where...

### ISSUE THREAD

**Issue by homer4me** [Wurst-Imperium/Wurst-Client#314]
Where Exactly do I put the Passwords / Xatos Passwords?

**Comment by Alexander01998** [comment]
There:

![](https://cloud.githubusercontent.com/assets/10100202/6793113/5bf64504-d1c0-11e4-8f32-35e812911943.jpg)

**Comment by homer4me** [comment]
I mean like what file? Serverlist? Or Something else?

**Comment by homer4me** [comment]
Really Where do I Put the files exactly
It would make my day

**Comment by Nitrogen-Dioxide** [comment]
@homer4me https://github.com/Wurst-Imperium/Wurst-Client/wiki/ForceOP-%28a.k.a.-AuthMeCracker%29
