### ISSUE TITLE
Add It So...

### ISSUE THREAD

**Issue by homer4me** [Wurst-Imperium/Wurst-Client#315]
Add It so You can take Stuff out of peoples Inventory with .invsee Please. Regards, Homer4me

**Comment by Nitrogen-Dioxide** [comment]
Impossible.....

**Comment by homer4me** [comment]
Why?

**Comment by homer4me** [comment]
Kinda like the other mod with .rv
And .invsee Combined.

**Comment by homer4me** [comment]
Or Something like that.

**Comment by homer4me** [comment]
Or just make a Dupe.

**Comment by homer4me** [comment]
Oh and 1 more thing any good servers that I can Wreck?

**Comment by Nitrogen-Dioxide** [comment]
It is ipossible because you are not the other player .-. simple.

**Comment by Nitrogen-Dioxide** [comment]
You are only "visualizating" his inventory.

**Comment by homer4me** [comment]
Would there be a way to dupe the item in his/her inv?

**Comment by pokeball99** [comment]
Could be possible with a server with mcmmo,maybe abuse the api of it?
