### ISSUE TITLE
Middle click enhancement

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#318]
Please rename middle click friends to middle click mode
If i click it, a combo box appears.
 - friend add
 - invsee : shows the nearest players inventory
 - run a command
 - don't do anything

This is much better than middle click friend

**Comment by Alexander01998** [comment]
Just make a keybind for the middle mouse button.

**Comment by mcccs** [comment]
i cant add a keybind for middle button! Please try it, its impossible!

**Comment by Nitrogen-Dioxide** [comment]
@mcccs do you know if you write the first letter (or more letters) of other players name and press tab into the chat, it auto complete the nickname? .invsee near is not useful .-. .
