### ISSUE TITLE
How to use Force op

### ISSUE THREAD

**Issue by nidhish2099** [Wurst-Imperium/Wurst-Client#32]
Can someone pls explain what force op is and what servers to use it on i cant find a server to use it on and wurst website isnt helping

**Comment by Alexander01998** [comment]
There is an integrated `How to use` button that answers this question.

Press it.

**Comment by nidhish2099** [comment]
what servers does it work on

**Comment by Alexander01998** [comment]
That is explained in the tutorials.
It even has `This is important! Do not ignore!` attached to it.

**Comment by GlitchHead** [comment]
lol you should just change the ForceOP thing to pass Cracker or Cracker

**Comment by Alexander01998** [comment]
> lol you should just change the ForceOP thing to pass Cracker or Cracker

This sentence doesn't make any sense to me. Please rewrite.
