### ISSUE TITLE
TriggerBot is incompatible with AutoSword

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#320]
triggerbot doesnt work with autosword

~~EDIT: killauralegit doesnt work with autosword too.~~

**Comment by Alexander01998** [comment]
> EDIT: killauralegit doesnt work with autosword too.

KillauraLegit is all about bypassing NoCheat+, so it ignores AutoSword on purpose.

**Comment by pokeball99** [comment]
Needs "work's as intended" label
