### ISSUE TITLE
Disable client

### ISSUE THREAD

**Issue by PyroNinja01** [Wurst-Imperium/Wurst-Client#323]
There should be a option in game to completely disable the client until you restart your game. It could be useful if a admin tells you to screenshot your game or screenshare on skype.

**Comment by OMGchangeMYusername** [comment]
i sugested this several times before **._.** but i was suggesting it by commenting so i guess that's why.
oh and this could be a command :+1:

**Comment by Nitrogen-Dioxide** [comment]
Just closes the wurst, and open a vanilla minecraft '-' '-' '-' .

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide it doesn't close anything it more **switches** to vanilla minecraft in an instant

**Comment by pokeball99** [comment]
The metro client does it,but it leaves the metro message on the debug screan,plus the built in optifine is also left in
