### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by Krowit** [Wurst-Imperium/Wurst-Client#324]
Hey :)
Maby it is possible to add a zoom just like in Optifine?

**Comment by eveythingistaken** [comment]
Why rejected? @Alexander01998

**Comment by OMGchangeMYusername** [comment]
I can't believe you don't understand this despite the fact you opened more than ten issues...
He is free to reject any issue for any reason. It's fine to ask for the reason sometimes,but i think this is self explanatory..

**Comment by Bluscream** [comment]
But im also interested why you dont implement a simple zoom mod with a slider?
