### ISSUE TITLE
Nuker mode "ID"

### ISSUE THREAD

**Issue by iZeqq** [Wurst-Imperium/Wurst-Client#325]
Hey there, can someone help me putting Nuker in ID mode ? It's keep saying me "ERROR something went wrong. If you need help, type ".help nuker". But the normal mode and flat mode work fine !
Even with the ID/name block i want to "nuke", it always says this, so can someone help please?

**Comment by Alexander01998** [comment]
Working fine for me.
`.nuker mode id`

**Comment by iZeqq** [comment]
Thanks for the reply but what do you type when you want nuker in ID mode ?
