### ISSUE TITLE
AntiPotion/FastEat/FastBow/Regen do not work in the air

### ISSUE THREAD

**Issue by xeZx** [Wurst-Imperium/Wurst-Client#326]
If u are in the air (fly) AntiPotion/FastEat/FastBow/Regen do not work.
And AntiFire is for me only the same like "Regen".

**Comment by Alexander01998** [comment]
> If u are in the air (fly) AntiPotion/FastEat/FastBow/Regen do not work.

That is intended. These mods send a lot of packets, so using them while flying (or even jumping) would kick you from the server almost instantly.

> And AntiFire is for me only the same like "Regen".

It's the same method, activated at a different time. Couldn't figure out a better method so far.

**Comment by pokeball99** [comment]
Needs a "works as intended" label
