### ISSUE TITLE
Is it possible to add Wurst into the mods file of Forge and add optifine with it?

### ISSUE THREAD

**Issue by Unitato69** [Wurst-Imperium/Wurst-Client#328]
I've started using Wurst client but it has been kind of laggy, I would like to know if you could add Wurst into a Forge mod file and add Optifine with it as well.

**Comment by pokeball99** [comment]
Part of this is dupe of #2

**Comment by Nitrogen-Dioxide** [comment]
It is not possible to make wurst a forge mod. But add optifine is possible.
#2

**Comment by pokeball99** [comment]
y would it not work for forge?yes he would have to recode it,but other than that,y wouldn't it?
