### ISSUE TITLE
Delay tag for WSpam.

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#330]
Like ----------------------------------------150ms

 1234
<|delay 233|>
 4321

Thats useful when a server have anti spam, I figured out that exact ms numbers, makes the anti spam kicks you.
Or a option to let the ms random, to makes the server thinks that you are really typing it.

**Comment by Alexander01998** [comment]
```HTML
.spammer delay 150<!-- set delay to 150ms
--><repeat 5><!-- spam something -->
Fast spam!</repeat>
.spammer delay 1000<!-- set delay back to 1000ms -->
```

> Or a option to let the ms random, to makes the server thinks that you are really typing it.

```HTML
.spammer delay <random number 4><!-- random 4 digit number -->
(...)
```

**Comment by Nitrogen-Dioxide** [comment]
waa WSpam is so flexible haha.
