### ISSUE TITLE
One click commands

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#333]
I'm donor on a server and I'm allowed to type /enchant. I want to be able to enchant my sword for example with all enchants with one click. I know I can do that with one command, but I want it to run like 10.

**Comment by Alexander01998** [comment]
Take a look at Keybinds and WSPAM.

**Comment by eveythingistaken** [comment]
@Alexander01998 I have looked at keybinds and wspam, but I still don't know how to do it?

**Comment by OMGchangeMYusername** [comment]
if you don't know how to run multiple commands by wspam you should just ask in a new issue maybe?
ps i don't use wspam so currently i know nothing of the syntax and stuff..

**Comment by eveythingistaken** [comment]
I do know how to do that, just don't know how to put it in key bindings.

**Comment by OMGchangeMYusername** [comment]
i'm pretty sure he meant binding your commands..
example,`.say /enchant username sharpness 5` for one key,and then you can set another enchantment for another key.
but idk if you can make it that long O_o

**Comment by OMGchangeMYusername** [comment]
yaay that was right xD
![enchant](https://cloud.githubusercontent.com/assets/10786571/7430976/4d672956-f022-11e4-811b-f473a7f409d8.gif)
i love to play around with the gif thingy :3
thanks @Alexander01998 for sharing it ;)

**Comment by eveythingistaken** [comment]
Ok thanks :)
