### ISSUE TITLE
One click multiple commands

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#334]
I want to be able to press one key and have it run about 7 commands. Is this possible?

**Comment by Nitrogen-Dioxide** [comment]
Thought about the same thing days ago, but i think Alexander will  need to "remanage" the key-binds. One thing that he already did.

With the same keybind for multiple commands, you can make "modules-packets" enabling, no-kb, noslow criticals etc at the same time.

**Comment by pokeball99** [comment]
This a good idea,probably just have a , to seprate

**Comment by Alexander01998** [comment]
Duplicate: #333
