### ISSUE TITLE
Executable download link for v1.10

### ISSUE THREAD

**Issue by mikamika83** [Wurst-Imperium/Wurst-Client#336]
There's no download link for executable (wurst.JAR and wurst.JSON)
there is only source code.

**Comment by pokeball99** [comment]
Confirmed

**Comment by mcccs** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/releases/latest
just click it, download will start instantly

**Comment by GlitchHead** [comment]
and you have wurst 1.10? upload it to google drive and post link

**Comment by Alexander01998** [comment]
Forgot to upload it. Added it now.
