### ISSUE TITLE
Autoreconnect interval

### ISSUE THREAD

**Issue by mikamika83** [Wurst-Imperium/Wurst-Client#337]
Please make a setting to edit autoreconnect interval. It's by default 5 seconds.

**Comment by pokeball99** [comment]
I believe this is to prevent the logged on too fast kick message

**Comment by mikamika83** [comment]
I understand, but in many servers there's no such check for fast logon and this is needed.

**Comment by pokeball99** [comment]
It goes as "contention throtteled,please wait and try again" or something to that effect

**Comment by OMGchangeMYusername** [comment]
lol i have a server that requires you to wait 30 seconds before relogging **.-.**

**Comment by Alexander01998** [comment]
> I understand, but in many servers there's no such check for fast logon and this is needed.

That's why there is a normal `Reconnect` button right above it. That one doesn't have any delay.
