### ISSUE TITLE
Xato's "10k most common.txt".

### ISSUE THREAD

**Issue by GERDominik165** [Wurst-Imperium/Wurst-Client#339]
I can´t Download :Xato's "10k most common.txt". for ForceOp
on this link :https://xato.net/passwords/more-top-worst-passwords

Can any the reports? 
Please i need this to grief server :+1: 

Love Minecraft Hack Wurst <3

**Comment by Alexander01998** [comment]
Like I said in 6f6ca05a4d670a7ae2537ce96e2e22f11da2cc09, you can find that list on Google.

It is, however, in no way required to use that list. Any password list will do, even the default one.
