### ISSUE TITLE
Control mobs (mod)

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#345]
can you make mod make you control the mobs and work with RemoteView but in singleplayer only 
is that Possible :/

**Comment by pokeball99** [comment]
Well in 1.8.3 it is possible,as serge said in his recent twitter

**Comment by osa219** [comment]
Can add it in wurst ?

**Comment by Alexander01998** [comment]
> but in singleplayer only

Wurst is intended for multiplayer.

**Comment by osa219** [comment]
ok not in singleplayer but in vanilla servers , can you ??

**Comment by Alexander01998** [comment]
> ok not in singleplayer but in vanilla servers , can you ??

It's not possible on any servers.
