### ISSUE TITLE
Outdated Java Issue

### ISSUE THREAD

**Issue by SuperJuicy** [Wurst-Imperium/Wurst-Client#347]
I just downloaded the newest version of Wurst and when I try to play it says I need java 8. I am sure I have I have java 8 though. In terminal when I do "java -version" it says "java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)" However it says I am running 1.6.0_65. This only happens in Wurst. Please someone help me on my issue.

Thank you,
SuperJuicy

**Comment by Alexander01998** [comment]
See #142
