### ISSUE TITLE
slow down the updates 

### ISSUE THREAD

**Issue by osa219** [Wurst-Imperium/Wurst-Client#350]
You must to slow down the counter updates and be sure that there are not any mistakes and increase the number of features that add to wurst .

These are just a note :)

**Comment by mcccs** [comment]
Yeah, i have an idea too, only answer threads once a day, and dont update Wurst before you implement all confirmed issues. Then release Wurst 2.0, and wurst users say: "OMG there are too many added hacks. YAY!"
