### ISSUE TITLE
Debugging wurst in eclipse: Question.

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#352]
I understand everything fine, but the only thing I'm not understanding is that part:
> Apply the patch to your decompiled Minecraft source code using Git. The Git command for that is

> git apply --ignore-space-change --ignore-whitespace minecraft.patch

Tried to apply the patch a lot of times, but anything works.

Oh and thanks for posting my auto build templates :D.

**Comment by Alexander01998** [comment]
Make sure you apply the patch with Git. Eclipse's `Apply Patch...` function is broken.

**Comment by Nitrogen-Dioxide** [comment]
You mean the git shell right? When i try to apply at the src of MCP, I get error messages, because the patch of the src is not the same as the .patch file.
Oh, i need to apply it at the bin or the src?

**Comment by Alexander01998** [comment]
> Oh, i need to apply it at the bin or the src?

At the root folder of the Eclipse project.

**Comment by Nitrogen-Dioxide** [comment]
There is no src/net... at my Eclipse project folder.

> error: src/net/minecraft/world/gen/structure/MapGenStructure.java: No such file
> or directory
> C:\Users\aaa\desktop\mcp910\eclipse> error: src/net/minecraft/world/gen/structur
> e/MapGenStructure.java: No such file

**Comment by Alexander01998** [comment]
> C:\Users\aaa\desktop\mcp910\eclipse

This is not the root folder of the project.

It's something like this: `C:\Users\Alexander\workspace\eclipse\Minecraft`

**Comment by Nitrogen-Dioxide** [comment]
C:\Users\aaa\workspace\mcp is the same thing right?
I think that the problem is on that part:
 \mcp\src\minecraft\net\minecraft
See? this folder should be \mcp\src\net\minecrat

Wait.. what version of MCP you are using?

**Comment by Alexander01998** [comment]
> Wait.. what version of MCP you are using?

This is Eclipse, not MCP.

> C:\Users\aaa\workspace\mcp is the same thing right?
> I think that the problem is on that part:
> \mcp\src\minecraft\net\minecraft
> See? this folder should be \mcp\src\net\minecrat

It seems like you don't understand what I am talking about. Like I said in the tutorial, you need to be familiar with both MCP **and Eclipse** in order to understand it. This means being able to use Eclipse without MCP and understanding its project management system.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 Now I resolved a lot of things, I applied the patch successfully, cloned the wurst client, added missing libraries (discovered that lwjgl must be 2.0 not 3.0), and now.. it runs like it was the normal Minecraft, I think it is because this errors...

![aaaaaaa](https://cloud.githubusercontent.com/assets/11248300/6887241/946b59e2-d62f-11e4-8036-31e0ff1ed841.png)
![bbbbbbb](https://cloud.githubusercontent.com/assets/11248300/6887242/946bf140-d62f-11e4-810f-8e2b2db6f397.png)

I solved a lot of errors, but now, I'm stuck here...

**Comment by Alexander01998** [comment]
The error `The field Entity.boundingBox is not visble` shows that you are still using the unmodified vanilla source, because that field is made visible by Wurst since the very beginning.

This means that you didn't apply the patch correctly.

**Comment by Nitrogen-Dioxide** [comment]
arrrggg Thx for the info!

**Comment by Nitrogen-Dioxide** [comment]
Omg... finaly, it worked! , my mistake was applying the patch with **"ignore leading path segments = 0"**
Since it needs to be = 1 to work.

Thanks again for your patience.

**Comment by scriptinator** [comment]
Git didn't work for me, but using Eclipse worked.
