### ISSUE TITLE
Help ChestESP Not working.

### ISSUE THREAD

**Issue by iQuintennn** [Wurst-Imperium/Wurst-Client#353]
Well if i run chest esp. the chest istn surrounded, but in the left corner i can see a little box (That should be the chest esp) please help -Quinten

**Comment by Alexander01998** [comment]
![](https://cloud.githubusercontent.com/assets/10100202/6882432/a09b77a2-d584-11e4-9d71-e1b358d81021.png)

**Comment by iQuintennn** [comment]
But it doesnt work for me :(
