### ISSUE TITLE
Disable Client

### ISSUE THREAD

**Issue by xXRedHackingXx** [Wurst-Imperium/Wurst-Client#357]
A button (in Wurst Option) that can disable the client and makes the client like vanilla until minecraft restart.

**Comment by OMGchangeMYusername** [comment]
Duplicate #323 
Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by GlitchHead** [comment]
lel

**Comment by Alexander01998** [comment]
@OMGchangeMYusername, thanks.
