### ISSUE TITLE
Mass TPA crashes Wurst 1.5.1

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#358]

**Comment by scriptinator** [comment]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I let you down. Sorry :(

Time: 3/29/15 11:07 AM
Description: Updating screen events

java.lang.NoSuchMethodError: java.util.ArrayList.sort(Ljava/util/Comparator;)V
	at tk.wurst_client.module.modules.MassTPA.onEnable(MassTPA.java:46)
	at tk.wurst_client.module.Module.setToggled(Module.java:76)
	at tk.wurst_client.module.Module.toggleModule(Module.java:88)
	at tk.wurst_client.gui.GuiManager$2.onButtonPress(GuiManager.java:159)
	at org.darkstorm.minecraft.gui.component.basic.BasicButton.press(BasicButton.java:42)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.handleComponentInteraction(WurstButtonUI.java:222)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.handleComponentInteraction(WurstButtonUI.java:30)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.handleInteraction(AbstractComponentUI.java:109)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.onMousePress(AbstractComponent.java:43)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.onMousePress(AbstractContainer.java:148)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.mouseClicked(GuiManagerDisplayScreen.java:47)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2007)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1334)
	at net.minecraft.client.Minecraft.run(Minecraft.java:448)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at tk.wurst_client.module.modules.MassTPA.onEnable(MassTPA.java:46)
	at tk.wurst_client.module.Module.setToggled(Module.java:76)
	at tk.wurst_client.module.Module.toggleModule(Module.java:88)
	at tk.wurst_client.gui.GuiManager$2.onButtonPress(GuiManager.java:159)
	at org.darkstorm.minecraft.gui.component.basic.BasicButton.press(BasicButton.java:42)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.handleComponentInteraction(WurstButtonUI.java:222)
	at org.darkstorm.minecraft.gui.theme.wurst.WurstButtonUI.handleComponentInteraction(WurstButtonUI.java:30)
	at org.darkstorm.minecraft.gui.theme.AbstractComponentUI.handleInteraction(AbstractComponentUI.java:109)
	at org.darkstorm.minecraft.gui.component.AbstractComponent.onMousePress(AbstractComponent.java:43)
	at org.darkstorm.minecraft.gui.component.AbstractContainer.onMousePress(AbstractContainer.java:148)
	at org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen.mouseClicked(GuiManagerDisplayScreen.java:47)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:591)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:560)

-- Affected screen --
Details:
	Screen name: org.darkstorm.minecraft.gui.util.GuiManagerDisplayScreen

-- Affected level --
Details:
	Level name: MpServer
	All players: 24 total; [EntityPlayerSP['DataPools'/3411084, l='MpServer', x=0.00, y=73.00, z=-57.72], EntityOtherPlayerMP['Jiffy_'/2906271, l='MpServer', x=-3.34, y=76.00, z=-50.66], EntityOtherPlayerMP['cyclone274'/2586975, l='MpServer', x=-22.84, y=73.16, z=-68.81], EntityOtherPlayerMP['tim_n_steve'/2023864, l='MpServer', x=-12.31, y=73.00, z=-64.41], EntityOtherPlayerMP['J_Marr88'/3116976, l='MpServer', x=-3.63, y=73.00, z=-74.81], EntityOtherPlayerMP['Osiris33'/2921370, l='MpServer', x=5.47, y=73.00, z=-75.84], EntityOtherPlayerMP['Look_At_My_Dirt'/148396, l='MpServer', x=3.34, y=73.00, z=-70.09], EntityOtherPlayerMP['Ceeray'/2558677, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['xFMz'/44249, l='MpServer', x=0.44, y=72.00, z=-65.47], EntityOtherPlayerMP['BirdStuckInCloud'/209642, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['aaronZanderBro'/2554820, l='MpServer', x=1.91, y=73.00, z=-75.19], EntityOtherPlayerMP['George_BOO'/2721529, l='MpServer', x=4.69, y=73.00, z=-75.75], EntityOtherPlayerMP['whitmyster'/916441, l='MpServer', x=4.53, y=73.00, z=-73.38], EntityOtherPlayerMP['Menace_Monsters'/31181, l='MpServer', x=4.78, y=72.75, z=-60.56], EntityOtherPlayerMP['Karpii'/6538, l='MpServer', x=-29.41, y=65.00, z=-44.03], EntityOtherPlayerMP['CodyJackH'/2892360, l='MpServer', x=-25.38, y=73.00, z=-68.53], EntityOtherPlayerMP['arcotre'/918, l='MpServer', x=-1.56, y=73.00, z=-82.59], EntityOtherPlayerMP['Tropicalxshark'/2752012, l='MpServer', x=1.00, y=73.00, z=-82.28], EntityOtherPlayerMP['techmark'/59521, l='MpServer', x=5.47, y=73.00, z=-76.69], EntityOtherPlayerMP['_x5rose_'/110263, l='MpServer', x=1.28, y=70.00, z=-87.19], EntityOtherPlayerMP['masterlol123'/3157946, l='MpServer', x=0.40, y=73.00, z=-81.36], EntityOtherPlayerMP['Dhr_Banana'/2565876, l='MpServer', x=28.55, y=68.58, z=-37.66], EntityOtherPlayerMP['Jimmybest22'/2270765, l='MpServer', x=0.42, y=72.00, z=-65.54], EntityOtherPlayerMP['TizzyFuzzy'/2355530, l='MpServer', x=-33.32, y=65.67, z=-26.58]]
	Chunk stats: MultiplayerChunkCache: 50, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 6650.00,65.00,597.00 - World: (6650,65,597), Chunk: (at 10,4,5 in 415,37; contains blocks 6640,0,592 to 6655,255,607), Region: (12,1; contains chunks 384,32 to 415,63, blocks 6144,0,512 to 6655,255,1023)
	Level time: 99713844 game time, 99743425 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntityOtherPlayerMP['masterlol123'/3157946, l='MpServer', x=0.40, y=73.00, z=-81.36], EntityOtherPlayerMP['J_Marr88'/3116976, l='MpServer', x=-3.63, y=73.00, z=-74.81], EntityOtherPlayerMP['Dhr_Banana'/2565876, l='MpServer', x=28.55, y=68.58, z=-37.66], EntityOtherPlayerMP['Jimmybest22'/2270765, l='MpServer', x=0.42, y=72.00, z=-65.54], EntityOtherPlayerMP['BirdStuckInCloud'/209642, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['tim_n_steve'/2023864, l='MpServer', x=-12.31, y=73.00, z=-64.41], EntityOtherPlayerMP['_x5rose_'/110263, l='MpServer', x=1.28, y=70.00, z=-87.19], EntityOtherPlayerMP['Karpii'/6538, l='MpServer', x=-29.41, y=65.00, z=-44.03], EntityOtherPlayerMP['Tropicalxshark'/2752012, l='MpServer', x=1.00, y=73.00, z=-82.28], EntityOtherPlayerMP['Menace_Monsters'/31181, l='MpServer', x=4.78, y=72.75, z=-60.56], EntityOtherPlayerMP['TizzyFuzzy'/2355530, l='MpServer', x=-33.32, y=65.67, z=-26.58], EntityOtherPlayerMP['arcotre'/918, l='MpServer', x=-1.56, y=73.00, z=-82.59], EntityOtherPlayerMP['masterlol123'/3157946, l='MpServer', x=0.40, y=73.00, z=-81.36], EntityOtherPlayerMP['George_BOO'/2721529, l='MpServer', x=4.69, y=73.00, z=-75.75], EntityOtherPlayerMP['Dhr_Banana'/2565876, l='MpServer', x=28.55, y=68.58, z=-37.66], EntityOtherPlayerMP['Jimmybest22'/2270765, l='MpServer', x=0.42, y=72.00, z=-65.54], EntityOtherPlayerMP['TizzyFuzzy'/2355530, l='MpServer', x=-33.32, y=65.67, z=-26.58], EntityOtherPlayerMP['Look_At_My_Dirt'/148396, l='MpServer', x=3.34, y=73.00, z=-70.09], EntityOtherPlayerMP['Ceeray'/2558677, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['aaronZanderBro'/2554820, l='MpServer', x=1.91, y=73.00, z=-75.19], EntityOtherPlayerMP['whitmyster'/916441, l='MpServer', x=4.53, y=73.00, z=-73.38], EntityOtherPlayerMP['CodyJackH'/2892360, l='MpServer', x=-25.38, y=73.00, z=-68.53], EntityOtherPlayerMP['xFMz'/44249, l='MpServer', x=0.44, y=72.00, z=-65.47], EntityOtherPlayerMP['Jiffy_'/2906271, l='MpServer', x=-3.34, y=76.00, z=-50.66], EntityOtherPlayerMP['techmark'/59521, l='MpServer', x=5.47, y=73.00, z=-76.69], EntityOtherPlayerMP['fluffypinkpug'/3041450, l='MpServer', x=8.72, y=73.00, z=-61.50], EntityPlayerSP['DataPools'/3411084, l='MpServer', x=0.00, y=73.00, z=-57.72], EntityBat['Bat'/2298, l='MpServer', x=3.94, y=74.59, z=-80.28], EntityOtherPlayerMP['Osiris33'/2921370, l='MpServer', x=5.47, y=73.00, z=-75.84], EntityOtherPlayerMP['MinecraftPLAYZ'/2324310, l='MpServer', x=9.25, y=73.00, z=-73.41], EntityOtherPlayerMP['Ceeray'/2558677, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['Osiris33'/2921370, l='MpServer', x=5.47, y=73.00, z=-75.84], EntityOtherPlayerMP['Look_At_My_Dirt'/148396, l='MpServer', x=3.34, y=73.00, z=-70.09], EntityOtherPlayerMP['tim_n_steve'/2023864, l='MpServer', x=-12.31, y=73.00, z=-64.41], EntityOtherPlayerMP['J_Marr88'/3116976, l='MpServer', x=-3.63, y=73.00, z=-74.81], EntityOtherPlayerMP['Jiffy_'/2906271, l='MpServer', x=-3.34, y=76.00, z=-50.66], EntityOtherPlayerMP['cyclone274'/2586975, l='MpServer', x=-22.84, y=73.16, z=-68.81], EntityOtherPlayerMP['cyclone274'/2586975, l='MpServer', x=-22.84, y=73.16, z=-68.81], EntityOtherPlayerMP['Karpii'/6538, l='MpServer', x=-29.41, y=65.00, z=-44.03], EntityOtherPlayerMP['Menace_Monsters'/31181, l='MpServer', x=4.78, y=72.75, z=-60.56], EntityOtherPlayerMP['whitmyster'/916441, l='MpServer', x=4.53, y=73.00, z=-73.38], EntityOtherPlayerMP['George_BOO'/2721529, l='MpServer', x=4.69, y=73.00, z=-75.75], EntityOtherPlayerMP['aaronZanderBro'/2554820, l='MpServer', x=1.91, y=73.00, z=-75.19], EntityOtherPlayerMP['vindell'/2905121, l='MpServer', x=0.19, y=70.75, z=-92.78], EntityOtherPlayerMP['BirdStuckInCloud'/209642, l='MpServer', x=0.41, y=72.00, z=-65.47], EntityOtherPlayerMP['xFMz'/44249, l='MpServer', x=0.44, y=72.00, z=-65.47], EntityOtherPlayerMP['_x5rose_'/110263, l='MpServer', x=1.28, y=70.00, z=-87.19], EntityOtherPlayerMP['techmark'/59521, l='MpServer', x=5.47, y=73.00, z=-76.69], EntityOtherPlayerMP['Tropicalxshark'/2752012, l='MpServer', x=1.00, y=73.00, z=-82.28], EntityOtherPlayerMP['gre258'/301699, l='MpServer', x=-2.03, y=73.00, z=-86.06], EntityOtherPlayerMP['arcotre'/918, l='MpServer', x=-1.56, y=73.00, z=-82.59], EntityOtherPlayerMP['CodyJackH'/2892360, l='MpServer', x=-25.38, y=73.00, z=-68.53]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"f2d17cb":1052) <- PaperSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2988)
	at net.minecraft.client.Minecraft.run(Minecraft.java:470)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.5.1 (latest: 1.10)
	Operating System: Mac OS X (x86_64) version 10.10
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 154639216 bytes (147 MB) / 342454272 bytes (326 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.0.86, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Wurst v1.5.1 is outdated.

Use the [latest version](https://github.com/Wurst-Imperium/Wurst-Client/releases/latest).
