### ISSUE TITLE
AutoCrafter/FastCraft

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#359]
so the name is obvious,but the way it could be implemented could be a button at the top corner of the crafting gui,and have options to chose what to craft and how much,and have some presets,like full tool/armor craft,and "condensing" preset.by that i mean craft all ores into blocks

**Comment by Nitrogen-Dioxide** [comment]
Waa this feature is only for weepcraft Vips. It will be a GREAT implement into wurst.

**Comment by pokeball99** [comment]
so @Alexander01998,is all of that going to be implemented,or just the autocrafting?

**Comment by Alexander01998** [comment]
> so @Alexander01998,is all of that going to be implemented,or just the autocrafting?

I'll try to add [Not Enough Items](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods). If that fails, I'll make my own auto-crafting.

**Comment by CryptikRaven** [comment]
love the idea of not enough items @Alexander01998 :D loved this client since the start and i love seeing it grow i hope you are getting some sort of money for all this hardwork my man

**Comment by pokeball99** [comment]
found the source code of Huzuni,and this looks like a good implementation
https://bitbucket.org/chrixian/huzuni-minecraft-griefing-client/src/bb8a98464fb7640d09d076fedc28da32e6afa34d/minecraft/net/halalaboos/client/mods/modes/AutoCrafting.java?at=master

**Comment by Nitrogen-Dioxide** [comment]
@pokeball99 How did you find the no obfuscated source?!

**Comment by TekkitCommando** [comment]
Is the code outdated?

**Comment by Nitrogen-Dioxide** [comment]
2013-06-16
But it probably works at the same way today.

**Comment by TekkitCommando** [comment]
Your Probly right

**Comment by pokeball99** [comment]
I just googled "hack client" and looked for coding

**Comment by WurstMan** [comment]
dont do nei
do tmi
:dash:

**Comment by WurstMan** [comment]
:+1:
