### ISSUE TITLE
Include Updater source

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#36]
import tk.wurst_client.update.Updater;

What is this class? It doesn't exist.

Maybe try listing your clients dependencies also.

**Comment by Alexander01998** [comment]
The updater is part of a self-made library that is not included in this repo, just like the "encryption" of the AltManager.

I will rewrite the Updater anyways, since the GitHub API makes it much easier to get the latest version of a project.

**Comment by Ericyeah** [comment]
Could you help me clone and run the project in eclipse?

**Comment by Alexander01998** [comment]
That is not yet possible (though it is planned) because a lot of necessary source code is still missing.

It's hard to publish my modified Minecraft source code without publishing any of the original non-open source do-not-distribute source code.

**Comment by Ericyeah** [comment]
I spent ~2 hours with MCP fixing the obfuscated method/field names but than it wouldn't open because a lwjglb error.

If you could help set up my workspace, that'd be awesome, I'd really like to contribute.

**Comment by Alexander01998** [comment]
See above.

**Comment by Ericyeah** [comment]
You helping me privately wouldn't go beyond any dnd code restrictions being I decomped it myself.

**Comment by Alexander01998** [comment]
It wouldn't help me much, either. I would need to do this for everyone who wants to work on the Wurst Client and it would take up all my time. Clearly not what I want. Not the way GitHub's forking system was meant to work either.

Like I said, I will add the modified vanilla source code without adding any of the unmodified source code. All you will need to do then is pressing the `Fork` button.
