### ISSUE TITLE
Wurst says I do not have Java 1.8

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#360]
Wurst gives me an alert to get java 8 even though I have it. I am on a mac. Here is the screenshot of Java version below.
![screen shot 2015-03-29 at 12 32 23 pm](https://cloud.githubusercontent.com/assets/6655672/6887302/b005f902-d60f-11e4-8442-bc0f1a83bfc0.png)

**Comment by Alexander01998** [comment]
You are **not** using Java 8. This isn't the first time Apple has lied to you.

More info & fix in Issue #142.
