### ISSUE TITLE
Alts.wurst import alts

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#361]
Wurst 1.10 import my saved alts form alts.wurst

**Comment by Alexander01998** [comment]
Old `alts.wurst` lists can be converted with the [Alt list converter](https://github.com/Wurst-Imperium/Wurst-file-converter/releases/tag/v1.6.1).

**Comment by pokeball99** [comment]
better title would be "how can i update my altlist"
