### ISSUE TITLE
PlayerESP Enhancement

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#362]
Player esp cant find players in vanish from essentials this is really annoying when your getting stalked by a admin and have no idea. Could there be a possible way for it to find admins of vanished players and when you have player esp on it will show the name of invisible players.

**Comment by pokeball99** [comment]
Isn't there true see?

**Comment by iQuintennn** [comment]
Yes u can make it, in fact i made it in 1.7.10 but it is hard.

**Comment by Alexander01998** [comment]
This isn't possible. Vanish mode works by cancelling all packets that contain the position of the vanished player.
