### ISSUE TITLE
Extend .goto

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#363]
On my factions server I have coordinates to a base, but they are more than 256 blocks away from me. In the next wurst update can there be .goto w/ a range more than 256

**Comment by Alexander01998** [comment]
This is planned for later, but not the next update.

**Comment by pokeball99** [comment]
I don't know java,but it looks like this is what u would want to edit: https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/command/commands/GoTo.java#L33-L38

**Comment by Alexander01998** [comment]
> I don't know java,but it looks like this is what u would want to edit:https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/command/commands/GoTo.java#L33-L38

It's not about removing the limit, it's about removing the reasons why the limit exists.

1. The PathFinder calculates the path as a series of one block movements, so the more blocks you have, the longer it takes to find the path. Especially if you are walking, finding a long path takes quite a bit of time.
2. You might also exceed the chunk loading range, meaning that you no longer know where the blocks are and how to get around them.

This is a common problem in path finding and there are several possible ways to solve it. Many of them are listed and explained on [the website of Stanford University](http://theory.stanford.edu/~amitp/GameProgramming/#pathfinding). They also have a very nice [interactive tutorial](http://www.redblobgames.com/pathfinding/a-star/introduction.html) explaining the basics of path finding.

**Comment by pokeball99** [comment]
ok,upon further research,i found http://qiao.github.io/PathFinding.js/visual/ which although in .js,it seam to have many good path finding algorithm,including the "trace" algorithm with the Heuristic on Euclidean

**Comment by pokeball99** [comment]
and on the second problem,have it get to the closest of the currently available chunks to the goal,and once there, recalculate,and repeat
