### ISSUE TITLE
Move InstantBunker to AutoBuild frame

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#367]
Please remove Instant bunker from modlist and add it to autobuild list.

**Comment by pokeball99** [comment]
i think this is a valid change,do u @Alexander01998 ?

**Comment by Alexander01998** [comment]
Because the mods are sorted alphabetically, InstantBunker would be positioned below AutoBuild, making it look like the AutoBuild mode selector was an InstantBunker mode selector.

![image](https://cloud.githubusercontent.com/assets/10100202/7148127/a04b72f0-e300-11e4-9695-ad0add8cf4a8.png)
