### ISSUE TITLE
team ignoring

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#369]
is there a way to ignore all people you cant attack from kill aura and other bots so you dont need to mark a bunch of people as frend ?
maybe if they have the same armor color or the same suffix or prefix ?

**Comment by GlitchHead** [comment]
or like it will look for in player names you pass a §1Notch it will look for §1 prefix for blue team

**Comment by Le0pold** [comment]
another well idea :3

**Comment by Alexander01998** [comment]
Duplicate: #112
