### ISSUE TITLE
WSPAM writes the wurst commands in chat

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#371]
so everybody can see for example this:
<Le0pold>: .t healthtags on

**Comment by Nitrogen-Dioxide** [comment]
you are writing 
*.t healthtags on*
without the " : " ?

**Comment by Alexander01998** [comment]
In older versions, autorun scripts did this sometimes. It was fixed in v1.10 (in commit f5f95c3f6246ff9ef6ea2a0881a0fe5cc1830ef8).

**Comment by Le0pold** [comment]
ty C: for fixing it
