### ISSUE TITLE
Optifine???

### ISSUE THREAD

**Issue by FrostedGaming** [Wurst-Imperium/Wurst-Client#374]
Can u add Optifine pls? I would like this very much.
Kannst du Optifine hinzufügen? Wäre geil :D

**Comment by osa219** [comment]
Duplicate: #2

**Comment by OMGchangeMYusername** [comment]
:loudspeaker: STOP SUGGESTING OPTIFINE 

this is really getting annoying :anger: you should pin an issue that warns people from suggesting this in the future :+1:

**Comment by Alexander01998** [comment]
> you should pin an issue that warns people from suggesting this

Unfortunately, there is no such feature on GitHub.
