### ISSUE TITLE
Fast version changer

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#377]
hey :sparkles: 
please add an auto version changer
it is basically a button that allows you to choose Wurst 1.7.10 or 1.8 without making another version in versions folder,, i found this on Cyanit client and it is really neat to add to Wurst!
have a look at the top left corner : 
![wurst issue 1](https://cloud.githubusercontent.com/assets/10786571/6925763/68cad918-d7ea-11e4-9e03-5b60ce4260cf.png)
![wurst issue 2](https://cloud.githubusercontent.com/assets/10786571/6925764/694e3cd6-d7ea-11e4-92d6-0a5891aa924e.png)

as you can see that happened with one click :open_mouth:

**Comment by Alexander01998** [comment]
Wurst no longer supports Minecraft 1.7.X (since Wurst v1.4).

I want to make sure we're building the future and not the past.

**Comment by Nitrogen-Dioxide** [comment]
servers with 1.7 that doesn't support 1.8 are so stupid --' .

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide that's why i was hoping to be able to use wurst at 1.7 servers..
i'll try cicada or latemod.
