### ISSUE TITLE
Freecam makes Mobs fall through the map.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#382]
If you enable freecam in single player all mobs around you will just fall through the map into the void and die i have no idea why this happens.

**Comment by OMGchangeMYusername** [comment]
this happens to me with phase but i never tested freecam on Singleplayer

**Comment by Nitrogen-Dioxide** [comment]
This happens because wurst makes a "virtual view" ( I think ) . So you are not enable to see armor in another players too (or change the items in your hand ) .

**Comment by JamesJebson** [comment]
Only happens to me on single player flatland map
