### ISSUE TITLE
fightbot .goto integration

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#383]
Fightbot kills me, (i always fall to abyss) but .goto doesnt. Please integrate .goto to fightbot.

**Comment by pokeball99** [comment]
needs more info

**Comment by Nitrogen-Dioxide** [comment]
What he means is that fight bot doesn't t know that you are going to fall into a hole, but .goto have a better AI, so, integrate .goto to fightbot don't " suicide "

**Comment by pokeball99** [comment]
oh yea,that is related to this https://github.com/Wurst-Imperium/Wurst-Client/issues/135

**Comment by pokeball99** [comment]
i don't think this needed to be closed,as #135 wasn't to specific,this one is clear,what i would do is has the fightbot calculate using the path/GoTo A.I. to the nearest applicable entity.
