### ISSUE TITLE
AutoFarm

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#384]
please import an AutoFarm mod it would be helpfull at factions because you need to sell that stuff to get money

**Comment by pokeball99** [comment]
https://github.com/DarkStorm652/DarkBot/blob/development/src/main/java/org/darkstorm/darkbot/minecraftbot/ai/FarmingTask.java would be a good way to do this

**Comment by 49ers2001** [comment]
Oh I didnt know. I didnt read all the way to that sry

**Comment by pokeball99** [comment]
found this in the src of ONE: https://gist.github.com/pokeball99/6335a4bdf2f74ce17572
here is full source code: http://ssrock101.com/clients/one/

**Comment by TekkitCommando** [comment]
jd gui?

**Comment by pokeball99** [comment]
What do u mean @TekkitCommando?

**Comment by llaurenss** [comment]
:)

**Comment by TekkitCommando** [comment]
I don't know why I put JD GUI might have thought I was on something different lol

**Comment by Alexander01998** [comment]
> I don't know why I put JD GUI might have thought I was on something different lol

Because the gist that @pokeball99 posted had JD-GUI comments in it.

**Comment by OMGchangeMYusername** [comment]
lol i was wondering what was going on with TekkitCommando xDD
(i remember the day this issue was opened)
