### ISSUE TITLE
Disabling

### ISSUE THREAD

**Issue by brld** [Wurst-Imperium/Wurst-Client#386]
There are many times where if you hack, the person you pvped or whatever usually asks you to type .legit or .nohacks or something with a period in front of it.

This is a problem, because you can't type anything with a period in front of it in chat. I suggest a button in Wurst Options that is "disable wurst", which acts as if there is no client installed, and you can safely type .legit or .nohacks :)

Hope this gets added! Wurst is a great client, and this would make it best.

**Comment by Alexander01998** [comment]
Duplicate: #141

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
