### ISSUE TITLE
WSPAM "if"

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#389]
so i coded a script with WSPAM for survival games and it would be cool if you could add "if"
bad example: if derp123 dies then .t panic

**Comment by mcccs** [comment]
Very advanced. and why do you need this?

**Comment by pokeball99** [comment]
This would need a lot of listeners and variables to make this be useful

**Comment by MyzticalTekkno** [comment]
@mcccs its very useful, because you can use it for spammings, spamming commands, and use .give command on the spammer if the command you are typing doesnt fit on the chat bar

**Comment by Le0pold** [comment]
i wasted my time in the last months of creating completely self playing bots using the move to functions and killaura and stuff... so the "if" think would be rly helpfully ;3 well.. just say'n
