### ISSUE TITLE
Remove mod list in ModuleManager

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#39]
Make mods modular in that mods(classes) can be loaded at runtime if placed in a certain folder.

**Comment by Alexander01998** [comment]
How and why?

**Comment by Ericyeah** [comment]
This allows users of Wurst client who're proficient in java, to make their own moduals, and add them, without making updating to a newer version of WurstClient an hinderance.

https://github.com/Snorflake/v2

Here is an example of a client (whom is open source) who does this.

If you'd like I'd be happy to find my sourcecode to the previously private client, Huzuni, who also had the ability to include additional mods by adding a .jar in (example: versions/client/mods) a subfolder, which would then detected @ runtime, and allowed to be used.

**Comment by Alexander01998** [comment]
I'm not planning to do Wurst PlugIns though. :stuck_out_tongue_winking_eye:
