### ISSUE TITLE
You should make a mod that gives you any item in minecraft

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#392]
This would be useful for games like Hypixel UHC and Factions, you could just run a command like .give Playername diamond 64 to be OP in games of survival

**Comment by Edtlogin** [comment]
This would be useful for games like Hypixel UHC and Factions, you could just run a command like .give      Playername diamond 64 to be OP in survival games

**Comment by GlitchHead** [comment]
Sort of duplicate #342

**Comment by Alexander01998** [comment]
In survival mode, this is not possible. In creative mode, this is a duplicate.
