### ISSUE TITLE
Xray render block not enabled in settings

### ISSUE THREAD

**Issue by eioadea** [Wurst-Imperium/Wurst-Client#397]
Xray render blocks such as slabs or leaves when are disabled in settings.

Content of xray.json:
[
  8,
  9,
  82,
  58,
  41,
  173,
  137,
  57,
  42,
  22,
  152,
  133,
  16,
  56,
  15,
  61,
  62,
  51,
  52,
  21,
  47,
  89,
  14,
  48,
  73,
  74,
  120,
  153,
  65,
  129,
  116,
  46,
  50
]

Without xray
![2015-04-02_14 42 40](https://cloud.githubusercontent.com/assets/7475049/6964164/db13d580-d946-11e4-92d1-63c1a3aabb90.png)

With xray
![2015-04-02_14 42 47](https://cloud.githubusercontent.com/assets/7475049/6964176/f52b0b96-d946-11e4-9536-37e3686a702a.png)

**Comment by Alexander01998** [comment]
Duplicate: #211
