### ISSUE TITLE
control while using bird view (freecam)

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#399]
you can control your player while being in freecam mode using right and left click to control him.
means: if i right klick on a block he walk to that. if i left klick the player will attack the entity klicked.

another aditional idea is: if i click on the player a manue would open and i can choose he should sneak walk to... or attack or place block... could be combinated with autobuild :D....

i know its a bit dreamed but the goto featuere could make that possible :)

**Comment by Alexander01998** [comment]
Freecam stops all real movement.

Most of what you "dreamed of" is already implemented or planned for Wurst-Bot.

**Comment by Le0pold** [comment]
i know but its a completly new way of strategically.
