### ISSUE TITLE
AntiAFK

### ISSUE THREAD

**Issue by Krowit** [Wurst-Imperium/Wurst-Client#40]
How about adding something that let you jump every minute to avoid beeing kicked because afk?

**Comment by Alexander01998** [comment]
Even better: A bot that walks around randomly.

**Comment by Krowit** [comment]
the problem is that it could let you walk into death, maby adding both, so you can choose is better

**Comment by Alexander01998** [comment]
> the problem is that it could let you walk into death, maby adding both, so you can choose is better

If zombies can see gaps & lava, then why shouldn't Wurst see it? :stuck_out_tongue_winking_eye:

**Comment by Krowit** [comment]
Okay, thats definetly gonna be cool :+1:
