### ISSUE TITLE
"Bored" Mod

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#400]
Category: Fun

When i click it, enables AntiAFK and shows a PAC-Man game (but the character should be TACO)

This can be an easter egg too!

**Comment by pokeball99** [comment]
haha,i like this,but don't know if @Alexander01998 would want to implement this

**Comment by pokeball99** [comment]
@Alexander01998,what is your thought on this?

**Comment by Alexander01998** [comment]
Could not be an Easter egg because everyone could see it without searching. Making a whole Pac-Man game inside of Minecraft with a taco as Pac-Man probably takes quite long - too long for a feature without practical use.

**Comment by mcccs** [comment]
just copy this to wurst 
https://github.com/dtschust/javapacman/blob/master/Pacman.java
