### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#402]
Time: 02.04.15 23:16
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockState{block=minecraft:double_stone_slab, properties=[seamless, variant]}
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2494)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1354)
	at net.minecraft.client.Minecraft.run(Minecraft.java:468)
	at net.minecraft.client.main.Main.main(Main.java:127)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplemenation.getValue(BlockState.java:150)
	at net.minecraft.world.World.doesBlockHaveSolidTopSurface(World.java:2422)
	at net.minecraft.block.BlockLiquid.randomDisplayTick(BlockLiquid.java:282)
	at net.minecraft.client.multiplayer.WorldClient.doVoidFogParticles(WorldClient.java:318)

-- Affected level --
Details:
	Level name: MpServer
	All players: 5 total; [EntityPlayerSP['Le0pold'/433, l='MpServer', x=-107,60, y=47,00, z=-113,21], EntityOtherPlayerMP['benisme123'/8932, l='MpServer', x=-70,63, y=24,00, z=-88,50], EntityOtherPlayerMP['ToxicTea'/8910, l='MpServer', x=-69,50, y=24,00, z=-88,63], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-68,56, y=27,00, z=-85,72], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-108,49, y=47,00, z=-112,80]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 168,00,50,00,168,00 - World: (168,50,168), Chunk: (at 8,3,8 in 10,10; contains blocks 160,0,160 to 175,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 106922 game time, 106922 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntityOtherPlayerMP['JokeOfDead_'/4060, l='MpServer', x=-109,08, y=48,69, z=-153,94], EntityOtherPlayerMP['nicklas1442'/1649, l='MpServer', x=-144,41, y=54,22, z=-160,59], EntityOtherPlayerMP['fat3_94'/937, l='MpServer', x=-147,21, y=53,93, z=-160,76], EntityOtherPlayerMP['JelleTheFatman'/22449, l='MpServer', x=-147,38, y=54,00, z=-161,73], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-158,35, y=55,00, z=-155,98], EntityOtherPlayerMP['benjamindiaz'/1194, l='MpServer', x=-158,75, y=54,00, z=-156,75], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-163,70, y=59,48, z=-128,67], EntityOtherPlayerMP['benisme123'/8932, l='MpServer', x=-70,63, y=24,00, z=-88,50], EntityOtherPlayerMP['ToxicTea'/8910, l='MpServer', x=-69,50, y=24,00, z=-88,63], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-68,56, y=27,00, z=-85,72], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-108,49, y=47,00, z=-112,80], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-68,56, y=27,00, z=-85,72], EntityOtherPlayerMP['benjamindiaz'/1194, l='MpServer', x=-158,72, y=54,00, z=-156,72], EntityPlayerSP['Le0pold'/433, l='MpServer', x=-107,60, y=47,00, z=-113,21], EntityOtherPlayerMP['JokeOfDead_'/4060, l='MpServer', x=-161,62, y=50,64, z=-86,16], EntityOtherPlayerMP['asierm777'/1759, l='MpServer', x=-155,65, y=54,00, z=-162,34], EntityOtherPlayerMP['brandonriidder'/3816, l='MpServer', x=-117,06, y=50,16, z=-152,54], EntityOtherPlayerMP['benjamindiaz'/1194, l='MpServer', x=-158,72, y=54,00, z=-156,72], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-110,28, y=47,00, z=-110,34], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-116,89, y=48,08, z=-112,46], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-107,41, y=47,00, z=-113,04], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-164,01, y=55,00, z=-159,90], EntityOtherPlayerMP['mlibuPvP'/20418, l='MpServer', x=-164,59, y=49,00, z=-165,81], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-102,01, y=47,55, z=-95,96], EntityOtherPlayerMP['steefje123'/3733, l='MpServer', x=-162,50, y=49,00, z=-165,62], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-156,25, y=53,00, z=-142,88], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-155,72, y=48,00, z=-165,47], EntityOtherPlayerMP['Valadro'/30114, l='MpServer', x=-173,16, y=44,59, z=-116,16], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-152,68, y=55,17, z=-130,52], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-165,19, y=55,50, z=-113,38], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-150,22, y=53,92, z=-161,47], EntityOtherPlayerMP['asierm777'/1759, l='MpServer', x=-142,00, y=53,41, z=-157,84], EntityOtherPlayerMP['steefje123'/30801, l='MpServer', x=-148,31, y=53,00, z=-145,56], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-151,31, y=48,00, z=-165,69], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-149,20, y=47,81, z=-109,45], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-161,31, y=49,00, z=-166,72], EntityOtherPlayerMP['JokeOfDead_'/4060, l='MpServer', x=-157,90, y=48,33, z=-105,28], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-155,14, y=50,15, z=-113,55], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-106,33, y=50,00, z=-108,64], EntityOtherPlayerMP['benjamindiaz'/1194, l='MpServer', x=-158,72, y=54,02, z=-156,72], EntityOtherPlayerMP['Le0pold'/-69, l='MpServer', x=-108,49, y=47,00, z=-112,80], EntityOtherPlayerMP['asierm777'/1759, l='MpServer', x=-163,41, y=48,00, z=-158,35], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-153,47, y=46,00, z=-108,46], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-157,03, y=48,00, z=-104,50], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-153,54, y=46,00, z=-108,31], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-164,75, y=49,00, z=-165,79], EntityOtherPlayerMP['ToxicTea'/8910, l='MpServer', x=-69,50, y=24,00, z=-88,63], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-100,94, y=47,00, z=-108,84], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-154,03, y=49,00, z=-113,38], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-160,12, y=55,06, z=-157,14], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-98,69, y=47,00, z=-91,78], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-99,72, y=47,00, z=-86,34], EntityOtherPlayerMP['benisme123'/8932, l='MpServer', x=-69,34, y=24,00, z=-86,63], EntityOtherPlayerMP['ToxicTea'/8910, l='MpServer', x=-70,13, y=24,00, z=-89,47], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-152,78, y=48,16, z=-107,38], EntityOtherPlayerMP['psychoanimal'/33033, l='MpServer', x=-168,50, y=48,50, z=-103,34], EntityOtherPlayerMP['jadan08'/33034, l='MpServer', x=-168,75, y=48,50, z=-99,00], EntityOtherPlayerMP['fuzzy88'/33038, l='MpServer', x=-165,09, y=48,25, z=-102,50], EntityOtherPlayerMP['benisme123'/8932, l='MpServer', x=-70,63, y=24,00, z=-88,50], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-109,50, y=47,16, z=-69,13], EntityOtherPlayerMP['toddy96'/33041, l='MpServer', x=-165,50, y=47,50, z=-97,53], EntityOtherPlayerMP['brandonriidder'/3816, l='MpServer', x=-161,33, y=54,27, z=-155,00], EntityOtherPlayerMP['brandonriidder'/3816, l='MpServer', x=-163,56, y=54,00, z=-152,47], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-153,29, y=47,66, z=-111,72], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-167,66, y=48,00, z=-100,69], EntityOtherPlayerMP['steefje123'/3733, l='MpServer', x=-148,31, y=53,00, z=-145,53], EntityOtherPlayerMP['mlibuPvP'/20418, l='MpServer', x=-161,66, y=50,12, z=-165,16], EntityOtherPlayerMP['mizukimizuki1104'/99, l='MpServer', x=-116,55, y=48,32, z=-111,95], EntityOtherPlayerMP['thomasnyg'/5037, l='MpServer', x=-165,55, y=48,14, z=-100,04], EntityOtherPlayerMP['S0phini'/1932, l='MpServer', x=-153,31, y=46,00, z=-109,34]]
	Retry entities: 0 total; []
	Server brand: ungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:73d7e0c:unknown) 
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3002)
	at net.minecraft.client.Minecraft.run(Minecraft.java:497)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.10 (latest: 1.10)
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 205767656 bytes (196 MB) / 379568128 bytes (361 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 3800 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository. Especially the part about reporting bugs & pasting crash logs.

Duplicate: #124
