### ISSUE TITLE
Ability to turn off . commands in the options

### ISSUE THREAD

**Issue by vastowen456** [Wurst-Imperium/Wurst-Client#405]
There needs to be an ability to turn these off so that you can 'prove' to people that you arent hacking. People tell you to say .legit to prove you aren't hacking, since . commands are used in hacked clients.
I'm using wurst 1.9, so sorry if this is in 1.10.

**Comment by GlitchHead** [comment]
use command .say

**Comment by Alexander01998** [comment]
Duplicate: #141
