### ISSUE TITLE
Google analytics?

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#406]
I hate it. It tracks internet. WHY DİDU ADD İT.?

**Comment by Alexander01998** [comment]
Because it's awesome.

**Comment by OMGchangeMYusername** [comment]
@mcccs what do you mean by "it tracks internet"?
did you mean its spying or somethin'?

**Comment by GlitchHead** [comment]
WERE BEING STALKED!>!??!

lel.

**Comment by Alexander01998** [comment]
> what do you mean by "it tracks internet"?
> did you mean its spying or somethin'?

See #420
