### ISSUE TITLE
Colored Cracked Alts & Item Drop Creative Spammer

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#41]
It is possible to login to offline servers without authme with a colored name i have tried everything to force a colored name on to the alt list but the WURST format alt file blocks me i even tried .addalt and spammer but spammer would not let me spam § in single player.

Also I have a bit of fun sometimes with .drop on creative servers with a full inventory would it be possible if you could make a mod for creative mode and make the player drop Tons of random items? that would be some intense trolling on servers without /clear In the creative inventory when hovering over a item and pressing 1 or 2 it will make a full stack goto that slot.

**Comment by Alexander01998** [comment]
Only **one** issue per Issue. [Read the guidelines](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md).

**Comment by GlitchHead** [comment]
ok i issue per issue
