### ISSUE TITLE
Wurst-Bot-Lancher: Console Command bug

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#410]
When typing commands and the console gets output from chat or something the command will move up with the text and act weird you can still press enter and it will work but its highly annoying.

**Comment by Alexander01998** [comment]
That's an intended feature of the console.

**Comment by GlitchHead** [comment]
no when you are typing and someone chats in game your text will like move up with the text even when you did not press enter so it is very confusing when typing a message or command.

**Comment by Alexander01998** [comment]
> no when you are typing and someone chats in game your text will like move up with the text even when you did not press enter so it is very confusing when typing a message or command.

Like I said, it's an intended feature of the console.

**Comment by GlitchHead** [comment]
ok... can you add a option to disable the feature?

**Comment by GlitchHead** [comment]
im really confused right now.

**Comment by GlitchHead** [comment]
@Alexander01998 Please watch this video on the bug: https://youtu.be/VB8bAch8TFc?t=53 then you will see what im trying to say.
