### ISSUE TITLE
NoOverlay : WIP  And question :p 

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#412]
I'm making a NoOverlay mod, it disables a bunch of screen overlays. I already removed the fire effect, suffocation effect, a "water overlay" (didn't know that water had one) and pumpkin equipped effect.
![nooverlay](https://cloud.githubusercontent.com/assets/11248300/6985520/b36d8b2e-da0a-11e4-8683-415fc22dd644.png)

But now the problems, I want to when NoOverlay is enabled, it displays a message on screen saying "OMFG FIRE" . Do you have any idea on how to make that?

Annnnd I didn't find how the lava makes a overlay on your screen when you are inside it. It looks like a different type of overlay ( a vignette i think ) . So NoOverlay didn't disable the lava overlay --' .

Another question, is how I send the codes that I change to you see?

**Comment by Orcunegeacar** [comment]
go to  AppData/Roaming/Minecraft/Wurst and send the codes... (all)

**Comment by Orcunegeacar** [comment]
%appdata% to go there (in search button)

**Comment by Nitrogen-Dioxide** [comment]
Nooo, what I am asking is how o send the codes I change to alexander add or review.
I changed the client classes to make this mod, here is an example to remove anitfire fx:

```javascript

 //TODO: Client
            if (this.mc.thePlayer.isBurning() && !Client.wurst.modManager.getModByClass(NoOverlay.class).isEnabled())
            {
                this.renderFireInFirstPerson(p_78447_1_);
            }
```

**Comment by Alexander01998** [comment]
> Another question, is how I send the codes that I change to you see?

You do that using Git and GitHub. Please read the [GitHub Guides](https://guides.github.com/) for instructions.

Guides you need to read:
- [GitHub Workflow](https://guides.github.com/introduction/flow)
- [Contributing to Open Source](https://guides.github.com/activities/contributing-to-open-source)
- [Forking](https://guides.github.com/activities/forking)

I have a few additional notes for you. Please red them *after* you read the guides, otherwise you wont understand it.

- In case the GitHub Guides didn't tell you this, you must create a branch for your edits. Otherwise they can't be merged.
- When writing commit messages, do the following:
  - Use the present tense ("Add feature", not "Added feature")
  - Use the imperative mood ("Move cursor to...", not "Moves cursor to...")

**Comment by Alexander01998** [comment]
Another thing: I just saw in the screenshot that you are still using v1.10. You need to pull in the changes I made since then to make sure your edits can be merged. GitHub recommends to pull in changes as often as possible.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

Thanks, again!

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 How do I create a new branch?

**Comment by Alexander01998** [comment]
> How do I create a new branch?

I guess I forgot to send you a tutorial for that. Here are some:
- [The GitHub Training Playlist on YouTube](https://www.youtube.com/playlist?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-)
- [TryGit - an interactive online tutorial](https://try.github.io/levels/1/challenges/1)
- [training.github.com - plenty of other tutorials](https://training.github.com/)

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 Ok, I'm almost there now, so another question --' 

When you change the Client source, how do you create the patch file? Because almost all the changes I made are in the Client source.

**Comment by Alexander01998** [comment]
> When you change the Client source, how do you create the patch file? Because almost all the changes I made are in the Client source.

```
git checkout master
git checkout -b tmp
git merge --squash Wurst
git commit -a -m "Wurst"
git format-patch master
git checkout Wurst
git branch -D tmp
```

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998  But this code only makes a tmp branch and commits my last changes, my client source cant be detected by git...

**Comment by Alexander01998** [comment]
> @Alexander01998 But this code only makes a tmp branch and commits my last changes, my client source cant be detected by git...

You need to run this in your Minecraft repo, not your Wurst-Client repo. After it's done, you will have a `0001-Wurst.patch` file. That's your `minecraft.patch`.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998  So at the initial time, I should make a Client repository... So now i can't make a patch file because any change i made has been "recorded" ?

**Comment by Alexander01998** [comment]
> @Alexander01998 So at the initial time, I should make a Client repository... So now i can't make a patch file because any change I made has been "recorded" ?

Yes.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 **git format-patch master** doesn't do anything. It doesn't create a patch. :/

**Comment by Alexander01998** [comment]
> git format-patch master doesn't do anything. It doesn't create a patch. :/ and when i create a patch, it creates a empty file...

Oh wait, I remember. `master` was my vanilla MC 1.8 branch and `Wurst` was my modded branch.

**Comment by pokeball99** [comment]
This is done,can we get this closed @Alexander01998?
