### ISSUE TITLE
server crash possibility ?

### ISSUE THREAD

**Issue by Le0pold** [Wurst-Imperium/Wurst-Client#414]
is it possible to change chunk load range to endless ? so the server needs to load a bunch of chunks and laggs

**Comment by pokeball99** [comment]
not possible,servers have a max chunk render,in vannila that is 32 chunks,which can't crash a server

**Comment by Nitrogen-Dioxide** [comment]
If that was possible, any user with optifine and extremely chunk range would crash any server xD .

**Comment by Le0pold** [comment]
oh wait the april jokes are getting boring right ^^ ?

im sry i didnt know...
