### ISSUE TITLE
avoid fall damage in uhc

### ISSUE THREAD

**Issue by Trojmans** [Wurst-Imperium/Wurst-Client#415]
Can you make a feature that does the following things:
    -make every block a litle bit red where you can't fall on without take fall damage
    -make every block a litle bit orange where you can't fall on without take fall damage if you jump before falling.
    -make the blocks where can you can fall without take fall damage or can't on fall normal

like this:
![2015-04-03_20 06 23](https://cloud.githubusercontent.com/assets/11739930/6986396/241cc010-da3d-11e4-80ab-fb72d0290393.png)

**Comment by Nitrogen-Dioxide** [comment]
Ohhhh that will consume a lot of your cpu :/ .

**Comment by GlitchHead** [comment]
there is a no fall mod in the client already ;p

**Comment by mcccs** [comment]
Why rejected but not closed?
