### ISSUE TITLE
Wurst Bot for Mac

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#417]
As I can see wurst-bot depends on windows only files is there any way you could make a future version that is like the wurst installation now. So wurst bot would be installed as a minecraft version like the client

**Comment by Alexander01998** [comment]
> As I can see wurst-bot depends on windows only files

Wurst-Bot itself doesn't require Windows (except for the `debug` command). What requires Windows is the Wurst-Bot launcher.

However, this is only a demo launcher. It is designed to be simple and lightweight, so that others can easily understand how it works and make their own launchers.

> is there any way you could make a future version that is like the wurst installation now. So wurst bot would be installed as a minecraft version like the client

Sounds like a bad idea to me (the Minecraft launcher would add an extra startup delay), but yes, this is possible too. Someone could make a fake Minecraft version that launches Wurst-Bot instead of Minecraft.

**Comment by GlitchHead** [comment]
It will probably be available for mac when the wurst-bot gets implemented in the wurst client its self and you can control it from the client.

**Comment by Alexander01998** [comment]
> It will probably be available for mac when the wurst-bot gets implemented in the wurst client its self and you can control it from the client.

Yes, but there's no need to wait for that.

The Wurst-Bot launcher is only 29 lines of code: The part that actually launches it is one line, the rest auto-installs required libraries and throws user-friendly errors if something goes wrong. So re-creating it in a Mac compatible language is really easy, especially if you skip the fancy auto-installations.

**Comment by scriptinator** [comment]
I get this error running wurst-bot.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3202)
	at net.minecraft.client.main.Main.main(Main.java:54)
	at tk.wurst_client.bot.WurstBot.main(WurstBot.java:27)

**Comment by Alexander01998** [comment]
> so basically from what I understand Wurst-Bot is command line of regular wurst?

Yes.
