### ISSUE TITLE
ChestStealer can't bypass NoCheat+

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#42]
Simply, this kind of CheastStealer dosen't work at all.
You can't steal anything with it.
except for survival..
What i recommend is a ChestStealer that grabs items in order..
it should be like any other mod and can have a keybind.
It grabs items fast and it quickly closes the blank chests.
Finally, I reallly appreciate your hard work and i wish i helped by informing you of this in order to enhance wurst and make it the best client ever.

**Comment by Alexander01998** [comment]
I've tested it several times, it **can** steal & store just about anything and it **does** steal stuff in order.

**Comment by OMGchangeMYusername** [comment]
did you try it on HiveMC,Hypixel,Mineplex?
i tried it on all of them and it really didn't work! 
if the network has something to do with it,i'm not really sure 'cause my net isn't the best these days..
and btw,i gave up on the chests that players spawn near them and tried a chest that had about 5 things and no one opened it except me,and it didn't work!
i click on steal,it steals them for a moment,and then it goes back to the chest!

**Comment by Alexander01998** [comment]
That's NoCheat+. You should've said that in the beginning.

**Comment by OMGchangeMYusername** [comment]
ok then should i like make a video?

**Comment by Alexander01998** [comment]
> ok then should i like make a video?

No, I'll test it.
