### ISSUE TITLE
Keybind for multiple command

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#422]
A keybind that executes multiple command at the same time

**Comment by GlitchHead** [comment]
yea like in the keybind manager /home, /spawn, /f home
you would be able to add a delay to them also /home, /spawn -d 50
-d for a delay this could be used to make a world edit nuker xD
just thought of this while reading.

**Comment by GlitchHead** [comment]
i cant seem to figure out how to do this i try adding 2 commands with the same key and it just replaces the other one.

**Comment by Alexander01998** [comment]
> i cant seem to figure out how to do this i try adding 2 commands with the same key and it just replaces the other one.

1. Create a WSPAM script that runs all your commands,
2. save it
3. and set the keybind to `.spammer spam SCRIPT_NAME`.

**Comment by eveythingistaken** [comment]
How do I save a wspam script??

**Comment by GummiBoat** [comment]
File -> Save Spam to File

**Comment by OMGchangeMYusername** [comment]
I think this is a good idea after all
