### ISSUE TITLE
Suggestion on how in-client bot control would work.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#424]
Suggestion on how the format of commands will be for bots in wurst client.

This is just what i think it should look like for using wurst-bot in the client wurst.

there will be a .bot command it will be used for the bot to do any wurst command after it has logged in ex: .bot follow kllr0928

joining server format: .bot -join -u Notch -p PasswordMuch? -Proxy 127.0.0.1:1234
-j joins a server also -join can be used
join command partermeters:
-u (user or email)
-p (password)
-Proxy (Socks proxy for bot to join)

.bot other commands after bot joins
-d or -debug
-f or -fixme
-l or -leave

The .bot command will automaticly do a wurst command ex .bot follow kllr0928
.bot say hello
.bot -fixme
.bot autorespawn
you get the idea by now...

**Comment by Alexander01998** [comment]
> joining server format: .bot -join -u Notch -p PasswordMuch? -Proxy 127.0.0.1:1234

This is very insecure. As soon as you forget the leading dot, you send your password into the chat.

> -u (user or email)
> -p (password)
> -Proxy (Socks proxy for bot to join)
> -d or -debug
> -f or -fixme
> -l or -leave
> .bot say hello
> .bot -fixme
> .bot autorespawn

I don't want to rename all my commands.

**Comment by GlitchHead** [comment]
"I don't want to rename all my commands." Your already working with in game bot control?

**Comment by Alexander01998** [comment]
> "I don't want to rename all my commands." Your already working with in game bot control?

No, but Wurst-Bot already has commands.

**Comment by GlitchHead** [comment]
see maby you can type perfectly i make so many spelling mistakes and when my command that im entering moves up from chat and like glitches i cant fix my mistake i don't understand whats so bad about fixing it.... i wont mention it anymore.

**Comment by Alexander01998** [comment]
> see maby you can type perfectly i make so many spelling mistakes and when my command that im entering moves up from chat and like glitches i cant fix my mistake i don't understand whats so bad about fixing it.... i wont mention it anymore.

Because it is a built-in, non-removable **feature** (not bug) in perhaps every console out there. In the old days, when most programs used the command-line, this feature was used to make the programs look better. Like this:

![](http://i.stack.imgur.com/1zJFg.png)

Look at the bottom, where it says `KEYWORD values:`. If you would start typing keywords, they would land right next to the `:` instead of appearing on the next line.

**Comment by GlitchHead** [comment]
"non-removable feature (not bug)" Minecraft servers that are Run from cmd or a .bat dont have the text your typing scroll up when a new message appears maby you could use the method that the Minecraft server jar or craftbukkit is using? for wurst-bot just an idea.

**Comment by GlitchHead** [comment]
@Alexander01998 could that be a possible solution to it? ^

**Comment by Alexander01998** [comment]
> @Alexander01998 could that be a possible solution to it? ^

You said you would stop ("i wont mention it anymore."). Now do that.
