### ISSUE TITLE
You should make a mod that doesn't allow you to take damage

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#427]
What I mean is that when you turn on this mod, it will not allow you to take any sort of damage. It could bypass NoCheat+ by giving you the Regeneration 255 effect.

**Comment by Nitrogen-Dioxide** [comment]
I think that is possible only in single-player, or in a shared world. It is not possible on **any** server, because you don't have access to the damage  or potion effects that servers do **server side**.

**Comment by OMGchangeMYusername** [comment]
lol i was just about to say that xD

**Comment by Edtlogin** [comment]
Or you could just make it not able to bypass NoCheat+

**Comment by Nitrogen-Dioxide** [comment]
wait... Regen doesn't disable when you enable yescheat+ ?

**Comment by Edtlogin** [comment]
it does

**Comment by Nitrogen-Dioxide** [comment]
Oh now i understand what you said.
