### ISSUE TITLE
A mod that lets you have any item from a chest by sending a packet

### ISSUE THREAD

**Issue by Edtlogin** [Wurst-Imperium/Wurst-Client#430]
What I mean is that you could create a GUI where you could type items and the amount of them you want. When you hit OK, a packet will be sent "I'm opening a chest with __ in it"

**Comment by Nitrogen-Dioxide** [comment]
But.. what is the *I'm opening a* **Chest** *with __ in it* That you are going to open? this is controlled server side too!!!

**Comment by GlitchHead** [comment]
WHY does it not work like that :c

**Comment by mcccs** [comment]
Edt please type close to close this thread

**Comment by mcccs** [comment]
Close

**Comment by Alexander01998** [comment]
> When you hit OK, a packet will be sent "I'm opening a chest with __ in it"

The server knows what's inside its chests.

**Comment by pokeball99** [comment]
maybe rename to "packet chest dupe"?
