### ISSUE TITLE
Auto-detect NoCheat+

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#431]
command: .analyze 
Example:

Server: BungeeCord {Version} (Wurst gets version with /version command)
With NoCheatPlus (wurst checks /nocheatplus and similar commands)
And Wurst says:
suggested options
  Max killaura Aps 
Max killaura Range
Max Timer

**Comment by mcccs** [comment]
close

**Comment by Nitrogen-Dioxide** [comment]
Some server (almost all) disable the /pl command, so it is hard to find the NCP version.

**Comment by GlitchHead** [comment]
how to find plugins in "most" servers with it blocked type: /? [tab] and keep pressing tab to scan through all the plugins a quick way to find if it has no cheat do /nc[tab] and if "/ncp" appears it has no cheat.

**Comment by Nitrogen-Dioxide** [comment]
@GlitchHead Or just try to fly xD .

**Comment by Alexander01998** [comment]
> And Wurst says:
> suggested options
> Max killaura Aps 
> Max killaura Range
> Max Timer

Instead of suggesting things, I would rather set it all up automatically.

A similar thing is planned for the YesCheat+ mod.

**Comment by PixelMaster3D** [comment]
Can you add an improvement where when you click the YesCheatPlus button it has a setting. For an example:
YesCheatPlus : Auto  (Automatically turns on when plugin is detected)
YesCheatPlus : On    (On)
YesCheatPlus : Off    (Off)
