### ISSUE TITLE
.help

### ISSUE THREAD

**Issue by Blakersmith** [Wurst-Imperium/Wurst-Client#432]
Sometimes people will ask you to type something that requires you to put a period like .help to see if you are hacking or not is there way to type a period without the help command coming up?

**Comment by OMGchangeMYusername** [comment]
`.say .HelpYouNoobsImNotUsingWurst!`
.say is available :smiley: anyway this is a duplicate.

**Comment by Blakersmith** [comment]
Oh thanks I didn't know about that
