### ISSUE TITLE
Minecraft Server Join Crashes the game

### ISSUE THREAD

**Issue by ThaPro** [Wurst-Imperium/Wurst-Client#433]
I Just joined a server and Minecraft Crashed

**Comment by mcccs** [comment]
OS?
Wurst Version?
Server IP?

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
