### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Modifiedshark** [Wurst-Imperium/Wurst-Client#437]
Hey i just wanted to know if you where ever going to put Optifine in any of your clients email me if you will

**Comment by Nitrogen-Dioxide** [comment]
Here is a MASSIVE list of duplicates xD.
#2 #6 #10 #60 #171 #210 #220 #221 #240 #324 #328 #374

**Comment by GlitchHead** [comment]
lel.

**Comment by Alexander01998** [comment]
Here is the full list of duplicates: https://github.com/Wurst-Imperium/Wurst-Client/issues?utf8=%E2%9C%93&q=Optifine+label%3Aduplicate
