### ISSUE TITLE
Name change issue

### ISSUE THREAD

**Issue by ijustneedaname** [Wurst-Imperium/Wurst-Client#44]
Hi there, I recently changed my name on Minecraft, and today I downloaded the updated version of the Wurst client. The client has been saying that I'm using a cracked alt on a premium server, which I'm not doing because I have the paid version of Minecraft, please fix this since its bugging me and it could effect others who've changed their name
![screenshot from 2015-02-21 10 47 32](https://cloud.githubusercontent.com/assets/11096894/6309984/5a1d8a38-b9b7-11e4-80a9-60a3ea38641f.png)

**Comment by Alexander01998** [comment]
You **are** using a cracked alt on a premium server because, by "changing your name" as you call it, you logged in using an account that you don't have the password for (and that might not even exist).

I added this message because so many people were making this mistake.

**Comment by ijustneedaname** [comment]
No, true name changes are possible on minecraft now and I am not using a cracked account

**Comment by ijustneedaname** [comment]
![screenshot from 2015-02-21 11 14 10](https://cloud.githubusercontent.com/assets/11096894/6310350/cf0e177e-b9ba-11e4-889f-8df68377f2ca.png)

I'm able to log into minecraft.net, with my new name so there isn't doubts to the validity of the account

**Comment by ijustneedaname** [comment]
![screenshot from 2015-02-21 11 17 10](https://cloud.githubusercontent.com/assets/11096894/6310389/36be8eda-b9bb-11e4-83bd-ca6d32caba78.png)

**Comment by Alexander01998** [comment]
> No, true name changes are possible on minecraft now

No, they are not. If you saw something on YouTube, that was a virus. Trust me, I know the code.

> and I am not using a cracked account

Like I said, you login with a new account every time you use an alt. So just because you started with a premium alt, that doesn't mean you are still logged in with that premium alt.

**Tip:** Because of this, I highly recommend adding your real account to your alt list. That way, if you log in with a cracked alt, you can switch back to premium with just one click.

**Comment by Alexander01998** [comment]
Ah, that's what you meant.

As Mojang said a thousand times, this **changes the name** of **your account**, but doesn't actually **change your account**.

**Comment by ijustneedaname** [comment]
THANK YOU. Yeah, I haven't changed my name wurst-cracked-alt-wise, but its saying im using a cracked alt.
