### ISSUE TITLE
Optifine for more less lag performance?

### ISSUE THREAD

**Issue by rakazet** [Wurst-Imperium/Wurst-Client#441]
Hi it's rakazet here, im a wurst client user and i really love it! Everything works perfectly especially the killaura which i really like. But there's one problem, lag, lag, lag everywhere. So i went to wizardhax and searched for another hacked client with optifine, i checked my fps with that client and i got 120-200 FPS even with 32 render distance, when i only get max 60 fps but it always drops to 20 when i use wurst (12 render distance). So im suggesting that you may add Optifine to the hacked client and that will help alot of people, thanks!

**Comment by Lucky2307** [comment]
Ikr, i only got 20 FPS, 2 render distance, yep that's right, 2
i tried using other client, i got 40 or more fps
