### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by MeLikeChoco** [Wurst-Imperium/Wurst-Client#442]
This mod/hack (not really hack) was in another hacked client (I believe Huzuni) and it was what drew me into using it. It would basically show you the trajectory of the object (if throwable). When you would pull back a bow, the trajectory would adjust as you pull it showing you just where you needed to pull it to. Every throwable object had a trajectory line available when you held it in your hand (it would show you when you switched to it). At the end of the trajectory line, it would have a box showing (approximately) where the said object would land. It was very accurate and very useful.

**Comment by Alexander01998** [comment]
Duplicate: #168
