### ISSUE TITLE
Eim en idijit 

### ISSUE THREAD

**Issue by gruenwald32** [Wurst-Imperium/Wurst-Client#444]
Ei wont optiefeine pleese mäke it in se neckst abdäte!!!!11!

**Comment by Alexander01998** [comment]
Nöööö!

**Comment by TekkitCommando** [comment]
Something about optifine i think?? I hardly understand what he just said :P lol

**Comment by Alexander01998** [comment]
> Something about optifine i think?? I hardly understand what he just said :P lol

It's a joke, he's from the Wurst-Imperium.
