### ISSUE TITLE
".protect" behavior enhancement

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#445]
When using .protect you will attack anything close to the Entity your protecting but if the Entity that's being protected moves away the bot will not follow the player it will continue attacking the target it found
it would be good to add a feature to it that when the Entity the bot is protecting moves away the bot will follow it so if your on a pvp server and in a no pvp zone the bot will not stay there trying to kill a player and follow you into a pvp zone.

**Comment by Alexander01998** [comment]
> when the Entity the bot is protecting moves away the bot will follow it

If I remember correctly, Protect worked that way in the Closed Beta version where it was added. I quickly realized that changing it to follow the enemy until it's dead made it both more efficient and more realistic.

However, the behavior of the old Protect can be recreated by using Follow and Killaura.

**Comment by TekkitCommando** [comment]
Hmmm I am interested in this client any help needed? Or have you got this covered :P

**Comment by Alexander01998** [comment]
> Hmmm I am interested in this client any help needed? Or have you got this covered :P

Sure, help me out.

**Comment by TekkitCommando** [comment]
Wooot!
