### ISSUE TITLE
make a gitter.im chat room

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#447]

**Comment by Alexander01998** [comment]
Duplicate: #89

**Comment by pokeball99** [comment]
no,its not a dupe,this is different,it just for github,not for the client

**Comment by TekkitCommando** [comment]
Well it's still irc and if there was a chat room within the client it would probably hook to the same irc that he would make for talking outside the client and this probably why he marked it as duplicate

**Comment by TekkitCommando** [comment]
I also recommend adding a description so you can explain your Idea more, "add gitter.im chat room" is not very descriptive and can be taken as a duplicate of other feature requests

**Comment by WurstContributer** [comment]
@pokeball99 Deal with it.

**Comment by Bluscream** [comment]
Since @Alexander01998 denied it for no reason i do see a sense in avoiding spamming ppl's email accounts i made a Wurst-Chat [![Wurst Gitter Live Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Bluscream/Wurst-IRC?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
