### ISSUE TITLE
Horse Stats

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#449]

**Comment by OMGchangeMYusername** [comment]
No description? Really?

**Comment by pokeball99** [comment]
i thought i might be self explanatory,u know like speed,high,and health

**Comment by GlitchHead** [comment]
Its not i have no idea what its suppose to do o_o

**Comment by pokeball99** [comment]
there was a simple mod out there that did this on the horse inventory,it would be used to get the best horse
