### ISSUE TITLE
How do I add the control for the menu?

### ISSUE THREAD

**Issue by Crazy16** [Wurst-Imperium/Wurst-Client#450]
I accidently deleted the control for opening up the Wurst menu (for choosing your hacks) and I don't know the 'command' ?

**Comment by GlitchHead** [comment]
.t clickgui

**Comment by Crazy16** [comment]
Cheers!

**Comment by TekkitCommando** [comment]
Might wanna close your issue than :P

**Comment by mcccs** [comment]
OR
ESC -> Wurst Options -> Alt manager -> clikgui
