### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#451]

**Comment by pokeball99** [comment]
useless

**Comment by mcccs** [comment]
ok

**Comment by pokeball99** [comment]
well,that just my opinion,but if u have a legitimate use for it, @Alexander01998  might put it in

**Comment by TekkitCommando** [comment]
lol what would be the point of breadcrumbs :P

**Comment by TekkitCommando** [comment]
And it might just be me but I think an issue without a description is pointless

**Comment by TekkitCommando** [comment]
Haha

**Comment by Alexander01998** [comment]
People with a bad orientation system can use Breadcrumbs to prevent getting lost.

Although it's not too high on my list, I do plan to add this one day.

**Comment by pokeball99** [comment]
This looks like a good implementation for breadcrumbs mod
www.github.com/ItTotallyHax/src/blob/master/minecraft/net/axiom/modules/AxiomModuleCrumb.java
