### ISSUE TITLE
Optifine?

### ISSUE THREAD

**Issue by TigrexHD** [Wurst-Imperium/Wurst-Client#452]
I think it would be cool if you will add Optifine, because on my computer running minecraft not really good.

**Comment by pokeball99** [comment]
dupe #2

**Comment by TekkitCommando** [comment]
Please read issues that have already been dealt with it makes life easier for you and ppl don't have to mark so many issues as duplicates :P

**Comment by TigrexHD** [comment]
ok sry :(

**Comment by TekkitCommando** [comment]
It is fine @TigrexHD Don't worry about it, its just some advice buddy ;)
