### ISSUE TITLE
Spammer Repeat Enhancement.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#453]
You can make the spammer loop by adding at the end of a spam script ".spammer spam Potato" (as if the script name was Potato) the problem is that there is no way to stop it. 
Could you make it so that there would be this command: .spammer loop potato and if .spammer loop potato was executed again it would stop This could be useful for stuff like world edit nukers.

**Comment by pokeball99** [comment]
they have this already
<repeat>

**Comment by GlitchHead** [comment]
really? what is the command?

**Comment by pokeball99** [comment]
repeat with < and >

**Comment by pokeball99** [comment]
i had it on the other comment but it got hidden,idk why though

**Comment by GlitchHead** [comment]
give me a example like something for me to spam

**Comment by Alexander01998** [comment]
> i had it on the other comment but it got hidden,idk why though
>
> ---
> give me a example like something for me to spam

See #20
