### ISSUE TITLE
Excavator

### ISSUE THREAD

**Issue by Spassvogelw** [Wurst-Imperium/Wurst-Client#456]
This feature would be helpful, if you have to dig deep and big holes for a project, a job whatever. Normally it would be many hours work,  but now you could go away while your player is working. 
One way to implement it would be a new chat command:
You have to write .dig
Then you have to go to one edge of your plot and write   .start
After this you go to the opposite edge and write  .end
Now you write how deep it has to dig. 
The other way to implent it would be coordinates or a few extra options in the auto mine feature. 

![screenshot_2015-04-08-12-44-44](https://cloud.githubusercontent.com/assets/11574076/7044255/b208f9b8-ddf1-11e4-9395-1aca63bcd6fb.png)

**Comment by pokeball99** [comment]
how would this handle water,lava,and say mob spawners?I assume that this would be just like u start it up and just walk off and let it do its work

**Comment by Spassvogelw** [comment]
On possibility would be to use XDA to fill out the holes with stone. You would need only a few minutes for that then the client would make the work for hours. 
Water would not be the problem with good shoes or a anti slowdown feature. Lava is only deep in the ground so ist would be for  long time no problem.

**Comment by pokeball99** [comment]
ok.then what about the chance of it getting stuck in bedrock?would there be a avoiding feature or would u just say stop at where bedrock starts?

**Comment by Spassvogelw** [comment]
Yes just stop where  bedrock starts

**Comment by pokeball99** [comment]
but could we have a blacklist on what blocks not to mine?like mob spawner ect.?

**Comment by pokeball99** [comment]
ps just noticed that the screenshot was in mc:pe XD

**Comment by Spassvogelw** [comment]
Yes in minecraft Pocket Edition exists a bot for digging,  but for normal Minecraft I couldn't find a Feature like this. Crazy because in my opinion would  be this feature really useful. 
BTW I'm on holidays and only have a tablet with me ;)

**Comment by pokeball99** [comment]
spring break?lucky,im at school right now :\

**Comment by Alexander01998** [comment]
> Yes in minecraft Pocket Edition exists a bot for digging, but for normal Minecraft I couldn't find a Feature like this. Crazy because in my opinion would be this feature really useful.

It's also a VIP feature in Weepcraft.
