### ISSUE TITLE
AutoRegister

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#458]
types /register and /login if needed

**Comment by pokeball99** [comment]
for what? need more info label please @Alexander01998

**Comment by Nitrogen-Dioxide** [comment]
@pokeball99 
Weep craft have this feature, it is good because it auto login or register, for me, it is good because my passwords have more than 10 characters xD. It is hard to keep writing it all the time.

**Comment by pokeball99** [comment]
is this for authme servers?or just mojang authaction? or for the wurst bot? if the middle,they cache the info so u don't have to type it in every time on the official mojang launcher

**Comment by TekkitCommando** [comment]
I see where @pokeball99 it coming from :P

**Comment by Meylama** [comment]
A nice way to implement it:

".authme [password]"

then it does

"/register [your password]" or if needed "/register [your password] [repeat your password]"
and also
"/login [your password]"
