### ISSUE TITLE
Movement menu doesn't fit screen

### ISSUE THREAD

**Issue by Victortjeuh** [Wurst-Imperium/Wurst-Client#459]
Hello.

I'll go straight to the point. If I open up my GUI (R. Ctrl) and when I open up the 'Movement' menu, it doesn't fit my screen. Is there any solution to this, besides buying a larger screen ;)?

Thanks in advance!

**Comment by GlitchHead** [comment]
i cant even select the target in the combat menu.

**Comment by Victortjeuh** [comment]
Me neither @GlitchHead

**Comment by Alexander01998** [comment]
Change your GUI Scale to `Large` & maximize the Minecraft window. Works every time, even on 800x600 screens.

**Comment by GlitchHead** [comment]
I cant seem to find the GUI scale option.
