### ISSUE TITLE
Name change issue

### ISSUE THREAD

**Issue by ijustneedaname** [Wurst-Imperium/Wurst-Client#46]
THIS IS NOT INVALID

![screenshot from 2015-02-21 10 47 32](https://cloud.githubusercontent.com/assets/11096894/6310403/678bcb4a-b9bb-11e4-9b10-fd72e9a6d870.png)
i changed my username at mojang legitimately, please stop being a stubborn fucktard and look
![screenshot from 2015-02-21 11 14 10](https://cloud.githubusercontent.com/assets/11096894/6310414/7f99197c-b9bb-11e4-9e44-a0a8952d6d57.png)
im able to log onto minecraft with my new username, and i have not had problems on ANY SERVER before you decided to add the message to wurst.
![screenshot from 2015-02-21 11 17 10](https://cloud.githubusercontent.com/assets/11096894/6310419/94b6505e-b9bb-11e4-8caf-613b6dacdde9.png)
here you go, you're able to change your bloody username legitimately without it being known as a 'cracked account'

**Comment by Alexander01998** [comment]
Read my comment on #44
