### ISSUE TITLE
AFKdetect

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#460]
Detects afk users and highlites them

**Comment by Nitrogen-Dioxide** [comment]
Why?

**Comment by TekkitCommando** [comment]
I feel like this would be something that isn't really a priority nor will it offer an advantage really over people

**Comment by pokeball99** [comment]
yea,because even if u log out.they could just lava your corrds,and then u die when u log back in

**Comment by OMGchangeMYusername** [comment]
it might be useful when playing any sort of PvP things where some people go afk and loosen thier guard ;)

**Comment by OMGchangeMYusername** [comment]
WoW five participants :open_mouth:

**Comment by TekkitCommando** [comment]
I guess that's true @OMGchangeMYusername but that would only be useful I think for kitpvp and some servers afk kick

**Comment by Alexander01998** [comment]
If it works the way I think it works, meaning it waits until a nearby player stops moving for 5 minutes and then marks him as AFK, then it's probably quite useless.

If the player is already nearby and you can't tell for sure that he's AFK, then it's just as accurate to watch him with Freecam or RemoteView for 5 minutes.
