### ISSUE TITLE
AutoDisconnect

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#461]
Quits the server if your get hit by anything.

**Comment by pokeball99** [comment]
this is a reasonable request,but u could just have it to auto disconnect at 19 or something

**Comment by OMGchangeMYusername** [comment]
@mcccs ok stop reading and think of a new feature or something that is **really important** other than auto log in or auto register and such..
it might be a bit beneficial but still there are many more important mods to add.

**Comment by Spassvogelw** [comment]
Yeah a auto disconnect, if you have only two hearts would be helpful.

**Comment by TekkitCommando** [comment]
Unless the server has pvp logger @Spassvogelw lol

**Comment by Nitrogen-Dioxide** [comment]
@TekkitCommando Auto disconect bypass that... You can auto disconnect with nuker ( with YesCheat+ disabled). The server will disconnect you saying " You interacted too fast!! " bypassing combat logger.
You can disconnect with illegal characters in the chat too.

**Comment by pokeball99** [comment]
@Nitrogen-Dioxide,That is Geinus

**Comment by TekkitCommando** [comment]
@Nitrogen-Dioxide I didn't think of that hmmm
