### ISSUE TITLE
add enemies

### ISSUE THREAD

**Issue by TigrexHD** [Wurst-Imperium/Wurst-Client#463]
command: .enemy add [Player Name]
All enemies are dark red in tracer and playeresp
when an enemy is in your near [ radius = 50 blocks ] it is reported in the chat
for example : §4 [Player Name] is in your near. 
only an example you can make it better

**Comment by TekkitCommando** [comment]
§4[Danger] Enemy <player> Nearby haha

**Comment by TigrexHD** [comment]
xD

**Comment by TekkitCommando** [comment]
I understand why this was rejected but it wasnt the worst idea so far :smiley:
