### ISSUE TITLE
Wurst Bot Log-in Bug

### ISSUE THREAD

**Issue by 1337HaxorKiddie** [Wurst-Imperium/Wurst-Client#467]
Mir ist aufgefallen das ich auf vielen CRACKED Servern nicht joinen kann statt dessen wird mir diese Meldung angezeigt:

![bugwurst](https://cloud.githubusercontent.com/assets/11871421/7067337/bceb2700-deca-11e4-8fca-d18bc36af80a.PNG)

Ich denke das dieser Error eigentlich dann auftreten sollte wenn ich mit dem Bot auf einem Premium Server joine. Aber dieser Server ist Cracked.

PS: Ich finde es Geil das du diesen Bot am besten noch mit Spammer und Auto Reconnect. Good Work!

LG Lukas

**Comment by OMGchangeMYusername** [comment]
I thought this repository was only in english?

**Comment by Alexander01998** [comment]
> I thought this repository was only in english?

:us: Yes, it is.

> Ich denke das dieser Error eigentlich dann auftreten sollte wenn ich mit dem Bot auf einem Premium Server joine. Aber dieser Server ist Cracked.

No way. The server has kicked you, Wurst has just changed the message.
