### ISSUE TITLE
Gui .goto meni

### ISSUE THREAD

**Issue by wkuba500** [Wurst-Imperium/Wurst-Client#468]
Please add interactive panel in gui to run commands like ".goto".
In this panel please add places for specify x ,y and z.
Please add option to turn off .goto when it's working

Thank you!

**Comment by wkuba500** [comment]
Alexander01998 why you closed my future? :(

**Comment by OMGchangeMYusername** [comment]
> Alexander01998 why you closed my idea? :(

he didn't like it so he closed it,simple as that.
you might want to review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
