### ISSUE TITLE
Hotkey for steal.

### ISSUE THREAD

**Issue by 1226love** [Wurst-Imperium/Wurst-Client#469]
When you open a chest, there should be a button to press to steal all, instead of having to use your mouse to select it.

**Comment by TekkitCommando** [comment]
lazy mucch? lol

**Comment by 1226love** [comment]
more for the purpose of survival games.

**Comment by TekkitCommando** [comment]
haha i was jk :P

**Comment by Alexander01998** [comment]
There is an AutoSteal mod for that.

**Comment by 1226love** [comment]
My boyfriend brought that to my attention almost immediately after I posted it, hence why I closed it. It's good to know that the owner is so active though!

**Comment by TekkitCommando** [comment]
Yes it is
