### ISSUE TITLE
Wrong message when getting kicked for Nuker

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#47]
If you activate Nuker, and lose connection/get DCed from server because NC+, the disconnect message informs "You're using a cracked MC account on a premium server".

[![YouTube video](https://i.ytimg.com/vi_webp/alsgr6JT3YQ/mqdefault.webp)](https://www.youtube.com/watch?v=alsgr6JT3YQ)

**Comment by Alexander01998** [comment]
Dangit!
