### ISSUE TITLE
Autorun script error when quitting

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#473]
IMPORTANT: I used the client not the Wurst-Bot

I typed .leave in single player and it doesnt move.

I typed .leave in multiplayer and it said:

![](http://i.imgur.com/znfkCwp.png)

And bug reporter didn't open

**Comment by Alexander01998** [comment]
You forgot to say what happened.

**Comment by mcccs** [comment]
sorry i pressed enter, now i am going to edit

**Comment by mcccs** [comment]
fixed in https://github.com/Wurst-Imperium/Wurst-Client/commit/d2f833db29069c6a8e7a73e1f21b7d4f54356bf0
