### ISSUE TITLE
Video BUG (Very IMPORTANT)

### ISSUE THREAD

**Issue by TheHellBoyHB** [Wurst-Imperium/Wurst-Client#478]
https://www.youtube.com/watch?v=JDATysV8RoQ&feature=youtu.be

Here I record myself with the bug (from 7 - 16)
I can play like this

In other version works at 16 and in another Java !!

@#System specification#@

  GPU : Asus Radeon HD 7770 DirectCu
  CPU : AMD FX(tm)-6300 Six-core | 3500 Mhz | 3 Cores
  OS : Windows 8.1 Pro build 10041 (Windows 10 Pro Technical Preview build 10041 | Version : 10.0.10041)
  RAM : 4.00 GB (Game use 1.00 GB)

**Comment by OMGchangeMYusername** [comment]
LOL that's so funny! and sad..

**Comment by Alexander01998** [comment]
> @#System specification#@

That is not a heading. Please review the [Markdown syntax](https://guides.github.com/features/mastering-markdown/).

> and in another Java !!

What other Java?

> (Windows 10 Pro Technical Preview build 10041 | Version : 10.0.10041)

That is most likely the cause of your issue. The Windows 10 pre-releases are non-production-ready.

**Comment by TheHellBoyHB** [comment]
I figure out the problem, the JAVA was the problem 

I remember : In old version was short, normal and far, If I've go JAVA on 32 bit far doesn't work

So the problem was the JAVA on 32

Anyway, Thanks for review

**Comment by Nitrogen-Dioxide** [comment]
Holy ff.... So never use java 32 with far distance.

**Comment by mcccs** [comment]
No it doesnt solve the problem completely. I could use max. 5 chunks in 32 bit. I installed it and now i can use 20 chunks but i cant use 32 chunks now.

**Comment by EnderGamer21** [comment]
so cool it was useful for singleplayer to go to caves or under bed rock
