### ISSUE TITLE
compound repeated message timeout.

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#48]
In the antispam mod, add a timer so the xX label resets itself.

Seeing x11 next to a message gets confusing if teh chats been dead.

**Comment by Alexander01998** [comment]
That feature is awesome! :stuck_out_tongue:

**Comment by Ericyeah** [comment]
Alexander, you misunderstand me. I love the feature, I'm asking you to make the stored data dynamically reset itself.

EG.

12:00am usr 1: give me admin im 11 yrs old rdy to admin this server xD xD im gud admin![x4]

If I keep my client running, and at 12:30am usr1 says the same message, it'll say [x5]. 

I'm saying, for clarity and practicality, the counter should reset if the messages aren't said within the same 2 minute period, which is refreshed each time the message is said?

example

hi 1x 2:00 rmning
1:00 rmning
hi 2x 2:00 rmning

**Comment by Alexander01998** [comment]
It will reset that once 100 chat messages (the client's chat buffer size) have been sent.

I don't want to reset it earlier.

**Comment by Ericyeah** [comment]
You wouldn't consider making this configureable?

**Comment by Alexander01998** [comment]
> You wouldn't consider making this configureable?

Wurst doesn't have it's own buffer for this. The repeat numbers are only stored within the messages themselves (the ` [x15]` at the end).

Because of this, it is very light-weight and doesn't slow down the chat.
