### ISSUE TITLE
Bot Launcher thinks there is no 1.8.jar 

### ISSUE THREAD

**Issue by xXhydraXx** [Wurst-Imperium/Wurst-Client#480]
Bot Launcher thinks there is no 1.8.jar in the wurst-bot_lib file

![image](https://cloud.githubusercontent.com/assets/11883243/7101695/918e1bf4-e0a4-11e4-8af7-cf6661fe9a79.png)

![image](https://cloud.githubusercontent.com/assets/11883243/7101700/ebc1f564-e0a4-11e4-93ab-0c7f5494edd9.png)
this are the screen shots

**Comment by Alexander01998** [comment]
You didn't press any key to continue, at least not in the screenshot.

**Comment by xXhydraXx** [comment]
yea i ll send another if you  want

**Comment by xXhydraXx** [comment]
![image](https://cloud.githubusercontent.com/assets/11883243/7103993/660b6826-e101-11e4-9588-3a43eb7686a9.png)

Before i press a key

![image](https://cloud.githubusercontent.com/assets/11883243/7103994/709f456e-e101-11e4-9262-c6dbd33aa94f.png)

After i press a key

**Comment by Alexander01998** [comment]
Try editing `start.bat` and removing the code that checks for the Jar.

**Comment by xXhydraXx** [comment]
I had to fix my path varible
Because i recently fixed it for my cmd prompt i had to add java to it

**Comment by xXhydraXx** [comment]
Could you lead me to a tutorial on how this was done soz for changing toppic

**Comment by Alexander01998** [comment]
You can find plenty of tutorials for that by searching it on Google: http://lmgtfy.com/?q=add+java+to+path

**Comment by xXhydraXx** [comment]
no, i mean the bot?

**Comment by Alexander01998** [comment]
What exactly do you mean?

**Comment by xXhydraXx** [comment]
can u lead me to a tuturial to coding my one bot?

**Comment by Alexander01998** [comment]
In Java, you can access the Wurst-Bot console using the method described in this [question on StackOverflow](http://stackoverflow.com/questions/24665768/sending-user-input-to-console-in-java). Then you can write to the OutputStream (for sending commands) and read from the InputStream (for analyzing chat messages, errors, etc.).

It should be similar in any other language, as long as you can start a process and access its console.

**Comment by xXhydraXx** [comment]
cool thanks this should be fun =)

**Comment by xXhydraXx** [comment]
can i get the source code plz id like to learn how it works and try to make
my own

**Comment by xXhydraXx** [comment]
dont worry i found it in the wurst source code
