### ISSUE TITLE
AutoWalk not stopping when turned off.

### ISSUE THREAD

**Issue by JamesJebson** [Wurst-Imperium/Wurst-Client#482]
I find that whenever I turn off AutoWalk, it carries on walking. I have to tap W A S D until it stops.
It's been happening since 1.10 I think.

V: 1.12.1

**Comment by pokeball99** [comment]
thats more or less a vannila thing,its does that when u "glitch walk" u have to do what u said to stop that

**Comment by Nitrogen-Dioxide** [comment]
But it only don't disable when you click at the gui, trough keybinds it disables normally.

**Comment by Alexander01998** [comment]
Fixed in v1.14.
