### ISSUE TITLE
a few ideas

### ISSUE THREAD

**Issue by CryptikRaven** [Wurst-Imperium/Wurst-Client#483]
some sort of modloader (for pixelmon and tmi and not enough items etc etc.)

rei's minimap built in and with an on/off button in the gui 

a specific player finder lets say i used a command .findplayer agief233 it would give me a waypoint and how many meters away they are.

and a few other things (i will update this in a few hours once i remember) 

thanks for reading loving each and every update you are doing to this client and it is working great for every player that has used it :D

**Comment by pokeball99** [comment]
2. is confirmed already
3.sounds okay,but @Alexander01998  would have the say on whether to add it

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by alientony** [comment]
See what i think should be maybe a enhancement would be for "The Bots" is I know there just to fill in space but i think that If you gave them a grief and survival setting that would be nice. It was just a little hard to take care of all of them at once on different windows. And Blink is are can u see your self for a reason or is that a bug and i got teleported up a level that i hadn't


 entered ? Oh and The breadcrumb idea was good maybe u can implement a .goto add on so u can use breadcrumbs together to program the bot with No-clip.
