### ISSUE TITLE
Book links that execute commands

### ISSUE THREAD

**Issue by xeZx** [Wurst-Imperium/Wurst-Client#486]
Can you add this Feature to the Client?
https://www.youtube.com/watch?v=xWzi8JPnO5g

**Comment by GlitchHead** [comment]
omg i did not even know this was possible this would take server owner scamming to a whole new level.

**Comment by OMGchangeMYusername** [comment]
ok i have no idea what could this be about.
can you please explain it **in english** to me? @GlitchHead

**Comment by GlitchHead** [comment]
This will allow you with no OP permissions to add text to a book that when clicked it will execute a command, so if a server has PermissionsEX or something else you can make the command /pex user Notch add * and then just give it to a owner or admin and tell them to click it.

**Comment by OMGchangeMYusername** [comment]
Well that should be fairly impossible?

**Comment by GlitchHead** [comment]
did you even watch the video? just translate captions.

**Comment by OMGchangeMYusername** [comment]
that's just an expression :stuck_out_tongue_winking_eye: it's really something tho!

**Comment by Nitrogen-Dioxide** [comment]
Well.. as the client is payed and it is very new... it have a great chance to be a scam haha.

**Comment by Nitrogen-Dioxide** [comment]
Works the same way as here:
https://www.youtube.com/watch?v=r5riz8RKhgc

**Comment by Alexander01998** [comment]
> Works the same way as here:
> https://www.youtube.com/watch?v=r5riz8RKhgc

Thanks! That video contains the code for it:
```
clickEvent:{action:run_command,value:'/do stuff'}
```

**Comment by Nitrogen-Dioxide** [comment]
It is so strange they try to sell it for 10 EU '-' .

**Comment by Edtlogin** [comment]
Great! But the trick is finding a moderator, admin, whatever. If you do, OP is in your hands.

**Comment by Nitrogen-Dioxide** [comment]
@Edtlogin or put /pay ( your name ) (lots of money) and spread the book for op ppl xD.

**Comment by Edtlogin** [comment]
Yeah, but when you get op, you can do that on your own

**Comment by Nitrogen-Dioxide** [comment]
@Edtlogin Never thought that...
