### ISSUE TITLE
.goto <entity>

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#487]
examples:

.getpos <>
.goto <>
.path <>

2nd examples:
.getpos Notch
(gives you Notch's coordinates)
.path Chicken
(gives you nearest chicken's coordinates)
~~Exceptions:
.path Notch true
(true means update its path once a second)
.goto Notch false
(false means dont update)~~

**Comment by Alexander01998** [comment]
> examples:
> 
> .getpos <>
> .goto <>
> .path <>

What is that supposed to do?

> 2nd examples:
> .getpos Notch
> (gives you Notch's coordinates)
> .path Chicken
> (gives you nearest chicken's coordinates)

:white_check_mark: Confirmed.

> Exceptions:
> .path Notch true
> (true means update its path once a second)
> .goto Notch false
> (false means dont update)

Already implemented through *Follow*. Doing that with `.goto` would cause massive lag once the followed entity starts jumping, flying or otherwise becoming unreachable.
