### ISSUE TITLE
FriendTracker [Menu]

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#488]
Add this Friendtracker to main menu.

It says:

YourFriend1 seen at us.mineplex.com at 11'o'clock

**Comment by mcccs** [comment]
yes it is. you didn't understand me.:
YourFriend1 seen BY YOU at us.mineplex.com at 11'o'clock

**Comment by OMGchangeMYusername** [comment]
Ok useless.

**Comment by pokeball99** [comment]
There was a forge mod for 1.2 that did this

**Comment by Alexander01998** [comment]
I agree with @OMGchangeMYusername.
