### ISSUE TITLE
FreeCam crash on crApple

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#49]
[![YouTube video](https://i.ytimg.com/vi_webp/alsgr6JT3YQ/mqdefault.webp)](https://www.youtube.com/watch?v=alsgr6JT3YQ)

Video confirms freecam and nuker issues.

<3

**Comment by Alexander01998** [comment]
Tip: you can embed YouTube videos like this:
```Markdown
[![YouTube video](https://i.ytimg.com/vi_webp/VIDEO_ID/mqdefault.webp)](https://www.youtube.com/watch?v=VIDEO_ID)
```

**Comment by Alexander01998** [comment]
Did you use your hacked version of Wurst? If so, that's clearly the cause. There are countless changes in the vanilla source that help Freecam to work properly.

Also, you should post the crash report for this.

**Comment by Alexander01998** [comment]
>Still needs confirmation on Windows.
