### ISSUE TITLE
Wurst-bot debug bug

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#490]
typed ```debug``` and
![](http://i.imgur.com/8GEMp5k.png)
![](http://i.imgur.com/l7Auyt9.png)

**Comment by Alexander01998** [comment]
Please review the definition of a debug mode:

> A debug menu or debug mode is a user interface implemented in a computer program that allows the user to view and/or manipulate the program's internal state for the purpose of debugging. Debug menus are used during software development for easy testing and are usually made inaccessible or otherwise hidden from the end-user.  
> --[Wikipedia](http://en.wikipedia.org/wiki/Debug_menu)

**Comment by mcccs** [comment]
Yes, i knew. look at the font!
