### ISSUE TITLE
ClickAimbot

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#495]
Hey could you please add Clickaimbot? Lots of servers blocks multiaura and killaura, and not clickaimbot. so that'd be helpful

**Comment by OMGchangeMYusername** [comment]
Oh this one is a good idea! its basically when there's a player in your range you click once it automatically aims for him and then the second blow should hit.

**Comment by Alexander01998** [comment]
Duplicate: #179
