### ISSUE TITLE
Slower Camera Thing Wont Stop When LSD Is Turned Off

### ISSUE THREAD

**Issue by RPNeo** [Wurst-Imperium/Wurst-Client#496]
When you turn on LSD, you will notice that the camera also moves a lot slower than usual and appears to have momentum. However, when LSD is turned off, the slower camera movement will not turn off. Please Fix This.

**Comment by Nitrogen-Dioxide** [comment]
Update wurst client, it is fixed. If you downloaded wurst client from wizard hax, you have a very outdated version :/ .

**Comment by Alexander01998** [comment]
> If you downloaded wurst client from wizard hax, you have a very outdated version :/ .

WiZARDHAX.com always links to the latest version (see [wizardhax.com/wurst](http://wizardhax.com/wurst)).

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 ohhh so now it redirects to wurst.tk . Past days it wasn't like that :p .

**Comment by Alexander01998** [comment]
> @Alexander01998 ohhh so now it redirects to wurst.tk . Past days it wasn't like that :p .

It redirects to wurst-client.tk since wurst-client.tk exists. I believe you have mixed it up with a different website or YouTube channel.
