### ISSUE TITLE
cant see all mods in drop down menu

### ISSUE THREAD

**Issue by coolmanbeast** [Wurst-Imperium/Wurst-Client#5]
when i open some of the drop down menus i cant see all the mods because its a long list

**Comment by coolmanbeast** [comment]
NVM FIXED IT

**Comment by Alexander01998** [comment]
### For everyone who is having the same problem:
1. Set your `GUI Scale` to `large`.
2. Maximize your Minecraft window.
3. Enable `AutoMaximize` in the Wurst Options. (optional)
