### ISSUE TITLE
MultiKill Bug with Regen

### ISSUE THREAD

**Issue by ZeinH** [Wurst-Imperium/Wurst-Client#500]
Lets get a hacked client that has Regen and Killaura for example alright
I turn them on both and they work fine.
I go to WURST , I turn on Multikill
First thing, It doesnt hit multiple players.
When it is hitting players it doesnt do any damage and regen stops working.

**Comment by ZeinH** [comment]
Well fuck this client, Going back to old client then.

**Comment by TekkitCommando** [comment]
Unless you can fix the problem yourself (if there even is an actual problem and your computer isn't just shit) or you intend to restate what the error is please do not make issues where you act like a spaz who doesn't know shit about java

**Comment by TekkitCommando** [comment]
@ZeinH

**Comment by TekkitCommando** [comment]
Sorry @Alexander01998 if that was a little overboard but people like that pisses me off
