### ISSUE TITLE
add a blurb for no solutions issues in readme.md

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#501]
That way someone might be able to come up with a solution 
https://github.com/Wurst-Imperium/Wurst-Client/issues?q=is%3Aissue+is%3Aclosed+label%3A"no+solution"

**Comment by Alexander01998** [comment]
What do you mean? I have that label.

https://github.com/Wurst-Imperium/Wurst-Client/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22no+solution%22

**Comment by pokeball99** [comment]
No like how u have it at the bottom linking to issues with confirmed and enhancements on it,have something there
