### ISSUE TITLE
IRC for Wurst Client (Not a suggest/feature request but a question)

### ISSUE THREAD

**Issue by TekkitCommando** [Wurst-Imperium/Wurst-Client#505]
Not sure if this is even the place to ask this (sorry in advance) I'm on my phone and so needed to write this pretty quickly, ok so I have been coding irc integration for wurst in my free time (don't know if your doing it also) but anyways, I have it now where it opens up its own GUI for you to submit and see the messages and I was just wondering if that was fine for the irc part of Wurst or if your vision was more like it was just another part of the messages box that minecraft already has for server chat and typing commands

**Comment by Alexander01998** [comment]
I would prefer integrating it into the Minecraft chat.
