### ISSUE TITLE
Colored cracked Alts?

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#51]
It is possible to login to offline servers without authme with a colored name i have tried everything to force a colored name on to the alt list but the WURST format alt file blocks me i even tried .addalt and spammer but spammer would not let me spam § in single player.

**Comment by Alexander01998** [comment]
> the WURST format alt file blocks me

That's because the values (name & password) are seperated by a `§`.
I am currently rewriting the alt list format, so that should be possible in Wurst v1.6.

> i even tried .addalt and spammer but spammer would not let me spam § in single player.

That's because writing `§` in the chat on **any** Minecraft server or SP world will kick you instantly.
