### ISSUE TITLE
Just an inspiring issue

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#512]
I decided to share the wurst client on Leak Forums, just read the messages :D .
https://leakforums.org/thread-517690

**Comment by GlitchHead** [comment]
I was banned for spam on leak forums just for commenting on something for download saying "commenting so i can download" .-.

**Comment by Nitrogen-Dioxide** [comment]
http://www.hotspotshield.com/ 
You can bypass the ban with that .-. .

**Comment by GlitchHead** [comment]
Yes but creating a new account is SOOOOOO annoying.
