### ISSUE TITLE
Yescheat+ mode

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#514]
Yescheat+ mode (not mod)
How does this work?
If I click autobuild while holding shift, it paints the autobuild button red and enables autobuild in Yescheat+ mode

or vice versa

if i enable yescheat+ mod (not mode) 
it paints all mod boxes red and if i click autobuild while holding shift it paints it green.

**Comment by pokeball99** [comment]
Yescheat makes hack ncp bypass or DiSable the hacks that can't

**Comment by GlitchHead** [comment]
Well autobuild just does not work on MP in the first place even if the server has no nocheat+ just try it
i need to enable yescheat+ to use autobuild in MP.

**Comment by Nitrogen-Dioxide** [comment]
@mcccs I have a better idea, modes for nocheat+ ( disable or just warn ) . It is duplicate.

**Comment by Alexander01998** [comment]
Duplicate: #243
