### ISSUE TITLE
How to define many hacks just on one Key ? (Keybind Menu)

### ISSUE THREAD

**Issue by ComYse** [Wurst-Imperium/Wurst-Client#515]
I don't know how to set many hacks just on one key ... please help

**Comment by GlitchHead** [comment]
Steps:
1: Open spammer enter all the commands you would like a key bind to execute
2: save it as anything
3: on the key bind menu make the key bind that will execute those commands do .spammer spam <file>
the file will be the saved WSPAM script you created

**Comment by Alexander01998** [comment]
Duplicate: #422
