### ISSUE TITLE
AutoFish

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#517]
issue: AutoFish isn't avo enough, needs more graphics, like when you catch a fish, it should phase to a graphic that says fish caught much like in GTA when you die it says wasted.

**Comment by Nitrogen-Dioxide** [comment]
If Minecraft.getminecraft().Gui.DrawCenteredString was easy to do :/ .

**Comment by Ericyeah** [comment]
Actually, this would be ridiculously cool, if you want to autofish on an MCMMO server, it'd be swag to have a text log of all the items you catch.

**Comment by pokeball99** [comment]
@Ericyeah,if u want to code,your welcome to,then see if Alexander would want to put it with the client or not

**Comment by Ericyeah** [comment]
@pokeball99 Learn to type properly.

**Comment by pokeball99** [comment]
@Ericyeah yea it's because my pc broke the other day and I'm typing on my phone
