### ISSUE TITLE
Infinite item dropper in CreativeMode

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#52]
>Low quality Issue fixed by an Admin. Please write a better Issue next time!

A enhancement i have is creative drop spammer.

I got the idea from sometimes with the  `.drop` command creative servers with a full inventory and throwing items at people (**lots** of items).

Would it be possible if you could make a mod for creative mode and make the player drop *tons* of random items? That would be some intense trolling on servers without `/clear`...

In the creative inventory when hovering over a item and pressing 1 or 2 it will make a full stack goto that slot.

**Comment by pokeball99** [comment]
Infintie should be spelled Infinite

**Comment by GlitchHead** [comment]
lel

**Comment by Orcunegeacar** [comment]
It'll be awesome for lagging. :D

**Comment by GlitchHead** [comment]
cant wait for dis

**Comment by GlitchHead** [comment]
YES

**Comment by GlitchHead** [comment]
could you make this rapid fire? its seems a bit slow.

**Comment by Alexander01998** [comment]
> could you make this rapid fire or add a delay option? its seems a bit slow.

Nope. I even tried dropping 1024 items per tick - same slow speed.

**Comment by GlitchHead** [comment]
k
