### ISSUE TITLE
.autobuild reload

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#520]
reloads autobuilds, gui.json etc.

**Comment by pokeball99** [comment]
What's the point of that?

**Comment by Alexander01998** [comment]
> What's the point of that?

When designing AutoBuild templates, you need to reload them often.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 When i was making the auto-build templates I noticed that, but forget to talk about it. xD
