### ISSUE TITLE
Deleteing server list

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#523]
Sometimes i click on Refresh or add a server then all of my servers get removed and this happens sometimes this is my second time it happened please fix

**Comment by Alexander01998** [comment]
Check the `Game output` tab in your Minecraft launcher. There will likely be a stack trace containing the necessary information to find the cause of this bug.

**Comment by pokeball99** [comment]
@trollmad3 @Alexander01998,this happens with vanilla minecraft,there really nothing u can do,mojang would have to find out what happens.

**Comment by OMGchangeMYusername** [comment]
I haven't heard of it up until you opened this issue,it never happened to me.
perhaps it's a problem in your PC or anythin'?

**Comment by GlitchHead** [comment]
This happens to me it randomly renames servers.dat to servers_tmp.dat

**Comment by Alexander01998** [comment]
Considering that I haven't written anything about renaming the `servers.dat` file, I will assume that @pokeball99 is right about this being a vanilla bug.
