### ISSUE TITLE
Wurst-Bot multiple accounts

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#526]
if i join a server on a alt then login a second account and join again the first alt stays in the server but the new alt that i joined as can do commands the first alt that was on is completely useless as you cant command it but the new one is. maby you should make it that all commands goto all accounts on the server.

**Comment by Alexander01998** [comment]
That is not supposed to work. One instance of Wurst-Bot can only use one alt at a time.

Starting multiple instances of Wurst-Bot and distributing commands to all of them is something for a Wurst-Bot launcher.
