### ISSUE TITLE
Block party Hack

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#528]
Hi alex :rocket: 

I'm suggesting a block party hack which has a bot walking to the correct colour.
E.G: Stand on purple colour (it would say it in the chat) the bot would recognise it and run to the closest and correct colour BTW. It may be a good idea to use Cyanit's code to do this as this is what I would like, just in Wurst!

-Lol

**Comment by OMGchangeMYusername** [comment]
i feel like these special gamemode hacks should be added when Wurst is fully packed with everything that has been suggested,After that i think @Alexander01998 would agree on adding them just to make Wurst more swaggy :sparkles: :sparkles: :sparkles:

**Comment by pokeball99** [comment]
yea,if u want to,go on hack forums or such,and find cicada,its for 1.7,but if u want to update it yourself @Loltage23 to 1.8,be my guest,it has plenty of minigame hacks,with some custom anticheat bypasses on the bigger servers,again might need to update

**Comment by OMGchangeMYusername** [comment]
Oh Cicada is my favorite 1.7 client ever!
didn't know people are still using it xD anyway it has been cracked by H&E and it's awesome as always!
ok can you tell me what minigame hacks it has?i for sure remember VampireZ and QuakeCraft.
What i really love is CapsarSpeed and triggerbot ixaura **ah it's so beautiful**.
oh by the way is it possible to update cicada to 1.8??
and i feel like we're talking in the wrong place xD 
ok sorry i'll stop after @pokeball99 answers me :pray:

**Comment by pokeball99** [comment]
I don't use it,but I saw a review for it the other day for a cracked version,saw there was quite a lot of stuff,the guy did not go into much detail of it,I just saw the gui
