### ISSUE TITLE
Server Crasher

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#529]
It can be amazing if Wurst has this mod. When you write .crash than it'll send empty folders when you are playing in a server. The Server can crash. But Minecraft can crash too. But I think it will not work in strong servers. (Code: ping (ip) -t )  :smile:

**Comment by Orcunegeacar** [comment]
ForceOp can't work everytime. But it'll work

**Comment by Orcunegeacar** [comment]
Of course on weak servers

**Comment by Alexander01998** [comment]
Can't do that, DDoS attacks are illegal.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998  What's the DDoS?

**Comment by pokeball99** [comment]
crashing the server would be a ddos,although there are is a hack out there that can crash a vanilla server.i forget what client @OMGchangeMYusername

**Comment by mcccs** [comment]
This isn't DDoS it is DoS. DDoS needs multiple computers.

But it is not legal too.

**Comment by GlitchHead** [comment]
DoS is a single computer

**Comment by Orcunegeacar** [comment]
If DoS or DDoS are illegal. Are minecraft hacks legal?

**Comment by Orcunegeacar** [comment]
"HACK" is illegal too :smile:

**Comment by Alexander01998** [comment]
> If DoS or DDoS are illegal. Are minecraft hacks legal?

Those have nothing to do with each other.

> "HACK" is illegal too

Cheating in a game is not considered hacking in the law.

**Comment by TekkitCommando** [comment]
It's called a Hacked client because it was the name people liked

**Comment by OMGchangeMYusername** [comment]
Hacking in minecraft is just beneficial,it's not really considered as **Hack**

**Comment by pokeball99** [comment]
http://blog.ammaraskar.com/minecraft-vulnerability-advisory/ found out about this 10 min ago

**Comment by Alexander01998** [comment]
> http://blog.ammaraskar.com/minecraft-vulnerability-advisory/ found out about this 10 min ago

Yesterday it was released, the night between yesterday and today I worked on including it in Wurst and today it was [patched by Mojang](https://mojang.com/2015/04/minecraft-1-8-4-security-release/). Damn, that was quick.

**Comment by pokeball99** [comment]
well,still add it,it might be able to do it on some of the servers that don't update

**Comment by Alexander01998** [comment]
> well,still add it,it might be able to do it on some of the servers that don't update

Couldn't get it to work yet, but I'll upload the branch.
