### ISSUE TITLE
Treatise to Incredible Idiocy

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#531]
*Think before you react. If you disagree strongly, consider giving it a few minutes before responding.

Alright, this rule shouldn't be necessary, this rule seems to be written from a context of infallibility, like you guys think that any position WurstTeam makes is inarguable, and any contentions one might have will surely be resolved by taking a deep breath, and this is simply untrue, immature, and completely opposite of the community github, and all open-source is supposed to be. If you want to think you're perfect, that's fine, there is no point in having an open source if you're going to ignore valid suggestions because of the tone/language they're written in.

*Ask questions, don't make demands. ("What do you think about trying...?" rather than "Don’t do...!!!")

If someone makes a demand that you patch a bug/add a feature which affects all users/would benefit all users, are you really that petty and immature that you're going to disregard/take negatively something which would benefit your users who you don't patronize by your ridiculous standards? I completely see you getting mad if someone made an issue saying "This client sucks, make it better." because that's not a constructive comment at all, but if someone says "This client sucks, there're a bunch of bugs, here's a list of them." you're nothing but an ungrateful jerk who needs to take their head out of their ass, if you think your contention with the rudeness the user supplied changes the fact that the user gave you solid points to improve on, maybe it warrants not replying, maybe it warrants an apology, an assurance that contributors will be alerted of the bugs, but it's just hypocritical, unproductive, and crude to reply defensively to something which if fluffed up to your standards with emoji and nice people words, you'd reply to with action; it's selfish to the users who may also be experiencing the issues/wanting feature X who may not be aware of github's issue system.

*Don't insult. Avoid using terms that could be seen as referring to personal traits. ("dumb", "stupid"). Assume everyone is attractive, intelligent, and well-meaning.

Who wrote this? I got criticized immaturely for having a mac by @Alexander01998 Maybe you guys do think you're infallible, epitome of foolishness.

Regardless, grow up, if people are going to be idiots and call people names, delete the comments/report them, if said comments come along with actual helpful input, than there is no reason to take the comments personally/to offense, just be thankful you have a potential point of improvement for your loyal users, regardless of the fact it came from the mouth of someone who decided to be a dick.

*Be explicit. Remember people don't always understand your intentions online.

This is a very reasonable and fair guideline, but again, if someone is unclear, don't reply defensively like I've seen you do, reply like you want the user clarify, being you could very possibly gain knowledge of a bug which is affecting users your seeming sense of infallibility doesn't offend.

*Don't use hyperbole. ("always", "never", "endlessly", "nothing")

You're governing things which make me think you care more about control than you do the client you've programmed. If people want to use hyperbole, that should be fine, as long as they manage to appropriately explain the issue that's happening.

*Use emoji to clarify tone. (":sparkles::sparkles: Looks good :+1: :sparkles::sparkles:" rather than "Looks good.") 

If there was a book called "Rules to impose on your user-base, if you want nobody to take you seriously!" this would definitely be a top card on the list.

Thanks. 
I just want you to know that I care about all projects (open-source) and I hate to see project managers act in such a way which deter people from contributing, leveraging it's not worth the fight.

**Comment by OMGchangeMYusername** [comment]
@Ericyeah does that mean it's ok to say "this client sucks balls it's the worst because it has so many bugs and its killaura is hellla bad,here's a list of bugs" just because you included bug reports that doesn't mean it's ok to insult the hell out of this client..

**Comment by Ericyeah** [comment]
@OMGchangeMYusername If you actually read my post, you'd have gathered I agree partially with your above statement. If people insult your project, but include a bug report, you simply leverage that they're a useful asshole. Sure, they insulted you, but they also gave you an opportunity to make other users' experiences better; it's simply reprehensible to act aggressively defensively, you may as well say that you don't care about UIx. 

Here's an appropriate, productive, and supremely efficient template/basis for how a reply to a message such as "
 "we're trying hard, lots of people love our client, thanks for giving us the opportunity to work on making their experience better; feel free to try the client again once we fix the issue, maybe you'll reconsider your contentions towards it. Thanks again for submitting this issue, instead of just bashing the project mentally, hopefully that means that despite your negative thoughts on the project, you still trust our ability to make it more awesome, or in regards to your opinion, less shitty."

bang bang.

**Comment by gruenwald32** [comment]
Sou hellou mei frent ei wont to tolk ebout somesing with ju.
first of oll ei wont to sey yu set ju meybi dount nouw set yur masser iss eh beaver end jur sissta iss in reallity yur brosser
