### ISSUE TITLE
can i get Xato's "10k most common.txt" please

### ISSUE THREAD

**Issue by arnont33** [Wurst-Imperium/Wurst-Client#537]
i looking to the force op and found Xato's "10k most common.txt" in the information
im try to force op server,but i cant i need this list to try force op,/w default list have 50 password
when i click Xato's "10k most common.txt" i cant download it can u give me this list pls.

**Comment by Alexander01998** [comment]
Xato's website no longer exists, but you can still find plenty of good password lists on Google.

**Comment by pokeball99** [comment]
isn't this a dupe of something?

**Comment by OMGchangeMYusername** [comment]
@pokeball99 lol it's already closed.

**Comment by Nitrogen-Dioxide** [comment]
@arnont33 

https://www.dropbox.com/s/fkbw7rhjdc32ftg/10k%20Most%20Common%20Passwords%20%28Big%29.txt?dl=0

**Comment by BlinkHacker** [comment]
it can be also found at archive.com http://1024kb.co.nz/worlds-10k-most-popular-passwords-download/

**Comment by arnont33** [comment]
Thanks :D
