### ISSUE TITLE
Quake Aimbot 

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#539]
Please add quake aimbot  Alex 
What is quake aimbot?: A bot that finds a player and shoots them via right click

**Comment by OMGchangeMYusername** [comment]
@failvenom and @paris-ci this is a DUPLICATE #55 
you **have to** read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by OMGchangeMYusername** [comment]
lol so you're failvenom? xD
I think you should be pretty much used to Github,why do you duplicate things at some points?..
 
(boored.. a lot of net issues happening to me so i can't play and stuff..)
And sorry Alexander,i won't comment like this next time :rabbit:
