### ISSUE TITLE
BlockParty

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#542]
So this is another big suggestion made by me. Most of it is just a collaboration of some mods already in the wurst client, but there's also something else I want to put.

Added .search functionality:
If there is 10 or less than the block you searched, it will show tracers to the blocks. The reason I put only 10 is because if you put tracers to all blocks, you'd crash (no duhh). But that's it for the new .search.

The mods in BlockParty:
Tracers to the color of clay (nearest clay of that particular color, and optionally tracers to beacons)
Levitate/Phase (Optional, since you can get easily caught with it).

Other:

BlockParty will fall under the category "Misc"

Wurst is my all-time favorite hacked client. Why else would you think I'd create a suggestion for this client? I haven't for any others. In fact, the only reason I have this account is just to make some pretty nice suggestions for Wurst.

**Comment by OMGchangeMYusername** [comment]
@ICouldntUseMyRealNameSoIHaveThis ok i'd love to see BlockParty mod in wurst but i'm afraid that this would be labeled as **invalid**. 
did you read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository (issue section)?
oh and also,i'm the first one to make an account and sub to this repository :blush:

**Comment by Alexander01998** [comment]
Duplicate: #528
