### ISSUE TITLE
KeyBinds

### ISSUE THREAD

**Issue by ADudeLikeMe** [Wurst-Imperium/Wurst-Client#545]
I accidentally deleted the keybind for opening the mods tab! How do i bring it back someone please help!

**Comment by nellthan22** [comment]
OH GOD THANK YOU

**Comment by ADudeLikeMe** [comment]
Ya Thank you so much!!!!

**Comment by ADudeLikeMe** [comment]
And do i just put that in the keybinds?

**Comment by ADudeLikeMe** [comment]
Will it work?

**Comment by OMGchangeMYusername** [comment]
I'm pretty sure that binding `.t clickgui` to any key would work,Haven't tried it tho.

**Comment by nellthan22** [comment]
Yes, it works on any key.
