### ISSUE TITLE
Tracers Back on Chests with ChestFinder

### ISSUE THREAD

**Issue by VenomAbuse** [Wurst-Imperium/Wurst-Client#549]
Tracers on the chests were really nice! Then you don't have to turn around or look up or down! The tracers will just show you where the chests are at. This is so much easier and I hope you add this back to the client! Thank You

**Comment by pokeball99** [comment]
This is neat,I see nothing wrong with adding this

**Comment by pokeball99** [comment]
Y was this tejected,it's not useless

**Comment by Alexander01998** [comment]
Because it would look very messy once you have a lot of chests.

**Comment by OMGchangeMYusername** [comment]
Exactly! i wonder what some client makers think when they stick the tracers to ChestESP even if you don't want tracers...
