### ISSUE TITLE
QuakeAura

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#55]
please add a quake aura

**Comment by Alexander01998** [comment]
What is that?

**Comment by wtfbomb153** [comment]
90% sure he's talking about the gamemode Quake on Hypixel

**Comment by OMGchangeMYusername** [comment]
well it's basically locks your aiming on the players and gibs them.
it's like the aimbot but with much longer distance and it sort of locks the view on the player and gibs him,when it gib someone it aims for the other closest player and continues on the same pattern!
oh and also,there are a lot of servers that has this game!

**Comment by Alexander01998** [comment]
Nah, doesn't sound useful.

**Comment by OMGchangeMYusername** [comment]
xD
thanks anyway :grinning:
