### ISSUE TITLE
PropHunt Suggestions

### ISSUE THREAD

**Issue by TabooBaboo** [Wurst-Imperium/Wurst-Client#551]
I would suggest that killaura and fighbot worked for PropHunt blocks cause I have no mouse. I would also suggest that PropHuntESP shows on mobs because on Minelplex you can also be mobs,

**Comment by Alexander01998** [comment]
> I would suggest that killaura and fighbot worked for PropHunt blocks cause I have no mouse.

Minecraft requires a mouse. You couldn't even join a server without one.

> I would also suggest that PropHuntESP shows on mobs because on Minelplex you can also be mobs,

Mobs cannot be detected. See #81.
