### ISSUE TITLE
a moment of silence for the creator of darkbot

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#553]
I know this is somewhat unrelated,but I thought some people here should know this,since many hack clients use his work in their clients
https://github.com/DarkStorm652/DarkBot/issues/47
( @Alexander01998,leave this up a day before closing it,just so people can pay ommiage)

**Comment by Unihedro** [comment]
They will be forever missed. I don't even know them, but they were I good person. I think.

**Comment by Alexander01998** [comment]
> I don't like saying this but I'm the brother of the maintainer of this Git. He died as of a week ago when he contracted pneumonia, if any of you want to take over, drop me a message and I will pass along his private details, including the files he was working on before the illness hit.

If he died a week ago, then why did I see him on the HackForums just 3 days ago? :smile:

Here is his post: http://www.hackforums.net/showthread.php?tid=4781359&page=7#post_45734523
And here is his profile: http://www.hackforums.net/member.php?action=profile&uid=1323113

**Comment by Nitrogen-Dioxide** [comment]
LOL just LOL. Is he a ghost? xD.
