### ISSUE TITLE
Chat Translator

### ISSUE THREAD

**Issue by thewurstguy** [Wurst-Imperium/Wurst-Client#558]
A chat translator to translate to different languages or dialects.

**Comment by Nitrogen-Dioxide** [comment]
aww maii god this is so useful and so hard to make D: :rage:

**Comment by pokeball99** [comment]
Does Google translate have an api?

**Comment by thewurstguy** [comment]
Yes, but you must pay for it :/

**Comment by mcccs** [comment]
no, free: https://code.google.com/p/google-api-translate-java/downloads/list

**Comment by thewurstguy** [comment]
can this be done pokeball?

**Comment by OMGchangeMYusername** [comment]
@thewurstguy alexander has put the "confirmed" label on it,that means it's possible.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
We're definitely going to need a gangsta translator.

**Comment by pokeball99** [comment]
https://mega.nz/#F!1tJAxbSS!6g-AKjU5mTPrqJ9fd3OTSg
some files i got from the Serenity Client,this should get this to work
although i think 
```
    Translate.setClientId("sCheese-MCClient");
    Translate.setClientSecret("4UaoXOyXaPaogjj3L0VBglXny+BxQpXYsq1DMYBtSuU=");
    setDisplayInModuleList(false);
  }
```
should be changed,but then again,i think u could keep it
