### ISSUE TITLE
Wurst Cape?

### ISSUE THREAD

**Issue by capsload** [Wurst-Imperium/Wurst-Client#56]
Hello,

just like optifine or  huzuni, you could add CAPE Support for other optifine/wurst users, the user should be able to use his custom cape.

I could give you the website hosting if you need :3

So anything like http://url/wurstcape/Usercape.png <- only for donators ;P

**Comment by OMGchangeMYusername** [comment]
That would be helpful for mr.Alexander!
but i can't really donate coz i don't even have a credit card or a visa
but i'm trying my best to reprt bugs or suggest mods :grinning:

**Comment by Alexander01998** [comment]
> but i can't really donate coz i don't even have a credit card or a visa

I can't take donations either - same reason.

I do like the idea of Wurst capes, though. I'll talk to Billy about that.

**Comment by capsload** [comment]
Whos Billy? :p
Yeah, i'd love to use Custom Capes. Hopefully you have a good implement thing soon!
And as i said, i could help you with the hosting.
Greetings.

**Comment by Alexander01998** [comment]
> Whos Billy? :p

[Billy Billy Bob](http://www.wizardhax.com/the-crew/#g1-frame-7)

**Comment by capsload** [comment]
Oh, okay :) Really would like to see this happen in the next update!
<3 Cape

**Comment by Alexander01998** [comment]
Billy didn't reply, but I figured it out myself.

**Comment by MorganPlaysMC** [comment]
Wurst cape sounds really cool

**Comment by OMGchangeMYusername** [comment]
the problem is, if a mod or an admin used wurst and started banning whoever has the cape xD
please if you are going to add wurst capes make an option to disable them :worried:

**Comment by Alexander01998** [comment]
> the problem is, if a mod or an admin used wurst and started banning whoever has the cape xD
> please if you are going to add wurst capes make an option to disable them

At least for now, Wurst capes are for Wurst-Imperium members and friends only. There are three reasons for this:
1. There is a list of all players who have a Wurst cape. Admins could use this as a list of players to ban.
2. A lot of people would use the cape and the list would become very long. So it would take very long for the client to load the list and slow everyone down.
3. Hosting a long list that updates frequently is very difficult.

**Comment by capsload** [comment]
I could help you with hosting the capes. :) It would be great to choose your own cape. (You can use a Mojang Cape or Minecon Cape that way, Admins will not see that.)

**Comment by Alexander01998** [comment]
> I could help you with hosting the capes. :)

Hosting a list of several thousand names that changes hundreds of times per day and gets tens of thousands of requests per day (estimated values based on the Wurst website statistics) is one problem. The other problem is preventing server admins from using this list as a list of hackers to ban.

> It would be great to choose your own cape.

That is already possible. GitHub's servers make it really easy to host gigabytes of images at a very fast speed. Uploading these images directly from the client might be a problem, but compared to the other problems, I wouldn't worry too much about this one.

> (You can use a Mojang Cape or Minecon Cape that way, Admins will not see that.)

They can't see it in Minecraft, but they could still look up the player's name in the list. Admins of big servers like Mineplex would certainly do this once they hear about it. Or worse, automatically look up & ban everyone on the list with a Bukkit plugin.

> And, how to be a Wurst-Imperium Member?

The Wurst-Imperium consists of only three people: A close friend, my brother and myself. I will never allow anyone who I don't know personally to become a Wurst-Imperium member.

Becoming a friend of the Wurst-Imperium is a little easier, but still pretty hard. Friends are people who have helped the Wurst-Imperium or have worked together with us, people like WiZARDHAX or the Reflex team.

**Comment by capsload** [comment]
Okay, sounds bad for the end-users :3
didnt i suggested that feature? ;P hehe.

ok, how did huzuni managed that system? they check if the username was premium through a website, then bam, cape shown.

Maybe you build in the Client something like;

http//url/check_imperium.php?=%username%

while %username% is the Minecraft IGN.

That way, Mineplex cant "sniff" the userlist. Because the Client checks that everytime the WurstClient gets startet.

**Comment by Alexander01998** [comment]
> Maybe you build in the Client something like;
> http//url/check_imperium.php?=%username%
> while %username% is the Minecraft IGN.
> That way, Mineplex cant "sniff" the userlist. Because the Client checks that everytime the WurstClient gets startet.

It wouldn't make much of a difference. They could still make a plugin that checks every player who joins the server.

> ok, how did huzuni managed that system? they check if the username was premium through a website, then bam, cape shown.

The difference is that Huzuni is closed source. They can just hide the URL of their `capes.json` or their `hascape.php`.

**Comment by capsload** [comment]
:-(
