### ISSUE TITLE
HackBook

### ISSUE THREAD

**Issue by DerekHale** [Wurst-Imperium/Wurst-Client#563]
How to make this HackBook in 1.8 ?
Help me Please in skype
Add me User 
BananaGam1ng

**Comment by Alexander01998** [comment]
> How to make this HackBook in 1.8 ?

Take a look at the [v1.13 changelog](https://github.com/Wurst-Imperium/Wurst-Client/releases/tag/v1.13).

> Help me Please in skype
> Add me User 
> BananaGam1ng

![](https://cloud.githubusercontent.com/assets/10100202/7230874/d1815afe-e771-11e4-91a6-a4dcbdb0cdae.png)
