### ISSUE TITLE
Extended Target Player Specifier

### ISSUE THREAD

**Issue by Updates4dayz** [Wurst-Imperium/Wurst-Client#567]
In the bottom of the combat list, where there is the target specifier there should be an add-on to the player section where you can select multiple color name tags to target players with color name tags, which is good for 4 team mini-games, for example, when hovering over the player button in the target section it shows the colors you can attack (clicking the button will select that color). This extension will optimize kill aura for games that involve more than 2 teams.

**Comment by Updates4dayz** [comment]
Btw I messed up on the title it should have been "Target Selection By Color Nametag"

**Comment by Alexander01998** [comment]
Duplicate: #112
