### ISSUE TITLE
Any ESP causing hotbar to glitch with colors

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#568]
The cheat item esp, player esp, mob esp, tracers and the others cause the hotbar to change colors when looking in different directions along with the player hand please fix this

**Comment by Alexander01998** [comment]
Although I personally use these mods very often, I have never experienced any of the problems you described.
Please provide more information about your problem. Our [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) may help you with that.

**Comment by Whatisthisname** [comment]
Here I have some screenshots if this is what is meant
![2015-05-29_18 34 08](https://cloud.githubusercontent.com/assets/12211068/7887510/e832e19e-0631-11e5-8c83-577a2cde591a.png)

**Comment by Whatisthisname** [comment]
![2015-05-29_18 27 55](https://cloud.githubusercontent.com/assets/12211068/7887528/0560c25e-0632-11e5-9e3c-9370c2a31da4.png)

**Comment by Whatisthisname** [comment]
Thats what I got

**Comment by Whatisthisname** [comment]
(Look at my arm, it isnt normally green)

**Comment by Alexander01998** [comment]
Your arm's color will always change when you are above Y127. It's a vanilla bug.
