### ISSUE TITLE
Brute force option for ForceOP!

### ISSUE THREAD

**Issue by ShteinCoder** [Wurst-Imperium/Wurst-Client#569]
Sorry that this isn't in pull requests, it wouldn't work for some reason (or I'm just a noob at using GitHub). My idea is that you could add a brute force option for the ForceOP. What I mean by this is that it generates random passwords using random numbers and letters. For example, on 3 digit padlocks you are able to cycle through the numbers to eventually open the lock because there are a limited amount of combinations. 
001
002
003.. 
and so on. Obviously it would be more than just incrementing a number because passwords contain letters also. I think this feature is necessary because I've tried TXT lists with ForceOP too and so far I've had no success. However, if this feature is implemented, the power of a semi-decent CPU can crack any password under 6 characters in a matter of 10 minutes or so. It would be even better if you could do the calculations with the GPU. The only problem left here is the timeout disconnect from AuthMe. Maybe add an accomplice feature to instant-relog? Thanks a lot for creating this client! Love it!

**Comment by Alexander01998** [comment]
Since AuthMe has a limit of one attempt per second, brute-forcing a 6 character password world take about 2179 years...
