### ISSUE TITLE
Won't save alts

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#570]
Whenever I add alts to Wurst, close it, and open it again, the alts are gone. I'm on a mac with the latest version of wurst.

**Comment by Alexander01998** [comment]
Delete your alt list (`%appdata%\.minecraft\wurst\alts.json`), your AES key (`%appdata%\.minecraft\wurst\key`) and your RSA keypair (`C:\Users\You\.ssh\wurst_rsa` & `...\wurst_rsa.pub`).

**Comment by eveythingistaken** [comment]
I'm on mac and I can't find the other 2 files.

**Comment by eveythingistaken** [comment]
@paris-ci You just copied what he said. I can find alt list, and aes key and nothing else. there is no .ssh file anywhere.

**Comment by GlitchHead** [comment]
eveythingistaken please when you launch wurst have the launcher stay open and tell us if you get any errors while launching

**Comment by eveythingistaken** [comment]
@paris-ci Works! Thank you so much
