### ISSUE TITLE
Built-in AltChecker

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#574]
Add Built-in AltChecker + Proxy support 

How it would work :
1.Add proxies if wanted 
2.Press "Check alts" Button
DONE
Tip : It will do nothing if there are no alts to check

**Comment by pokeball99** [comment]
@paris-ci proxys....

**Comment by Pokemonplatin** [comment]
proxys are hard to made.

**Comment by pokeball99** [comment]
no,he can just add support for proxies,there are 1000's if not millions of proxies for public use that we can just copy and paste in

**Comment by failvenom** [comment]
Umm i can just provide a list a list of fresh proxies weekly

**Comment by Pokemonplatin** [comment]
the problem is not the proxy list the problem is the iplementaiton

**Comment by Alexander01998** [comment]
With the new improvements to Mojang's authentication servers, alt checkers no longer work.
