### ISSUE TITLE
Telnet Spam

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#576]
I recently went on a server where someone totally spammed chat through a telnet client and the admins couldn't ban him, so I think it would be cool if there could make a wurst mod to spam chat through telnet

**Comment by pokeball99** [comment]
Telnet?

**Comment by Nitrogen-Dioxide** [comment]
@pokeball99 

" *Telnet is an application protocol used on the Internet or local area networks to provide a bidirectional interactive text-oriented communication facility using a virtual terminal connection. User data is interspersed in-band with Telnet control information in an 8-bit byte oriented data connection over the Transmission Control Protocol (TCP).* "

**Comment by pokeball99** [comment]
So like irc?

**Comment by Alexander01998** [comment]
Minecraft uses Netty, which, as far as I know, has nothing to do with Telnet.
