### ISSUE TITLE
Add Projectiles Please...

### ISSUE THREAD

**Issue by HeyShell** [Wurst-Imperium/Wurst-Client#577]
Add a "Projectiles" mod... this show where falls every item what is throwable (sorry for my english, im not british/american) but... dont remove the "BowAimbot" mod...

**Comment by scriptinator** [comment]
Projectile Prediction makes him sick and is very hard to do.

**Comment by mcccs** [comment]
https://github.com/Wurst-Imperium/Wurst-Client/tree/trajectories He already made it, but not added

**Comment by Alexander01998** [comment]
Duplicate: #168
