### ISSUE TITLE
Regen hack not working!

### ISSUE THREAD

**Issue by Enderspider87** [Wurst-Imperium/Wurst-Client#58]
Hello! So I love the Wurst hacked client but I think the "Regen" hack has a glitch whenever I play on the Mineplex server.  So what happens is that my hunger bar goes to and from 95% and 85% repeatedly whenever I get hit. This causes me to not regenerate any health whatsoever. At first, I thought that this was due to NoCheat+. But when I went into singleplayer and tested it, the same thing happened. After that, I was certain that this was caused by a bug or glitch. This glitch has allowed many people to kill me in PvP many times and it frustrates me.
![2015-02-21_18 00 55_2](https://cloud.githubusercontent.com/assets/11141415/6317055/deb6f77e-b9f4-11e4-9648-60fc42740bf5.png)
![2015-02-21_18 00 55](https://cloud.githubusercontent.com/assets/11141415/6317058/e35697a8-b9f4-11e4-86cb-143673b3e792.png)
 These two photos were taken within 90 milliseconds of each other and you can see that I don't regen health.  I would love to see this fixed in the near future. Thank you for reading this report and please tell me if you have the same problem!

**Comment by GlitchHead** [comment]
you need full food bar for regen to work it will take your hunger bar away fast so this mod is good for servers like mineplex that make you always have a full hunger bar.

**Comment by Enderspider87** [comment]
Oh yeah I for got to mention that during the PvP, my hunger bar did start out as full. But it never came back to full.

**Comment by Alexander01998** [comment]
> Oh yeah I for got to mention that during the PvP, my hunger bar did start out as full. But it never came back to full.

Hunger bars aren't supposed to go backwards.

**Comment by Enderspider87** [comment]
Then that could be a glitch

**Comment by Alexander01998** [comment]
> But it never came back to full.
> Then that could be a glitch

It **shouldn't** go backwards and, as you said, it **didn't** go backwards either.

So that's working fine.
