### ISSUE TITLE
projectiles

### ISSUE THREAD

**Issue by roomster2000** [Wurst-Imperium/Wurst-Client#580]
i would like if there was projectiles in this hack

**Comment by GummiBoat** [comment]
How exactly do you mean that? A Line that shows how projectiles fly, or what?

**Comment by roomster2000** [comment]
like with a bow, to see where your arrow is going too

**Comment by pokeball99** [comment]
being implemented,still W.I.P. https://github.com/Wurst-Imperium/Wurst-Client/tree/trajectories is the branch,u can help finish it if u can code

**Comment by Alexander01998** [comment]
Duplicate: #168
