### ISSUE TITLE
ColorShuffle mode request 

### ISSUE THREAD

**Issue by webboytm** [Wurst-Imperium/Wurst-Client#583]
Not sure how many servers this is on, but the minigame ColorShuffle is where you hotbar is filled with a random color of wool and you have to go stand on that color of wool carpet. If you arn't standing on that color by the time the timer runs out, you fall. What I would like to see in a future update in the Wurst client is a mode that automatically moves out character to the correct color carpet. I'm not sure if this is possible though since it may send to many packages. However if this is possible, I would really enjoy it.

**Comment by pokeball99** [comment]
maybe generalizing for .goto <block>,whats your take @Alexander01998?

**Comment by GummiBoat** [comment]
Same as #528 .

**Comment by pokeball99** [comment]
well,yes it is,but in the sense,we can just solve this by implementing .goto (block),making this be solved,plus being open for other things to be used

**Comment by GummiBoat** [comment]
yeah, the .goto <block> idea is really cool, maybe you should open a request for that, problem with this and the request is, you would have to type everytime you would get a new color .goto <blockid:damage>, which makes it very unefficient. so i'll stay with a no for the request, but a yes for your idea.

**Comment by Alexander01998** [comment]
Duplicate: #528
