### ISSUE TITLE
BookHack not working.

### ISSUE THREAD

**Issue by ShteinCoder** [Wurst-Imperium/Wurst-Client#584]
Hi! Sorry if I missed something but... BookHack will not work on any servers I join. I have tried both 1.8 and 1.7 servers and neither work. However it does work on Singleplayer. Thanks!

EDIT: Just tried on my own vanilla server and it worked there.... odd. maybe only vanilla?

**Comment by pokeball99** [comment]
vanilla will,for the most part always work,but i believe they patched bookhack in modded servers like bukkit/spigot

**Comment by Alexander01998** [comment]
See #541 and the [BookHack page](https://github.com/Wurst-Imperium/Wurst-Client/wiki/BookHack) on the wiki.

> vanilla will,for the most part always work,but i believe they patched bookhack in modded servers like bukkit/spigot

Spigot is very slowly working on a fix, but they are no where near to it. All others don't even care.
