### ISSUE TITLE
Item / Enchant Hack

### ISSUE THREAD

**Issue by KingIngot** [Wurst-Imperium/Wurst-Client#585]
I think that you will be able to do this, but I am not sure. Could you add something to hack an item or hack an enchant onto an item? Sorry if you're getting spammed with these types of messages, I'm just a little curious.

**Comment by Nitrogen-Dioxide** [comment]
.enchant?

**Comment by KingIngot** [comment]
I wasn't familiar with the .enchant command. Would .give work as well?

**Comment by GummiBoat** [comment]
as far as i know, giving items only works if you have OP or Gamemode. But then it makes it useless, because you can give it to yourself anyways.

**Comment by Nitrogen-Dioxide** [comment]
In creative, you can pick any item with.
C10PacketCreativeInventoryAction(-1, new ItemStack(item, 64)

You can have dragon eggs with .drop infinite command for example.
