### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by MeLikeChoco** [Wurst-Imperium/Wurst-Client#586]
They are more like minor adjustments really. 

One of them is when you (well, for now it's I because it might just be my problem) get disconnected (not by my own will, as in disconnected in any other way except hitting the quit button in the ESC menu) and you have 3 options, Reconnect/Return to Title Screen/Auto Reconnect. Well, the problem is that those 3 options are all mashed together and it's hard to click Return to Title Screen. It's just Reconnect and AutoReconnect really close together and a tiny slit for the option Return to Title Screen (you cant even see the words, just a slit of the box). 

Another problem is when you hit Refresh, sometimes it doesn't refresh. The servers just keep pinging. Sometimes it works and sometimes it doesn't.

**Comment by GummiBoat** [comment]
I'm not having the problems with the buttons, did you try out resizing your GUI/or changing your texture pack?

I'm experiencing the problem with the servers too, but not only on wurst-version. just try to join them anyways.

**Comment by Alexander01998** [comment]
1. Maximize the Minecraft window.
2. That's a vanilla bug.
