### ISSUE TITLE
Book command

### ISSUE THREAD

**Issue by stiff4321** [Wurst-Imperium/Wurst-Client#587]
How do you use the book command im having trouble on a server trying to get op

**Comment by GummiBoat** [comment]
Step 1: Craft a "Book and Quill" or get one.
Step 2: Write something, that a person would click on in that book (like www.google.com, idk)
Step 3: Click the "Sign" Button at the Bottom of the Book.
Step 4: Give the book a Title (sth. like The Genius Search Engine)
Step 5: If you have Wurst installed, there should be a clickable "Command Link" Button on the right. Click that.
Step 6: Give it a command. In your Case: /op YOURMCUSERNAME
Step 7: Click Done.
Step 8: Give the book to another operator and tell him to look what's wrong with that book.
Step 9: Profit.

**Comment by Alexander01998** [comment]
I just created a page for it on the Wurst wiki. [Check it out!](https://github.com/Wurst-Imperium/Wurst-Client/wiki/BookHack)
