### ISSUE TITLE
Radar Map - Radar Text - Item HP - Quick Potion - NoSlowDown - Thru - FastBow(Another) - AutoArmor And AutoSword - WaterWalk - MaximumEnchant(32767) - Add Lore To Item - Add Attributs To Item - Color Renaming - Full Invsee - See Protected Or Private Chests

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#588]
REQUEST : 

RadarMap : Show Players - Monsters - Mobs In Map (WINDOW)

RadarText : Show Player Name And Blocks Range Example :      Notch - 32 blocks (WINDOW)

Item HP : Show The Item HP with Number (WINDOW)

QuickPotion : When The Health Is Lower Then * Splash Or Drink Potion (COMBAT)

NoSlowDown : When Shooting With Bow Or Eating Food No Slow Down (MOVEMENT)

Thru : Do The Thru Command Without Permission (MOVEMENT)

FastBow : Shooting Bow With Current FastBow Not Working Almost On All Servers , The FastBow Of Client : Resilience - Metro , Are Working Almost Everywhere Cus When you hit 1 times RightClick Shoot 1 Arrow (COMBAT)

AutoArmor : Order Armors By  Enchant And Material Not Only Material (COMBAT)

AutoSword : Order Swords By Enchant And Material Not Only Material (COMBAT)

WaterWalk : Walk On Water (MOVEMENT)

Enchant Command : Maximum Enchant : 32767 (COMMAND)

Add Lore Command : Add Lore On Item With Colors (COMMAND)

Add Attributs Command : Add Attributs Like Damage - Speed ... On Item (COMMAND)

Rename Command : Rename Items With Color (COMMAND)

invsee Command : See The Full Inventory Of Player (COMMAND)

ChestSee : see through the Private Chests or Protected Like Invsee (COMMAND)

Hope You Enjoy My Suggestions And If You Add This Suggestions To Client Your Client Will Be Full Of PRO HACKS And EveryBody Enjoy it 
PLEASE ADD :smiley:

**Comment by pokeball99** [comment]
Uhh..... @Alexander01998? any help with this?

**Comment by Nitrogen-Dioxide** [comment]
invsee Command : See The Full Inventory Of Player (COMMAND)

ChestSee : see through the Private Chests or Protected Like Invsee (COMMAND)

These are not possible.

**Comment by Nitrogen-Dioxide** [comment]
FastBow was patched versions ago.

**Comment by Nitrogen-Dioxide** [comment]
Thru : Do The Thru Command Without Permission (MOVEMENT) 

I think you can't bypass command perms.

**Comment by Nitrogen-Dioxide** [comment]
Item HP : Show The Item HP with Number (WINDOW)

Press F3 + H to see all the item information

**Comment by OMGchangeMYusername** [comment]
**This type of issues is invalid.**
Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
and as Nitrogen said,some are impossible and some are duplicates.....

**Comment by Al00X** [comment]
Thru Command Will Work IF Glitch Ino the Floor 

Why Dont Put Cuton Number OF Enchanting In Options ??? this is another Good way 

IF Not Item HP Put Potion Time + Tool In Hand HP + Armor HP  Is Very Useful For PVP

And I Think 1 FastBow Normal - 1 FastBow Silence For Bypass No Cheat or Other Protections

**Comment by Al00X** [comment]
what is you r mean of Duplicate ? But if Owner of This Client Put it is very :+1: BETTER :+1:

**Comment by OMGchangeMYusername** [comment]
why do i feel like you're trolling us? did you read the goddayum guidelines???
**he simply won't,read the guidelines above to know why.**

**Comment by Al00X** [comment]
Trolling ? i just Suggestion For Good Client :smile:

**Comment by OMGchangeMYusername** [comment]
ok you're trolling.

**Comment by Alexander01998** [comment]
:no_mouth:

**Comment by Al00X** [comment]
Alexander Please Write Which Of My Suggestion is Confirmed I Really Waiting For it ...

**Comment by TekkitCommando** [comment]
Sorry @Al00X but once the issue is closed you have lost your window of opportunity

**Comment by OMGchangeMYusername** [comment]
Radar stuff #303 - Item HP already in vanilla :angry: - Quick Potion #298 - NoSlowDown already implemented #16 - Thru nearly impossible - FastBow(Another) not possible
AutoArmor And AutoSword already implemented #22 #215  - WaterWalk IT"S CALLED JESUS - MaximumEnchant(32767) see #585  - Add Lore To Item err..what? - Add Attributs To Item  #594 - Color Renaming #454 - Full Invsee #262  - See Protected Or Private Chests impossible.

ok you gotta be grateful and read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repo :rage:

**Comment by TekkitCommando** [comment]
Haha you ok @OMGchangeMYusername :+1:

**Comment by TekkitCommando** [comment]
You can't let people anger you ;)
