### ISSUE TITLE
where/how did u learn English?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#589]
just wondering,since it seam it is a second language for u (although its great spelling and grammar non the less  :D)

**Comment by Alexander01998** [comment]
I didn't take a special English course or anything like that. I just go to school like everyone else.

I learned most of it by watching [Direwolf20](https://www.youtube.com/user/direwolf20) on YouTube. He uploads a 30-40 min video every day, which I used to watch every day.

I don't watch his videos anymore, but I have plenty of other English videos, texts, etc. surrounding me at any time. I can't even remember the last day I haven't heard or read something in English.

**Comment by OMGchangeMYusername** [comment]
lol me too xD
some people think i have special course or somthing but i'm just relying on school.
How i improved at speaking is by watching [TheDiamondMinecart] (https://www.youtube.com/user/TheDiamondMinecart),I watched his entire modded survival eps xD
oh @pokeball99 what is your native language? or what's your nation anyway.

**Comment by pokeball99** [comment]
english/U.S.A.
