### ISSUE TITLE
No Render (multiple types)

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#593]
Doesn't render entities or items or only don't render mobs/monsters/players etc.
Useful when there are a ton of stuff in the ground, or in parkours.
(when a lot of people blocks your vision).

**Comment by Meylama** [comment]
Code example from another client for NoRender:

http://hastebin.com/orivedulik.java

**Comment by Nitrogen-Dioxide** [comment]
@Meylama 
if ((entity instanceof EntityItem)

Thats only for items :/

**Comment by Meylama** [comment]
@Nitrogen-Dioxide: Maybe more options? Wurst could make a ".norender items", ".norender players", ".norender animals", ".norender monsters", ".norender mobs", and a ".norender all" to change this settings.

**Comment by Nitrogen-Dioxide** [comment]
Yes you just need to detect the type of the entity.

**Comment by Meylama** [comment]
Short question:

<code>
if ((entity instanceof EntityItem)
</code>

Does this also stop the rendering of XP-Orbs? (would be really nice to have this also in NoRender) :D
