### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#595]
ok this isn't essential *as many of you would think when reading the title*
in fact i thought it is completely useless at some point, but..
we can all be bored of listening songs from other places when playing,but what if Wurst plays your own songs/music?
i was so surprised at how it can get you in the mood while playing with your fav music or song!
and i think it's fairly simple to make, no?
Cicada music player:
![music](https://cloud.githubusercontent.com/assets/10786571/7297128/b643e464-e9ce-11e4-8a70-adc326e66dd5.gif)
such a nice feature can be even nicer if it's with Wurst
the songs should be just MP3 and be placed at `.minecraft/wurst/music`
it'll make my day if you accepted this :heart:

**Comment by pokeball99** [comment]
<3 the idea

**Comment by OMGchangeMYusername** [comment]
can i possibly ask for the reason?
i can understand if it was any sort of duplicate,or if it was multiple issues at once,or any sort of spam.
but i don't see any of the above fitting,
- **Don't get angry** or needy if your Issue gets rejected. We are free to reject any Issue for any reason.

that's why i'm asking you gently to inlcude the reason,as it might make future suggestions better.

**Comment by Alexander01998** [comment]
Mainly for performance reasons. Sounds are one of the top lag sources in Minecraft (that's also why rain causes so much lag) and running Windows Media Player in the background would achieve the same effect.

**Comment by TekkitCommando** [comment]
:+1:

**Comment by OMGchangeMYusername** [comment]
Optifine NO LAG!!11!!!!111! xD
Anyway i'll keep hoping that after wurst is done updating,you'll review this suggestion
