### ISSUE TITLE
PotionSaver

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#596]
Does this even work?https://github.com/TheFBI/Bureau-Hacked-Client/blob/master/src/minecraft/org/thefbi/mods/mods/combat/PotionSaver.java

**Comment by Nitrogen-Dioxide** [comment]
Not this way but yes...

**Comment by pokeball99** [comment]
So this can be used for infinite regeneration or strength right?

**Comment by Nitrogen-Dioxide** [comment]
Not infinite, since if you move, the time counts normally haha.

**Comment by pokeball99** [comment]
well,infinitely in place

**Comment by OMGchangeMYusername** [comment]
guys wait! does that mean if i enabled this when having resistance III for 4 more minutes,that should save me those 4minutes after the walls fall??

**Comment by OMGchangeMYusername** [comment]
i mean if i was ready and geared up and there's more five minutes,i should stop moving,and it should save me the 4 minutes for battle?

**Comment by pokeball99** [comment]
well,i hope this repects A.K. and that on would make it like u can get moved by players hitting u :D

**Comment by OMGchangeMYusername** [comment]
i have no idea what you could be saying.

**Comment by TekkitCommando** [comment]
Lol

**Comment by pokeball99** [comment]
well,if potion saver repects antiknock back,u can put that on,and then the potion effects time would go down when u get hit by a player in pvp :D

**Comment by TekkitCommando** [comment]
I understand what he's saying lol

**Comment by pokeball99** [comment]
i swear @TekkitCommando,u seem like the issue modrator,that what it seams when u type. XD

**Comment by TekkitCommando** [comment]
I would love to be but no xD I just am a wurst user that has a background in java and hacked client and server applications like craftbukkit :P so I try to help out

**Comment by TekkitCommando** [comment]
Oh yay a new version was just released :D

**Comment by OMGchangeMYusername** [comment]
i'm saying what daheck is "repect"???!?

**Comment by Nitrogen-Dioxide** [comment]
The potionsaver freezes the time when you don't send packets, so any hit/damage/anyhing "desfreezes" it. This is great because it is not all the time that you keeps hiting or moving. It can really save a lot of potion.

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide oooh that means what i said is possible?! since the walls divide players into four teams and your teammates can't hit you or damage you directly (fire and TNT can tho)

**Comment by TekkitCommando** [comment]
It is possible I'm sure

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername 
Yes.. you can keep the potions forever if you are stoped xD

Kepp in mind that the "desfreeze" is not infinite, so if you enable killaura with regen, it will only count the milisecs that you hit someone (or got hited).

**Comment by pokeball99** [comment]
Would it work with blink?

**Comment by Nitrogen-Dioxide** [comment]
@pokeball99 
How I will know? If this feature isn't implemented :p

**Comment by pokeball99** [comment]
true @Nitrogen-Dioxide ,derp on my end

**Comment by bazzz1512** [comment]
It would be really cool with enderpearl out of pvp and then get regen 2 for a long time

**Comment by pokeball99** [comment]
Closed? y?
