### ISSUE TITLE
NBTEditor for Creative

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#602]
NBTEditor for Creative :) (cmdblock with op)
.nbtedit:
	.nbtedit name <ItemName>
	.nbtedit lore add | set | remove | clear
	.nbtedit potion add regeneration 1 60
	.nbtedit cmdblock rename <name> |set <command> | clear
	.nbtedit attr clear | remove | add
	.nbtedit color 000000
	.nbtedit copy | paste
	.nbtedit count 64

name: change the item name
lore: add item lore's
potion: a potion editor
cmdblock: a commandblock editor
attr: Item Atribute editor
color: Armour color editor
copy | paste: Copy the ItemData and paste it to other slot in the Inventory
cout: set stack size of item

**Comment by Alexander01998** [comment]
Duplicate: #342

**Comment by ravenje** [comment]
Why!?
it was only 1 comnmand idee!
