### ISSUE TITLE
Selectable Enchantments

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#603]
.enchant all > Enchant item at all enchantments
.enchant <enchantment> <level> to select the enchantment
.enchant sharpness 10

**Comment by MyzticalTekkno** [comment]
or could alex edit the
currentItem.addEnchantment(enchantment, 127);
to
currentItem.addEnchantment(enchantment, 32467); ??? so would be more op XD

**Comment by 1337HaxorKiddie** [comment]
Sure that this is Working? The Number is really big.

**Comment by MyzticalTekkno** [comment]
<p>Sure that this is Working? The Number is really big.</p>
i think because the max level is 32767 because i know it from 
<#755><https://github.com/Wurst-Imperium/Wurst-Client/pull/755>

**Comment by 1337HaxorKiddie** [comment]
But not for Enchantment also with In-Game commands you can´t enchant over 127

**Comment by MyzticalTekkno** [comment]
As GummiBoat Said

>Afaik enchantments can be maximal lvl 32767 (because Mojang changed it to a 16-Bit integer) since >... dunno... a few patches atleast. (/give @p diamond_sword 1 0 {ench:[{id:16,lvl:32767}]}).

**Comment by GummiBoat** [comment]
@MyzticalTekkno No, it works everywhere. but the most Spigot/Bukkit servers, have a plugin that overwrites the vanilla /give command, so you have to type `/minecraft:give @p ...`.

**Comment by Alexander01998** [comment]
#755 is disconfirmed because it doesn't work.
