### ISSUE TITLE
.lore command

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#604]
To chance the item lore in creative (like .rename)
.lore set <text>
.lore clear
.lore add <text>
.lore remove <line>
.lore set <line> <text>

**Comment by Alexander01998** [comment]
What is a lore?

**Comment by ravenje** [comment]
The subtitle of a item
try this:
/give @p minecraft:command_block 1
/give @p minecraft:stone 1 0 {display:{Lore:["This is a lore","This is the Second line of a Lore"],Name:"This is the Itemname"}}

**Comment by Alexander01998** [comment]
#342 already does that.

**Comment by ravenje** [comment]
How?!
