### ISSUE TITLE
disable client

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#611]
is it possible to add a [Disable Client] button like huzuni has?

**Comment by TekkitCommando** [comment]
I am sure it's possible

**Comment by OMGchangeMYusername** [comment]
@ravenje @TekkitCommando this is a duplicate #276.
you shouldn't just answer him "i'm sure it's possible" you should also see if it's a duplicate or not :/
i said that because you were playing the defensive role last time.

**Comment by TekkitCommando** [comment]
I was just answering his question, it is a duplicate but you don't have the power to add the tag and neither do I, @Alexander01998 will do it

**Comment by TekkitCommando** [comment]
I could have said duplicate #276 but i still would have answered his question because i choose to

**Comment by TekkitCommando** [comment]
and if you wanted to go back far enough it would e duplicate #233 technically

**Comment by TekkitCommando** [comment]
;)

**Comment by OMGchangeMYusername** [comment]
that's not precisely right,because he's talking about **disabling the client**,not **removing the arraylist  and the client name for RECORDING** and it's not called *power* it's *permission*
also,this guy might close it before Alexander does and we'll all live happily ever after.

**Comment by TekkitCommando** [comment]
Don't be rude please :)

**Comment by OMGchangeMYusername** [comment]
Again,what is the "rude" part?

**Comment by TekkitCommando** [comment]
What's your nationality?

**Comment by OMGchangeMYusername** [comment]
you don't have to know,sorry.

**Comment by TekkitCommando** [comment]
And how old are you

**Comment by OMGchangeMYusername** [comment]
i'm 15 years old but what does that have to do with you? seriously.

**Comment by TekkitCommando** [comment]
Well if you were from Australia, UK, or US you would know what technically meant and that power and permission mean the same thing in that context

**Comment by TekkitCommando** [comment]
And I'm 17 so I probably understand a little more

**Comment by OMGchangeMYusername** [comment]
i just said that out of a little sarcasm to your use of words,power is the least used word in such things.
while the "permission" is often used to point out the ability to add/change things,either in a site or a game or whatever.

**Comment by OMGchangeMYusername** [comment]
and it's not necessary for age to point out the person's mind level or so (not saying i'm less/more minded than my age but it's not the case all the time)

**Comment by GummiBoat** [comment]
Guys, could you please stop bitchfighting and take the issues-section serious?

well, you can turn off all your modes with the panic-command. But why would it be necessary to disable the client? Just start another Minecraft-version and you're fine..

**Comment by OMGchangeMYusername** [comment]
i didn't really intend to continue this "bitchfighting" 
but i don't like to stop at the loser position,as it might make him feel a little cocky.
in fact when i said i'm fifteen he replied instantly that he's 17 and how he is more educated than me just because of our age..
also,sorry @TekkitCommando for talking about the word usage or whatever,i don't usually do that but i think you should also stop calling "rude" on every single comment i post.

**Comment by TekkitCommando** [comment]
It's fine sorry as well

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername 
@TekkitCommando 
This is not a forum, this is Github, please.

**Comment by OMGchangeMYusername** [comment]
i know i know.. read what i said.
oh and i only use two forums now and i don't really respond to them that much,my priority is Github for now because of Wurst <3

**Comment by TekkitCommando** [comment]
We already said sorry no poin in bringing it up again
