### ISSUE TITLE
Multiple commands in BookHack?

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#612]
Is it possible to add more commands to a book Like:
[Creative]  ->  /gamemode 1
[Survival]   -> /gamemode 0

i see it here:
https://github.com/TheWebmage/commands-json/blob/master/Magic%20Book

**Comment by TekkitCommando** [comment]
I am not sure on this one I have no experience with that we will have to see what @Alexander01998 thinks

**Comment by GummiBoat** [comment]
Well, you don't need that in a normal book to get permissions. So I assume you already have OP and Gamemode. You can achieve that by give yourself a Book with some NBT-Data in it.

Paste this into a commandblock and you have your book. 

/give @p minecraft:written_book 1 0 {author:"GummiBoat",title:"Gamemode",pages:["{text:\"[Creative]\",clickEvent:{action:\"run_command\",value:\"/gamemode 1\"},extra:[{text:\"\\n[Survival]\",clickEvent:{action:\"run_command\",value:\"/gamemode 0\"}}]}"]}

If you want to know more about that, there are plenty tutorials on youtube or in minecraft-wikis.

If you're on a Bukkit-Server, that has a plugin installed that takes advantage of the /give command and works with command-blocks, put a "minecraft:" in front of the give.

**Comment by TekkitCommando** [comment]
I didn't know that @GummiBoat Cool :)
