### ISSUE TITLE
Slime chunk finder

### ISSUE THREAD

**Issue by Illrigger** [Wurst-Imperium/Wurst-Client#613]
This would be extremely helpful because ops seldom want to reveal seeds to world maps.

**Comment by Nitrogen-Dioxide** [comment]
http://chunkbase.com/apps/slime-finder

**Comment by pokeball99** [comment]
And it would need access to the seed in the first place,which the server does not give to the client

**Comment by pokeball99** [comment]
And it would need access to the seed in the first place,which the server does not give to the client

**Comment by GummiBoat** [comment]
It's not possible. As @pokeball99 said, you need access to the seed. That's something most Servers reject, unless you are OP and type in /seed. So, if you want a Seed-based Chunk-checker, you need a plugin on your server, that enables that. (I don't think that there are some servers currently.)
