### ISSUE TITLE
Wurst spontaneous crash

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#615]
I was playing skywars with freecam and sneak enabled spectating people... and for no reason my minecraft screen turns gray and i cant do anything its not responding and i close minecraft and get this crash report: http://pastebin.com/3bKPqppn

Client Version: 1.14
OS: windows 8
Java: 1.8.0_45

**Comment by OMGchangeMYusername** [comment]
is this another crash that involve half blocks or something? #124

**Comment by GlitchHead** [comment]
i think it might be i was near a lot if slabs.... but it did not crash for a while
