### ISSUE TITLE
Spammer stop

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#616]
If the spammer is in a loop from a spam file and you used .spammer spam you cant stop it unless re logging you should add a ".spammer stop" command to cut all spamming.

**Comment by pokeball99** [comment]
can confirm

**Comment by GummiBoat** [comment]
I don't know how you managed a loop, but it should be avoidable, shouldn't it? Can you try to explain how to reproduce it? Because even if I have multiple repeats in a spam file, the spammer exits after he's done.

**Comment by GlitchHead** [comment]
sorry i for some reason never seemed to see your question till now just simply make a spam file like this
< --
Hello
.spammer spam hello
-->
save it as hello.wspam

**Comment by GummiBoat** [comment]
Okay, thank you for the late response. I never thought of actually calling the spammer command within the spammer. Well, for that specific reason, it really would be useful to have some thing that stops it.
