### ISSUE TITLE
Autobuild Templates

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#618]
http://i.imgur.com/gkKmXZ3.gifv
Bunker, Rampart, CompactStairs
Bunker: i meant in #367 move it into the combo box, and i made it.
Rampart: Great for Turf Wars at mineplex
CompactStairs: Great Stairs with least blocks
https://www.dropbox.com/s/kxhbxixc2t5fmis/autobuild.zip?dl=0

Note: don't say Bunker is made by mcccs, it's made by you (i only converted it)

**Comment by OMGchangeMYusername** [comment]
if that works,i'd be so happy and thanks!

**Comment by Nitrogen-Dioxide** [comment]
haha a new template maker, welcome xD.

The compactstairs can't be placed in a server :p you need to make it more "solid".

**Comment by OMGchangeMYusername** [comment]
The rampart didn't go well with turf wars..
(YesCheat+ enabled) it builds three or four blocks and then gets stuck after that :sad:
