### ISSUE TITLE
Command Signs

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#622]
a "Insert Command" button on a sign like BookHack
i think that's possible, i see it on Youtube
https://www.youtube.com/watch?v=klMST4cxGuw
time 5:10

**Comment by GummiBoat** [comment]
Yup, it's definitely possible. Because on Signs you can add the exact same NBT-Data as in Books.

A little Example (paste this into a commandblock): /setblock ~ ~1 ~ minecraft:standing_sign 0 replace {Text1:"{text:\"Click This.\",clickEvent:{action:run_command,value:\"/say Clicked.\"}}"}

**Comment by Alexander01998** [comment]
> Yup, it's definitely possible. Because on Signs you can add the exact same NBT-Data as in Books.
> 
> A little Example (paste this into a commandblock): /setblock ~ ~1 ~ minecraft:standing_sign 0 replace {Text1:"{text:\"Click This.\",clickEvent:{action:run_command,value:\"/say Clicked.\"}}"}

Thanks, I'll give it a try.

**Comment by mcccs** [comment]
please fix the title

command :microphone:

**Comment by GlitchHead** [comment]
also if this is possible colored signs will be possible too:
/setblock ~ ~1 ~ minecraft:standing_sign 0 replace {Text1:"{text:\"Click This.\",color:\"dark_blue\",clickEvent:{action:run_command,value:\"/say Clicked.\"}}"}
