### ISSUE TITLE
Wurst Main Class

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#623]
I am trying to debug wurst in eclipse. In order to create a launch config I need the main class however I can't seem to find it

**Comment by Alexander01998** [comment]
The preferred main class is MCP's `Start.java` in the default package.
Minecraft's `net.minecraft.client.main.Main.java` will work as well if you know the arguments.

**Comment by scriptinator** [comment]
It can not find the main class

**Comment by scriptinator** [comment]
But the file exists

**Comment by scriptinator** [comment]
Nvm

**Comment by mcccs** [comment]
@scriptinator mcpfolder > src.minecraft > start
