### ISSUE TITLE
Blink to block (without walking to him)

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#626]
.blink look
to blink to the block where I look

**Comment by GummiBoat** [comment]
.tp ?

**Comment by Nitrogen-Dioxide** [comment]
@ravenje Blink doesn't works this way.... When you enable it the movement packets stop and keeps recording, so, if you enable blink and insta tp to a block, is the same as the .tp command because you sent the same packets.
