### ISSUE TITLE
Font gets weird without ArrayList

### ISSUE THREAD

**Issue by Clean0nion** [Wurst-Imperium/Wurst-Client#63]
Wurst 1.5.1

When in Debug Mode (Fn+F3 / F3) the font on the Hack Menu becomes obfuscated and unreadable. The obfuscated font vaguely resembles the default Minecraft font in its pixel-ness.

(Related: when no mods are active or the Array List is in Hidden mode, the Wurst Version number also appears obfuscated. This is visible in the screenshots.)

Screenshots:
![2015-02-22_13 28 11](https://cloud.githubusercontent.com/assets/11146111/6318670/153a45ec-ba97-11e4-9ee8-e3d462b062bc.png)
![2015-02-22_13 28 22](https://cloud.githubusercontent.com/assets/11146111/6318671/153ce810-ba97-11e4-94b6-419422a385a9.png)
![2015-02-22_13 29 20](https://cloud.githubusercontent.com/assets/11146111/6318672/153d0516-ba97-11e4-8979-964338d4eb46.png)
![2015-02-22_13 29 31](https://cloud.githubusercontent.com/assets/11146111/6318673/153d2f32-ba97-11e4-8c0d-77eb8726918c.png)

**Comment by GlitchHead** [comment]
it also changes when you are holding a item.
