### ISSUE TITLE
Player Duplication

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#632]
First it types
.tp ~ ~ ~1
Then it types
.tp ~ ~ ~-1
With 0.1 seconds delay

Then it repeats this script
~  means players coordinate

This is an illusion and other players will be surprised!

**Comment by GummiBoat** [comment]
Try out blink. It kinda does the same. You activate it, you leave "your old position" and if you deactivate it you'll get "teleportet" to your new location.
