### ISSUE TITLE
.annoycommand

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#634]
the idea:
.annoycommand look in the chat for a failed command "7tpa" and execute the right command "/tpa <player>"
.annoycommand 7tpa /tpa
is this command possible?

**Comment by GummiBoat** [comment]
Yup, it's possible to replace a 7 with a /. But you also can press "#" before opening the chat, which will open your chat with a "/" in it instantly.

**Comment by ravenje** [comment]
i mean for tpa kill on server's

**Comment by GummiBoat** [comment]
Oh, you mean like.. someone else types 7tpa and Wurst sends /tpa for that person instead? That's impossible.

**Comment by ravenje** [comment]
why?

**Comment by GummiBoat** [comment]
Because it's not possible to send other peoples chat-messages, as far as i know.

**Comment by TekkitCommando** [comment]
Its not, A Server can do it but not a client

**Comment by ravenje** [comment]
no, i mean that i send /tpa from me
