### ISSUE TITLE
.enchant & .rename bug/problem

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#635]
Who do I .enchant or .rename use, which is sometimes item back to normal whom I click on the ground
which is possible to fix though, as I click on the item in inventory 1 time but I wolte still useable even know why this is so and whether you can fix that.

**Comment by OMGchangeMYusername** [comment]
i have no idea of what you could be saying.
you should explain that to someone in your native language and make him write the issue instead.

**Comment by GummiBoat** [comment]
It's about the functionality of .rename and .enchant. He means, that if you rightclick on the ground or sth like that, it returns back to normal. He needs to open his Inventory and click on it once to make sure that the enchants/the renaming stays.

**Comment by ravenje** [comment]
yes,
is this fixable?

**Comment by Nitrogen-Dioxide** [comment]
@ravenje I think not because it looks like the server removes the enchant/rename :p .

**Comment by TigrexHD** [comment]
you have to go over the item that you have renamed or enchanted with the mouse before you use the item or drop it

**Comment by OMGchangeMYusername** [comment]
This should be close :)

**Comment by im4nthony** [comment]
you have to open your inventory and click on the item once then place it back, fixed

**Comment by Eyremba** [comment]
@Alexander01998 there was a pull request a few weeks ago but you rejected it because there were a few things fixed in only one pull request. It was from @kim-yannick if I remember right. You could maybe fix it now.
