### ISSUE TITLE
Can't Open Menu

### ISSUE THREAD

**Issue by Zargonorix** [Wurst-Imperium/Wurst-Client#636]
Pressing Left Ctrl used to open the menus with all the hacks, but now it doesn't do anything. I think I deleted some keybinds, so that may be the issue, but I don't know how to bring my menu back. I still have the previous hacks I had on, still on, but I can't turn them off or use any other ones because I can't find the menu. Thanks

**Comment by GlitchHead** [comment]
The keybind command for gui is .t click gui

**Comment by Zargonorix** [comment]
THANKS SO MUCH!!!
