### ISSUE TITLE
Forge Modloader Possible?

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#637]
Is there a way to forge 1.8 to use in wust?
Because mods such as minimap?
Maybe someone can help me ...

**Comment by GummiBoat** [comment]
Already rejected. Duplicate of #464

**Comment by TekkitCommando** [comment]
That would cause unneeded lag and you wouldn't be able to use any mods but minimal making it not worth it

**Comment by TekkitCommando** [comment]
Minimap*
