### ISSUE TITLE
Please make the commands ~ and not .

### ISSUE THREAD

**Issue by StayBoltyHD** [Wurst-Imperium/Wurst-Client#639]
Please make the commands ~ and not . because all servers say "say .legit" and i get banned, but if it was changeable, please make it changeable or just change it to that.
it would help me out a lot!

**Comment by GlitchHead** [comment]
.say .legit

**Comment by OMGchangeMYusername** [comment]
ok what about making it "changeable"?
i mean,some clients have the command prefix thing that let you change the `.` to `-` or such.
it'd be cool if you made that.
