### ISSUE TITLE
Macro implement Idea 

### ISSUE THREAD

**Issue by dustyroo** [Wurst-Imperium/Wurst-Client#641]
I think had a Macro recorder/keybind it could be the next best hack client. No other has one. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1275039-macro-keybind-mod-0-10-12 if you go to that link you could somonehow implement it into the client.

**Comment by Nitrogen-Dioxide** [comment]
It is only for minecraft 1.7.10 :/ and.. It don't use forge right?

**Comment by dustyroo** [comment]
thats why I was wondering if you could update it for 1.8 and implement it and it does not use forge

**Comment by GummiBoat** [comment]
First of all, the Macro Keybind Mod is already released for 1.8. (http://eq2.co.uk/minecraft/mods/prerelease/).

And secondly, forge was already rejected several times. You can use the Wurst Keybinder. Well.. it isn't as progressive as the Mod, but it should be enough for the basics.

**Comment by Alexander01998** [comment]
Duplicate: #334
