### ISSUE TITLE
Random Crash v1.14 On MP Server

### ISSUE THREAD

**Issue by AiranewGaming** [Wurst-Imperium/Wurst-Client#642]
Screen turns black, close window and this shows
Wurst v1.14
Was on Mineplex Block Hunt

```
---- Please report this crash at: wurst-client.tk/bugs ----
// Sorry :(

Time: 4/26/15 11:41 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 6 total; [EntityPlayerSP['AiranewGaming'/22579493, l='MpServer', x=-89.41, y=16.50, z=-4.67], EntityOtherPlayerMP['SaintCafe'/769132, l='MpServer', x=-94.54, y=2.01, z=-10.01], EntityOtherPlayerMP['Cpellitt'/813925, l='MpServer', x=-55.56, y=4.01, z=42.50], EntityOtherPlayerMP['Acquadux'/755328, l='MpServer', x=35.56, y=4.05, z=-40.96], EntityOtherPlayerMP['tenderslim'/878566, l='MpServer', x=6.42, y=4.01, z=5.38], EntityOtherPlayerMP['LGxTragicJr'/872187, l='MpServer', x=-92.24, y=5.01, z=-10.68]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -990.00,4.00,-315.00 - World: (-990,4,-315), Chunk: (at 2,0,5 in -62,-20; contains blocks -992,0,-320 to -977,255,-305), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 4137120 game time, 1146828000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntityChicken['Chicken'/881421, l='MpServer', x=-11.74, y=4.00, z=-31.28], EntityChicken['Chicken'/881420, l='MpServer', x=-13.49, y=4.04, z=-22.61], EntityArrow['arrow'/881932, l='MpServer', x=-81.69, y=2.03, z=18.31], EntityChicken['Chicken'/877582, l='MpServer', x=-27.72, y=4.02, z=1.69], EntityChicken['Chicken'/881422, l='MpServer', x=-13.38, y=3.00, z=-25.56], EntityChicken['Chicken'/881417, l='MpServer', x=-28.75, y=4.00, z=4.16], EntityChicken['Chicken'/881416, l='MpServer', x=-30.53, y=4.00, z=-1.59], EntityChicken['Chicken'/881419, l='MpServer', x=-11.56, y=2.00, z=-28.47], EntityChicken['Chicken'/881418, l='MpServer', x=-16.56, y=4.00, z=-27.41], EntityArrow['arrow'/881930, l='MpServer', x=-82.06, y=2.03, z=18.03], EntityChicken['Chicken'/881413, l='MpServer', x=-31.59, y=4.00, z=0.41], EntityChicken['Chicken'/881412, l='MpServer', x=-41.22, y=4.00, z=7.78], EntityChicken['Chicken'/881415, l='MpServer', x=-36.53, y=4.09, z=4.19], EntityChicken['Chicken'/881414, l='MpServer', x=-33.28, y=4.00, z=0.53], EntityArrow['arrow'/881926, l='MpServer', x=-82.31, y=2.03, z=18.06], EntityChicken['Chicken'/881409, l='MpServer', x=-42.56, y=4.00, z=8.47], EntityOtherPlayerMP['LGxTragicJr'/872187, l='MpServer', x=-92.24, y=5.01, z=-10.68], EntityChicken['Chicken'/881411, l='MpServer', x=-37.94, y=4.00, z=10.19], EntityChicken['Chicken'/881410, l='MpServer', x=-39.97, y=4.00, z=4.75], EntityArrow['arrow'/882461, l='MpServer', x=-47.63, y=4.00, z=10.59], EntityArrow['arrow'/882462, l='MpServer', x=-63.47, y=3.22, z=31.31], EntityArrow['arrow'/882457, l='MpServer', x=-91.75, y=5.03, z=6.41], EntityArrow['arrow'/882459, l='MpServer', x=-91.75, y=5.03, z=6.41], EntityChicken['Chicken'/881428, l='MpServer', x=-9.22, y=3.47, z=59.41], EntityFallingBlock['Falling Block'/882449, l='MpServer', x=-54.64, y=4.17, z=-65.01], EntityChicken['Chicken'/881424, l='MpServer', x=-14.22, y=3.00, z=-26.28], EntityChicken['Chicken'/881427, l='MpServer', x=-11.75, y=3.50, z=60.59], EntityItemFrame['entity.ItemFrame.name'/870191, l='MpServer', x=-91.50, y=6.50, z=-8.97], EntityItemFrame['entity.ItemFrame.name'/870190, l='MpServer', x=-92.50, y=9.50, z=-10.03], EntityArrow['arrow'/882494, l='MpServer', x=-62.88, y=3.00, z=8.88], EntityChicken['Chicken'/757565, l='MpServer', x=-98.34, y=4.00, z=-4.66], EntityArrow['arrow'/882490, l='MpServer', x=5.91, y=2.78, z=-30.97], EntityItemFrame['entity.ItemFrame.name'/870196, l='MpServer', x=-94.97, y=3.50, z=-8.50], EntityItemFrame['entity.ItemFrame.name'/870199, l='MpServer', x=-72.97, y=3.50, z=3.50], EntityPlayerSP['AiranewGaming'/22579493, l='MpServer', x=-89.41, y=16.50, z=-4.67], EntityItemFrame['entity.ItemFrame.name'/870198, l='MpServer', x=-67.97, y=3.50, z=4.50], EntityItemFrame['entity.ItemFrame.name'/870193, l='MpServer', x=-90.03, y=3.50, z=-8.50], EntityItemFrame['entity.ItemFrame.name'/870192, l='MpServer', x=-93.50, y=6.50, z=-8.97], EntityItemFrame['entity.ItemFrame.name'/870195, l='MpServer', x=-94.97, y=3.50, z=-1.50], EntityItemFrame['entity.ItemFrame.name'/870194, l='MpServer', x=-90.03, y=3.50, z=-1.50], EntityPig['Pig'/876876, l='MpServer', x=20.80, y=4.00, z=-8.24], EntityArrow['arrow'/882511, l='MpServer', x=-89.00, y=9.05, z=-12.34], EntityArrow['arrow'/882505, l='MpServer', x=-71.31, y=2.00, z=9.16], EntityChicken['Chicken'/876875, l='MpServer', x=-69.53, y=2.51, z=4.69], EntityTNTPrimed['Block of TNT'/882507, l='MpServer', x=22.13, y=4.00, z=-35.19], EntityFallingBlock['Falling Block'/882506, l='MpServer', x=-35.49, y=10.80, z=-3.54], EntityArmorStand['§aRadar Hunter'/881732, l='MpServer', x=-89.50, y=6.46, z=4.50], EntityArrow['arrow'/882503, l='MpServer', x=0.97, y=10.69, z=-16.38], EntityChicken['Chicken'/876865, l='MpServer', x=-35.49, y=10.62, z=-3.44], EntityArmorStand['§aTNT Hunter'/881731, l='MpServer', x=-92.50, y=6.46, z=5.50], EntityArmorStand['§eLeaper Hunter'/881730, l='MpServer', x=-95.50, y=6.46, z=4.50], EntityChicken['Chicken'/833884, l='MpServer', x=39.50, y=4.01, z=-8.72], EntityPainting['Painting'/870246, l='MpServer', x=0.00, y=6.00, z=25.97], EntityMinecartFurnace['entity.MinecartFurnace.name'/870229, l='MpServer', x=10.31, y=5.50, z=-58.50], EntityTNTPrimed['Block of TNT'/882515, l='MpServer', x=34.49, y=4.00, z=-35.84], EntityFallingBlock['Falling Block'/882514, l='MpServer', x=-69.86, y=3.22, z=49.44], EntityMinecartFurnace['entity.MinecartFurnace.name'/870249, l='MpServer', x=24.63, y=4.50, z=-56.50], EntityOtherPlayerMP['SaintCafe'/769132, l='MpServer', x=-94.54, y=2.01, z=-10.01], EntityOtherPlayerMP['Cpellitt'/813925, l='MpServer', x=-55.56, y=4.01, z=42.50], EntityChicken['Chicken'/755327, l='MpServer', x=35.44, y=5.01, z=-15.31], EntityOtherPlayerMP['Acquadux'/755328, l='MpServer', x=35.56, y=4.05, z=-40.96], EntityChicken['Chicken'/836992, l='MpServer', x=-2.83, y=4.01, z=51.78], EntitySilverfish['Silverfish'/881557, l='MpServer', x=-89.31, y=16.34, z=-4.53], EntityOtherPlayerMP['Ginny4122006'/878585, l='MpServer', x=2.50, y=4.00, z=3.50], EntityFallingBlock['Falling Block'/881558, l='MpServer', x=-89.31, y=16.57, z=-4.53], EntityChicken['Chicken'/739497, l='MpServer', x=-10.44, y=15.45, z=-55.31], EntityChicken['Chicken'/797608, l='MpServer', x=39.31, y=4.01, z=61.69], EntityFallingBlock['Falling Block'/881827, l='MpServer', x=-69.60, y=2.68, z=4.76], EntityOtherPlayerMP['ChocolateChips10'/876875, l='MpServer', x=3.50, y=4.00, z=6.50], EntityOtherPlayerMP['tenderslim'/878566, l='MpServer', x=6.42, y=4.01, z=5.38], EntityArrow['arrow'/882101, l='MpServer', x=-74.00, y=2.00, z=-5.84], EntityOtherPlayerMP['Acquadux'/755328, l='MpServer', x=35.56, y=4.05, z=-40.96], EntityPig['Pig'/881357, l='MpServer', x=-39.09, y=4.00, z=-10.97], EntityPig['Pig'/881356, l='MpServer', x=-35.38, y=4.00, z=-12.88], EntityPig['Pig'/881359, l='MpServer', x=-36.13, y=4.00, z=8.66], EntityPig['Pig'/881358, l='MpServer', x=-34.22, y=4.00, z=9.63], EntityPig['Pig'/881353, l='MpServer', x=-42.09, y=4.00, z=6.06], EntityZombie['§aRadar Hunter Kit'/881352, l='MpServer', x=-89.50, y=5.00, z=4.50], EntityPig['Pig'/881355, l='MpServer', x=-33.91, y=4.00, z=-13.06], EntityPig['Pig'/881354, l='MpServer', x=-39.59, y=4.00, z=11.03], EntityZombie['§aTNT Hunter Kit'/881351, l='MpServer', x=-92.50, y=5.00, z=5.50], EntityZombie['§eLeaper Hunter Kit'/881350, l='MpServer', x=-95.50, y=5.00, z=4.50], EntityChicken['Chicken'/872897, l='MpServer', x=-69.89, y=3.04, z=49.53], EntityChicken['Chicken'/874176, l='MpServer', x=-0.96, y=4.01, z=8.88], EntityOtherPlayerMP['pentaholic13'/788450, l='MpServer', x=5.50, y=4.00, z=1.50], EntityOtherPlayerMP['SaintCafe'/769132, l='MpServer', x=-94.54, y=2.01, z=-10.01], EntityOtherPlayerMP['Cpellitt'/813925, l='MpServer', x=-55.56, y=4.01, z=42.50], EntityPig['Pig'/881365, l='MpServer', x=-29.13, y=4.00, z=-13.03], EntityPig['Pig'/881364, l='MpServer', x=-30.83, y=5.00, z=-16.16], EntityChicken['Chicken'/875991, l='MpServer', x=-9.75, y=11.01, z=-5.34], EntityPig['Pig'/881361, l='MpServer', x=-33.84, y=4.00, z=-15.22], EntityPig['Pig'/881360, l='MpServer', x=-37.75, y=4.00, z=-12.22], EntityPig['Pig'/881363, l='MpServer', x=-35.53, y=5.00, z=-17.91], EntityPig['Pig'/881362, l='MpServer', x=-35.53, y=5.00, z=-17.91], EntityOtherPlayerMP['LGxTragicJr'/872187, l='MpServer', x=5.50, y=4.00, z=3.50], EntityOtherPlayerMP['tenderslim'/878566, l='MpServer', x=6.42, y=4.01, z=5.38], EntityChicken['Chicken'/788450, l='MpServer', x=-54.64, y=4.00, z=-64.91], EntityChicken['Chicken'/878585, l='MpServer', x=-44.97, y=10.01, z=34.35], EntityOtherPlayerMP['LGxTragicJr'/872187, l='MpServer', x=-92.24, y=5.01, z=-10.68]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"fa828eb":1059) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 108988856 bytes (103 MB) / 362848256 bytes (346 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
```

**Comment by Alexander01998** [comment]
When including error output, please wrap it into a [Markdown code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) so that it renders nicely.
Example:

<pre>```
java.lang.NullPointerException: null
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
```</pre>

**Comment by AiranewGaming** [comment]
Happened again. How do I fix?

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I bet Cylons wouldn't have this problem.

Time: 5/1/15 12:21 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 15 total; [EntityPlayerSP['AiranewGaming'/87606973, l='MpServer', x=-13.78, y=4.00, z=44.61], EntityOtherPlayerMP['marleyva2'/967099, l='MpServer', x=-1.59, y=4.00, z=75.81], EntityOtherPlayerMP['Mighted'/975425, l='MpServer', x=-2.55, y=4.00, z=51.36], EntityOtherPlayerMP['lolinator233'/1005614, l='MpServer', x=24.87, y=8.00, z=31.99], EntityOtherPlayerMP['VampireBeauty'/967098, l='MpServer', x=-5.88, y=5.11, z=36.40], EntityOtherPlayerMP['meablings'/1005152, l='MpServer', x=46.44, y=10.00, z=15.69], EntityOtherPlayerMP['portal_shard'/999216, l='MpServer', x=48.84, y=10.00, z=16.28], EntityOtherPlayerMP['ampardo'/958633, l='MpServer', x=46.22, y=8.00, z=67.03], EntityOtherPlayerMP['ApostleHD'/996562, l='MpServer', x=-4.45, y=6.44, z=90.11], EntityOtherPlayerMP['DarkMatrixWars'/708739, l='MpServer', x=2.16, y=9.00, z=83.97], EntityOtherPlayerMP['muppet_slayer'/1004985, l='MpServer', x=-38.34, y=11.02, z=101.78], EntityOtherPlayerMP['LegendPiggle'/968420, l='MpServer', x=-2.31, y=4.00, z=90.28], EntityOtherPlayerMP['Lazy_Girl'/996561, l='MpServer', x=-29.06, y=4.00, z=92.97], EntityOtherPlayerMP['WindCraft'/1005303, l='MpServer', x=-24.59, y=4.00, z=61.84], EntityOtherPlayerMP['santa1111111111'/956734, l='MpServer', x=-17.06, y=4.00, z=49.53]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -990.00,4.00,-315.00 - World: (-990,4,-315), Chunk: (at 2,0,5 in -62,-20; contains blocks -992,0,-320 to -977,255,-305), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 302013 game time, 30420000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntityEnderPearl['entity.ThrownEnderpearl.name'/1008527, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008526, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008525, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008524, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008523, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityOtherPlayerMP['DarkMatrixWars'/708739, l='MpServer', x=2.16, y=9.00, z=83.97], EntityOtherPlayerMP['lolinator233'/1005614, l='MpServer', x=24.87, y=8.00, z=31.99], EntityOtherPlayerMP['Mighted'/975425, l='MpServer', x=-2.55, y=4.00, z=51.36], EntityOtherPlayerMP['marleyva2'/967099, l='MpServer', x=-1.59, y=4.00, z=75.81], EntityPlayerSP['AiranewGaming'/87606973, l='MpServer', x=-13.78, y=4.00, z=44.61], EntityOtherPlayerMP['portal_shard'/999216, l='MpServer', x=48.84, y=10.00, z=16.28], EntityOtherPlayerMP['meablings'/1005152, l='MpServer', x=46.44, y=10.00, z=15.69], EntityOtherPlayerMP['VampireBeauty'/967098, l='MpServer', x=-5.88, y=5.11, z=36.40], EntityOtherPlayerMP['DarkMatrixWars'/708739, l='MpServer', x=2.16, y=9.00, z=83.97], EntityOtherPlayerMP['ApostleHD'/996562, l='MpServer', x=-4.45, y=6.44, z=90.11], EntityOtherPlayerMP['ampardo'/958633, l='MpServer', x=46.22, y=8.00, z=67.03], EntityOtherPlayerMP['WindCraft'/1005303, l='MpServer', x=-24.59, y=4.00, z=61.84], EntitySkeleton['§f§l§kXX§r §bBriDragon02 §f§l§kXX'/1008407, l='MpServer', x=-23.63, y=4.00, z=37.28], EntityOtherPlayerMP['Lazy_Girl'/996561, l='MpServer', x=-29.06, y=4.00, z=92.97], EntityOtherPlayerMP['LegendPiggle'/968420, l='MpServer', x=-2.31, y=4.00, z=90.28], EntityOtherPlayerMP['muppet_slayer'/1004985, l='MpServer', x=-38.34, y=11.02, z=101.78], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008530, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityOtherPlayerMP['BriDragon02'/875090, l='MpServer', x=-23.90, y=4.00, z=37.74], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008529, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityOtherPlayerMP['santa1111111111'/956734, l='MpServer', x=-17.06, y=4.00, z=49.53], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008528, l='MpServer', x=-2.03, y=5.50, z=75.63], EntityOtherPlayerMP['lolinator233'/1005614, l='MpServer', x=24.87, y=8.00, z=31.99], EntityOtherPlayerMP['ampardo'/958633, l='MpServer', x=46.22, y=8.00, z=67.03], EntityArmorStand['§f§l§kXX§r §bBriDragon02 §f§l§kXX'/1008421, l='MpServer', x=-23.63, y=5.35, z=37.28], EntityOtherPlayerMP['santa1111111111'/956734, l='MpServer', x=-17.06, y=4.00, z=49.53], EntityOtherPlayerMP['VampireBeauty'/967098, l='MpServer', x=-5.88, y=5.11, z=36.40], EntityBat['Bat'/1003963, l='MpServer', x=-25.25, y=7.10, z=48.69], EntityOtherPlayerMP['marleyva2'/967099, l='MpServer', x=-1.59, y=4.00, z=75.81], EntityBat['Bat'/1003962, l='MpServer', x=-33.25, y=8.10, z=20.75], EntityOtherPlayerMP['muppet_slayer'/1004985, l='MpServer', x=-38.34, y=11.02, z=101.78], EntityOtherPlayerMP['portal_shard'/999216, l='MpServer', x=48.84, y=10.00, z=16.28], EntitySnowball['Snowball'/1008463, l='MpServer', x=0.13, y=14.70, z=87.25], EntitySnowball['Snowball'/1008462, l='MpServer', x=-9.88, y=17.64, z=91.09], EntitySnowball['Snowball'/1008461, l='MpServer', x=-1.47, y=15.70, z=90.94], EntitySnowball['Snowball'/1008460, l='MpServer', x=-3.47, y=13.02, z=85.63], EntitySnowball['Snowball'/1008459, l='MpServer', x=-2.81, y=13.42, z=85.28], EntitySnowball['Snowball'/1008458, l='MpServer', x=-3.25, y=21.95, z=83.09], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008456, l='MpServer', x=-1.81, y=23.36, z=116.72], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008455, l='MpServer', x=-4.59, y=15.73, z=111.41], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008454, l='MpServer', x=-3.06, y=22.14, z=116.03], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008453, l='MpServer', x=-10.91, y=13.14, z=121.84], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008452, l='MpServer', x=-4.38, y=21.27, z=121.28], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008451, l='MpServer', x=-9.28, y=15.52, z=109.91], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008450, l='MpServer', x=-8.25, y=22.83, z=116.81], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008449, l='MpServer', x=-8.19, y=24.73, z=110.66], EntityOtherPlayerMP['Mighted'/975425, l='MpServer', x=-2.55, y=4.00, z=51.36], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008347, l='MpServer', x=-80.03, y=-57.47, z=159.62], EntityOtherPlayerMP['ApostleHD'/996562, l='MpServer', x=-4.45, y=6.44, z=90.11], EntityOtherPlayerMP['Lazy_Girl'/996561, l='MpServer', x=-29.06, y=4.00, z=92.97], EntitySnowball['Snowball'/1008465, l='MpServer', x=-1.94, y=21.52, z=83.44], EntitySnowball['Snowball'/1008464, l='MpServer', x=-4.59, y=19.08, z=83.41], EntitySkeleton['§f§l§kXX§r §cAiranewGaming §f§l§kXX'/1008490, l='MpServer', x=-14.44, y=4.00, z=45.00], EntityEnderPearl['entity.ThrownEnderpearl.name'/1008489, l='MpServer', x=-18.62, y=5.53, z=50.51], EntitySnowball['Snowball'/1008487, l='MpServer', x=0.33, y=5.97, z=75.38], EntityOtherPlayerMP['LegendPiggle'/968420, l='MpServer', x=-2.31, y=4.00, z=90.28], EntityOtherPlayerMP['meablings'/1005152, l='MpServer', x=46.44, y=10.00, z=15.69], EntityArmorStand['§f§l§kXX§r §cAiranewGaming §f§l§kXX'/1008504, l='MpServer', x=100.00, y=64.00, z=100.00], EntityOtherPlayerMP['WindCraft'/1005303, l='MpServer', x=-24.59, y=4.00, z=61.84]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"fa828eb":1059) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 175140512 bytes (167 MB) / 325079040 bytes (310 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)

**Comment by redkilllerz45p** [comment]
I'm still getting this on v1.14.1

**Comment by OMGchangeMYusername** [comment]
v1.14.1 only fixed some bugs,it's not like he said it fixes everything.
