### ISSUE TITLE
Admins see bookhack /OP command?

### ISSUE THREAD

**Issue by Saint-Khaine** [Wurst-Imperium/Wurst-Client#646]
I figured it would be wiser to ask this here before trying it out.  If I successfully pull off /op <my name> using the Bookhack, will the admin see that they've op'ed me, or will their chatbox remain empty?  How soon they know sort of limits the effectiveness of it.

**Comment by TekkitCommando** [comment]
They would no immediately if they're on :)

**Comment by TekkitCommando** [comment]
Know*

**Comment by TekkitCommando** [comment]
Essentials or even the default minecraft server would notify I'm sure, there is no way the book hack should be able to change that

**Comment by Saint-Khaine** [comment]
Wow, that was a fast response.  I might try severely lagging/crashing the server immediately afterword, get them thinking its a mistake they've seen.  The first thing to be done is get a command block, and hope they don't notice.

**Comment by TekkitCommando** [comment]
Haha good luck :) and yes I try to respond immediately xD

**Comment by TekkitCommando** [comment]
I actually didn't think about that, slipped my mind good job @pokeball99

**Comment by pokeball99** [comment]
np,athough i do wish that we could do multible commands at once like /gamerule commandoutput false;/gamerule logadmin false;/op @a :D

**Comment by TekkitCommando** [comment]
:D yep that would be cool

**Comment by Saint-Khaine** [comment]
So have the first be /game rule command output false, then /gamerule log admin false, then /op <me!>!  Brilliant, I really look forward to this.  I know an admin who would click all three books too.

**Comment by ravenje** [comment]
Good idea pokeball99 :D i open a issuse: https://github.com/Wurst-Imperium/Wurst-Client/issues/651
