### ISSUE TITLE
Effect Invisibility bug?

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#650]
if i has the effect invisibility, i can see myself!
/effect ravenje minecraft:invisibility 999 100
or a invisibility Potion...
why?

**Comment by GlitchHead** [comment]
wow have not realized that in wurst your not invisible in F5 mode or your hands are not but in normal minecraft you cant see them.

**Comment by ravenje** [comment]
yes, i now but its a bug

**Comment by GoGoJJTech** [comment]
Could it be that you have truesight on?

**Comment by GummiBoat** [comment]
No, it's definitely not because of truesight. I don't know what causes the problem, but the effect doesn't show up in the effect-bar either. (give yourself the effect, open your inventory and you don't have it, even if everyone else can confirm, that you're invisible.)
