### ISSUE TITLE
More 1.4 versions cuz i cant download latest java stuff 

### ISSUE THREAD

**Issue by MorganPlaysMC** [Wurst-Imperium/Wurst-Client#653]
Can u make more 1.4 versions please For some reason i cant download latest java stuff idk why but i cant so can u plz add more 1.4 versions? with all the latest wurst stuff but no latest java ok if u would have to remove something from the client for that to happen i dont care just please do it. And it could be possible other people have this issue too.

**Comment by OMGchangeMYusername** [comment]
@MorganPlaysMC seriously? this is the weirdest request i've seen at this repo..

**Comment by GlitchHead** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by GlitchHead** [comment]
If that does not work goto https://minecraft.net/download and download the msi installer and it will make minecraft run off of the latest java (java 8)

**Comment by TekkitCommando** [comment]
So what there saying is No, because this is not a problem a lot of people have and it's not worth managing two versions of worth sorry :/ If the MSI doesn't work try COMPLETELY removing java from your computer then installing it again.

**Comment by MorganPlaysMC** [comment]
How is this a duplicate?

**Comment by MorganPlaysMC** [comment]
Ok ill try your suggestions.
