### ISSUE TITLE
Add GodMode and TpAura?

### ISSUE THREAD

**Issue by Creepy11** [Wurst-Imperium/Wurst-Client#655]

**Comment by eveythingistaken** [comment]
Um.. Ok? What's tpaura?

**Comment by TekkitCommando** [comment]
Its where if someone gets close to you, you teleport to them and start killing them with killaura

and GodMode is pretty easy to figure out

**Comment by TekkitCommando** [comment]
@Creepy11 @Alexander01998 probly wont read this if you close it right after typing it :P
