### ISSUE TITLE
Presets for settings & enabled mods

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#656]
New tab : Presets
New feature: Save all current mods/settings and enables them whenever you want.
New command : .Savemods [NAME] {KeyBind}
How to use : 
1. Either use the new command or button.
2. Name your preset.
3. Set a keybind (OPTIONAL)
4. Click on whatever you named your preset it should load the mods/settings saved

**Comment by eveythingistaken** [comment]
That's a very good idea.

**Comment by TekkitCommando** [comment]
:+1:

**Comment by arnont33** [comment]
good idea :D

**Comment by mcccs** [comment]
Lots o' mods sounds better
