### ISSUE TITLE
Book Author Changer (for multiplayer)

### ISSUE THREAD

**Issue by Huanjohn** [Wurst-Imperium/Wurst-Client#657]
In v1.13, BookHack was added. A great idea might be to add a book author changer (for multiplayer) that changes the author of the book, i.e. in order to hide that YOU wrote said book, especially if that book was written with a Command Link (BookHack).

**Comment by Nitrogen-Dioxide** [comment]
Problaly only possible in creative but possible.

**Comment by Nitrogen-Dioxide** [comment]
Is this dublicate to the NBT tag editor?

**Comment by Huanjohn** [comment]
I mean to work on a multiplayer server that you don't host.  Doesn't NBT Edit only work on singleplayer and multiplayer servers that you host.

**Comment by pokeball99** [comment]
Or sever u have op

**Comment by Huanjohn** [comment]
When a player signs a book, does the client store the author data in the book; or does the server see who signs the book, then adds the author data to the book?  And is the author data of the book stored in the book item itself, or is it stored in the server and referenced when a player hovers over the book?

**Comment by GummiBoat** [comment]
It should definitely be possible. After you clicked on the "Sign" Book, the Autor automatically appears under your Title-Name. So I guess the Sign-Button Checks for your Username in some way. I also saw in the "original" Bookhack, that the Author was "Server". Should be Something in the GuiScreenBook.class like "this.bookObj.setTagInfo("author", new NBTTagString("§cWurst"));".

**Comment by Huanjohn** [comment]
I see the line you are talking about in the sendBookToServer method, however when i set that line to:
this.bookObj.setTagInfo("author", new NBTTagString("Server"));
and implement it into the Wurst Client, Minecraft crashes when I try to open a book and quill.

**Comment by trollmad3** [comment]
This would be awesome for getting op on a server you can change the author for saying
Example: Hello this is the owner can you please click this url to go to are website 
when they click it you get op

**Comment by Huanjohn** [comment]
What about something like [this](http://pastebin.com/LM6kTvAW)?

**Comment by GummiBoat** [comment]
Did you tested it?

**Comment by Huanjohn** [comment]
It now checks if the item is a book.  I can't test it, my minecraft crashes anytime I try to add a new command.

**Comment by Huanjohn** [comment]
Tested it, it works.

![authorcmd](https://cloud.githubusercontent.com/assets/12178060/8663334/3af3c594-298f-11e5-8949-ce2fb0e78de6.gif)

**Comment by trollmad3** [comment]
@Huanjohn how do i add the code in to wurst?

**Comment by Alexander01998** [comment]
@Huanjohn Are you going to PR this?

**Comment by Huanjohn** [comment]
@Alexander01998 Sure.
