### ISSUE TITLE
Realms?

### ISSUE THREAD

**Issue by Bc1151** [Wurst-Imperium/Wurst-Client#659]
Minecraft realms does not seem to work with this client (1.8.4) I am missing something and I don't know what. A little assistance would be greatly appreciated. 

(The button does not show up or I can't find it)

Thanks!

**Comment by pokeball99** [comment]
The button for realms was removed because modded clients are not able to connect to realms

**Comment by ravenje** [comment]
why not?

**Comment by Alexander01998** [comment]
> why not?

Because Wurst (and most other clients) are based on Minecraft 1.8, which isn't compatible to Realms anymore.
