### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by xeZx** [Wurst-Imperium/Wurst-Client#664]
Happy Birthday Wurst! The 1st Anniversary!

**Comment by OMGchangeMYusername** [comment]
err.. idgaf about anniversaries or birthdays or whatever but if that's right,Happy birthday xD

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Great suggestion.

**Comment by mcccs** [comment]
Yep. It's uploaded now.
https://www.wurst-client.tk/news/2015-05-01-first-anniversary/
