### ISSUE TITLE
.Search

### ISSUE THREAD

**Issue by jojo319** [Wurst-Imperium/Wurst-Client#666]
When i search for something
![screen shot 2015-05-01 at 7 47 14 am](https://cloud.githubusercontent.com/assets/12194088/7429807/65514dfe-efd6-11e4-8fc5-87946cb4ba3e.png)

happens.

how do i make it work

**Comment by eveythingistaken** [comment]
What are you trying to accomplish?

**Comment by OMGchangeMYusername** [comment]
Disconfirmed,working fine here:
![default search](https://cloud.githubusercontent.com/assets/10786571/7430468/8f418070-f01c-11e4-94dd-becc0ad55ec8.gif)

**Comment by jojo319** [comment]
Thanks
