### ISSUE TITLE
Server World downloader

### ISSUE THREAD

**Issue by Notchshero** [Wurst-Imperium/Wurst-Client#67]
Downloads server worlds.

**Comment by Clean0nion** [comment]
If this is possible then something to view the server world's seed would also be nice

**Comment by OMGchangeMYusername** [comment]
hmm.. that's nice!

**Comment by Alexander01998** [comment]
How would that work???

**Comment by GlitchHead** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285484-world-downloader-mod

**Comment by GlitchHead** [comment]
@Clean0nion Minecraft servers no longer send the seed to players

**Comment by Notchshero** [comment]
Here, more info: it is Open Source
https://github.com/dslake/WorldDownloader

**Comment by Alexander01998** [comment]
> Here, more info: it is Open Source
> https://github.com/dslake/WorldDownloader

It's incompatible with Minecraft 1.8.

**Comment by GlitchHead** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285484-world-downloader-mod
it is 1.8 goto that link: ^ there is a skydrive Download quick link:

https://onedrive.live.com/?cid=77B5E138E468EDE3&id=77B5E138E468EDE3!338
(includes decompiled sources)

**Comment by Alexander01998** [comment]
I'll take a look at it.

**Comment by pokeball99** [comment]
this might be of some use
https://github.com/italiceyeball/v/commit/fc3eb2f6c109f388fccd18bc2915462107c6f180

**Comment by pokeball99** [comment]
y was this not added? the link above showed the way it could be done

**Comment by Alexander01998** [comment]
> y was this not added? the link above showed the way it could be done

Because it rewrites too much vanilla source code and isn't worth the effort.
