### ISSUE TITLE
Attempting to combine two commands with 1 keybind will result in only 1 keybind.

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#671]
If title is confusing, read this:
Create new key, command is .help. Changed keybind to 3.
Create another new key, that is .t prophuntesp. Changed keybind to 3.
Old keybind is removed and replaced with the command '.t prophuntesp' instead of both PropHuntESP and help being shown with the same key.
Another bug is if you create a new key, type a command, and *then* create a keybind, the command field will be empty.

**Comment by OMGchangeMYusername** [comment]
The title is too long :/ why not "One keybind for multiple commands"
Oh just researched it,Duplicate #422
