### ISSUE TITLE
Potion Enchantments

### ISSUE THREAD

**Issue by Huanjohn** [Wurst-Imperium/Wurst-Client#672]
A possible suggestion is to add a feature (like .potion) that can enchant potions with potion enchantments(i.e. blindness, speed, resistance, night vision, etc.) similar to how .enchant enchants items with item enchantments (i.e. sharpness, unbreaking, protection, etc.).  Then, as far as which enchantments would go on said potion, there could possibly be commands such as
.potion add (enchantment)  and  .potion remove (enchantment).

**Comment by Alexander01998** [comment]
Potion effects are not enchantments, they can't be changed.
