### ISSUE TITLE
WSPAM + Keybind help

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#674]
So I'm trying to run alot of commands with one click. I saved a spam script and it is in my wurst > autorun file. Now in the keybind menu, I have this command  .spammer spam sword.wspam I also tried it without the .wspam at the end. Do you know why it won't run the commands? Also, in chat it just says "file doesn't exist".

**Comment by GummiBoat** [comment]
![Image 1](http://puu.sh/hyQCJ/83de018e7f.png)
![Image 2](http://puu.sh/hyQFy/6029165709.png)
![Image 3](http://puu.sh/hyQIl/2b46f55655.png)

Don't save it in the Autorun-Folder.

**Comment by eveythingistaken** [comment]
Thanks :)
