### ISSUE TITLE
Auto-drop

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#676]
I'm going afk at a mob spawner thing, but my inventory fills up so I can't pick up money. Is there a way to instantly drop or not pick up at all a certain item? If not, I guess this is should be in suggestions..

**Comment by GummiBoat** [comment]
I guess the "money" is credited to your account as soon as it gets into your inventory? If so, then setup a WSPAM Script with 30000ms delay (every 30 Seconds)
```
<repeat 50>.drop
</repeat>
```
To stop it, simply relog on the server/reload the world.

**Comment by eveythingistaken** [comment]
The thing is, I want to keep one item in my inventory. So I want to drop all items except one item

**Comment by Nitrogen-Dioxide** [comment]
@eveythingistaken 
Weepcraft have this feature, it is called.... item ban or something. It drops all the unwanted items you select.

**Comment by eveythingistaken** [comment]
@Nitrogen-Dioxide Ok thanks

**Comment by OMGchangeMYusername** [comment]
lol
dude why did you close this?the confirmed label means he will add it later xD
you should re-open this.
