### ISSUE TITLE
Weird texturepack problem.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#679]
for some weird reason when i try to play galaxy wars on mc.hypixel.net i goto the waiting lobby and get a texture pack download prompt when i click yes to download it it keeps saying downloading texturepack....
it closes applys the texture pack but then it pops up again downloading texture pack... and just keeps repeating i get kicked at game start for not having the texture pack yet i clearly did on the normal minecraft 1.8.4 its working fine i can play on galaxy wars but with wurst i cant.

game output:
http://pastebin.com/gJmbgFEE

**Comment by Alexander01998** [comment]
That appears to be a problem with Hypixel, as it is working just fine on other servers.
You should try their `/resourcehelp` command.
