### ISSUE TITLE
Reverse Throw Mod

### ISSUE THREAD

**Issue by JackWurst** [Wurst-Imperium/Wurst-Client#682]
Just like the throw mod can throw items all at once, there should be a mod that doesn't get rid of the item when you throw it.

**Comment by Alexander01998** [comment]
Throw is about throwing eggs, snowballs, etc. Not about dropping items.
If you want to be unable to drop items, you can delete the keybind for it.

**Comment by OMGchangeMYusername** [comment]
never thought of that! nice idea hehe :D
