### ISSUE TITLE
Mob AI controller

### ISSUE THREAD

**Issue by JackWurst** [Wurst-Imperium/Wurst-Client#684]
Just like you can see the perspective of the nearest entity, on vanilla servers/in single player you should be able to control it. If the nearest mob is a zombie, you can hop into its body and walk around. (Of course your character would stay where it started, just like in something in the 'Free Flight' mod.)
if it is possible, would it be possible to control other people? :0 who knows

**Comment by GummiBoat** [comment]
With a plugin, yes. Without - no. Same reason as the chat-thing. you can't block/modify someone elses movement-packets.
