### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Miotrestoked** [Wurst-Imperium/Wurst-Client#686]
Hi Alexander! You're doing great, I LOVE Wurst! But could you please add Optifine in it, too? I've tried several hacked clients, they were not as good as this one but they DID have Optifine, which I found very handy.

Thank you for reading.

Yours, Miotrestoked

**Comment by GummiBoat** [comment]
Rejected several times. Duplicate: #2 
Please search the section before opening new issues.

**Comment by Miotrestoked** [comment]
:/ Sorry 
I just like the zooming function

**Comment by OMGchangeMYusername** [comment]
lol i actually mistoke you for this guy #437 
but there ya go this is a duplicate and it has been rejected over twenty times...
