### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 49ers2001** [Wurst-Imperium/Wurst-Client#690]
I'm playing on this Survival/economics server. I like this server but I want to be op or get more money without them tracing it back to me is this possible?

A bug display or something like that where you you can type in the plug ins and it searches for bugs in the plug in could be very usefull.

Show the id when you hover you mouse at a block it shows you the id or something else so I can see the ID's of blocks when I for example want to add stuff to xray.

Anonym. This is meant to be so you can hide your name tag in the multiplayer game. This would be a great tool.

Allahu akbar:
Whereever you walk behind you everything explodes.

Bomber:
Get the coordinates of a building/player and then blow it up from distance.

Trace back. Is there a tool where you can break block anonnym?

Kind Regards

**Comment by Nitrogen-Dioxide** [comment]
@49ers2001 The sugestions are good, but never put 2, 3, 4 sugestions in the same issue :/
This way alexander can't resolve and keep everything organized.

**Comment by OMGchangeMYusername** [comment]
lol @Nitrogen-Dioxide i hope you're joking.
for me i couldn't see any proper suggestion except for that nametag thing and i doubt it's possible...

**Comment by 49ers2001** [comment]
@OMGchangeMYusername  Sry man Im really new to this client and I doubted that these where possible but hey I just wrote what I thought could be cool it isnt hurting anybody

**Comment by OMGchangeMYusername** [comment]
@49ers2001 ok i'm sorry i exaggerated a little in your other issue.
because you know this is issue number 690! that means a hell load of issues were dealt with and that is a lot for @Alexander01998 because he has to organise every single issue...

**Comment by 49ers2001** [comment]
Ok sry about that. Well im gonna be more precise and only put the most necessary ideas in thx for your quick reply :+1:
