### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#691]
Please implement a way to use a IP:PORT proxy to bypass ip bans more quickly ;)

**Comment by OMGchangeMYusername** [comment]
duplicate #70.
Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by OMGchangeMYusername** [comment]
err.. you sure?
