### ISSUE TITLE
i lose all my alts after restart the game

### ISSUE THREAD

**Issue by llaurenss** [Wurst-Imperium/Wurst-Client#693]
i lose all my alts after restart the game. when i add some alts to wurst and close the game and open it aigen the alts are gone am i the only one with this problem?

**Comment by OMGchangeMYusername** [comment]
close the previous issue.
also,don't worry Alexander will look at it soon but he could be just offline.
oh and you should review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by llaurenss** [comment]
yeah thanks, the first time i add a issue to github ;)

**Comment by OMGchangeMYusername** [comment]
lol i was so confused first time i came here xD
i wanted to report an issue but i made a new wiki page instead xD
anyway if you read the guidelines above they should help you.

**Comment by llaurenss** [comment]
oke, thanks.

**Comment by Nitrogen-Dioxide** [comment]
@llaurenss No... I had this problem, the alts was not saving, but this didn't was annoying me so I never opened a issue :/ 
Well... the only way it fixed ( for me ) was when I installed windows 8 (formated everything) .

**Comment by Alexander01998** [comment]
Dupliacte: #570
