### ISSUE TITLE
Add Auto Parkour,auto jump,safe walk

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#694]

**Comment by OMGchangeMYusername** [comment]
dude did you read the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repo?
you have to provide a description to your issues and you shouldn't put multi[le suggestions into one issue,that will make your issue labelled **invalid**.
and btw i'm not sure what you meant by these but some of them are already suggested,you should search the issues to check out if they've been suggested or not next time :D

**Comment by OMGchangeMYusername** [comment]
**watching a show while leaving Github,that's why i'm responding too much today** :grin:
