### ISSUE TITLE
Wurst v2.0 Release Date

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#697]
Hey I was wondering when you think you'll be finished with Wurst 2.0. Just your general estimate like in this week?

**Comment by Alexander01998** [comment]
It's very hard to tell, as the progress in deobfuscating Minecraft 1.8.3 is so unpredictable.

**Comment by eveythingistaken** [comment]
@Alexander01998 Will it be done this month?

**Comment by TekkitCommando** [comment]
hes not sure

**Comment by pokeball99** [comment]
Hey @Alexander01998,any update on when u going to be developed wurst again?it looks like the hook manager is complete

**Comment by Alexander01998** [comment]
> it looks like the hook manager is complete

It's not. Only the basics (injecting hooks at method beginnings & ends) are done.

**Comment by pokeball99** [comment]
So @Alexander01998 what left is needed?

**Comment by Alexander01998** [comment]
> So @Alexander01998 what left is needed?

- Hooks that steal method parameters,
- Hook Manager settings files (will replace the `minecraft.patch` file),
- the `HookManager` class that actually manages the hooks (currently just prints them to the console),
- automatically adding the `HookManager` class to the Jar,
- setting all private/protected fields & methods to public,
- maybe a better auto updater (currently downloads the update but doesn't install it)
- and probably more...
