### ISSUE TITLE
Proxies for joining multiplayer servers

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#70]
Enhancement: Can you please add Socks proxy's for multi player servers like a small box to enter a proxy and test it and join a server with a new ip address me i really need this because a lot of people want to ddos me. (dont ask) so if you could add this feature it would really help me not get ddosed or tracked or attacked thank you.

**Comment by Alexander01998** [comment]
I would rather use HTTP proxies for that. They are much easier to find than SOCKS.

**Comment by Ericyeah** [comment]
I don't think he's asking you to provide proxies for users, I think he's asking for the functionality to input your own proxies to be an possibility. I think it'd be wholesomely unreasonable for anyone to expect you to maintain a database of proxies for your client.

**Comment by Alexander01998** [comment]
> I don't think he's asking you to provide proxies for users, I think he's asking for the functionality to input your own proxies to be an possibility. I think it'd be wholesomely unreasonable for anyone to expect you to maintain a database of proxies for your client.

I know. I was talking about *support* for SOCKS proxies, not about *providing* SOCKS proxies.

**Comment by Ericyeah** [comment]
I don't understand your usage of the word find, unless you're saying you're going to refrain from adding a functionality based on the fact socks proxies are more difficult to find, despite the fact they're significantly more stable, which is especially beneficial for a game who's networking infrastructure is major, and requires minimal delay.

**Comment by Alexander01998** [comment]
> I don't understand your usage of the word find

# Defintion of finding proxies
1. Go to http://google.com.
2. Search `:8080 site:pastebin.com`.
3. In the search options, set the time to `last 24h`.
4. Copy anything that looks like a proxy list.
5. Run your list through a proxy checker.
6. Done!

> despite the fact they're significantly more stable

Not stable for me, not at all.

> for a game who's networking infrastructure is major, and requires minimal delay.

Delays of up to 30s are allowed in Minecraft. My definition of "minimal delays" does not allow delays of more than 3s.

**Comment by GlitchHead** [comment]
i have a proxy leecher and i would not have a problem with HTTP proxy's i use proxy's for other things to.

**Comment by GlitchHead** [comment]
like i really need this i cant seem to find a vpn for linux that works with minecraft

**Comment by Alexander01998** [comment]
> like i really need this i cant seem to find a vpn for linux that works with minecraft

CyberGhost maybe?

**Comment by Ericyeah** [comment]
@GlitchHead Why not just apply an HTTP proxy to your entire systems network? Any PPTP VPN should work anyways.

**Comment by GlitchHead** [comment]
i have been using PPTP VPN's but there flipping annoying to find and find ones that work with minecraft.

**Comment by GlitchHead** [comment]
@Alexander01998 CyberGhost for linux is not a install its just PPTP servers and you have to pay for them.

**Comment by Alexander01998** [comment]
> @Alexander01998 CyberGhost for linux is not a install its just PPTP servers and you have to pay for them.

They have a free demo and I have used it with Minecraft before.

**Comment by GlitchHead** [comment]
like on linux or windows or mac? there is not download for linux for CyberGhost There are PPTP servers for CyberGhost and you can setup linux to connect to the PPTP vpn server.

**Comment by Alexander01998** [comment]
> like on linux or windows or mac? there is not download for linux for CyberGhost There are PPTP servers for CyberGhost and you can setup linux to connect to the PPTP vpn server.

I don't know, just downloaded & installed it.

**Comment by GlitchHead** [comment]
Well still a vpn is a lot more than a change ip it does other stuff that causes lag a proxy just changes ip and hides it thats all i really need simple and basic and i can bypass ip bans for greifing some vpns don't have a lot of virtual locations for new ip's :)

**Comment by Alexander01998** [comment]
> Well still a vpn is a lot more than a change ip it does other stuff that causes lag a proxy just changes ip and hides it thats all i really need simple and basic and i can bypass ip bans for greifing some vpns don't have a lot of virtual locations for new ip's :)

Well still, this feature request already has the `confirmed` label since yesterday. :grinning:

**Comment by GlitchHead** [comment]
well i just really want this ;D

**Comment by GlitchHead** [comment]
thx

**Comment by GlitchHead** [comment]
i know you have a lot of work to do, but what time would you think this feature would be finished? just asking.

**Comment by Alexander01998** [comment]
> i know you have a lot of work to do, but what time would you think this feature would be finished? just asking.

Generally, a feature is finished up to 7 days after I start working on it. However, there is no way to know when I will start working on a feature. All you know is that it's on the list (of confirmed enhancements).

**Comment by eveythingistaken** [comment]
Have u started working on this? It's beena month. If you added that would be so sick

**Comment by failvenom** [comment]
@Alexander01998 Cyberghost can get very annoying when u have to wait D:<

**Comment by trollmad3** [comment]
I would love this. i see other hack clients (ghost,nodus,weepcraft,) and weepcraft has a proxy checker and you can also use the proxy for minecraft servers

**Comment by WurstContributor** [comment]
@Alexander01998 Why?

**Comment by pokeball99** [comment]
@wurstcontributor if your talking about y he closed this issue,he added this,just see the recent commits

**Comment by WurstContributor** [comment]
Oh Sorry. I didn't see the commits
