### ISSUE TITLE
Make the Home mod changeable when you have multiple homes

### ISSUE THREAD

**Issue by Lakitu** [Wurst-Imperium/Wurst-Client#701]
There is a Home mod, that types '/home' for you when pressing 'h'. This works only when you have one home, because you have to type '/home home' when you have multiple homes. I saw that the new 2.0 GUI will have text fields. So it makes the possibility to fill in what home you want to use for the Home mod. Is this an executable idea?

P.S. Excuse me if my English is hard to read, I am doing my best to learn English.

**Comment by GlitchHead** [comment]
you can set a key bind for it just change the h key bind to /home otherhome

**Comment by Lakitu** [comment]
This doesn't works, because '/home' is the mod name, not the command. ;)

**Comment by GummiBoat** [comment]
Esc -> Wurst Options -> Keybinds -> Add/Edit "H"

![Image](http://puu.sh/hBAxa/27ee91a7f1.png)

Save. Yay!

**Comment by Lakitu** [comment]
Thanks, I didn't know that you can use keybinds for in-game commands, I had '.t /home', a Wurst command. The HomeMod isn't essential for this, so I close this issue. ;)
