### ISSUE TITLE
Activate/Deactivate Wurst

### ISSUE THREAD

**Issue by HeyShell** [Wurst-Imperium/Wurst-Client#702]
Put an option for activate or deactivate the hack.
So many people asks you: Can you write ".hi"?...
or something, and the people can catch you with the hack... and will report u.
I dont know if this is avaible in 1.14> version... but i dont see that option nowhere.
(Sorry for my english :v)
If you want to translate this from Spanish to English:

Pon alguna opción para activar o desactivar el hack.
Mucha gente te pregunta: ¿Puedes escribir ".hi"?
o algo similar, y la gente puede atraparte con el hack... y pueden reportarte.
No sé si ya está disponible en la versión 1.14> pero no he visto esa opción en ninguna parte.

**Comment by scriptinator** [comment]
.say .hi

**Comment by GummiBoat** [comment]
Please search your issue before creating a new one. Already rejected several Times and as @scriptinator said, you can just type ".say .hi" or ".say .legit" or whatever the admin wants from you.

Duplicate of #141 .
