### ISSUE TITLE
Crashing when playing on a multiplayer server

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#704]
Every time i want to play OITC or a factoin server (OITC=One In The Chamber) i was using bow aimbot no slowdown killauralegit and AntiKnockback and i was on a killing spree and then it was a gray crash and then i got mad.......I dont know what i did.....please help

**Comment by scriptinator** [comment]
Post a crash log

**Comment by trollmad3** [comment]
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Shall we play a game?

Time: 5/9/15 8:24 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1326)
	at net.minecraft.client.Minecraft.run(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:127)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.ChatComponentStyle.getFormattedText(ChatComponentStyle.java:107)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:97)
	at net.minecraft.client.gui.GuiIngame.func_175180_a(GuiIngame.java:414)

-- Affected level --
Details:
	Level name: MpServer
	All players: 11 total; [EntityPlayerSP['bugzncheese1'/5572, l='MpServer', x=17.91, y=170.42, z=7.45], EntityOtherPlayerMP['brendoproto69'/856, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Creeper_Face_45'/5556, l='MpServer', x=1.94, y=169.00, z=-4.72], EntityOtherPlayerMP['LastPopcornTime'/5564, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Justinisswag12'/5523, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['LiamRyan6'/5575, l='MpServer', x=-5.28, y=169.00, z=1.72], EntityOtherPlayerMP['iTuxedoTim'/5582, l='MpServer', x=0.50, y=170.00, z=1.50], EntityOtherPlayerMP['pcsimke'/5584, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['matty_114'/5585, l='MpServer', x=-1.44, y=169.91, z=3.06], EntityOtherPlayerMP['alledenvilde'/5587, l='MpServer', x=0.47, y=170.00, z=1.50], EntityOtherPlayerMP['SmookyLukey'/5588, l='MpServer', x=0.53, y=170.00, z=1.50]]
	Chunk stats: MultiplayerChunkCache: 960, 960
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,170.00,1.00 - World: (0,170,1), Chunk: (at 0,10,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1042316280 game time, 178457989820 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityOtherPlayerMP['pcsimke'/5584, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['matty_114'/5585, l='MpServer', x=-1.44, y=169.91, z=3.06], EntityOtherPlayerMP['DarthUncle'/5586, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['alledenvilde'/5587, l='MpServer', x=0.47, y=170.00, z=1.50], EntityOtherPlayerMP['SmookyLukey'/5588, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Justinisswag12'/5523, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Creeper_Face_45'/5556, l='MpServer', x=1.94, y=169.00, z=-4.72], EntityOtherPlayerMP['LastPopcornTime'/5564, l='MpServer', x=0.53, y=170.00, z=1.50], EntityArmorStand['§d§lMineverse'/71, l='MpServer', x=-6.31, y=171.73, z=1.50], EntityOtherPlayerMP['LiamRyan6'/5575, l='MpServer', x=-5.28, y=169.00, z=1.72], EntityArmorStand['§7§lWelcome, please right'/72, l='MpServer', x=-6.31, y=171.48, z=1.50], EntityArmorStand['§7§lclick your Navigator to select'/73, l='MpServer', x=-6.31, y=171.23, z=1.50], EntityArmorStand['§7§la server!'/74, l='MpServer', x=-6.31, y=170.98, z=1.50], EntityOtherPlayerMP['brendoproto69'/856, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['TomBoy_7'/5569, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Creeper_Face_45'/5556, l='MpServer', x=1.94, y=169.00, z=-4.72], EntityOtherPlayerMP['iTuxedoTim'/5582, l='MpServer', x=0.50, y=170.00, z=1.50], EntityOtherPlayerMP['LastPopcornTime'/5564, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['xSoulHero'/5537, l='MpServer', x=-3.41, y=169.00, z=1.56], EntityOtherPlayerMP['pcsimke'/5584, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Justinisswag12'/5523, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['matty_114'/5585, l='MpServer', x=-1.44, y=169.91, z=3.06], EntityOtherPlayerMP['alledenvilde'/5587, l='MpServer', x=0.47, y=170.00, z=1.50], EntityOtherPlayerMP['SmookyLukey'/5588, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['scope0106'/5570, l='MpServer', x=-0.31, y=170.00, z=0.69], EntityOtherPlayerMP['Renard2004'/5571, l='MpServer', x=-2.09, y=170.00, z=1.50], EntityOtherPlayerMP['brendoproto69'/856, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['RxbotsSharedAcc'/5561, l='MpServer', x=-5.47, y=169.00, z=2.78], EntityOtherPlayerMP['JAKE_INATOR'/5562, l='MpServer', x=-8.09, y=169.00, z=-2.25], EntityOtherPlayerMP['Samuel_Hubbard'/5540, l='MpServer', x=-6.88, y=169.00, z=-0.66], EntityOtherPlayerMP['SWAGER_ANDREA'/5548, l='MpServer', x=2.88, y=169.50, z=-2.28], EntityOtherPlayerMP['HappySmiles714'/5558, l='MpServer', x=-16.88, y=170.00, z=1.50], EntityOtherPlayerMP['3snoW'/5573, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['Creepy_DoesMC'/5574, l='MpServer', x=-4.00, y=169.00, z=1.22], EntityOtherPlayerMP['LiamRyan6'/5575, l='MpServer', x=-5.28, y=169.00, z=1.72], EntityOtherPlayerMP['YRys11'/5576, l='MpServer', x=4.22, y=169.50, z=1.50], EntityOtherPlayerMP['DarthNick1'/5577, l='MpServer', x=2.56, y=169.50, z=4.81], EntityOtherPlayerMP['ElectroStorm'/5578, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['jboy66'/5579, l='MpServer', x=0.53, y=170.02, z=1.50], EntityOtherPlayerMP['rubyrude'/5580, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['rubyrude'/5581, l='MpServer', x=0.53, y=170.00, z=1.50], EntityOtherPlayerMP['iTuxedoTim'/5582, l='MpServer', x=0.50, y=170.00, z=1.50], EntityPlayerSP['bugzncheese1'/5572, l='MpServer', x=17.91, y=170.42, z=7.45], EntityOtherPlayerMP['_TrojanVirus_'/5583, l='MpServer', x=0.53, y=170.00, z=1.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e6da9cb":1040) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:393)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2949)
	at net.minecraft.client.Minecraft.run(Minecraft.java:440)
	at net.minecraft.client.main.Main.main(Main.java:127)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.14 (latest: 1.14)
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 186774312 bytes (178 MB) / 341602304 bytes (325 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 39, allocated: 13, tallocated: 95
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 350.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Canadian English (Canada)
	Profiler Position: N/A (disabled) 



PS:Sorry if it took to long Had school work :)

**Comment by Alexander01998** [comment]
Duplicate: #642
