### ISSUE TITLE
.attribute command

### ISSUE THREAD

**Issue by Lakitu** [Wurst-Imperium/Wurst-Client#705]
The commands .enchant and .rename are working in creative mode, they are both item properties, and attributes are item properties too. So I think it should be possible to make a command for this, .attribute, that will be useful. There are five different attributes: maxHealth, followRange (for mobs, I think) knockbackResistance, movementSpeed and attackDamage. So it is very helpful, and there is legit AntiKnockback. :P
http://minecraft.gamepedia.com/Attribute
Is it possible to add this?

**Comment by GummiBoat** [comment]
A .give Command with NBT-Support was already confirmed. And adding Attributes is not the same as adding enchantments or changing names.( #342 )
