### ISSUE TITLE
Bookhack bug report

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#706]
I take a book and typed text
if i now used bookhack and sign it, the second replace some spacers with \n
Here are screenshots

![screenshot-minecraft 1 8-2](https://cloud.githubusercontent.com/assets/12088599/7482167/c3d51430-f375-11e4-9d0e-7044a5f9d935.png)

![screenshot-minecraft 1 8-3](https://cloud.githubusercontent.com/assets/12088599/7482171/c9e6a276-f375-11e4-9cf2-ce8d965f7fc8.png)

**Comment by Alexander01998** [comment]
BookHack breaks into the JSON data by removing the outer `{}` brackets, so it leaves a JSON-escaped  version of the book text.

I personally don't find this very annoying, considering that URLs don't use any characters that need to be escaped, so unless someone finds a good way to produce the same data using GSON or to reverse-escape the text afterwards, I will just leave it as it is.
