### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by StarLord1226** [Wurst-Imperium/Wurst-Client#707]
When i press ctrl to open the menu it doesnt work and i cant get any keybindings up. does anyone know how to fix this?

**Comment by Alexander01998** [comment]
Duplicate: #545

**Comment by StarLord1226** [comment]
what does duplicate: #504 mean?

**Comment by GummiBoat** [comment]
That your Issue already was reported and someone came up with a solution or it was rejected. In your case, just click on the Number and read the post.

Next time, before opening new Issues, please search for your problem.
![Image](http://puu.sh/hC1Fc/1af12ad39d.png)

**Comment by StarLord1226** [comment]
but what does the website have anything to do with what i need? i need to know how to make it so i can get keybindings and the mods list

**Comment by GummiBoat** [comment]
Escape -> Wurst Options -> Keybindings. Then bind .t ClickGUI to CTRL. (You stated the wrong number. He said it's a duplication from 545, you went to 504). Is it really that hard to understand it?

**Comment by StarLord1226** [comment]
whoops my bad. sorry
