### ISSUE TITLE
Hide the Wurst logo on top left corner!

### ISSUE THREAD

**Issue by Kalid910** [Wurst-Imperium/Wurst-Client#708]
Most Minecrafters often like to sreenshare with their friends or post screenshots. Well we can't do that if this huge Wurst sign is on the top lft corner please add a feature so we can hide or disable the Wurst logo on the top left corner thanks.

**Comment by GummiBoat** [comment]
Press F1 or F3, or use a Screenshot-Programm like Puush, where you can select an Area for Screenshots.

Next Time please search the Issues for your problem, before opening a new one. 

![Image](http://puu.sh/hC1Fc/1af12ad39d.png)
Duplicate #19

**Comment by Kalid910** [comment]
I don't think your getting what I mean I want to be able to play while that logo isn't there at all.

**Comment by GummiBoat** [comment]
I don't think you're getting why the same request as yours has been rejected over 9000 times.

If you want to play regular - use regular minecraft. If you want to use  a hacked client - atleast let them have the credit for putting so much effort in it.

**Comment by WurstContributor** [comment]
@GummiBoat  ITS OVAR 9000!!!!!!!!!

**Comment by TekkitCommando** [comment]
@GummiBoat well said pal

**Comment by OMGchangeMYusername** [comment]
@WurstContributor & @TekkitCommando Why are you pumping something this old for absolutely no reason?

**Comment by TekkitCommando** [comment]
@OMGchangeMYusername Why are you a dick for absolutely no reason? Case Closed moving on

**Comment by OMGchangeMYusername** [comment]
Sorry it appears you're far more ignorant than i thought you are.

**Comment by TekkitCommando** [comment]
Nah Bro just keep your comments to yourself unless it's about the issue or it's something nice :)

**Comment by OMGchangeMYusername** [comment]
Wait you're saying this?

**Comment by TekkitCommando** [comment]
@OMGchangeMYusername lol we are friends don't worry :+1:

**Comment by OMGchangeMYusername** [comment]
@TekkitCommando Ok :c
