### ISSUE TITLE
Keybind reset to default after restart?

### ISSUE THREAD

**Issue by capsload** [Wurst-Imperium/Wurst-Client#71]
Hey,

when i restart MC, it changes the GUI Bind back to RSHIFT, while i set it to LSHIFT.

**Comment by OMGchangeMYusername** [comment]
it's left ctrl (facepalm)

**Comment by Alexander01998** [comment]
Probably the new file format. Running the [converter](https://github.com/Wurst-Imperium/Wurst-file-converter/releases/tag/v1.5) helps.
