### ISSUE TITLE
Worldedit

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#710]
Something like worldedit to save autobuild things easier
Like select an item to be ur wand

**Comment by GlitchHead** [comment]
Like a auto build recorder? It will recored something you build and save it to the templates? That would make making auto build templates much easy

**Comment by Alexander01998** [comment]
> Something like worldedit to save autobuild things easier
> Like select an item to be ur wand

AutoBuild templates cannot be made by scanning existing buildings because the order and direction that the blocks were placed in is important.
