### ISSUE TITLE
McEdit schematic builder

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#713]
This would take auto-building to a whole new level if you could create a mod that when you click it you will get a select file popup and you select a .schematic file then you will get a out line of it in green boxes like in auto build and select were it will be placed and it auto builds it and adds the items to your inventory needed for it to be build if in creative it will take control of the player and move it around and place the blocks... this would be probably very complicated to make but it is possible just some cool idea i had.

**Comment by Alexander01998** [comment]
AutoBuild templates are incompatible to MCEdit schematics because the order and direction that the blocks were placed in is important for AutoBuild.
