### ISSUE TITLE
Turn on/off

### ISSUE THREAD

**Issue by GhostGuy283** [Wurst-Imperium/Wurst-Client#716]
make a feature that you can disable and enable wurst! or maybe a hide button that you can make screenshots and nobody sees that you are hacking!

**Comment by GummiBoat** [comment]
Press F1 to hide your GUI completely.

Next time please search for your matter instead of opening a new issue.
![Image](http://puu.sh/hC1Fc/1af12ad39d.png)

Duplicate of #19.
