### ISSUE TITLE
Nuker

### ISSUE THREAD

**Issue by TigrexHD** [Wurst-Imperium/Wurst-Client#717]
if a player or a mob is in my nuker range and nuker is enabled then I kicked from the server and this notification comes
![2015-05-06_12 30 50](https://cloud.githubusercontent.com/assets/11839093/7493584/89e8ae98-f402-11e4-99b6-7982f486a577.png)

**Comment by GummiBoat** [comment]
What version of Nuker are you using? (ID/Flat/...)

Also, if you're nuking too much at the same time, you'll get the error pretty often. Try adjusting the Speed and range. (Atleast that helped me while using nuker.)

**Comment by TigrexHD** [comment]
normal

**Comment by bazzz1512** [comment]
I get this when you nuke area's where you can't break blocks. the server then kicks you for too much activity going on.

**Comment by OMGchangeMYusername** [comment]
guys i don't really see the point of the whole "Nuker"!
i can understand when talking about creative and it's actually fun,but Nuker at survival mode is just pointless to me (or i might be misunderstanding the whole thing). How can i make use of it?

**Comment by Alexander01998** [comment]
> guys i don't really see the point of the whole "Nuker"!
> i can understand when talking about creative and it's actually fun,but Nuker at survival mode is just pointless to me (or i might be misunderstanding the whole thing). How can i make use of it?

1. Get Efficiency 5 diamond tools.
2. Enable SpeedNuker.
3. Grief everything incredibly quickly.
4. Profit.
