### ISSUE TITLE
NoBreak

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#718]
Add a mod that makes so that when a tool or sword is at very low durability it does not allow you to swing it at all, so you don't break it.

**Comment by GummiBoat** [comment]
What is the point of this? If you press F3+H you have detailed information about the durability. And if you care for your equipment, you're gonna see when it drops to critical damage.

**Comment by OMGchangeMYusername** [comment]
@GummiBoat why did you steal what i was writing xD

**Comment by GummiBoat** [comment]
I'm utterly evil. >:)

**Comment by eveythingistaken** [comment]
It would be useful if you wanted to automate mining (with tunneler and autowalk) and you wanted to save a good pickaxe OR you had an automated mob farm and you're using multi aura and want to save a good sword.

**Comment by eveythingistaken** [comment]
And you go afk while it is mining or killing.

**Comment by eveythingistaken** [comment]
I probably should've put that message in the description.. Oh well

**Comment by GummiBoat** [comment]
For Mining.. use AutoTool & AutoMine. If you want to do it AFK, then do it with tools that are not important.

For Killing.. damage the Mobs via fall-damage or sth. similar, to the point where they have ~1-2 health left. And then.. use your MLG Chuck Norris-SkillZ.
