### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by mastercoolguy** [Wurst-Imperium/Wurst-Client#720]
Is there a possibility, on something like factions, to have something that launches txt where your pointing? Also what about something that when your in someone's territory and you can't break blocks it allows you to break them and stay broken by not sending certain packets, then when you get in and take stuff, etc. you click something and it sends the packets. Also I know this is a duplicate but could someone explain this better,: if I wanted to make custom enchants the .enchant command with no op, is there a way in multiplayer? Also what about something that could target specific players and make them lag out. So say in certain servers if you leave during combat you die, so if I tagged someone (hit them once) and clicked a keybind it would crash there game, thus making them die?
Thanks for the help guys

**Comment by GummiBoat** [comment]
1) "that launches txt where your pointing" ... I have no clue what you're meaning.
2) You can "ghost-break" blocks with freecam. If it's out of your range and you break it, it's broken (client-side)
3) You can't enchant via commands without permissions. (Or their server/plugin is really bad.)
4) Well.. crashing other peoples game with Wurst.. I don't think this will ever be implemented.

And next time don't write multiple Issues in one. It can make things very confusing.

**Comment by mastercoolguy** [comment]
Sorry, autocorrect, I meant TNT, not txt. Also with ghost-breaking, your saying if I broke a block 20blocks away and then came out of free can the block would be actually broken?

**Comment by GummiBoat** [comment]
Since launching the TNT is caused by a plugin (i guess?) i don't think it will be implemented.. yet. If Wurst will support any specific mods.. we'll see in the future.

They are not ACTUALLY broken. They are, on your client. You can look through them, but you can't walk through it, You'll glitch back and forward by trying so.
