### ISSUE TITLE
Wurst Client Disable

### ISSUE THREAD

**Issue by MangoAssassin** [Wurst-Imperium/Wurst-Client#723]
So yeah, ive seen all of the other topics about having a button to disable the client, but I never read a full response. So is there one or no?

**Comment by GummiBoat** [comment]
No.

Duplicate of #19 .

**Comment by MangoAssassin** [comment]
Aw. Why not?

**Comment by OMGchangeMYusername** [comment]
well this would be useful but Alexander won't accept it anyway so yeah..
