### ISSUE TITLE
ChestEnhancer

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#724]
![](http://i.imgur.com/H0y6Sla.gif)

**Comment by OMGchangeMYusername** [comment]
ChestSorter sounds better :+1: 
i like the idea! let's wait for Alexander's opinion.

**Comment by OMGchangeMYusername** [comment]
oh it'd be nice if it was a button like [Sort] << [Steal] [Store]
and please make it bypass (by default),it wouldn't be the best if it was the same as current steal and store buttons.

**Comment by GummiBoat** [comment]
This is a hacked client, not Inventory Tweaks... I like the idea, but i don't think it's relevant to "sort" a chest in order to grief a server...

**Comment by OMGchangeMYusername** [comment]
oh i forgot wurst is mostly for griefing.. but still why the heck not?
it'd be just cooler if he added it and it won't be less cooler if he didn't!

**Comment by OMGchangeMYusername** [comment]
Wait again,Alexander has already accepted a bunch of suggestion that aren't necessarily used to "grief",just sayin' :P

**Comment by Nitrogen-Dioxide** [comment]
Like inventory tweaks haha.
