### ISSUE TITLE
Suggestion for a little pre-update?

### ISSUE THREAD

**Issue by Anonyluke** [Wurst-Imperium/Wurst-Client#725]
Please! Add the newest version of OptiFine (1.8.4)! That would be nicer than nice!
(and maybe a sexy Wurst-Cape? :3)
Stay cool, Love ya! <3 
-Luke

**Comment by GummiBoat** [comment]
Optifine has been rejected several times. A Wurst-Cape is already implemented, but only a few users have access to it. Duplicate of #2 .
