### ISSUE TITLE
Mineplex: Survival Games Players

### ISSUE THREAD

**Issue by GoGoJJTech** [Wurst-Imperium/Wurst-Client#726]
As the title states, Mineplex's survival games received an update where players remain on the ground when they die, meaning all forms of attacking focus on dead bodies. The hitboxes are small like baby pets, so maybe checking for player size would help ignore them? I'm not sure. Here's an example image of what happens when a player dies:

![](http://i.imgur.com/A01E70E.png)
![](http://i.imgur.com/tZpZOKU.png)

Tracers also show them, making finding people harder, as well as fightbot tracking them.

I've never gone through Minecraft source code, so I'm not sure how you'd be able to go around this issue, but best of luck Alex

**Comment by GummiBoat** [comment]
Should be possible, because the "dead" players are actually "sleeping" players. (Players have a really small hitbox, while in a bed.) For now just add everyone you kill to your friend list, by middle clicking their hitbox.

**Comment by GoGoJJTech** [comment]
Oh, sweet, didn't know about that trick lol
Thanks for the workaround.

**Comment by Alexander01998** [comment]
Looks to me like invisible baby chicken, in which case setting `Target` to `Players` would fix it.

**Comment by GoGoJJTech** [comment]
Target is set to players for combat already, it's just very strange how even if the player dies/quits a little hitbox remains. Setting them to friends works for now, but other people may be experiencing the same issue as I have been.

**Comment by GummiBoat** [comment]
@Alexander01998 trust me, that's a  hitbox from a "sleeping" player.

**Comment by GoGoJJTech** [comment]
Makes sense to do that. It does get a lot of hackers that way, which was smart of them to do for aesthetics and for preventing killaura.

**Comment by GummiBoat** [comment]
Yup, can confirm that now. 

![Image](http://puu.sh/hFFz7/e5a9758f34.png)
(Notice that the player is floating above the ground.)

And it probably works through sending specific packets. (Probably with the help from ProtocolLib).
```
protocolManager.createPacket(PacketType.Play.Server.BED, false);
```

So it should be possible to just ignore sleeping players in general (or make a button to enable/disable it).

**Comment by OMGchangeMYusername** [comment]
I actually thought of opening an issue regarding that idiot update,but i didn't have a clue about what they actually might be xD

**Comment by GoGoJJTech** [comment]
Them being NPCs actually explains why Alex's and Steves don't retain the correct skin when they die.

Anyhoozle, that's good to know that it is relatively simple.

**Comment by OMGchangeMYusername** [comment]
Anyhoozle? **O.o**

**Comment by GoGoJJTech** [comment]
Anyhoozle.
