### ISSUE TITLE
What music did you used on " Making Wurst v1.9 " video?

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#727]
https://www.youtube.com/watch?v=wQBe94ZXT6c

I want to know. 

And don't answer Darude Sandstorm. xD

**Comment by GlitchHead** [comment]
Then can be found here the name is in the desc two
https://www.youtube.com/watch?v=2HQaBWziYvY

**Comment by OMGchangeMYusername** [comment]
he said "And don't answer Darude Sandstorm." :/
oh and i'm interested too **=D**

**Comment by Alexander01998** [comment]
:musical_note: Gunnar Olsen - The End Is Near :musical_note:

**Comment by Nitrogen-Dioxide** [comment]
Thx @Alexander01998 !
And @GlitchHead , at least the video is broken for me xD.

**Comment by OMGchangeMYusername** [comment]
@nitrogen-dioxide  Me too O_o why?

**Comment by GummiBoat** [comment]
Because the "Publisher" is Vevo, and thus it's copyrighted and restricted in several countries, espacially in Germany, due to complications with the organization "GEMA". If you want to access these videos in your land, use proxies or browser extensions like "ProxFlow" etc.

**Comment by OMGchangeMYusername** [comment]
Hotspot shield ELITE :+1:

**Comment by GlitchHead** [comment]
Or you can just use translate.google.com

**Comment by Nitrogen-Dioxide** [comment]
Brazil can't play this video too LOL. Well.. if you want to really watch this, use this chrome extension:
https://chrome.google.com/webstore/detail/hola-better-internet-engi/epbfmioobedknooiakdehepogalbgkng

**Comment by mcccs** [comment]
Easiest way. NO download.
https://www.youtube.com/watch?v=2HQaBWziYvY
convert it to
https://www.youtube.com/v/2HQaBWziYvY

**Comment by OMGchangeMYusername** [comment]
That didn't work either..
