### ISSUE TITLE
FightBot/multiwaura/killaura/legit Ignore armor stands.

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#728]
http://spigotleaks.gq/index.php?resources/armorstands.9/

This plugin makes armor stands, and any killaura related mod try to hit it ( in all/mob mode).

Is there any way to ignore them?

**Comment by GummiBoat** [comment]
Well, it should be possible to take out ArmorStands completely while registering the mobs to attack. (Because in the end, ArmorStands are "hostile" Mobs/Entitys.)

**Comment by OMGchangeMYusername** [comment]
ooooh are they armor stands??!!
i was always wondering why did killaura attack these!
but i thought it's the same as #81 where i can't do something about it xD
