### ISSUE TITLE
Random time between spam messages

### ISSUE THREAD

**Issue by Lakitu** [Wurst-Imperium/Wurst-Client#729]
There are servers using spam detectors detecting spam when the time between chat messages is exactly the same. For example: the time between chat messages is 7294 milliseconds, and there are four messages. It's easy to detect, because it's impossible for human spammers to make it exactly the same time. Then it's 100% sure for the server that the player is using a bot. :( So my idea was to add an option to make the time between messages random, with "no less than" and "no more than". It's important for the future of spamming (I think 😉).

**Comment by Nitrogen-Dioxide** [comment]
I noticed that too, and @Alexander01998 answered me.
So, WSpam is very flexible, remember the <random number/string/junk x > tag?
So... remember the .spammer delay too?

So again xD
if you do:

.spammer delay <random number 4>

It will create a random time! I think that this is one the best things you can do with wspam haha.

**Comment by Lakitu** [comment]
Nice, it's with commands, but that's enough to spam randomly. Thanks for your comment, I will close this issue because it's not needed to add this. ;)
