### ISSUE TITLE
Repository suggestion

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#730]
Hey.
Github is different than other sites,and its seach is different too..
so why don't you explain how the search works on Github?like you should put another line under that "please review the guidelines.." and make it link to this [Searching issues] (https://help.github.com/articles/searching-issues/) which i think most of people here should read!

i mean,i can easily find **any** issue because i actually read this ages ago,but a lot of others didn't.

e.g: i wanted to suggest Trajectories or any bow-related suggestion,i could look up words like bow/arrow
with 
![capture1](https://cloud.githubusercontent.com/assets/10786571/7535569/5fdbad38-f58f-11e4-9576-eb758a6c7ae3.PNG) ![capture2](https://cloud.githubusercontent.com/assets/10786571/7535596/9044c554-f58f-11e4-9d0e-89e6b2e87e82.PNG)

BAM! that brought me a nice 7-15 issues without having to surf the other 700 issues!

**Comment by GummiBoat** [comment]
If you read the Guidelines, you'll come to the section [Issues](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md#issues). The Video ( 3 Minutes of time, everyone should have) explains everything very simple and detailed.

**Comment by OMGchangeMYusername** [comment]
> If you read the Guidelines, you'll come to the section Issues. The Video ( 3 Minutes of time, everyone should have) explains everything very simple and detailed. 

no one will bother to watch a video if he just wants to report a bug or suggest a feature...
i'm saying Alexander should put something that makes sure people will actually **search** issues.
##### Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
##### Please make sure your issue has not been mentioned before,[Searching issues] (https://help.github.com/articles/searching-issues/).
that will surely decrease the number of duplicates.
and if he reject this anyway,it's ok..

**Comment by Alexander01998** [comment]
> Please review the guidelines for contributing to this repository.
> 
> Please make sure your issue has not been mentioned before,Searching issues.
> 
> that will surely decrease the number of duplicates.
> and if he reject this anyway,it's ok..

This message cannot be changed.

**Comment by OMGchangeMYusername** [comment]
oh.. i thought it's one of repository things like labels and stuff where you're able to add/remove anything..
well,i can understand if you rejected this now :wink:
