### ISSUE TITLE
"Silent Aimbot"

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#732]
A aim-bot that acts like killaura.
The normal aim-bot acts like the killauralegit,

**Comment by GummiBoat** [comment]
You mean something like the "Auto Bow Shooter" from Issue 731? Or did I just understood that one wrong?

**Comment by OMGchangeMYusername** [comment]
More of a Clickaimbot to me.

**Comment by OMGchangeMYusername** [comment]
Alexander you should really think of adding such things.. 
yes,Killaura is mostly enough but a lot of other clients add multiple choices,like ordinary Aimbot, Cilckaimbot,the age check,killaura timing thing...

**Comment by eveythingistaken** [comment]
^^ I absolutely agree

**Comment by Nitrogen-Dioxide** [comment]
@GummiBoat Auto bow shooter is diferent. It auto shots for you, without your permission.

What I mean. Is something that when you release the bow. It sends a packet of "shooting this way". So, not changing the direction of view.

**Comment by GummiBoat** [comment]
That sounds funny, but I guess the normal version is enough... and additional it sounds ... really obvious. I mean.. if someone looks away from me and suddenly an arrow hits me from his direction... you know...

**Comment by OMGchangeMYusername** [comment]
wait a sec did you mean "Silent Bowaimbot"?
i was 99% sure you meant something like Clickaimbot,it doesn't change your view but when you hit,it automatically hits the player in your range.
anyone could think of that when you say "Silent aimbot"....
