### ISSUE TITLE
Can't fly on servers

### ISSUE THREAD

**Issue by yycyyc** [Wurst-Imperium/Wurst-Client#733]
Why won't some mods work on servers?
And why can't you fly on servers
I just keep returning to ground when I try to fly..
Works perfectly on singleplayer though

**Comment by TekkitCommando** [comment]
It's because fly is not usually enabled on servers and no cheat plus makes it worse

**Comment by yycyyc** [comment]
Is there any way to use it?
I saw someone flying in the server..how was he doing it?

**Comment by GummiBoat** [comment]
He probably had the permissions to do so. There is currently no bypass for NCP(NoCheat+), so you just can fly on servers where you have the permissions or that don't have NCP.
