### ISSUE TITLE
IpFinder

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#737]
Find peoples ip's! :D

**Comment by OMGchangeMYusername** [comment]
isn't that illegal?

**Comment by eveythingistaken** [comment]
is it?

**Comment by GoGoJJTech** [comment]
Sounds like it. That's a violation of information really, especially since you specifically aren't supposed to access it.

**Comment by Alexander01998** [comment]
As far as I know, only the server can do that.
