### ISSUE TITLE
.Potion Command

### ISSUE THREAD

**Issue by Huanjohn** [Wurst-Imperium/Wurst-Client#738]
A possible suggestion might be to add a command (like .potion) that would give a potion being held all potion effects.  An idea might be something like:

ItemStack currentItem = Minecraft.getMinecraft().thePlayer.inventory.getCurrentItem();
for(int x = 1; x <= 23; x++) {
PotionEffect effect = new PotionEffect(x, 99999, 127);
currentItem.setTagCompound(effect.writeCustomPotionEffectToNBT(currentItem.getTagCompound()));
}

**Comment by GoGoJJTech** [comment]
That would give you poison, instant damage, weakness and blindness as well. You'd have to add exceptions inside of the for those values as well.

**Comment by Alexander01998** [comment]
As I said in #672, potion effects of potions cannot be changed.
Your code example throws an exception, as it is only intended for applying potion effects to entities.
