### ISSUE TITLE
Projektiles

### ISSUE THREAD

**Issue by Swiftb0y** [Wurst-Imperium/Wurst-Client#740]
Please implement "Projectiles" like in Huzuni, Wolfram or every other client.

**Comment by GummiBoat** [comment]
Duplicate: #168 

Please consider reading the [guidelines to contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) next time and search this repository before opening a new issue.
![Image](https://camo.githubusercontent.com/9b7cbf889d96d03740a87192086701362872e8fd/687474703a2f2f7075752e73682f68433146632f316166313261643339642e706e67)

**Comment by Swiftb0y** [comment]
Sry, my first time on GitHub.
