### ISSUE TITLE
What does the arena brawl mod have it in it

### ISSUE THREAD

**Issue by LOOTER4** [Wurst-Imperium/Wurst-Client#741]

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Read the description in-game.
"A collection of mods that make Arena Brawl on Hypixel.net a lot easier"

**Comment by GummiBoat** [comment]
1) It renders boxes around targets. (Blocks, Entitys, "Totems")
2) It has built in Auto-Sprint & BunnyHop.
3) It looks at players and attacks them if they are in range.
...and much more.

If you are able to read through Java-Code and want a complete overview , visit [this](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/mods/ArenaBrawlMod.java) Page.

**Comment by Alexander01998** [comment]
There is also a page for it on the old Wurst wiki: https://old.wurst-client.tk/wiki/mods/arenabrawl

**Comment by tykodey** [comment]
hmm. mine does not seem to be working in game. it works in the lobby but not the game? can u helo me plz
