### ISSUE TITLE
AutoFight Monster target

### ISSUE THREAD

**Issue by tony8894** [Wurst-Imperium/Wurst-Client#742]
When I use auto fight set to monsters It attacks cows and other non monsters

**Comment by Alexander01998** [comment]
1. It's called FightBot

2. Disconfirmed.  
![image](https://cloud.githubusercontent.com/assets/10100202/7556292/10078fce-f76b-11e4-8812-020499c2fc71.png)

**Comment by GummiBoat** [comment]
There are multiple options for attacking entitys. 
* All 
* Mobs (Hostile & Friendly) 
* Monsters (Hostile) 
* Animals (Friendly) 
* Players.

You probably chose the wrong one (accidently).

**Comment by tony8894** [comment]
No I did not choose the wrong One I kept seeing it hit cows and more so i checked again and its still doing it. There is nothing wrong on my part

**Comment by GummiBoat** [comment]
Can you please...

a)... try to reconstruct your problem and write a step-by-step?
or
b)... make a screenshot while the problem is occuring.
