### ISSUE TITLE
Implementing old wiki into the new one

### ISSUE THREAD

**Issue by GummiBoat** [Wurst-Imperium/Wurst-Client#743]
The [old wiki](https://old.wurst-client.tk/wiki) isn't linked anywhere (atleast I can't find it.)

So I would suggest, giving it a polish-up and adding it to the new one, in more stylish. Also there are missing some mods and the linking to similar mods isn't correct.

Additionally I would really like to help with that too. I just need to know, how.

**Comment by Alexander01998** [comment]
> The old wiki isn't linked anywhere (atleast I can't find it.)
> 
> So I would suggest, giving it a polish-up and adding it to the new one, in more stylish. Also there are missing some mods and the linking to similar mods isn't correct.

It is hidden on purpose. Even before it was replaced with the wiki on GitHub, a lot of the mods & commands were missing and a lot of the information was outdated.

> Additionally I would really like to help with that too. I just need to know, how.

You can [clone the wiki, make your changes](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/), create a patch and e-mail it to me. That's how git collaboration worked before GitHub existed and it is still the only way to collaborate on a GitHub wiki.
(Except for allowing anyone to edit the wiki, which a lot of people used to mess it up.)

**Comment by GummiBoat** [comment]
@Alexander01998 How do I create a patch? I tried to Sync the Commit, but I don't have permissions. (I guess that's what you meant with allowing anyone to edit the wiki.)

So I googled, but the only thing were pull-requests, and these are not enabled for wiki-changes.

I really am confused right now...

**Comment by Alexander01998** [comment]
The new wiki, easier than ever: https://www.wurst-client.tk/news/2015-06-21-Wurst-Wiki-v3/

**Comment by GummiBoat** [comment]
Edit redirects to an incorrect github Page.
![](http://puu.sh/ix5On/a188dfd3b4.jpg)

**Comment by Alexander01998** [comment]
Strange. That worked fine just a couple of minutes ago.

**Comment by Alexander01998** [comment]
Oh wait, I see what's going wrong.

**Comment by Alexander01998** [comment]
Fixed.

**Comment by OMGchangeMYusername** [comment]
Why don't you put a little description for every mod in the mods list?
i can do that if it's ok,i'm bored right now so yeah..

**Comment by GummiBoat** [comment]
That's what I'm doing right now, view the Pull Request on wurst-client.tk, i currently am only working on the commands. Feel free to contribute to the mods.

**Comment by OMGchangeMYusername** [comment]
is it ok?
