### ISSUE TITLE
FightBot Monster Target

### ISSUE THREAD

**Issue by Tendersexpartner** [Wurst-Imperium/Wurst-Client#744]
So I play on this server that has a bug to were when you hit a mob or player a cow or passive mob spawns above your head for a split second. 

I set the fightbot target thing to "monsters" not anything just monsters. Then I used it to kill endermen. Everytime it killed an endermen it looked right up to kill the cow or passive mob. Every time It kills an endermen it does this.

I do Not know how to fix this but as far as I can see I put the right setting on it "monsters" not "mobs" not "passive" and not "Players"

**Comment by GummiBoat** [comment]
Then it's not a cow. FightBot isn't attacking what it's not supposed to attack. (And why is a server spawning a mob when you're killing one? o.O)

**Comment by Alexander01998** [comment]
Duplicate: #742
