### ISSUE TITLE
Alex, is this you?

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#745]
http://gyazo.com/42d1a626b014296d85554cc6cf0edd23
![42d1a626b014296d85554cc6cf0edd23](https://cloud.githubusercontent.com/assets/11602755/7556985/50d07a90-f73c-11e4-9663-087bcc0d40b0.png)

Thread:
https://leakforums.org/thread-528276&page=2

If that isn't you, then what a bastard they are.

**Comment by Alexander01998** [comment]
That's just a faker who wants attention.

This is me: https://leakforums.org/-437459
