### ISSUE TITLE
Better regen

### ISSUE THREAD

**Issue by Tan74** [Wurst-Imperium/Wurst-Client#746]
Could you please make it so regen mod works in mid air it's pretty annoying and embarrassing when you say oh I never die but accidently go in air and then die...

**Comment by eveythingistaken** [comment]
It does work in air.

**Comment by Tan74** [comment]
no, no it doesn't

**Comment by GummiBoat** [comment]
Well, one of the requirements to activate the regeneration is that the player has to be on the ground. I don't think Alexander would've done this, if it wouldn't be necessary.

**Comment by Alexander01998** [comment]
Using Regen in mid-air would instantly kick you for "Flying is not enabled on this server".

**Comment by Tan74** [comment]
Ohhh
