### ISSUE TITLE
RemoteView

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#747]
Whenever I turn on RemoveView, it makes it so I face the same direction the target is facing.
For example:
Target is facing West, I'm facing South.
I turn RemoteView on.
I'm viewing the target's field of view in the direction of West.
When I turn it off, I'm facing West. (I was facing South before I turned RemoteView on)
And yes, I have searched if there was an issue already, but I didn't find one.

**Comment by GoGoJJTech** [comment]
That has been happening to me since I began using Wurst, and I never thought of it as an issue really. Although it is annoying, fixing it would make it a lot more subtle.
