### ISSUE TITLE
Display name changer

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#748]
can you make an option under the "password" while adding or editing an alt that says "display name" or something similar?
i mean,it only changes the client side name or whatever it's called..
e.g i'm using an alt "alt1" and i've put display name to "alt2",when i kill someone everyone will see "someone is killed by alt1",however in my minecraft it says "someone is killed by alt2".
i think it's easy to understand but i just don't know the best words to describe it.

**Comment by Alexander01998** [comment]
I prefer adding a command for this:
```shell
.alias <name> <fakename>
```

**Comment by OMGchangeMYusername** [comment]
just thought about it,if that works with the original name as well,it'd solve most of the recording issues!

**Comment by GummiBoat** [comment]
@OMGchangeMYusername That exists already (NameProtect).

But I prefer changing the Name ingame via command.. Maybe it's possible to change other players names with that too?

**Comment by OMGchangeMYusername** [comment]
Alexander has already said it'll be a command O.o
The NameProtect isn't a solution at all.. just what kind of server will have everyone named Player1 Player2 Player3 and on.. this would be tons better :)
oh it'll be even more interesting to change other players' names :+1:

**Comment by WurstMan** [comment]
yea like nameprotect in metro

**Comment by Alexander01998** [comment]
Note to self: add color support (suggested in #1529).
