### ISSUE TITLE
Nametag's Larger? Nametag Scale?

### ISSUE THREAD

**Issue by Risen01** [Wurst-Imperium/Wurst-Client#749]
I would the option to be able to enhance nametags so when your far from a player you can easily see there nametag before they can see yours. Hopefully you understand?
![2015-05-11_17 03 37](https://cloud.githubusercontent.com/assets/12401706/7576086/efe6ed26-f7ff-11e4-9400-035912c57ec1.png)

**Comment by Nitrogen-Dioxide** [comment]
Already implemented :package:

**Comment by GummiBoat** [comment]
The Mod is called "NameTags". Should be big enough.

![](http://puu.sh/hJWUL/8841f808fc.png)
