### ISSUE TITLE
AutoPVPBot

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#750]
Yes, I know there are plenty of PVP hacks in this client, but they don't automatically. I want it to detect players coming and killaura them, then if it detects low on health it pulls out of the fight. If low on food it will autoeat. It also uses autoarmor and autosword. Also when it strikes one player it keeps on that player and not switch over to another player until the player it was originally following is killed.

**Comment by GummiBoat** [comment]
How about you just activate all the mentioned features above at the same time? 

>I want it to detect players coming and killaura them

Use Protect or a regular Killaura.

> low on health it pulls out of the fight

That could be useful, I agree, but you instead you could a) look out for your health or  b) regen.

>  If low on food it will autoeat.  It also uses autoarmor and autosword.

Then just activate those mods.

> Also when it strikes one player it keeps on that player and not switch over to another player until the player it was originally following is killed.

You should open a new Issue for that one, could be useful.

**Comment by OMGchangeMYusername** [comment]
What about a killstealer mode for Killaura? i found a server where tons of people fight,and you're lucky if you get a clean kill. So what about making Killaura prioritize the lowest players on health?

**Comment by Alexander01998** [comment]
Already implemented. (FightBot)

**Comment by scriptinator** [comment]
FightBot doesn't do that

**Comment by scriptinator** [comment]
It just attacks nearest players
