### ISSUE TITLE
Killaura Glitch

### ISSUE THREAD

**Issue by ZappyDappy** [Wurst-Imperium/Wurst-Client#756]
When i use killaura, i always get stuck to the ground and facing upwards. I always cant run when im being chased sometimes and die. Please help. Killaura would be quite useless with this bug.

**Comment by ZappyDappy** [comment]
It only happens when playing on multiplayer servers :3

**Comment by GummiBoat** [comment]
Then you're playing on a NoCheat+ Server. Enable YesCheat+ and the problem should be solved. Or use KillAuraLegit.
