### ISSUE TITLE
i accidenly delete my keybinds 

### ISSUE THREAD

**Issue by nowifiidie** [Wurst-Imperium/Wurst-Client#757]
who can help me or leave the commands here i need the gui menu pls fast reply if u know pls

**Comment by GummiBoat** [comment]
ESC -> WURST Options -> Keybinds -> Add -> Change the key first ( to Y or sth. like that.) -> Command: .t ClickGUI.

Next time please search the issues for your matter.
Duplicate: #545

**Comment by OMGchangeMYusername** [comment]
Gummi :+1:
