### ISSUE TITLE
Bug Reporting

### ISSUE THREAD

**Issue by GoGoJJTech** [Wurst-Imperium/Wurst-Client#759]
Whenever I encounter a bug, I report it, but clicking back to game or pressing esc does literally nothing. I stay stuck and get kicked for being afk.

**Comment by Alexander01998** [comment]
The <kbd>Report Bug</kbd> button will bring you back to the game once it's done sending the bug report (which might take a couple seconds).
The <kbd>Back to Game</kbd> button is for going back without sending a bug report.

**Comment by GoGoJJTech** [comment]
Well I do report the bug, but the menu doesn't go anywhere.

**Comment by GoGoJJTech** [comment]
Literally just happened again, the menu is still there and I think I sent 2 reports accidentally.
It *could* have to do with autorespawn since I have that on, but that's just a thought. I have absolutely no clue. Might require more testing.

**Comment by Alexander01998** [comment]
Wurst tries to disable the thing that caused the bug so you can continue playing, but there is no way to guarantee that this will always work.

To find out if your report was sent correctly, you can look it up at [wurst-client.tk/error-reports](https://www.wurst-client.tk/error-reports/).
