### ISSUE TITLE
Force OP

### ISSUE THREAD

**Issue by Afrigo** [Wurst-Imperium/Wurst-Client#760]
For some reason the Force OP is not working for me. I have a macbook air. PLS HELP!

**Comment by Alexander01998** [comment]
We have had a similar case about a month ago. This might help you:

![](https://cloud.githubusercontent.com/assets/10100202/7282607/62dfc2c2-e931-11e4-8181-ba33f477849f.jpg)

**Comment by OMGchangeMYusername** [comment]
so,is this solved or what?

**Comment by trollmad3** [comment]
Yes this is solved.

**Comment by OMGchangeMYusername** [comment]
@trollmad3 how did you know?

**Comment by Alexander01998** [comment]
> so,is this solved or what?

There has been no reply after 5 days, so I assume that it is solved.
