### ISSUE TITLE
BookHack

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#763]
Bookhack doesn't work for me reinstalled 2 times already
Computer : Toshiba Satellite C55-B5200
OS : Windows 8.1

**Comment by Alexander01998** [comment]
We have had a similar case about a month ago. This might help you:

![](https://cloud.githubusercontent.com/assets/10100202/7282607/62dfc2c2-e931-11e4-8181-ba33f477849f.jpg)

**Comment by failvenom** [comment]
No. Litteraly I did everything correctly. Text. Title. Command. Sign. Done
Clicked it nothing happens

**Comment by Alexander01998** [comment]
> No. Litteraly I did everything correctly.

You are either playing on a 1.7 server or are doing something wrong.

> Text. Title. Command. Sign. Done

The correct order would be **text > sign > title > command > done**.

> Clicked it nothing happens

For commands like `/op`, the link must be **clicked by an admin**.

**Comment by failvenom** [comment]
I played on a 1.8 server 
I used a command everyone can do.
Result?
```
Nothing
```

**Comment by scriptinator** [comment]
post a video?

**Comment by failvenom** [comment]
ok.

**Comment by failvenom** [comment]
wat. it worked rn.

**Comment by failvenom** [comment]
Nope
