### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#764]
Presses buttons for you! Such as walk , go to the right, Spam keys! , or just hit keybinds :P
Commands
.record - Starts recording the macro
.stoprecord - Stops recording the macro

Once done it will prompt you to select a key and have it activate once or just repeat until clicked again

**Comment by Alexander01998** [comment]
Already implemented through WSPAM.
Recording would be hard to implement and would leave weird delays (such as the 3 seconds it takes to type `.stoprecord`).
