### ISSUE TITLE
How to look legit and bypass staff "eyes".

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Wurst-Imperium/Wurst-Client#765]
Recently I made a tutorial on leak forums, but I'l share here for "free" \o/.

You will need:

-Trigger Bot
-AutoMine

In The kill-aura/trigger-bot configs set to:
kill-aura speed: 10.3
kill-aura range: 2.4

Now, set an key-bind for triggerbot. (I use C for triggerbot)

Now, enable AutoMine. In wurst it is .t AutoMine.

The deal is that, when you have the AutoMine mod enabled, everytime you face a block. You will send a "I'm clicking" packet to the server.
It looks very veeery realistic because you can enable and disable triggerbot. ( I'm playing guild craft pvp and they don't even thought that I'm using wurst, even with ~5 admins on :trollface:  )

Rules for better "performance" :
Keep jumping! You will have a LOT of criticals hit with that!
Keep jumping more! Other players will find too hard to hit you 
If you are lazy to jump, enable bunnyhop xD.
If it is an soup-pvp server, set a key-bind for auto walk, so -> enable auto walk -> reorganize the pots -> disable it -> keep fighting again.
If someone say that you are hacking, type the command -> .say .legit 

Rules to don't be caught:
NEVER KEEP TRIGGERBOT ENABLED ALL THE TIME. Because it will look obvious. :cakeyplz: Specially when you are drinking or eating something xD.
DON'T USE "OBVIOUS HACKS". Such as antikb, killaura, fightbot.
PAY ATTENTION WHEN USING CLIENT COMMANDS. Check if the . is really a dot, or anything.

With this method, it is almost impossible to guess that you are hacking.

Thanks for reading and good haxing.

**Comment by Alexander01998** [comment]
Issues are not meant for sharing tutorials. That is the purpose of the Wiki.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 Sorry :/ so it can be added to the wiki?

**Comment by Alexander01998** [comment]
> Sorry :/ so it can be added to the wiki?

Yes, but please fix the formatting first (e.g. bold text instead of caps, code blocks for commands, etc.).
