### ISSUE TITLE
Making/Editing hacked clients

### ISSUE THREAD

**Issue by bazzz1512** [Wurst-Imperium/Wurst-Client#767]
How can you start making your own hacked clients/editing Wurst?
It would be really cool if I could edit Wurst and make my own hacked client.
I really like the wurst client and would love to know how it's built etc.

**Comment by OMGchangeMYusername** [comment]
This is the featured tutorial on [wizardhax] (http://www.wizardhax.com/how-to-code-a-minecraft-hacked-client/). It's a nice tutorial but you need a little more than that to code a client by your own.

**Comment by pokeball99** [comment]
for the first question see https://github.com/Wurst-Imperium/Wurst-Client/issues/510

**Comment by Alexander01998** [comment]
> How can you start making your own hacked clients

:arrow_down: 

> This is the featured tutorial on [wizardhax](http://www.wizardhax.com/how-to-code-a-minecraft-hacked-client/).

---

> editing Wurst?

https://github.com/Wurst-Imperium/Wurst-Client/wiki/Debugging-Wurst-in-Eclipse
