### ISSUE TITLE
World Downloader Function

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#770]
There is a world Downloader for 1.8 and it does not use forge. I think that a world Downloader should be in wurst

**Comment by Alexander01998** [comment]
Duplicate: #67

**Comment by TheEpicCooldeal** [comment]
Have you removed the world downloader?

**Comment by OMGchangeMYusername** [comment]
@TheEpicCooldeal It has the "rejected" label so it wasn't even implemented..

**Comment by OMGchangeMYusername** [comment]
@TheEpicCooldeal It has the "rejected" label so it wasn't even implemented..
