### ISSUE TITLE
How to submit a video

### ISSUE THREAD

**Issue by Brincz** [Wurst-Imperium/Wurst-Client#771]
How do I submit a video of me griefing a server?

**Comment by pokeball99** [comment]
Umm....I don't think Alex wants u to submit a video to a Open suorce coding site......

**Comment by OMGchangeMYusername** [comment]
You must be talking about the Wurst cape giveaway? it's already finished and the winners have been announced. if you didn't mean the giveaway,i don't recall him asking you to submit a video but well... you can use [Fraps] (http://www.fraps.com/) to record,a lot of people say it's the best recording software for minecraft.
