### ISSUE TITLE
AltManage Crash

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#772]
When spamming the "Use alt" Button if 3-50 alts don't work the client crahses

**Comment by OMGchangeMYusername** [comment]
i've tried spamming it with 15 alts (that are not working) and it never crashed for me..
> When spamming the "Use alt" Button if 3-50 alts don't work the client crahses

well,if it really crashed for you i'm pretty sure it's because of "spamming" the button.. go cool and never crash :stuck_out_tongue:.

**Comment by failvenom** [comment]
Ive spammed the button. I crashed

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.

**Comment by Alexander01998** [comment]
This bug has now been reported properly in #855.
