### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#773]
Make keybinds useable in GUIs

**Comment by OMGchangeMYusername** [comment]
explain it a little more,did you mean you want it usable in the ClickGUI? or everywhere in minecraft?

**Comment by failvenom** [comment]
Everywhere else because in like big servers with minigames and a game selector in the first slot and i have some type of aura on it clicks it i either have to close my minecraft or spam esc and another slot button

**Comment by OMGchangeMYusername** [comment]
@failvenom lol that happens to me too xD
i would suggest to disable any fighting thing such as Killaura and Triggerbot if the entity you're hitting would open up something.
although idk if it can be that simple..

**Comment by failvenom** [comment]
Simple just make keybinds useable  in like chests and stuff :P

**Comment by OMGchangeMYusername** [comment]
thought it'd be rejected,but what do you recommend to do when this happens?
it's not happening to me anymore since i've got used to it but it surely made me suffer at the past xD

**Comment by Alexander01998** [comment]
> what do you recommend to do when this happens?

See #127.
