### ISSUE TITLE
Parcour cheat

### ISSUE THREAD

**Issue by XJetfireX** [Wurst-Imperium/Wurst-Client#776]
Make cheat parkour, which can help in the passage of parkour.
Example: You run, and automatically jump from the edge of the block.
(Often the problem arises when you do not have time/not on time jump and fall.)
I think, this is useful cheat for fans of parcour as I )))

**Comment by OMGchangeMYusername** [comment]
This has been suggested before #522.
Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by XJetfireX** [comment]
Oh, sorry. I'm newbie and just wrote this idea :) I didn't know this idea already wrote
