### ISSUE TITLE
Instantbunker

### ISSUE THREAD

**Issue by bazzz1512** [Wurst-Imperium/Wurst-Client#780]
I found out that if you want to make an instant bunker it doesn't has a floor.
If the instantbunker mod would have a floor it would be great for skywars if you get knocked off to make an instant bunker, so you still survive. 

Edit : or make an path from the nearest steady block to make an bunker from there.

**Comment by eveythingistaken** [comment]
It can't place blocks in mid-air, can it?

**Comment by OMGchangeMYusername** [comment]
@eveythingistaken nope,it can't.

**Comment by bazzz1512** [comment]
I tried in single player to do it, and it worked in single player

**Comment by OMGchangeMYusername** [comment]
@bazzz1512 There is something called NoCheat+, this is a plugin that servers use against hackers.
for example,if you flew when you shouldn't (survival mode or something) it pulls you back and it never let's you fly. same thing with building,you can't build in mid-air even in singleplayer without hacks..
There are many other hacks are prevented by NCP (NoCheat+) such as Nuker,Timer,Regen,Nofall.

**Comment by OMGchangeMYusername** [comment]
hope you got the idea :)

**Comment by Alexander01998** [comment]
All servers prevent you from placing blocks in mid-air, not just the NoCheat+ ones.
