### ISSUE TITLE
Optifine alternative?

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#782]
http://www.curse.com/mc-mods/minecraft/fpsplus-lagfixes

Please

**Comment by OMGchangeMYusername** [comment]
I think Alex has said Wurst overwrites the same classes as forge,dunno if that applies for 1.8 too,but it looks good! that'd be awesome if it can be added :+1:

**Comment by OMGchangeMYusername** [comment]
Wait that's only for 1.7.10 and less :/
make sure it is even 1.8 before you suggest it...
