### ISSUE TITLE
Jump'n'Run

### ISSUE THREAD

**Issue by tkoesti** [Wurst-Imperium/Wurst-Client#783]
Is there a possibility to do sth. like a Jump'n'Run hack? I haven't seen one yet, but maybe because it just isn't possible :D

**Comment by OMGchangeMYusername** [comment]
ok you have to explain this more detailed,like i can't even guess what you meant by Jump'n'Run?
is it a minigame? if you haven't seen this hack before then explaining it is very important.

**Comment by mcccs** [comment]
it is TOO DİFFİCULT to make.

**Comment by OMGchangeMYusername** [comment]
ok @mcccs you can explain it instead,it seems you know it already so why not describe it?

**Comment by Alexander01998** [comment]
See #338
