### ISSUE TITLE
Macro

### ISSUE THREAD

**Issue by bazzz1512** [Wurst-Imperium/Wurst-Client#786]
Is it possible to introduce a macro mod in Wurst?
It would be pretty cool for a prison server to do after a while it automatticly does /sell etc.

**Comment by pokeball99** [comment]
Already implemented

**Comment by bazzz1512** [comment]
Where?

**Comment by OMGchangeMYusername** [comment]
not sure what you meant,but if you talk about keybinds that excute normal commands it's already implemented.
