### ISSUE TITLE
Wurst need a update. (BIGGEST UPDATES) Hardcore too

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#790]
Ok, I know the 2.0 version will come soon but you have to change some things.

1- Wurst need a NEW THEME. 
 (The Wust's theme is really awful. People will think its not good. But its perfect client. I just downloaded KİLO hacked client. Its good and its theme is perfect. Wurst is better than that but Wurst's theme is the original Minecraft texture. (I mean the main menu in minecraft) If you change this. It'll be perfect.)

2- Delete ClickGUI or add GUI in game.
(I mean when you play in a server or a map , you don't have to press clickgui button. It'll be on the top. You are going to select mods with arrow keys. I guess I saw that mod in WeepCraft?!?)

3- Wurst need a IRC (Chat Talk)
(The new users of "Wurst" (noobs :smile:) don't know how to start. The Wurst users will chat in single player or multi player. They will help and chat.

4- Add a GUIDE in hacked client. 
(like this... press the  "Z" and the message box or a form will come up. You can do a TUTORIAL. a tutorial map for ALL MODS. The tutorial will teach them how to use mods. I CAN HELP YOU WITH THIS. IF YOU WANT A REDSTONER.)

5- Wurst premium.
(The Donators will have a SPECIAL version of Wurst. More mods , more professional help , faster)

6- Add a button and call it Arena Fighter to Main Menu.
(I'm doing a pvp arena. It has a story and a lot of things. It'll be a multi and single map. I designed it for MinePlex but it'll be better in Wurst. The Alpha verison will only have story mode (single player) and shop. The real version will be playable in MultiPlayer and Free Mode buttons.) The map is HUGE.

7- Daily prizes.
(add a button in GUI. "Daily Spin" and it'll give you Special mods.)

**Comment by TekkitCommando** [comment]
One suggestion at a time is expected :smile: and an IRC will be here soon once i have the time again :)

**Comment by TekkitCommando** [comment]
I have higher priorities IRL and on github which makes it hard to update the irc code i had

**Comment by Orcunegeacar** [comment]
Lol. I just said thinks in my mind :smile:

**Comment by pokeball99** [comment]
i don't think alex would make anything to pay for,besides its open source....

**Comment by OMGchangeMYusername** [comment]
1. is Ok but still not really necessary.
2. that's called tabGUI,idk why do people like it..
3. it is confirmed,but i don't really think it's more necessary than some other features.
4. that is really dumb tbh.. because no one needs a tutrial on how to use Killaura and such..
5. he said he can't accept donations already...
6. idk what to actually say about this,but i guess this kind of suggestions won't be accepted.
7. totally useless,sorry,i'll say the same as pokeball.
don't take it personally please.

**Comment by TekkitCommando** [comment]
why make it pay to win sounds terrible

**Comment by Orcunegeacar** [comment]
Everything is free I know. in 7th suggestion I meant you will have a FREE chance to spin something. you don't have to give money

**Comment by bazzz1512** [comment]
I think 2,5 and 7 are not really good to implement into wurst. The other ideas would be really cool if we saw these things back in wurst.

**Comment by mcccs** [comment]
Good ones:
1
2b
3
BUT I
hate 5!
hate 7!

**Comment by Alexander01998** [comment]
> you have to change some things.

Please do not make demands like that. It sounds very disrespectful.

> why make it pay to win sounds terrible

^^^^^^^^

**Comment by OMGchangeMYusername** [comment]
I was about to comment "invalid :/" but when i saw TekkitCommando's reply,i was like he will call rude again and it will never end xD

**Comment by TekkitCommando** [comment]
This deserves invalid

**Comment by TekkitCommando** [comment]
It's a matter of what the issue is xD

**Comment by Orcunegeacar** [comment]
Lol
