### ISSUE TITLE
Macro and steal(Chest) glitch

### ISSUE THREAD

**Issue by bazzz1512** [Wurst-Imperium/Wurst-Client#791]
Macro:
When I try to bind a mouse key to a maco it doesn't works.
I play on a OPprison server where if I mine 1 block my invetory is full. So if I could bind /sell command to my mouse key it would automatticly sell when I mine, but you can't bind it to a mouse key

Steal :
When I try to steal all the items from a chest with the steal button, I get all the items and then some items bug in the chest again.

**Comment by GoGoJJTech** [comment]
Some servers have detection to see if you're taking out more than one item at a time. Hypixel is an example.
The way to get around that is to repetitively press the steal button, that way you get it really quickly but not all at once. Great for blocking dead and blitz survival.
Mineplex has a different custom nocheat service, and they don't check for that, which means you can use blink to teleport to the middle at the beginning and steal all of the chests, then wreck everyone at spawn. The reactions are great.

**Comment by GummiBoat** [comment]
I don't think you're supposed to add Macros to the essential Minecraft-Keys. But if you have a mouse with extra Keys to the side (No, not the 2 small ones, i mean like a gamer mouse with ~6-12 extra keys) you can bind them.

And for the Steal thing, just enable YesCheat+ and it will take the items out in a really fast way, that's not detected by Plugins like NoCheat+ and shit like that.
