### ISSUE TITLE
Add a donate store

### ISSUE THREAD

**Issue by trollmad3** [Wurst-Imperium/Wurst-Client#792]
On weepcraft there is a vip area where you can give money to it and you will get a cape or a hat or vip hack features that are awesome the KiLO has a feature where you can buy deadmau5 ears or a cape.
I think that when you donate 3 dollars you will get a wurst cape or something else.

**Comment by OMGchangeMYusername** [comment]
Seriously dude you've opened a lot of issued,don't you know that this has already been suggested? duplicate #56.
please,please search the issues next time.

**Comment by TekkitCommando** [comment]
This will probly be denied but thx for the suggestion

**Comment by OMGchangeMYusername** [comment]
@TekkitCommando may i ask why would you thank him for duplicating ~~shit~~?
like,this has been suggested several times!!
