### ISSUE TITLE
Arrow trejectory/ arrow esp PLZ ADD I NEED IS WE ALL DO

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#798]
The hack i would like to request is arrow trajectory. Arrow trajectory is where when a bow is pulled a line is drawn from the player to where the arrow will land. PLEASE add this i have used many hack clients but wurst is one of the only ones without arrow trajectory please add this in i ABSOLOUTLY love wurst and happy anniversary but really this is the only suggestion to add to wurst please do and thankyou

**Comment by bob80333** [comment]
Duplicate: #168 
Use the search function.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
There is also #310 #426 #532 #577 #580 as duplicates. Alex has already made the mod, but it isn't added just yet. *Please* view [This] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for the guidelines to contributing.
