### ISSUE TITLE
Recording Hack

### ISSUE THREAD

**Issue by MorganPlaysMC** [Wurst-Imperium/Wurst-Client#80]
This hack is where people cant see your username on TAB and they cant see your nametag when they look at you.

**Comment by MorganPlaysMC** [comment]
This would be really useful so if somebody on a server they record you tell admin or whatever they wont know your username to ban you

**Comment by Alexander01998** [comment]
You cannot join any server without sending them your username. You can send a fake name on cracked servers (see AltManager), but that's it.

**Comment by MorganPlaysMC** [comment]
Ok
