### ISSUE TITLE
Magnet

### ISSUE THREAD

**Issue by 8bitPotato** [Wurst-Imperium/Wurst-Client#800]
In drop parties everyone gets all the good stuff and u dont. so with magnet, all the items in a chosen radius get sucked towards you and you can get all the stuff! This looks like a good idea.
But the radius cannot be bigger than 5 of 10 blocks. I hope this becomes a feature in wurst.

**Comment by OMGchangeMYusername** [comment]
> In a nutshell,Minecraft doesn't work that way.

^^^^ #144
