### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#803]
I dont know. Fullscreen and un-fullscreen quickly
this happens. Wears off when window size is changed or moved

![](http://puu.sh/hVSAc/aba290e162.png)

**Comment by Alexander01998** [comment]
Works fine for me. Do you have AutoMaximize enabled?

**Comment by pokeball99** [comment]
i can confirm this bug too @Alexander01998 , i forget how it happens exactly works,but it happens often

**Comment by WurstContributer** [comment]
Yes.

**Comment by Whatisthisname** [comment]
I can also confirm.

**Comment by OMGchangeMYusername** [comment]
meh.. it happened to me before but it never affected anything,it disappears after several tries of maximizing and minimizing.
