### ISSUE TITLE
Insant Item picking up

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#804]
Pick up items instantly! You dont have to reach down and get them anymore :D

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
So what you're trying to say is that if you're a block higher than the ground the item is sitting on it will suck up the item in a way?

**Comment by failvenom** [comment]
No it picks the item up instantly

**Comment by TigrexHD** [comment]
I think he mean: if an item is dropped you have to wait a little delay and with wurst you can collect the items instant

**Comment by GummiBoat** [comment]
I don't think it's possible, because Items have a default pickup-delay, that's generated when you drop the item.

(Btw, Items are "Entitys", so in order to display them on the ground, they have to be summoned. Example: "/summon Item ~ ~1 ~ {Item:{id:stone,Count:1}}" This summons one Stone-Item at your position.)

Dropped Items can have these NBT-Tags (Click on the image to resize it to be readable):
![](http://puu.sh/hWvDk/14d34ecd2c.png)

**Comment by Alexander01998** [comment]
> I don't think it's possible, because Items have a default pickup-delay, that's generated when you drop the item.

The same effect can be achieved with Blink (by turning it on, walking to the item, standing there for a couple of seconds, walking away and then turning Blink off), so it should be possible.

**Comment by GummiBoat** [comment]
> standing there for a couple of seconds

Yeah, exactly because of that it shouldn't ... because you actually wait the time, blinking or not.

**Comment by Alexander01998** [comment]
> Yeah, exactly because of that it shouldn't ... because you actually wait the time, blinking or not.

You are not actually waiting there. Once you turn it off, Blink sends all the packets that you would send when waiting there, but all at once.

**Comment by GummiBoat** [comment]
Yeah, i know.. but if an Item is on ground for a specific time, you can pick it up instantly. As soon as the person throws the item, the entity gets the pickup delay tag. (or else you could pick up items, as soon as they throw it.) and if the counter gets to zero, you can just walk to it and pick it up. I don't know if you can modify that with a client or not, but i don't think so...

Well, you can try it, if you want to. I'm just very sceptic.
