### ISSUE TITLE
burn mod

### ISSUE THREAD

**Issue by Fart-sparklez** [Wurst-Imperium/Wurst-Client#805]
When you hold a flint and steel it uses the flint and steel to light fire in a customisable radius and extinguishes fire before you walk on it.

**Comment by bazzz1512** [comment]
I don't really see the point in this mod ...

**Comment by Alexander01998** [comment]
> When you hold a flint and steel it uses the flint and steel to light fire in a customisable radius

Can be done with AutoBuild.

> and extinguishes fire before you walk on it.

Can be done with Nuker.
