### ISSUE TITLE
Some Idea's

### ISSUE THREAD

**Issue by xeZx** [Wurst-Imperium/Wurst-Client#806]
1. A NBT-Editor:
 If u r pressing a key, a GUI opens in the specifying the item, and specifies the NBT-Tags. If you have entered the things you get the the item with the NBT-Tags, in the Game Mode. With this, u can make "OP" Sign, a Crasher Item, or a troll potion.

2. More NCP-Bypasses
 Some "Paid" Client have a NCP-Bypass Glide/Fly, Step, Speed, MultiAura, and FastHeal (2 Times) Like this: https://www.youtube.com/watch?v=gMVZhb3zQW8

Can u add this 2 Features to the client?

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
You can bypass NCP if you're in fire and you attempt to fly while on fire. I think you can fly when the fire goes away too.
It takes a bit of practice.
