### ISSUE TITLE
Block bypass

### ISSUE THREAD

**Issue by bazzz1512** [Wurst-Imperium/Wurst-Client#807]
Is it possible to bypass full blocks of air. I want to glitch through the barrier of a area where I'm not permitted to enter of Worldguard. Vclip doesn't work. So is there another way or can you guys make another way to glitch through this barrier. I'm above the barrier.

**Comment by Alexander01998** [comment]
It's easy to get behind a WorldGuard border, but you will always be teleported back before you can do anything there.
