### ISSUE TITLE
Switch targets in BowAimbot

### ISSUE THREAD

**Issue by hellothere21244** [Wurst-Imperium/Wurst-Client#809]
be able to switch between targets

**Comment by bazzz1512** [comment]
I think you need to add more information to this thread, but that id up to you. It isn't really clear what you want.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@hellothere21244 So what would the controls be by default? I'd think maybe < and > but whatever's fine.
@bazzz1512 He wants it so that any type of aimbot would be considered "manual" - So it's less likely for players to detect you constantly switching around. I personally think it's a great idea.

**Comment by hellothere21244** [comment]
exactly and so that in co-op games you dont look stupid shooting your own
team

**Comment by hellothere21244** [comment]
and yes thats what i was thinking or [ and ]

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 how about adding a slider to limit the targetting angle? should be pretty cool,coz Bowaimbot can be annoying sometimes,when i want to attack the entity in front of me,it aims for the thing behinds me instead (doh) <<"Github should have this,if you know what i mean :P"

**Comment by hellothere21244** [comment]
thats what im saying a manual aimbot that allows you to actully control
what your aiming at

**Comment by TabooBaboo** [comment]
Maybe a key to change the target?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
One more thing I forgot to say is there should be two modes (just a suggestion): nearest to player (1, selected by default) and nearest to cursor (2). It would really help.

**Comment by hellothere21244** [comment]
A key would be good for choosing

Also closed?
