### ISSUE TITLE
Player Finder

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#81]
can you please add an ESP like thing that can detect disguised players?
it works the same as prophunt ESP but with mobs.
like if a player disguised as a chicken or a villager,it renders a hitbox on them :smile: 
and by the way i didn't really know what to call it so deal with that name xD

**Comment by MorganPlaysMC** [comment]
OMGchangeMYusername they have that already its called MobESP

**Comment by MorganPlaysMC** [comment]
Leave a comment on my recording hack Opened issue Plz!

**Comment by Alexander01998** [comment]
> it works the same as prophunt ESP but with mobs

ProphuntESP works by searching fake mobs. If ProphuntESP can't detect these players, it means that there is no fake mob around them making them detectable.

**Comment by OMGchangeMYusername** [comment]
Dude this really dosen't work on mobs!
you might've made it so it detects fake "blocks" but it NEVER works on mobs!
if you need to confirm this play on mineplex sneaky assassins

**Comment by Alexander01998** [comment]
> you might've made it so it detects fake "blocks" but it NEVER works on mobs!

Players *hiding as blocks* always have fake mobs around them that make them detectable. If players *hide as mobs*, however, they don't need fake mobs because they already are a mob.

> if you need to confirm this play on mineplex sneaky assassins

I tested ProphuntESP on Mineplex when I made it. I have thoroughly analyzed their Block Hunt game and I know for sure that there is nothing detectable in players that hide as mobs.

**Comment by OMGchangeMYusername** [comment]
Well the label "rejected" is somehow brute, it should be "no sloution"

**Comment by Nitrogen-Dioxide** [comment]
@OMGchangeMYusername Think about a arrow (it is an entity too). One arrow is controlled normally by a bow (when you shot it). But there is another arrow that is controlled by a player ( it can fly crazily out there ). Now.. tell me how to know which arrow is fake, since the 2 are identical?

**Comment by OMGchangeMYusername** [comment]
@Nitrogen-Dioxide i'm well aware that it's not possible..
but the "rejected" makes it sound like it might be possible and not "not possible"
adding every label that fits and removing ones that don't,is necessary for this repo.
