### ISSUE TITLE
Freecam bug report

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#810]
if i activate freecam armour and tools from other are invisible ;(

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
I noticed this yesterday. I confirm.

**Comment by Nitrogen-Dioxide** [comment]
It is not a bug, it is only how freecam works.

**Comment by TheBoyIsHere** [comment]
if u use xray it will (meybe) show to u.
thx for reporting i sas think all time its something thet they try 2 fix
