### ISSUE TITLE
BowAimbot for PropHuntESP

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#811]
Make it so whenever it's toggled, BowAimbot will aim at props.
I tried using BowAimbot on animal mode (or whatever you'd call it) and it kept aiming at normal animals.

**Comment by GummiBoat** [comment]
Since when are Bows in PropHunt? o.O

BTW there's a thing called PropHuntESP already, which allows you to see non-solid Props.

And yes, indeed, BowAimbot is aiming for animals if you choose the animal-target option. If you change  the target to players, it will target players. Or is "Animal Mode" some new kind of shitty gamemode?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@GummiBoat 
1. Since ever. At least on the MinePlex server.
2. I know, I'm just saying I need the client not to aim at real animals, just props, or fake animals.
3. http://i.gyazo.com/abc4c786e0f04dd3b16b9176f70f04c7.png "Animal Mode"

**Comment by Alexander01998** [comment]
> 2. I know, I'm just saying I need the client not to aim at real animals, just props, or fake animals.

Players hiding as animals cannot be detected. See #81.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
It's got to somehow be possible, I saw it working on another 1.8 client.
![2c135c9a1a3d4a97c7047e1f7f959ec5](https://cloud.githubusercontent.com/assets/11602755/7829296/0a009a12-03f5-11e5-8db7-e6c6bcced48b.jpg)

**Comment by OMGchangeMYusername** [comment]
> It's got to somehow be possible, I saw it working on another 1.8 client.

You should put this comment on #81 :+1:

**Comment by GummiBoat** [comment]
@ICouldntUseMyRealNameSoIHaveThis Could you share the name of the Client?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@GummiBoat The name of it is Sinister. It's in Public Beta 4 so it's free to download. Also sorry for the late respone. To activate the PropHuntESP you have to enable "BlockHunt" in the MinePlex category.

**Comment by OMGchangeMYusername** [comment]
Oh it is Sinister?
@gummiboat you can take a look at this too #522.
it has nice features,but still most of public clients are better than it.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@OMGchangeMYusername I'm not gonna put that on #81 , I don't want to disturb that old issue. Hopefully Alex has already seen the screenshot, and/or maybe gave the client a test run to see if my point was valid.

**Comment by OMGchangeMYusername** [comment]
@icouldntusemyrealnamesoihavethis actually,if you want to prove something wrong,you should put it on the original issue,he might change it to "confimred" if he found out how.
> To activate the PropHuntESP you have to enable "BlockHunt" in the MinePlex category.

that sounds so plugins for me,some clients use plugins for certain gamemodes,it's be cool to see it in Wurst.
