### ISSUE TITLE
Hats

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#812]
Features: Puts item currently holding in any armor slot. Also drag any item into armor slot
Commands: .wear [Armorslot 1-4]

**Comment by Nitrogen-Dioxide** [comment]
I tried to make this mod based on the essentials /hat but it is not possible :/

**Comment by failvenom** [comment]
@Nitrogen-Dioxide Helios can spawn items into you armor slots.

**Comment by Nitrogen-Dioxide** [comment]
@failvenom Only client or server side?

**Comment by failvenom** [comment]
@Nitrogen-Dioxide Both

**Comment by Nitrogen-Dioxide** [comment]
@failvenom Can you send a print-screen of you in creative/survival (in a server) with a block in your head?
