### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by failvenom** [Wurst-Imperium/Wurst-Client#813]
How many confirmed mods have been completed?

**Comment by OMGchangeMYusername** [comment]
use this syntax: is:issue is:closed label:confirmed label:enhancement

**Comment by OMGchangeMYusername** [comment]
wait lol,i could simply [link] (https://github.com/Wurst-Imperium/Wurst-Client/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aconfirmed+label%3Aenhancement+is%3Aclosed+) it for you xD
