### ISSUE TITLE
I accidentally replaced the keybind to pull up the Gui with another keybind for a server.

### ISSUE THREAD

**Issue by iBeHacking** [Wurst-Imperium/Wurst-Client#814]
How do I put it back.

**Comment by bob80333** [comment]
Open up Wurst Options and go into the key binds menu.  Find the key you want to open the menu.  Press edit,  and change it to say '. t clickgui' (without the quotes)

**Comment by Sebandar** [comment]
but when i 
''Open up Wurst Options and go into the key binds menu. Find the key you want to open the menu. Press edit, and change it to say '. t clickgui' (without the quotes)'' is does this 
![2016-10-17_11 30 13](https://cloud.githubusercontent.com/assets/22884275/19432707/15095f84-945e-11e6-8f7a-7dec8b40c21b.png)
