### ISSUE TITLE
Packet Sniffer

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#815]
It would be nice if wurst had a packet sniffer built in.

**Comment by pokeball99** [comment]
packet sniffer?more info needed

**Comment by mcccs** [comment]
https://github.com/bencvt/McPacketSniffer
or
https://github.com/Yogu/minecraft-sniffer

**Comment by Alexander01998** [comment]
How would the user benefit from logging the packets?

**Comment by DigitalInsanity** [comment]
Hey Alexander,
packet sniffer/sender is usually used to abuse math mistakes on server. Example: you can buy meat for 10$ and sell it for 11$ with huge speed (automate this process with packet sniffer&sender) (of course this can be done throw WPE pro/RIPE)
Vid: http://www.youtube.com/watch?v=z3tL07_INoY
Sorry for bad english.

**Comment by scriptinator** [comment]
Bungee cord proxies

**Comment by scriptinator** [comment]
You could use a packet sniffer to hack the server in many ways such as finding bungee IPS and proxies. I can use wireshark, but it is difficult to discern what packets are from Minecraft and which are not.

**Comment by scriptinator** [comment]
So?
