### ISSUE TITLE
Move recorder

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#817]
Records your movements as JSON. 

Like This

go 5.12 blocks to south east
jump
....

then use them like a spam script.

add a movement section to your website.
Example
Mineplex dragon escape through the hell movement uploaded by abc

**Comment by OMGchangeMYusername** [comment]
Idk if that would be possible (??) but that would be Extremely gooooood!
it would even solve that #557! by recording the mining and selling.
again,is that possible?

**Comment by Nitrogen-Dioxide** [comment]
This is called macro, I think that cyanit have it. But it need enhancements because it is not so easy to record and play.

And a macro for dragonscape is not the solution, because you spawn in random areas when it starts. :/

**Comment by mcccs** [comment]
>This is called macro, I think that cyanit have it. But it need enhancements because it is not so easy to record and play.

>And a macro for dragonscape is not the solution, because you spawn in random areas when it starts.

 @Nitrogen-Dioxide 

1st it goes to given coordinates with .goto command, then it starts the script

**Comment by Nitrogen-Dioxide** [comment]
@mcccs Yea this can be the solution.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
This would be a nice addition. I could literally just farm for gems in Mineplex.
And if this ever got complex enough, maybe even DeathRun.

**Comment by bob80333** [comment]
Initially, I was thinking of just going through all outgoing packets, and saving them to a new file to later be read and sent.  However, using them as a spam script would probably require a good bit of processing of the user input.  It could be done, but I'm unsure as to how you would convert left/right clicks to WSpammer commands, although I haven't taken a look at its syntax yet.

**Comment by eveythingistaken** [comment]
That would be THE MOST helpful thing ever. It seems just so hard to make

**Comment by bob80333** [comment]
Thinking about it more, it would be impossible to add either anything more than movement or there would have to be a command in the client to simulate a right/left click.  The idea of using packets would require a custom interpreter, but then you could simulate any in-game action a player could take.

**Comment by bob80333** [comment]
Or at least some sort of mechanism to interrupt whenever an input event occurs and store it.

**Comment by BoomBoomLHack** [comment]
its possible. look at replaymod
