### ISSUE TITLE
BlockMine Hack.

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#821]
So what it does is mines the specific block E.G *Hack Activated* Menu pops up find the block that you want mined E.G Cobblestone. It's pretty much a mining bot but you can choose the block type you want mined.

**Comment by Loltage23** [comment]
It's a good idea for Skyblock

**Comment by bob80333** [comment]
So nuker with only 1 block type?   Because the command '.nuker id <block id>' does that already.

**Comment by Alexander01998** [comment]
Duplicate: #456 or already implemented: `.nuker mode id`.
