### ISSUE TITLE
Non-Ai Spotter

### ISSUE THREAD

**Issue by ayciate** [Wurst-Imperium/Wurst-Client#822]
As being a keen player of block hunt i find myself stuck with one animal left and need a hack to spot all the non mobs. Also this would be us-full as there could be a killaura setting for non-mob ai usfull for Sneaky Assassins on mineplex and other mob things.

**Comment by bob80333** [comment]
Use PlayerESP and set target to Player

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@bob80333 Doesn't work for me, and I tried it both on Sneaky Assassins and Block Hunt.

**Comment by Alexander01998** [comment]
Duplicate: #81
