### ISSUE TITLE
RightclickInvsee

### ISSUE THREAD

**Issue by Lakitu** [Wurst-Imperium/Wurst-Client#825]
At this moment it's only possible to open a player's inventory by the command <code>.invsee [player]</code>, so my idea was to make it more easy. If you (double) rightclick on a player, there will open the inventory of that player, exactly like the command of invsee, but then much faster. Players are able to disable and enable it, because it is a mod. That will make it faster to read the player's enchantments and potion effects.

**Comment by mcccs** [comment]
>i cant add a keybind for middle button! Please try it, its impossible! EDIT: and i need .invsee near command
https://github.com/Wurst-Imperium/Wurst-Client/issues/318
dupli
