### ISSUE TITLE
.annoy

### ISSUE THREAD

**Issue by GoGoJJTech** [Wurst-Imperium/Wurst-Client#829]
Either I'm missing something, or .annoy doesn't repeat what the person says back to them. In main chats, at least. If it works via /msg, then I guess that makes sense since I can't see it and they can't either.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Did you try it on a vanilla server? I haven't, don't know if that will fix anything. Try to do it to someone on a vanilla server.

**Comment by GummiBoat** [comment]
> if(message.startsWith("<" + name + ">") || message.contains(name + ">"))

Because of that, only if the message starts with "<username>" or it contains "username>" it will get repeated. But I agree that it should be more than those two options.
