### ISSUE TITLE
AutoSoup hack

### ISSUE THREAD

**Issue by MorganPlaysMC** [Wurst-Imperium/Wurst-Client#83]
This hack is for Soup pvp plugin servers it eats soup automatically and throws it without holding the soup

**Comment by Alexander01998** [comment]
No one plays KitPVP anymore.

**Comment by GlitchHead** [comment]
Tru

**Comment by MorganPlaysMC** [comment]
I do :(

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Resilience-Client-Source/blob/master/com/krispdev/resilience/module/modules/combat/ModuleAutoSoup.java

**Comment by Meylama** [comment]
It would be cool if Wurst would have AutoSoup, some servers like Timolia or US servers use this very often.

**Comment by Alexander01998** [comment]
I guess people do play KitPVP.

**Comment by OMGchangeMYusername** [comment]
Yeah XD
