### ISSUE TITLE
EnderChest Hilighter

### ISSUE THREAD

**Issue by Loltage23** [Wurst-Imperium/Wurst-Client#832]
So on Hive TIMV You get wooden chests and Ender chests. Basically I want a Enderchest hack that's like the chest hack but it's blue and says EnderChest on the top if it.

**Comment by OMGchangeMYusername** [comment]
You can use `.t search`. If you don't know how to choose enderchests,`.search name ender_chest`

Well,this can be a little enhancement for the ChestESP,where it highlights Enderchests with a different color or blue anyway.

**Comment by Alexander01998** [comment]
ChestESP will highlight chests, trapped chests, ender chests, minecart chests and several types of piston crates.

![](https://cloud.githubusercontent.com/assets/10100202/7882265/385b6dce-060c-11e5-8824-e33bd441265d.jpg)

**Comment by OMGchangeMYusername** [comment]
It is of course working,but he meant that it should highlight different types with different colors.
these are all green highlighted,HiveMC uses both enderchests and ordinary chests,however the wooden chests don't contain stuff,only enderchests have items in them.
it's not only HiveMC tbh,but he wanted to clarify it a little more :)

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@OMGchangeMYusername He was talking about Trouble in Mineville, not SG. I have really bad OCD.

**Comment by OMGchangeMYusername** [comment]
@ICouldntUseMyRealNameSoIHaveThis woops,thanks for correcting me :smiley: 
OCD?
if you were serious,that must be tough xD
