### ISSUE TITLE
More `.search` options

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#833]
I was playing around with `.search` a little,it's a useful feature.
I was thinking,it can be better with more possibilities,for instance you can make it so it can highlight more blocks.
It could be even nicer if it had presets,like `.search 1` should look for the blocks you have chosen for the preset 1 etc..
I'm not putting the presets as the main suggestion so you can ignore it if you want,but Search should Be able to look for more blocks, `search <add/remove> <id/name> <block>`

Greets :smiley:

**Comment by Alexander01998** [comment]
That is almost exactly what X-Ray does.
```
.xray (add|remove) (id|name) <block_id|block_name>
```
Search is meant for quickly searching a certain block without changing your X-Ray settings.

**Comment by OMGchangeMYusername** [comment]
If you highly disagree to this,i'd suggest X-Ray opacity instead. A lot of other clients have this as a slider in the settings,and it's very awesome because it's not really the same as turning everything black and only render the blocks you chose.
![2015-05-29_15 58 32](https://cloud.githubusercontent.com/assets/10786571/7882996/a9026f8c-061b-11e5-9940-73e0814e5d74.png)

**Comment by Alexander01998** [comment]
Wurst for Minecraft 1.7.X had opacity X-Ray, but Minecraft 1.8 broke it.

**Comment by OMGchangeMYusername** [comment]
~~shit~~ :/
