### ISSUE TITLE
Forge Mods

### ISSUE THREAD

**Issue by CreeperBoy2001** [Wurst-Imperium/Wurst-Client#835]
Please add the Feature, that you can Change from vanilla minecraft to forge minecraft 1.8 in  the Options, that would be very nice, than you can cheat on modded Servers, too.

I love this Client because there are so many Options.

And sorry for my bad english, I normally don't speak it.
I'll donate for this Client when I'm older than 13.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Duplicate: #777 
Just in case you were looking for it.
