### ISSUE TITLE
Killaura bug!

### ISSUE THREAD

**Issue by brld** [Wurst-Imperium/Wurst-Client#836]
I was using some killaura today and then all of a sudden neither killaura or killaura legit would work? Any suggestions?

**Comment by brld** [comment]
This might help--It happened right after I restarted my game.

**Comment by Alexander01998** [comment]
> Any suggestions?

- You set the Target selector to something else than the entity you wanted to attack

- You set the Killaura range to a very low value

- You tried to attack a player that you added to your friends list
