### ISSUE TITLE
Wurst.jar checking script downgrades version.

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#837]
İ use Wurst 1.14.1 but bot says 1.11?

**Comment by mcccs** [comment]
fixed
https://github.com/Wurst-Imperium/Wurst-Client/issues/480#issuecomment-92008981

**Comment by mcccs** [comment]
Wait, this is only fixed for me, wurst.jar checking command downgrades version to 1.11. Please fix this bug.

**Comment by Alexander01998** [comment]
> wurst.jar checking command downgrades version to 1.11.

It will always use the Wurst version that you have currently installed.
That means you are currently using Wurst v1.11.
