### ISSUE TITLE
PlayerESP (Green Hands) Closed

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#838]
![2015-05-30_17 18 33](https://cloud.githubusercontent.com/assets/11218527/7897759/e4a6f6fe-06f0-11e5-8d8d-4190f1355e96.png)

When I turned on PlayerESP and fly to up. The Player's inventory and hand is being green

**Comment by Orcunegeacar** [comment]
Note: I'm in the play.randomcraft.nl (Not single player)

**Comment by Orcunegeacar** [comment]
SO SORRY. Didn't see that. #568

**Comment by GummiBoat** [comment]
There should be a close button next to the "Comment" Button. You don't need to write "Closed" in the title.
