### ISSUE TITLE
Folder Editor

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#839]
Are you tired of the ways the tabs are organized? Do you want to rename the tabs? Do you have trouble finding your mod buttons? Well I have the perfect thing for you! Only $9.99 (Its free of course)!
With the folder editor you can rename folders make new folders and rename folders! You can also put mods in different folders than the original!

Tab that cannot be edited 

AutoBuild, Settings

**Comment by GummiBoat** [comment]
I assume that you are suggesting to add one? I think the mods are organized fine currently.

**Comment by Nitrogen-Dioxide** [comment]
A "Favorite Mods" tab would be better.

**Comment by Alexander01998** [comment]
I'm planning to add custom frames, but not by using folders.
