### ISSUE TITLE
.search for players

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#840]
New stuff
`.search player <player_name>`

turns tracers, player esp and other stuff red for that player.

easier for bounty hunting

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Kind of ruins the whole block-search thing, maybe a different command?

**Comment by Alexander01998** [comment]
> Kind of ruins the whole block-search thing, maybe a different command?

Updated.
