### ISSUE TITLE
Crash on AFK

### ISSUE THREAD

**Issue by PopTrop972** [Wurst-Imperium/Wurst-Client#841]
After a few hours, I got back on my pc to see an almost completely dark screen and at the top was "Minecraft 1.8 (Not Responding)." I was going to put the crash report in here but accidentally deleted it. 

Help I'm on a windows laptop and the Wurst client is version 1.14.1

**Comment by Nitrogen-Dioxide** [comment]
Probably it is the spontaneous crash...

**Comment by Alexander01998** [comment]
Probably a duplicate of #642.
