### ISSUE TITLE
LSD doesn't generate random colors

### ISSUE THREAD

**Issue by Huanjohn** [Wurst-Imperium/Wurst-Client#844]
When I was using Wurst v 1.14, LSD generated random colors as it is supposed to.  However, after I updated to Wurst v 1.14.1, LSD does not generate random colors, instead, it just toggles cinema camera.

![2015-05-31_01 36 52](https://cloud.githubusercontent.com/assets/12178060/7900916/21dd5bfe-0736-11e5-99e8-e216618c01a0.png)

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Super Secret Settings (all of them) also don't work. Also in the screenshot you should have censored your name, just so you don't get banned.

**Comment by Alexander01998** [comment]
Fixed.
