### ISSUE TITLE
Wurst-Bot NoClassDefFoundError

### ISSUE THREAD

**Issue by MagicGamer191** [Wurst-Imperium/Wurst-Client#845]
Hi, when I try to start wurst-bot, I get an error (Appendix)
What do I wrong?
PS sorry for my bad English
![error](https://cloud.githubusercontent.com/assets/12681906/7901646/a8afdcae-0792-11e5-90bd-1ffb5a79605a.PNG)

**Comment by GummiBoat** [comment]
You need to put the Wurst-Bot Folder into your .minecraft/versions/Wurst - Folder.

**Comment by Alexander01998** [comment]
> What do I wrong?

You either forgot the Wurst-Bot_lib folder or put the Wurst-Bot folder in the wrong place.

**Comment by MagicGamer191** [comment]
I'm sorry but it's still not here my Wurst-bot folder and my sausage Bot_lib folder. 
![wurst-bot](https://cloud.githubusercontent.com/assets/12681906/7919436/90dc81c0-0898-11e5-99fa-6715ed422d34.PNG)
![wust odner](https://cloud.githubusercontent.com/assets/12681906/7919437/90dcd314-0898-11e5-9d08-c0ee7f5c550d.PNG)
![wust_lib](https://cloud.githubusercontent.com/assets/12681906/7919438/90e13de6-0898-11e5-8029-308858a5d1bd.PNG)

**Comment by Alexander01998** [comment]
You downloaded the wrong file.
Instead of downloading the repository, you need to go to the "releases" tab and download the latest release.
