### ISSUE TITLE
FastBow (Single Shot)

### ISSUE THREAD

**Issue by HospitalStaff** [Wurst-Imperium/Wurst-Client#853]
Would you be able to add a semi-automatic bow mod? I like the FastBow but it fires a little too fast.
Maybe add a commend like to change the speed?

**Comment by mcccs** [comment]
Wow, i thought this enhancement. yesterday. And you read my mind!

**Comment by Alexander01998** [comment]
Duplicate: #753

**Comment by GummiBoat** [comment]
@Alexander01998 I think you quite misunderstood his problem. The Issue you labeled is changing the Speed of the Charge Animation of the Bow.

What @HospitalStaff means, is that the built-in FastBow should be configurable. Currently it's like.. 10 arrows per second(?). But he wants to change it to slower (or even faster) amounts. Like 2 arrows each second, or 20 arrows each second. I hope that's a little bit more understandable. (I think a slider is more suited for this than a command.)

**Comment by mcccs** [comment]
@Alexander01998 he meant this:
.fastbow lock 2
{hold right click
shoot two arrows
wait for release right click
if right click
repeat these steps
}
.fastbow unlock
{
hold right click
shoot ∞ arrows
}
