### ISSUE TITLE
ExtraCarry

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/Wurst-Client#867]
Doesn't drop the items you've put in the player crafting slots in the inventory,you can store anything at the four slots without dropping them if you close the inventory.
it's also featured on Cicada,they've stopped developing this client ages ago,this is the code:
```python
package cicada.mods.player;

import cicada.mods.*;
import cicada.event.events.*;
import cicada.util.*;
import net.minecraft.network.play.client.*;
import net.minecraft.network.*;

public class ExtraCarry extends ModBase
{
    public ExtraCarry() {
        super("ExtraCarry", 0, ModType.PLAYER, false);
    }
    
    private void onPacketOut(final EventPacketOut event) {
        if (event.getPacket() instanceof C0DPacketCloseWindow) {
            event.lock();
            Wrapper.sendPacket(new C0EPacketClickWindow(0, 0, 0, 6, Wrapper.getPlayer().inventory.getItemStack(), Wrapper.getPlayer().openContainer.getNextTransactionID(Wrapper.getPlayer().inventory)));
        }
    }
}
```
i don't really know that much i just copy pasted it,hoping it'd help you making it :)

**Comment by WurstContributer** [comment]
Maybe armor slots? +8 Extra slots

**Comment by OMGchangeMYusername** [comment]
i doubt that's possible...
i've never seen a way to put things other than armor in the armor slots.
if it's possible then GG.

**Comment by GummiBoat** [comment]
It's possible to equip non-armor items in minecraft, but I don't know if the server allows the client to do so, if not caused by a plugin...

**Comment by WurstContributer** [comment]
Helios spawns items into your armor slots if ur in gm1

**Comment by kristian2830** [comment]
yes if your in gm1 only

**Comment by GummiBoat** [comment]
@kristian2830 That's because you only can give yourself items as a client if you're in creative mode.

**Comment by WurstContributer** [comment]
Spawning items into the slot is possible but i dont know if its possible to do it in gm0. You can also wear stacked armor but i dont know if its possible with blocks

**Comment by WurstContributer** [comment]
Helios spawns items into the armor slot right? So if we made it "put" the item into the slots :D it would be possible
