### ISSUE TITLE
Book Hack

### ISSUE THREAD

**Issue by radko007** [Wurst-Imperium/Wurst-Client#870]
i did all what is in "tutorial" on web but i can´t click on URL and no one can click on it .Please help!
and you can add some new command , that command will be able to  changed by people.

Sorry for mistakes! i am from slovakia so if you find mistakes please sorry me ! and don´t worry!!

**Comment by GummiBoat** [comment]
Currently, it's not working anymore. It will be fixed in future versions. And your Issue got reported this morning as well (in a similar version). Please search for your matter the next time.
Duplicate #856
