### ISSUE TITLE
Selective nuker

### ISSUE THREAD

**Issue by AshleyWaterman** [Wurst-Imperium/Wurst-Client#877]
Hi,

In other various clients I have seen a 'Nuker' command that only targets specific blocks? This would be a useful feature as it would allow people to specifically mine stone (instead of granite, andersite and that...) or run through a forest and ignore the leaves and just chop the wood.

Would this be possible to add to Wurst?

Kind regards,

Ashley Waterman

**Comment by GummiBoat** [comment]
That is already implemented, ".nuker id ITEM_ID" or if you don't know the id you can type ".nuker name NAME". So for your example It could be ".nuker id 1" or ".nuker name stone". Then you just have to activate Nuker and you're done.

**Comment by AshleyWaterman** [comment]
Oh! Fantastic!!! Could it be made into a separate hack though? As in you select the hack and then select a block by clicking on it and the hack will only mine that block, rather than typing in the command? Just thinking for ease of use for everyone else too.

Thanks for the quick reply!

**Comment by GummiBoat** [comment]
@AshleyWaterman ".nuker mode id". After activating nuker, you have to punch the block you want to destroy once. If you punch another one, it will switch. You can not add multiple Blocks to ID-Nuker, afaik.

**Comment by AshleyWaterman** [comment]
As soon as you said that I tried it and it works, my only issue is that on some servers the way it breaks the blocks not directly in your line of sight is a little buggy and doesn't break the block but repeatedly tries to break the block and doesn't switch to a different one

**Comment by GummiBoat** [comment]
That's because of NoCheat+, should be fixed if you activate YesCheat+ and/or move a bit back, if it still happens.

**Comment by AshleyWaterman** [comment]
Yeah I always use YesCheat+ and it still happens when I move slightly away from the block

**Comment by GummiBoat** [comment]
Then you have to wait, that Alexander changes his Nuker Algorithm. Usually it shouldn't mine blocks that you can't reach yet, but it seems that you have a special case. Just deactivate Nuker if your problem occurs and reactivate it a few blocks away again.
