### ISSUE TITLE
.legit Command

### ISSUE THREAD

**Issue by Orcunegeacar** [Wurst-Imperium/Wurst-Client#878]
I was playing in a server. (I was using killaura :smile: ) They detected me and said type .legit or something like that. I didn't type anything because I knew Wurst hasn't got a command like that. And I banned :smiley: ..... Please do a .legit thing and it will not a command. Just word. (You understand me anyway :+1: :smile: )

**Comment by Orcunegeacar** [comment]
They tried to know I'm using hacked client.

**Comment by Orcunegeacar** [comment]
duplicate?? If you didn't understand. Let me tell you again. A server owner says type .legit (Trying to know if I am using hacked client) but I didn't and I banned from server. When I type .legit , Wurst says there is no command like that or error. (Please delete .legit from commands. let it go to the chat.)

**Comment by GummiBoat** [comment]
Duplication of the Issue #141 , to be more precise.

You can just type ".say ,legit" and it will send ".legit".

**Comment by Orcunegeacar** [comment]
Thank you for information.
