### ISSUE TITLE
Can You Add Zoom,Click aura, and OpSign??

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#887]

**Comment by GummiBoat** [comment]
Zoom: Duplicate #324 
Click Aura: WTF is that?
OPSign: I'm pretty sure that it got patched. But #342 covers that.

**Comment by billyoz** [comment]
Click Aura is like kill aura , but clickaura is not automatic attack. click
aura is attack when you press attack button. Sorry For bad English

**Comment by GummiBoat** [comment]
Oh, you mean, you click and the client attacks the nearest entity for you? You have to wait for a reply from @Alexander01998 for that one.

**Comment by billyoz** [comment]
yes, but its use aura

**Comment by Alexander01998** [comment]
ClickAura is a synonym for ClickAimbot, so that part is also a duplicate.

**Comment by billyoz** [comment]
Can you Add ClickAimbot in wurst??

**Comment by OMGchangeMYusername** [comment]
Wouldn't this be invalid more than duplicate?
oh,ClickAimbot and ClickAura are mostly the same,Clickaura attacks anyone in your range (when you click),it's like a silent Aimbot.
ClickAimbot is not a silent Aimbot,it faces the entity in your range after you've clicked once,and then you can click again to attack.
