### ISSUE TITLE
I need help with force op

### ISSUE THREAD

**Issue by Mineshafterrawks** [Wurst-Imperium/Wurst-Client#888]
I cant edit my pw list when i click browse there isnt any files i see with the defaults pw and i have a huge pw list but i dont see a file where i can dump it in

**Comment by GummiBoat** [comment]
There is a [Wiki Page for Foce OP](https://github.com/Wurst-Imperium/Wurst-Client/wiki/ForceOP-%28a.k.a.-AuthMeCracker%29).

**Comment by Mineshafterrawks** [comment]
There isnt a Your list button this is all i see
![screen shot 2015-06-07 at 5 51 19 pm](https://cloud.githubusercontent.com/assets/12782863/8023413/dbd49740-0d3d-11e5-8625-debd1f123fbf.png)

**Comment by GummiBoat** [comment]
Well.. u just need to select your pw-list within that window and then click on the "Open" Button below.. shouldn't be that hard.

**Comment by Mineshafterrawks** [comment]
Theres no file there.

**Comment by Alexander01998** [comment]
Why do you want to use your own list if you don't have one?

**Comment by Mineshafterrawks** [comment]
I wanna Dump my whole pile of common pw on it i cant seem to find the file

**Comment by Alexander01998** [comment]
If you can't find your file anymore, that's either human error or a Mac issue. It has nothing to do with Wurst.

**Comment by Mineshafterrawks** [comment]
So what can i do to get it back ._.

**Comment by Alexander01998** [comment]
Yell at crApple for not having a search bar like Windows. :wink:

**Comment by Mineshafterrawks** [comment]
boohoo -crys- I regret buying a mac i had to talk to apple support just to download wurst URGHHHHH getting windows next :>

**Comment by Mineshafterrawks** [comment]
whats the name of the pw file btw i will find that file and ......

**Comment by Alexander01998** [comment]
> whats the name of the pw file btw i will find that file and ......

How could I know what you named your file?

**Comment by Mineshafterrawks** [comment]
I swear i did not rename anything but i looked through all the wurst files and i dont seem to see anywhere with a pw list

**Comment by Alexander01998** [comment]
The default list is not a file, it can only be used by selecting the <kbd>default</kbd> option (see screenshot).

![](https://cloud.githubusercontent.com/assets/10100202/8033908/efe0c100-0de2-11e5-9a75-b7e6151b7fe9.jpg)

The <kbd>TXT file</kbd> option is only meant for custom lists that *you* made or downloaded, that *you* named and that *you* placed in a folder of *your* choice. A custom list is in no way related to Wurst.
