### ISSUE TITLE
Wurst chat (IRC)

### ISSUE THREAD

**Issue by MorganPlaysMC** [Wurst-Imperium/Wurst-Client#89]
How about Wurst chat? So whoever has Wurst client they can chat with other people who have wurst by typing @ (Chat Message) Like they can talk about servers to hack on etc... Can you please add this to the client?

**Comment by MorganPlaysMC** [comment]
Me and my brother and my friends play kitpvp. I have like 10 friends who play mc with me on servers. they would love it if you add these to the hack.

**Comment by MorganPlaysMC** [comment]
I meant Client

**Comment by MorganPlaysMC** [comment]
Client chat is also in Weepcraft Client and TeamBattle client for a example.

**Comment by MorganPlaysMC** [comment]
**Please Add!**

**Comment by pokeball99** [comment]
Please don't beg for features to be added,if he has not responded to this yet,he Is probably busy irl,as the client development does not have 24/7 to work on this and is not payed to do so,and we should be greatfull that he has taken the time to make this awesome client,so I bid u good day sir

**Comment by GlitchHead** [comment]
well some clients have some stuff similar to this using IRC chat so it is possible.

**Comment by OMGchangeMYusername** [comment]
That'd Be Cool! But You Should Add Nicknames For People Using The Chat :grin:

**Comment by MorganPlaysMC** [comment]
That sounds good!

**Comment by MorganPlaysMC** [comment]
I hope this will be added to the client! :smile:

**Comment by Notchshero** [comment]
But dont use the in-server chatbar, or add an option to close irc

**Comment by Orcunegeacar** [comment]
It'll be awesome :smile: If there is a Form too. The greatest client ever :smiley:

**Comment by Nitrogen-Dioxide** [comment]
The bad thing about IRC, is that wurst will need a private server host, and that costs money. :(

**Comment by Alexander01998** [comment]
> The bad thing about IRC, is that wurst will need a private server host, and that costs money. :(

So far, I have always found a way around paid hosting.

**Comment by Nitrogen-Dioxide** [comment]
Haha nice.

**Comment by pokeball99** [comment]
so,how long will this take to implement?its been 21 days,u just not gotten around to it?

**Comment by Alexander01998** [comment]
> so,how long will this take to implement?its been 21 days,u just not gotten around to it?

When a suggestion gets confirmed, that doesn't mean that I immediately start working on it.

**Comment by pokeball99** [comment]
i know that,but how high is this on the your to-do list?

**Comment by Alexander01998** [comment]
> i know that,but how high is this on the your to-do list?

The [list of confirmed issues](https://github.com/Wurst-Imperium/Wurst-Client/labels/confirmed) is my to-do list and it doesn't have any priorities.

**Comment by mcccs** [comment]
> The bad thing about IRC, is that wurst will need a private server host, and that costs money. :(

i suggest co.nr (not co.nr.com) free %100 hosting

**Comment by MorganPlaysMC** [comment]
stop messaging me!

**Comment by OMGchangeMYusername** [comment]
@MorganPlaysMC Dude you can disable getting email notifications from Github!
go play around with the profile thing and you'll find it.

**Comment by pokeball99** [comment]
or just unsubscribe from this thread

**Comment by TekkitCommando** [comment]
i might try to code this irc part and send a pull request if it works haha

**Comment by TekkitCommando** [comment]
Ok so i trashed the GUI irc chat thing i was coding in favor of just having an irc section of the normal minecraft chat so i got a new branch going on my fork of Wurst Client and will be working on that now :smile:

**Comment by Whatisthisname** [comment]
I WANT

**Comment by TekkitCommando** [comment]
Haha I can submit a pull request for the GUI irc if you want so you can have it until i can work on the integrated mc chat one :P

**Comment by WurstContributer** [comment]
IRC Chat room much?

**Comment by LolDatSec** [comment]
Personally, I dislike the idea of an IRC because even the skrubbiest skid can trace IPs with it, rendering it insecure, might as well add a proxy-er?

**Comment by WurstContributor** [comment]
One problem : Theres always a skrubby kid that spams up a chat room

**Comment by TekkitCommando** [comment]
xD

**Comment by Nitrogen-Dioxide** [comment]
@WurstContributor With wurst spammer for sure :D xD

**Comment by WurstContributor** [comment]
XD

**Comment by Bluscream** [comment]
Thats why Wurst should have a IRC moderator like Resilience had.

![Image of Wurst Credits](http://i.gyazo.com/2ac85b64976b6a35630ed8c1a6cef099.png)

**Comment by pokeball99** [comment]
@blusream I agree,but since this is open source,how are we going to prevent admins from making a plugin to just auto ban all user on the irc? Also,mods would be good,maybe the first mods would be some of the regs of the issues like @TekkitCommando,@Nitrogen-Dioxide,@GlitchHead,@GummiBoat,and me

**Comment by WurstContributor** [comment]
Well this is how i would think it would work

Wurst>Proxy(To prevent skrubby kids from getting ips)>IRC
  Wurst generates an id to use for banning
   
Staff would do /ban or whatever [Displayname] to ban them.
 You may pick a nickname of anything but your id will stay the same.

The id system should work like in Teamspeak 
 Wurst will find a hidden id for the computer somewhere and use that as the id.
  That id will not be public for any members in the IRC chat room.

Banning system will work like this
 Command>You>Encrypt your id in MD5 Hash>IRC>Ban.

The id will be public in MD5 hash form.

**Comment by TekkitCommando** [comment]
@pokeball99 I don't mind being a mod, I have got a lot of free time now :smile:  I will probably get back to coding irc, but I would like some help if other devs are interested in helping we can just make a git organization called Wurst-IRC and Put anybody thats gonna be developers/mods on the Organization Team :) I am still learning/experimenting with Java some, so it would be good to get some help from more experienced people haha :P

**Comment by Nitrogen-Dioxide** [comment]
@Bluscream 
Omg welcome! I love the resilience client, thanks for making a very very good work! I used the resilience IRC when it was working (old god days when fastbow was not patched). Can you help this client too? I know it is a hard task but it will be very cool if you contribute here.

@pokeball99 
Resilience is not obfuscated... and the IRC worked very very well.

**Comment by Bluscream** [comment]
Maybe @Alexander01998 wants to talk to me about IRC related stuff :)

**Comment by pokeball99** [comment]
@bluscream,thanks for the invite!

**Comment by LolDatSec** [comment]
@WurstContributer or you can make a socket protocol instead of using the IRC protocol. Even I can do one.

**Comment by Bluscream** [comment]
Also @Alexander01998 can take a look into [this](https://github.com/Bluscream/Resilience-Client/tree/master/irc).

**Comment by OMGchangeMYusername** [comment]
meh.. i want to be excited but it's just hard..

**Comment by Bluscream** [comment]
https://github.com/Bluscream/Resilience-Client-Source/tree/1109ddcb3c50bda06c2fe6775bc811e8342d07d8/com/krispdev/resilience/irc

**Comment by TekkitCommando** [comment]
O-O :D

**Comment by Bluscream** [comment]
@TekkitCommando hmm? :D

**Comment by TekkitCommando** [comment]
I forked it already xD

**Comment by Bluscream** [comment]
Its old but has many cool mods to skid :DD

**Comment by TekkitCommando** [comment]
:D Yep I like client development, I coded a client update for minecraft that added new stuff, never made a hacked client before but i do enjoy coding the minecraft update

**Comment by Bluscream** [comment]
Could you make some commits for Wurst?

There are many cool feature requests with included code examples so it shouldn't be hard and @Alexander01998 can focus on the hard things :+1:

**Comment by TekkitCommando** [comment]
Maybe, I coded IRC for Wurst but never sent a PR because it was a windowed IRC and was integrated into the Minecraft Chat like Alexander wanted :P

**Comment by Bluscream** [comment]
Resilience's IRC is in the MC chat. Thats much more comfortable i think.

**Comment by TekkitCommando** [comment]
Yeah Me To, I might try to code PR's for Wurst sometime

**Comment by Bluscream** [comment]
Also i dont mean big changes like a IRC chat system. I mean the small ones like: #1332, #1318, #1319, #1316, #1317, #1297, #1296

**Comment by TekkitCommando** [comment]
I will look at them :P

**Comment by Bluscream** [comment]
Thanks :)

**Comment by TekkitCommando** [comment]
No Problem :)

**Comment by haykam** [comment]
If we have an IRC that knows who uses Wurst, why not put an indicator on their name?

**Comment by Bluscream** [comment]
[![Wurst Gitter Live Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Bluscream/Wurst-IRC?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by solidshadow96** [comment]
Ok look i have an idea lets say every letter that you type witht the hack on will change to the oposite letter so a would be z and b would be y ect that way you could just say its a different language.Also typing $w(your message) would have wurst translate all letter after that automatically. i think this would work much better

**Comment by WurstContributor** [comment]
@solidshadow96 Not nessacery. It sends the message TO ALL online wurst users. No one else.

**Comment by solidshadow96** [comment]
Wow great

**Comment by solidshadow96** [comment]
When is it gonna be implamented

**Comment by pokeball99** [comment]
@solidshadow96 who knows? @Nitrogen-Dioxide said he was like ~5 months ago,no luck,and then @Bluscream said he was as well going to do it,but again its fell though,so we may never get this XD
