### ISSUE TITLE
Mining a certain radius

### ISSUE THREAD

**Issue by heyotomato** [Wurst-Imperium/Wurst-Client#892]
I would like to see a feature where you could select a radius and it automatically mines without touching your computer at all. This would be great for making farms on factions.

**Comment by GummiBoat** [comment]
Do you mean a radius or a certain area? Because you can change the range from Nuker yourself.

**Comment by Nitrogen-Dioxide** [comment]
Like excavator? - You select 2 vertices for the excavator (like world edit) and the bot auto mines it.

**Comment by GummiBoat** [comment]
I think he means more like you select an Area and it repeats mining it over and over again.. but your idea would be very practical too @Nitrogen-Dioxide, I like it!

**Comment by Alexander01998** [comment]
Duplicate: #456
