### ISSUE TITLE
Barrier esp

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#894]
A mod to see Barriers on server's without holding it

**Comment by GummiBoat** [comment]
Shouldn't .search id 166 do the thing? And as far as I know, "visible" Barrier Blocks are displayed with a particle, which is only visible up to ~16 or so Blocks from its source... But it already got confirmed, so I'm gonna say it can be useful...

**Comment by LolDatSec** [comment]
Play the barrier particle effect on the barrier block, should be really easy.
Can even be done with vanilla command blocks. `/particle`
