### ISSUE TITLE
AltManager: save name and e-mail address

### ISSUE THREAD

**Issue by NinjaYouBro** [Wurst-Imperium/Wurst-Client#9]
If you add the email and password of an account, it doesn't show the skin. If you add the ingame name and the password, it says "Password Incorrect". Also please make it change to the ingame name once you added the email and password and it saves correctly.

**Comment by Alexander01998** [comment]
> If you add the email and password of an account, it doesn't show the skin.
> Also please make it change to the ingame name once you added the email and password and it saves correctly.

This was planned for quite a while and I agree that it should be implemented. It will require a new alt list format that stores two names per alt - one for login, one for display. A converter for old alt lists will be necessary as well.

> If you add the ingame name and the password, it says "Password Incorrect".

This only happens with migrated accounts. Normal accounts can log in with their username.

**Comment by GlitchHead** [comment]
This would be nice

**Comment by GlitchHead** [comment]
Converter.jar just deleted my alts.wurst....

**Comment by CraftyGamer22** [comment]
But what password? Where do you get this password from?

**Comment by Alexander01998** [comment]
> But what password?

The password of the Minecraft account.

> Where do you get this password from?

Three methods:

1. Buy a Minecraft account. (20€, legal)
2. Use a leaked account. (free, somewhat legal)
3. Crack someone's password. (free, not legal)

**Comment by CraftyGamer22** [comment]
Ok. Thanks!

**Comment by CraftyGamer22** [comment]
how do you stop using a cracked or premium account?
