### ISSUE TITLE
Keybinds not saving properly

### ISSUE THREAD

**Issue by MisterQuatsch** [Wurst-Imperium/Wurst-Client#90]
In my keybinds the ClickGUI resets every time i restart the client.

**Comment by Alexander01998** [comment]
# Possible reasons
- You have had a crash after you changed the keybind so that it couldn't be saved.
- You didn't change the keybind properly (e.g. you clicked `Cancel` instead of `Save`).

# Possible solutions
- Make sure that you have write access in `%appdata%\.minecraft\wurst`.
- Edit the file `%appdata%\.minecraft\wurst\modules.json` manually and see if that works.

**Comment by MisterQuatsch** [comment]
You have had a crash after you changed the keybind so that it couldn't be saved. > No, i try it over 10 times

You didn't change the keybind properly (e.g. you clicked Cancel instead of Save). > No

Make sure that you have write access in %appdata%\.minecraft\wurst. > jep 

Edit the file %appdata%\.minecraft\wurst\modules.json manually and see if that works. > try it also but din´t work

**Comment by Krowit** [comment]
I have the same problem...

**Comment by MorganPlaysMC** [comment]
It doesn't happen for me. What do you mean by you restart the client?

**Comment by MisterQuatsch** [comment]
Close Minecraft and Open it again

**Comment by Alexander01998** [comment]
What are your system details (OS name, Java version, etc.)?

**Comment by MisterQuatsch** [comment]
Java i use the new Minecraft Launcher with his own java

**Comment by MisterQuatsch** [comment]
I think the Titel is Not right.
IT safe all my keybinds but not the bind for the ClickGUI.

**Comment by Alexander01998** [comment]
I still need your system details.

**Comment by MisterQuatsch** [comment]
What you man with that? 
cpu?
Grafik Card?
or the Software that i usw to play Mc?

**Comment by MisterQuatsch** [comment]
So somethink like: i use Java 7
?

**Comment by Alexander01998** [comment]
> What you man with that? 
> cpu?
> Grafik Card?
> or the Software that i usw to play Mc?

Sure, but most importantly:
- OS name
- Java version, update number & vendor
- RAM
- 32bit or 64bit
- Default charset

**Comment by MisterQuatsch** [comment]
ok now i am in my bed :D
I`ll look later:)
p.s. Im german :D

**Comment by MisterQuatsch** [comment]
Here are my system details.

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 1.5.1 (latest: 1.5.1)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 196500512 bytes (187 MB) / 413405184 bytes (394 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 14, allocated: 12, tallocated: 94
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6570 GL version 4.2.12217 Compatibility Profile Context 12.104.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [CleanMine.zip, Inventar.zip, By MisterQuatsch.zip, Texte (1).zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by MisterQuatsch** [comment]
Or you need more infos?

**Comment by MisterQuatsch** [comment]
>>>Look at this Video<<<

http://youtu.be/j942vlcX39U

**Comment by TommieIV** [comment]
I have this same problem my info:

Minecraft Launcher 1.6.11 (through bootstrap 5) started on linux...
Current time is Feb 27, 2015 10:11:36 AM
System.getProperty('os.name') == 'Linux'
System.getProperty('os.version') == '3.16.0-30-generic'
System.getProperty('os.arch') == 'i386'
System.getProperty('java.version') == '1.7.0_75'
System.getProperty('java.vendor') == 'Oracle Corporation'
System.getProperty('sun.arch.data.model') == '32'

Its not that big of a deal really. Your already doing a good job with this client so I would put this on the bottom of my list!

**Comment by MisterQuatsch** [comment]
"Its not that big of a deal really. Your already doing a good job with this client so I would put this on the bottom of my list!"

I also think so!

**Comment by OMGchangeMYusername** [comment]
"pending confirmation" label should be removed :)
i just happened to check issues with the label "pending confirmation" and i was surprised that a closed issue has it ;)
