### ISSUE TITLE
Cbook

### ISSUE THREAD

**Issue by YTJelly** [Wurst-Imperium/Wurst-Client#900]
can you awesome guys make the cbook is a lot easier and let it have every command. Thank you Yours sincerely YTJelly

**Comment by scriptinator** [comment]
What is a cbook. I say invalid or needs more info

**Comment by Huanjohn** [comment]
By cbook, do you mean command book?

**Comment by Orcunegeacar** [comment]
command block ?

**Comment by Orcunegeacar** [comment]
@YTJelly I guess you are talking about "Book Hack" in Wurst. Right ???

**Comment by OMGchangeMYusername** [comment]
Yep he definitely meant the book hack,it has every command the is **possible** for the player you give the book.
you can't make a simple player run commands that need permissions..
you can use /pay or /msg anyone you want to trick xD
it seems kewl to make a guy msg the owner with bad words xDD
