### ISSUE TITLE
Hack Plugin that detects a hack in 3 seconds

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#901]
The owner of the server valorpvp.org is bragging about his anti hack plugin and how it can appearantly detect hacks within 3 seconds. I wonder if what he claims is possible and if Wurst could bypass it

**Comment by Nitrogen-Dioxide** [comment]
xD tell him to detect render hacks xD xD.

**Comment by GlitchHead** [comment]
Thanks for the server to attack.

**Comment by scriptinator** [comment]
Hmm it seems he has deleted his post I'lol see what I can find. It was under a post about valor 3.0 features

**Comment by Alexander01998** [comment]
This is not a forum. It is only meant for bug reports, suggestions and support.
