### ISSUE TITLE
Force OP/Password cracker doesnt work right on reconnect

### ISSUE THREAD

**Issue by afreeusername** [Wurst-Imperium/Wurst-Client#911]
I just used force op and noticed that you cant reconnect/autoreconnect to a server without force op to stop.
It shows the last passwort it has tried and says its correct as soon you reconnected to the server.
I was kicked from a server because I took to long to login so it didnt try all passwords.
Btw sorry for my bad english, its not my native language.

**Comment by Alexander01998** [comment]
> It shows the last passwort it has tried and says its correct as soon you reconnected to the server.

You appear to have found a special server that confuses ForceOP by sending a message that looks similar to the "login successful" message that is usually sent by AuthMe.

There is no way to validate that a message was sent by AuthMe, as chat messages are sent to the client as plain text without any information about the sender. So instead, Wurst tries to guess the AuthMe message by looking for works like "login", "successful", "failed", etc.
