### ISSUE TITLE
Cant "direct login or save" alts when clicking edit or add alts

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#912]
i dont know why but i cant add edit or direct login alts i get cannot contact to the authorisation server yet the use button works on the alts that were added a while ago is anyone else getting this problem?

Im using the latest version of wurst
OS: windows 8

**Comment by GlitchHead** [comment]
i just deleted my alts.json and imported my alts still i cant edit and save alts yet direct login seems to be working

**Comment by Alexander01998** [comment]
The authorization servers may have banned your IP address. This usually happens when you try to login with a lot of broken alts.
Just wait one or two days and it should work again.

**Comment by GlitchHead** [comment]
but its working fine on the launcher and when i change my VPN ip it still happens.

**Comment by GlitchHead** [comment]
I also deleted my wurst folder and made a new one i could add alts and direct login. The only thing that's not working is the edit select a random alt and click edit and then save see if you get the prompt.
