### ISSUE TITLE
Minecraft hacked client outdated java version

### ISSUE THREAD

**Issue by thekilleralbino** [Wurst-Imperium/Wurst-Client#914]
whenever i try to use a hacked client it says my java version is outdated, and I found another one issue #142 but none of the fixes worked for me I tried every single one and not one worked for me, I don't know how to fix it anymore and am really having a problem with this any help is much appreciated

**Comment by mcccs** [comment]
Did you try method 3?

**Comment by scriptinator** [comment]
If you are on a mac open terminal and type:
which Java
If it gives something like usr/bin
Do ls-l usr/bin (Or whatever it gives)
Then copy that path to the executable field in the edit profile button in the launcher
