### ISSUE TITLE
What are the best settings for bypassing NoCheat+ with Killaura?

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#915]
Hi , I Have Found Issue That : When You Enable Your Kill Aura On Servers (Speed 10 Also !) You Cannot Move But You Can Hit , But Trigger Bot Works Fine ! Please Fix This Issue For Kill Aura Also Multi Aura 

Thanks , Hope To Wurst Be The Best Client :heart:

**Comment by GummiBoat** [comment]
This is probably not a problem with Killaura, but more a problem with the NoCheat Plugin on the Server. Try enabling "YesCheat+" While using Killaura, and never use MultiAura on NoCheat Servers. Probably your Range and Speed are too high, but YesCheat+ should adjust them automatically for you.

**Comment by Al00X** [comment]
Thx For Help ,But Other Clients I Tested And Worked At Same Server

**Comment by GummiBoat** [comment]
It doesn't matter if you tested other clients, because every client is doing its own job at handling Killauras.  Have you tried the steps I told you?

**Comment by Al00X** [comment]
No Cus I Banned At That Server LOL ! But i will Test On Other Server Thanks :laughing:

**Comment by Al00X** [comment]
And What Is The Normal Range & Speed For Killaura ?

**Comment by Al00X** [comment]
Tested Your Method - Not Work At : 11 Speed - 3.5 Range

**Comment by OMGchangeMYusername** [comment]
use KillauraLegit,it bypasses well.

**Comment by Alexander01998** [comment]
As there seems to be no answer to this question yet, the best settings for using Killaura on a NoCheat+ server are a speed of `12` and a range of `4.25`.

**Comment by OMGchangeMYusername** [comment]
@Alexander01998 A lot of servers have the range less than 4.25,i set it to 4.0 and it works fine.
and the speed is honestly too much,should be 7-8 or less..
