### ISSUE TITLE
Watermark Idea?

### ISSUE THREAD

**Issue by ChugsGaming** [Wurst-Imperium/Wurst-Client#917]
I think it would be very helpful if there was a way to temporarily disable the wurst logo so that we could take screenshots without being busted for using a hacked client. Forgive me if there is already a way, I have not found it. Anyone support or oppose this idea?

**Comment by scriptinator** [comment]
This has been requested and denied many times please search for issues before posting duplicates

**Comment by GummiBoat** [comment]
Duplicate: #19

Just use F1 or F3 if you really need to.

**Comment by ChugsGaming** [comment]
F1 removes the chat, rendering screenshots pointless, and f3 keeps the logo rendering screenshots pointless. How does this help? 

Script, I just joined this place, Is there a reason it as denied?

**Comment by ChugsGaming** [comment]
So I don't get a reason as to why?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
@GummiBoat 
You cannot use F1, as it blocks chat. When you open chat, it will show the logo.
F3. If you look at the Minecraft version, it will say "Wurst/Vanilla" or something like that.

**Comment by GummiBoat** [comment]
Then just use Puush and take seperate screenshots from the chat.
