### ISSUE TITLE
X-Ray 

### ISSUE THREAD

**Issue by oOLegionOo** [Wurst-Imperium/Wurst-Client#919]
When i use X-Ray to try to find spawners it tends to only shows spawners if you're close enough for it to be active.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Sometimes the X-Ray glitches and you can't see some blocks, but if you move position or try looking at the ground in a different angle it should fix it. Maybe try doing .search id 52?

**Comment by oOLegionOo** [comment]
i did but also most of the time nothing loads besides coal

**Comment by Alexander01998** [comment]
Duplicate: #247
