### ISSUE TITLE
Exits sever then Closes minecraft

### ISSUE THREAD

**Issue by Slowfudgeballs** [Wurst-Imperium/Wurst-Client#92]
when joining specific servers it will close minecraft in like a split second

**Comment by GlitchHead** [comment]
example ip?

**Comment by OMGchangeMYusername** [comment]
what is that supposed to mean O_o
is it like you can still play but minecraft isn't open?

**Comment by Alexander01998** [comment]
More information required. See above comments.

**Comment by Slowfudgeballs** [comment]
I'll give you the specific in when I get back from school

**Comment by Slowfudgeballs** [comment]
No it closes and exits in less than a second

**Comment by Slowfudgeballs** [comment]
It doesn't happend when I fist join it happens when I play it for a wile then I can never play a gain with that client

**Comment by Alexander01998** [comment]
> It doesn't happend when I fist join it happens when I play it for a wile then I can never play a gain with that client

Server IP???
