### ISSUE TITLE
Koby-Klient

### ISSUE THREAD

**Issue by ICouldntUseMyRealNameSoIHaveThis** [Wurst-Imperium/Wurst-Client#920]
Link to the website/download: koby-klient.ga
http://gyazo.com/9a5b2785042d839aca608e25eebdc395
Too bad the creator can't start off with a unique client :(
It's not much a concern, though.

**Comment by GummiBoat** [comment]
Well, that's a shame, but there are always some people that try to steal other peoples work. Just ignore them and they won't get any attention at all. BTW, he didn't even TRIED to change it really. ![](http://puu.sh/ikw49/0f0eb4dcbd.png)

**Comment by Nitrogen-Dioxide** [comment]
This not the worst way to steal the wurst code, we need to be afraid about other clients that copy paste code from here, without giving any credit.

**Comment by Alexander01998** [comment]
It's technically illegal, as he didn't make that client open source. (read the [license](https://www.mozilla.org/MPL/2.0/) for details)
But as @ICouldntUseMyRealNameSoIHaveThis said,

> It's not much a concern, though.

**Comment by OMGchangeMYusername** [comment]
Invalid,with respect :)
