### ISSUE TITLE
Can I make custom auto build???

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#921]

**Comment by GummiBoat** [comment]
Yes, but it is complicated. There is a file called "autobild_custom" in your .minecraft/wurst folder. Everything is explained in detail there.

**Comment by billyoz** [comment]
i dont found it, can you send me the file??

**Comment by billyoz** [comment]
And Why AutoBuild Doesn't work in multiplayer??

**Comment by GummiBoat** [comment]
[AutoBild-File Download Link](https://mega.co.nz/#!gkVyFAKa!qkUQZZkf2499nhTgzpGsf408m7O15QGgJPSTgX_rqb8)

Ah, just enable YesCheat+, mostly it doesn't work properly because of NoCheat Plugins.

**Comment by Alexander01998** [comment]
AutoBuild templates are JSON files that are saved in the `.minecraft\wurst\autobuild` folder.

If you are familiar with JSON, read #245 for details on how to make templates. If you are not familiar with JSON, you can download templates that other people have made at https://www.wurst-client.tk/downloads/autobuild/.

**Comment by billyoz** [comment]
thx for help
