### ISSUE TITLE
Remove all friends

### ISSUE THREAD

**Issue by ekyl** [Wurst-Imperium/Wurst-Client#922]
I'd like to see a feature that lets you remove all of your friends. I think this would be very easy to implement...

**Comment by OMGchangeMYusername** [comment]
First Duplicate Of #1 Ever!
I think this guy needs reward xD

**Comment by GummiBoat** [comment]
@OMGchangeMYusername :trophy: <- is this enough?

Please search for your matter the next time, before you open a new issue.
![](http://puu.sh/ikCE3/96754c0e34.png)
