### ISSUE TITLE
.vanish command (Creative mode)

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#924]
A command (for creative mode) to get Invisibility effect with Hidden Particles

If it is not possible to apply this effect in gamemode, its possible to get a Potion with this effect:

give @p minecraft:potion 1 8206 {CustomPotionEffects:[{Id:14,Amplifier:2,Duration:1200,ShowParticles:0b}]} 

=)

**Comment by GummiBoat** [comment]
Maybe being able to give yourself every effect generally (with or without particles) would be kinda cool... especially for people that don't have access to the /effect command. Maybe something like .effect <effect name/effect id> <amplifier> <duration> <particles>... dunno, but maybe that's a little too much.

Giving custom potions would be possible through #342 tho.
