### ISSUE TITLE
.switch command

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#925]
.switch command would be used to switch from premium/cracked accounts.
Here is an example syntax
.switch username password
Cracked:
.switch username
If there is no password it will be cracked. It will just automatically login if cracked server will kick like normal. This will be easy in game switching of accounts.

**Comment by Alexander01998** [comment]
I don't want people to accidentally post their password in the chat.

**Comment by scriptinator** [comment]
With 2.0 you could have text fields and people put passwords in a text field. And .switch could toggle a text field.
