### ISSUE TITLE
Idea for better .vclip

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#928]
Is it possible to add teleport forward & backward, left & right in .vclip???

.vclip f5
.vclip b5
.vclip l5
.vclip r5
?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Well the v in vclip stand for vertical (But you'd be like "no shit Sherlock")
Maybe an .hclip? I don't know. But I really like your idea.

**Comment by GummiBoat** [comment]
.tp works with relative coordinates.

**Comment by Alexander01998** [comment]
Teleporting through walls is only possible vertically.
For normal teleportation, you can use `.tp` as mentioned by @GummiBoat.
