### ISSUE TITLE
I dont even know how this guy did this

### ISSUE THREAD

**Issue by kristian2830** [Wurst-Imperium/Wurst-Client#930]
https://www.youtube.com/watch?v=dXHAgwlSvck just watch it

**Comment by GummiBoat** [comment]
He is using a (probably self written) plugin. It's simple as that.

**Comment by scriptinator** [comment]
This is not a forum nor does this have anything to do with wurst. Invalid

**Comment by Alexander01998** [comment]
^^^^^
