### ISSUE TITLE
I can't join  a game when i use a alt it says internal exception and java.lang.NullPointerException 

### ISSUE THREAD

**Issue by minecraftYoutuber** [Wurst-Imperium/Wurst-Client#931]

**Comment by scriptinator** [comment]
Please post whole error. If it is a timeout exception it is a problem with the server

**Comment by minecraftYoutuber** [comment]
ok

**Comment by minecraftYoutuber** [comment]
java.lang.NullPointerException

**Comment by Alexander01998** [comment]
You are probably trying to use a cracked alt on a premium server. This can only be done with premium alts.

**Comment by minecraftYoutuber** [comment]
they all say cracked

**Comment by gruenwald32** [comment]
Dude do you know what a piece of shit you are?
I don't want to say that you are gay but... you are gay
so i wonder how you where born?
maybe like you get your pc,accidentally on a golf course.
So please please fuck youre mom fuck youre sis fuck your dog and fuck you.
FUCK FUCK FUCK FUCK FUCK FUCK FUCK

Yours Adolf Hitler
Sig heil over and out
