### ISSUE TITLE
BUCK!!111!! Wen i plai minecraft everything is cubi

### ISSUE THREAD

**Issue by gruenwald32** [Wurst-Imperium/Wurst-Client#933]

**Comment by gruenwald32** [comment]
please help

**Comment by Alexander01998** [comment]
Lass stecken, Olli.

**Comment by gruenwald32** [comment]
im not doof

**Comment by gruenwald32** [comment]
afold riddler

**Comment by gruenwald32** [comment]
zani

**Comment by gruenwald32** [comment]
schick beil

**Comment by scriptinator** [comment]
You kinda are it doesn't take a genius the figure out Minecraft is all cubes. Plus this is not a forum nor does this have anything to do with wurst, if you need help with something not wurst but Minecraft related go to the Minecraft forum

**Comment by OMGchangeMYusername** [comment]
**whishpering to @scriptinator** This guy knows Alexander and he does some jokes xD

**Comment by scriptinator** [comment]
Whispering to OMGCHANGENYUSERNAME Oh lol xD I didn't mean it

**Comment by Alexander01998** [comment]
*Whispering to @gruenwald32:* Ey Olli, die reden über dich.
