### ISSUE TITLE
Question over NBT Editor

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#935]
Will a nbt editor added in Wurst 2.0?

**Comment by Alexander01998** [comment]
STOP IT!

**Comment by OMGchangeMYusername** [comment]
it must be hard to deal with idiots..
**not like i'm saying anyone is idiot here**

**Comment by Alexander01998** [comment]
> it must be hard to deal with idiots..

*Let me tell you a little secret...*
If someone is an idiot, it's their problem, not mine. And because it's not my problem, I don't to care about it. I don't try to fix other people's problems.

So that's how I deal with idiots, by not dealing with them.

**Comment by ravenje** [comment]
I just want to know if NBT editor or .Give command will added in wust in the future :/

**Comment by GummiBoat** [comment]
Look at #342. The Label is "Confirmed", so it will be added.

**Comment by ravenje** [comment]
a ok, sorry
