### ISSUE TITLE
can you add the old x-ray???and Nametags large setting??

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#936]

**Comment by billyoz** [comment]
Please Add Nametags can show mob name too

**Comment by WurstContributer** [comment]
More info required

**Comment by WurstContributer** [comment]
There is a option to make nametags large and wtf is the old xray

**Comment by Alexander01998** [comment]
Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.

**Comment by OMGchangeMYusername** [comment]
> Wurst for Minecraft 1.7.X had opacity X-Ray, but Minecraft 1.8 broke it. - Alexander01998

^^ i assume that's what he's talking about

And i think he's talking about the Nametags scale,that there should be some sort of a slider to it where you can make them larger/smaller.
(It renders the nametags from the farthest place possible but what changes is thier size on your screen)

**Comment by WurstContributer** [comment]
@OMGchangeMYusername  whats the point of having tiny nametags xD
