### ISSUE TITLE
Wurst 2.0 Theme

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#938]
Wurst 2.0 should not look the same. I made a Wurst 2.0 Logo in [Material Theme](https://www.google.com/design/spec/material-design/introduction.html).
![](http://imgh.us/wurst.svg)
Note: i DON'T want credits.

**Comment by OMGchangeMYusername** [comment]
This one is too simple,anyone could make it.
look up the original one to see the difference,the original is somehow more 3D and looks so Wurst-ish.

**Comment by Spassvogelw** [comment]
I like it. In my opinion it´s better than the 3D one

**Comment by OMGchangeMYusername** [comment]
> Wurst 2.0 should not look the same.

I agree! not the logo but the whole GUI should be something else.
i actually like that thing @orcunegeacar made
![sassy model](https://cloud.githubusercontent.com/assets/10786571/8144728/474d6438-11f4-11e5-9048-0f01722ed93f.png)
Could you please do something similar? you don't need to change the logo but change how the GUI looks like a little bit.
