### ISSUE TITLE
'§' button for books

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#939]
I now, i can copy & paste the § symbol into books, but can you add a [§] button to books?

**Comment by GummiBoat** [comment]
Because pressing two buttons (Ctrl+V) is so much harder than moving the mouse over to a §-button. Seriously.. I don't think this is necessary.

**Comment by ravenje** [comment]
Yes, but no a bed idea, or?

**Comment by OMGchangeMYusername** [comment]
i don't quite understand how this actually works..
can you guys explain how this symbol actually works?

**Comment by GummiBoat** [comment]
@OMGchangeMYusername Read [this article](http://minecraft.gamepedia.com/Formatting_codes).

**Comment by OMGchangeMYusername** [comment]
hmm.. then the mod should be something like colored buttons,if you want a certain color,it automatically types the symbol followed by the number or the letter for that color :+1:

**Comment by eveythingistaken** [comment]
@GummiBoat the long part is obviously not clicking 2 buttons. It's finding the symbol then copying it.

**Comment by OMGchangeMYusername** [comment]
The symbol can be simply be typed using `Alt`+`2``1`**using the number pad.**
but it can't be done in minecraft books anyway,so you might open a text file and try typing it.

although it's not actually long at all,i agree to this if it was in the form of buttons or choices like if i want **bold** i can click on it and it'll type `§l` instantly,should be awesome.

**Comment by Alexander01998** [comment]
> The symbol can be simply be typed using Alt+21using the number pad.

On a European keyboard, you can press <kbd>Shift + 3</kbd>.

**Comment by eveythingistaken** [comment]
On mac you can type `Alt + 3`
