### ISSUE TITLE
Accidentally deleted every key binding

### ISSUE THREAD

**Issue by leledragon1354** [Wurst-Imperium/Wurst-Client#940]
i dont care about the other key bindings the only problem is, i deleted the key binding for opening the hacked client menu, can someone tell me the command to open it?

**Comment by WurstContributer** [comment]
*Esc>Wurst Options>Keybinds>Add Keybind>Click add keybind>Set key to LCTRL>.t clickgui

**Comment by leledragon1354** [comment]
Thank you very much
