### ISSUE TITLE
Symbol Speak

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#941]
A mod, they all "a b c d e f g h i j k l m n o p q r s t u v w x y z" with
"ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓟⓞⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩ"
and all
":D :) =)" with ☻ ☺ シ

**Comment by scriptinator** [comment]
Minecraft cannot render these

**Comment by ravenje** [comment]
Wrong, copy & paste it!

**Comment by GummiBoat** [comment]
And once we're at it, maybe just make 1337 speak an option too. would be funny.

**Comment by mcccs** [comment]
uʍop ǝpısdn puɐ

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Suggestions
Pirate: Speak like a pirate
Faggot: Speak Like You Are From 9gag

:D

**Comment by OMGchangeMYusername** [comment]
I don't know if i should open an issue for this,but can you please add a Yes-swear mod?
when i say "fuck you" ofcourse that would be blocked on most of the servers..
i want it so it uses symbols for censoring or bubbles for the swear word only :grinning:

**Comment by GlitchHead** [comment]
this will take spamming to a whole new level.

**Comment by GlitchHead** [comment]
paste this in minecraft it looks awesome.
```
ａ ｂ ｃ ｄ ｅ ｆ ｇ ｈ ｉ ｊ ｋ ｌ ｍ ｎ ｏ ｐ ｑ ｒ ｓ ｔ ｕ ｖ ｗ ｘ ｙ ｚ
```

**Comment by pokeball99** [comment]
so,is this just going to be just bubble speak,or just a bunch of custom letters @Alexander01998?

**Comment by Orcunegeacar** [comment]
http://www.sekillinickyazma.org/ It's Turkish (and old) website but it's cool.
