### ISSUE TITLE
Cannot turn off glide and glide is too fast

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#947]
```html
.t glide on
```
i 10 times used this script , then i glid but it was too fast. Then i retyped this script it was much faster. Then
```
.t glide off
```
but did'nt work

**Comment by mcccs** [comment]
Confirm: http://i.imgur.com/CXhbEDD.gifv

**Comment by Nitrogen-Dioxide** [comment]
This happens with any mod. It is caused because when you type the ".t (mod) on", it will ignore if the target mod is already enabled, adding "multi listeners" to them sometimes.
