### ISSUE TITLE
ProphuntESP

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#953]
So how does it work?

From my understanding it detects the FallingSandEntity and put a box around it.

**Comment by GummiBoat** [comment]
That's not quite correct, it's checking all loaded entities and then checks if it is a "living" one and if it's invisible and then puts a box around it.

**Comment by WurstContributer** [comment]
Oh Ok

**Comment by WurstContributer** [comment]
Whoops

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
1. Turn on PropHuntESP.
2. When you find a hider, turn it off. If it's a flower pot, stay there for the next step. If not, kill the hider and move on to find a flower pot.
3. Turn on PropHuntESP AND TrueSight. You should see a baby chicken.

I think every block has its own animal, correct me if I'm wrong.

**Comment by WurstContributer** [comment]
This is how Block hunt on mineplex works
1. When moving there is a falling sand entity following you disgused as a block
2. When in solid form The sand entity stays and a block is placed
This is how Block hunt on HiveMC works 
1. Same
2. Sand ent dies and block is placed

**Comment by Alexander01998** [comment]
Mineplex uses invisible baby chicken, other servers use other small mobs.
