### ISSUE TITLE
MovementBot

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#954]
A Bot mod, that save what the player do (commands / clicks / chat messages / Moves / Build)
and do this again & again

that would useful for Autobild a complete house or Custom mineing ways

Like spammer, but for Movements
+ a folder to save movement files

Or its possible to add AutoBuild houses
(First copy a house to a chematic and let wurst build it Block by Block, like a 3d Printer)

I do not think it added but it is in my opinion a good idea and it is indeed possibly Added

**Comment by Alexander01998** [comment]
Duplicate: #817

**Comment by ravenje** [comment]
o sorry :/
