### ISSUE TITLE
.t xray isnt a command?

### ISSUE THREAD

**Issue by SaintsBoss** [Wurst-Imperium/Wurst-Client#956]
so I know there is an xray, but I dont know the command for it. I accidentally changed my x key to blink, but now I want xray to be there instead. I bind .t xray to x, but it says it isnt a command. What is the command for xray?

**Comment by OMGchangeMYusername** [comment]
Yes it isn't a command,since the actualy name is X-Ray.
`.t X-Ray` should work perfectly.

And btw,why is it named "X-Wurst" in the arraylist while the command and the mod in the ClickGUI are named "X-Ray",you might want to change it or make both X-Wurst or X-Ray work anyway.

**Comment by Alexander01998** [comment]
> And btw,why is it named "X-Wurst" in the arraylist while the command and the mod in the ClickGUI are named "X-Ray",you might want to change it or make both X-Wurst or X-Ray work anyway.

EasterEgg :egg:
