### ISSUE TITLE
Criticals are not working!

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#957]
I enabled criticals mod and tried it out, but I don't get any criticals and no critical star-effects are shown?

I think it's caused by something in the doCritical method:

```java
thePlayer.motionY = 0.1F;
thePlayer.fallDistance = 0.1F;
thePlayer.onGround = false;
```

I cant myself actually see whats wrong in the code?

Please fix it!

**Comment by OMGchangeMYusername** [comment]
Just tried it on singlplayer,it doesn't show the particles for criticals,and i think it's actually not working too.

**Comment by Murplyx** [comment]
Wow that was a fast respond! Do you have your own client?

**Comment by eveythingistaken** [comment]
Make sure your particles are turned on. 
Options > video settings > particles 👍

**Comment by Murplyx** [comment]
I have particles on all?

**Comment by Alexander01998** [comment]
Working fine.

![output_fjuwyb](https://cloud.githubusercontent.com/assets/10100202/8168634/6cfcbfc4-13a4-11e5-9600-59602d153a4b.gif)

**Comment by OMGchangeMYusername** [comment]
hmm.. idk why but it didn't seem like it O.o
maybe it isn't compatible with ordinary clicking?and compatible with Killaura?

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
When using criticals, DO NOT jump.
Minecraft criticals (without hacks) require you to jump and hit. This will make a critical hit.
So basically when you jump and critical hit, you are basically double jumping, in a way. This triggers NCP so it makes criticals not work.
