### ISSUE TITLE
AntiFireball

### ISSUE THREAD

**Issue by WurstContributor** [Wurst-Imperium/Wurst-Client#959]
Deflects all fireballs

**Comment by mcccs** [comment]
Trajectories makes him sick.

**Comment by GummiBoat** [comment]
Trajectories are not needed for this one. Ghast-Fireballs are Entities. You just need to send an attack-command to that entity and it gets "reflected".

**Comment by WurstContributer** [comment]
@GummiBoat So does that mean that you can deflect a fireball out of the 6 blocks range?

**Comment by GummiBoat** [comment]
No, it needs to be in your hitting range.

**Comment by WurstContributer** [comment]
Oh ok ;)
