### ISSUE TITLE
AutoMine doesn't continue after opening&closing a GUI

### ISSUE THREAD

**Issue by GummiBoat** [Wurst-Imperium/Wurst-Client#961]
Steps to Reproduce:

1) Enable AutoMine (.t AutoMine)
2) Open ANY GUI (Inventory, Chat, ClickGUI, ...) and close it
3) AutoMine is stopped and you need to click your Action Key once to continue it.

Also, if you activate AutoMine via ClickGUI, the same thing occurs.

PLS FIX ASAP & **INSTALL OPTIFINE**!!!!1!!!1one. Kappa.

**Comment by OMGchangeMYusername** [comment]
if your report is right i hope it get's fixed "ASAP" xD
But this can be invalid though :stuck_out_tongue_winking_eye: Optifine has been rejected several times.
Please use the search function next time :P

**Comment by GummiBoat** [comment]
ERMARGERD (╯°□°）╯︵ ┻━┻

**Comment by WurstContributer** [comment]
ERMAHGERD (╯°□°）╯︵ ┻━┻
