### ISSUE TITLE
Glitche Through Doors

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#964]
Hi, I Just Think About Glitching Through The Doors Or Trapped Doors ...
Is There Any Way To Glitch Game With This Client And Move Through Doors Or Trapped Doors
Cus I See Many Peoples Do This Trick But I Dont See Any Useful Tut On Internet ,

Thanks

**Comment by GummiBoat** [comment]
Through Doors should be possible with "Phase". (which only works on NoCheat+ Servers). Through trapdoors with ".vclip", but that doesn't work on NoCheat+ Servers.
