### ISSUE TITLE
Bug error crash with action

### ISSUE THREAD

**Issue by hugotrak** [Wurst-Imperium/Wurst-Client#965]
hello, i need help with a bug. when i recon a video with action and wurst, the game will crash when record just minecraft screen.

**Comment by GummiBoat** [comment]
Okay, I assume, that "Action" is a recording programm. Recording Minecraft sure is a little bit stressful for your computer. So, first you should check, if you can record the normal Minecraft. If you can't do that, then this problem has nothing to do with Wurst.

Anyways, you probably need to increase the RAM you give these Programms and decrease the quality of your Minecraft graphics. Close everything in the background, that you don't need. (Steam, Skype, your browser,...). If it still does not work, try to record any other programm or even your desktop. If that doesn't work, or it laggs really hard, then your computer probably isn't able to handle recording properly.

**Comment by Alexander01998** [comment]
Crashes cannot be fixed without the crash log.

Please review the [guidelines for contributing](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) for instructions on how to properly include a crash log in an Issue.
