### ISSUE TITLE
SignCrash

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#967]
Signcrash is a feature in the Wolfram client and what it does is basically you enable it, craft a sign, place the sign then anyone near it will crash.

**Comment by GummiBoat** [comment]
I can confirm that. The string the Sign contains is too long, (32789 bytes, the maximum minecraft can handle is 32787). But Spigot 1.8.7 fixed it, and there are some plugins, that fix that too.

**Comment by mcccs** [comment]
CrashSign is better

**Comment by mcccs** [comment]
Im sure its possible. It's in wolfram

**Comment by mcccs** [comment]
@Alexander01998 Why don't you add 2.2 Milestone to this? :) Plss

**Comment by Eyremba** [comment]
@Alexander01998 please make Wurst ressistant to overloaded signs (Signs with more chars than allowed, for example 10.000). This is one of the last steps to get a SignCrasher working.

**Comment by nerdtron123** [comment]
so?
