### ISSUE TITLE
How Do you use  the  OP-Sign the CrashChest and the CrashItem?

### ISSUE THREAD

**Issue by iTurtelzz** [Wurst-Imperium/Wurst-Client#969]

**Comment by GummiBoat** [comment]
OP-Sign: You need creative Mode. Give yourself the Sign. Take it from the shoes-slot. Place it. Rightclick it. Done. (Only works on Vanilla 1.8.5 and versions before that.)

CrashChest: You need Creative Mode. Give yourself one Chest. Copy it and throw the Stacks away immediately into another ones inventory. He Crashes after a few Stacks.

CrashItem: You need a Nametag and Creative Mode. It gets renamed. Rename any mob with it and the server crashes. Only on Vanilla 1.8.5 and versions before that.

**Comment by iTurtelzz** [comment]
so i cant craft the things in survival world like the sign i craft it and place it and done?

**Comment by GummiBoat** [comment]
No.

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
If you're using Helios, the OP-Sign works by typing into the command box: /OPSIGN (command here)

**Comment by Dylanlay02PvP** [comment]
Hey what do you mean about the shoes slot?

**Comment by GummiBoat** [comment]
The slot, where the shoes go, in creative mode. (At the Chest-Icon at the bottom right of the creative inventory, is your normal player inventory. Around the picture of your Avatar are your Armor Slots.)

**Comment by lol1336** [comment]
How do u copy and pate it?

**Comment by Alexander01998** [comment]
> How do u copy and paste it?

Click on it with the mouse wheel. That will give you a whole stack of copies.

**Comment by lol1336** [comment]
thanks

**Comment by lol1336** [comment]
the force op sign dosen't work for me :( When I place it, it shows me the text thing that you can put on the siggn, should I not put anything or what should Ido

**Comment by GummiBoat** [comment]
>(Only works on Vanilla 1.8.5 and versions before that.)

**Comment by lol1336** [comment]
Dosen't work for me, what do u have to do?

**Comment by OMGchangeMYusername** [comment]
What version is the server you're on? if it is using 1.8.5 or more,you can't get it to work.
+ some servers can block it with Bukkit and Spigot..

**Comment by lol1336** [comment]
I tried it on servers like  "c4.lionhost.org:25590" on creative and it goes sign registered then nothing happens when I click it, or in other servers it tells me to write something on the sign....

**Comment by lol1336** [comment]
the server is 1.8.0

**Comment by xXGamMeRZzxX1221** [comment]
the OP-Sign wont work pls helpz
