### ISSUE TITLE
Letter/numbers/unicode carertor for auto build

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client#970]
And have it to where it has a text field to put it in

**Comment by GummiBoat** [comment]
I don't know what a carertor is, but I assume, that you want to be able, to type in a Letter and AutoBuild builds that for you?

Would be cool, but I think it's a little hard to implement..

**Comment by pokeball99** [comment]
Yea,I suck at spelling (and u have it pretty much spot on,just rushed the issue)

**Comment by Alexander01998** [comment]
All letters and numbers would be ~60 AutoBuild templates. All Unicode characters would be about 6 million. Not to mention that only ~20 templates can fit onto the screen.

**Comment by pokeball99** [comment]
When then not the unicode then,just the numbers and letters,and it wouldn't be in the autobuild drop down,it would be mostly hidden,just have it as a text field then it builds ot
