### ISSUE TITLE
Arena Brawl Hack?

### ISSUE THREAD

**Issue by MagicDitto** [Wurst-Imperium/Wurst-Client#971]
Wondering on how to use the Arena Brawl option for the server Hypixel. Please help!

![arena brawl option](https://cloud.githubusercontent.com/assets/12927433/8196315/9f4dd440-1458-11e5-909f-04b234dfc5bb.PNG)
![arena option](https://cloud.githubusercontent.com/assets/12927433/8196316/a127bf2e-1458-11e5-8698-443d7f724f2c.PNG)

**Comment by GummiBoat** [comment]
https://old.wurst-client.tk/wiki/mods/arenabrawl

Duplicate: #741

Next time please search the Issues for your matter, before opening a new one.
