### ISSUE TITLE
Flat Nuker doesn't ignore Liquids

### ISSUE THREAD

**Issue by GummiBoat** [Wurst-Imperium/Wurst-Client#972]
Steps to reproduce:

1) Stay in a field with water or lava on the same Y coordinate as you
2) Activate FlatNuker
3) After Nuker reaches the Liquids, it tries to break them. (The "Nuker Box" is appearing really slow.)

Proof:
![](http://puu.sh/irBrN/bb1dcb6d0b.jpg)

**Comment by ICouldntUseMyRealNameSoIHaveThis** [comment]
Here is 3 screenshots taken within 4-5 seconds:

![](http://i.gyazo.com/930776c0ddc12ab5cde82327411a9d03.png)

![](http://i.gyazo.com/b28416b5e38dd1b258712097d4869692.png)

![](http://i.gyazo.com/cb5ce40df2e8f7e9ad8a242d0f843577.png)

**Comment by Alexander01998** [comment]
That's not a bug. Nuker and FlatNuker are supposed to target all blocks, including water.
