### ISSUE TITLE
NoHurtcam doesn't react on Poison Damage

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client#973]
Removes that annoying effect
![](http://i.imgur.com/KsFbPjj.gif)

**Comment by GummiBoat** [comment]
You should change the title to "NoHurtcam doesn't react on Poison Damage". Because it should be covered by the same mod.

**Comment by Alexander01998** [comment]
You don't have NoHurtcam enabled in that GIF.

**Comment by GummiBoat** [comment]
I tried it out and can confirm the bug, he forgot to activate it in the gif. Give yourself a bit hunger, activate NoHurtcam and eat a Pufferfish, or poison yourself. It's not working on Poison.

**Comment by mcccs** [comment]
@Alexander01998 fixed it ![](http://i.imgur.com/7g1siAH.gif)

**Comment by mcccs** [comment]
tested, it doesn't work on zombie damage, .damage 1 too

**Comment by mcccs** [comment]
![](http://i.imgur.com/hTXpBgD.gif)

**Comment by mcccs** [comment]
@Alexander01998 really DOES NOT work
