### ISSUE TITLE
Are criticals supposed to work like they do?

### ISSUE THREAD

**Issue by Murplyx** [Wurst-Imperium/Wurst-Client#974]
If you turn criticals-mod on and turn all other mods off, and find a mob and attack it once, there will be no critical. Is the criticals-mod supposed to work like that?

**Comment by Alexander01998** [comment]
As requested, here is another GIF that doesn't use Killaura.
Criticals works exactly like it does in the GIF and is supposed to work exactly like that.

![](https://cloud.githubusercontent.com/assets/10100202/8215060/d0453f86-152d-11e5-9244-fe493c41146e.gif)
