### ISSUE TITLE
About the AutoSoup hack Deny... 

### ISSUE THREAD

**Issue by MorganPlaysMC** [Wurst-Imperium/Wurst-Client#98]
How about thinking about people who DO play kitpvp???? :sweat_smile:

**Comment by MorganPlaysMC** [comment]
:sweat_smile:

**Comment by MorganPlaysMC** [comment]
But seriously... What about the people who still play kitpvp with the SoupPVP plugin????

**Comment by Alexander01998** [comment]
How about no?

**Comment by MorganPlaysMC** [comment]
thanks anyway...... :disappointed:
