### ISSUE TITLE
ChestESP render glitch

### ISSUE THREAD

**Issue by SaintsBoss** [Wurst-Imperium/Wurst-Client#980]
So if you have ChestESP enabled, and you are above the clouds, your hand and hotbar will turn black. If you hold something it will be its regular color, and when you go back below the clouds it will go back to your skin, but I think it is annoying when I am playing minigames or something above the clouds

![2015-06-18_09 53 42](https://cloud.githubusercontent.com/assets/12749127/8234174/e841068e-159f-11e5-905d-02c346f66bce.png)

![2015-06-18_09 53 40](https://cloud.githubusercontent.com/assets/12749127/8234184/f7a07376-159f-11e5-8baf-03e8271a8c52.png)

**Comment by GummiBoat** [comment]
Duplicate #568 

Please search the Issues for your matter before opening a new one.
