### ISSUE TITLE
IP Player, join bot, Server IP and More ?

### ISSUE THREAD

**Issue by Mr9Zurby** [Wurst-Imperium/Wurst-Client#982]
Hi!
Is it possible to find a player ip like with the command / whois ? 
![wois](https://cloud.githubusercontent.com/assets/12958636/8243405/17984862-1617-11e5-97a6-09902c272480.jpg)
Or again create the "Frames Windows" like on "weepCraft" 
![frames](https://cloud.githubusercontent.com/assets/12958636/8243363/ae1480e0-1616-11e5-8f27-fdc26f7c1167.PNG)
Or include a join bot like "Gravity Bot", "Death Bot" ok again "Spam Bot".
![bot](https://cloud.githubusercontent.com/assets/12958636/8243414/257a892c-1617-11e5-9dd8-7e01d0af5bbb.PNG)

And all that for free ?

Thanks you for Reading
and I'm Sorry for my English, 
(im a french player !)

**Comment by WurstContributer** [comment]
Ip finder Is Duplicate:#737 And not possible
