### ISSUE TITLE
Crash log issue

### ISSUE THREAD

**Issue by WurstContributer** [Wurst-Imperium/Wurst-Client#984]
When my client crashes, Sometimes it doesn't generate a crash log

**Comment by GummiBoat** [comment]
That depends mostly on how your Client crashes. If your Window freezes and you have to forcefully eliminate the task, it won't go back to the launcher. If it just crashes while an ingame Error occured, it will.

**Comment by Alexander01998** [comment]
You can change the settings in the Minecraft launcher so that it always shows the crash log.

![image](https://cloud.githubusercontent.com/assets/10100202/8253215/e991c44e-168d-11e5-874d-a0e3e002ab78.png)

**Comment by WurstContributer** [comment]
Ok Thx

**Comment by WurstContributer** [comment]
Question tag PLEASE?!
