### ISSUE TITLE
Why BookHack and Opsign Doesn't work in bukkit??

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#989]

**Comment by mcccs** [comment]
Maybe They updated to a new patched version

**Comment by billyoz** [comment]
Thx

**Comment by billyoz** [comment]
how to make it work??

**Comment by GummiBoat** [comment]
If something is patched, or not even possible in Bukkit, there is no way to make it work. You have to search a server with an older Bukkit Version.
