### ISSUE TITLE
New x ray!!

### ISSUE THREAD

**Issue by Jinx103** [Wurst-Imperium/Wurst-Client#99]
Some severs block X ray like this one here http://s12.postimg.org/a4k4a13t9/2015_02_27_10_23_15.png
So how they block x ray is that any block that you cant see looks different then it actually is so one way that you guy's could get around this is buy making blocks of importance highlighted like how you did with the items that you can see through walls. You guys should all so make it so when a block is highlighted the color that highlights the block should be the color of the item that you get from the block. I don't know if this will work to get past the x ray block but it doesn't hurt to try. I would call this (clear X ray) if it works and you guys put it in the client. ps you cant make normal blocks clear or it will mess it up. look at this pic http://s27.postimg.org/tlt1ms4s3/2015_02_27_10_46_18.png so a imagine this that the Block is highlighted right now in the pic so i would mine to it and get the block. this was just to give you a visual effect of what I'm thinking of. So hopefully you guys could pull this off and add it to the client.

**Comment by MorganPlaysMC** [comment]
Arent all those ores not actually there?

**Comment by Jinx103** [comment]
yeah they aren't there

**Comment by MorganPlaysMC** [comment]
So servers blocked Xray huh? that sucks

**Comment by Jinx103** [comment]
yea it does :'(

**Comment by MorganPlaysMC** [comment]
No wonder when i was editing the xray i saw the blocks i wanted to see but it was all just cobble.. :disappointed:

**Comment by Alexander01998** [comment]
Minecraft doesn't work that way. There is no way to know whether or not a block is real or it's one of the fake blocks placed by the Anti-X-Ray plugin.

Can't explain it further right now, too busy.

**Comment by Jinx103** [comment]
ooo ok thx any way
