### ISSUE TITLE
NBT-Editing

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#991]
Hi, Thx For The New Update For Wurst :smile: Very Good Update 

My Suggest Is To NBT-Edit Items Like "Add Lore - Custom Enchants - Custom Name ... (THIS ONLY WORK ON CREATIVE)"

I Have Know A Mod That Do This But With Forge : All U Want 

It Just Need A New GUI or Program Like (Spammer - Force OP Tools) OR A Command Like :

.give name/id CustomName CustomEnchant Lore Attributes
.give DiamondSword $aSword Sharpness_4,Unbreaking_5 $2KillerSword Damage_50

This Is Possible Cus In New Wurst , Wurst Can Create Potion , Chest , Tags That Have Edited NBT
And There Be Could Custom NBT

If This Feature Added To Future Wurst (v2.0) Will BE G00D

Thanks (Sorry If I Have Bad English)

**Comment by ravenje** [comment]
Duplicate https://github.com/Wurst-Imperium/Wurst-Client/issues/342
