### ISSUE TITLE
I CANT OPEN THE GUI WITH CTRL!

### ISSUE THREAD

**Issue by EASTON4554** [Wurst-Imperium/Wurst-Client#998]
When i download an older version of wurst, i click ctrl and the gui opens, when i download the 1.15 version, i cant open the gui with ctrl!

**Comment by GlitchHead** [comment]
goto keybind manager and set CTRL to .t clickgui

**Comment by mcccs** [comment]
Duplicate: #545 
Next time please search for your matter, before opening a new Issue.
![](https://camo.githubusercontent.com/15a01ae3b576e2776e9d2d5b752c0940fba6c3bd/687474703a2f2f7075752e73682f696b4345332f393637353463306533342e706e67)

**Comment by GummiBoat** [comment]
@mcccs That's mine! :disappointed:

**Comment by mcccs** [comment]
sorry, @GummiBoat next time i won't use it.

**Comment by GummiBoat** [comment]
It's okay, feel free to use it. ^^
