### ISSUE TITLE
x-Wurst (Xray) Doesnt work well

### ISSUE THREAD

**Issue by Enemyinsid3** [Wurst-Imperium/Wurst-Client#999]
The xray on this client doesn't work that well, or really stand up to other mods. When you enter a new chunk it doesn't load any ores. When it does load ores its just one ore and when you mine one it shows all the other.

**Comment by GummiBoat** [comment]
This hat nothing to do with the client. This is probably caused by an Anti-X-Ray Plugin on the Server you are Playing on. There is nothing that can bypass that.

**Comment by Alexander01998** [comment]
# *Duplicate: #247*
![](http://i.imgur.com/qJJQI0X.png)

**Comment by OMGchangeMYusername** [comment]
# *Duplicate: #247*
That is swaggy xD
@GummiBoat when did you use this? or make it?

**Comment by Alexander01998** [comment]
We just started a meme...

**Comment by GummiBoat** [comment]
@OMGchangeMYusername wut? No, i only made this one ![](https://camo.githubusercontent.com/15a01ae3b576e2776e9d2d5b752c0940fba6c3bd/687474703a2f2f7075752e73682f696b4345332f393637353463306533342e706e67)

But the new one has :heavy_dollar_sign:wag, indeed.
